import { s } from "./s.mjs";

const N = "Sentences";
const R = "Reading";
const W = "Writing";
const V = "Words";
const M = "Speaking & media";

export const ENGLISH_SEEDS = [
  s("english", N, "e-sentence-vs-fragment", "A sentence needs a complete job",
    "A finite verb and a subject doing something (or being something) usually make a clause that can stand. ‘Because the bus’ is a fragment.",
    "Any group of words with a capital and a full stop is a sentence.",
    "Find the verb that has tense. If the thought is unfinished (‘when the rain’), attach it or finish it.",
    "‘Wow!’ can be a minor sentence in speech. Academic writing still wants the full job most of the time."),
  s("english", N, "e-comma-splice", "A comma cannot weld two sentences",
    "‘The bell rang, we ran’ is a splice. You want a full stop, a semicolon, or a joining word.",
    "Commas are pauses, so any pause is a comma, and two sentences can share one.",
    "Spot two main clauses. Split, or add and/but/so, or use a semicolon if they are close cousins.",
    "A splice is not ‘a style’. Readers trip. So do markers."),
  s("english", N, "e-run-on", "A run-on is a pile-up, not enthusiasm",
    "Two or more main clauses with no legal join. Excitement is not a conjunction.",
    "Longer is smarter. Keep going with ‘and’ until the lungs fail.",
    "Cut, or subordinate one idea (‘after the bell rang, we ran’).",
    "A full stop is a kindness. So is a paragraph break."),
  s("english", N, "e-subject-verb", "The verb agrees with the subject, not the nearest noun",
    "‘The box of biscuits is’ — box is singular. ‘Biscuits’ is a decoy.",
    "Always match the verb to the last noun you typed.",
    "Underline the real subject. Ignore prepositional extras. Then pick is/are.",
    "‘Neither of the answers is’ treats neither as singular in many school styles. Check the style you were asked for."),
  s("english", N, "e-tense-shift", "Pick a time and stay unless you mean to jump",
    "A recount that hops past/present without a reason feels like a glitch, not a voice.",
    "Mix tenses so it sounds lively, like a trailer.",
    "Decide the home tense. Flashbacks get a clear signal. Instructions live in present or imperative.",
    "Historical present (‘Caesar crosses’) is a choice you commit to, not a slip."),
  s("english", N, "e-active-passive", "Passive hides the doer — sometimes on purpose",
    "‘The window was broken’ vs ‘Sam broke the window’. Science methods use passive to focus on the procedure; politics uses it to dodge blame.",
    "Passive is always wrong. Teachers said so in Year 4 forever.",
    "Ask: do we need the actor? If yes, put them in. If the object matters more, passive can be honest.",
    "‘Mistakes were made’ is a famous dodge. Name the maker when you can."),
  s("english", N, "e-modifier-dangle", "A dangling modifier attaches to the wrong head",
    "‘Running for the bus, the backpack bounced’ — the backpack was not running.",
    "Opening phrases are decoration. They attach to whichever noun is nearest by luck.",
    "Put the real actor right after the comma, or rewrite.",
    "‘While still in nappies, my family left Perth’ accuses the family of being in nappies. Move the baby."),
  s("english", N, "e-parallel", "Lists want the same grammatical clothes",
    "‘She likes hiking, to swim, and bicycles’ is a jumble. Make them all -ing, or all nouns, or all clauses.",
    "Variety in a list proves creativity. Grammar is optional in threes.",
    "Match form. Headings and slides need this even more than essays.",
    "‘We came, we saw, we conquered’ works because the clothes match."),
  s("english", N, "e-colon-list", "A colon introduces a payoff you already set up",
    "A complete clause, then a colon, then the list or the reveal. Do not colon after ‘such as’ as a reflex.",
    "Sprinkle colons because they look academic.",
    "Check the left side could stand as a sentence. Then pay it off.",
    "‘Bring:’ is a label. ‘Bring the following:’ is a clause. School styles differ; be consistent."),
  s("english", N, "e-apostrophe", "Apostrophes are ownership or missing letters, not extras",
    "cat’s = of the cat (or cat is). cats = more than one cat. cats’ = of the cats. Its = belonging to it; it’s = it is.",
    "Put an apostrophe in every word that ends with s, to be safe.",
    "Ask: plural, or possession, or contraction? ‘Its’ never takes an apostrophe for possession.",
    "1990s is a decade, not 1990’s unless you mean of the year 1990."),
  s("english", N, "e-semicolon-cousin", "A semicolon joins cousins, not strangers",
    "Two complete sentences that belong together: ‘The bus was late; we still made the bell.’",
    "A semicolon is a fancy comma you can drop anywhere.",
    "If a full stop would also work, a semicolon is a style choice for closeness. If a comma is illegal, do not ‘upgrade’ a splice with a random semicolon into a worse mess — actually a semicolon would fix a splice. Use it on purpose.",
    "Between list items that already have commas, semicolons are traffic police."),
  s("english", N, "e-clause-sub", "A subordinate clause cannot stand alone",
    "‘Although it rained’ wants a main clause. That is a dependent thought.",
    "Start with although/because/when and stop. It sounds deep.",
    "Attach it: ‘Although it rained, the match went on.’ Or drop the subordinator.",
    "Relative clauses (‘who spilled the milk’) modify a noun. They are not a new essay."),
  s("english", R, "e-infer-not-guess", "Inference is a trace plus a because",
    "The text does not say ‘she is angry’; the slammed locker and short answers do. You still need the evidence line.",
    "Inference means whatever you felt while reading, even if the page disagrees.",
    "Quote or point, then ‘this suggests… because…’. If you cannot because, you guessed.",
    "A film still is a text. Lighting can be evidence. ‘I just knew’ is not."),
  s("english", R, "e-main-idea", "The main idea is the spine, not the first sentence always",
    "Topic sentences help. Sometimes the spine is delayed. Details decorate; they are not the claim.",
    "The main idea is the longest sentence, because length is importance.",
    "Boil the paragraph to one clause. If a detail can leave and the clause survives, it was not the spine.",
    "A narrative’s ‘main idea’ might be a theme, not a topic sentence. Say which job you were asked to do."),
  s("english", R, "e-fact-opinion", "A fact can be checked; an opinion is a stance",
    "‘The hall holds 400’ vs ‘the hall is ugly’. Loaded words can smuggle opinion into a fact-shaped line.",
    "If it is in a newspaper it is a fact. If it is in a poem it is an opinion.",
    "Ask: what evidence would settle this? If none could, it is value or taste.",
    "‘Everyone knows’ is not a citation. Neither is ‘studies show’ with no study."),
  s("english", R, "e-audience-purpose", "Who is this for, and what is it trying to do",
    "A Year 4 safety poster and a senate submission can share a topic and not share a voice. Audience plus purpose choose the features.",
    "All writing is for ‘everyone’ and the purpose is ‘to inform’ forever.",
    "Name a specific reader and a verb: persuade, instruct, entertain, record. Then match features.",
    "A meme’s audience is a subculture. Missing that is how adults ‘explain’ it into dust."),
  s("english", R, "e-tone", "Tone is the attitude in the word choices",
    "Sarcastic, solemn, matey. Not the plot. A funeral speech in meme-speak is a tone crash unless that is the point.",
    "Tone means volume. Yell = serious.",
    "Circle loaded words and sentence length. That cluster is the tone.",
    "Irony is saying one thing to mean a tilt. If the reader misses it, the tone failed, not the reader’s moral worth."),
  s("english", R, "e-structure-shift", "A shift is a door in the text",
    "A volta in a sonnet, a ‘but’ paragraph, a cut in a film. Structure is not a box-tick of intro-body-conclusion only.",
    "Structure means five paragraphs, always, including in a play.",
    "Mark where the argument or mood turns. Ask what the turn does to the reader.",
    "A circular ending is a structure choice. So is a cliffhanger. Name it."),
  s("english", R, "e-compare-texts", "Comparison wants a lens, not two summaries glued",
    "Both texts, one idea: how they treat power, or endings, or a symbol. A+B summaries is two book reports.",
    "Write everything about text 1, then everything about text 2. Comparison will happen in the marker’s heart.",
    "Pair evidence. ‘While A does X, B does Y’ — then so what.",
    "A table of features can be a plan. It is not a paragraph."),
  s("english", R, "e-context", "Context is the world around the text, not a Wikipedia dump",
    "A wartime ration book next to a poem about cake. Use what changes the reading, then return to the words.",
    "Start every essay with the author’s full biography including their dog.",
    "Pick 1–2 context facts that unlock a line. If the line still means the same without it, cut the dump.",
    "Anachronistic ‘they would have had Twitter’ is not context. It is a time machine gag."),
  s("english", R, "e-unreliable", "An unreliable narrator is a designed leak",
    "They omit, boast, or fail to see. You catch them via other clues in the text, not via ‘I didn’t like them’.",
    "Villains are unreliable; heroes tell the truth. Always.",
    "Find a contradiction the text lets you see. That gap is the device.",
    "A diary can be sincere and wrong. Sincerity is not reliability."),
  s("english", R, "e-visual-text", "Images have grammar too",
    "Salience, vectors, colour, framing, demand vs offer gaze. A poster is not ‘just a picture’.",
    "Visual analysis is listing objects. ‘There is a dog. There is a flag.’",
    "Name a choice (close-up, saturation) and its effect on the viewer. Then link to purpose.",
    "A high angle can shrink a subject. It is a power shot, not a tall photographer."),
  s("english", R, "e-poetry-enjamb", "Enjambment is a run-on that is on purpose",
    "The sentence keeps going over the line break. The break is a breath or a trap, not a mistake.",
    "Every line ends with a full stop in proper poems.",
    "Read it twice: once with the breaks, once as grammar. The friction is the effect.",
    "A rhyme is not required for it to be poetry. Lineation still is a choice."),
  s("english", R, "e-theme-vs-topic", "A topic is a noun; a theme is a claim about it",
    "Topic: friendship. Theme: friendship can be a cover for control. If you only name the topic, you have not started.",
    "Theme is the subject of the book, like ‘war’ or ‘love’, and you stop.",
    "Finish the sentence: ‘This text suggests that…’ If you cannot, you are still in topic-land.",
    "A moral taped on the end (‘and so always be kind’) can be thinner than the text. Do not flatten."),
  s("english", W, "e-thesis", "A thesis is a contestable sentence",
    "It can be disagreed with. ‘This essay will discuss sharks’ is a table of contents, not a thesis.",
    "The thesis is the essay title copied into the first line.",
    "Make a claim about how/why, not just that the text exists. Preview the angle, not every paragraph.",
    "‘Shakespeare uses language’ is true and empty. ‘Shakespeare uses prose to drop Falstaff’s status’ can be fought."),
  s("english", W, "e-topic-sentence", "A body paragraph needs a job-one line",
    "The first sentence should say what this chunk proves. Quotes then work. A quote dump is not a paragraph.",
    "Start with a 40-word quotation so the marker knows you read.",
    "Claim, evidence, explanation, link. The quote is a brick, not the house.",
    "PEEL/TEEL are training wheels. The idea still has to be yours."),
  s("english", W, "e-quote-integrate", "A quotation is a passenger in your sentence",
    "Lead in, snip what you need, punctuate. A floating quote is a brick in the road.",
    "The longer the quote, the higher the mark.",
    "Use a short piece that actually shows the technique. Then unpack the words, not the plot around them.",
    "Ellipses are for cuts, not for mystery. Do not ‘…’ the useful verb."),
  s("english", W, "e-paragraph-unity", "One paragraph, one job",
    "If you wander into a new claim, break. White space is a tool.",
    "A page-long paragraph proves stamina.",
    "When the ‘also’ is a new spine, hit return. Check the first and last sentence still match.",
    "Dialogue in narrative can be short paragraphs. That is still unity of beat, not of essay-claim."),
  s("english", W, "e-concision", "Cut the throat-clearing",
    "‘In today’s society in this essay I will attempt to’ is fog. Start the claim.",
    "More prepositions and ‘very’ make it formal.",
    "Delete empty openers. Prefer a verb with a backbone. Read it aloud; if you gasp, cut.",
    "Nominalisations (‘the utilisation of’) can hide who did what. Sometimes science wants them. Your recount probably does not."),
  s("english", W, "e-register", "Register is the clothing of the situation",
    "A job email is not a snapchat. Slang can be precise in fiction and sloppy in a report.",
    "Always write like a judge, even to your friend about footy.",
    "Match audience. If you mix meme and statute without a reason, it reads as accidental.",
    "Jargon is a register. Define it once if the reader is outside the club."),
  s("english", W, "e-narrative-show", "Show is sensory and action; tell is a label",
    "‘She was angry’ tells. A slammed locker can show. You still need tell sometimes (time jumps, inner rules).",
    "Never tell. Only show. Even ‘it was Tuesday’ must be a metaphor.",
    "Pick the beats that earn a camera. Summarise the rest so the story moves.",
    "A whole page of weather before a door opens is stalling unless weather is the point."),
  s("english", W, "e-dialogue-punct", "Dialogue punctuation is a small machine",
    "New speaker, new line. Commas inside the quote when the tag follows, in standard school style.",
    "Put all talk in one paragraph with no marks so it feels realistic.",
    "Learn one style and keep it. Tags (‘she said’) are invisible on purpose; ‘she ejaculated thunderously’ is not a flex.",
    "Subtext: they do not say the thesis of the scene. If they do, it is on-the-nose."),
  s("english", W, "e-planning", "A plan is cheaper than a rewrite",
    "Five bullets of claims beat a beautiful first sentence that leads nowhere.",
    "Planning kills creativity. Real writers type into the void.",
    "List the points in order. If two points are the same, merge. If one is a new essay, cut it into a later piece.",
    "An exam plan can be 90 seconds. That still counts."),
  s("english", W, "e-editing-pass", "Editing is a different hat from drafting",
    "Draft for ideas. Edit for sense, then for sentences, then for ticks (spelling, quotes). One pass cannot do all jobs well.",
    "Spellcheck is editing. You are done.",
    "Read aloud. Search your pet words (‘very’, ‘aspects’). Check every quote against the text.",
    "A teacher’s rubric is an edit checklist. Use it before they do."),
  s("english", W, "e-referencing", "Credit is a trail, not a decoration",
    "Quote, paraphrase, and the idea you did not invent all want a trail. School styles (Harvard, APA) are machines — pick one.",
    "If you change two words, it is yours. No citation.",
    "Name the source at the point of use and in the list. URLs alone are a weak trail.",
    "AI paste without checking is still your submission. So is a copied paragraph from a mate."),
  s("english", V, "e-connotation", "Connotation is the cloud around a word",
    "Slim vs skinny vs scrawny. Denotation overlaps; the cloud does not. Propaganda lives in the cloud.",
    "Synonyms are identical. That is why the thesaurus exists — mash replace.",
    "Pick the cloud that matches tone. Read the sentence with a swapped synonym and listen.",
    "‘Settler’ and ‘invader’ can point at the same year with different clouds. History English cares."),
  s("english", V, "e-nominalisation", "Turning a verb into a noun packs and hides",
    "‘They decided’ → ‘the decision’. Useful in reports; foggy when nobody is left to blame.",
    "More nouns = more academic, always better.",
    "Use it to tighten method writing. Unpack it when you need an actor.",
    "‘The utilisation of’ can often be ‘using’. Try the verb first."),
  s("english", V, "e-figurative", "Metaphor says this is that; simile says like",
    "A metaphor does not need like/as. If every image is decorated, none land. Mixed metaphors (a storm that also has brakes) stall.",
    "Pile similes so it sounds poetic. Ten likes per line.",
    "One fresh image beats three dead ones (‘as busy as a bee’).",
    "Personification is a kind of metaphor with a pulse. The wind ‘gnaws’ is a choice."),
  s("english", V, "e-modality", "Modality is how sure the sentence is",
    "Must, might, could, will. High modality sounds certain. Low leaves room. A recipe wants high; a hypothesis may want low.",
    "Always write ‘is’ and ‘must’ so you sound like an expert.",
    "Match certainty to evidence. Hedging (‘suggests’) is honesty, not weakness, when the proof is thin.",
    "A command (‘Do not’) is high modality with no modal verb. Mood counts."),
  s("english", V, "e-cohesion", "Cohesion is the glue: pronouns, synonyms, connectives",
    "‘This’ needs a clear noun nearby. Vague ‘this’ is a fog machine. Connectives should match the logic (but vs therefore).",
    "Start every sentence with However to sound smart.",
    "Track a noun chain. If the pronoun could point at two people, name one.",
    "Repetition can be cohesion in a speech. In an essay it can be a stuck record. Choose."),
  s("english", V, "e-etymology-root", "Roots are a map, not a spell",
    "bio = life, graph = write. They help guesses. English still steals and lies (a pineapple is not a pine or an apple in the obvious way).",
    "If you know Latin you never need a dictionary.",
    "Use roots to attempt a meaning, then check. False friends exist.",
    "‘Inflammable’ and ‘flammable’ are a famous trap. Roots would not have saved you without a check."),
  s("english", V, "e-formal-vocab", "Formal is precise, not just longer",
    "Buy vs purchase. Sometimes purchase is right (a contract). Sometimes you just bought milk.",
    "Replace every small word with a long one from a list.",
    "Prefer the accurate word. If the long one adds nothing, keep the small one.",
    "‘Utilise’ vs ‘use’ is a classic inflate. Use ‘use’."),
  s("english", V, "e-ambiguity", "Ambiguity can be a bug or a feature",
    "‘The teacher hit the student with the book’ — who held the book? Grammar can fork. Poetry may want the fork; instructions must not.",
    "Ambiguity means you are deep. Never clarify.",
    "In info writing, close the fork. In literature, name the fork and its effect.",
    "Headlines love garden paths. ‘Squad helps dog bite victim’ is a classic."),
  s("english", V, "e-idiom", "Idioms are not Lego",
    "‘Kick the bucket’ is death, not sport. Learners (and literal robots) trip. Mix an idiom and you get sludge (‘we’ll burn that bridge when we come to it’).",
    "Translate idioms word by word. That is how language works.",
    "Learn them as chunks. In formal writing, many idioms are too chatty.",
    "A mixed metaphor is often a mixed idiom. Pick one road."),
  s("english", V, "e-spelling-morph", "Spelling is patterns plus a few outlaws",
    "Hope → hoping (drop e). Hop → hopping (double). ‘I before e’ has a street of exceptions. Morphology (un- + happy) is more reliable than a rhyme.",
    "English spelling is random. Memorise every word as a logo.",
    "Use prefix/suffix rules, then a list for outlaws. Read to feed the pattern brain.",
    "A spellchecker will not catch ‘their/there’ or a real word in the wrong seat."),
  s("english", M, "e-rhetoric-ethos", "Ethos is ‘why listen to me’",
    "Credentials, fairness, calm. It can be honest or costume. A white coat in an ad is often costume.",
    "Ethos means ethics, so any moral word is ethos.",
    "Spot who is selling their character. Ask whether the expertise matches the claim.",
    "A sports star on a finance ad is borrowed ethos. Sometimes it is also a joke. Not always."),
  s("english", M, "e-rhetoric-pathos", "Pathos is a feeling on purpose",
    "A sick child in a campaign, a joke in a speech. Feeling is not fake by default; it is a tool. Check what it is trying to make you do.",
    "If you felt something, the argument is true.",
    "Name the emotion and the ask. Then look at the logos (reasons) sitting next to it — or missing.",
    "A tear is not a statistic. You can honour the tear and still ask for the number."),
  s("english", M, "e-rhetoric-logos", "Logos is the reasoning chain",
    "Data, examples, if-then. A number can still be cherry-picked. Logos is the chain, not ‘there was a graph’.",
    "A graph makes it science. Do not read the axes.",
    "Check the warrant: why does this evidence mean that claim? Missing warrant is a hole.",
    "‘N = 8, all my friends’ is a logos costume."),
  s("english", M, "e-speech-pace", "A speech lives in breath and time",
    "Short sentences, a pause, a repeat. What looks repetitive on a page can land in a hall. What looks clever on a page can die in a mumble.",
    "Write a speech like an essay and then talk faster.",
    "Read it out. Cut clauses you cannot breathe. Put the key word at the end of a beat sometimes.",
    "A rhetorical question needs a pause. If you rush, it was just a question mark."),
  s("english", M, "e-podcast-voice", "Audio has no italics — the voice does the work",
    "Pace, music stings, who gets the last word in an edit. A transcript misses the smirk.",
    "A podcast is just an essay with a mic. Analyse it only as words.",
    "Note sound choices as techniques. An interrupt is structure.",
    "A laugh track (or a host’s chuckle) is pathos. It coaches you."),
  s("english", M, "e-ad-target", "An ad is a targeting machine",
    "Audience slice, problem, product as hero, tiny print. Representation (who is shown) is a claim about who matters.",
    "Ads inform the public equally. That is their legal definition in your heart.",
    "Name the want they invented or found, and who is missing from the picture.",
    "Native advertising wears journalism’s clothes. Labels matter."),
  s("english", M, "e-news-angle", "A news angle is a choice of front door",
    "Same event: ‘chaos’ vs ‘families wait’. Headline, photo, and lead sentence pick a door. Objectivity is a set of habits, not a halo.",
    "The first story you see is the full truth in 3D.",
    "Compare two outlets’ doors. Then go to a primary (a speech, a data release).",
    "A ‘sources say’ without naming can be protection or fog. Ask which."),
  s("english", M, "e-social-caption", "A caption is a frame, not a sticker",
    "The same image with ‘hero’ vs ‘hoarder’ trains the eye. Alt-text is access and also a frame.",
    "Captions are optional. The photo speaks for itself always.",
    "Write what is not obvious and what must be accurate (names, places). Do not invent a mind.",
    "A misleading crop plus a true caption can still mislead. The pair is the text."),
  s("english", M, "e-stereotype", "A stereotype is a shortcut that costs someone",
    "Stock characters (the nag, the thug) travel because they are cheap. Critique is naming the shortcut and who it harms.",
    "Stereotypes are efficient, so they are fine in stories ‘for kids’.",
    "Ask who is flattened, who is complex, and whether the text winks or believes it.",
    "Reclaiming a stereotype (in-group humour) is not the same as an out-group repeating it. Context is the whole move."),
  s("english", M, "e-intertextual", "Texts talk to other texts",
    "An allusion, a remix, a genre template. You only hear it if you know the other text — or the new one teaches you.",
    "Originality means no links. Any echo is cheating.",
    "Name the reference and what changes in the new seat. A parody needs you to know the original’s rules.",
    "Shakespeare is a quarry. So is a 2014 meme. Both can be intertext."),
  s("english", M, "e-persuasive-structure", "A pitch has an order that does work",
    "Hook, problem, proof, answer, ask. Skipping the ask is a speech that claps itself.",
    "Put the ask first and the stories never, so it stays professional.",
    "Map the beats. If proof never arrives, it was only pathos in a suit.",
    "A call to action should be doable (‘email this MP’) not ‘fix the world by Friday’."),
  s("english", M, "e-inclusive-language", "People are not their labels as a whole self",
    "Person-first or identity-first depends on communities (many Autistic advocates prefer identity-first). The skill is following the people, not a 2005 pamphlet only.",
    "Slurs are fine in analysis without a purpose, because you are quoting the world.",
    "Use the terms people use for themselves. When quoting hate, do it with a reason and a frame.",
    "A default ‘he’ for a mixed group is a small erasure that adds up. Recast the sentence."),
  s("english", W, "e-intro-hook", "An introduction earns the next line",
    "A hook that is a question dumped from a list (‘Have you ever thought about themes?’) is a groan. Better: a precise tension from the text.",
    "Start with a dictionary definition of the first noun in the question.",
    "Open with a specific, then widen to the thesis. Keep it short in an exam.",
    "A joke can work if the rest of the essay can afford it. A tragedy essay might not."),
  s("english", W, "e-conclusion", "A conclusion is a last turn, not a copy-paste",
    "Synthesise (so what, who cares) rather than reprint paragraph one. No new giant claim that needed evidence.",
    "Write ‘In conclusion’ and then the intro again. Safety first.",
    "Answer the question with the weight of the evidence. One step out (why it matters) is enough.",
    "A flourish is optional. Clarity is not."),
  s("english", R, "e-satire", "Satire attacks with a grin that has teeth",
    "It imitates to expose. If the reader thinks the mask is the face, satire failed (or they did). Modest Proposal is the nuclear example.",
    "Satire means funny. All jokes are satire.",
    "Name the target (a vice, a policy, a type) and the method (exaggeration, irony). Ask who might miss it.",
    "A meme can be satire. A meme can also just be mean. The target and the power tilt decide."),
];
