import { s } from "./s.mjs";

const K = "Skills extras";
const W = "World stories";
const A = "Australia extras";
const R = "Rights & everyday";
const U = "Sources & museums";

export const HISTORY_SEEDS = [
  s("history", K, "h-primary-secondary", "A primary source was there",
    "A letter from 1854 is primary for that event. A textbook chapter is secondary. A memoir written fifty years later is primary for memory, slippery for facts.",
    "Old-looking documents are always primary. PDFs are always secondary.",
    "Ask: did this person witness it, or are they explaining it later with other people’s traces?",
    "A photograph is primary and still can lie (crop, caption, staging). The category is not a halo."),
  s("history", K, "h-bias-not-insult", "Bias is a lean, not a swear",
    "Every source has a seat: who paid, who was scared, who wanted a vote. Naming the lean is the skill. ‘Biased so useless’ is a cop-out.",
    "If a source is biased, throw it out and use Wikipedia only.",
    "Read against the grain: what did they assume, who is missing, what would embarrass them?",
    "A company report and a union pamphlet can both be true-and-leaning about the same strike."),
  s("history", K, "h-cause-contingent", "Causes stack; they are not a single villain",
    "Long-term fuel, short-term spark, and choices in the room. ‘Because of one person’ is a movie, sometimes a factor, rarely the whole stack.",
    "Pick the famous name. History is famous names.",
    "List structural causes and then the decision that could have gone the other way. That is contingency.",
    "Federation had railways, racism, defence fears, and ambitious men. Dropping any one still leaves a pile."),
  s("history", K, "h-anachronism", "Do not send them your phone",
    "Judging 1800s people as if they had your newsfeed is anachronism. You can still judge cruelty; you must not fake their options.",
    "If it is wrong now, they must have known it in those words then.",
    "Translate their categories (honour, empire, Country) before you prosecute. Then prosecute with evidence if you need to.",
    "A convict did not have a LinkedIn. ‘Why didn’t they just leave’ needs ships, money, and law."),
  s("history", K, "h-silence-archive", "The archive has holes on purpose and by accident",
    "Who could write, whose papers were kept, whose language the clerk spoke. Silence is evidence of power, not proof that nothing happened.",
    "If it is not in the state archive, it did not happen.",
    "Look for traces: archaeology, oral history, court scraps, songs. Say what you cannot know.",
    "Frontier violence is often in euphemism (‘dispersal’) or not filed. Reading the gap is the work."),
  s("history", K, "h-corroborate", "One source is a claim; two is a conversation",
    "Corroboration is overlap plus friction. If they agree word-for-word, one might have copied. If they fight, you just got a lead.",
    "The first source you like wins.",
    "Set two traces next to each other. Note what only one mentions. That is where to dig.",
    "A diary and a newspaper on the same riot will not match. Good."),
  s("history", K, "h-periodise", "Periods are boxes we made",
    "‘The 1960s’ did not start on 1 January for everyone. Periods help teaching; they hide overlap and people who missed the memo.",
    "History comes in labelled decades the way shops come in aisles. Nothing spills.",
    "Use periods as scaffolding, then name who did not fit (women, colonies, kids).",
    "Mabo (1992) is ‘late 20th century’ and also a continuation of much older law. The box leaks."),
  s("history", K, "h-empathy-not-excuse", "Historical empathy is reconstructing a world, not blessing it",
    "You try to see their constraints. You do not have to like the constraints. Empathy is a method; endorsement is a vote.",
    "To understand is to forgive. Always.",
    "Write ‘they believed X because Y’. Then write the consequence for the people who paid.",
    "A squatter’s fear of bankruptcy is real in the sources. So is the dispossession it funded."),
  s("history", W, "h-nile-flood", "The Nile’s gift was a calendar",
    "Predictable floods laid silt; priests and administrators made a state that could tax grain. Geography did not ‘cause’ pyramids by itself — people organised.",
    "Egypt was rich because the desert is magic.",
    "Link flood, surplus, and the state. Then ask who laboured and who was written in stone.",
    "A low Nile was a political crisis, not just a weather report."),
  s("history", W, "h-athens-limited", "Athenian democracy had a guest list",
    "Citizen men voted. Women, enslaved people, and metics did not. The word ‘democracy’ is not a sticker you slap on the whole city.",
    "Athens proves everyone in the ancient world voted.",
    "Name who was in the assembly and who kept the house/workshop running. Then talk about the idea’s later travels.",
    "Ostracism was a safety valve and a weapon. Fancy words, sharp edges."),
  s("history", W, "h-roman-roads", "Roads were a military app",
    "Rome built paths for legions and tax. Trade rode along. The road is not a gift shop; it is logistics.",
    "Romans built roads because they loved hiking.",
    "Follow the legion, then the merchant, then the idea of ‘Roman peace’ and who was on the wrong side of it.",
    "A road through a province is a claim. Local paths were already there."),
  s("history", W, "h-han-exam", "Han China bet on clerks",
    "Recommendation and later examination cultures tried to staff an empire with literate officials. It was never purely merit — pedigree still talked.",
    "Anyone poor could sit a test and run China, no catch.",
    "Link writing, grain, and distance. An empire that size needs paper-pushers or it frays.",
    "Paper and bureaucracy are a technology pair. Ideas moved along the same corridors as silk."),
  s("history", W, "h-silk-not-only", "The Silk Road was many roads",
    "Goods, Buddhists, diseases, and stories. ‘Silk’ is a nickname. Oasis towns taxed the caravans; empires tried to own the tax.",
    "One paved highway from Rome to China with a gift shop.",
    "Think network: desert, sea, steppe. Ask what travelled that was not luxury cloth.",
    "The Black Death later used some of the same connective tissue. Connection is not kindness."),
  s("history", W, "h-islamic-golden", "Translation was a power move",
    "Baghdad’s House of Wisdom stories (and other cities) gathered Greek, Persian, Indian science into Arabic. Europe later borrowed. Knowledge had visas.",
    "Science slept until Europe woke it in 1500.",
    "Follow a book: who copied, who funded, who used algebra for inheritance law or astronomy for prayer times.",
    "Algebra’s name is a clue. So is a star’s Arabic name in a modern sky map."),
  s("history", W, "h-mongol-connect", "The Mongol moment was violence and a post office",
    "Conquest, massacre, and also a Pax that moved merchants and plague. Both sentences can be true. Cheerleading is optional.",
    "The Mongols were only a postal service with ponies.",
    "Map the destruction and the relay stations. Then ask what a ‘world-system’ looks like from a burned city.",
    "Yuan China and the Golden Horde are not one hat. The family firm split."),
  s("history", W, "h-print-press", "Print multiplied arguments",
    "Movable type in Europe (and earlier print cultures in East Asia) changed who could afford a pamphlet. Reformation and rumour both scaled.",
    "The printing press invented thinking.",
    "Cheaper copies, more readers, more heresy and more standardisation. Literacy still had a class gate.",
    "A 16th-century pamphlet war is social media with wet ink and a hangman."),
  s("history", W, "h-columbian-exchange", "1492 shuffled living things",
    "Potatoes, maize, horses, smallpox. Calorie maps and death maps moved. It was not ‘discovering empty land’.",
    "Europe brought civilisation; the Americas contributed a few curios.",
    "List biota both ways, then the labour systems (including slavery) that followed the crops.",
    "Andean potato in Ireland is a later chapter of the same shuffle — including famine when the crop failed."),
  s("history", W, "h-atlantic-slavery", "The Atlantic system was a machine",
    "Captives, Middle Passage, plantations, sugar/cotton profits, and laws that made people into property. It was not a series of unfortunate captains.",
    "Slavery was as old as time so this version needs no special look.",
    "Follow a commodity and a body. Name the companies, states, and buyers. Abolition was fought, not granted by mood.",
    "British abolition and British profits can sit in the same empire. That tension is the point."),
  s("history", W, "h-industrial-coal", "Coal plus mills rewrote time",
    "Steam, factories, child labour, and a new clock. Rural putting-out died unevenly. Smoke was a class experience.",
    "The Industrial Revolution was gadgets appearing one Tuesday in England, equally for all.",
    "Energy source, labour law, and who owned the mill. Then the global cotton that fed it.",
    "A Luddite smash was a workplace argument, not a fear of toasters."),
  s("history", W, "h-french-revolution", "1789 was a stack that slipped",
    "Debt, bad harvests, Enlightenment talk, and a king who ran out of road. Terror and Napoleon were sequels, not proofs that the first demand was fake.",
    "The French Revolution is ‘liberty’ on a mug. Skip the rest.",
    "Order: fiscal crisis, Estates-General, popular violence, war, radicalisation. Rights talk travelled — including to colonies who asked ‘us too?’",
    "Haiti’s revolution is the sequel Europe tried not to hear."),
  s("history", W, "h-meiji", "Meiji Japan chose a crash course",
    "Faced with gunboat power, reformers abolished the old order fast: industry, army, constitution with a catch. It was not ‘Westernisation’ as cosplay — it was survival and empire.",
    "Japan became European because it liked tea less.",
    "Name the threat, the reforms, and the later imperialism in Korea/China. Modernisation had a bayonet.",
    "A constitution can exist and still keep the emperor above the fray. Read the fine print."),
  s("history", W, "h-ww1-trench", "The Western Front was industrial killing",
    "Artillery, mud, and a state that could feed the guns. ‘Lions led by donkeys’ is a debate, not a caption you skip evidence for.",
    "WWI was pointless because it was in black and white.",
    "Technology + mass conscription + blocked fronts. Then home fronts and empire troops (including Australians).",
    "Gallipoli is one campaign in a world war. It is not the whole war, and it is not ‘nationhood’ without argument."),
  s("history", W, "h-ww2-home", "Total war ate the home street",
    "Rationing, bombing, women’s labour, internment. The ‘front’ was also a factory and a kitchen. Propaganda was a tool, not wallpaper.",
    "WWII was only soldiers in helmets until 1945, then peace.",
    "Pick a civilian trace (ration book, air-raid shelter) and a policy (who was interned). Then the Holocaust as a specific crime, not a blur.",
    "Australia’s war included Darwin raids, POWs, and a turn toward the US. The map moved."),
  s("history", W, "h-cold-war-proxy", "The Cold War was hot in other people’s countries",
    "Nuclear stalemate in the centres, wars and coups at the edges. ‘Peace’ in Europe could be war in Korea, Vietnam, or Afghanistan.",
    "The Cold War means nobody died, because the bombs were not used on Washington.",
    "Bipolar pressure + local conflicts. Spies and aid were weapons. Non-aligned states tried a third path.",
    "A ‘police action’ is a war in a suit. Read the body count, not the nickname."),
  s("history", W, "h-decolonisation", "Flags changed; strings often did not",
    "After 1945 many empires folded under cost, war, and nationalist movements. Borders could be hasty. Neo-colonial economics could stay.",
    "Britain politely packed and left because it was tired of tea.",
    "Name the movement, the violence or negotiation, and what the new state inherited (debt, army, a bad map).",
    "India/Pakistan 1947 is independence and partition trauma in the same fortnight."),
  s("history", A, "h-deep-time", "This continent has deep human time",
    "Aboriginal and Torres Strait Islander peoples’ occupancy is tens of thousands of years — among the longest continuous cultures. ‘Prehistory’ as ‘empty’ fails the evidence.",
    "Real history starts in 1788 when writing arrived.",
    "Use archaeology, oral traditions, and continuing cultures. Deep time is not a prologue you skip.",
    "A 65,000-year neighbourhood (debated in details, not in the fact of ancient presence) makes 1788 a recent layer."),
  s("history", A, "h-songlines", "Songlines are knowledge systems",
    "Routes, law, and land are braided in ceremony and story. They are not ‘myths for kids’ in the dismissive sense. They are maps with obligations.",
    "Dreaming stories are fiction hour, like superhero films.",
    "Treat them as intellectual property and law. Ask permission and context before you retell.",
    "A highway can cut a songline. That is an infrastructure and a culture event."),
  s("history", A, "h-terra-nullius", "Terra nullius was a legal story that failed",
    "The claim of land belonging to no one ignored law, farming, and presence. Mabo (1992) killed it in Australian law; the political fight did not end that afternoon.",
    "The land was unused because fences had not been invented.",
    "Contrast the doctrine with evidence of occupancy and the High Court’s move. Native title is not a simple ‘give it back’ sticker — read what it can and cannot do.",
    "A cattle lease and native title can coexist in law and still collide on a road."),
  s("history", A, "h-frontier-wars", "The frontier was not a handshake",
    "Violence, disease, and resistance. ‘Settlement’ can be accurate as a government word and still hide killings. Historians argue scale; they do not have a blank page.",
    "It was peaceful because the paintings look calm.",
    "Use specific cases (a massacre with records, a war on a named Country) rather than a national shrug.",
    "Euphemisms like ‘dispersal’ in official papers are a tell. Read them as operations."),
  s("history", A, "h-gold-rush", "Gold scrambled the colonies",
    "Population spike, Eureka, anti-Chinese riots, and a more assertive colonial politics. Gold is a mineral and a social bomb.",
    "Gold just made everyone rich and friendly.",
    "Follow who came, who was taxed, who was excluded, and what the licence hunt really was.",
    "Eureka is a democracy story and a miners’ tax revolt. Both. It is not a general strike for everyone."),
  s("history", A, "h-federation-why", "Federation was a deal, not a destiny",
    "Defence fears, tariffs, railways of different gauges, and a White Australia consensus. Women and Indigenous people were not equally in the ‘we’.",
    "Australia federated because it was inevitable and kind.",
    "List the yes reasons and the excluded. The Constitution is a bargain with freeze-frames we still argue with.",
    "The 1901 flag moment is not the same as a republic debate. Different tickets."),
  s("history", A, "h-white-australia", "White Australia was policy, not mood",
    "Dictation tests and later variants tried to control who could come. It was popular in its day and is a stain you should name, not mumble.",
    "Australia was always multicultural in law, so this is a myth.",
    "Read the acts, the tests, and who campaigned to end them (including post-1945 shifts).",
    "A dictation test in a language you did not know was the point. It was a lock dressed as a quiz."),
  s("history", A, "h-anzac-debate", "Anzac is memory with politics",
    "Gallipoli was a failed campaign with courage and waste. The legend was built in newspapers, schools, and later governments. You can honour dead without buying every slogan.",
    "Questioning the legend means you hate soldiers.",
    "Separate the experience of troops, the imperial command, and the later commemorative industry.",
    "Aboriginal service sits inside and against a nation that often denied them a vote. Hold both."),
  s("history", A, "h-great-depression-au", "The Depression was a dole and a riot",
    "Unemployment, eviction, Premiers’ Plan fights, and a generation that distrusted banks. Australia’s version had its own politics (Lang, Lyons).",
    "Everyone was equally poor and then WWII fixed it like a switch.",
    "Use a local trace (a shanty town, a ration) and a policy argument. Recovery was uneven.",
    "A ‘susso’ payment is a primary-source word. It is not a joke nickname only."),
  s("history", A, "h-postwar-migration", "Populate or perish had a passenger list",
    "Displaced Europeans, then later sources, rebuilt labour and cities. ‘New Australian’ was a phrase with a pecking order. First Nations were not the ones being ‘populated’.",
    "Migration was a charity picnic with no industrial need.",
    "Link labour shortage, Cold War, and assimilation pressures. Then the later unravelling of White Australia.",
    "A hostel in Bonegilla is a site. Snowy Hydro is a project with migrant labour in the concrete."),
  s("history", A, "h-1967-referendum", "1967 was a count, not a magic wand",
    "The referendum let the Commonwealth count Aboriginal people in the census and make laws. It did not grant a wage, land, or an apology by itself.",
    "1967 gave the vote and ended all discrimination at lunchtime.",
    "Read the actual constitutional change. Then look at land rights, deaths in custody, and Closing the Gap as later, unfinished business.",
    "Citizenship stories are messy: voting rights varied by state before and after. Do not collapse them into one year."),
  s("history", A, "h-stolen-generations", "Removal was a policy with files",
    "Children taken under ‘protection’ and assimilation. Bringing Them Home (1997) collected testimony. The Apology (2008) was a speech, not a time machine.",
    "It was well-meaning adoptions, so it is not history’s business.",
    "Use testimony, government files, and the legal fights. Intergenerational effects are part of the evidence.",
    "A file that says ‘for their own good’ is a primary source of ideology. Read it as such."),
  s("history", A, "h-mabo-native-title", "Mabo was a court fight on a reef of law",
    "Eddie Mabo and others proved Meriam law on Mer. Native title is recognised where it survived, with extinguishment rules that bite.",
    "Mabo gave every Aboriginal person a house title the next morning.",
    "Distinguish native title, land rights statutes, and sovereignty claims. They are neighbouring tools, not synonyms.",
    "The Wik follow-up and later amendments are the fine print. A headline is not the act."),
  s("history", A, "h-republic-1999", "1999 was a model fight, not only a crown fight",
    "Voters were asked about a specific republic design. Many who disliked the model voted no without loving the monarchy. Process was the battlefield.",
    "Australians voted that they never want a republic, forever, amen.",
    "Separate ‘head of state’ from ‘which appointment method’. Referendums fail without a broad coalition.",
    "A constitutional monarchy can coexist with an independent foreign policy. The crown is not the whole state."),
  s("history", R, "h-suffrage-women-au", "Some Australian women voted early — not all",
    "White women got federal votes early compared with much of the world. Aboriginal women (and men) were often excluded in practice and law. ‘First’ needs a qualifier.",
    "Australia invented women’s rights and handed them to everyone in 1902, job done.",
    "Name who was included in 1902 and who was not. Then the later campaigns.",
    "A world-leading franchise for some is still a restriction for others. Both sentences."),
  s("history", R, "h-eight-hour", "The eight-hour day was a fight",
    "Stonemasons in the 1850s and later unions pushed 8-8-8. Leisure was political. It did not arrive as a gift from a kind factory.",
    "Work hours shrank because machines are nice.",
    "Strikes, laws, and exceptions (farm, home, gig). A slogan on a banner is a primary source.",
    "Labour history is history. A payday is a document."),
  s("history", R, "h-welfare-state", "The pension was an argument about who deserves",
    "Age pensions, invalidity, later unemployment insurance — each had a moral test. Indigenous access was often delayed or denied.",
    "The welfare state is natural once a country is rich, like fruit on a tree.",
    "Follow a payment: who got it, who policed it, what stigma came with it.",
    "A ‘dole bludger’ headline is a source about culture, not a fact about a person."),
  s("history", R, "h-media-press", "Newspapers made publics",
    "Partisan papers, later broadcasting, now platforms. A ‘public’ is assembled, not found under a rock. Censorship in war is a recurring tool.",
    "The news was always neutral until the internet ruined it.",
    "Ask who owned the press, who was the audience, and what could not be printed.",
    "A 19th-century paper endorsing a candidate on page one is honest. So is a paywalled algorithm, in a different way."),
  s("history", R, "h-youth-culture", "Teenagers were invented as a market and a panic",
    "Postwar wages, rock’n’roll, and moral panics. Youth culture is not trivial — it is consumption, identity, and policing.",
    "Kids have always been the same, so the 1950s did not happen.",
    "Use a song, a police gazette, and an ad. The panic often says more about adults.",
    "Bodgies, widgies, later punks: different costumes, similar newspaper breathing."),
  s("history", R, "h-environment-movements", "Green bans were labour plus ecology",
    "NSW builders’ labourers refused work on some sites (Kelly’s Bush and others). Heritage and class met on a scaffold.",
    "Environmentalism started in 2006 on the internet.",
    "Link union power, suburban protest, and later party politics. A tree and a wage can be one campaign.",
    "A green ban is a primary-source tactic. It is not a Facebook filter."),
  s("history", R, "h-lgbt-law", "Decriminalisation was a calendar of states",
    "Homosexuality laws fell at different speeds in different Australian jurisdictions. The Sydney Mardi Gras began as a protest, not a brand activation.",
    "Rights arrived all at once when culture became kind.",
    "Track a law, a raid, a march, and a later court or ballot. Pride’s commercial layer is a later sediment.",
    "A police ledger and a protest badge are both archives."),
  s("history", R, "h-disability-rights", "Access is a political demand",
    "Institutions, then deinstitutionalisation fights, then DDA-style law. A ramp is a policy, not a courtesy.",
    "Disability history is medical only. Skip the protests.",
    "Use activist traces and the built environment (a step, a bus). The person is not the diagnosis as a full biography.",
    "Paralympics are sport and also a visibility machine. They do not finish the access job."),
  s("history", U, "h-museum-frame", "A museum is an argument in glass",
    "What is displayed, what is repatriated, whose voice is on the label. Objectivity is a tone, not a fact of the building.",
    "Museums are neutral warehouses. Labels are just names.",
    "Read the caption as a source. Ask who lent the object and who wants it back.",
    "Ancestral remains and secret/sacred objects are not ‘cool skulls’. Protocols exist."),
  s("history", U, "h-oral-history", "Memory is a source with weather",
    "Interview a person and you get meaning, emotion, and drift. That can be more true about experience than a shipping list, and worse about a date.",
    "If they were there, every detail is courtroom-perfect.",
    "Record, contextualise, corroborate dates, and respect trauma. Oral history is not ‘less than’ a memo.",
    "A Stolen Generations testimony is evidence. So is a bureaucratic form. They do different jobs."),
  s("history", U, "h-map-as-claim", "A map is a claim on paper",
    "Borders, names, empty interiors. Colonial maps can erase paths that existed. A Mercator classroom map stretches power.",
    "Maps are just accurate pictures. They cannot lie.",
    "Ask who surveyed, who named, and who is missing. North-up is a convention.",
    "‘Terra nullius’ lived in maps that left Country blank. Blank is a political colour."),
  s("history", U, "h-statistics-past", "A census is a power tool",
    "Who is counted, as what, by whom. 1967 changed a count. Categories (race, occupation) are historical, not natural kinds.",
    "Numbers from the past are raw truth because they are numbers.",
    "Read the question asked that year. Compare categories across censuses with care — they move.",
    "A column called ‘half-caste’ is a source of a racial regime. Do not recycle it as a neutral variable."),
  s("history", U, "h-commemoration", "A statue is a sentence in bronze",
    "Who paid, when it went up, who is not on the plinth. Taking one down is also a historical event, not only a tantrum.",
    "Statues are history itself. Removing one deletes the past.",
    "Read the plaque date (often later than the hero). Put a second plaque or a new site if the argument is ‘add context’.",
    "A cenotaph and a statue of a squatter are both commemorations. They are not the same sentence."),
  s("history", U, "h-digital-archive", "Digitised is not complete",
    "Search boxes love print and English. Handwriting, off-digitised series, and paywalls still hide. OCR misreads names.",
    "If Google cannot find it, it is not historical.",
    "Use Trove and also the box in the reading room. Note what the algorithm cannot see.",
    "A keyword misspelling in 1890 can hide a riot. Try the racist word the paper actually used, with care and a purpose."),
  s("history", W, "h-ottoman-end", "The Ottoman end redrew a map with a ruler",
    "WWI killed an empire. Mandates, new states, and promises that conflicted (including over Palestine) are the hangover. ‘Artificial borders’ still had local politics inside them.",
    "The Middle East has no history until oil.",
    "Follow a wartime promise, a league mandate, and a local movement. Maps at Versailles were weapons.",
    "Gallipoli sits in this Ottoman story too — not only in an Australian one."),
  s("history", A, "h-vietnam-au", "Australia’s Vietnam was an alliance choice",
    "Forward defence, conscription ballot, moratoriums. Veterans’ return was not a single parade feeling. The war’s meaning split the street.",
    "Australia was in Vietnam because it is near Vietnam.",
    "Use a ballot marble, a protest photo, and a cabinet paper. Then the later welcome-home fights.",
    "A birthday-ballot conscript is a specific policy. Volunteers and regulars are other paths through the same war."),
];
