import { s } from "./s.mjs";

const D = "Decimals";
const R = "Ratio & rate";
const A = "Algebra extras";
const G = "Geometry extras";
const C = "Data & chance";

export const MATHS_SEEDS = [
  s("maths", D, "m-decimal-place", "Tenths are not extra zeros",
    "0.3 is three tenths. 0.03 is three hundredths. The zero is a chair, not decoration.",
    "0.3 and 0.30 and 0.03 are the same because they all have a 3.",
    "Name the place out loud, then compare. Trailing zeros after the last non-zero decimal do not change size; middle zeros do.",
    "Money writes $3.50 with a trailing zero because cents are hundredths. That is a place convention, not proof that 3.5 ≠ 3.50."),
  s("maths", D, "m-decimal-add-lineup", "Line up the points, not the left edges",
    "Adding decimals is adding matching places. 3.4 + 0.25 wants tenths under tenths.",
    "Park the numbers against the left margin like a word processor and add down.",
    "Write the decimal points in a column, fill empty places with zeros if it helps, then add.",
    "3.4 + 0.25 = 3.65, not 0.59 from a left-align accident."),
  s("maths", D, "m-repeating-third", "1/3 is not 0.3",
    "1/3 = 0.333… repeating. Cutting it to 0.3 is a round, and three of those do not make a whole.",
    "1/3 + 1/3 + 1/3 = 0.9, so a whole is optional.",
    "Keep it as a fraction, or keep the repeating mark, or round with an error budget.",
    "Calculators that show 0.3333333 are still rounding. 3 × (1/3) is 1 if you stayed in fractions."),
  s("maths", D, "m-rounding-5", "Five rounds by a rule you state",
    "Many school rules: 5 or more rounds away from 0 on that digit. Bankers’ rounding is different. State the rule before you fight.",
    "Always round 1.45 to 1.4 because 5 is small.",
    "Look one place past the keep-digit, apply the stated rule, and drop the tail.",
    "Money often keeps two decimal places. Rounding twice (first to 3 dp, then to 2) can drift."),
  s("maths", D, "m-scientific-notation", "Scientific notation is a sliding window",
    "4.5 × 10³ is 4500. The 4.5 is the significand; the 10³ counts how many places the point moved.",
    "4.5 × 10³ means 4.5 times 103, because you multiply the numbers you see.",
    "Move the point by the exponent. Negative exponents are small numbers, not negative money.",
    "2.3 × 10⁻² = 0.023. The minus is the direction of the slide."),
  s("maths", D, "m-sig-figs-measure", "Significant figures are honesty about a tool",
    "A cheap ruler does not justify eight decimal places. Significant figures are a claim about precision, not a vibe.",
    "Copy every digit the calculator spits so you look precise.",
    "Match the crudest measurement. Do not invent millimetres a metre-stick cannot see.",
    "Trailing zeros in 4.00 m mean you measured to hundredths. 4 m did not."),
  s("maths", D, "m-convert-metric", "Milli is a thousand slices",
    "milli- is 10⁻³, centi- 10⁻², kilo- 10³. 2.5 m = 2500 mm because you multiplied by 1000.",
    "2.5 m = 25 mm because milli sounds small so fewer digits.",
    "Count the jumps on the prefix ladder, then multiply or divide by 10 per jump.",
    "A ‘2.5 kg bag’ is 2500 g, not 25 g. Kitchen scales will not save a skipped zero."),
  s("maths", D, "m-negative-decimal", "Minus is a direction on decimals too",
    "−0.4 is left of 0. It is smaller than −0.1. ‘Smaller’ on a number line is more left, not ‘closer to zero’.",
    "−0.1 is colder/smaller than −0.4 because 1 is less than 4.",
    "Draw the line. More negative is further left. Temperature and overdrafts use the same picture.",
    "−0.4 + 0.5 = 0.1. You walked right past zero."),
  s("maths", D, "m-decimal-multiply", "Multiply, then park the point",
    "3.2 × 1.4: multiply 32 × 14, then the total decimal places (one + one = two) sit in the product.",
    "Add the numbers because there is a point involved.",
    "Ignore points, multiply as whole numbers, count decimal places in the factors, place the point.",
    "Estimate first: 3 × 1.4 ≈ 4.2. If you get 448, the point fell on the floor."),
  s("maths", D, "m-decimal-divide", "Dividing by 0.1 makes it ten times bigger",
    "÷ 0.1 is × 10. A smaller divisor means more groups fit. 6 ÷ 0.1 = 60.",
    "Dividing by a decimal always shrinks the number because decimals are small.",
    "Rewrite 6 ÷ 0.1 as 60 ÷ 1 by sliding both numbers one place, or invert-and-multiply.",
    "6 ÷ 0.5 = 12 because two halves fit in a whole, so twelve halves fit in six."),
  s("maths", R, "m-ratio-recipe", "A ratio is a recipe, not a pair of islands",
    "2:3 flour to water means 2 parts and 3 parts of the same size. Total parts = 5.",
    "2:3 means 2/3 of the mix is flour and you can ignore the 3.",
    "Find the part size (total ÷ parts), then multiply. Keep the same units.",
    "Scaling 2:3 to 10:15 is the same recipe. 2:4 is not."),
  s("maths", R, "m-unit-rate", "Per one is the honest comparison",
    "A unit rate is ‘for 1’. $4.80 per 12 means $0.40 each. Compare per 1 or per 100 g, not per bag.",
    "The bigger pack is always cheaper because it is bigger.",
    "Divide to per-one (or per 100 g), then compare. Watch the units.",
    "3 for $5 vs 5 for $8 wants per item, not a vibe about threes."),
  s("maths", R, "m-speed-distance", "Speed is a rate with a direction in time",
    "average speed = distance / time. 120 km in 2 h is 60 km/h. It is not 120 km/h because the number 120 looks faster.",
    "If you drove 120 km, your speed was 120.",
    "Match units (km and hours, or m and seconds) before you divide. Average speed is not a speedometer snapshot.",
    "A 2 h trip that includes a rest still uses total time in the denominator if the question asked average including rest."),
  s("maths", R, "m-density-pop", "Density is stuff per space",
    "Population density is people per km². A huge empty shire can have fewer people per km² than a tiny suburb.",
    "The state with more people is more dense.",
    "Divide people by area. Compare like with like (same units of area).",
    "A packed train can be dense and still have fewer people than a city. Density is not a headcount."),
  s("maths", R, "m-scale-map", "1:100 000 is a shrink, not a hint",
    "1 cm on the map is 100 000 cm in the world (1 km). Measure, then multiply by the scale.",
    "A bigger scale number means a more zoomed-in map.",
    "Convert to the same unit, multiply. ‘Large scale’ in geography means more detail (1:10 000 is larger-scale than 1:1 000 000).",
    "A ruler on a 1:100 000 map: 4.5 cm → 4.5 km, not 4.5 m."),
  s("maths", R, "m-best-buy-gst", "GST sits after the rate, unless the ticket says included",
    "In Australia GST is 10%. ‘Plus GST’ means × 1.10 at the end. Unit price comparisons must use the same tax treatment.",
    "Add 10% to both packs even if one already includes GST, for fairness.",
    "Read the label. Compare ex-GST with ex-GST, or inc with inc. Do not mix.",
    "A $10 + GST item is $11. 10% of $11 is not the GST on the original $10."),
  s("maths", R, "m-inverse-proportion", "More workers can mean fewer hours",
    "If the job is a fixed pile of work, twice the people can mean half the time (when they do not trip over each other).",
    "More people always means more hours because more names are on the timesheet.",
    "Ask: is the total work fixed? If yes, time × people stays in the same neighbourhood.",
    "A 6-person job that was 2 hours is 12 person-hours. Three people: about 4 hours, not 2."),
  s("maths", R, "m-percent-change-base", "Percent change needs the old base",
    "Increase 50 → 60 is +20% because 10/50 = 0.2. 60 → 50 is not −20% of 60 in the same breath without saying so.",
    "Up 10 and down 10 is a wash, so the percents cancel.",
    "Difference over original, then × 100. Going back is a new original.",
    "A 50% off then 50% off is 75% off the first price, not zero."),
  s("maths", R, "m-interest-simple", "Simple interest is a flat hire of money",
    "I = Prt with r as a decimal. $1000 at 5% for 3 years simple is $150 interest, not $1500.",
    "5% means multiply by 5.",
    "Convert percent to decimal, multiply principal × rate × time in years (or match the time the rate uses).",
    "Simple interest does not pay interest on interest. That is the next path."),
  s("maths", R, "m-compound-once", "Compound interest is interest on the pile",
    "A = P(1+r)^n. 5% for 2 years on $1000 is 1000 × 1.05² = $1102.50, not $1100.",
    "Compound is just simple interest twice, so +$50 +$50.",
    "Multiply by (1+r) once per period. The second year charges 5% of $1050.",
    "More frequent compounding (with the same nominal rate) is a little more, not a lottery."),
  s("maths", A, "m-like-terms", "Like terms share the letters and powers",
    "3x and 5x add to 8x. 3x and 5x² do not. The power is part of the name.",
    "Add all the numbers and write x at the end because there is an x nearby.",
    "Add coefficients of identical letters/powers. Leave unlike terms sitting beside each other.",
    "3x + 5 = 8x is the classic crime. 5 has no x to join."),
  s("maths", A, "m-distribute-minus", "A minus outside the brackets flips signs",
    "−(x − 4) = −x + 4. The minus is a −1 multiplying every term.",
    "−(x − 4) = −x − 4 because the minus looks sticky.",
    "Distribute −1 to each term. Check with a number: x=5 → −(1) = −1, and −5+4 = −1.",
    "4 − (x − 1) = 4 − x + 1 = 5 − x. The inner minus flips."),
  s("maths", A, "m-solve-both-sides", "Do the same to both sides",
    "An equation is a balance. Subtract 3 from both sides, not from the side you dislike.",
    "Move the 3 by changing its sign and also multiplying because moving is magic.",
    "Undo with inverse operations, both sides, until the unknown is alone. Check by substituting.",
    "2x + 3 = 11 → 2x = 8 → x = 4. Not x = 11 − 3 − 2."),
  s("maths", A, "m-inequality-flip", "Multiply by a negative and the inequality flips",
    "−2x > 6 → x < −3. The flip is the price of multiplying by a negative.",
    "Treat inequalities like equations and never flip, because the arrow is decoration.",
    "Do the same to both sides; if you multiply/divide by a negative, reverse the arrow. Test a number.",
    "Drawing the number line with an open circle for > or < stops you including the endpoint by accident."),
  s("maths", A, "m-gradient-rise", "Gradient is rise over run",
    "m = (y2−y1)/(x2−x1). A slope of 2 means up 2 for right 1. Negative is down as you go right.",
    "Gradient is the bigger y-value, because height is steepness.",
    "Count rise, then run, then divide. Keep the sign. Vertical lines have undefined gradient, not ‘infinity marks’.",
    "From (1,2) to (4,8): rise 6, run 3, m=2. Not 8/4 because those are coordinates, not rises."),
  s("maths", A, "m-y-intercept", "c is where it hits the y-axis",
    "In y = mx + c, when x=0, y=c. That is the intercept, not a secret gradient.",
    "c is always the bigger number in the equation.",
    "Read c when x=0. On a graph, it is the crossing of the vertical axis, if the scale starts at 0.",
    "y = 2x + 5 crosses at (0,5), not (5,0). That would be an x-intercept story."),
  s("maths", A, "m-substitute-first", "Substitution is plug-in, then order",
    "If x=3 in 2x², that is 2×9=18, not (2×3)²=36 unless the brackets say so.",
    "Write the number next to the letter and hope BODMAS is optional.",
    "Brackets around the substitution, then follow order of operations.",
    "f(x)=x²−1 at x=−2 is 4−1=3, not −4−1. The square eats the minus if −2 is the input."),
  s("maths", A, "m-factor-common", "Factor out what every term actually shares",
    "6x + 9 = 3(2x+3). The 3 is in both. Do not invent an x in the 9.",
    "6x + 9 = 6x(1+9) because 6x looks like a factor of the universe.",
    "Find the greatest common factor of the coefficients (and letters if present), pull it out, check by expanding.",
    "x² + x = x(x+1), not x²(1+x) unless you like extra x."),
  s("maths", A, "m-expand-binomial", "FOIL is just distribute twice",
    "(x+2)(x+3)=x²+5x+6. Each term in the first bracket meets each in the second.",
    "Add the insides: (x+2)(x+3)=x+5.",
    "Four products, then like terms. Check with x=1: 3×4=12, and 1+5+6=12.",
    "The middle term 5x is 2x+3x, not a mystery tax."),
  s("maths", A, "m-index-multiply", "Same base: add the indices when multiplying",
    "a³ × a² = a⁵. You are counting factors of a, not multiplying the little numbers for sport.",
    "a³ × a² = a⁶ because 3×2=6.",
    "Multiply same bases → add exponents. Power of a power → multiply exponents. Check with a=2.",
    "2³ × 2² = 8×4=32 = 2⁵, not 2⁶=64."),
  s("maths", A, "m-index-zero", "a⁰ is 1 (if a is not 0)",
    "The empty product is 1. a³/a³=a⁰=1. 0⁰ is a fight you should not pick in this path.",
    "Anything to the power 0 is 0 because you have nothing.",
    "For non-zero a, a⁰=1. 10⁰=1 is why 10³ is 1000 not 10000 from a missed zero power.",
    "2⁰=1, not 2, not 0. Calculators agree; folk memory sometimes does not."),
  s("maths", A, "m-linear-sequence", "An arithmetic sequence adds the same each time",
    "3, 7, 11, 15 … common difference +4. Term n is first + (n−1)d.",
    "If it looks roughly up, it is exponential.",
    "Find d, then use T_n = a + (n−1)d. The 10th term is not 10× the first unless d is magic.",
    "T_5 for 3,7,11,… is 3+4×4=19, not 3+4×5. The first term already used your ‘one’."),
  s("maths", G, "m-angle-straight", "A straight line is 180°",
    "Adjacent angles on a straight line add to 180°. A ‘straight-looking’ drawing is not a proof without that fact or a given.",
    "If it looks flat, each angle is 90°.",
    "Call the unknown x, write x + given = 180, solve. Mark the diagram.",
    "130° next to x on a line → x=50°, not 40° from a 90° superstition."),
  s("maths", G, "m-triangle-sum", "A triangle owns 180°",
    "Interior angles of a triangle add to 180°, Euclidean and flat. A 90° corner leaves 90° for the other two to share.",
    "Triangles add to 360° like a full turn, because they are shapes.",
    "Add the two you know, subtract from 180. Isosceles means base angles match.",
    "A 70° and 40° third angle is 70°, not 80°. 180−110=70."),
  s("maths", G, "m-pythag-right", "Pythagoras wants a right angle",
    "a²+b²=c² only for right triangles, c the hypotenuse (longest, opposite 90°).",
    "Use a²+b²=c² on every triangle because it is famous.",
    "Confirm 90°, identify hypotenuse, then square, add, square-root. Units stay length, not length².",
    "3-4-5 is a triple. 3²+4²=9+16=25=5². 3+4=7 is not a hypotenuse."),
  s("maths", G, "m-area-units", "Area is length × length",
    "m × m = m². A 3 m by 4 m rectangle is 12 m², not 12 m, not 7 m.",
    "Add the sides to get area because you walk the fence.",
    "Use the matching formula (lw, ½bh, πr²), then square units. Perimeter is the add-the-edges cousin.",
    "A 3 m × 4 m patio needs 12 m² of tiles, plus waste. 14 m of skirting is perimeter thinking."),
  s("maths", G, "m-circle-pi", "π is circumference over diameter",
    "C=πd=2πr. Area=πr². Mixing them is the national sport.",
    "Area is 2πr because that formula has π in it.",
    "Radius vs diameter first. Square only the radius for area. Leave π or use 3.14 as instructed.",
    "r=5 → area 25π, not 10π. 10π would be circumference."),
  s("maths", G, "m-similar-shapes", "Similar means same shape, scaled",
    "Equal angles, sides in proportion. A 2× scale multiplies lengths by 2 and areas by 4.",
    "Similar means the areas match and the lengths can argue.",
    "Match corresponding sides. Scale factor k for lengths, k² for area, k³ for volume.",
    "A triangle with sides 3,4,5 and 6,8,10 is similar (k=2). 3,4,5 and 6,8,9 is not."),
  s("maths", G, "m-volume-prism", "A prism is a base I can slide",
    "Volume of a prism = base area × height (the slide). A triangular prism uses triangle area, not ‘three rectangles and hope’.",
    "Volume is always length×width×height even when the ends are triangles.",
    "Find the face that is the base, compute its area, multiply by the perpendicular height.",
    "A tent-shaped prism with triangle 6 m² and length 10 m is 60 m³, not 16."),
  s("maths", G, "m-net-surface", "A net is the skin unfolded",
    "Surface area is the sum of the faces. A net that overlaps or misses a face will lie.",
    "Surface area is the volume with different units.",
    "Sketch all faces, use each once, add. Cylinders: two circles plus a rectangle 2πr by h.",
    "A cube of side 2 has SA 6×4=24, not 8. 8 would be if you counted only a couple of faces."),
  s("maths", G, "m-bearing", "A bearing is from north, clockwise",
    "035° is 35° east of north. Three digits. It is not an angle inside a random triangle unless you draw north.",
    "Bearings are just the acute angle on the diagram.",
    "Draw north lines, measure clockwise from north, keep three digits. Back bearing = +180° (mod 360).",
    "A bearing of 090° is east. 270° is west. ‘To the right’ depends on which way you stand."),
  s("maths", G, "m-coords-midpoint", "Midpoint averages the coordinates",
    "M = ((x1+x2)/2, (y1+y2)/2). It is the average of positions, not the average of the distances as a vibe.",
    "Midpoint of (1,2) and (5,8) is (4,6) because you subtract.",
    "Add x’s, divide by 2; same for y. Check it is halfway on a sketch.",
    "(1,2) to (5,8): midpoint (3,5). Distance would use Pythagoras, a different tool."),
  s("maths", G, "m-transform-translate", "A translation is a slide, not a stretch",
    "Vector (3,−2) means +3 x, −2 y. Shape, size, angles stay. It is not a scale.",
    "Translation by 3 means multiply every coordinate by 3.",
    "Add the vector to every vertex. Check one point thoroughly.",
    "(1,4) + (3,−2) = (4,2). Not (3,−8). Not (1×3, 4×−2) unless someone said scale."),
  s("maths", C, "m-mean-vs-median", "The mean is a fair share; the median is the middle",
    "Mean = total / count. Median = middle of an ordered list. An outlier yanks the mean harder.",
    "Mean and median are the same word in statistics.",
    "Order the list for median. Add and divide for mean. If one value is wild, say so.",
    "1,2,3,4,100: median 3, mean 22. ‘Typical’ needs a word you choose."),
  s("maths", C, "m-range-spread", "Range is a blunt spread",
    "Range = max − min. Two classes can share a mean and not share a range.",
    "Range is the average of the biggest and smallest.",
    "Subtract min from max. For a better spread story, later paths use IQR or standard deviation.",
    "2, 5, 5, 20: range 18, not 5 because 5 appears often."),
  s("maths", C, "m-bar-vs-hist", "A bar chart is categories; a histogram is bins",
    "Bars for colours of cars can have gaps. Histograms for heights glue bins; area (not just height) can carry frequency.",
    "Any graph with rectangles is a histogram.",
    "Ask: are the x-values categories or a number line? Choose the matching graph.",
    "‘Favourite sport’ wants bars. ‘Time to run 100 m’ wants a histogram."),
  s("maths", C, "m-probability-0-1", "Probability lives between 0 and 1",
    "0 is impossible, 1 is certain. 0.2 is 1 in 5, or 20%. 120% as a probability is a marketing leak.",
    "A probability of 2 means twice as certain as certain.",
    "Favourable over equally likely outcomes, if that model holds. Convert % by dividing by 100.",
    "A fair six-sided die: P(even)=3/6=1/2, not 2 because even numbers are 2,4,6 and you added labels."),
  s("maths", C, "m-independent-and", "Independent AND multiplies",
    "P(two heads in a row) on a fair coin = 1/2 × 1/2 = 1/4, if flips do not care about each other.",
    "AND means add, because you want more things.",
    "If independent, multiply. If they cannot both happen, that is mutually exclusive — different rule (add, with care).",
    "P(6 and 6) on two dice = 1/36, not 1/6. You need both."),
  s("maths", C, "m-mutually-exclusive-or", "OR for disjoint events adds",
    "P(heart or spade) = 13/52 + 13/52 = 1/2. You cannot draw both from one card.",
    "OR always multiplies, because OR sounds like a mash.",
    "If they cannot happen together, add. If they can overlap, add and subtract the overlap (inclusion).",
    "P(even or 5) on a die = 3/6 + 1/6 = 4/6. 5 is not even, so no overlap tax."),
  s("maths", C, "m-sample-bias", "Who you asked is the result",
    "A survey at a tram stop at 2 am is not ‘Australians’. Bias is a sampling story, not a rude word.",
    "Bigger samples are automatically fair, even if they are all your cricket team.",
    "Ask who is missing, who volunteered, and what the question pushed. Then talk about the number.",
    "1000 self-selecting tweets are not 1000 random people. Volume is not a sampling method."),
  s("maths", C, "m-outlier-check", "An outlier is a suspect, not a delete key",
    "A point far from the pack may be a typing error (5.0 vs 50) or a real rare event. You need a reason to drop it.",
    "Delete the biggest number so the mean looks tidy.",
    "Check the raw record, the units, and the context. Report with and without if it changes the story.",
    "A 250 km/h ‘car speed’ in a school zone is more likely a missing decimal than a supercar."),
  s("maths", C, "m-two-way-table", "A two-way table is a cross of categories",
    "Rows one variable, columns the other. Totals on the edges. Conditional probability is a row (or column) as the new whole.",
    "Add every number in the table and call that P(A and B).",
    "Find the cell, then divide by the matching total (all, or the row you were told to live in).",
    "If 20 of 50 students play sport, and 8 of those 20 also do music, P(music | sport)=8/20, not 8/50."),
  s("maths", C, "m-expected-value", "Expected value is a long-run average",
    "E = sum of (value × probability). A $10 raffle with 1/100 of $200 has E=$2, so $10 is a donation if you wanted the mean.",
    "The expected value is the prize you will definitely win.",
    "Multiply each outcome by its probability, add. Compare to the cost.",
    "A game you win $5 with probability 1/2 and $0 otherwise has E=$2.50, not $5."),
  s("maths", C, "m-scatter-correlation", "Correlation is not a boss of causation",
    "Points trending up together are associated. Ice cream and drowning both rise in summer; heat is the lurking variable.",
    "If r looks strong, one variable causes the other. Always.",
    "Describe the association, look for a lurking variable, and do not write ‘causes’ from a scatter alone.",
    "A tight line of school shoes vs reading age can just be ‘age’. Correlation still wants a story."),
  s("maths", A, "m-quadratic-roots", "Roots are where the parabola kisses the x-axis",
    "Solutions of y=x²−5x+6 are x=2 and x=3 because (x−2)(x−3)=0. They are x-intercepts, not the vertex automatically.",
    "The roots are the number in front of x², because that number looks important.",
    "Factor, or use the quadratic formula, then check by substituting back into the original.",
    "Vertex of this one sits at x=2.5, between the roots. Vertex is a different question from ‘where is y=0’."),
  s("maths", C, "m-boxplot-iqr", "A box plot is a five-number story",
    "Min, Q1, median, Q3, max. IQR = Q3−Q1 is the middle half. Whiskers are not error bars from a lab.",
    "The box is the mean plus or minus the range.",
    "Read the five numbers, compute IQR, and compare two plots by median and spread — not by which box is prettier.",
    "A long whisker means a tail, not a mistake, until you check the raw list."),
];
