import { s } from "./s.mjs";

const M = "Matter extras";
const E = "Earth & space";
const B = "Body systems";
const N = "Energy extras";
const L = "Living extras";

export const SCIENCE_SEEDS = [
  s("science", M, "s-periodic-groups", "A group is a family of habits",
    "Columns share valence patterns. Alkali metals (group 1) get more reactive down the column; noble gases mostly do not form everyday compounds.",
    "Elements in a period (row) are the family, because they sit next to each other.",
    "Read group for similar chemistry, period for electron shells filling. Atomic number is protons, not a popularity rank.",
    "Sodium and potassium both make +1 ions. That is group behaviour, not a coincidence of names."),
  s("science", M, "s-physical-vs-chem", "A phase change is not a new substance",
    "Melting ice is H2O(s) → H2O(l). Same molecules, different arrangement. Burning methane makes new molecules.",
    "If it looks different, it is a chemical change. Always.",
    "Ask: can I get the same stuff back by changing temperature/pressure, or did atoms rearrange?",
    "Dissolving salt is usually taught as physical (ions still there). You can boil the water off. Contrast with electrolysis."),
  s("science", M, "s-conservation-mass", "Atoms are not created in a beaker",
    "A closed rusting jar gains no magic mass from nowhere; oxygen from the air joins the iron. Open-air rust looks heavier because of that join.",
    "Rusting ‘uses up’ iron so the world has fewer atoms of iron.",
    "Count atoms on both sides of a balanced equation. Mass is a tally of those atoms plus the invisible gas.",
    "2Mg + O2 → 2MgO. The ash can weigh more than the ribbon. The extra is oxygen, not a miracle."),
  s("science", M, "s-ph-scale", "pH 3 is not ‘a bit more than 4’",
    "pH is logarithmic. Each whole number is a ten-times change in H+ concentration. pH 3 is ten times more acidic than pH 4.",
    "pH 1 is only slightly stronger than pH 2 because 1 and 2 are close.",
    "Lower pH, more H+. Neutral is 7 at standard conditions. Household acids and alkalis sit on this ladder.",
    "Stomach acid near pH 2 vs rain near 5.6 is not ‘three steps, so 3×’. It is 10³ if you compare 2 and 5."),
  s("science", M, "s-mixture-compound", "A mixture keeps the recipes of its parts",
    "Air is a mixture; water is a compound. You can (in principle) sieve or distill a mixture without breaking molecules.",
    "Salt water is a new compound called saltwaterite.",
    "Compounds have a fixed ratio and need chemical change to undo. Mixtures have variable recipes and physical separations.",
    "Alloys are mixtures of metals. Bronze is not a new element."),
  s("science", M, "s-endothermic", "Endothermic does not mean ‘cold forever’",
    "An endothermic change takes energy in (photosynthesis, some instant ice packs). The surroundings can feel cooler while the system stores energy.",
    "Endothermic means the reaction cannot happen.",
    "Follow energy: in vs out. Exothermic heats the surroundings (combustion). Instant cold packs are a designed endothermic dissolve.",
    "A candle is exothermic. The wax plus oxygen have more stored chemical energy than the CO2 and water you get."),
  s("science", M, "s-catalyst-path", "A catalyst is a cheaper door, not a free lunch",
    "Catalysts lower activation energy and are not used up as a net reactant. They do not change the energy difference between start and finish.",
    "A catalyst adds energy to the products so you get more stuff.",
    "Name the door (lower Ea), keep the start/finish energies. Enzymes are biological catalysts with picky shapes.",
    "A used-up metal powder that becomes a new compound is a reactant, not a catalyst, even if the label lied."),
  s("science", M, "s-isotope", "Isotopes share protons, not neutrons",
    "Carbon-12 and carbon-14 both have 6 protons. 14 has two extra neutrons. Chemistry is mostly the proton count; mass and stability can differ.",
    "Isotopes are different elements that look similar on a poster.",
    "Same atomic number, different mass number. Radioisotopes decay; many isotopes do not.",
    "C-14 dating uses a radioactive carbon isotope. C-12 is the stable majority in you."),
  s("science", M, "s-ionic-vs-covalent", "Ionic is a steal; covalent is a share",
    "Metal + non-metal often ionise (NaCl). Two non-metals often share (O2, H2O). The bond name is a model, not a moral.",
    "All bonds are the same because everything is atoms.",
    "Ask who is in the pair. Look at melting point and whether it conducts when molten as extra clues.",
    "Table salt in water conducts because ions can move. Sugar water is covalent molecules — sweet, not a great conductor."),
  s("science", M, "s-concentration", "Concentration is amount per volume",
    "A darker cordial can be more concentrated, or just a deeper glass. mol/L or g/L is the honest unit.",
    "More litres always means more concentrated because there is more drink.",
    "Amount of solute divided by volume of solution. Dilute by adding solvent — the solute count stays, the volume rises.",
    "10 g in 100 mL is more concentrated than 10 g in 1 L. Same sugar, different crowd."),
  s("science", E, "s-seasons-tilt", "Seasons are a tilt, not a closer hug",
    "Earth is slightly closer to the Sun in a southern summer? Actually perihelion is early January — so distance is the wrong story. Tilt changes day length and sun angle.",
    "Summer happens because Earth is nearer the Sun for everyone.",
    "Tilt toward the Sun: steeper rays, longer days. Australia’s summer is not ‘closer’, it is ‘tilted to face’.",
    "If distance ran the seasons, both hemispheres would summer together. They do not."),
  s("science", E, "s-day-night-spin", "Day and night are a spin",
    "Earth rotates about its axis in about 24 h. The Sun ‘rises’ because we turn, not because the Sun orbits us daily.",
    "The Sun races around Earth once a day. That is why it looks like it moves.",
    "Rotate the globe toward the light. Night is the shadow side. Time zones are slices of that spin.",
    "A solar eclipse is a Moon shadow, a different geometry from ordinary night."),
  s("science", E, "s-moon-phases", "Phases are a lighting angle, not a bite",
    "We see the half of the Moon that faces the Sun. The ‘crescent’ is that lighting from our seat, not Earth’s shadow (that would be an eclipse).",
    "A crescent Moon has a piece eaten by Earth’s shadow every month.",
    "Moon orbits, sunlight stays. Draw Sun–Moon–Earth angles. Eclipses are rare alignments.",
    "New Moon is the dark-facing-us time, not ‘the Moon took a week off’."),
  s("science", E, "s-plate-boundaries", "Plates do not care about country borders",
    "Earthquakes cluster at plate edges: diverge, converge, slide. Australia sits mid-plate, so big quakes are rarer — not impossible.",
    "Continents float free each year by thousands of kilometres.",
    "Match the boundary type to the hazard (volcanoes at many converge/diverge; transform likes strike-slip quakes).",
    "The Himalaya is a collision, not a pile of wind-blown dirt. The Mid-Atlantic Ridge is a zipper opening."),
  s("science", E, "s-rock-cycle", "Rocks are recipes that can be remade",
    "Igneous from melt, sedimentary from bits, metamorphic from heat/pressure. The cycle is paths, not a one-way career.",
    "Once a rock is igneous it can never be anything else.",
    "Name the last process: melt+cool, deposit+cement, or cook-and-squash. A sandstone can become quartzite.",
    "Fossils live in sedimentary stories. Granite is a slow-cool igneous story."),
  s("science", E, "s-water-cycle", "The water cycle is the same water on tour",
    "Evaporation, condensation, precipitation, runoff/infiltration. Energy from the Sun lifts water; gravity brings it back.",
    "New water is created in clouds when we need rain.",
    "Follow a drop: ocean → vapour → cloud → rain → river → ocean. Groundwater is the slow queue.",
    "Desalination is a human shortcut, not a new cycle. The salt stays unless you plan for it."),
  s("science", E, "s-greenhouse", "Greenhouse gases are a blanket, not a window tax",
    "CO2, methane, water vapour let visible light in and hold some infrared on the way out. More blanket, more stored heat.",
    "The greenhouse effect is a hoax because greenhouses are made of glass and the atmosphere is not.",
    "Name the gases, the infrared, and the difference between the necessary natural blanket and extra human forcing.",
    "Venus is an extreme greenhouse story. ‘Glass vs gas’ is a metaphor, not a court case."),
  s("science", E, "s-ozone-vs-climate", "Ozone holes are not the same dial as climate",
    "Stratospheric ozone absorbs UV. CFCs punched a hole. That is a different molecule story from CO2’s infrared blanket.",
    "Fix the ozone hole and climate change is solved, because both are ‘atmosphere’.",
    "Keep the two files: UV shield vs heat budget. Some gases overlap stories; the mechanisms do not collapse into one.",
    "The Montreal Protocol is an ozone success. It is not a substitute for carbon maths."),
  s("science", E, "s-stars-fusion", "Stars are fusion engines, not campfires",
    "Hydrogen nuclei fuse to helium in main-sequence stars, releasing energy (E=mc² neighbourhood). A campfire is a chemical rearrange.",
    "The Sun burns coal. That is why it is yellow.",
    "Nuclear fusion in the core, radiation out. Chemical burning cannot last billions of years on a Sun-sized budget.",
    "When core hydrogen runs low, the star’s later acts (giants, remnants) depend on mass."),
  s("science", E, "s-solar-system-scale", "Orbits are mostly empty",
    "A classroom-scale Sun the size of a melon puts Earth a long walk away and Neptune off the oval. Posters squash space.",
    "Planets sit a finger-width apart, like the poster.",
    "Separate size scale from distance scale. Moons orbit planets; planets orbit the Sun (plus perturbations).",
    "A light-minute to the Sun vs light-years to stars is why ‘starlight is old’ is not a metaphor."),
  s("science", E, "s-erosion-vs-weathering", "Weathering breaks; erosion moves",
    "Weathering is the breakdown in place. Erosion is the taxi (water, wind, ice, gravity). A cliff can weather for years before a slump erodes it.",
    "They are synonyms on a worksheet.",
    "Ask: did bits leave? If still in place, weathering. If the creek carried them, erosion.",
    "Salt weathering on Sydney sandstone is a coastal specialist. The harbour then moves the grains."),
  s("science", E, "s-fossils-sedimentary", "Fossils keep a sedimentary diary",
    "Hard parts and traces bury in sediment that lithifies. Granite will not keep a fern the same way.",
    "Dinosaurs are found in granite because granite is old and strong.",
    "Look in sedimentary layers, read superposition (oldest usually under, unless overturned), and watch for index fossils.",
    "A footprint is a trace fossil. It is still evidence. Soft-tissue fossils are the rare jackpot."),
  s("science", B, "s-heart-two-circuits", "Humans run a double loop",
    "Pulmonary circuit: heart → lungs → heart. Systemic: heart → body → heart. Oxygen pick-up and delivery are different errands.",
    "Blood goes heart → body → lungs → heart in one simple circle like a cartoon.",
    "Right side to lungs, left side to body. Valves stop backflow. Pulse is a pressure wave, not the blood doing a lap in one beat.",
    "A hole between sides (some defects) mixes the errands. That is why the double loop matters."),
  s("science", B, "s-lungs-alveoli", "Alveoli are the exchange rooms",
    "Thin walls, huge surface area, capillaries next door. O2 in, CO2 out by diffusion — high to low concentration.",
    "The lungs blow oxygen into the blood with tiny fans.",
    "Name diffusion, surface area, and the moisture. Asthma and smoke are surface-area/airway stories.",
    "You do not ‘absorb air’. You exchange gases. Nitrogen mostly just visits."),
  s("science", B, "s-digest-absorb", "Digestion is disassembly; absorption is the pickup",
    "Enzymes cut polymers to small bits. The small intestine’s villi pick them up. A long tube is not enough without the chemistry.",
    "The stomach absorbs everything because it is famous.",
    "Mouth/stomach start; small intestine does most absorbing; large intestine reclaims water. Liver gets a first look via the portal vein.",
    "Fibre can be important and still not ‘digested’ the same way sugar is. Gut microbes get a vote."),
  s("science", B, "s-neuron-one-way", "A neuron is a one-way wire with chemistry at the gap",
    "Electrical along the axon, chemical across the synapse. The next cell has to have receptors. It is not copper.",
    "Nerves are hollow tubes that squirt thoughts.",
    "Direction: dendrites/cell body → axon → synapse. Reflex arcs can skip the long chat with the brain.",
    "Myelin speeds the hop. Damage to myelin (some diseases) is a speed story."),
  s("science", B, "s-immune-self", "Immunity is a self/not-self argument",
    "White cells and antibodies tag non-self. Vaccines show a safe preview so memory cells wait. Autoimmune is the argument going wrong.",
    "Antibiotics kill viruses if you take them for a cold to be safe.",
    "Virus vs bacterium first. Vaccines train; antibiotics are for many bacteria, not virions. Finish the prescribed course when they are indicated.",
    "Herd immunity is a community threshold, not a personal vibe."),
  s("science", B, "s-homeostasis", "Homeostasis is a thermostat, not a freeze-frame",
    "Blood sugar, temperature, water: sensors, control, effectors. Negative feedback turns the response down as you near the set point.",
    "Healthy bodies never change. Change is disease.",
    "Name the sensor and the reverse action (sweat when hot, shiver when cold). Diabetes is a glucose-regulation story.",
    "Positive feedback (birth contractions) is the rare ‘push harder’ loop. Do not call every loop negative."),
  s("science", B, "s-skeleton-levers", "Bones are levers; joints are the hinges",
    "Muscles pull (they do not push). Antagonistic pairs (biceps/triceps) because a pull needs a partner to go the other way.",
    "Muscles inflate like balloons to lengthen bones.",
    "Find fulcrum (joint), load, and effort. Tendons join muscle to bone; ligaments bone to bone.",
    "A torn ligament is a joint-stability ticket. A torn tendon is a pull-transmission ticket."),
  s("science", B, "s-genetics-allele", "An allele is a version, not a whole extra gene",
    "You inherit two copies of most genes (one from each parent). Dominant/recessive is about how they show, not ‘stronger person’.",
    "Dominant means the trait is better and more common.",
    "Punnett squares are probability for that gene, not destiny for a life. Phenotype is what shows; genotype is the letters.",
    "Brown-eye dominance stories are simplified. Real eye colour is more than one gene."),
  s("science", B, "s-virus-not-cell", "A virus is not a cell on a diet",
    "Viruses need a host to copy. They have genetic material and a coat, not a full metabolism. Antibiotics miss them.",
    "Viruses are tiny bacteria. Treat them the same.",
    "Host, replication, and immune memory. Antivirals are a different shelf from antibiotics.",
    "COVID-era tests looked for viral genetic material or antigens — not ‘a small animal in the nose’."),
  s("science", B, "s-skin-barrier", "Skin is an organ with a job",
    "Barrier, vitamin D factory (with UV), temperature control, sensors. A cut is a broken wall, not just a cosmetic line.",
    "Skin is dead decoration. Only the heart counts as an organ.",
    "Keep the barrier (hygiene without destroying it), watch infection signs, and respect burns as barrier loss.",
    "Sweat cools by evaporation. Humidity makes that job harder — a climate story on your arm."),
  s("science", B, "s-kidney-filter", "Kidneys filter, then reclaim",
    "Nephrons filter blood, then take back water and useful solutes. Urine is the leftovers plus what you needed to dump (urea).",
    "Kidneys store urine. That is why they are hollow.",
    "Filter → reabsorb → secrete. ADH is a water-saving hormone. The bladder is the storage bag, not the filter.",
    "Drinking seawater is a net water loss story — more salt to dump than water gained."),
  s("science", N, "s-conduction-metal", "Metals conduct heat because electrons wander",
    "Delocalised electrons carry energy through a pan. Wood does not, which is why handles exist.",
    "All solids conduct heat equally. Heat is just ‘hotness juice’.",
    "Conduction (touch), convection (fluid movement), radiation (infrared even across vacuum). Name which path a situation uses.",
    "A vacuum flask fights all three: vacuum (no convect/conduct), silvering (radiation), cork (conduct)."),
  s("science", N, "s-electric-circuit", "A circuit is a loop, not a hose that empties",
    "Current is a flow of charge. Voltage is the push. Resistance makes it harder. A break anywhere stops a series loop.",
    "Current gets used up in the first bulb, so the last one is dim because it is last.",
    "Series: one path, current the same. Parallel: branches share voltage. A fuse is a planned weak link.",
    "Electrons drift slowly; the energy signal is fast. ‘Used up current’ is the folk model this path kills."),
  s("science", N, "s-magnet-poles", "Poles come in pairs; field lines are a map",
    "Cut a magnet and you get two smaller magnets, not a lonely north. Field lines leave north and enter south by convention.",
    "You can isolate a north pole if you saw carefully.",
    "Field, force on a current (motor), and induction (generator) are cousins. A coil + motion + field can make a current.",
    "Earth’s magnetic north is a pole story that is not exactly the geographic north. Compasses are honest about the field, not the atlas."),
  s("science", N, "s-waves-medium", "Sound needs a medium; light does not",
    "Sound is a vibration through matter. No air, no chat (space films that boom are lying). Light is an electromagnetic wave and can cross vacuum.",
    "If you can see an explosion in space, you must hear it, because movies are evidence.",
    "Name the wave type. Mechanical vs EM. Frequency × wavelength = speed in that medium.",
    "Thunder after lightning is the same event: light won the race in air."),
  s("science", N, "s-reflection-law", "Angle in equals angle out",
    "On a mirror, measured from the normal (the perpendicular). A rough wall scatters; a lake can glare.",
    "Light bounces randomly off mirrors. That is why you can see your face from any angle equally.",
    "Draw the normal, mark i and r. Refraction is the bend when speed changes in a new medium — next cousin, not the same law.",
    "A periscope is two mirrors at 45°. It is geometry, not a gadget spirit."),
  s("science", N, "s-photosynthesis-energy", "Photosynthesis banks light as sugar",
    "CO2 + water + light → glucose + oxygen (in the school equation). It stores energy; respiration in cells spends it.",
    "Plants photosynthesise instead of respiring, so they do not need energy at night.",
    "Both happen in plants. Daylight banks sugar; cells still burn it. Stomata are the gas doors.",
    "The oxygen we breathe is a by-product of a water-splitting step. That is a bigger deal than a poster lets on."),
  s("science", N, "s-food-energy-j", "Food energy is joules (or Calories) from bonds",
    "Respiration releases energy from glucose. A label’s kJ is a bomb-calorimeter neighbourhood, not ‘how tired you feel’.",
    "Fat has energy because it is heavy. Heavy things are energetic.",
    "kJ in vs kJ out is a budget, not a moral. Different macronutrients store differently per gram.",
    "A 2000 kJ snack is not 2000 degrees. Degrees are temperature; joules are energy."),
  s("science", N, "s-renewable-grid", "Renewable is a source story; dispatchable is a timing story",
    "Solar and wind are renewable and variable. Hydro and batteries help time-shift. ‘Baseload’ is a grid-behaviour word, not a moral.",
    "If it is renewable it is always on, because nature is generous.",
    "Match source, storage, and demand. A sunny noon and a 6 pm kettle spike are different minutes.",
    "A rooftop panel does not make a house an island unless you planned storage and protection for lineworkers."),
  s("science", L, "s-classification", "Classification is a nested filing cabinet",
    "Domain → … → genus → species. A species name is binomial (Homo sapiens). It is a hypothesis about relatedness, updated with evidence.",
    "Common names are safer because scientists change their minds.",
    "Use traits and now DNA. ‘Fish’ in everyday talk is not a clean clade. Platypus is a mammal that lays eggs — the cabinet has odd drawers.",
    "A dingo’s name is a taxonomy-and-culture argument. The filing cabinet is not finished."),
  s("science", L, "s-food-web", "A web is arrows of energy, not friendship",
    "Arrows point to the eater (energy to the consumer). Knock out a node and the effects branch. A chain is a simplified path through a web.",
    "Arrows point to the food, because that is who gets eaten, so the arrow should look scared.",
    "Draw producer → consumer. Count trophic steps. 10% rule is a rough leak of energy up the chain.",
    "A dingo–kangaroo–grass story is still a web once insects, fire, and people walk in."),
  s("science", L, "s-adaptation-not-wish", "An adaptation is a heritable fit, not a wish",
    "Thick leaves in a banksiadry heath are a selected trait over generations. One thirsty plant does not ‘decide’ to grow thicker leaves this afternoon as evolution.",
    "Giraffes stretched their necks because they wanted leaves, and wanting is inheritance.",
    "Variation, selection, inheritance. Acclimatisation (you tan) is not the same as a population evolving.",
    "Cane toads have evolved some predator stories in Australia already. That is selection on a short, ugly clock."),
  s("science", L, "s-photosynth-resp-cycle", "Carbon walks between air and bodies",
    "Photosynthesis pulls CO2 in; respiration and burning push it out. A forest is a stock; a fire is a flux.",
    "Trees destroy carbon. That is why planting one tree deletes climate change.",
    "Follow atoms: air → sugar → biomass or breath. Fossil fuels are old stock unlocked quickly.",
    "The ocean also stores carbon. A tree is not a magic bin that never respires or burns."),
  s("science", L, "s-microbe-roles", "Most microbes are not villains",
    "Nitrogen fixers, gut communities, decomposers. Pathogens are the famous minority. Sterile is not always safer.",
    "All bacteria are germs. The only good microbe is a dead one.",
    "Name the job: recycle, digest, infect, ferment. Antibiotics are a tool with collateral.",
    "Yeast making bread is a microbe you invited. Compost is a microbial workforce."),
  s("science", L, "s-water-quality", "A river can look clean and still be sick",
    "Dissolved oxygen, turbidity, nutrients, macroinvertebrates. Algal blooms after fertiliser are a nutrient story, not a ‘green means healthy’ story.",
    "If you cannot see dirt, the water is fine to drink.",
    "Measure more than clarity. Nitrates, bugs, and oxygen tell on farms and sewage.",
    "A platypus in the creek is a clue, not a lab certificate. Still nicer than foam."),
  s("science", L, "s-introduced-species", "Introduced is about the ecosystem, not a passport stamp",
    "Rabbits, cane toads, lantana: they win because controls that held them at home are missing. Native can still be pests in a changed place.",
    "If it is cute it is native. If it is ugly it is introduced.",
    "Ask: what did it outcompete, eat, or infect? Management is evidence, not a vibe about foreigners.",
    "Brumbies and dingoes sit in different political stories. Biology still asks about grazing and predation."),
  s("science", L, "s-fire-regimes", "Fire is a regime, not a single match",
    "Frequency, intensity, season. Some Australian plants need smoke or heat to germinate. Too often, or too hot, still wrecks the script.",
    "All fire is destruction. The only good bush is one that never burns.",
    "Read the species. Cool patchy burns vs crown fires are different tools. People and climate shift the regime.",
    "A banksia cone can hold seed until fire. A rainforest pocket may not forgive the same flame."),
  s("science", L, "s-mitosis-meiosis", "Mitosis copies; meiosis shuffles",
    "Mitosis: two same-ish body cells. Meiosis: gametes with half the chromosomes and new mixes. That is why kids are not clones.",
    "Meiosis is just mitosis twice for extra luck.",
    "Count the products and the chromosome number. Crossing over is a meiosis extra.",
    "Cancer is mitosis out of control, not ‘too much meiosis’. Different files."),
  s("science", L, "s-stimulus-response", "A tropism is a plant’s slow reply",
    "Phototropism: grow toward light (auxin story). Not a brain. Still a stimulus–response chain.",
    "Plants move because they want to, the way you want a snack.",
    "Name stimulus, receptor, response. Roots and gravity (gravitropism) are the other classroom classic.",
    "A sunflower face is more complicated than ‘always looks at the sun’, but the hormone-and-growth idea still holds for shoots."),
  s("science", L, "s-biodiversity", "Diversity is more than a species count",
    "Richness (how many kinds) and evenness (how stacked). A plantation of one tree can be green and poor.",
    "Biodiversity means ‘lots of animals I can name’.",
    "Count kinds, look at evenness, and include genes and habitats. A coral garden is a diversity engine.",
    "Australia’s endemic species are a uniqueness story. Losing them is not ‘replaced by a similar pigeon’."),
  s("science", M, "s-particle-pressure", "Pressure in a gas is collisions on a wall",
    "More particles, more speed (temperature), or less volume → more hits. A bike pump heats because you did work on the gas.",
    "Pressure is the weight of air sitting still like a brick.",
    "Link P, V, T in words: squeeze, heat, or add gas. Units later; the collisions now.",
    "A dented ping-pong ball in hot water pops out because the air inside pushed harder as it warmed."),
  s("science", E, "s-tides-moon", "Tides are a two-bulge story",
    "The Moon’s gravity plus Earth’s motion make two tidal bulges. The Sun joins in (spring/neap). Spinning Earth under the bulges makes the rhythm.",
    "Tides happen because the Moon soaks up water and then wrings it out.",
    "Two high tides in many places, spring when Moon and Sun line up. Local coasts mess with the simple model.",
    "A king tide is a coincidence of astronomy and weather/sea level — not a new moon creature."),
  s("science", N, "s-efficiency", "Efficiency is useful out over total in",
    "A 40% efficient motor dumps 60% as heat and sound. Perpetual motion would need 100% plus a gift.",
    "If you cannot feel heat, the machine is 100% efficient.",
    "Useful energy ÷ input × 100%. Name what ‘useful’ meant (motion, light, heat for a kettle).",
    "An LED is more efficient at making light than an old incandescent, which was a heater that glowed."),
];
