import { s } from "./s.mjs";

const H = "Hardware extras";
const N = "Networking extras";
const O = "OS extras";
const S = "Security extras";
const P = "Printers & peripherals";
const C = "Shop craft";

export const TECH_SEEDS = [
  s("tech", H, "t-soldered-ram", "Soldered RAM is not an upgrade path",
    "Many ultrabooks glue LPDDR to the board. Task Manager showing 8 GB does not mean a slot is hiding under a door.",
    "Order two SODIMMs because every laptop has two slots if you look hard enough.",
    "Read the FRU / service manual. If memory is onboard, sell a different machine or live with the size.",
    "Some boards mix one SODIMM with onboard. Mixing sizes can disable dual channel. Matched pairs or leave it."),
  s("tech", H, "t-nvme-lanes", "M.2 slots are not all the same speed",
    "An M.2 slot may be SATA, PCIe 3.0×2, or PCIe 4.0×4. The sticker on the drive is not a promise from the board.",
    "Any 2280 NVMe will run at the box speed in any M.2 slot.",
    "Check the board diagram: keying (B/M), length, and which CPU/chipset lanes that slot actually owns.",
    "A SATA-only M.2 will ignore an NVMe drive. Boot order can hide a perfectly good disk behind a disabled slot."),
  s("tech", H, "t-thermal-paste", "Thermal paste is a thin job",
    "Paste fills microscopic gaps between IHS and cooler. A rice-grain or pea in the centre usually spreads under spring pressure.",
    "More paste is cooler. Spread a thick frosting so no air can possibly remain.",
    "Pea or line, mount with even pressure, check the pump/fan header actually spins.",
    "Dried factory paste on a laptop heat pipe is a real slowdown. Too much paste is an insulator, not a gift."),
  s("tech", H, "t-psu-rails", "A 500 W label is not a 12 V promise",
    "Modern CPUs and GPUs drink from the 12 V rail. A bargain unit can be 500 W combined and still starve 12 V under a gaming spike.",
    "If the box says 500 W, any GPU in that wattage class will be happy.",
    "Read the 12 V amperage, the 80 Plus tier, and the CPU/GPU 8-pin count. Peak vs continuous matters.",
    "Undersized PSUs brown-out as random reboots, not a polite ‘insufficient power’ toast."),
  s("tech", H, "t-raid-is-not-backup", "RAID is not a backup",
    "RAID 1/5/10 keeps you online after a disk dies. Ransomware, fire, and ‘wrong folder deleted’ laugh at RAID.",
    "Mirror the system disk and you can skip offsite backups.",
    "Keep RAID for uptime. Keep 3-2-1 backups for survival. Test a restore or you have a ritual.",
    "A RAID controller with cache needs a BBU or you can lose in-flight writes during a power cut."),
  s("tech", H, "t-ecc-vs-consumer", "ECC RAM is a different conversation",
    "ECC catches bit flips. Servers and some workstations want it. Most consumer boards will not even POST with ECC DIMMs.",
    "Buy ECC for a gaming PC because more expensive RAM is always more stable.",
    "Match the motherboard QVL: unbuffered ECC vs registered, and the CPU’s memory controller.",
    "Workstations that do support ECC still need the right SKU of CPU. The sticker on the DIMM is not enough."),
  s("tech", H, "t-bios-cmos", "Clearing CMOS is a blunt instrument",
    "A CMOS reset drops custom fan curves, boot order, XMP, and the admin password on many boards — and nothing else.",
    "Clear CMOS to uninstall malware from Windows.",
    "Use it for POST-beep mysteries, forgotten BIOS passwords (if the board allows), and after a failed BIOS setting. Then reset time and boot order.",
    "Some laptops hide a jumper; others want a power drain with the pack out. The coin cell is not a Windows password."),
  s("tech", H, "t-usb-power-delivery", "USB-C charge is a negotiation",
    "USB Power Delivery profiles are a handshake. A 100 W brick does not force 100 W into a 45 W laptop, and a charge-only port may refuse video.",
    "Any USB-C cable and any USB-C brick will fast-charge and output DisplayPort.",
    "Check e-marker cables, PD wattage, and whether the port does DisplayPort Alt Mode or is charge-only.",
    "A 3 A cable on a 5 A laptop is a slow charge, not a mystery battery failure."),
  s("tech", H, "t-laptop-battery", "A swollen pack is a safety ticket",
    "Li-ion swelling is chemistry failure. It lifts trackpads and cracks glass. Do not puncture, crush, or ‘calibrate it flat’.",
    "Keep using a swollen battery until the next maintenance window — swelling is cosmetic.",
    "Power down, isolate the pack, replace with the FRU, recycle at a proper drop-off.",
    "Windows battery reports are not a swelling test. Look at the chassis. A 1 mm lift is enough."),
  s("tech", N, "t-private-rfc1918", "RFC1918 is not ‘the internet’",
    "10/8, 172.16/12, and 192.168/16 are private. They are not routable on the public internet without NAT or a tunnel.",
    "Give a printer a 192.168 address on the WAN port so the world can find it.",
    "Private on LAN, public or CGNAT on WAN. If two sites both use 192.168.1.0/24, VPN will cry.",
    "APIPA 169.254/16 means DHCP failed. It is not a clever private plan."),
  s("tech", N, "t-dhcp-apipa", "169.254 means DHCP never answered",
    "APIPA is a link-local consolation prize. The host can talk to other APIPA neighbours on the same L2, not to the default gateway.",
    "169.254.x.x is a valid office plan if you are in a hurry.",
    "Check cable/link light, VLAN, DHCP pool exhaustion, and whether a helper address is missing on the router.",
    "A static IP ‘to fix it’ without a ticket hides the broken scope until the next device arrives."),
  s("tech", N, "t-dns-vs-ping", "Ping is not name resolution",
    "Ping 8.8.8.8 tests a path. Ping office.example tests DNS plus a path. They fail for different reasons.",
    "If ping to a name fails, the internet is down. Reboot the WAN router and leave.",
    "Split the problem: ping an IP, then resolve the name, then check the client DNS suffix.",
    "A hosts file override can make one PC look fine while the whole office DNS is on fire."),
  s("tech", N, "t-vlan-access", "An access port is one VLAN, not a vibe",
    "Access ports untag a single VLAN. Trunks carry many. A phone+PC may want voice VLAN plus data — that is a special case, not ‘set it to trunk and hope’.",
    "If two PCs cannot see each other, make every port a trunk so VLANs stop mattering.",
    "Match switchport mode and VLAN ID to the design. A native VLAN mismatch is a silent drop, not an error balloon.",
    "VLAN 1 as a leftover default is how guest Wi-Fi accidentally hugs payroll."),
  s("tech", N, "t-wifi-6-vs-range", "A new Wi-Fi generation is not a longer radio",
    "802.11ax (Wi-Fi 6) is about capacity and OFDMA, not magic metres through brick. 5/6 GHz dies on walls faster than 2.4.",
    "Upgrade the AP generation and the shed will suddenly get full bars.",
    "Place APs for coverage, pick the band the client can hear, and stop hiding the SSID as a security plan.",
    "A mesh node in a metal filing cabinet is still a metal filing cabinet."),
  s("tech", N, "t-nat-loopback", "Hairpin NAT is a SOHO surprise",
    "Phones on the LAN that try to reach the office by its public name often need NAT loopback. Many cheap routers refuse.",
    "If the public URL works from the cafe but not from inside, the certificate is fake.",
    "Use an internal DNS name or enable hairpin if the router has it. Do not ‘fix’ it by putting the server on the WAN.",
    "Split DNS (internal view vs public view) is the grown-up version of this ticket."),
  s("tech", O, "t-win-safe-mode", "Safe Mode is a diagnostic hat",
    "Safe Mode loads a minimal set of drivers. If the crash dies in Safe Mode, a third-party driver or autostart is a suspect.",
    "Safe Mode reinstalls Windows automatically.",
    "Boot Safe Mode, disable the last driver/startup, then return to normal. Capture a dump if it still dies.",
    "Safe Mode with Networking is for when you need a patch, not a holiday from Ethernet."),
  s("tech", O, "t-linux-permissions", "chmod 777 is not a fix",
    "Linux permissions are owner/group/other with rwx. 777 means everyone can write. That is a welcome mat, not a repair.",
    "If a service cannot write a file, chmod 777 the whole tree and move on.",
    "Fix owner, group, and the actual bit that was missing. Check mount options (noexec, nosuid) before blaming chmod.",
    "A sticky bit on /tmp is why other users cannot delete your files there. Do not ‘clean it’ with 777."),
  s("tech", O, "t-macos-sip", "SIP is not a virus scanner",
    "System Integrity Protection stops even root from writing to some system paths. It is a seatbelt, not XProtect’s whole job.",
    "Turn off SIP whenever an app asks, because the app knows best.",
    "Leave SIP on. If a vendor needs it off, treat that as a smell and look for a supported install path.",
    "Recovery-mode commands that disable SIP will outlive the ticket unless you turn it back on."),
  s("tech", O, "t-windows-profile", "A corrupted profile is not a dead disk",
    "Windows can boot and still fail one user hive. Other local accounts working is the tell.",
    "Reinstall Windows when one user sees a temp profile.",
    "Copy data from the old profile, recreate the account or repair NTUSER.DAT with a known-good process — after a backup.",
    "OneDrive and folder redirection can look like a profile failure when the path is just offline."),
  s("tech", O, "t-update-rings", "Defer is not ‘never’",
    "Windows quality vs feature updates, and Intune/WSUS rings, are a schedule. Pausing 35 days is not a security strategy.",
    "Turn off updates forever so line-of-business software never breaks.",
    "Pilot ring, then broad. Pause only with a calendar reminder and a compensating control.",
    "A machine that ‘never updates’ is the one ransomware tutorials assume."),
  s("tech", S, "t-phishing-urgency", "Urgency is the payload",
    "Phishing works by compressing time: CEO wants gift cards now. The link is optional; the panic is required.",
    "If the logo looks sharp, the request is real.",
    "Slow the ticket. Verify out of band (known number, known chat). Look at the actual domain, not the display name.",
    "A ‘too busy to check’ culture is an open relay. Train the pause, not the fear of the internet."),
  s("tech", S, "t-mfa-fatigue", "MFA prompt spam is an attack",
    "Fatigue bombing hammers push approvals until a tired human taps Allow. Number matching exists because of this.",
    "Approve the prompt so it stops buzzing — it is probably you on another device.",
    "Deny, report, rotate the session. Prefer number matching or hardware keys over tap-to-approve.",
    "Legacy IMAP that bypasses MFA is a side door. Kill it in the tenant."),
  s("tech", S, "t-least-privilege", "Admin every day is a habit, not a need",
    "A standard user plus elevation when required beats running as Domain Admin for email.",
    "Give everyone local admin so tickets about printers go away.",
    "Separate admin account, JIT elevation, and application allow-lists for the tools that actually need it.",
    "Cached admin tokens on a laptop that goes to a cafe are how ‘that one PC’ becomes the domain."),
  s("tech", S, "t-lock-screen", "A lock screen is a control, not rudeness",
    "Win+L / a short idle policy stops the next person at the hot desk reading payroll.",
    "Only lock when you leave for lunch. Walking to the printer is fine.",
    "Short lock timeout on shared desks, privacy screens where shoulders are close, and no passwords on sticky notes.",
    "A ‘we trust our people’ policy does not bind contractors, cleaners, or the next tenant."),
  s("tech", S, "t-wiping-media", "Delete is not destroy",
    "Recycle Bin and quick format leave recoverables. A drive leaving the building needs a real wipe or physical destroy per policy.",
    "Empty Recycle Bin and the disk is safe to sell.",
    "Follow the shop’s media-sanitisation standard (crypto-erase, firmware sanitize, or shred). Record the asset tag.",
    "Failed disks still hold data. ‘It doesn’t spin’ is not a wipe certificate."),
  s("tech", P, "t-print-spooler", "The queue can be the outage",
    "A stuck job or a dying spooler makes every app look broken. The printer’s ready light is not the whole path.",
    "Reinstall Windows when a print job hangs.",
    "Clear the queue, restart spooler, test a local USB print, then chase drivers/ports.",
    "Print Nightmare patched a reason we stopped exposing spooler to the world. Do not ‘fix’ it by sharing spooler inbound."),
  s("tech", P, "t-inkjet-clog", "Dried nozzles are chemistry, not Windows",
    "Infrequent inkjet use clogs. A cleaning cycle wastes ink; a soak is sometimes the honest repair; replacement is sometimes cheaper.",
    "Reinstall the printer driver to unclog cyan.",
    "Print a nozzle check. Clean, then use the printer, or replace the head/cartridge per the model.",
    "A ‘new driver’ ticket that ignores the page of broken cyan lines will bounce."),
  s("tech", P, "t-impact-vs-laser", "Dot matrix still exists for a reason",
    "Impact printers survive multipart carbon forms. Laser will not stamp through three copies.",
    "Replace every warehouse printer with a cheap laser because laser is modern.",
    "Match the media: multipart → impact; office text → laser/LED; photo → inkjet/photo.",
    "Ribbon vs toner vs ink is a supply chain, not a personality test."),
  s("tech", P, "t-scanner-adf", "ADF and flatbed fail differently",
    "A double-feed in the ADF is rollers and separation pads. A blotch on every glass scan is the pane, not the driver.",
    "Reinstall TWAIN when pages skew in the feeder.",
    "Clean rollers/pad, fan the stack, and check paper weight. Clean glass for flatbed artefacts.",
    "A 200-page legal job on a 50-sheet ADF is a mechanical insult."),
  s("tech", C, "t-ticket-scope", "Scope creep is how tickets never close",
    "‘While you are here’ is a new ticket. The original symptom still needs a sentence in the close notes.",
    "Fix everything you notice so the user is delighted, then forget to document the first problem.",
    "Write the request, the cause, the fix, and the leftover risk. Park extras as new work.",
    "A close note that says ‘fixed’ with no verb is how the next tech repeats the job."),
  s("tech", C, "t-change-window", "Prod is not your lab",
    "A firmware flash at 10:00 on a till day is a choice. Change control exists because rollbacks are slower than confidence.",
    "If it worked on one PC, push it to the fleet before lunch.",
    "Pilot, snapshot/backup, change window, smoke test, and a written rollback.",
    "‘The vendor said it was fine’ is not a back-out plan."),
  s("tech", C, "t-esd-strap", "ESD is quiet damage",
    "You can kill a RAM stick without a spark you feel. A strap to ground (and a mat) is cheaper than a mystery POST.",
    "Carpet and a fluffy jumper are fine if you ‘discharge on the case’ once.",
    "Strap on, board on a mat, bag the parts. Humidity is not a policy.",
    "A ‘it worked until I carried it across the office’ stick is a classic ESD obituary."),
  s("tech", C, "t-asset-tag", "If it is not tagged, it is folklore",
    "Asset tags, serials, and a location beat ‘the tall Dell near accounting’.",
    "Skip the CMDB update because you will remember.",
    "Scan the tag, update location/user, and attach the ticket. Future-you is a stranger.",
    "Warranty checks need serials. Stickers peel; record them twice."),
  s("tech", H, "t-post-beeps", "Beep codes are a language",
    "POST beeps (or Capslock blinks on some laptops) point at RAM, GPU, or board before an OS exists.",
    "Reinstall Windows when the box beeps and never displays.",
    "Count the pattern, read that vendor’s table, reseat RAM/GPU, then swap known-good.",
    "A USB stick full of install media will not decode a RAM beep."),
  s("tech", H, "t-display-backlight", "Image dim is not always a dead panel",
    "A faint image with a torch test often means backlight/inverter/LED driver, not a dead LCD.",
    "If the screen is black, the motherboard is dead. Order the board.",
    "Torch test, external monitor, then cable/inverter/panel in that order on a laptop.",
    "A GPU that outputs to HDMI but not LVDS is a cable or lid switch, not ‘Windows theme’."),
  s("tech", N, "t-speed-duplex", "Speed/duplex mismatch is a silent tax",
    "One side 100/full, the other auto that fell to 100/half, equals collisions and sadness.",
    "Hard-set everything to 10/half for stability.",
    "Prefer auto/auto on modern links. If you must hard-set, set both ends the same.",
    "A ‘network is slow’ ticket with a 100 Mbps NIC in a 1 Gb office is sometimes just that."),
  s("tech", N, "t-i6-privacy", "IPv6 privacy addresses rotate on purpose",
    "Temporary IPv6 addresses change. That is privacy, not a flapping NIC.",
    "Disable IPv6 whenever an address looks long, because long is broken.",
    "Use the stable link-local or DHCPv6 identity when you need a reservation. Do not ‘fix’ privacy by killing IPv6 as a reflex.",
    "A dual-stack host that prefers a broken IPv6 path looks like ‘the internet is down’ for some apps only."),
  s("tech", O, "t-event-viewer", "The log is older than the reboot",
    "Event Viewer tells you the first error, not the last popup. Filter by time around the incident.",
    "Clear all logs so the error cannot come back.",
    "Note the Event ID, source, and first occurrence. Search that, not the user’s poetry.",
    "A disk-full warning from Tuesday explains Friday’s mysterious save failure."),
  s("tech", O, "t-gpupdate", "gpupdate is not magic dust",
    "Group Policy applies in order, with refresh intervals. A deny at the OU beats a hopeful gpupdate /force poem.",
    "If a setting did not apply, run gpupdate until it feels true.",
    "gpresult /h, check the OU, blocked inheritance, and whether the PC is even in the right group.",
    "Loopback processing on a kiosk OU surprises people who only thought about user objects."),
  s("tech", S, "t-password-manager", "Reuse is the incident",
    "A unique password in a manager plus MFA beats a clever personal scheme reused on five SaaS boxes.",
    "Change one letter per site so you can remember them all.",
    "Manager, unique secrets, MFA. Rotate when a breach mail lands, not on a folk calendar.",
    "SMS reset on the same reused email is how the manager gets bypassed."),
  s("tech", S, "t-guest-wifi", "Guest Wi-Fi is a fence",
    "Client isolation and a separate SSID/VLAN stop visitors from scanning tills.",
    "One big flat SSID is friendlier and therefore more secure.",
    "Guest network, no LAN access, captive portal if policy says so, and a password you actually rotate.",
    "A printer on guest ‘so the iPad can print’ is how guest becomes LAN."),
  s("tech", P, "t-displayport-daisy", "Daisy-chain needs the right DisplayPort",
    "MST daisy-chain wants DP 1.2+ and a monitor that actually supports it. HDMI-in on the second panel is not a chain.",
    "Any cable between two monitors will extend the desktop.",
    "Check MST, GPU output, and that the first monitor’s output port is DP, not a USB-C that is charge-only.",
    "A 4K+4K chain can run out of bandwidth and drop to 30 Hz. That is maths, not a driver curse."),
  s("tech", C, "t-known-good", "Swap one variable",
    "A known-good cable/PSU/RAM stick tests a theory. Swapping five parts at once writes a mystery novel.",
    "Replace motherboard, CPU, and PSU together to save time.",
    "One change, one test, notes. Return the known-good so the next ticket still has a known-good.",
    "A ‘known-good’ that never goes back to the drawer is how the drawer becomes folklore."),
  s("tech", C, "t-user-error-last", "Do not start at PEBKAC",
    "Users lie by accident and also hardware fails. Ask what changed, reproduce, then talk about clicks.",
    "If the user is senior, it cannot be hardware. If they are new, it cannot be the system.",
    "Reproduce, capture, then teach the click if it really was the click. No shame tax.",
    "A ticket closed as ‘user educated’ with no steps is how you get the same call tomorrow."),
  s("tech", H, "t-storage-trim", "TRIM is for SSDs that the OS can see",
    "TRIM (discard) helps SSD garbage collection. A RAID card or USB bridge may swallow it.",
    "Run TRIM on spinning rust monthly to keep it healthy.",
    "Confirm the OS sees an SSD, the controller passes TRIM, and you are not ‘optimising’ a HDD with a defrag religion on an SSD.",
    "A full disk with no free blocks makes even a fast SSD feel drunk. Leave slack."),
  s("tech", N, "t-proxy-wpada", "A proxy setting can look like a dead WAN",
    "WPAD/PAC files and a stale proxy send browsers into a building that no longer exists.",
    "If websites fail, the fibre is cut. Ignore proxy settings because they are advanced.",
    "Check system proxy, browser override, and PAC URL. Try a raw IP as a split test.",
    "Authenticated proxies plus a wrong clock (Kerberos) are a special kind of sad."),
  s("tech", O, "t-time-sync", "Kerberos hates a wrong clock",
    "If a PC is more than about five minutes off, domain logon and tickets fail in ways that look like ‘password wrong’.",
    "Reset the user’s password when the clock is 20 minutes slow.",
    "Fix time source (NTP / domain), timezone, and CMOS battery if the clock dies at every boot.",
    "A VM that pauses in sleep can drift. Host time sync is a setting, not a wish."),
  s("tech", S, "t-usb-autorun", "Found USB is not free software",
    "Rubber-ducky and poisoned sticks still work on curiosity. Autorun is less eager now; humans are not.",
    "Plug in the USB from the car park to see who left holiday photos.",
    "Do not plug it into a production PC. Hand it to the process your shop actually has (or destroy it).",
    "A data stick the CEO ‘needs right now’ still gets a scan station, not a bypass because of rank."),
  s("tech", P, "t-audio-exclusivemode", "Exclusive mode steals the device",
    "An app in exclusive WASAPI/ASIO mode can make every other sound look like a broken driver.",
    "Reinstall Windows when Teams has sound but Spotify does not.",
    "Disable exclusive mode, pick the same default device, update or roll back the audio driver after a check.",
    "HDMI audio defaulting to a dark TV is a classic ‘laptop is mute’ ticket."),
  s("tech", C, "t-documentation-photo", "A photo is a document",
    "Rear cabling, error LEDs, and the serial plate photograph well. Future-you cannot remember the mess.",
    "Write ‘see above’ and trust memory.",
    "Photo, serial, ticket ID in the filename or notes. Blur secrets.",
    "A rack photo without labels is still better than nothing, but label the ports while you are there."),
  s("tech", H, "t-tpm-bitlocker", "Clearing TPM can be a hostage situation",
    "BitLocker keys live with TPM + PIN/startup key. Clearing TPM without recovery keys is how you invent a brick.",
    "Clear TPM to speed up a Windows reinstall. Recovery is always in the cloud of feelings.",
    "Suspend BitLocker, confirm recovery keys in Azure AD/AD/printout, then change TPM. Keep the key out of the same bag as the laptop.",
    "A board swap is a new TPM. Plan the key before the screwdriver."),
];
