import type { LingoNode } from "@/content/lingo/types";

export const frU01L01: LingoNode = {
  id: "fr-u01-l01",
  lang: "fr",
  unit: 1,
  unitTitle: "Greetings",
  skill: "Say hello",
  title: "Say hello at the door",
  index: 0,
  steps: [
    {
      id: "fr-u01-l01-intro-bonjour",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Bonjour",
      prompt: "Someone opens the door. This is the word you say.",
      native: "Bonjour",
      phonetic: "bon-ZHOOR",
      meaning: "Hello",
      image: "/figures/lingo/door-hello.svg",
      speakTarget: "Bonjour",
      speakGloss: "Hello",
      speak: { silent: true },
      why: "Bonjour is the daylight hello at the door.",
    },
    {
      id: "fr-u01-l01-listen-bonjour",
      kind: "listen-pick",
      type: "listen-pick",
      lemma: "Bonjour",
      prompt: "Listen, then tap the English.",
      native: "Bonjour",
      phonetic: "bon-ZHOOR",
      meaning: "Hello",
      speakTarget: "Bonjour",
      speak: { silent: true },
      choices: [
        { id: "a", label: "Hello", correct: true },
        { id: "b", label: "Thank you", correct: false },
        { id: "c", label: "Goodbye", correct: false },
      ],
      why: "Bonjour means hello.",
      speakFeedbackCorrect: "That greeting is hello.",
      speakFeedbackWrong: "Bonjour is hello at the door.",
    },
    {
      id: "fr-u01-l01-intro-bonsoir",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Bonsoir",
      prompt: "The porch light is on. Evening uses a different hello.",
      native: "Bonsoir",
      phonetic: "bon-SWAHR",
      meaning: "Good evening",
      image: "/figures/lingo/door-evening.svg",
      speakTarget: "Bonsoir",
      speakGloss: "Good evening",
      speak: { silent: true },
      why: "Bonsoir is the evening hello.",
    },
    {
      id: "fr-u01-l01-contrast-jour-soir",
      kind: "contrast",
      type: "contrast",
      prompt: "The sun is down. Which greeting fits the door?",
      native: "Bonsoir",
      speakTarget: "Bonsoir",
      speak: { silent: true },
      choices: [
        { id: "a", label: "Bonsoir", correct: true },
        { id: "b", label: "Bonjour", correct: false },
      ],
      why: "Evening at the door is Bonsoir, not Bonjour.",
      speakFeedbackCorrect: "Evening at the door is Bonsoir.",
      speakFeedbackWrong: "After dark, switch to Bonsoir.",
    },
    {
      id: "fr-u01-l01-intro-salut",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Salut",
      prompt: "A friend, not a stranger. This hello is smaller.",
      native: "Salut",
      phonetic: "sah-LUU",
      meaning: "Hi",
      image: "/figures/lingo/door-friend.svg",
      speakTarget: "Salut",
      speakGloss: "Hi",
      speak: { silent: true },
      why: "Salut is the informal hi.",
    },
    {
      id: "fr-u01-l01-produce-bonjour",
      kind: "produce",
      type: "produce",
      lemma: "Bonjour",
      prompt: "Type the daylight hello you say at the door.",
      meaning: "Hello",
      answers: ["Bonjour", "bonjour"],
      speak: "Type the French hello you use in daylight.",
      why: "Daylight at the door is Bonjour.",
      speakFeedbackCorrect: "Bonjour is the daylight hello.",
      speakFeedbackWrong: "Aim for Bonjour.",
    },
    {
      id: "fr-u01-l01-intro-revoir",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Au revoir",
      prompt: "You turn back down the path. This is how you leave.",
      native: "Au revoir",
      phonetic: "oh ruh-VWAHR",
      meaning: "Goodbye",
      image: "/figures/lingo/door-leave.svg",
      speakTarget: "Au revoir",
      speakGloss: "Goodbye",
      speak: { silent: true },
      why: "Au revoir is goodbye at the door.",
    },
    {
      id: "fr-u01-l01-match",
      kind: "match",
      type: "match",
      prompt: "Match the door words you already met.",
      pairs: [
        { left: "Bonjour", right: "Hello" },
        { left: "Bonsoir", right: "Good evening" },
        { left: "Salut", right: "Hi" },
        { left: "Au revoir", right: "Goodbye" },
      ],
      speak: "Match each French door word to the English you already heard.",
      why: "These four already walked through the door.",
    },
    {
      id: "fr-u01-l01-reuse-bonjour",
      kind: "reuse",
      type: "reuse",
      lemma: "Bonjour",
      prompt: "The door opens at noon. Tap the word.",
      speakTarget: "Bonjour",
      speak: { silent: true },
      choices: [
        { id: "a", label: "Bonjour", correct: true },
        { id: "b", label: "Au revoir", correct: false },
        { id: "c", label: "Bonsoir", correct: false },
      ],
      why: "Noon is still Bonjour.",
      speakFeedbackCorrect: "Noon at the door is still Bonjour.",
      speakFeedbackWrong: "Noon is Bonjour, not goodbye.",
    },
  ],
};
