import type { LingoNode } from "@/content/lingo/types";

export const idU01L01: LingoNode = {
  id: "id-u01-l01",
  lang: "id",
  unit: 1,
  unitTitle: "Greetings",
  skill: "Say halo",
  title: "Say hello at the door",
  index: 0,
  steps: [
    {
      id: "id-u01-l01-intro-halo",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Halo",
      prompt: "Someone opens the door. This is the word you say.",
      native: "Halo",
      phonetic: "HAH-lo",
      meaning: "Hello",
      image: "/figures/lingo/door-hello.svg",
      speakTarget: "Halo",
      speakGloss: "Hello",
      speak: { silent: true },
      why: "Halo is the hello at the door.",
    },
    {
      id: "id-u01-l01-listen-halo",
      kind: "listen-pick",
      type: "listen-pick",
      lemma: "Halo",
      prompt: "Listen, then tap the English.",
      native: "Halo",
      phonetic: "HAH-lo",
      meaning: "Hello",
      speakTarget: "Halo",
      speak: { silent: true },
      choices: [
        { id: "a", label: "Hello", correct: true },
        { id: "b", label: "Thank you", correct: false },
        { id: "c", label: "Goodbye", correct: false },
      ],
      why: "Halo means hello.",
      speakFeedbackCorrect: "That greeting is hello.",
      speakFeedbackWrong: "Halo is hello at the door.",
    },
    {
      id: "id-u01-l01-intro-pagi",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Selamat pagi",
      prompt: "Morning light on the porch. This hello names the time.",
      native: "Selamat pagi",
      phonetic: "suh-LAH-mat PAH-gee",
      meaning: "Good morning",
      image: "/figures/lingo/door-hello.svg",
      speakTarget: "Selamat pagi",
      speakGloss: "Good morning",
      speak: { silent: true },
      why: "Selamat pagi is the morning hello.",
    },
    {
      id: "id-u01-l01-contrast-pagi-malam",
      kind: "contrast",
      type: "contrast",
      prompt: "The sun is just up. Which greeting fits?",
      native: "Selamat pagi",
      speakTarget: "Selamat pagi",
      speak: { silent: true },
      choices: [
        { id: "a", label: "Selamat pagi", correct: true },
        { id: "b", label: "Halo", correct: false },
      ],
      why: "Morning at the door is Selamat pagi.",
      speakFeedbackCorrect: "Morning at the door is Selamat pagi.",
      speakFeedbackWrong: "Morning at the door is Selamat pagi.",
    },
    {
      id: "id-u01-l01-intro-siang",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Selamat siang",
      prompt: "Midday heat. The hello changes with the clock.",
      native: "Selamat siang",
      phonetic: "suh-LAH-mat see-AHNG",
      meaning: "Good afternoon",
      image: "/figures/lingo/door-evening.svg",
      speakTarget: "Selamat siang",
      speakGloss: "Good afternoon",
      speak: { silent: true },
      why: "Selamat siang covers late morning into mid-afternoon.",
    },
    {
      id: "id-u01-l01-produce-halo",
      kind: "produce",
      type: "produce",
      lemma: "Halo",
      prompt: "Type the short hello you say at the door.",
      meaning: "Hello",
      answers: ["Halo", "halo"],
      speak: "Type the short Indonesian hello.",
      why: "Halo is the short door hello.",
      speakFeedbackCorrect: "Halo is the short hello.",
      speakFeedbackWrong: "Aim for Halo.",
    },
    {
      id: "id-u01-l01-intro-tinggal",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Selamat tinggal",
      prompt: "You turn back down the path. This is how the leaving person says goodbye.",
      native: "Selamat tinggal",
      phonetic: "suh-LAH-mat TEENG-gahl",
      meaning: "Goodbye",
      image: "/figures/lingo/door-leave.svg",
      speakTarget: "Selamat tinggal",
      speakGloss: "Goodbye",
      speak: { silent: true },
      why: "Selamat tinggal is goodbye from the person leaving.",
    },
    {
      id: "id-u01-l01-match",
      kind: "match",
      type: "match",
      prompt: "Match the door words you already met.",
      pairs: [
        { left: "Halo", right: "Hello" },
        { left: "Selamat pagi", right: "Good morning" },
        { left: "Selamat siang", right: "Good afternoon" },
        { left: "Selamat tinggal", right: "Goodbye" },
      ],
      speak: "Match each Indonesian door word to the English you already heard.",
      why: "These four already walked through the door.",
    },
    {
      id: "id-u01-l01-reuse-halo",
      kind: "reuse",
      type: "reuse",
      lemma: "Halo",
      prompt: "The door opens. Tap the short hello.",
      speakTarget: "Halo",
      speak: { silent: true },
      choices: [
        { id: "a", label: "Halo", correct: true },
        { id: "b", label: "Selamat tinggal", correct: false },
        { id: "c", label: "Selamat siang", correct: false },
      ],
      why: "The short door hello is Halo.",
      speakFeedbackCorrect: "The short hello is Halo.",
      speakFeedbackWrong: "Halo is hello, not goodbye.",
    },
  ],
};
