import type { LingoNode } from "@/content/lingo/types";

export const isU01L01: LingoNode = {
  id: "is-u01-l01",
  lang: "is",
  unit: 1,
  unitTitle: "Greetings",
  skill: "Say halló",
  title: "Say hello at the door",
  index: 0,
  steps: [
    {
      id: "is-u01-l01-intro-hallo",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Halló",
      prompt: "Someone opens the door. This is the word you say.",
      native: "Halló",
      phonetic: "HAH-loh",
      meaning: "Hello",
      image: "/figures/lingo/door-hello.svg",
      speakTarget: "Halló",
      speakGloss: "Hello",
      speak: { silent: true },
      why: "Halló is the hello at the door.",
    },
    {
      id: "is-u01-l01-listen-hallo",
      kind: "listen-pick",
      type: "listen-pick",
      lemma: "Halló",
      prompt: "Listen, then tap the English.",
      native: "Halló",
      phonetic: "HAH-loh",
      meaning: "Hello",
      speakTarget: "Halló",
      speak: { silent: true },
      choices: [
        { id: "a", label: "Hello", correct: true },
        { id: "b", label: "Thanks", correct: false },
        { id: "c", label: "Bye", correct: false },
      ],
      why: "Halló means hello.",
      speakFeedbackCorrect: "That greeting is hello.",
      speakFeedbackWrong: "Halló is hello at the door.",
    },
    {
      id: "is-u01-l01-intro-daginn",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Góðan daginn",
      prompt: "Daylight on the porch. This hello names the day.",
      native: "Góðan daginn",
      phonetic: "GOH-than DAI-yin",
      meaning: "Good day",
      image: "/figures/lingo/door-hello.svg",
      speakTarget: "Góðan daginn",
      speakGloss: "Good day",
      speak: { silent: true },
      why: "Góðan daginn is the daylight hello.",
    },
    {
      id: "is-u01-l01-contrast-dag-kvold",
      kind: "contrast",
      type: "contrast",
      prompt: "It is still daylight. Which greeting fits?",
      native: "Góðan daginn",
      speakTarget: "Góðan daginn",
      speak: { silent: true },
      choices: [
        { id: "a", label: "Góðan daginn", correct: true },
        { id: "b", label: "Halló", correct: false },
      ],
      why: "Daylight at the door is Góðan daginn.",
      speakFeedbackCorrect: "Daylight at the door is Góðan daginn.",
      speakFeedbackWrong: "Daylight at the door is Góðan daginn.",
    },
    {
      id: "is-u01-l01-intro-kvold",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Gott kvöld",
      prompt: "The porch light is on. Evening uses a different hello.",
      native: "Gott kvöld",
      phonetic: "gott KVULT",
      meaning: "Good evening",
      image: "/figures/lingo/door-evening.svg",
      speakTarget: "Gott kvöld",
      speakGloss: "Good evening",
      speak: { silent: true },
      why: "Gott kvöld is the evening hello.",
    },
    {
      id: "is-u01-l01-produce-hallo",
      kind: "produce",
      type: "produce",
      lemma: "Halló",
      prompt: "Type the short hello you say at the door.",
      meaning: "Hello",
      answers: ["Halló", "Halló", "halló", "Hallo", "hallo"],
      speak: "Type the short Icelandic hello.",
      why: "Halló is the short door hello.",
      speakFeedbackCorrect: "Halló is the short hello.",
      speakFeedbackWrong: "Aim for Halló.",
    },
    {
      id: "is-u01-l01-intro-bless",
      kind: "introduce",
      type: "introduce",
      new: true,
      lemma: "Bless",
      prompt: "You turn back down the path. This is how you leave.",
      native: "Bless",
      phonetic: "bless",
      meaning: "Bye",
      image: "/figures/lingo/door-leave.svg",
      speakTarget: "Bless",
      speakGloss: "Bye",
      speak: { silent: true },
      why: "Bless is goodbye at the door.",
    },
    {
      id: "is-u01-l01-match",
      kind: "match",
      type: "match",
      prompt: "Match the door words you already met.",
      pairs: [
        { left: "Halló", right: "Hello" },
        { left: "Góðan daginn", right: "Good day" },
        { left: "Gott kvöld", right: "Good evening" },
        { left: "Bless", right: "Bye" },
      ],
      speak: "Match each Icelandic door word to the English you already heard.",
      why: "These four already walked through the door.",
    },
    {
      id: "is-u01-l01-reuse-hallo",
      kind: "reuse",
      type: "reuse",
      lemma: "Halló",
      prompt: "The door opens. Tap the short hello.",
      speakTarget: "Halló",
      speak: { silent: true },
      choices: [
        { id: "a", label: "Halló", correct: true },
        { id: "b", label: "Bless", correct: false },
        { id: "c", label: "Gott kvöld", correct: false },
      ],
      why: "The short door hello is Halló.",
      speakFeedbackCorrect: "The short hello is Halló.",
      speakFeedbackWrong: "Halló is hello, not goodbye.",
    },
  ],
};
