import type { LearnBeat } from "@/content/types";

export const ATOMS_LOCK = "An element is its proton count, not its costume.";

export const atomsMatterBeats: LearnBeat[] = [
  {
    id: "atoms-hook",
    type: "hook",
    title: "The pencil and the diamond",
    iCan: "meet two faces of carbon",
    speak: "A pencil mark and a diamond are both carbon. The costume changed.",
    body: ["Same atoms. Different packing. The name of the element did not change."],
    objective: "Meet an element as a proton count.",
  },
  {
    id: "atoms-see",
    type: "see",
    title: "Packed, not smooth",
    iCan: "read nucleus and electron cloud",
    speak: "A dense nucleus sits in a wide electron cloud. Most of the atom is empty.",
    body: ["Read the labels. The nucleus is the ID. The cloud is the space."],
    figure: {
      kind: "diagram",
      diagram: "atom",
      alt: "Nucleus and electron cloud labelled on one atom.",
      caption: "The nucleus holds the proton count. The cloud is not a tiny planet track.",
      labels: ["nucleus", "electron cloud"],
    },
    termsIntroduced: ["nucleus", "electron cloud"],
  },
  {
    id: "atoms-try",
    type: "try",
    title: "What names the element",
    iCan: "pick the element ID",
    speak: "What stays the same when carbon is graphite or diamond?",
    check: {
      id: "atoms-try",
      type: "choice",
      prompt: "What stays the same when carbon is graphite or diamond?",
      choices: [
        { id: "a", label: "The proton count", correct: true, why: "Proton count is the element ID." },
        { id: "b", label: "The hardness", correct: false, why: "Hardness is the costume, not the ID." },
        { id: "c", label: "The colour of the pencil", correct: false, why: "Colour is not the element." },
      ],
    },
    speakFeedbackCorrect: "Proton count names the element.",
    speakFeedbackWrong: "The costume changed. The proton count did not.",
  },
  {
    id: "atoms-name",
    type: "name",
    title: "Name the element",
    iCan: "name an element by protons",
    speak: "An element is one kind of atom. The proton count is its ID.",
    body: ["Carbon stays carbon in a pencil or a diamond. That ID is the proton count."],
    termsIntroduced: ["element", "proton count"],
  },
  {
    id: "atoms-contrast",
    type: "contrast",
    title: "Mixture versus compound",
    iCan: "split mixture from compound",
    speak: "A compound has a fixed recipe. A mixture is a salad you can unmix.",
    body: ["Water is a recipe. Salt water is a salad."],
    termsIntroduced: ["compound", "mixture"],
  },
  {
    id: "atoms-decide",
    type: "decide",
    title: "What is carbon",
    iCan: "keep the proton count",
    speak: "Graphite and diamond look different. What still makes both carbon?",
    lockLine: ATOMS_LOCK,
    cardHook: ATOMS_LOCK,
    termsIntroduced: ["element", "proton count"],
    check: {
      id: "atoms-decide",
      type: "choice",
      prompt: "Graphite and diamond look different. What still makes both carbon?",
      choices: [
        { id: "a", label: "The same proton count", correct: true, why: "An element is its proton count, not its costume." },
        { id: "b", label: "They are equally hard", correct: false, why: "Hardness is the packing, not the ID." },
        { id: "c", label: "They both melt at the same time", correct: false, why: "Melting is packing, not the element ID." },
      ],
    },
    speakFeedbackCorrect: "An element is its proton count, not its costume.",
    speakFeedbackWrong: "The costume changed. The proton count is the ID.",
  },
  {
    id: "atoms-lock",
    type: "lock",
    title: "Keep this line",
    iCan: "repeat the proton count line",
    speak: "An element is its proton count, not its costume.",
    lockLine: ATOMS_LOCK,
    body: [ATOMS_LOCK, "The packing can change. The ID does not."],
  },
];
