import type { LearnBeat, Lesson } from "@/content/types";
import { diagramFigure } from "@/content/figures";

export const MOBILE_LOCK_CPU =
  "A thin-and-light faster CPU means a different laptop.";

const cpuFigure = {
  kind: "diagram" as const,
  diagram: "soldered-cpu" as const,
  alt: "Thin laptop board with a soldered CPU, a so-dimm stick, an M.2 drive, and a pack, each labelled.",
  caption: "The C P U is soldered. So dimm, M two, and the pack can leave the board.",
  labels: ["soldered CPU", "so-dimm", "M.2", "pack"],
};

const fruFigure = diagramFigure(
  "fru-laptop",
  "Laptop broken into labelled replaceable parts: lid and antennas, so-dimm, M.2 storage, and pack.",
  "Name the part you can pull. The lid hides antennas. The C P U is often soldered.",
);
fruFigure.labels = ["lid / antennas", "so-dimm", "M.2", "pack"];

export const mobileDevicesBeats: LearnBeat[] = [
  {
    id: "md-cpu-hook",
    type: "hook",
    title: "They want a faster chip",
    iCan: "hear a faster chip request",
    objective: "Meet a thin laptop that cannot take a socket swap.",
    speak: "A thin laptop feels slow. The owner asks for a faster processor.",
    body: [
      "A thin-and-light comes in slow. The owner points at the processor and asks you to swap it.",
      "Hold that request until you know what is soldered.",
    ],
  },
  {
    id: "md-cpu-see",
    type: "see",
    title: "What can leave this board",
    iCan: "read soldered versus pull parts",
    objective: "See a soldered CPU next to parts that unplug.",
    speak: "This board has a soldered C P U. So dimm, M two, and the pack can leave.",
    body: ["Read the labels. Only the labelled pull parts come off without a new laptop."],
    figure: cpuFigure,
    termsIntroduced: ["soldered CPU", "so-dimm", "M.2", "pack"],
  },
  {
    id: "md-cpu-try",
    type: "try",
    title: "Tap a part you can swap",
    iCan: "pick a part you can pull",
    objective: "Choose a pull part, not the soldered chip.",
    speak: "Tap the part you can swap without ordering a new laptop.",
    body: ["A field-replaceable unit is a part you can pull at the bench."],
    termsIntroduced: ["field-replaceable unit"],
    check: {
      id: "md-cpu-try",
      type: "choice",
      prompt: "Which part can you pull on this thin board?",
      choices: [
        {
          id: "a",
          label: "The so-dimm stick, the M.2 drive, or the pack",
          correct: true,
          why: "Those unplug. The processor on this board is soldered.",
        },
        {
          id: "b",
          label: "The processor, because laptop sockets are universal",
          correct: false,
          why: "This thin board has no socket. The chip is soldered.",
        },
        {
          id: "c",
          label: "The chipset, if you bring hot air",
          correct: false,
          why: "Hot air on a customer thin-and-light is not a field swap.",
        },
      ],
    },
    speakFeedbackCorrect: "So dimm, M two, and the pack can leave. The chip stays.",
    speakFeedbackWrong: "The processor is soldered. Pick a part that unplugs.",
  },
  {
    id: "md-cpu-name",
    type: "name",
    title: "Field-replaceable unit",
    iCan: "name a field replaceable unit",
    objective: "Name FRU with the expansion first.",
    speak: "A field replaceable unit is a part you can pull. The C P U often is not.",
    body: [
      "A field-replaceable unit, written F R U on parts lists, is a module you can pull: so-dimm, M.2, pack, display, sometimes a keyboard deck.",
      "On modern thin-and-lights the processor is often soldered. It is not a field-replaceable unit.",
    ],
    termsIntroduced: ["field-replaceable unit", "soldered CPU"],
  },
  {
    id: "md-cpu-contrast",
    type: "contrast",
    title: "Socket versus solder",
    iCan: "contrast socket versus solder",
    objective: "Contrast a socketed desktop chip with a soldered thin board.",
    speak: "A desktop chip sits in a socket. This thin board has the chip soldered.",
    body: [
      "A desktop board lets you lift a chip from a socket.",
      "This thin board glued the chip down. A faster processor here means a different laptop.",
    ],
  },
  {
    id: "md-cpu-decide",
    type: "decide",
    title: "Answer the faster-chip ask",
    iCan: "answer the faster chip ask",
    objective: "Decide what to tell a user who wants a faster CPU in a thin-and-light.",
    speak: "The owner wants a faster C P U in this thin laptop. What do you say?",
    lockLine: MOBILE_LOCK_CPU,
    cardHook: MOBILE_LOCK_CPU,
    termsIntroduced: ["soldered CPU", "field-replaceable unit"],
    check: {
      id: "md-fru",
      type: "choice",
      prompt: "A thin laptop is slow. The user wants a faster CPU. What do you tell them?",
      choices: [
        {
          id: "a",
          label: "Most modern thin-and-lights have soldered CPUs. A faster chip usually means a different laptop.",
          correct: true,
          why: "Field-replaceable units are so-dimm, storage, pack, display. The processor is often not a socket swap.",
        },
        {
          id: "b",
          label: "Order any desktop socket chip. Laptop sockets are universal.",
          correct: false,
          why: "This thin board has no universal socket. The chip is soldered to this model.",
        },
        {
          id: "c",
          label: "Flash the firmware to unlock hidden cores.",
          correct: false,
          why: "Firmware does not turn this SKU into a faster soldered chip.",
        },
      ],
    },
    speakFeedbackCorrect: "A thin and light faster C P U means a different laptop.",
    speakFeedbackWrong: "The chip is soldered. A faster processor means a different laptop.",
  },
  {
    id: "md-cpu-lock",
    type: "lock",
    title: "Keep this line",
    iCan: "repeat the soldered chip line",
    objective: "Lock the thin-and-light CPU line.",
    speak: "A thin and light faster C P U means a different laptop.",
    lockLine: MOBILE_LOCK_CPU,
    body: [MOBILE_LOCK_CPU],
  },
  {
    id: "md-dock-hook",
    type: "hook",
    title: "The dock that will not show a screen",
    iCan: "meet a dock with no video",
    objective: "Meet a USB-C dock that charges and stays dark.",
    speak: "The laptop drinks power from the dock. The monitor stays black.",
    body: ["Same hole on the side. Charge arrived. The picture did not."],
  },
  {
    id: "md-dock-see",
    type: "see",
    title: "Three jobs, one hole",
    iCan: "read three U S B C jobs",
    objective: "See charge-only versus video versus Thunderbolt.",
    speak: "The hole can be charge only, video, or Thunderbolt. The spec sheet picks.",
    body: ["Labels name the job. The hole shape does not."],
    figure: {
      ...diagramFigure(
        "usb-c-roles",
        "Three U S B C jobs: charge only, DisplayPort alt mode, and Thunderbolt.",
        "The hole looks the same. The spec sheet says whether video rides along.",
      ),
      labels: ["charge only", "DisplayPort alt mode", "Thunderbolt"],
    },
    termsIntroduced: ["charge only", "DisplayPort alt mode", "Thunderbolt"],
  },
  {
    id: "md-dock-name",
    type: "name",
    title: "Charge only is a real port",
    iCan: "name a charge only port",
    objective: "Name charge-only USB-C.",
    speak: "A charge only U S B C port will not drive a monitor.",
    body: [
      "Charge only means power. DisplayPort alt mode or Thunderbolt is what carries a picture.",
    ],
    termsIntroduced: ["charge only"],
  },
  {
    id: "md-dock-contrast",
    type: "contrast",
    title: "Charge is not video",
    iCan: "split charge from video",
    objective: "Contrast charging with video output.",
    speak: "Power on the cable does not prove the port can send video.",
    body: ["A dock that works on laptop A can fail on laptop B. Compare the port, not the brand."],
  },
  {
    id: "md-dock-decide",
    type: "decide",
    title: "Does charge prove video?",
    iCan: "reject charge proves video",
    objective: "Decide that charge does not prove video.",
    speak: "If a laptop charges from a U S B C dock, does that port always output video?",
    check: {
      id: "md-usbc",
      type: "truefalse",
      prompt: "If a laptop charges from a USB-C dock, that same port will always output video.",
      answer: false,
      why: "USB-C can be charge only. Video needs DisplayPort alt mode or Thunderbolt.",
    },
    speakFeedbackCorrect: "Charge only ports exist. Video needs alt mode or Thunderbolt.",
    speakFeedbackWrong: "Charge does not prove video. The port may be charge only.",
  },
  {
    id: "md-dock-lock",
    type: "lock",
    title: "Keep this line",
    iCan: "repeat the charge only line",
    objective: "Lock the charge-only line.",
    speak: "A U S B C hole that charges can still be charge only.",
    lockLine: "A USB-C hole that charges can still be charge only.",
    body: ["A USB-C hole that charges can still be charge only."],
  },
  {
    id: "md-ant-hook",
    type: "hook",
    title: "Wi-Fi dies after a new panel",
    iCan: "meet weak wifi after a panel",
    objective: "Meet weak Wi-Fi after a lid swap.",
    speak: "The new screen looks fine. Wi-Fi range collapses while the cable port still works.",
    body: ["Ethernet still talks. The radios in the lid do not."],
  },
  {
    id: "md-ant-see",
    type: "see",
    title: "Leads in the lid",
    iCan: "see antenna leads in the lid",
    objective: "See MAIN and AUX leads on the combo card.",
    speak: "Antenna leads ride in the lid and click onto the combo card.",
    body: ["MAIN and AUX are printed on the card. They pop off during a panel job."],
    figure: {
      ...fruFigure,
      labels: ["lid / antennas", "MAIN", "AUX", "combo card"],
    },
    termsIntroduced: ["antenna leads", "MAIN", "AUX"],
  },
  {
    id: "md-ant-name",
    type: "name",
    title: "Name the leads",
    iCan: "name main and aux leads",
    objective: "Name MAIN and AUX antenna leads.",
    speak: "The leads are marked main and aux. Ethernet does not use them.",
    body: ["If range dies after a lid job and a cable still works, look at the leads first."],
    termsIntroduced: ["antenna leads"],
  },
  {
    id: "md-ant-decide",
    type: "decide",
    title: "First theory after a screen swap",
    iCan: "blame leads before the OS",
    objective: "Decide the first theory for weak Wi-Fi after a panel swap.",
    speak: "After a screen swap, Wi-Fi range collapses while Ethernet stays fine. What is the first theory?",
    check: {
      id: "md-wifi",
      type: "choice",
      prompt: "After a screen swap, Wi-Fi range collapses. Ethernet is fine. First theory?",
      choices: [
        {
          id: "a",
          label: "Antenna leads (MAIN / AUX) were left off the combo card or pinched in the lid",
          correct: true,
          why: "Lid antennas unseat during a panel job. Ethernet does not use those leads.",
        },
        {
          id: "b",
          label: "Reinstall the operating system to rebuild the Wi-Fi stack",
          correct: false,
          why: "A cable port that still works points at the lid leads, not the OS.",
        },
        {
          id: "c",
          label: "Replace the motherboard first. Radios live only on the board.",
          correct: false,
          why: "The antennas live in the lid. Seat the leads before you order a board.",
        },
      ],
    },
    speakFeedbackCorrect: "Seat the lid leads on the combo card before you blame the OS.",
    speakFeedbackWrong: "Ethernet still works, so start with the lid leads.",
  },
  {
    id: "md-ant-lock",
    type: "lock",
    title: "Keep this line",
    iCan: "repeat the lid lead line",
    objective: "Lock the antenna-lead line.",
    speak: "Weak Wi-Fi after a lid job usually means pinched antenna leads.",
    lockLine: "Weak Wi-Fi after a lid job usually means pinched antenna leads.",
    body: ["Weak Wi-Fi after a lid job usually means pinched antenna leads.", "Ethernet still working is the clue."],
  },
];

export const mobileDevicesLesson: Lesson = {
  id: "mobile-devices-essentials",
  domainId: "mobile-devices",
  title: "Soldered chips and the parts you can pull",
  minutes: 12,
  objective: "Teach a soldered CPU before anyone is asked to quiz it.",
  lockLine: MOBILE_LOCK_CPU,
  intro:
    "A thin laptop fails in parts. Name what is soldered before you promise a faster chip.",
  figure: cpuFigure,
  beats: mobileDevicesBeats,
  sections: [
    {
      heading: "Think in replaceable parts",
      paragraphs: [
        "A field-replaceable unit is a part you can pull. On a thin-and-light the processor is often soldered.",
        "A faster CPU on that board usually means a different laptop.",
      ],
      figure: cpuFigure,
    },
    {
      heading: "Docks, port replicators, and the cable people trip over",
      paragraphs: [
        "A USB-C hole that charges can still be charge only. Video needs DisplayPort alt mode or Thunderbolt.",
      ],
    },
    {
      heading: "The radios: Wi-Fi, Bluetooth, cellular, GPS, NFC",
      paragraphs: [
        "Weak Wi-Fi after a lid job usually means pinched antenna leads.",
      ],
    },
  ],
  keyTakeaways: [
    MOBILE_LOCK_CPU,
    "A USB-C hole that charges can still be charge only.",
    "Weak Wi-Fi after a lid job usually means pinched antenna leads.",
  ],
};
