import type { Domain } from "./types";

export const schoolDomains: Domain[] = [
  {
    id: "number-sense",
    subject: "maths",
    number: 1,
    title: "Number sense",
    summary: "Place value, estimation, and the order that keeps a calculation honest.",
    lessonId: "number-sense-essentials",
    quizId: "number-sense-quiz",
  },
  {
    id: "fractions",
    subject: "maths",
    number: 2,
    title: "Fractions",
    summary: "Parts of a whole, equivalent slices, and why 1/2 + 1/3 is not 2/5.",
    lessonId: "fractions-essentials",
    quizId: "fractions-quiz",
  },
  {
    id: "percentages",
    subject: "maths",
    number: 3,
    title: "Percentages",
    summary: "Discounts, GST, and “of” as multiply — money problems that behave.",
    lessonId: "percentages-essentials",
    quizId: "percentages-quiz",
  },
  {
    id: "algebra-foundations",
    subject: "maths",
    number: 4,
    title: "Algebra",
    summary: "Unknowns, balance, and rearranging without hoping the equals sign is decoration.",
    lessonId: "algebra-foundations-essentials",
    quizId: "algebra-foundations-quiz",
  },
  {
    id: "geometry-measure",
    subject: "maths",
    number: 5,
    title: "Geometry",
    summary: "Angles, area, and a right triangle you can trust on a building site.",
    lessonId: "geometry-measure-essentials",
    quizId: "geometry-measure-quiz",
  },
  {
    id: "atoms-matter",
    subject: "science",
    number: 1,
    title: "Atoms & matter",
    summary: "Particles, states, and why chemistry is rearranging Lego, not magic smoke.",
    lessonId: "atoms-matter-essentials",
    quizId: "atoms-matter-quiz",
  },
  {
    id: "forces-motion",
    subject: "science",
    number: 2,
    title: "Forces & motion",
    summary: "Pushes, friction, and Newton’s habits — including the ones that feel wrong.",
    lessonId: "forces-motion-essentials",
    quizId: "forces-motion-quiz",
  },
  {
    id: "energy-systems",
    subject: "science",
    number: 3,
    title: "Energy",
    summary: "Forms, transfers, and why “used up” is almost never the real story.",
    lessonId: "energy-systems-essentials",
    quizId: "energy-systems-quiz",
  },
  {
    id: "cells-life",
    subject: "science",
    number: 4,
    title: "Cells & life",
    summary: "The smallest living unit, DNA’s job, and what a virus is not.",
    lessonId: "cells-life-essentials",
    quizId: "cells-life-quiz",
  },
  {
    id: "ecosystems-au",
    subject: "science",
    number: 5,
    title: "Ecosystems",
    summary: "Food webs, cycles, and Australian places that refuse to be generic posters.",
    lessonId: "ecosystems-au-essentials",
    quizId: "ecosystems-au-quiz",
  },
  {
    id: "historical-thinking",
    subject: "history",
    number: 1,
    title: "How history works",
    summary: "Evidence, bias, cause and effect — the method before the stories.",
    lessonId: "historical-thinking-essentials",
    quizId: "historical-thinking-quiz",
  },
  {
    id: "ancient-worlds",
    subject: "history",
    number: 2,
    title: "Ancient worlds",
    summary: "Nile, Rome, and Han China: power, trade, and the choices that stuck.",
    lessonId: "ancient-worlds-essentials",
    quizId: "ancient-worlds-quiz",
  },
  {
    id: "country-contact",
    subject: "history",
    number: 3,
    title: "Country & contact",
    summary: "Deep time on this continent, 1788, and why “settled empty land” fails the evidence.",
    lessonId: "country-contact-essentials",
    quizId: "country-contact-quiz",
  },
  {
    id: "making-australia",
    subject: "history",
    number: 4,
    title: "Making Australia",
    summary: "Colonies to Federation, who got a vote, and the fights that followed.",
    lessonId: "making-australia-essentials",
    quizId: "making-australia-quiz",
  },
  {
    id: "twentieth-century",
    subject: "history",
    number: 5,
    title: "The twentieth century",
    summary: "World wars, rights, and a decision on a ridge — not a list of years.",
    lessonId: "twentieth-century-essentials",
    quizId: "twentieth-century-quiz",
  },
];
