import type { PathCheck } from "./types";

export const schoolChecks: Record<string, PathCheck[]> = {
  "number-sense": [
    {
      id: "ns-place",
      afterHeading: "Place value is an address",
      type: "truefalse",
      prompt: "True or false: 3.04 and 3.4 are the same amount because both have a 3 and a 4.",
      answer: false,
      why: "3.04 is three and four hundredths. 3.4 is three and four tenths — ten times fatter in the fractional part. The zero is a chair, not decoration.",
    },
    {
      id: "ns-est",
      afterHeading: "Estimate before you compute",
      type: "choice",
      prompt: "Four coffees at $4.80 print as $192. What is the grown-up move?",
      choices: [
        { id: "a", label: "Pay it — computers don’t lie", correct: false, why: "Computers lie whenever a human parked a decimal in the wrong room." },
        { id: "b", label: "Estimate 5 × 4 = $20, then hunt the extra zero", correct: true, why: "Neighbourhood check. $192 is a place-value accident, not a coffee." },
        { id: "c", label: "Add 10% GST to $192 to be safe", correct: false, why: "Do not GST a typo." },
      ],
    },
    {
      id: "ns-bodmas",
      afterHeading: "Order of operations is a queue, not a vibe",
      type: "choice",
      prompt: "3 + 4 × 5. What is honest?",
      choices: [
        { id: "a", label: "35 — left to right, always", correct: false, why: "That is the friendly-wrong calculator energy." },
        { id: "b", label: "23 — the 4 × 5 is a packet", correct: true, why: "Multiply first unless brackets say otherwise." },
        { id: "c", label: "12 — add then ignore the 5", correct: false, why: "The 5 is not a spectator." },
      ],
    },
  ],
  fractions: [
    {
      id: "fr-add",
      afterHeading: "Adding needs a common cut",
      type: "choice",
      prompt: "1/2 + 1/3. Why is 2/5 a trap?",
      choices: [
        { id: "a", label: "You added denominators like they were counts of the same piece", correct: true, why: "Hours + minutes is not “2.” Common denominator 6 → 5/6." },
        { id: "b", label: "Fractions cannot be added", correct: false, why: "They can. They just need matching cuts." },
        { id: "c", label: "2/5 is actually right", correct: false, why: "It is the most popular wrong answer on Earth." },
      ],
    },
    {
      id: "fr-eq",
      afterHeading: "Equivalent fractions are the same amount",
      type: "match",
      prompt: "Match the fraction to a twin.",
      pairs: [
        { left: "1/2", right: "2/4" },
        { left: "2/3", right: "4/6" },
        { left: "3/4", right: "6/8" },
        { left: "5/1", right: "5" },
      ],
      why: "Same pile, different cut. Multiply or divide top and bottom together.",
    },
    {
      id: "fr-div",
      afterHeading: "Division is “how many of these fit”",
      type: "truefalse",
      prompt: "True or false: 1 ÷ 1/4 = 4 because four quarters fit in a whole.",
      answer: true,
      why: "Keep-change-flip is invert-and-multiply with a story, not a superstition.",
    },
  ],
  percentages: [
    {
      id: "pe-of",
      afterHeading: "“Of” means multiply",
      type: "choice",
      prompt: "A shop takes 20% off, then another 20% at the till. Total off?",
      choices: [
        { id: "a", label: "40% — percents add, everyone knows that", correct: false, why: "Everyone “knows” that. The second 20% hits the already-reduced price." },
        { id: "b", label: "36% — 0.8 × 0.8 leaves 64%", correct: true, why: "Successive percentages multiply. Shops love the confusion." },
        { id: "c", label: "20% — only the last one counts", correct: false, why: "Both hit. Just not as a sum." },
      ],
    },
    {
      id: "pe-orig",
      afterHeading: "Finding the original",
      type: "choice",
      prompt: "Jumper $64 after 20% off. Original?",
      choices: [
        { id: "a", label: "$80 — 64 is 80% of the start", correct: true, why: "Divide by 0.8. Do not add 20% of 64 and call it done — that is a different jumper." },
        { id: "b", label: "$76.80 — add 20% of 64", correct: false, why: "That treats $64 as the original. It is the remnant." },
        { id: "c", label: "$64 — discounts don’t change the tag", correct: false, why: "Then why is it on sale." },
      ],
    },
    {
      id: "pe-gst",
      afterHeading: "Percent, decimal, fraction — same clothes",
      type: "truefalse",
      prompt: "True or false: a $55 GST-inclusive price means you add another $5.50 at the till.",
      answer: false,
      why: "Inclusive already contains the 10%. $5 of that $55 is GST, not $5.50 extra.",
    },
  ],
  "algebra-foundations": [
    {
      id: "al-balance",
      afterHeading: "An equation is a balance",
      type: "choice",
      prompt: "x + 7 = 20. The legal move is",
      choices: [
        { id: "a", label: "Subtract 7 from the left only, because that’s where x lives", correct: false, why: "Then the sides stop being equal. The claim breaks." },
        { id: "b", label: "Subtract 7 from both sides", correct: true, why: "Undo the glued operation on both piles. x = 13." },
        { id: "c", label: "Divide by 7 immediately", correct: false, why: "The 7 is added, not multiplied." },
      ],
    },
    {
      id: "al-like",
      afterHeading: "Like terms and the silent 1",
      type: "truefalse",
      prompt: "True or false: 3x + 2 = 5x.",
      answer: false,
      why: "3x and 2 are different units. Folding them is adding crates to apples.",
    },
    {
      id: "al-two",
      afterHeading: "Two-step and the trap of dividing too early",
      type: "choice",
      prompt: "2x + 6 = 20. After a correct undo, x is",
      choices: [
        { id: "a", label: "13", correct: false, why: "That ignored the 2 or the 6. Substitute and watch it fail." },
        { id: "b", label: "7", correct: true, why: "2x = 14, x = 7. Plug in: 14 + 6 = 20." },
        { id: "c", label: "8", correct: false, why: "Close-looking wrongness. Still check." },
      ],
    },
  ],
  "geometry-measure": [
    {
      id: "ge-peri",
      afterHeading: "Area is covering, perimeter is wrapping",
      type: "choice",
      prompt: "A 4 by 6 rectangle. Which pair is honest?",
      choices: [
        { id: "a", label: "Perimeter 24, area 20", correct: false, why: "You swapped the jobs." },
        { id: "b", label: "Perimeter 20, area 24", correct: true, why: "Fence 4+6+4+6. Grass 4×6." },
        { id: "c", label: "Both 24 because rectangles are tidy", correct: false, why: "Tidy is not a formula." },
      ],
    },
    {
      id: "ge-pyth",
      afterHeading: "Pythagoras is a right-angle test",
      type: "truefalse",
      prompt: "True or false: a 6 m by 8 m garden bed should have a 10 m diagonal if the corner is square.",
      answer: true,
      why: "3-4-5 scaled by 2. If the diagonal is off, the right angle is a rumour.",
    },
    {
      id: "ge-scale",
      afterHeading: "Scale drawings and similar shapes",
      type: "choice",
      prompt: "A tank is scaled up ×2 in every length. Volume becomes",
      choices: [
        { id: "a", label: "×2", correct: false, why: "That’s lengths." },
        { id: "b", label: "×4", correct: false, why: "That’s area." },
        { id: "c", label: "×8", correct: true, why: "Volumes go with the cube of the scale factor. Twice as tall is eight times the water." },
      ],
    },
  ],
  "atoms-matter": [
    {
      id: "at-id",
      afterHeading: "The periodic table is a seating chart",
      type: "choice",
      prompt: "What is the element’s ID card?",
      choices: [
        { id: "a", label: "Mass number only", correct: false, why: "That’s protons + neutrons. Isotopes share an element and split that number." },
        { id: "b", label: "Proton count (atomic number)", correct: true, why: "Change protons and you are playing a different element." },
        { id: "c", label: "How shiny it is in the cupboard", correct: false, why: "Chemistry is not interior design." },
      ],
    },
    {
      id: "at-state",
      afterHeading: "States and changes of state",
      type: "truefalse",
      prompt: "True or false: boiling water turns H₂O into a new compound called steam.",
      answer: false,
      why: "Same particles, more freedom. Steam burns because condensation dumps energy into you.",
    },
    {
      id: "at-cons",
      afterHeading: "Bonds are deals, not glue sticks",
      type: "choice",
      prompt: "A candle in a sealed jar “loses” wax. Where did the atoms go?",
      choices: [
        { id: "a", label: "Destroyed to make heat", correct: false, why: "Heat is not a dumpster for atoms." },
        { id: "b", label: "Rearranged into gases you could weigh if you kept them", correct: true, why: "Closed system: mass holds. Open window: the gases commute." },
        { id: "c", label: "They became neutrons", correct: false, why: "That would be a different, much louder lab." },
      ],
    },
  ],
  "forces-motion": [
    {
      id: "fo-n1",
      afterHeading: "Newton 1: leave it alone and it keeps doing that",
      type: "choice",
      prompt: "A bike slows on the flat. The grown-up explanation is",
      choices: [
        { id: "a", label: "Motion naturally wears out", correct: false, why: "Aristotle in a helmet. Newton 1 says otherwise." },
        { id: "b", label: "Unbalanced friction and drag", correct: true, why: "Net force is not zero, so velocity changes." },
        { id: "c", label: "The mass leaked out the tyres", correct: false, why: "Please do not." },
      ],
    },
    {
      id: "fo-turn",
      afterHeading: "Newton 2: unbalanced force means acceleration",
      type: "truefalse",
      prompt: "True or false: a car on a roundabout at constant 60 km/h is accelerating.",
      answer: true,
      why: "Direction is part of velocity. Turning is a change. Seatbelt physics agrees.",
    },
    {
      id: "fo-n3",
      afterHeading: "Newton 3: you cannot punch the universe without it punching back",
      type: "choice",
      prompt: "If force pairs are equal, why do you move more than Earth when you jump?",
      choices: [
        { id: "a", label: "Newton 3 is optional on weekdays", correct: false, why: "It is not." },
        { id: "b", label: "Same-size forces, different masses — you are the joke mass", correct: true, why: "a = F/m. Earth barely notices. You do." },
        { id: "c", label: "Gravity switches off mid-jump", correct: false, why: "It does not. Landing will confirm." },
      ],
    },
  ],
  "energy-systems": [
    {
      id: "ey-cons",
      afterHeading: "Transfers and conservation",
      type: "truefalse",
      prompt: "True or false: a kettle “uses up” electrical energy so it is gone.",
      answer: false,
      why: "It transfers: electrical → thermal (water + room). The ledger still balances. You just cannot recapture the kitchen air easily.",
    },
    {
      id: "ey-work",
      afterHeading: "Work and power",
      type: "choice",
      prompt: "You hold a piano still for ten minutes. Work done on the piano?",
      choices: [
        { id: "a", label: "Huge — you are wrecked", correct: false, why: "Your muscles are a different story. The piano did not move." },
        { id: "b", label: "Zero on the piano — no displacement", correct: true, why: "Work = force × distance in the force’s direction." },
        { id: "c", label: "Negative mass was created", correct: false, why: "No." },
      ],
    },
    {
      id: "ey-fossil",
      afterHeading: "Earth’s energy budget, quickly",
      type: "choice",
      prompt: "Burning coal is, energetically,",
      choices: [
        { id: "a", label: "making new energy from rocks", correct: false, why: "Rocks are not a free lunch." },
        { id: "b", label: "a fast unwind of old stored chemical energy from photosynthesis", correct: true, why: "That’s the climate lever: vault opened quickly." },
        { id: "c", label: "pure geothermal steam", correct: false, why: "Different menu." },
      ],
    },
  ],
  "cells-life": [
    {
      id: "ce-virus",
      afterHeading: "DNA, genes, and not destiny-in-a-sentence",
      type: "truefalse",
      prompt: "True or false: antibiotics are a sensible first weapon against influenza.",
      answer: false,
      why: "Flu is viral. Antibiotics target bacteria. Stewardship is not a personality quiz.",
    },
    {
      id: "ce-pro",
      afterHeading: "Prokaryote vs eukaryote",
      type: "match",
      prompt: "Match the part to the job.",
      pairs: [
        { left: "Nucleus", right: "Keeps the DNA" },
        { left: "Mitochondria", right: "Respiration, ATP" },
        { left: "Chloroplast", right: "Photosynthesis" },
        { left: "Membrane", right: "Gate and skin" },
      ],
      why: "Shared kit, then extras. Plants kept the solar panels.",
    },
    {
      id: "ce-theory",
      afterHeading: "Cell theory, without the poster glaze",
      type: "choice",
      prompt: "Cell theory’s spicy sentence is",
      choices: [
        { id: "a", label: "Mice appear from wheat", correct: false, why: "That one lost." },
        { id: "b", label: "New cells come from existing cells", correct: true, why: "Life is a continuity, not a magic trick." },
        { id: "c", label: "Viruses are the smallest cells", correct: false, why: "Viruses are not cells." },
      ],
    },
  ],
  "ecosystems-au": [
    {
      id: "ec-arrow",
      afterHeading: "Food webs, not chains",
      type: "choice",
      prompt: "A food-web arrow from grass to kangaroo means",
      choices: [
        { id: "a", label: "grass eats kangaroos", correct: false, why: "That would be a different Australia." },
        { id: "b", label: "energy flows to the kangaroo (grass is eaten)", correct: true, why: "Arrow = energy this way = is eaten by." },
        { id: "c", label: "they are friends", correct: false, why: "Ecology is not a group chat." },
      ],
    },
    {
      id: "ec-fire",
      afterHeading: "Australian wrinkles",
      type: "truefalse",
      prompt: "True or false: some Australian plants are adapted to fire (heat-opening seed stores, epicormic buds), and Indigenous fire practice is part of that living map.",
      answer: true,
      why: "Fire is not only catastrophe here. It is also a technology and an ecology. Crown fire in a hot eucalypt forest is still not a video-game joke.",
    },
    {
      id: "ec-bleach",
      afterHeading: "Interdependence and the human patch",
      type: "choice",
      prompt: "Coral bleaching, in one mechanism line:",
      choices: [
        { id: "a", label: "Fish paint the coral white", correct: false, why: "No." },
        { id: "b", label: "Heat stress: corals lose their algal partners", correct: true, why: "The city depends on that partnership. Marine heatwaves break it." },
        { id: "c", label: "The reef is not an ecosystem", correct: false, why: "It is a loud one." },
      ],
    },
  ],
  "historical-thinking": [
    {
      id: "hi-prim",
      afterHeading: "Primary vs secondary, and why you should care",
      type: "choice",
      prompt: "A 1788 captain’s log is",
      choices: [
        { id: "a", label: "useless because he was biased", correct: false, why: "Bias is a handle. You read with it." },
        { id: "b", label: "primary — he was there — and still a job application to the Admiralty", correct: true, why: "Both facts. That is the whole skill." },
        { id: "c", label: "a secondary textbook", correct: false, why: "He did not write a Year 9 chapter. He wrote a log." },
      ],
    },
    {
      id: "hi-cause",
      afterHeading: "Cause is a braid, not a billiard ball",
      type: "match",
      prompt: "Match the cause-move to the question.",
      pairs: [
        { left: "Trigger", right: "What lit it that week?" },
        { left: "Short-term", right: "What piled up that year?" },
        { left: "Long-term", right: "What made this thinkable?" },
        { left: "Consequence", right: "What actually changed after?" },
      ],
      why: "“Because” is lazy. Split the braid.",
    },
    {
      id: "hi-emp",
      afterHeading: "Empathy without cosplay",
      type: "truefalse",
      prompt: "True or false: historical empathy means you must forgive the action.",
      answer: false,
      why: "Reconstruct why it made sense then. Pardons are a different department. Critics existed at the time too.",
    },
  ],
  "ancient-worlds": [
    {
      id: "an-nile",
      afterHeading: "Egypt: the river as a machine",
      type: "choice",
      prompt: "Why do historians care so much about the Nile flood?",
      choices: [
        { id: "a", label: "Tourism", correct: false, why: "Not the ancient reason." },
        { id: "b", label: "Surplus grain funded specialists and the state", correct: true, why: "No surplus, no pyramids-as-logistics, no scribes." },
        { id: "c", label: "It invented Rome", correct: false, why: "Different river, different millennia." },
      ],
    },
    {
      id: "an-rome",
      afterHeading: "Rome: a city that ate a sea",
      type: "truefalse",
      prompt: "True or false: a useful Roman move was incorporating conquered elites rather than only stacking skulls.",
      answer: true,
      why: "Roads and law and citizenship (on Roman terms) are political technology. Still an empire. Still grain and slavery.",
    },
    {
      id: "an-grain",
      afterHeading: "What would you do: a grain year fails",
      type: "choice",
      prompt: "Granaries low, flood late. The historical skill is",
      choices: [
        { id: "a", label: "pick the one honourable button", correct: false, why: "There isn’t one. There are trade-offs and enemies." },
        { id: "b", label: "logistics plus a story that keeps people from walking away", correct: true, why: "Tax, army, temple, hinterland — then legitimacy." },
        { id: "c", label: "wait for Canberra", correct: false, why: "Wrong millennium." },
      ],
    },
  ],
  "country-contact": [
    {
      id: "co-empty",
      afterHeading: "1770 and 1788 are not the same event",
      type: "truefalse",
      prompt: "True or false: terra nullius described an actually empty continent.",
      answer: false,
      why: "It was a legal story that made British property simpler. People were here. Mabo said the common-law empty-land tale was wrong.",
    },
    {
      id: "co-deep",
      afterHeading: "Deep time is not a prologue",
      type: "choice",
      prompt: "“Hunter-gatherer” as a shrug fails because",
      choices: [
        { id: "a", label: "there were no people", correct: false, why: "There were, for tens of thousands of years." },
        { id: "b", label: "it hides farming-with-fire, aquaculture, trade, law, archives in song", correct: true, why: "Complexity is the point. Country is not dirt." },
        { id: "c", label: "everyone was identical across the continent", correct: false, why: "Hundreds of nations. Do not flatten." },
      ],
    },
    {
      id: "co-frontier",
      afterHeading: "Frontier: word vs. what happened",
      type: "choice",
      prompt: "The least honest headline for pastoral expansion is",
      choices: [
        { id: "a", label: "dispossession with violence and regional variation", correct: false, why: "That one can stand in a classroom." },
        { id: "b", label: "peaceful settlement of unused parkland", correct: true, why: "Euphemism is a source problem. Whose water, whose stock." },
        { id: "c", label: "contested, evidenced, still argued in the details", correct: false, why: "Historians argue numbers. Not whether it was a picnic." },
      ],
    },
  ],
  "making-australia": [
    {
      id: "mk-why",
      afterHeading: "Why federate at all",
      type: "choice",
      prompt: "Federation was mostly",
      choices: [
        { id: "a", label: "a folk circle around a campfire that had to happen", correct: false, why: "New Zealand looked and left. WA nearly didn’t. Close-run club politics." },
        { id: "b", label: "a deal: tariffs, defence, immigration control, jealous colonies", correct: true, why: "Lawyers in halls. Not destiny." },
        { id: "c", label: "Britain forcing identical railway gauges", correct: false, why: "The gauges stayed a mess. That’s half the joke." },
      ],
    },
    {
      id: "mk-67",
      afterHeading: "Who was the “people”",
      type: "truefalse",
      prompt: "True or false: the 1967 referendum is correctly summarised as “the year First Nations people got the vote.”",
      answer: false,
      why: "Common mix-up. 1967 changed constitutional counting and special laws. Franchise history is older, uneven, and racially gated in different ways. Precision is respect.",
    },
    {
      id: "mk-white",
      afterHeading: "The Constitution as a deal",
      type: "choice",
      prompt: "White Australia in the early Commonwealth was",
      choices: [
        { id: "a", label: "a side rumour", correct: false, why: "It organised who could come and stay." },
        { id: "b", label: "central — part of the Australian Settlement, not garnish", correct: true, why: "Describe it. Then you can fight it with facts." },
        { id: "c", label: "repealed in the Constitution’s first clause", correct: false, why: "It was policy and statute, and it lasted." },
      ],
    },
  ],
  "twentieth-century": [
    {
      id: "tw-gal",
      afterHeading: "1914–18: a remote war that arrived as lists",
      type: "choice",
      prompt: "Gallipoli’s myth vs. the Western Front body count:",
      choices: [
        { id: "a", label: "Gallipoli killed more Australians, so the myth is just maths", correct: false, why: "France killed more. Myths do other work." },
        { id: "b", label: "The louder story is Gallipoli; larger Australian deaths were in France/Belgium", correct: true, why: "Hold both. Myth plus lists." },
        { id: "c", label: "Australia sat WWI out", correct: false, why: "It did not." },
      ],
    },
    {
      id: "tw-sg",
      afterHeading: "1939–45: when the map moved south",
      type: "truefalse",
      prompt: "True or false: the fall of Singapore in 1942 shook the idea that the Empire could guarantee Australia’s north.",
      answer: true,
      why: "Darwin was bombed. The US alliance thickened. Curtin’s paperwork looks different after that shock.",
    },
    {
      id: "tw-ridge",
      afterHeading: "What would you do: a ridge, 1915",
      type: "choice",
      prompt: "A junior officer, bad maps, orders to attack. The historical skill is",
      choices: [
        { id: "a", label: "press the one honourable button", correct: false, why: "There isn’t a clean button. That’s the point." },
        { id: "b", label: "see the box: comms, class, offensive doctrine — then still judge the choice", correct: true, why: "Empathy without satellite-phone cosplay." },
        { id: "c", label: "refuse to judge anyone ever", correct: false, why: "Constraints explain. They do not mute." },
      ],
    },
  ],
};
