import type { DomainId, PathCheck } from "./types";

export const PATH_CHECKS: Record<DomainId, PathCheck[]> = {
  "mobile-devices": [
    {
      id: "md-fru",
      afterHeading: "Think in replaceable parts",
      type: "choice",
      prompt: "A thin laptop is slow. The user wants “a faster CPU.” What do you tell them?",
      choices: [
        {
          id: "a",
          label: "Most modern thin-and-lights have soldered CPUs — a faster chip usually means a different laptop",
          correct: true,
          why: "FRUs are RAM, storage, battery, display, sometimes a Wi-Fi card. The CPU is often not a socket swap.",
        },
        {
          id: "b",
          label: "Order any LGA socket CPU — laptop sockets are universal",
          correct: false,
          why: "Laptop CPUs are generation- and board-specific, and often not socketed at all.",
        },
        {
          id: "c",
          label: "Flash the BIOS to unlock hidden cores",
          correct: false,
          why: "That is not how laptop SKUs work, and it is a good way to brick a board.",
        },
      ],
    },
    {
      id: "md-usbc",
      afterHeading: "Docks, port replicators, and the cable people trip over",
      type: "truefalse",
      prompt: "True or false: if a laptop charges from a USB-C dock, that same port will always output video.",
      answer: false,
      why: "USB-C can be charge-only. Video needs DisplayPort Alt Mode or Thunderbolt. Ports are not equal.",
    },
    {
      id: "md-swell",
      afterHeading: "Phones and tablets: batteries, accessories, and sync",
      type: "choice",
      prompt: "A laptop trackpad is lifting the palm rest. What is the safety-first move?",
      choices: [
        {
          id: "a",
          label: "Power down, isolate the swollen Li-ion pack, and replace it — do not puncture or crush",
          correct: true,
          why: "Swelling is a battery failure. Isolate and dispose properly. Do not flatten the chassis.",
        },
        {
          id: "b",
          label: "Keep using it until the next maintenance window — swelling is cosmetic",
          correct: false,
          why: "A swollen cell can crack a panel and is a fire risk.",
        },
        {
          id: "c",
          label: "Calibrate the battery in Windows to shrink it back",
          correct: false,
          why: "Software cannot un-swell chemistry.",
        },
      ],
    },
    {
      id: "md-wifi",
      afterHeading: "The radios: Wi-Fi, Bluetooth, cellular, GPS, NFC",
      type: "choice",
      prompt: "After a screen swap, Wi-Fi range collapses. Ethernet is fine. First theory?",
      choices: [
        {
          id: "a",
          label: "Antenna leads (MAIN/AUX) were left off the combo card or pinched in the lid",
          correct: true,
          why: "Lid antennas are easy to unseat during a panel job. Ethernet does not use those leads.",
        },
        {
          id: "b",
          label: "Reinstall Windows to refresh the TCP/IP stack",
          correct: false,
          why: "A sudden range cliff after a lid repair is hardware path, not the OS.",
        },
        {
          id: "c",
          label: "The default gateway was lost during the repair",
          correct: false,
          why: "Gateways do not live in the display cable.",
        },
      ],
    },
  ],
  networking: [
    {
      id: "net-apipa",
      afterHeading: "A mental model, not a memorized OSI poster",
      type: "choice",
      prompt: "ipconfig shows 169.254.17.4. What failed?",
      choices: [
        {
          id: "a",
          label: "DHCP — this host gave itself APIPA because it got no lease",
          correct: true,
          why: "169.254.0.0/16 is APIPA. Fix the DHCP path, VLAN, or cable — not the browser.",
        },
        {
          id: "b",
          label: "DNS — 169.254 is a Google resolver",
          correct: false,
          why: "Public resolvers look like 8.8.8.8 or 1.1.1.1, not 169.254.",
        },
        {
          id: "c",
          label: "The NIC is in a loopback-only mode",
          correct: false,
          why: "Loopback is 127.0.0.1.",
        },
      ],
    },
    {
      id: "net-rdp",
      afterHeading: "Ports you must know cold",
      type: "choice",
      prompt: "A user needs Windows Remote Desktop through the firewall. Which port?",
      choices: [
        {
          id: "a",
          label: "TCP 3389",
          correct: true,
          why: "RDP listens on 3389. SSH is 22, HTTPS is 443, SMB is 445.",
        },
        {
          id: "b",
          label: "TCP 22",
          correct: false,
          why: "22 is SSH/SFTP.",
        },
        {
          id: "c",
          label: "UDP 67",
          correct: false,
          why: "67 is DHCP server.",
        },
        {
          id: "d",
          label: "TCP 445",
          correct: false,
          why: "445 is SMB file sharing.",
        },
      ],
    },
    {
      id: "net-ping",
      afterHeading: "Tools that settle arguments",
      type: "order",
      prompt: "A PC has “no internet.” Order these tests from inside-out.",
      items: [
        { id: "loop", label: "Ping 127.0.0.1 (stack)" },
        { id: "gw", label: "Ping the default gateway (LAN)" },
        { id: "wan", label: "Ping a public IP such as 8.8.8.8 (WAN)" },
        { id: "dns", label: "Resolve a name with nslookup / ping a FQDN (DNS)" },
      ],
      correctOrder: ["loop", "gw", "wan", "dns"],
      why: "This split tells you whether the NIC stack, LAN, WAN, or DNS is the broken layer.",
    },
    {
      id: "net-wep",
      afterHeading: "Wi-Fi standards without the marketing fog",
      type: "truefalse",
      prompt: "True or false: WEP is still acceptable on a home AP if the password is long.",
      answer: false,
      why: "WEP is broken. Baseline is WPA2-AES or WPA3. Enterprise Wi-Fi uses 802.1X, not a shared PSK.",
    },
  ],
  hardware: [
    {
      id: "hw-raid",
      afterHeading: "Storage and RAID, in the language of tickets",
      type: "match",
      prompt: "Match each RAID level to what you actually buy.",
      pairs: [
        { left: "RAID 0", right: "Speed only — any disk dies, array dies" },
        { left: "RAID 1", right: "Mirror — can lose one disk" },
        { left: "RAID 5", right: "Stripe + parity — min 3 disks, lose one" },
        { left: "RAID 10", right: "Stripe of mirrors — fast and redundant" },
      ],
      why: "RAID is not a backup. It keeps you online after a disk failure, not after ransomware or a deleted folder.",
    },
    {
      id: "hw-ddr",
      afterHeading: "RAM: generation, speed, and channels",
      type: "truefalse",
      prompt: "True or false: you can mix a DDR4 SODIMM into a desktop DDR5 DIMM slot with an adapter.",
      answer: false,
      why: "Generations and form factors do not mix. Different notches, voltages, and controllers.",
    },
    {
      id: "hw-cmos",
      afterHeading: "Motherboards, CPUs, and the BIOS/UEFI you flash once a year",
      type: "choice",
      prompt: "Every boot the clock is 2012 and BIOS settings vanish. First FRU?",
      choices: [
        {
          id: "a",
          label: "CMOS battery (and then re-set time, boot order, and virtualization)",
          correct: true,
          why: "A dead CMOS cell drops firmware settings. It is not a dead CPU.",
        },
        {
          id: "b",
          label: "New GPU — clocks live on the graphics card",
          correct: false,
          why: "Wall-clock and BIOS settings live with the chipset/CMOS.",
        },
        {
          id: "c",
          label: "Reinstall Windows to refresh HAL",
          correct: false,
          why: "The OS is not even up yet when firmware forgets the time.",
        },
      ],
    },
    {
      id: "hw-psu",
      afterHeading: "Power: wattage, rails, and the smell of a dead PSU",
      type: "choice",
      prompt: "A PC has no fans and no lights after a storm. A lamp on the same outlet works. Best first experiment?",
      choices: [
        {
          id: "a",
          label: "Prove the external power path, then test with a PSU tester or a known-good PSU",
          correct: true,
          why: "Dead-box tickets split power vs POST vs boot. Surges often kill the PSU first.",
        },
        {
          id: "b",
          label: "Reimage Windows from USB",
          correct: false,
          why: "There is no POST. The OS is not in the room.",
        },
        {
          id: "c",
          label: "Replace the motherboard on sight — storms always kill boards first",
          correct: false,
          why: "Possible later. Test the cheaper power theory first.",
        },
      ],
    },
  ],
  "virtualization-cloud": [
    {
      id: "vc-type",
      afterHeading: "Hypervisors and why the host still matters",
      type: "match",
      prompt: "Match the hypervisor type to where it sits.",
      pairs: [
        { left: "Type 1 (bare metal)", right: "On the hardware — ESXi, Hyper-V Server" },
        { left: "Type 2 (hosted)", right: "On a host OS — Workstation, VirtualBox" },
      ],
      extraRights: ["Only in the public cloud", "A container runtime that shares a kernel"],
      why: "Containers share a kernel. VMs virtualize a whole machine. A+ wants the VM story.",
    },
    {
      id: "vc-snap",
      afterHeading: "Client-side virtualization you will actually click",
      type: "truefalse",
      prompt: "True or false: a VM snapshot is a backup you can keep for a year.",
      answer: false,
      why: "Snapshots are short-term undo. Long chains slow disks and are a restore risk. Backups are a separate policy.",
    },
    {
      id: "vc-iaas",
      afterHeading: "Cloud characteristics, in plain language",
      type: "choice",
      prompt: "You still install patches on the guest OS. Which model is that?",
      choices: [
        {
          id: "a",
          label: "IaaS — you manage the OS, apps, and data",
          correct: true,
          why: "If you patch the OS, it is IaaS. PaaS is runtime. SaaS is “open the browser and work.”",
        },
        {
          id: "b",
          label: "SaaS — the vendor patches everything including your files",
          correct: false,
          why: "SaaS means you do not install an OS at all.",
        },
        {
          id: "c",
          label: "PaaS — you only manage the hypervisor",
          correct: false,
          why: "On PaaS you deploy code; the vendor owns the OS.",
        },
      ],
    },
  ],
  "hw-net-troubleshooting": [
    {
      id: "ts-loop",
      afterHeading: "The six-step loop (say it until it is boring)",
      type: "order",
      prompt: "Put CompTIA’s troubleshooting method in order.",
      items: [
        { id: "id", label: "Identify the problem" },
        { id: "th", label: "Establish a theory" },
        { id: "te", label: "Test the theory" },
        { id: "pl", label: "Plan of action" },
        { id: "ve", label: "Verify full function" },
        { id: "do", label: "Document" },
      ],
      correctOrder: ["id", "th", "te", "pl", "ve", "do"],
      why: "The exam rewards this loop more than heroics. Identify includes “can I undo this?”",
    },
    {
      id: "ts-dead",
      afterHeading: "Power, POST, and “nothing happens”",
      type: "choice",
      prompt: "Fans spin, no beep codes, no display, no POST LEDs you can read. Which bucket?",
      choices: [
        {
          id: "a",
          label: "POST path — CPU, RAM, GPU/board — not “reinstall Windows”",
          correct: true,
          why: "Power is present (fans). The firmware handshake is not. Minimal boot: one stick, onboard video, known-good PSU.",
        },
        {
          id: "b",
          label: "OS boot — run Startup Repair from USB",
          correct: false,
          why: "You never reached a bootloader.",
        },
        {
          id: "c",
          label: "DHCP — the NIC has no lease so the screen stays black",
          correct: false,
          why: "A lease does not drive POST.",
        },
      ],
    },
    {
      id: "ts-net",
      afterHeading: "Network symptoms with a decision tree",
      type: "match",
      prompt: "Match the symptom to the first fork.",
      pairs: [
        { left: "No link light", right: "Physical — cable, port, NIC" },
        { left: "169.254.x.x", right: "DHCP / VLAN / lease path" },
        { left: "Ping IP works, names fail", right: "DNS" },
        { left: "Ping 8.8.8.8 fails", right: "Gateway / WAN / firewall" },
      ],
      why: "Three commands split most “no internet” tickets: ipconfig, ping IP, nslookup.",
    },
  ],
  "operating-systems": [
    {
      id: "os-home",
      afterHeading: "Installs, upgrades, and the questions that change the outcome",
      type: "truefalse",
      prompt: "True or false: Windows 11 Home can join an on-prem Active Directory domain.",
      answer: false,
      why: "Domain join, BitLocker (full), and RDP host are Pro+ features. The SKU is wrong — not the password.",
    },
    {
      id: "os-gpt",
      afterHeading: "Installs, upgrades, and the questions that change the outcome",
      type: "choice",
      prompt: "UEFI firmware, setup cannot create a partition. Classic mismatch?",
      choices: [
        {
          id: "a",
          label: "Disk is MBR — UEFI expects GPT",
          correct: true,
          why: "UEFI + GPT, legacy BIOS + MBR. Convert or wipe with the matching style.",
        },
        {
          id: "b",
          label: "The CMOS battery is dead",
          correct: false,
          why: "A dead CMOS cell does not usually block partition style.",
        },
        {
          id: "c",
          label: "Missing Visual C++ redistributable",
          correct: false,
          why: "Setup has not installed apps yet.",
        },
      ],
    },
    {
      id: "os-tools",
      afterHeading: "The Windows tools you should open without thinking",
      type: "match",
      prompt: "Which tool for which job?",
      pairs: [
        { left: "sfc /scannow", right: "Repair protected system files" },
        { left: "DISM RestoreHealth", right: "Fix the component store when SFC cannot" },
        { left: "Event Viewer", right: "Why something died at 2:14 a.m." },
        { left: "Device Manager", right: "Yellow bangs and driver rollbacks" },
      ],
      why: "These are daily tools, not obscure extras.",
    },
  ],
  security: [
    {
      id: "sec-iso",
      afterHeading: "Malware and social engineering, as they appear on tickets",
      type: "choice",
      prompt: "Ransomware splash screen on a still-connected PC. First move?",
      choices: [
        {
          id: "a",
          label: "Isolate — pull the cable / disable Wi-Fi — then investigate",
          correct: true,
          why: "Stop the spread first. Do not run five scanners on a live LAN share.",
        },
        {
          id: "b",
          label: "Pay the ransom so finance can work, then scan",
          correct: false,
          why: "Do not pay as policy advice. Restore from known-good backups.",
        },
        {
          id: "c",
          label: "Post the sample to a public forum for IDs",
          correct: false,
          why: "You may leak data and you still have not contained it.",
        },
      ],
    },
    {
      id: "sec-mfa",
      afterHeading: "Authentication and access",
      type: "truefalse",
      prompt: "True or false: a password plus a PIN you also memorized counts as MFA.",
      answer: false,
      why: "MFA is two different factor types (know / have / are). Two secrets from the same brain are still “know.”",
    },
    {
      id: "sec-malware-order",
      afterHeading: "A practical malware response order",
      type: "order",
      prompt: "Order a practical malware response.",
      items: [
        { id: "iso", label: "Identify and isolate" },
        { id: "rem", label: "Remediate or rebuild from known-good media" },
        { id: "edu", label: "Verify, update protection, educate, document" },
      ],
      correctOrder: ["iso", "rem", "edu"],
      why: "Contain, then clean or wipe, then stop the next click.",
    },
  ],
  "software-troubleshooting": [
    {
      id: "sw-sys",
      afterHeading: "Windows will not boot (cleanly)",
      type: "choice",
      prompt: "A BSOD names nvlddmkm.sys after a GPU driver update. Best next step?",
      choices: [
        {
          id: "a",
          label: "Safe Mode (or WinRE) and roll back the driver",
          correct: true,
          why: "A named .sys is a driver lead. Roll back before you rebuild Windows.",
        },
        {
          id: "b",
          label: "Reinstall Office to refresh COM",
          correct: false,
          why: "Office is not the GPU kernel driver.",
        },
        {
          id: "c",
          label: "Disable the firewall so the driver can phone home",
          correct: false,
          why: "The box is not even staying up.",
        },
      ],
    },
    {
      id: "sw-profile",
      afterHeading: "Slow, crashy, and “it happens only to my account”",
      type: "truefalse",
      prompt: "True or false: if an app crashes only for one user on a shared PC, start with a machine-wide Windows reinstall.",
      answer: false,
      why: "One-user issues live in the profile, AppData, or per-user startup. All-users issues are drivers, services, disk.",
    },
    {
      id: "sw-clock",
      afterHeading: "Security-flavored software symptoms",
      type: "choice",
      prompt: "Every HTTPS site shows a certificate date error. Ping still works. First fork?",
      choices: [
        {
          id: "a",
          label: "Fix the system clock — then look at proxy/malware if it remains",
          correct: true,
          why: "A wrong clock makes every TLS handshake look expired. Do not reimage first.",
        },
        {
          id: "b",
          label: "Replace the NIC — certificates live in firmware on the card",
          correct: false,
          why: "NICs do not store the public web PKI.",
        },
        {
          id: "c",
          label: "Format the boot drive immediately",
          correct: false,
          why: "Too big a hammer for a clock.",
        },
      ],
    },
  ],
  "operational-procedures": [
    {
      id: "op-psu",
      afterHeading: "Safety and ESD — you cannot RMA a person",
      type: "truefalse",
      prompt: "True or false: you should open a failed PSU and replace the blown capacitor to save the shop money.",
      answer: false,
      why: "You replace the unit. High voltage lives inside. You cannot RMA a person.",
    },
    {
      id: "op-change",
      afterHeading: "Change management and documentation",
      type: "choice",
      prompt: "What must a change request include besides “it seemed like a good idea”?",
      choices: [
        {
          id: "a",
          label: "Reason, scope, risk, rollback, schedule, and approval",
          correct: true,
          why: "Rollback is a plan (snapshot, backup, image), not a hope. Do not patch finance at 10:00 Monday unannounced.",
        },
        {
          id: "b",
          label: "Only the vendor SKU of the patch",
          correct: false,
          why: "SKU without risk and rollback is not change control.",
        },
        {
          id: "c",
          label: "A screenshot of Reddit saying it is safe",
          correct: false,
          why: "Not an approval path.",
        },
      ],
    },
    {
      id: "op-backup",
      afterHeading: "Backups, recovery, and the 3-2-1 idea",
      type: "match",
      prompt: "What survives what?",
      pairs: [
        { left: "RAID", right: "A single disk failure (you stay online)" },
        { left: "Snapshot", right: "A short-term undo of a change" },
        { left: "Backup (3-2-1)", right: "Ransomware, fire, or “wrong folder deleted”" },
      ],
      extraRights: ["Faster RAM timings"],
      why: "You still want backups even if RAID and snapshots exist. Test restores or you have a ritual.",
    },
  ],
};
