import type { AplusDomainId, Quiz, QuizQuestion } from "../types";
import { core1Quizzes } from "./core1";
import { core2Quizzes } from "./core2";

type Fact = [objective: string, prompt: string, choices: [string, string, string, string], correct: 0 | 1 | 2 | 3, why: string];

const EXISTING_OBJECTIVES: Record<string, string> = {
  "md-q1": "1.2",
  "md-q2": "1.1",
  "md-q3": "1.2",
  "md-q4": "1.1",
  "md-q5": "1.3",
  "md-q6": "1.1",
  "md-q7": "1.3",
  "md-q8": "1.2",
  "md-q9": "1.3",
  "md-q10": "1.1",
  "net-q1": "2.6",
  "net-q2": "2.1",
  "net-q3": "2.1",
  "net-q4": "2.2",
  "net-q5": "2.4",
  "net-q6": "2.5",
  "net-q7": "2.8",
  "net-q8": "2.3",
  "net-q9": "2.7",
  "net-q10": "2.1",
  "hw-q1": "3.3",
  "hw-q2": "3.4",
  "hw-q3": "3.6",
  "hw-q4": "3.2",
  "hw-q5": "3.5",
  "hw-q6": "3.4",
  "hw-q7": "3.1",
  "hw-q8": "3.7",
  "hw-q9": "3.5",
  "hw-q10": "3.8",
  "vc-q1": "4.1",
  "vc-q2": "4.2",
  "vc-q3": "4.1",
  "vc-q4": "4.2",
  "vc-q5": "4.2",
  "vc-q6": "4.1",
  "vc-q7": "4.2",
  "vc-q8": "4.1",
  "vc-q9": "4.2",
  "vc-q10": "4.1",
  "tn-q1": "5.1",
  "tn-q2": "5.2",
  "tn-q3": "5.5",
  "tn-q4": "5.4",
  "tn-q5": "5.3",
  "tn-q6": "5.6",
  "tn-q7": "5.1",
  "tn-q8": "5.5",
  "tn-q9": "5.2",
  "tn-q10": "5.4",
  "os-q1": "1.3",
  "os-q2": "1.5",
  "os-q3": "1.2",
  "os-q4": "1.4",
  "os-q5": "1.1",
  "os-q6": "1.8",
  "os-q7": "1.9",
  "os-q8": "1.6",
  "os-q9": "1.7",
  "os-q10": "1.10",
  "sec-q1": "2.4",
  "sec-q2": "2.5",
  "sec-q3": "2.3",
  "sec-q4": "2.2",
  "sec-q5": "2.1",
  "sec-q6": "2.6",
  "sec-q7": "2.7",
  "sec-q8": "2.4",
  "sec-q9": "2.2",
  "sec-q10": "2.5",
  "sw-q1": "3.1",
  "sw-q2": "3.1",
  "sw-q3": "3.2",
  "sw-q4": "3.3",
  "sw-q5": "3.4",
  "sw-q6": "3.1",
  "sw-q7": "3.3",
  "sw-q8": "3.2",
  "sw-q9": "3.1",
  "sw-q10": "3.4",
  "op-q1": "4.3",
  "op-q2": "4.1",
  "op-q3": "4.3",
  "op-q4": "4.5",
  "op-q5": "4.2",
  "op-q6": "4.4",
  "op-q7": "4.6",
  "op-q8": "4.1",
  "op-q9": "4.3",
  "op-q10": "4.5",
};

const BANKS: Record<AplusDomainId, Fact[]> = {
  "mobile-devices": [
    ["1.1", "Which laptop memory form factor is the usual field replacement?", ["SODIMM", "DIMM", "SIMM", "RIMM"], 0, "Laptops use SODIMM (or soldered LPDDR). Full-size DIMMs belong in desktops."],
    ["1.1", "Wi-Fi antennas on a clamshell laptop are most often routed through the…", ["Display lid", "Battery pack", "Optical bay", "CMOS coin cell"], 0, "MAIN/AUX leads typically run into the lid. A panel swap can pinch them."],
    ["1.1", "A swollen lithium-ion pack is lifting a phone screen. First safety move?", ["Power down, isolate, do not puncture", "Press the glass flat overnight", "Microwave the pack to shrink it", "Keep charging until calibration finishes"], 0, "Swelling is a failed cell. Isolate and dispose; never crush or puncture."],
    ["1.1", "Which part is often NOT a laptop FRU on a modern thin-and-light?", ["Soldered CPU", "SODIMM", "M.2 SSD", "Wi-Fi card"], 0, "Many ultrabook CPUs are BGA. RAM, storage, and Wi-Fi cards are the usual swaps."],
    ["1.1", "After a display replacement the webcam is dead. Likely cause?", ["Lid cable or camera module left unseated", "The SSD was installed backwards", "APIPA on the NIC", "RAID 0 is rebuilding"], 0, "The webcam rides a lid ribbon. Reseat before you order a board."],
    ["1.1", "A laptop only charges from one USB-C port. The other USB-C port does data only. What is true?", ["USB-C ports are not equal — check the spec for PD", "Every USB-C port must supply 100 W", "Charge-only ports always output DisplayPort", "The CMOS battery gates USB-C power"], 0, "Some ports are USB 2.0 data. Others add PD, DP Alt Mode, or Thunderbolt."],
    ["1.2", "A dock that works on Laptop A shows no video on Laptop B. Check first?", ["Whether B’s USB-C supports DP Alt Mode or Thunderbolt", "Whether B needs a new default gateway", "Whether RAID 1 is degraded", "Whether the CMOS jumper is open"], 0, "Video over USB-C needs Alt Mode or Thunderbolt. Charge-only ports will not drive a dock display."],
    ["1.2", "Lightning connectors are associated with which vendor family?", ["Older Apple phones and accessories", "All Android tablets", "SATA optical drives", "Molex fans"], 0, "Lightning is Apple’s older phone/tablet connector. Newer iPads moved to USB-C."],
    ["1.2", "A port replicator compared with a full docking station typically…", ["Adds ports, often without extra GPU power or a full desk chipset", "Always includes an extra discrete GPU", "Replaces the laptop PSU with ATX 24-pin", "Is only used for RAID enclosures"], 0, "Replicators are the lighter cousin: extra I/O, usually no extra graphics silicon."],
    ["1.2", "NFC payments fail through a thick metal phone case. Likely reason?", ["The case is shielding the short-range coil", "The SIM PIN is wrong", "SMTP is blocked", "The SSD is in RAID 0"], 0, "NFC is centimetres and hates metal plates and some wallets."],
    ["1.2", "Tethering a laptop to a phone hotspot still fails while the phone browses. First theory?", ["Carrier hotspot block, data saver, or quota", "The laptop needs a new CMOS battery", "RAID 5 is rebuilding", "IMAP is down"], 0, "The phone can have data while hotspot DHCP or the plan is denied."],
    ["1.2", "USB-C, micro-USB, and mini-USB are all…", ["Physical connector families — not the same capability", "Guaranteed Thunderbolt 4", "Always 100 W PD", "DisplayPort only"], 0, "The hole shape is not the spec. Check data, power, and video separately."],
    ["1.3", "Airplane mode is useful in a radio test because it…", ["Disables the radios together for a clean baseline", "Formats the eSIM", "Forces APIPA", "Enables RAID 1"], 0, "Kill all radios, then enable one at a time."],
    ["1.3", "Indoor GPS “wrong city” is most often…", ["Location services / Wi-Fi assist, not a dead GPS chip", "A failed SODIMM", "Port 445 blocked", "A swollen inverter"], 0, "GPS wants sky. Indoor location is often fused with Wi-Fi and cell."],
    ["1.3", "A wiped iPhone still asks for the previous Apple ID. What was missed?", ["Activation Lock / iCloud lock (and MDM if supervised)", "Removing Bluetooth before the wipe", "Updating iOS after the wipe only", "Clearing the ARP cache"], 0, "Activation Lock stays bound to the identity until released."],
    ["1.3", "MDM on a supervised phone can typically…", ["Push Wi-Fi, VPN, and camera restrictions the user cannot remove", "Replace a swollen battery over the air", "Upgrade soldered RAM", "Change the CPU socket"], 0, "Supervision is policy, not hardware repair."],
    ["1.3", "Bluetooth pairing fails at the PIN step. Best next test?", ["Retry pairing at short range with a known PIN; forget old cache", "Reinstall the laptop CPU", "Disable DHCP on the AP", "Format the SSD as RAID 0"], 0, "Pairing is radio + cache + PIN. Stay close and clear old bonds."],
    ["1.3", "A corporate Android enrolls in MDM as BYOD. What is the point of the work profile?", ["Separate work apps/data from the personal side", "Give the user a faster CPU", "Disable all radios forever", "Convert microSD into RAID 10"], 0, "Work profile is a policy boundary, not a hardware SKU."],
    ["1.1", "Biometric unlock on a laptop is usually which hardware?", ["Fingerprint reader or IR camera in the bezel", "The TPM only, with no sensor", "The SATA optical drive", "The CMOS jumper"], 0, "Windows Hello still needs a sensor. TPM stores keys; it is not the finger."],
    ["1.1", "A laptop keyboard replacement often means replacing the…", ["Top cover assembly or key deck, not one floating key", "Entire motherboard always", "PSU 24-pin", "DIMM latches"], 0, "Many notebooks treat the keyboard as part of the palm-rest assembly."],
    ["1.2", "A USB headset is silent while a 3.5 mm headset works. Check?", ["Windows sound output device and the USB audio endpoint", "Whether RAID 1 is degraded", "The default gateway only", "S.M.A.R.T. on the HDD"], 0, "USB audio is a separate device. The analog jack does not prove the USB stack."],
    ["1.2", "A drawing tablet needs a digitizer channel. A failed stylus is often…", ["A dead tip, unpaired Bluetooth, or palm-rejection settings", "APIPA on the LAN", "A missing SMTP relay", "ECC RAM"], 0, "Digitizer issues are tip, radio, or software — not a WAN outage."],
    ["1.3", "Hotspot vs tethering USB: the phone is acting as a…", ["Router (NAT + DHCP) for the laptop", "Hypervisor Type 1", "Print server only", "RAID controller"], 0, "The phone shares its WAN. The laptop is just a DHCP client."],
    ["1.3", "eSIM vs physical SIM: the field issue is usually…", ["Carrier provisioning / profile, not a missing plastic card", "Soldered RAM", "Port 23 being open", "RAID stripe size"], 0, "eSIM still needs a downloaded profile. No profile, no attach."],
    ["1.1", "A laptop that charges but will not turn on is a different ticket from…", ["A laptop that will not charge at all", "A printer paper jam", "An MX record failure", "A missing CNAME"], 0, "Power-in vs power-on split the FRU list (adapter/port vs board/battery/button)."],
    ["1.2", "Qi wireless charging needs…", ["A healthy coil and a case that is not a metal plate sandwich", "Thunderbolt 4", "ECC registered DIMMs", "Port 3389"], 0, "Metal rings and wallet plates kill the coil coupling."],
    ["1.3", "Calendar/contacts not syncing after a mail cutover is often…", ["Account type (IMAP vs Exchange) or MDM app allow-list", "A failed GPU", "RAID 0", "APIPA"], 0, "Sync is identity and protocol, not a display cable."],
    ["1.1", "Document screw lengths on a laptop because…", ["A long screw into a battery or board is a short waiting to happen", "Screws set the Wi-Fi channel", "Longer screws raise RAID speed", "UEFI requires metric only"], 0, "Service manuals call out screw maps for a reason."],
    ["1.1", "Disconnect internal battery (or the vendor pad) before you unplug a display ribbon because…", ["The system can still have power on the cable", "It increases DIMM frequency", "It clears APIPA", "It rebuilds RAID 5"], 0, "Standby rails can live with the pack connected."],
    ["1.2", "A flaky USB-C dock that works on a known-good cable most often points to…", ["A damaged receptacle on the laptop", "A failed MX record", "BitLocker recovery", "ext4 vs NTFS"], 0, "Wiggle test the laptop port. Docks die too, but the receptacle is a classic."],
    ["1.3", "Find My / Google Find can typically…", ["Locate, lock, or erase a lost phone", "Upgrade soldered RAM", "Change CPU sockets", "Convert HDD to NVMe in place"], 0, "Those are identity services, not hardware upgrades."],
    ["1.2", "A headset with a TRRS jack that has no mic is often…", ["CTIA vs OMTP wiring or a TRS-only port", "RAID 6", "Port 67 only", "TPM 2.0 missing"], 0, "Mic rings are not universal. Adapters exist for a reason."],
  ],
  networking: [
    ["2.1", "HTTPS typically uses which TCP port?", ["443", "80", "22", "25"], 0, "HTTP is 80. HTTPS (TLS) is 443."],
    ["2.1", "SSH remote shell uses TCP port…", ["22", "23", "21", "3389"], 0, "22 is SSH/SFTP. 23 is Telnet. 3389 is RDP."],
    ["2.1", "DNS queries commonly use UDP port…", ["53", "67", "80", "445"], 0, "DNS is 53. DHCP is 67/68. SMB is 445."],
    ["2.1", "RDP uses TCP port…", ["3389", "389", "443", "22"], 0, "3389 is Remote Desktop. 389 is LDAP."],
    ["2.1", "SMTP for server mail is classically port…", ["25", "53", "80", "445"], 0, "25 is SMTP. Clients often use 587 in the real world — still know 25 for A+."],
    ["2.1", "SMB file sharing on modern Windows uses TCP…", ["445", "23", "67", "161"], 0, "445 is SMB. Older NetBIOS used 137–139."],
    ["2.1", "DHCP server / client ports are…", ["67 / 68", "20 / 21", "161 / 162", "110 / 143"], 0, "Server listens on 67, client on 68."],
    ["2.1", "LDAP directory traffic is classically TCP…", ["389", "3389", "22", "80"], 0, "389 LDAP, 636 LDAPS, 3389 RDP — easy mix-up."],
    ["2.1", "HTTP without TLS uses TCP…", ["80", "443", "22", "25"], 0, "Cleartext web is 80."],
    ["2.1", "Telnet, the cleartext remote shell, is port…", ["23", "22", "21", "3389"], 0, "Know it exists. Do not use it."],
    ["2.1", "POP3 mail retrieval is port…", ["110", "25", "443", "53"], 0, "110 POP3, 143 IMAP, 25 SMTP."],
    ["2.1", "IMAP mail retrieval is port…", ["143", "110", "25", "445"], 0, "IMAP 143 (993 with TLS). POP3 is 110."],
    ["2.1", "FTP control is typically port…", ["21", "22", "23", "25"], 0, "21 control, 20 data in active FTP. Prefer SFTP."],
    ["2.2", "2.4 GHz Wi-Fi compared with 5 GHz generally has…", ["Longer range, more interference, fewer non-overlapping channels", "Shorter range and no microwave ovens nearby", "Only 6 GHz clients", "No 802.11 support"], 0, "2.4 GHz travels and collides. 5 GHz is faster and fussier about walls."],
    ["2.2", "Wi-Fi 6E adds which band?", ["6 GHz", "900 MHz only", "60 GHz only", "HF shortwave"], 0, "6 GHz is the new clean air. Clients and APs must both support it."],
    ["2.2", "Bluetooth is a…", ["Short-range PAN radio, often on the Wi-Fi combo card", "Routed WAN protocol like BGP", "Replacement for SMTP", "Fibre connector"], 0, "PAN. It shares silicon and sometimes antennas with Wi-Fi."],
    ["2.3", "A host with no DHCP lease and 169.254.x.x has…", ["APIPA — DHCP failed", "A public routable address", "IPv6 only", "A DHCP reservation"], 0, "169.254/16 is link-local IPv4 when DHCP is silent."],
    ["2.3", "DNS A vs AAAA records map names to…", ["IPv4 vs IPv6 addresses", "Mail exchangers vs text", "VLANs vs VPNs", "MAC vs serial"], 0, "A is IPv4. AAAA is IPv6."],
    ["2.3", "DHCP reservations are useful when…", ["A host should keep the same IPv4 from the server pool", "You want APIPA on purpose", "You are disabling DNS", "You need a loopback plug"], 0, "Reservation ≠ static typed on the NIC. The server still hands it out."],
    ["2.4", "A VLAN’s job is to…", ["Segment a switch into separate L2 broadcast domains", "Replace DNS", "Encrypt SMB", "Power a PoE camera"], 0, "VLAN = virtual LAN. Routing still needed between them."],
    ["2.4", "A VPN typically…", ["Encrypts a tunnel to another network over the internet", "Replaces the subnet mask with APIPA", "Is a cable category", "Is RAID for packets"], 0, "Virtual private network. Split tunnel vs full tunnel is a later fight."],
    ["2.5", "A managed switch unlike an unmanaged one can often…", ["Offer VLANs, SNMP, and port security", "Only pass PoE", "Never flood broadcasts", "Replace a router’s NAT automatically"], 0, "Unmanaged is a dumb repeater of frames. Managed has a config plane."],
    ["2.5", "PoE delivers power over…", ["Ethernet pairs to a phone, AP, or camera", "USB-C only", "DisplayPort", "SATA"], 0, "Injector or PoE switch. Check the watt budget."],
    ["2.5", "An ONT sits at the…", ["Fibre handoff into the premises", "Core of a SAN", "CMOS battery", "RAID controller"], 0, "Optical network terminal. The ISP’s light becomes Ethernet."],
    ["2.6", "A wrong default gateway usually means…", ["Local LAN works, internet does not", "DNS always works", "DHCP cannot exist", "Cables stop negotiating"], 0, "Gateway is the door off this LAN."],
    ["2.6", "A /24 IPv4 mask is…", ["255.255.255.0", "255.255.0.0", "255.0.0.0", "255.255.255.255"], 0, "24 bits of network. Classic small LAN."],
    ["2.6", "Private IPv4 examples include…", ["10/8, 172.16/12, 192.168/16", "8.8.8.8 only", "169.254 as a public WAN", "224.0.0.1 as a host address you ping for DHCP"], 0, "RFC 1918. APIPA is not a planned LAN plan."],
    ["2.7", "A PAN is typically…", ["Phone to earbuds / watch — personal area", "A campus fibre ring", "A storage array fabric", "An undersea cable"], 0, "Personal. WLAN is the office radio LAN. WAN is the long haul."],
    ["2.7", "Satellite internet compared with fibre usually has…", ["Higher latency", "Lower latency always", "No weather issues", "Layer-1 identical to DAC"], 0, "Speed of light to orbit is the tax."],
    ["2.8", "A toner probe is for…", ["Tracing which pair is which in a bundle", "Measuring PSU rails", "Crimping RJ45", "Punching down nothing"], 0, "Tone generator + probe. Cable tester is continuity/map."],
    ["2.8", "A loopback plug on Ethernet is used to…", ["Test a NIC by looping TX to RX", "PoE-inject a camera", "Punch down CAT6", "Strip plenum"], 0, "Hardware loopback, not a 127.0.0.1 ping (that is software)."],
    ["2.8", "A Wi-Fi analyzer helps you…", ["See channels, overlap, and signal — not guess SSID names only", "Crimp RJ11", "Flash UEFI", "Format NTFS"], 0, "Spectrum/channel view beats “it feels weak.”"],
    ["2.2", "RFID compared with NFC is typically…", ["Longer-range identification tags vs tap-to-pay centimetres", "A fibre connector", "IPv6 only", "Port 22"], 0, "NFC is a close cousin used for payments and pairing."],
    ["2.3", "A syslog server’s job is to…", ["Collect logs from networked devices", "Hand out DHCP", "Terminate fibre", "Host MX records only"], 0, "Central logs. Not DNS, not DHCP."],
    ["2.5", "A patch panel exists so that…", ["Horizontal runs terminate neatly instead of on the switch face", "PoE becomes fibre", "VLANs configure themselves", "APIPA is disabled"], 0, "Punch down once, patch often."],
    ["2.4", "A DNS MX record points to…", ["The mail exchanger for a domain", "The IPv6 address of a host", "A VLAN ID", "A PoE budget"], 0, "Mail server name. A/AAAA still need to resolve that name."],
    ["2.4", "SPF / DKIM / DMARC live in DNS to help with…", ["Mail authentication and spoofing defense", "Wi-Fi channel width", "RAID parity", "SODIMM timings"], 0, "TXT-ish mail auth. Not LAN addressing."],
    ["2.7", "A SAN is primarily…", ["Block storage on a dedicated network", "A Bluetooth watch link", "A DSL modem feature", "An RJ11 wall jack"], 0, "Storage area network. Not the same as a file share on the LAN."],
    ["2.6", "Static vs DHCP on a SOHO PC: static means…", ["You typed address, mask, gateway, DNS yourself", "APIPA will always win", "The ISP cannot exist", "IPv6 is forbidden"], 0, "Static is manual. Dynamic is leased."],
  ],
  hardware: [
    ["3.1", "IPS vs TN LCD in one line?", ["IPS: better angles/colour; TN: cheaper/faster historically", "TN is always OLED", "IPS needs an inverter for LED backlight always", "Mini-LED is a connector"], 0, "Panel tech is not the connector. OLED is emissive, no separate CCFL inverter."],
    ["3.1", "A digitizer on a laptop screen is the…", ["Touch/pen input layer", "Inverter for CCFL only", "SATA controller", "PSU 5 V rail"], 0, "Broken glass can still show picture with a dead digitizer — or the reverse."],
    ["3.2", "T568A vs T568B are…", ["Two pinouts for RJ45 — both work if both ends match", "Fibre polish types", "RAID levels", "USB versions"], 0, "Mixing A and B on one cable makes a crossover. Match the plant."],
    ["3.2", "Plenum-rated cable is chosen because…", ["Jacket chemistry for air-handling spaces", "It is always Cat 8", "It cannot carry PoE", "It is coaxial only"], 0, "Fire code, not speed."],
    ["3.2", "Single-mode fibre compared with multimode typically…", ["Longer distance, smaller core, laser", "Shorter distance only, LED, huge core", "Uses RJ11", "Is a USB pinout"], 0, "OS2 vs OM3/OM4 is a later mnemonic. Distance is the headline."],
    ["3.2", "HDMI vs DisplayPort vs VGA: VGA is…", ["Analog video", "Packetised like DP", "Always audio on pin 1", "Thunderbolt only"], 0, "VGA is analog. HDMI/DP are digital (HDMI also carries audio)."],
    ["3.2", "SATA data vs power: the data connector is…", ["The thin L-shaped data cable, separate from the power pigtail", "Molex-only", "24-pin ATX", "RJ45"], 0, "Do not confuse SATA power with data. eSATA is the external cousin."],
    ["3.3", "SODIMM vs DIMM: SODIMM is…", ["The small outline module used in laptops and some SFFs", "Always ECC registered", "Only DDR2", "A RAID stripe"], 0, "Desktops: DIMM. Laptops: SODIMM or soldered."],
    ["3.3", "ECC RAM is used when…", ["You need error correction (servers/workstations), not faster games", "You want dual-channel only", "The PSU is modular", "The panel is OLED"], 0, "ECC vs non-ECC is a motherboard/CPU feature, not a heat-sink sticker."],
    ["3.3", "Dual-channel RAM wants…", ["Matched modules in the correct colour slots", "One stick in any slot always", "RAID 1", "Port 445"], 0, "Populate the pairs the manual shows. Mixing sizes can fall back to flex."],
    ["3.4", "NVMe vs SATA SSD: NVMe typically rides…", ["PCIe (often M.2)", "Only spinning 3.5-inch", "RJ11", "VGA"], 0, "NVMe is the protocol. M.2 is a slot that might be SATA or NVMe — read the silkscreen."],
    ["3.4", "RAID 1’s headline is…", ["Mirroring — survive one disk, no extra stripe speed like RAID 0", "Striping with no redundancy", "Dual parity like RAID 6", "Hot spare only"], 0, "RAID 0 stripes and dies on one disk. RAID 1 mirrors."],
    ["3.4", "RAID 5 needs a minimum of…", ["Three disks (striping + parity)", "Two disks", "One disk", "Twelve disks"], 0, "One disk can fail. Rebuilds are stressful. RAID is not a backup."],
    ["3.4", "2.5-inch vs 3.5-inch HDDs are…", ["Form factors — laptops/SFF vs desktops", "Speed ratings of NVMe", "USB versions", "RAID levels"], 0, "Laptops used 2.5-inch spinning disks. Desktops 3.5-inch."],
    ["3.5", "ATX vs microATX vs ITX is about…", ["Motherboard size and expansion", "RAM generation only", "PSU colour", "Display panel type"], 0, "ITX is tiny. ATX has more slots. Check the case."],
    ["3.5", "UEFI Secure Boot’s job is to…", ["Load only signed bootloaders", "Overclock RAM", "Replace TPM solder", "Set T568B"], 0, "It is a boot policy, not antivirus by itself."],
    ["3.5", "TPM is used for…", ["Platform keys — BitLocker and measured boot live here", "Faster NVMe", "PoE budgets", "RJ45 pinouts"], 0, "Trusted Platform Module. Hardware security module is the bulk cousin."],
    ["3.5", "x86/x64 vs ARM is…", ["CPU architecture — apps are not always interchangeable", "A RAID level", "A Wi-Fi band", "A fibre polish"], 0, "Windows on ARM is a different binary world than Intel/AMD x64."],
    ["3.6", "A 24-pin (20+4) connector feeds the…", ["Motherboard primary power", "CPU 8-pin only", "SATA data", "DisplayPort"], 0, "CPU still wants its own EPS/8-pin on most boards."],
    ["3.6", "110–120 vs 220–240 VAC on a PSU is…", ["Input voltage selector or auto-range — get it wrong and you let smoke out", "Output rail names", "PCIe versions", "RAID stripe size"], 0, "Red switch on older units. Auto-range on most modern ones."],
    ["3.6", "Modular PSU cables mean…", ["You plug only the cables you need", "The rails are 48 V only", "It cannot power a GPU", "It is always redundant"], 0, "Less clutter. Still match the vendor cables — pinouts differ."],
    ["3.7", "PCL vs PostScript on a printer is…", ["Page-description languages / driver families", "Toner colours", "RAID 10", "USB versions"], 0, "Wrong driver = garbage print. Firmware still matters."],
    ["3.7", "An ADF on a MFP is the…", ["Automatic document feeder", "Toner waste pack", "Fuser lamp only", "Inkjet damper"], 0, "Feeds a stack. Flatbed is the glass."],
    ["3.8", "Laser printer maintenance kit typically includes…", ["Fuser / rollers — not just “more toner”", "A new CPU", "ECC RAM", "An ONT"], 0, "Page-count kits exist. Calibrate and clean as the vendor says."],
    ["3.8", "Inkjet printheads that streak often need…", ["A clean cycle or replacement — not a new RAID controller", "A TPM clear", "Port 25 open", "APIPA"], 0, "Clogged nozzles. Alignment after a head change."],
    ["3.8", "Thermal printers want…", ["Special thermal paper and a clean heating element", "CMYK toner", "Impact ribbons only", "SATA power"], 0, "Receipt printers. No toner."],
    ["3.8", "Impact (dot matrix) still exists for…", ["Multipart carbon forms", "Photo paper gloss", "OLED calibration", "NVMe heatsinks"], 0, "Ribbon + tractor. Loud on purpose."],
    ["3.2", "USB-C as a video cable works when…", ["The port speaks DP Alt Mode (or Thunderbolt)", "Every USB-C is video", "It is charge-only", "It is USB 2.0 only"], 0, "Same hole, different wires."],
    ["3.4", "RAID 10 is…", ["Striped mirrors — speed + redundancy, four disks typical minimum", "Single disk spanning", "JBOD with a name", "Parity on two disks only"], 0, "1+0. Costs disks. Rebuilds are saner than RAID 5 on big drives."],
    ["3.5", "Thermal paste exists to…", ["Fill microscopic gaps between die and heatsink", "Glue the GPU permanently", "Lubricate fans", "Coat SATA power"], 0, "Pea or spread — vendor method. Too much is messy, too little cooks the die."],
    ["3.6", "The 12 V rail on a PC PSU is the heavy lifter for…", ["CPU/GPU conversion; 3.3/5 V for logic and some peripherals", "Only the USB ports", "Only the CMOS battery", "PoE cameras"], 0, "Modern platforms convert 12 V on board."],
    ["3.7", "Secured print / badging on an MFP is…", ["Hold-until-authenticate so pages do not sit in the open", "Faster toner melt", "IPv6 only", "RAID for spools"], 0, "Privacy on the glass and in the tray."],
    ["3.1", "OLED burn-in risk compared with LCD is…", ["Higher for static HUD/taskbars", "Zero because OLED has a backlight inverter", "Only on VGA", "Solved by RAID"], 0, "Emissive pixels age. Screen shift and hide taskbars help."],
    ["3.3", "DDR generation (DDR4 vs DDR5) is…", ["Not interchangeable in the same slot", "Just a speed XMP sticker", "A RAID level", "A USB version"], 0, "Keying differs. The board’s QVL is the adult answer."],
    ["3.5", "A capture card is an add-in that…", ["Ingests HDMI/SDI for recording or streaming", "Replaces the PSU 24-pin", "Is a SODIMM", "Terminates fibre"], 0, "Not a GPU, though some GPUs can encode."],
    ["3.2", "RJ11 vs RJ45: RJ11 is…", ["The smaller phone/DSL jack", "Always 8P8C Ethernet", "Fibre SC", "Molex"], 0, "Do not jam RJ11 into RJ45 hoping for a LAN."],
    ["3.4", "mSATA vs M.2: mSATA is…", ["The older mini-SATA card; M.2 replaced most of it", "Always NVMe", "A DIMM", "A display standard"], 0, "Look at the slot. They are not the same card."],
    ["3.6", "Redundant PSUs in a server mean…", ["Two units; one can fail and the box stays up", "Twice the 3.3 V for RGB", "RAID 0 for power", "A paperclip test is required"], 0, "Hot-swap in the datacentre. Still size each unit for the load."],
  ],
  "virtualization-cloud": [
    ["4.1", "A Type 1 hypervisor runs…", ["On bare metal (ESXi, Hyper-V server)", "Inside a desktop OS only, always", "Only in a browser", "As a RAID firmware"], 0, "Type 2 sits on an OS (Workstation, VirtualBox). Type 1 is the metal."],
    ["4.1", "A VM sandbox is useful because…", ["You can detonate unknown software off the host", "It upgrades soldered RAM", "It replaces DNS", "It is RAID 6"], 0, "Isolation is the point. Snapshots are not backups forever."],
    ["4.1", "VDI means…", ["Desktop OS delivered from a server farm", "A fibre connector", "A PSU rail", "APIPA"], 0, "Virtual Desktop Infrastructure. The PC can be a thin client."],
    ["4.1", "Containers vs VMs: containers share…", ["The host kernel; VMs virtualise hardware/OS", "Nothing; they are identical", "Only the GPU", "Only the CMOS"], 0, "Lighter isolation. Not a replacement for every VM."],
    ["4.1", "Nested virtualization needs…", ["CPU flags (VT-x/AMD-V) passed through", "APIPA", "Port 23", "VGA only"], 0, "The guest hypervisor still needs hardware assists."],
    ["4.1", "Application virtualization is for…", ["Running an app without a full second OS install", "Replacing the PSU", "Cat 6 pinouts", "Punchdown"], 0, "Legacy line-of-business apps are the usual customer."],
    ["4.1", "A VM still needs…", ["vCPU, memory, storage, and a virtual NIC — they are not free", "No resources; the host is magic", "Physical SODIMMs inside the VM case", "Its own ATX 24-pin"], 0, "Overcommit carefully. Storage latency shows up as “the VM is slow.”"],
    ["4.2", "IaaS vs SaaS: IaaS is…", ["You rent VMs/networks/disks; SaaS is the finished app", "Always Gmail-only", "Always on-prem hypervisors", "A cable type"], 0, "IaaS = infrastructure. PaaS = platform. SaaS = software."],
    ["4.2", "PaaS is the middle: you bring…", ["Code; the vendor brings runtime and OS patching", "Racks and PDUs", "Only a browser bookmark", "RJ11"], 0, "Heroku-style. You are not patching the guest OS the same way as IaaS."],
    ["4.2", "Public vs private cloud: private is…", ["Dedicated to one org (on-prem or hosted exclusive)", "Always cheaper", "Always SaaS", "Always Type 2"], 0, "Hybrid is both. Community is a shared niche."],
    ["4.2", "Elasticity in cloud-speak means…", ["Scale out/in with demand", "The VM cannot reboot", "Fibre stretch", "ECC only"], 0, "Metered: you pay for what you spin."],
    ["4.2", "Multitenancy means…", ["Many customers share the platform with isolation boundaries", "One VM per planet", "No identity", "RAID 0 required"], 0, "Your neighbour is another tenant. Isolation is the vendor’s job and yours."],
    ["4.2", "Metered ingress/egress is…", ["You may pay for data in/out of the cloud", "Always free forever", "A CAT6 spec", "A hypervisor type"], 0, "Leaving the cloud can cost more than compute."],
    ["4.1", "Cross-platform virtualization example?", ["A Windows VM on a Linux host (or the reverse)", "Two identical physical laptops", "RAID 1", "T568A"], 0, "The guest OS can differ from the host."],
    ["4.1", "Legacy OS in a VM is a common reason to virtualise because…", ["The old app dies on modern hardware/OS", "VMs make CPUs faster than silicon", "Cloud forbids IaaS", "USB-C cannot exist"], 0, "Keep the junk in a box. Snapshot before you poke it."],
    ["4.2", "File sync as a cloud characteristic is…", ["One namespace across devices (Drive, OneDrive)", "RAID 5 on a SAN only", "APIPA", "Port 23"], 0, "Conflict copies are the gotcha."],
    ["4.2", "Dedicated vs shared resources: dedicated is…", ["Not oversubscribed to other tenants the same way", "Always cheaper", "Always Type 2", "A display panel"], 0, "You pay for the isolation."],
    ["4.1", "A Type 2 hypervisor example is…", ["VirtualBox or VMware Workstation on Windows/macOS", "ESXi on bare metal only", "An ONT", "A toner probe"], 0, "Convenient on a laptop. Not what a cluster runs."],
    ["4.2", "Hybrid cloud is…", ["Burst or identity spanning on-prem and public", "Two SaaS logos", "IPv6 only", "A PSU mode"], 0, "VPN/ExpressRoute/interconnect is the plumbing."],
    ["4.1", "VM snapshots are great for…", ["Undo a change; they are not a 3-2-1 backup", "Replacing tape forever", "ECC", "PoE"], 0, "Delta disks grow. Do not chain them forever."],
    ["4.2", "Availability in cloud SLAs is about…", ["Uptime targets — still design for failure", "Guaranteed zero cost", "No patches", "No identity"], 0, "Multi-AZ is a design, not a checkbox you forgot."],
    ["4.1", "Security requirement for a VM lab often includes…", ["Isolated vSwitch / no bridged malware onto the LAN", "APIPA as a firewall", "Port 80 as management", "VGA loopback"], 0, "Bridged NICs are how lab ransomware visits the office."],
    ["4.2", "Community cloud is…", ["Shared by orgs with a common need (gov, industry)", "Always public hyperscale only", "A Type 1 brand", "RAID 10"], 0, "Rare on A+, still in the model list."],
    ["4.1", "Test/dev VMs exist so that…", ["You do not experiment on production", "Production has no backups", "DHCP cannot run", "Cables are optional"], 0, "Clone, break, throw away."],
    ["4.2", "SaaS identity (the user only sees the app) still needs…", ["Your accounts, MFA, and an exit plan for data", "A Type 1 hypervisor on every desk", "SODIMM upgrades in the cloud", "RJ11"], 0, "You do not patch the vendor’s OS. You still own the people and the data."],
    ["4.1", "vMotion / live migrate (conceptually) needs…", ["Shared storage and compatible CPUs — not a prayer", "APIPA", "Telnet", "VGA"], 0, "A+ wants the idea: moving a running VM is a platform feature, not drag-and-drop of a VHD on a USB stick during uptime."],
    ["4.2", "On-demand self-service is a cloud trait meaning…", ["Users provision without a weeks-long hardware ticket", "No billing", "No network", "No MFA"], 0, "The portal is the point. Guardrails still matter."],
    ["4.1", "A VM’s virtual NIC can be…", ["Bridged, NAT, or host-only — pick isolation on purpose", "Only fibre", "Only PoE", "Only USB-C"], 0, "NAT hides the guest. Bridged puts it on the LAN."],
    ["4.2", "Rapid elasticity gone wrong looks like…", ["A bill shock from unbounded scale-out", "Slower fibre", "A bent pin on RJ45", "A swollen CMOS"], 0, "Caps and budgets are operational procedures meeting cloud."],
    ["4.1", "Hypervisor escape is the nightmare where…", ["Malware in a guest attacks the host", "The VM gets more RAM for free", "Cloud becomes free", "RAID heals itself"], 0, "Patch the hypervisor. Limit who is admin on the host."],
    ["4.2", "IaaS still leaves you responsible for…", ["The guest OS, apps, and much of the identity", "The physical PDUs in the region", "The undersea cables", "The vendor’s hypervisor source"], 0, "Shared responsibility. Read the model."],
    ["4.1", "32-bit guests on a 64-bit host are…", ["Usually fine; the reverse is not", "Impossible", "A RAID requirement", "A CAT8 need"], 0, "The guest can be smaller. A 32-bit host will not run a 64-bit guest."],
  ],
  "hw-net-troubleshooting": [
    ["5.1", "No fans, no lights after a surge. First cheap checks?", ["Outlet, cord, PSU switch, known-good power — before a new motherboard", "Reimage Windows", "Replace RAM first always", "Disable Secure Boot"], 0, "Dead box: power path first."],
    ["5.1", "POST beeps with no display often point to…", ["RAM seating, GPU, or board — not Explorer.exe", "A bad MX record", "IMAP", "Cat 6 colour"], 0, "Beep codes / Q-LEDs are the firmware talking."],
    ["5.1", "A swollen capacitor on a board is a…", ["Hardware failure — not a Windows theme", "DNS issue", "VLAN mismatch", "APIPA"], 0, "Look with your eyes. Recap or replace the board."],
    ["5.1", "Inaccurate date/time that resets at power-off often means…", ["CMOS battery (CR2032) is tired", "RAID 0", "Port 53", "Toner empty"], 0, "UEFI settings dying is the same ticket."],
    ["5.1", "Random shutdowns plus a burning smell: you…", ["Power off and inspect — do not keep booting into the smell", "Run sfc first", "Disable the firewall", "Change the SSID"], 0, "Safety. Then PSU/board/GPU."],
    ["5.2", "Clicking hard drive + SMART failing: next move?", ["Backup what you can, replace the disk — not chkdsk forever", "Increase pagefile and ignore", "RAID 0 to hide it", "Disable S.M.A.R.T."], 0, "Click of death. Copy off, replace."],
    ["5.2", "RAID array missing after a power blip: first theory?", ["Controller/BIOS did not see members — reseat, check status, do not initialise blindly", "Reinstall Chrome", "Change DNS to 8.8.8.8 only", "Disable TPM"], 0, "Initialise wipes. Import/foreign arrays exist for a reason."],
    ["5.2", "Boot device not found after a clone: often…", ["Boot order / UEFI vs legacy / missing EFI partition", "A bad RJ11", "PoE budget", "NFC"], 0, "The OS can be on disk while firmware looks at the old USB."],
    ["5.3", "Projector with a lamp-hour warning and dim image: likely…", ["End-of-life bulb (or laser module on newer units)", "APIPA", "RAID 5", "IMAP"], 0, "Also check input source and lens cap — yes, still."],
    ["5.3", "Wrong input source on a display looks like…", ["No signal until HDMI/DP/input is correct", "A DHCP outage only", "BitLocker", "ext4"], 0, "The panel is fine. The source is not selected."],
    ["5.3", "Burn-in on OLED vs stuck pixels on LCD: burn-in is…", ["Aged emissive pattern; stuck pixels are transistor/cell faults", "Always a cable", "Always GPU RAM", "Always the PSU 5 V"], 0, "Different physics, different hope."],
    ["5.4", "Phone that charges only at an angle: first hardware theory?", ["Debris or damaged port (or a failing cable)", "APN typo only", "RAID", "SMTP"], 0, "Wiggle is mechanical."],
    ["5.4", "Cursor drift on a laptop after a spill: think…", ["Digitizer/trackpad calibration or hardware damage", "MX records", "VLAN 1", "PoE"], 0, "Also disable the pad while typing if it is software ghosting."],
    ["5.4", "Liquid damage tickets: you…", ["Power off, do not charge, document, do not rice-as-a-plan", "Max the charger watts", "Enable RAID 0", "Factory reset while wet"], 0, "Corrosion continues. Honesty with the user."],
    ["5.5", "Intermittent Wi-Fi in one room: classic RF issues include…", ["Interference, channel overlap, dead AP, or a bad antenna", "A missing SODIMM", "Fuser temp", "CR2032"], 0, "Analyzer + move + known-good client."],
    ["5.5", "High latency and jitter hurt…", ["VoIP/video more than a file copy", "Only RAID rebuilds", "Only laser printers", "Only TPM"], 0, "Real-time traffic hates delay variation."],
    ["5.5", "Limited connectivity on Windows often means…", ["DHCP/DNS/gateway trouble — not “reinstall Office” first", "A failed digitizer", "Empty toner", "A bent HDMI pin only"], 0, "ipconfig /all is the flashlight."],
    ["5.5", "Port flapping is…", ["Link up/down rapidly — bad cable, duplex, or a loop", "A DNS record type", "A RAID level", "A PSU rail"], 0, "Check logs on the switch. Replace the patch."],
    ["5.6", "Garbled print on a laser after a driver change: try…", ["Correct PCL/PS driver and a test page from the panel", "A new CPU", "APIPA", "Port 22 on the printer"], 0, "Panel test page isolates PC vs engine."],
    ["5.6", "Paper jam plus accordion in the fuser: you…", ["Clear the whole path, check rollers, do not yank against the fuser blindly", "Increase RAID stripe", "Disable IPv6", "Flash UEFI"], 0, "Respect the hot fuser. Accordion is a mechanical grab."],
    ["5.6", "Jobs stuck in the queue on Windows: classic fix path?", ["Restart spooler, clear stuck jobs, check IP/port", "Replace SODIMM", "Change T568B", "Disable Secure Boot"], 0, "Services.msc → Spooler. Stale WSD ports are a pest."],
    ["5.1", "A paperclip PSU test only proves…", ["The fan can idle — not that rails are in spec under load", "The GPU is fine", "UEFI is signed", "PoE is 60 W"], 0, "Use a tester or a known-good unit."],
    ["5.2", "RAID 0 with one dead disk means…", ["The volume is gone — restore from backup", "Parity will rebuild", "A hot spare heals it", "chkdsk rebuilds stripes"], 0, "RAID 0 is speed without a net."],
    ["5.3", "Intermittent projector shutdown is often…", ["Overheat / blocked filter / dying lamp", "MX failure", "eSIM", "ext4"], 0, "Clean the filter. Give it air."],
    ["5.4", "Unable to install apps on a phone after an MDM wipe: check…", ["Supervision / store account / storage / OS version", "The laptop PSU", "T568A", "RAID 10"], 0, "Policy can block sideload and the store."],
    ["5.5", "Authentication failures on Wi-Fi after a password rotation: users need…", ["Forget network and rejoin; old PSK is cached", "A new SSD", "A CMOS clear", "Inkjet calibration"], 0, "The SSID looks the same. The key is not."],
    ["5.6", "Speckling / ghosting on laser pages can be…", ["Drum/fuser/toner leak — not a Word setting", "DNS TTL", "VLAN 99", "APIPA"], 0, "Print a vendor diagnostic page."],
    ["5.1", "Sluggish PC that was fast: hardware suspects include…", ["Thermal throttle, dying disk, RAM fault — not only “too many tabs”", "A missing CNAME", "RJ11", "NFC"], 0, "Task Manager + temps + SMART."],
    ["5.2", "Extended read times on a spinning disk without SMART fail yet: still…", ["Back up; it may be dying quietly", "Stripe it in RAID 0 to hide", "Disable SATA", "Ignore"], 0, "SMART is late. Behaviour is early."],
    ["5.3", "No audio from HDMI TV but picture is fine: check…", ["Windows output device / TV input / ARC", "RAID 5", "CR2032", "Punchdown"], 0, "HDMI is picture and audio. The OS may still be sending to the laptop speakers."],
    ["5.4", "Stylus works on the glass but buttons do not: often…", ["Bluetooth pairing for the extra buttons, or a dead cell in the pen", "Gateway mismatch", "PoE", "MX"], 0, "Digitizer vs BLE accessory are different channels."],
    ["5.5", "External interference on 2.4 GHz: usual suspects?", ["Microwaves, Bluetooth, baby monitors, overlapping APs", "OLED burn-in", "ECC RAM", "Fuser"], 0, "Change band/channel or move the AP."],
    ["5.1", "Blank screen, fans spin, you hear POST: next cheap test?", ["Known-good display/cable/input — then RAM/GPU", "Reinstall Office", "Change the VLAN", "Replace the RJ11"], 0, "Confirm it is not the panel before you buy a board."],
    ["5.6", "Incorrect orientation every job: check…", ["Driver tray/orientation vs what the app thinks", "SODIMM A2", "Secure Boot", "eSIM"], 0, "Portrait in Word, landscape in the tray = fights."],
    ["5.2", "Missing drive in the OS but BIOS sees it: think…", ["Driver, letter, SAN policy, or a storage spaces/RAID metadata issue", "The PSU 3.3 V only", "NFC", "T568A"], 0, "Firmware sees silicon. Windows needs a stack."],
    ["5.5", "Slow wired speeds with a gigabit NIC: classic Layer 1?", ["Bad cable/patch, dirty NIC, or a 100 Mb switch port", "BitLocker", "IMAP", "OLED"], 0, "Check link lights and negotiated speed."],
  ],
  "operating-systems": [
    ["1.1", "NTFS vs exFAT vs FAT32: FAT32’s famous limit is…", ["File size (~4 GB) and weaker permissions", "No USB support", "No Windows 11", "Only ARM"], 0, "exFAT is the big-file USB stick. NTFS is the Windows volume with ACLs."],
    ["1.1", "APFS is the default modern filesystem on…", ["macOS", "Windows Home", "Android recovery only", "ext4 servers only"], 0, "Apple File System. ReFS is Microsoft’s resiliency cousin."],
    ["1.1", "ext4 is at home on…", ["Linux", "Windows PE only", "iPadOS", "BIOS option ROMs"], 0, "Linux default. Windows will not boot from it natively."],
    ["1.2", "A clean install vs in-place upgrade: clean means…", ["Wipe and lay a new OS; upgrade keeps apps/files when it works", "Always faster CPU", "Always TPM off", "No drivers"], 0, "Backup first either way."],
    ["1.2", "GPT vs MBR: modern UEFI Windows wants…", ["GPT", "MBR only", "FAT12", "RAID 0 metadata"], 0, "MBR is the old 2 TB-ish world. GPT with UEFI is current."],
    ["1.2", "Windows 11 hardware gates that show up on tickets include…", ["TPM 2.0 and UEFI", "Itanium only", "Token Ring", "VGA BIOS only"], 0, "Unsupported hardware is a policy fight, not a secret skip for corporate images without a decision."],
    ["1.3", "Windows Pro vs Home: Pro adds things like…", ["BitLocker, RDP host, domain join, gpedit", "A faster iGPU always", "ext4 boot", "APFS"], 0, "SKU features, not clock speed."],
    ["1.3", "gpedit.msc is…", ["Local Group Policy Editor — not on Home the same way", "Disk defrag", "Event Viewer", "A Linux package manager"], 0, "Pro/Enterprise land."],
    ["1.4", "eventvwr.msc is…", ["Event Viewer", "Disk Management", "Device Manager", "Certificate store"], 0, "Logs. diskmgmt.msc is disks. devmgmt.msc is devices."],
    ["1.4", "Task Manager’s Startup tab is for…", ["What launches at logon", "RAID status", "DHCP scopes", "Fibre levels"], 0, "Disable the junk. Services is a different tab."],
    ["1.5", "ipconfig /all shows…", ["Addresses, DHCP, DNS, MAC — the first flashlight", "Only the hostname", "Only routes", "Only firewall rules"], 0, "Windows. Linux uses ip/ifconfig."],
    ["1.5", "sfc /scannow is for…", ["Repairing protected Windows system files", "Formatting a USB", "Joining a domain", "Flashing UEFI"], 0, "DISM is the cousin when the component store is sick."],
    ["1.5", "chkdsk is for…", ["Filesystem errors on a volume", "DNS cache", "Group Policy", "MX records"], 0, "It is not a RAID rebuild."],
    ["1.5", "gpupdate /force …", ["Reapplies Group Policy now", "Formats C:", "Clears TPM", "Flashes BIOS"], 0, "gpresult shows what applied."],
    ["1.6", "File Explorer Options → hidden files is where you…", ["Show the files Windows tucks away", "Set the default gateway", "Enroll BitLocker", "Join Azure"], 0, "Also unhide extensions so ransomware is less cute."],
    ["1.6", "Power Options “lid close” on a laptop can…", ["Sleep, hibernate, or do nothing — and confuse a dock ticket", "Change T568B", "Set RAID 5", "Flash an ONT"], 0, "A “dead” laptop in a bag is often sleeping with the lid policy."],
    ["1.7", "Domain vs workgroup: domain is…", ["Central identity (AD); workgroup is a peer name in a box", "Faster RAM", "A filesystem", "A PSU mode"], 0, "Mapped drives and GP live on the domain side."],
    ["1.7", "A metered connection on Windows tells the OS to…", ["Go easy on updates and sync because the WAN is precious", "Disable IPv4", "Force APIPA", "Break RDP"], 0, "Cellular / capped Wi-Fi."],
    ["1.8", "A macOS .dmg is typically…", ["A disk image for install", "A Windows MSI", "An APK", "A GPT protective MBR"], 0, ".pkg is the installer package. .app is the bundle in /Applications."],
    ["1.8", "Time Machine is…", ["Apple’s backup", "A Linux scheduler", "Windows Sandbox", "BitLocker"], 0, "FileVault is the volume encryption cousin."],
    ["1.9", "Linux apt is a…", ["Package manager (Debian/Ubuntu)", "Windows MMC snap-in", "macOS gesture", "RAID BIOS"], 0, "dnf is Fedora’s. chmod changes mode bits."],
    ["1.9", "sudo vs su: sudo is…", ["One command as root (usually); su is a full switch", "A filesystem", "A Wi-Fi band", "An MX record"], 0, "Least privilege. You still need to be allowed."],
    ["1.10", "A 32-bit app on 64-bit Windows…", ["Often runs in WoW64 if the vendor shipped it; 64-bit OS will not run on 32-bit CPU", "Always fails", "Needs ARM", "Needs RAID 10"], 0, "Check the installer architecture and RAM."],
    ["1.5", "nslookup is for…", ["Querying DNS", "Formatting GPT", "Editing the registry", "PoE watts"], 0, "If ping works and names fail, it is DNS."],
    ["1.4", "diskmgmt.msc cannot always…", ["Fix a missing UEFI boot entry by itself", "Show volumes", "Assign letters", "Bring an offline disk online"], 0, "bcdboot / firmware boot order still exist."],
    ["1.1", "Chrome OS is…", ["A cloud-first OS on Chromebooks, not a Windows SKU", "Linux Server Core", "iPadOS", "ESXi"], 0, "Different management. Different store."],
    ["1.2", "WinRE is…", ["Windows Recovery Environment — reset, startup repair, command prompt", "A Linux runlevel", "Apple Recovery only", "A hypervisor"], 0, "Shift+Restart or install media."],
    ["1.6", "Indexing Options affect…", ["How fast Start/search finds files — and disk busy-ness", "DHCP", "RAID stripe", "TPM PCR"], 0, "Exclude giant folders if the disk is melting."],
    ["1.8", "Keychain on macOS stores…", ["Passwords and certs", "RAID metadata", "PoE budgets", "T568A maps"], 0, "iCloud Keychain is the sync story."],
    ["1.9", "chmod 755 on a script is…", ["Owner rwx, group/others rx — not a Windows ACL", "NTFS compression", "BitLocker", "GPT"], 0, "Permissions are octal on Unix."],
    ["1.7", "Mapped drive vs UNC path: a mapped drive is…", ["A letter pointing at \\\\server\\share", "A VLAN", "A SODIMM slot", "A fuser"], 0, "Offline files and letters confuse users. The UNC still matters."],
    ["1.3", "BitLocker is typically a…", ["Pro/Enterprise volume encryption feature using TPM", "Home-only theme", "ext4 flag", "APFS snapshot"], 0, "Home has Device Encryption on some modern PCs — still know the SKU story."],
    ["1.10", "An app that needs a hardware token will fail if…", ["The USB key is missing or the middleware is not installed", "The wallpaper is wrong", "IPv6 is on", "The SSID is 5 GHz"], 0, "Smart cards and FIDO keys are still “install according to requirements.”"],
    ["1.5", "robocopy is for…", ["Robust file copy with retries — better than a dragging Explorer on a WAN", "Editing the registry", "Joining macOS to AD only", "Flashing BIOS"], 0, "Know it exists. Know /MIR is a foot-gun."],
    ["1.4", "msconfig is…", ["System Configuration — boot and startup services (legacy-ish)", "Disk Management", "Event Viewer", "Certmgr"], 0, "Task Manager Startup took a lot of this job. Still on the exam list."],
    ["1.9", "Linux /etc/resolv.conf is about…", ["DNS resolvers", "User passwords", "fstab mounts", "cron"], 0, "systemd-resolved may manage it now. The idea is DNS."],
    ["1.2", "Zero-touch deployment is…", ["Autopilot-style: the device enrolls with little desk touching", "A paperclip PSU test", "RAID 0", "VGA loopback"], 0, "Cloud identity + enrollment profile."],
  ],
  security: [
    ["2.1", "A privacy screen on a kiosk is a…", ["Physical control against shoulder surfing", "Firewall rule", "VLAN", "RAID 1"], 0, "Physical: locks, badges, screens, cable locks."],
    ["2.1", "A Kensington lock is for…", ["Anchoring a laptop to furniture", "Encrypting NTFS", "WPA3", "DNSSEC"], 0, "Theft is physical. BitLocker does not stop a snatched chassis by itself if it is powered on and logged in."],
    ["2.2", "Least privilege means…", ["Accounts get only the rights they need", "Everyone is Domain Admin", "Guest is admin", "Passwords are shared"], 0, "Admin when needed, user when not."],
    ["2.2", "MFA is…", ["Something you have/are plus something you know", "Two passwords typed twice", "A longer PIN only", "A screensaver"], 0, "SMS is weak MFA. App/token/FIDO is better."],
    ["2.3", "WPA3 compared with WEP…", ["WPA3 is modern; WEP is broken museum radio", "WEP is stronger", "They are identical", "WEP is IPv6 only"], 0, "WPA2-AES is the common floor. WPA3 is the newer one. TKIP/WEP are the don’ts."],
    ["2.3", "A RADIUS/802.1X Wi-Fi enterprise setup authenticates…", ["Users/machines against a directory, not a shared PSK", "Only MAC addresses forever", "Only WEP", "Only WPS PINs"], 0, "PSK is SOHO. Enterprise is 802.1X."],
    ["2.4", "Ransomware first response is typically…", ["Isolate the host from the network, then recover from known-good backups", "Pay from the helpdesk card", "Run a random registry cleaner", "Disable the UPS"], 0, "Contain. Do not power-cycle evidence without a plan. Backups that were not tested are a rumour."],
    ["2.4", "A cryptominer on a PC often shows up as…", ["High GPU/CPU, heat, and a process you did not install", "A missing RJ45 spring", "APIPA", "A fuser error"], 0, "Task Manager and a reputable scanner. Then how it got in."],
    ["2.5", "Phishing is…", ["A fake message that wants credentials or a payload", "A VLAN hop", "A RAID rebuild", "A bent pin"], 0, "Urgency + borrowed logo. You never auth through the surprise link."],
    ["2.5", "Tailgating is…", ["Following someone through a badge door", "A Wi-Fi attack", "A BIOS password", "An MX spoof"], 0, "Physical social engineering."],
    ["2.5", "Whaling is phishing aimed at…", ["Executives / high-value targets", "Printers", "APs only", "BIOS vendors"], 0, "Same family as spear phishing, bigger fish."],
    ["2.6", "A SOHO default SSID + default admin password is a…", ["Gift to the street", "WPA3 requirement", "802.1X", "TPM PCR"], 0, "Change both. Guest network for friends. WPS off."],
    ["2.6", "Disabling WPS on a home AP is wise because…", ["WPS PINs were a brute-force story", "It speeds fibre", "It enables RAID", "It is required for IPv6"], 0, "Button pairing is convenience; the PIN mode was the hole."],
    ["2.7", "Browser pop-up “your PC is infected, call this number” is…", ["Scareware — close it, do not call, scan with tools you trust", "A Microsoft official channel", "BitLocker recovery", "A TPM fault"], 0, "Full-screen fake support. Alt-F4 / Task Manager, then education."],
    ["2.7", "Clearing browser cache is not the same as…", ["Removing saved passwords or extension malware", "Closing a tab", "Flushing DNS always", "A reboot"], 0, "Password manager + extension audit."],
    ["2.2", "EFS vs BitLocker: BitLocker encrypts…", ["The volume; EFS is per-file on NTFS", "Only the browser", "Only Wi-Fi", "Only mail"], 0, "Different scopes. Recovery keys are the ticket."],
    ["2.1", "A server-room mantrap is…", ["Two doors so tailgating is hard", "A firewall", "A VLAN", "WPA3"], 0, "Physical access control."],
    ["2.4", "A Trojan pretends to be…", ["Useful software while it is not", "A cable", "A RAID level", "A filesystem"], 0, "You invited it. Worms spread. Viruses infect files. The taxonomy is still taught."],
    ["2.5", "Dumpster diving is…", ["Trash as an intel source — shred the tickets", "A Wi-Fi band", "A Linux command", "A PSU test"], 0, "PII in the bin is still PII."],
    ["2.3", "A captive portal on guest Wi-Fi is…", ["A web login before the WAN — not WPA3 by itself", "Radius always", "WEP", "IPsec always"], 0, "Open radio + HTTPS page. Still isolate guests."],
    ["2.6", "Changing the default router IP helps a little because…", ["Some malware still aims at 192.168.0.1 / 1.1", "It creates WPA3", "It is 802.1X", "It replaces MFA"], 0, "Small. Still change the password."],
    ["2.7", "HTTPS on a site with a browser warning means…", ["The cert chain is unhappy — do not “click through” for a bank", "The fibre is unplugged", "RAID is degraded", "APIPA"], 0, "Date/time, captive portal, or an actual intercept."],
    ["2.2", "A shared local admin password across 200 PCs is…", ["A lateral-movement gift; use LAPS or equivalent", "MFA", "Least privilege", "802.1X"], 0, "One dump, every box."],
    ["2.4", "Quarantine in an AV console means…", ["The file is isolated, not yet deleted forever", "The PC is in a VLAN named Q", "BitLocker is on", "The user is fired"], 0, "You can restore a false positive. Do not restore ransomware."],
    ["2.1", "Badge cloning is a reason to…", ["Prefer modern card tech and check tailgating, not just “we have badges”", "Disable all doors", "Use WEP", "Share PINs on Slack"], 0, "Physical + policy."],
    ["2.5", "Vishing is…", ["Voice phishing — the phone call version", "A VLAN hop", "A virus that only hits printers", "A RAID attack"], 0, "Helpdesk impersonators love vishing."],
    ["2.3", "MAC filtering on Wi-Fi is…", ["A weak extra; MACs spoof; not a password replacement", "WPA3-SAE", "802.1X RADIUS", "IPsec"], 0, "Do not sell it as enterprise auth."],
    ["2.6", "UPnP on a home router is a…", ["Convenience that can punch holes; disable if you do not need it", "WPA3 replacement", "AD join", "BitLocker"], 0, "Games vs security. Know the trade."],
    ["2.7", "An unexpected browser extension with “full data” rights is…", ["Treat as hostile until proven — remove, scan, change passwords", "Always from Google HR", "A TPM feature", "RAID 1"], 0, "Supply-chain and fake store listings exist."],
    ["2.2", "Disable AutoRun on USB because…", ["Malware loved to launch from sticks", "NTFS cannot exist", "Wi-Fi breaks", "GPT fails"], 0, "Still a thing on older habits."],
    ["2.4", "A rootkit is nasty because…", ["It hides at a low level from ordinary tools", "It is only a pop-up", "It is always a phishing PDF", "It is APIPA"], 0, "Offline scan / rebuild may be the honest fix."],
    ["2.5", "Shoulder surfing is defeated partly by…", ["Privacy filters, screen lock, and not typing secrets on the train", "WPA3 only", "RAID 10", "IPv6"], 0, "Physical observation."],
    ["2.1", "Video surveillance without retention policy still needs…", ["A legal/privacy plan — cameras are not a personality", "WEP", "APIPA", "exFAT"], 0, "Ops + law. A+ still lists cameras as a physical control."],
    ["2.6", "Firmware updates on the SOHO AP matter because…", ["Old firmware is a known-exploit museum", "They change T568A", "They add SODIMM slots", "They enable MBR"], 0, "Patch the door you hung on the internet."],
    ["2.3", "A hidden SSID is…", ["Not secret; clients shout it; still use a real cipher", "Equivalent to WPA3-Enterprise", "A firewall", "BitLocker"], 0, "Obscurity is not a control."],
    ["2.7", "Download hashing (vendor SHA256) is for…", ["Checking the ISO was not swapped", "Faster fibre", "RAID speed", "PoE"], 0, "Trust but verify the bits."],
  ],
  "software-troubleshooting": [
    ["3.1", "A BSOD that names a driver is a hint to…", ["Update/roll back that driver or check the hardware it owns", "Change the SSID", "Replace RJ11", "Disable IPv6 always"], 0, "Reliability Monitor + dump + vendor notes."],
    ["3.1", "Windows will not boot, WinRE startup repair fails: next honest tools?", ["Safe mode, restore point, DISM/SFC from WinRE, known-good media", "A new fuser", "Punchdown", "ONT swap"], 0, "Do not reimage as the first keystroke if the disk is fine."],
    ["3.1", "A profile that loops at logon often means…", ["Corrupt user profile — temp profile, then copy or rebuild", "RAID 0", "WPA3", "T568B"], 0, "C:\\Users and the profile list in the registry are the adult path."],
    ["3.1", "“Slow after login” with a healthy disk: look at…", ["Startup apps, GP, Explorer extensions, AV, and network home drives", "CR2032 first", "The inkjet damper", "eSIM"], 0, "Task Manager Startup + Autoruns if you must."],
    ["3.2", "Unexpected browser homepage + toolbars: think…", ["PUA/adware — reset browser, scan, check installed programs", "A bent HDMI pin", "APIPA as malware", "RAID 5"], 0, "It is software. Treat the extensions as guilty."],
    ["3.2", "A user cannot open files they could yesterday, ACLs look odd: consider…", ["Permissions, EFS keys, or ransomware", "T568A", "Fuser temp", "PoE class"], 0, "Security ticket vs crypto ticket. Ask for the pop-up."],
    ["3.2", "Disabled System Restore on a malware box is often…", ["The malware covering tracks — do not trust old restore points blindly", "A Windows Home feature that never existed", "GPT", "APFS"], 0, "Rebuild may be cleaner than playing in the infected hive."],
    ["3.3", "An Android app crashes only on cellular: check…", ["App permissions, data saver, and a reinstall — then OS update", "Laptop SODIMM", "Print spooler", "CR2032"], 0, "Clear cache before a full wipe."],
    ["3.3", "iPhone apps missing after an Apple ID change: often…", ["Purchases are tied to the ID — not a “failed digitizer”", "RAID", "VLAN 1", "MX"], 0, "Offboard the old ID properly."],
    ["3.3", "A phone that overheats while idle with a new app: first software move?", ["Force stop / uninstall the new app and check battery usage", "Replace the motherboard immediately", "Disable DHCP on the AP", "Flash a PC BIOS"], 0, "Battery usage screen is the map. Hardware still exists — software first if it started with an install."],
    ["3.4", "A rooted/jailbroken phone showing up at work is a…", ["Policy and security issue — MDM may refuse it", "Faster CPU gift", "Required for Exchange", "A TPM upgrade"], 0, "Integrity is the point of the controls."],
    ["3.4", "Fake security app on mobile that wants Device Admin: treat as…", ["Malware — revoke admin, uninstall, scan, consider wipe", "A bank’s only MFA", "WPA3", "BitLocker"], 0, "Device admin rights are powerful. Users get tricked."],
    ["3.1", "Missing DLL after an uninstall: classic cause?", ["Shared library removed; repair the remaining app or reinstall", "A bad RJ45", "OLED burn-in", "PoE"], 0, "Do not copy random DLLs from the web."],
    ["3.1", "Windows Update stuck at 0% on a metered or dirty WSUS: check…", ["Network, disk space, servicing stack, and the update source", "The fuser", "T568B", "NFC"], 0, "DISM /resetbase is not the first click."],
    ["3.2", "A certificate warning on an internal site after a date jump: first check?", ["System time (CMOS or time sync) before you distrust the CA", "Replace the GPU", "RAID 10", "Inkjet"], 0, "Certs are clocks plus chains."],
    ["3.3", "Email not syncing on a phone after a password change: users must…", ["Update the account in the mail app / MDM profile", "Replace the screen", "Change CAT6", "Flash UEFI"], 0, "The OS still has the old secret."],
    ["3.3", "No sound on a phone after an OS update: try…", ["Do Not Disturb, Bluetooth endpoint, and volume sources before a new speaker", "A new PSU", "gpupdate", "chkdsk"], 0, "Software gates a lot of “dead speakers.”"],
    ["3.4", "Sideloaded APK from a forum is a…", ["Trust problem — Play Protect and MDM may block it for a reason", "Faster than the store always", "Required for Wi-Fi", "A filesystem"], 0, "Unknown sources is a door."],
    ["3.1", "Application “not responding” but others are fine: next?", ["End task, check Event Viewer, repair/reinstall that app", "Reimage immediately", "Replace all RAM", "Disable the NIC"], 0, "Scope the blast radius."],
    ["3.2", "A user is locked out after too many passwords: that is often…", ["Account lockout policy — wait or unlock in AD, do not reset AD blindly without ID", "RAID", "APIPA", "Fuser"], 0, "Helpdesk identity checks exist for a reason."],
    ["3.1", "Boot to a black screen with a cursor: try…", ["Win+Ctrl+Shift+B, known-good display, Safe Mode, Explorer restart", "A new ONT first", "Punchdown", "WEP"], 0, "Graphics driver vs Explorer vs actual panel."],
    ["3.3", "iOS “Unable to install update” with a full phone: free…", ["Storage — updates want headroom", "The SIM slot", "The laptop dock", "DNS only"], 0, "Offload photos. Then retry."],
    ["3.4", "SMS one-time codes arriving late: consider…", ["Carrier, Do Not Disturb, and dual-SIM mix-ups — and push users to an authenticator app", "RAID 5", "T568A", "OLED"], 0, "SS7 and delay are why app MFA is nicer."],
    ["3.2", "Defender real-time protection off and the user did not do it: treat as…", ["Compromise until proven otherwise", "A Windows Home limitation always", "GPT vs MBR", "APFS"], 0, "Malware disables AV. Turn it back on from a clean path."],
    ["3.1", "Time zone jumps that break Kerberos tickets: fix…", ["Time sync (NTP) and the zone, then retry the app", "The toner", "PoE", "NFC"], 0, "AD is picky about clocks."],
    ["3.3", "Android work profile apps missing after a wipe: the device needs…", ["Re-enrollment in MDM", "A new CPU", "RAID 1", "A CMOS battery"], 0, "The catalog lives in the policy."],
    ["3.1", "Print jobs fail for one user, others work: likely…", ["That user’s driver/port vs a down printer", "A building-wide fibre cut", "The DHCP scope empty for everyone", "The firewall at the edge"], 0, "Scope. Then spooler vs driver vs mapping."],
    ["3.2", "Someone ran a “cleaner” that deleted hosts file entries: symptoms look like…", ["Name resolution weirdness — restore hosts and scan", "A dead PSU", "A bent display pin only", "A failed fuser"], 0, "C:\\Windows\\System32\\drivers\\etc\\hosts is still a pest magnet."],
    ["3.4", "A mobile device with unknown MDM that the user cannot remove: that is…", ["Supervision — the org owns the policy", "A bug you jailbreak to fix", "APIPA", "RAID"], 0, "Do not fight it for a BYOD that was actually corporate."],
    ["3.1", "Safe Mode works, normal boot fails: that pattern suggests…", ["Startup software or a driver loaded only in normal boot", "Dead RAM always", "No OS", "A missing CPU"], 0, "Clean boot next."],
    ["3.3", "Bluetooth audio skips only in a crowded 2.4 GHz room: that can be…", ["RF congestion — try 5 GHz Wi-Fi offload on the laptop, move, or wired", "A failed MX", "GPT", "BitLocker"], 0, "Phones and headsets share the soup with Wi-Fi."],
    ["3.2", "A fake Windows activation popup that is not the real Settings page: treat as…", ["Malware/scareware — not a product key from the banner", "A TPM fault", "Secure Boot", "RAID"], 0, "Win+I to the real Settings. Scan."],
    ["3.1", "Explorer crashes on a specific folder: suspect…", ["A bad shell extension or a corrupt thumbnail/cache in that tree", "The default gateway only", "PoE", "eSIM"], 0, "Rename the folder, preview pane off, then repair."],
    ["3.4", "A stolen phone: the software move is…", ["Locate/lock/wipe from the account + change passwords", "Email the IMEI to a printer", "Disable STP", "Format the SAN"], 0, "Then carrier and MDM."],
    ["3.1", "A service fails with “logon as” errors after a password change: update…", ["The service account credential in services.msc / gMSA", "T568B", "The fuser", "The ONT"], 0, "Scheduled tasks too."],
    ["3.3", "Mobile hotspot draining a phone overnight: check…", ["Hotspot left on, a client still attached, and battery saver", "Laptop RAID", "CR2032", "PCL vs PS"], 0, "Software toggle. Then hardware if it still cooks with hotspot off."],
  ],
  "operational-procedures": [
    ["4.1", "A ticket should capture…", ["Who, what, when, and what you changed — not a vibe", "Only the user’s mood", "Only the asset tag", "Only the SLA colour"], 0, "The next tech should not have to be a mind reader."],
    ["4.1", "Asset tags exist so that…", ["Hardware is tracked through life, not guessed by colour", "RAID is faster", "WPA3 works", "APIPA stops"], 0, "Inventory is an operational control."],
    ["4.2", "Change management’s point is…", ["Risk, rollback, and a window — not surprise Friday production edits", "Hiding outages", "Skipping backups", "Avoiding tickets"], 0, "CAB/standard changes still have a record."],
    ["4.2", "A rollback plan answers…", ["How we undo this if it fails", "Who to blame", "The SSID", "The toner SKU"], 0, "If you cannot roll back, say so before you click."],
    ["4.3", "3-2-1 backup means…", ["3 copies, 2 media, 1 offsite — RAID is not a backup", "3 RAIDs, 2 switches, 1 AP", "3 passwords", "1 copy in RAM"], 0, "Test restores or you have a ritual."],
    ["4.3", "A UPS is for…", ["Ride-through and clean shutdown — not infinite runtime", "Replacing the PSU forever", "PoE for cameras only", "A Type 1 hypervisor"], 0, "Batteries age. Test them."],
    ["4.3", "Electrical safety on a PSU: you do not…", ["Open a switching PSU for fun — stored charge bites", "Use a tester ever", "Wear a strap on boards", "Unplug before service"], 0, "Respect mains. Recycle, do not trash."],
    ["4.4", "PII on a ticket should be…", ["Need-to-know and handled per policy — not pasted into a public chat", "Posted to social for “awareness”", "Printed on the lobby board", "Mailed on a USB"], 0, "Privacy is an operational procedure."],
    ["4.4", "MSDS / SDS sheets are for…", ["Chemical hazards (toner, batteries, cleaners)", "SSID lists", "VLAN maps", "MX records"], 0, "Toner is not flour. Batteries are not toys."],
    ["4.5", "A good first sentence to an angry user is…", ["Acknowledge the impact, then ask one clear question", "Explain that they are wrong", "Quote the SLA in caps", "Hang up"], 0, "Professional, not theatrical."],
    ["4.5", "Avoid jargon when the user needs…", ["A next step they can do — “reboot” vs “bounce the kernel”", "A RAID lecture", "An OSI poster", "A hex dump"], 0, "Translate. Then document the real terms for the next tech."],
    ["4.6", "A basic script on A+ is for…", ["Repeatable small tasks — not a replacement for change control", "Flashing random firmware from a forum", "Disabling backups", "Sharing admin passwords"], 0, "Know that .ps1 / .sh exist. Do not run mystery scripts."],
    ["4.6", "RDP vs SSH vs VPN: pick based on…", ["What you need to reach and how it is encrypted", "Which logo is prettier", "Port 80 always", "Telnet for speed"], 0, "Telnet is a museum. VPN is the tunnel. RDP/SSH are the sessions."],
    ["4.1", "Knowledge base articles should be…", ["Searchable, current, and tied to the ticket symptoms", "Secret so only you can close tickets", "AI slop without a lab check", "A meme folder"], 0, "Reuse beats heroics."],
    ["4.2", "A standard change (password reset) vs a major change (core switch) differ in…", ["Risk and approval — both still get a record", "Whether you are polite", "Whether DNS exists", "Whether USB-C exists"], 0, "Do not treat a core cutover like a password reset."],
    ["4.3", "Chain of custody matters when…", ["A device is evidence — who had it, when, and why", "You are ordering toner", "You are labelling CAT6", "You are setting an SSID"], 0, "Do not “just take it home to image.”"],
    ["4.4", "Toner spill: you do not…", ["Vacuum with a household vac that aerosolises it — follow the SDS", "Sweep harder", "Wash it down the sink first", "Ignore it"], 0, "Special vacs / damp wipe per vendor."],
    ["4.5", "Setting expectations (“I will call by 3”) then calling is…", ["Professionalism; ghosting is not a tool", "Optional if you are skilled", "A Linux flag", "A RAID feature"], 0, "Time is part of the ticket."],
    ["4.6", "Remote tools (vendor support, Quick Assist, etc.) still need…", ["User consent, identity, and a record", "A shared Facebook password", "Telnet to 23 on the firewall", "WEP"], 0, "Do not leave unattended remote sessions."],
    ["4.1", "An SLA is…", ["The promised response/restore times — not a personality", "A filesystem", "A hypervisor", "A cable category"], 0, "Priority on the ticket should match the SLA, not the shout volume alone."],
    ["4.2", "Documenting a change window in the ticket helps because…", ["The next outage has a timeline", "It makes RAID faster", "It disables APIPA", "It sets T568A"], 0, "When did we touch it?"],
    ["4.3", "Lithium battery disposal is…", ["Hazardous — tape terminals, proper recycle, no trash crush", "Normal landfill always", "Incinerator fun", "Mailbox"], 0, "Swollen packs are a special handling story."],
    ["4.4", "A privacy incident (wrong attachment emailed) is…", ["Escalate per policy — do not hide it in the ticket notes only", "A RAID issue", "A CAT6 issue", "An OLED issue"], 0, "Legal/privacy get a vote."],
    ["4.5", "Do not joke about a user’s data loss. Instead…", ["Stay calm, start recovery, communicate facts", "Blame them in CC: all", "Post the files internally for laughs", "Leave"], 0, "Empathy is operational, not optional."],
    ["4.6", "A jump box / PAM exists so that…", ["Admin paths are controlled and logged", "Everyone RDP’s to prod from a cafe Wi-Fi", "Telnet is required", "Passwords are in a wiki"], 0, "Least privilege remotely too."],
    ["4.1", "Acceptable use policy is…", ["What staff may do on org kit — you still enforce it politely", "A Wi-Fi cipher", "A PSU rating", "A GPT flag"], 0, "AUP. Know it exists."],
    ["4.2", "Emergency change after a total outage still needs…", ["A record after the fact — do not skip the write-up", "No ticket ever", "A meme", "A new SSID"], 0, "Retrospective is the tax for skipping the CAB."],
    ["4.3", "Test restore to a sandbox proves…", ["The backup is not a brick", "The SLA colour", "The SSID", "The toner"], 0, "Backups without restores are fiction."],
    ["4.4", "Air quality / HVAC in a closet full of switches matters because…", ["Heat kills silicon and warranties", "It changes T568B", "It creates VLANs", "It is MFA"], 0, "Environment is in the domain."],
    ["4.5", "If you do not know, you say…", ["I’ll find out — then you do", "Whatever, reboot it", "That’s impossible", "Have you tried Bitcoin"], 0, "Honesty scales better than bluffing."],
    ["4.6", "PowerShell execution policy is a…", ["Speed bump, not a security boundary — still do not run mystery .ps1", "Replacement for BitLocker", "WPA3", "RAID 10"], 0, "Signed scripts and constrained language exist for a reason."],
    ["4.1", "Inventory drift (ghost assets) breaks…", ["Patching, licensing, and incident scope", "Cat 6 colour", "HDMI versions", "OLED gamut"], 0, "If it is not in the CMDB, it is still in the blast radius."],
    ["4.3", "An ESD strap is for…", ["Boards and RAM — not a live PSU interior", "Mains work", "Fibre welding", "Toner"], 0, "Ground yourself to the chassis. Still unplug."],
    ["4.2", "User communication during a change should include…", ["When it starts, what they will see, and when it should end", "A hex dump", "The RAID stripe size", "Your lunch order"], 0, "Surprise outages create extra tickets."],
    ["4.4", "Shredding disks vs a single pass: policy may require…", ["Degauss/destroy for some data classes — ask, do not guess", "A quick format always", "exFAT", "RAID 0"], 0, "Remanence is a real word."],
    ["4.5", "Escalating without dumping on the next team means…", ["You pass what you tried, logs, and impact", "You delete your notes", "You CC the CEO first always", "You reset all passwords"], 0, "A good handoff is a gift."],
  ],
};

function tagExisting(quiz: Quiz): Quiz {
  return {
    ...quiz,
    questions: quiz.questions.map((question) => ({
      ...question,
      objective: question.objective ?? EXISTING_OBJECTIVES[question.id],
    })),
  };
}

function fromFacts(domainId: AplusDomainId, prefix: string, facts: Fact[]): QuizQuestion[] {
  return facts.map((fact, index) => ({
    id: `${prefix}-x${index + 1}`,
    objective: fact[0],
    prompt: fact[1],
    choices: [...fact[2]],
    correctIndex: fact[3],
    explanation: fact[4],
  }));
}

const PREFIX: Record<AplusDomainId, string> = {
  "mobile-devices": "md",
  networking: "net",
  hardware: "hw",
  "virtualization-cloud": "vc",
  "hw-net-troubleshooting": "tn",
  "operating-systems": "os",
  security: "sec",
  "software-troubleshooting": "st",
  "operational-procedures": "op",
};

function mergeQuiz(base: Quiz): Quiz {
  const extra = fromFacts(base.domainId as AplusDomainId, PREFIX[base.domainId as AplusDomainId], BANKS[base.domainId as AplusDomainId] ?? []);
  const seen = new Set(base.questions.map((question) => question.prompt));
  const unique = extra.filter((question) => {
    if (seen.has(question.prompt)) return false;
    seen.add(question.prompt);
    return true;
  });
  return {
    ...tagExisting(base),
    questions: [...tagExisting(base).questions, ...unique],
  };
}

export const techExpandedQuizzes: Quiz[] = [...core1Quizzes, ...core2Quizzes].map(mergeQuiz);

export function techQuizByDomain(domainId: string) {
  return techExpandedQuizzes.find((quiz) => quiz.domainId === domainId);
}
