import { pack } from "../pack.mjs";

export const ART_VOLUME = pack("art", [
  ["vx-a-blind-contour", "Seeing extras", "Blind contour is a looking drill, not a pretty-line exam",
    "Keep the eye on the subject. The ugly line is a record of attention. Peeking turns it back into a drawing you already know how to fake.",
    "If the page looks messy the exercise failed. Neat is seeing.",
    "Tape the paper, look at the still life, draw two minutes without a peek. Then a timed peek pass of the same object.",
    "A class that only marks neat contours never trains the eye. Neat is a later hat."],
  ["vx-a-sight-size", "Seeing extras", "Sight-size is an arm’s-length contract, not a vibe of proportion",
    "Lock the elbow, compare a pencil unit to a unit on the model. A head-count of a figure is a stack of those units, not a feeling of tall.",
    "If it feels like a person the proportions are fine. Feelings are anatomy.",
    "Pick one unit (an eye, a head). Stack it. Check a second axis. Then stop stretching a leg as ‘style’ when it was a miss.",
    "A selfie-arm measure is a different geometry from a locked elbow. Lock it."],
  ["vx-a-foreshorten", "Seeing extras", "Foreshortening compresses length; it does not delete the limb",
    "A arm coming at you is ellipses of a cylinder, not a shorter cartoon arm. Draw the overlap and the ellipse, not the knowledge of how long an arm ‘should’ be.",
    "If it looks wrong, lengthen it until it matches the word arm. Knowledge beats the eye.",
    "Photograph a fist toward the lens. Copy the pancake, then the same fist from the side. Name what changed.",
    "A foot on a wide phone lens is extra pancake. That is optics as well as drawing."],
  ["vx-a-overlap-stack", "Seeing extras", "Overlap is cheaper depth than a vanishing point as a religion",
    "What sits in front cuts what sits behind. Size and aerial fade help. A still life with no overlaps is a sticker sheet.",
    "If there is no vanishing point there is no space. Points are space.",
    "Stack three objects so each cuts the next. Then a size change. Then a softer far edge.",
    "Kids’ sticker-space is a real composition. Adults do it when they fear a cut."],
  ["vx-a-three-point", "Seeing extras", "Three-point is a tilt of the camera, not a third random vanishing",
    "Worm’s-eye and bird’s-eye send verticals to a third point. Basic room interiors often keep verticals upright on purpose.",
    "More vanishing points always means more realism. Add five.",
    "Decide viewer height first. Then whether the camera tilts. Then place the third point far enough that the building does not melt.",
    "A phone pointed up a Sydney tower is three-point for free. Trace it."],
  ["vx-a-ellipse-cup", "Seeing extras", "An ellipse is a circle in perspective, not a pointed football",
    "The major axis stays until you rotate the cup. Near eye-level the ellipse thins; it does not grow corners. Cylinder ends share an axis.",
    "Cups are two-point footballs. Points are ellipses.",
    "Box a square, inscribe the circle, squash it. Check both rims of a tin on the table.",
    "A takeaway coffee lid is an ellipse lesson that costs $5. Use it."],
  ["vx-a-core-shadow", "Seeing extras", "A core shadow is the form turning away; a cast is someone else’s blockage",
    "Terminator, bounce, and a core that is often not the darkest dark. Casts can be harder-edged if the light is small. One grey for both is a mud pie.",
    "Shadow is one sad colour. Sad is a value.",
    "Name which shadow you are painting. Soften form edges; keep a cast readable as a shape. Add a bounce from the cloth.",
    "An apple’s form versus its cast on a tablecloth is two jobs. Two greys at least."],
  ["vx-a-reflected-light", "Seeing extras", "Reflected light is a bounce, not a second sun glued to the shadow",
    "The shadow side lifts where a nearby plane throws light back. It stays darker than the lit side if there is one key. Chrome is a special case of the whole room.",
    "Brighten the shadow until it matches the highlight. Bounce is a second key.",
    "Place a white card under a mug, then a black cloth. Paint both. The bounce is the difference.",
    "A portrait with glowing jaws and no environment to bounce from is a cartoon of the rule."],
  ["vx-a-aerial-fade", "Seeing extras", "Aerial perspective is air as a filter, not a blue filter on everything far",
    "Contrast, edge, and saturation drop with distance in humid air. Desert air is meaner and clearer. A far mountain can cool without becoming a sticker.",
    "Far means blue. Always. The Blue Mountains named the rule so you can skip looking.",
    "Squint a landscape photo. If the far hill still shouts, you have not faded contrast, only hue.",
    "Bushfire haze is aerial perspective with a health warning. Values flatten for real."],
  ["vx-a-cross-contour", "Seeing extras", "Cross-contours are wires on the form, not decoration on a balloon",
    "Lines travel around the volume so a sleeve becomes a cylinder. A contour outline with empty inside is a puddle with a border.",
    "Hatch any direction so it looks busy. Busy is form.",
    "Draw a sleeve with three wires around the arm, then a wrinkle that obeys those wires.",
    "A contour-only exam drawing can still fail form. Wires prove you saw a volume."],
  ["vx-a-plumb-vertical", "Seeing extras", "A plumb line is a honesty stick for tilts",
    "Hold a pencil vertical. Compare the model’s ear to the ankle. Beginners lean every standing figure like a dune.",
    "If the gesture is lively the verticals can dance. Gesture is a spirit-level.",
    "Drop a vertical from the inner ankle. See what stacks. Then a second from the pit of the neck.",
    "A sculpture photo with a 2-degree lean looks drunk in a folio. Check the door frame."],
  ["vx-a-envelope-block", "Seeing extras", "An envelope is the big box first, not a eyelash first",
    "Block the whole pose as a simple polygon. Details that stick out of the envelope are lies or a designed overlap. Hair is not a cloud pasted on a skull later.",
    "Start with the eyelashes so you do not waste the important bits. Detail is a foundation.",
    "Ten seconds: one polygon. Then volumes. Then features. Keep the polygon until the end as a ghost.",
    "A comic ‘same face’ problem often started as no envelope of the skull."],
  ["vx-a-counterchange", "Seeing extras", "Counterchange is light-on-dark flipping to dark-on-light along an edge",
    "A tree trunk that is dark against sky and light against a hedge. The eye loves the flip. A outline that ignores it is a sticker.",
    "Pick one: object dark or object light. Flipping is indecision.",
    "Squint a street photo. Trace where the edge flips. Paint that flip on a bottle against a window.",
    "A charcoal portrait that outlines hair on black fights the paper. Lose the fight on purpose."],
  ["vx-a-silhouette-read", "Seeing extras", "If the silhouette fails, interior detail will not save it",
    "A pose should read as a black shape at postage-stamp size. Tangents (kissing edges) muddy the stamp. Comics and animation live here.",
    "Detail inside the shape is what makes it professional. Silhouettes are for kids’ shadow puppets.",
    "Fill the figure black. If you cannot tell a kick from a stand, move a limb. Then put the detail back.",
    "A sports logo that dies at 16 pixels failed silhouette first. Icons taught painters this and they forgot."],
  ["vx-a-occlusion-dark", "Seeing extras", "An occlusion is the crack where light gives up",
    "Where a mug meets a table, a tiny dark. Not a outline around the whole mug. Ambient occlusion in 3D is this idea with a slider.",
    "Outline everything so it sits on the page. Outlines are physics.",
    "Put a dark only in contact cracks. Lift the rest of the underside with bounce.",
    "A product shot with a floating bottle forgot occlusion and a cast. Two misses."],
  ["vx-a-chiaroscuro-system", "Seeing extras", "Chiaroscuro is a lighting contract, not a synonym for ‘moody’",
    "A strong key, a controlled dark, a form that turns. Caravaggio is a system. A muddy brown painting with no key is just underlit.",
    "If it is dark it is chiaroscuro. Dim is a period.",
    "Light one object from a single desk lamp. Map highlight, mid, core, bounce, cast. Then a second lamp only if you mean it.",
    "A school ‘dramatic’ portrait with five overheads is a canteen, not a tenebrist chapel."],
  ["vx-a-local-vs-light", "Colour extras", "Local colour is the object’s name; light is what you actually mix",
    "A red apple is still a set of planes: some pink, some maroon, some grey-green from bounce. The word red is a filing cabinet, not a tube.",
    "Paint the name of the thing. Apples are red. Shadows are black. Done.",
    "Set a coloured object under a warm lamp and a cool window. Mix what you see, then write the local name in the margin as a lie you refused.",
    "A night scene that is only navy with no local leftovers is a filter. Keep a hint of the object’s name."],
  ["vx-a-simultaneous-contrast", "Colour extras", "A grey changes nationality when the neighbour shouts",
    "The same mid grey looks cool on orange and warm on blue. Chevreul’s classroom. A ‘wrong’ mix is often a neighbour problem.",
    "If the mix is right in isolation it is right on the painting. Palettes do not have neighbours.",
    "Paint one grey square on orange and on blue. Do not remix. Watch the grey join a team.",
    "A logo on a coloured field that ‘looks off’ on the poster was often simultaneous contrast, not a bad hex."],
  ["vx-a-glaze-vs-mix", "Colour extras", "A glaze is a film of light through pigment, not a watery mess of the same mix",
    "Transparent layers over a dry underpaint. Optical richness. A wet mush of the same two tubes is a mix, not a glaze. Fat-over-lean still applies in oil.",
    "Thin paint is always a glaze. Water is a technique.",
    "Dry a yellow field. Glaze a transparent red. Mix the same two on the palette. Compare the two oranges.",
    "A acrylic ‘glaze’ on a still-tacky layer is a lift, not a jewel. Wait."],
  ["vx-a-optical-mix", "Colour extras", "Optical mixing is dots that marry in the eye, not a palette marriage",
    "Seurat’s bet, a screen’s RGB, a comic’s Ben-Day. Stand back. Up close it is a quarrel. A muddy mix is a different tool.",
    "If I put two colours next to each other they automatically mix correctly at any distance. Physics is kind.",
    "Make a 10 cm field of two complement dots. Photograph from 4 metres. Then a mixed version. Name which job you wanted.",
    "A phone screen is optical mix as a factory. Painters who copy a screen blob-for-blob miss the factory."],
  ["vx-a-underpaint-temp", "Colour extras", "An underpainting is a value-and-temperature map, not a colouring-in base that must peek",
    "Grisaille, verdaccio, a burnt-sienna wipe. The top paint can hide it. The gift is the decisions already made in value.",
    "If you cannot see the underpainting at the end you wasted it. Underpaintings are a brand.",
    "Solve the picture in one earth. Dry. Then hue. Keep a scrap of the earth only where it helps.",
    "A green under a face is a old trick for cooling shadows. A green face at the exhibition is a underpainting that won the fight."],
  ["vx-a-skin-not-peach", "Colour extras", "Skin is blood, olive, and a room, not a peach tube with a name",
    "Capillaries, a cool shadow, a yellow forehead, a local ethnicity that is not a crayon label. Peach from a kid’s set is a cartoon of one lighting.",
    "Buy ‘skin colour’. There is one. The packet said so.",
    "Mix a range from the person in front of you. Include a cool. Include the jumper bounce. Throw the peach tube.",
    "A class set of ‘multicultural skins’ that are still one formula with more brown is a slightly wider cartoon."],
  ["vx-a-mixed-black", "Colour extras", "A mixed dark is a colour; a tube black is a hole unless you mean a hole",
    "Ultramarine plus burnt umber, or a complement pair, still has a temperature. Ivory black can deaden a shadow that needed air. Graphic shapes can want the hole.",
    "Black is not a colour so never use it. Also: black is the only shadow. Two sermons, both thin.",
    "Mix a dark without black. Then a dark with a touch of black. Put both in a shadow. Pick.",
    "A comic ink black is a designed hole. An oil portrait with the same hole can flatten a cheek."],
  ["vx-a-watercolour-reserve", "Colour extras", "In watercolour the white is the paper, not a later titanium rescue as a habit",
    "Plan the lights. Masking fluid is a tool with a scar. Opaque white exists and shouts that it exists. A bloom can be a feature if you stop fighting.",
    "Watercolour is the same as acrylic but wetter. White paint is fine everywhere. Paper is a backup.",
    "Do a study with zero white paint. Lift, reserve, or live with the mid. Then one designed opaque spark if you must.",
    "A bushfire sky in watercolour is a reserve problem. The glow is often the paper."],
  ["vx-a-night-not-navy", "Colour extras", "Night is a low key with leftover local colour, not a navy bucket",
    "Moon, sodium street, a phone screen, a residual red in a brick. If every plane is the same blue-black you painted a filter, not a street.",
    "Night means blue. Movies taught us. Skip the looking.",
    "Stand on a verandah at 8pm. List five hues that are not navy. Mix a small study from the list.",
    "A sodium-vapour car park is orange-green, ugly, and true. Pretty navy is a poster."],
  ["vx-a-gamut-mask", "Colour extras", "A gamut mask is a limited neighbourhood on the wheel, not a personality test",
    "Pick a slice of hues you will allow. Mix inside it. Harmony is easier when the wheel is not a buffet. Break the mask once as a spotlight.",
    "More hues is more skill. Use the whole wheel so the teacher sees effort.",
    "Draw a triangle on a wheel. Mix only inside it for a still life. Then one outside note on the focal.",
    "A brand palette is a gamut mask with lawyers. Painters can steal the idea without the lawyers."],
  ["vx-a-split-comp", "Colour extras", "Split complementary is a neighbour-pair versus a hue, not a random trio",
    "One hue plus the two beside its complement. Softer than a straight complement fight. Still a system, not ‘any three’.",
    "Three colours I like are a split complementary because I split them from my heart.",
    "Pick a yellow. Find the complement. Take the two beside that complement. Mix a world. Note what you cannot get.",
    "A school poster in cyan, orange-red, and orange-yellow is often this system by accident. Name it on purpose."],
  ["vx-a-metamerism-light", "Colour extras", "A mix that matches in the studio can divorce under a shop fluoro",
    "Metamerism: different spectra, same look under one lamp. Print and textile people lose sleep. Painters meet it when a ‘perfect grey’ goes purple at the opening.",
    "If it matches at my desk it matches at the gallery. Light is light.",
    "Check the work under daylight, warm LED, and the hallway. Adjust the offender, not the whole picture as a panic.",
    "A uniform that matches in the storeroom and clashes on the oval is metamerism with a school logo."],
  ["vx-a-earth-first", "Colour extras", "Earths are cheap workhorses, not ‘beginner colours’ you graduate from",
    "Ochres, umbers, a red oxide. They mute without a fight. A painting of only cadmiums is a sports drink. Earths still have a hue.",
    "Serious artists use only modern organics. Earths are for Year 7.",
    "Do a landscape with three earths plus one loud. See how far the loud has to travel.",
    "A Pilbara red is an earth with a place name. Tube names are not Country, but the hue can still be honest."],
  ["vx-a-complement-mud", "Colour extras", "Mud is often a complement you did not admit, not a moral failing of the student",
    "Red in a green, a leftover on the brush, a rinse that is already soup. Sometimes mud is the right grey. Accidental mud is a dirty rinse.",
    "Mud means you cannot paint. Talent is a clean palette.",
    "Mix a complement grey on purpose. Mix a second by accident from a dirty brush. Keep the first, wash the second.",
    "A ‘muddy’ folio note that never names the complement is a vibe, not a lesson."],
  ["vx-a-highlight-colour", "Colour extras", "A highlight is the light’s colour on a surface, not white as a religion",
    "A glossy red apple’s spec can be the lamp (cool, pale). A matte orange has a weaker, more local highlight. White chalk on everything is a sticker sheet.",
    "Highlights are white. Always. That is how you prove you saw the shine.",
    "Tint the spec toward the lamp. Keep it off a matte plane. One spec per shiny object unless there are two lamps.",
    "A wet street at night has many specs. A dry orange does not. Count the lamps."],
  ["vx-a-afterimage-comp", "Colour extras", "Stare at red, look at white, meet a cyan ghost: the eye is a tired opponent",
    "Complementary afterimages. Painters use the fight (a red next to a green vibrates). Rest the eye on a mid grey between passes.",
    "If colours vibrate you mixed wrong. Vibration is a error.",
    "Place a pure complement pair at the focal. Grey the rest. Step back. If the whole page vibrates you used the trick as a wallpaper.",
    "A interactive installation that uses afterimage is a design of time. A homework page that uses it by accident is a headache."],
  ["vx-a-type-pairing", "Design extras", "A type pairing is a contrast of jobs, not two fonts that ‘feel nice’",
    "Display versus body, a serif with a sans, similar x-height if they must sit in one line. Two similar sans is a muddy handshake.",
    "More fonts is more personality. Six on a poster is a festival.",
    "Pick one body, one shout. Test a paragraph and a headline. Kill the third family.",
    "A school newsletter with a new font per article is a carnival, not a voice."],
  ["vx-a-modular-type", "Design extras", "A type scale is a ratio, not 11, 12, 13 as a timid ladder",
    "1.25 or 1.333 between rungs. Hierarchy is a jump the bus can see. A 0.5 pt ‘difference’ is a confession of fear.",
    "Small differences are subtle and therefore professional. Subtle is 0.5 pt.",
    "Set a modular scale. Assign H1, H2, body. Print A3. Walk 4 metres.",
    "A title at 11 and a body at 10 is not a hierarchy. It is a rumour of one."],
  ["vx-a-kerning-pair", "Design extras", "Kerning is a pair; tracking is a block; they are not a synonym",
    "AV, To, the gap in a logo. Tracking a headline into a ransom note is a different tool. Body text tracking is a last resort for a widow, not a vibe.",
    "Spread all letters until it looks airy. Air is luxury. Pairs do not exist.",
    "Fix three pairs in a wordmark. Do not touch the tracking of the paragraph until the rag is honest.",
    "A WAVES logo with a canyon in AV is a intern tell. Print it large."],
  ["vx-a-widow-orphan", "Design extras", "A widow is a lonely last line; an orphan is a lonely first — both are rags with names",
    "Edit the copy, a tracking whisper, a pull. Centred body paragraphs hide these sins under a new sin. Designers who never read the words cannot fix them.",
    "If the copy is sacred you cannot touch a line break. Sacred is a layout.",
    "Read the last lines of every paragraph. Pull one word. Ask the writer before you invent a hyphen in a name.",
    "A concert program with a widow that is the date is a civic fail. The date is the brief."],
  ["vx-a-figure-ground", "Design extras", "Figure–ground reversal is a designed flip, not a printer error",
    "Rubin’s vase neighbourhood. A logo that works in both states is a flex with a risk of cleverness. Street signage cannot afford the puzzle.",
    "If people see two things you failed clarity. Puzzles are unprofessional always.",
    "Draw a mark that reads as both a cup and faces. Then a bus-side version that must only be one. Know which job you are in.",
    "A wayfinding arrow that is also a mascot is a cute that kills a visitor at a fork."],
  ["vx-a-visual-weight", "Design extras", "Visual weight is not the same as centimetres",
    "A small black can balance a large pale. High-contrast, dense texture, and faces weigh more than a beige rectangle of the same size.",
    "Bigger is heavier. Always. Physics class said so, so layout agrees.",
    "Cut a composition in half. If one side is a brick and the other is mist, add a counter or accept a slide.",
    "A tiny red stamp on a poster can outweigh a pale photograph. That is the stamp’s job."],
  ["vx-a-z-pattern", "Design extras", "A Z-pattern is a habit of a Western poster, not a law of eyeballs",
    "Logo top-left, offer, a button bottom-right. F-patterns show up in text-heavy screens. Vertical scripts and RTL pages are not your Z.",
    "People always look top-left first, globally, because of English. Science.",
    "Map a read order with numbered thumbnails. Test one person who did not make it. Then a mobile stack where Z becomes a scroll.",
    "A gallery wall is not a web page. People enter from a door, not a URL bar."],
  ["vx-a-bleed-crop", "Design extras", "Bleed is a 3–5 mm religion because paper shifts",
    "Artwork past the trim. Crop marks are not decoration. A ‘I left a white edge to be safe’ is a different look, not a bleed.",
    "Printers can print to the exact pixel of my screen. Millimetres are for carpenters.",
    "Set bleed in the file before you design. Keep type inside a safe margin. Soft-proof.",
    "A photo that needed the fingertips and died on the guillotine is a bleed story. Fingers live inside the safe."],
  ["vx-a-white-space-rest", "Design extras", "A rest of space is an element, not leftover ‘should fill’",
    "Margins, a pause, a luxury brand’s empty. Clip-art in every gap is a 1999 panic. Density can be a style if the read order still works.",
    "Empty is unfinished. Fill is professional.",
    "Increase the margin. Remove one object. Ask whether the shout got louder.",
    "A packed Year 12 poster and a gallery card have different jobs. Name the job before you pack."],
  ["vx-a-snap-align", "Design extras", "Alignment is an invisible line, not ‘near enough’ at 3 mm",
    "Snap to a grid or a shared edge. A designed rag (poetry) is still a decision. Eight almost-lefts are a jitter.",
    "If it is close it is aligned. Close is a grid.",
    "Pick one edge. Snap. Then one break with a reason. Print and check with a ruler, not only a zoomed-out laptop.",
    "A business card with four alignments is a small tremor. Tremor reads as amateur at handshake distance."],
  ["vx-a-contrast-outdoor", "Design extras", "Outdoor contrast is a glare test, not a pale elegance on a studio monitor",
    "Yellow on white dies in a playground. WCAG-ish contrast is a civic cousin of posters. Colour-blind encoding still cannot be hue-only.",
    "Pretty is readable. Pretty is access.",
    "Tape the poster in sun. Read the date from 6 metres. Fix the type, not the sun.",
    "A school fete sign in canary on cream is an elegant fail. Fail is a parent driving past."],
  ["vx-a-wayfind-sequence", "Design extras", "Wayfinding is a sequence of decisions, not one pretty arrow",
    "Confirm at nodes, consistent height, a family of signs. Eight typefaces in a hospital is a panic. Art that hides the arrow is a different brief.",
    "If the arrow is beautiful they will find the room. Beauty is a path.",
    "Map the decision points. Put a confirm after a turn. Test a stranger from the car park.",
    "A school with six names for the same hall is a wayfinding bug. Names are a system."],
  ["vx-a-data-ink", "Design extras", "Chart junk is decoration that does not carry a number",
    "Tufte’s fight: 3D pies, a dual axis marriage, a truncated bar that turns 2% into a crisis. The title is already a claim.",
    "If it is a graph it is data. Data cannot lie. People can, but not graphs.",
    "Start at zero if you mean magnitude. Show n. Kill the 3D. Then a sentence of what remains.",
    "A ‘jobs created’ count versus a rate is a politician’s switch. Designers can refuse the switch."],
  ["vx-a-cta-one", "Design extras", "A poster with five calls to action has none",
    "One verb you can do next: buy, arrive, scan, enrol. A QR plus a novel plus three URLs is a flyer that wanted to be a website.",
    "More buttons is more helpful. Help is a pile.",
    "Write the one next step. Make it the loudest after the name of the event. Hide the rest in small or on a page.",
    "A council event that lists twelve departments is a org chart, not an invitation."],
  ["vx-a-swiss-grid-break", "Design extras", "A Swiss grid is a beat; a break is a drum fill",
    "Flush, a few sizes, a photographic honesty. Breaking every margin is not ‘expressive Swiss’. You need the beat first.",
    "Grids are for accountants. Art is a scatter.",
    "Set a 12-column. Place type. Break once with a reason you can say aloud.",
    "A tram ad that still aligns is often this school without the manifesto. Steal the alignment, skip the manifesto if you want."],
  ["vx-a-golden-not-law", "Design extras", "The golden ratio is a habit some people love, not a police of beauty",
    "1.618 as a rectangle. Plenty of good work ignores it. Retrofitting a spiral on a masterpiece is a poster of mysticism.",
    "If it is not golden it is amateur. Nature uses it so you must.",
    "Crop three ways: thirds, centre, a 1:1.618. Pick with a reason that is not ‘the Greeks’.",
    "A logo forced into a spiral diagram for the process page is a theatre. Process can be plainer."],
  ["vx-a-gesso-ground", "Making extras", "Gesso is a ground with a tooth, not a magic white that forgives oil on raw cotton as a habit",
    "Acrylic gesso on canvas, a oil ground, a size on paper. Fat paint on hungry raw fabric can rot. Tooth decides whether a wash sits or crawls.",
    "Any white paint is gesso. Prime with house paint from a garage. Same job.",
    "Read the support. Prime as the medium asks. Test a wash on a scrap of the same ground.",
    "A yellowing unprimed oil on a school cotton is a conservation ticket in five years. The art room will not be there to help."],
  ["vx-a-fat-over-lean", "Making extras", "Fat over lean is a flexibility sandwich, not a proverb you chant after a crack",
    "Lean (more solvent, less oil) underneath; fatter on top so the top stays flexible. A lean glaze on a fatty cake can craze. Acrylic has a different physics — do not import the proverb blindly.",
    "Oil is oil. Layer any way. Rembrandt did vibes.",
    "Underpass in a lean umber. Build with more oil. Varnish later, not in week one.",
    "A cracked Year 12 oil that was lean on fat is a chemistry, not a talent inquest."],
  ["vx-a-lino-register", "Making extras", "Registration is why a second colour lands on the first, not hope",
    "Pins, a jig, a T-bar. Reduction prints destroy the block as they go — test proofs are not optional. A ghost print is leftover ink, sometimes beautiful.",
    "Just eyeball the second pass. Hands are printers.",
    "Make a jig before you love the image. Pull a proof. Number the edition honestly, including APs.",
    "A four-colour lino of a face with tiny eyelashes is a fight the medium might win. Simplify or register like a monk."],
  ["vx-a-reduction-print", "Making extras", "A reduction print is a one-way door; the block gets thinner and cannot go home",
    "Each carve deletes what will stay the previous colour. Edition size is decided early. A ‘I’ll just recut’ is a different block.",
    "Printmaking is a photocopier with pride. You can always undo a carve with hope.",
    "Plan colours light to dark or as the method asks. Print the whole edition at each stage before the next carve.",
    "Picasso’s linos are a famous reduction story. Your first one can still be three colours and honest."],
  ["vx-a-clay-hollow", "Making extras", "Thick clay explodes because water becomes steam; hollow or wait",
    "Score and slip joins. An armature in clay that cannot burn out is a kiln grenade. Bone-dry before a bisque. This is physics, not a vibe of patience.",
    "Solid lump, hope, kiln. That is traditional.",
    "Hollow anything thicker than a thumb. Join with slip. Ask a technician before you invent a kiln schedule.",
    "A sculpture’s silhouette from 5 metres is the first read. A explosion is not a texture."],
  ["vx-a-paper-grain", "Making extras", "Paper has a grain and a history; tearing with it is not a personality test",
    "Grain direction for a fold, a deckle as a edge that was the mould, a weight in gsm. Watercolour on a business card is a different sport from 300 gsm rag.",
    "Paper is paper. Printer paper is a cheap canvas. Grain is a myth of stationers.",
    "Tear a strip with and against the grain. Fold a card both ways. Then pick a sheet that matches the wetness of the medium.",
    "A book bind that ignores grain is a cover that warps in a Sydney summer. Binders already knew."],
  ["vx-a-brush-care", "Making extras", "A brush is a tool with a glue in the ferrule; acrylic left to sleep is a sculpture of regret",
    "Rinse before the skin forms. Shape the tip. Solvent for oil, not a shared food sink. Cheap brushes can still die of a good artist’s laziness.",
    "If it is for art, tools are immortal. Soak overnight in a jar as a lifestyle.",
    "Wash until the rinse is clear. Rest bristles, not tips, in a jar. Bin a splayed brush rather than fight a portrait with it.",
    "A class sink full of acrylic milk is a plumbing ticket. That is also craft."],
  ["vx-a-dpi-start", "Making extras", "Resolution is a decision at the start, not a prayer at export",
    "300 dpi at print size, 72-ish for a screen hero that will never print. Upscaling a 50 px logo is porridge. Vectors exist for a reason.",
    "I will enlarge it later. Software is a microscope that creates information.",
    "Set the document to the largest honest output. Name layers. Save versions. Export a copy, do not overwrite the brain file.",
    "A folio photo of a painting at 800 px across is a different fail: the work was analogue and the documentation was lazy."],
  ["vx-a-non-destructive", "Making extras", "Adjustment layers are a reversible opinion; cooking pixels is a fried egg",
    "Masks, a smart object, a colour grade you can still hate tomorrow. Flatten at the end if a printer demands it. One layer ‘like oil’ is a choice, not a virtue.",
    "Digital should be like oil: one layer, no undo philosophy. Purity.",
    "Keep line, paint, and type apart. Grade on top. Duplicate before a filter that cannot take it back.",
    "A ‘I lost the layers’ USB is a process ethics. Version names are kindness to future-you."],
  ["vx-a-edition-honest", "Making extras", "1/10 is a claim; a reprint after a sell-out is a new edition or a lie",
    "State the process, the paper, a chop. Monotype is unique — do not number it as a 1/1 edition to look like a print shop unless that is the convention you name. APs are not a secret extra pile for mates only if you claimed a tight edition.",
    "Numbers are a vibe. Collectors do not read. Print more if it is popular.",
    "Write the edition in pencil as the field uses. Keep a studio log. If you reprint, say so.",
    "A school ‘edition’ of 40 with no log is a learning piece. Call it a series, not a market claim."],
  ["vx-a-maquette-first", "Making extras", "A maquette is a cheap disaster; a 2-metre first try is an expensive one",
    "Card, clay, a 3D print of a join. Installation OH&S is the unsexy medium. Wind, a crowd path, a downpipe — the site-specific path next door still applies.",
    "If the idea is strong the material will obey at any scale. Ideas are physics.",
    "Build 10 cm. Photograph. Fix the join. Then scale. Take the small one to the site.",
    "A clay too thin slumps overnight. Night is a collaborator. The maquette finds that before the truck."],
  ["vx-a-varnish-wait", "Making extras", "Varnish is a later skin; a week-old oil is still a chemistry experiment",
    "Retouch versus final. Gloss changes value. A spray in an unventilated art room is a lungs ticket from the original studio-safety path — still true.",
    "If it looks dry it is dry. Touch and spray. Deadlines are chemistry.",
    "Read the medium’s wait. Test a corner. Photograph before varnish because varnish is a look.",
    "A sticky varnish dusted with Year 8 glitter from the next desk is a conservation comedy. Isolate."],
  ["vx-a-tool-sharpen", "Making extras", "A dull lino tool is a slip toward the other hand",
    "Away from the body, a bench hook, a strop. Clay wires, a needle tool, a heat gun’s aim. Studio safety is not a vibe and not only solvents.",
    "Sharp tools are dangerous so keep them blunt. Blunt is safe. Emergency departments disagree.",
    "Sharpen, clamp, cut away. Wash then eat. Report a slip. Read the MSDS for the other half of the room.",
    "A UV resin craze without gloves is dermatitis as a craft trend. Cool is not PPE."],
  ["vx-a-palette-hygiene", "Making extras", "A dirty rinse is a colour decision you did not mean",
    "Two jars, a wipe, a dedicated dark brush. Impressionists sometimes mixed dirty on purpose. You should know which you are doing.",
    "Real painters have filthy water. Filth is authenticity.",
    "Change water when it is soup. Wipe the ferrule. Mix a grey on purpose on a clean patch.",
    "A class of 24 sharing one rinse is a brown united nations. Budget a second bucket."],
  ["vx-a-patina-vs-dirt", "Making extras", "Patina is a designed age; dirt is a storage fail",
    "Bronze chemistry, a wax, a rust that is a finish. A dusty unsealed charcoal is not a patina. Conservation may freeze a patina you thought was a start.",
    "Old-looking is always better. Rub ash on it. Museums love ash.",
    "Decide the finish in the proposal. Seal works that should not keep collecting bus soot. Label a living rust if it will keep living.",
    "A public sculpture’s ‘patina’ can be vandalism plus weather. Maintenance is part of the design."],
  ["vx-a-stretch-canvas", "Making extras", "A stretcher is a square you prove with diagonals, not a hope",
    "Even tension, a key, a staple pattern. A warp shows up under a gallery downlight as a banana. Cheap bars twist in a car boot.",
    "If the fabric is taut in the middle the corners can flap. Middle is the picture.",
    "Measure diagonals. Restaple. Leave keys for a later season. Photograph raking light before you paint a week of work.",
    "A humid Queensland studio will slacken a canvas. Keys exist. Use them before you panic-paint a new ground."],
  ["vx-a-folio-photo", "Making extras", "Documentation is a second artwork with a tripod",
    "Square on, even light, a colour target if you are serious, no wonky keystone. A glossy varnish flare is a lie about the object.",
    "A phone snap in a yellow bedroom is fine. Examiners will squint into the truth.",
    "Use raking light only to show texture on purpose. Crop clean. Keep a detail shot and a whole-object shot.",
    "A sculpture photographed against a busy doona is a amateur tell. A grey card is cheaper than a doona."],
  ["vx-a-patron-power", "Context extras", "Who paid is part of the picture, not gossip you skip for ‘pure form’",
    "Church, a duke, a brand, a grant, a parent’s credit card. Commissions shape size, piety, and who gets to be naked. Provenance later is a trail of those deals.",
    "Genius floats free of money. Dates are for historians, not artists.",
    "Write three facts around a work that include the payer. Then look again at the smile.",
    "A colonial landscape that emptied Country was often a real-estate mood board. The gum is not innocent automatically."],
  ["vx-a-gaze-who", "Context extras", "A gaze is who is allowed to look, and from where",
    "Male gaze as a classroom door, not a complete universe. The model’s look back, a queer camera, a surveillance camera are other gazes. A nude is not only ‘skill with anatomy’.",
    "If it is skillful the politics dissolve. Skill is a solvent.",
    "Name who is looking, who is shown, who was in the room. Then whether you are repeating the room.",
    "A sports photograph of a body can be a gaze too. Briefs are not only oil paint."],
  ["vx-a-provenance-trail", "Context extras", "Provenance is a paper trail, not a vibe of ‘old therefore legit’",
    "Dealers, a gap in the 1940s, a repatriation claim. Museums now ask. A family story is a start, not a certificate.",
    "If it is in a frame it is cleared. Frames are lawyers.",
    "For a research task, list owners if known. Flag a gap. Do not invent a romantic smuggler.",
    "Nazi-era gaps and First Nations stolen objects are different files with a shared lesson: objects travel with violence sometimes."],
  ["vx-a-conserve-ethics", "Context extras", "Cleaning a painting is an interpretation, not a car wash",
    "Varnish removal can take a later hand with it. Reversibility is a conservation ethic. A ‘restore’ filter on a scan is not the same job.",
    "Old should look new. Shine is respect. Strip until it pops on Instagram.",
    "Read one conservation report in a paragraph: what they did not do. Then your opinion as a opinion.",
    "A over-cleaned sky that lost the artist’s glaze is a permanent argument. Humility is a tool."],
  ["vx-a-biennale-industry", "Context extras", "A biennale is an industry with airfares, not only a spirit of now",
    "National pavilions, a curator class, a local artist who cannot afford the opening. Contemporary can still be a drawing. The wall text is a claim you can fight.",
    "If it needs a wall text it is fake. Real art explains itself like a sunset.",
    "Read the text, then agree or fight with evidence from the work. Name who funded the pavilion.",
    "A pile of chairs can hold a thought. So can a pencil. The brief is whether it holds, not whether it is furniture."],
  ["vx-a-street-vs-council", "Context extras", "Street work sits in a legal and a gift economy; council murals are a cousin with a form",
    "Permission, a criminal damage file, a commissioned wall. Style transfer onto a sacred site is not ‘street’. Photographing a mural for a tote is a shop.",
    "If it is outside it is free to take. Outside is a licence.",
    "Ask who owns the wall, whose style, whether the photo is for study or a product. Cite living artists.",
    "A legal wall in Melbourne and a tagged house in a suburb are not the same civic. Discern."],
  ["vx-a-feminist-reread", "Context extras", "A feminist reread asks who was the muse, who was the member",
    "Academies, a nude as a job, a wife’s labour in a studio. Adding women to a canon is not only a headcount; it is a change of questions. Intersectional rereads follow.",
    "The past was a different time so questions are rude. Rude is unhistorical.",
    "Take one famous work. Ask who is missing from the studio. Then one work that refused the setup.",
    "A ‘great men’ slideshow with one slide of ‘also women’ is a pamphlet, not a reread."],
  ["vx-a-bauhaus-workshop", "Context extras", "Bauhaus wanted workshops, not a poster of geometric beige as a personality",
    "Form follows a function argument, a craft-meets-industry hope, a politics that the Nazis shut. Copying a red square is not a membership.",
    "Modern means a white canvas and a lie that anyone could do it, so it is a scam. Also: beige is always Bauhaus.",
    "Pick one workshop (textile, metal, print). Name one object and one rule it broke. Then who it still excluded.",
    "A local TAFE workshop is closer to the idea than a phone wallpaper of a building in Dessau."],
  ["vx-a-aura-copy", "Context extras", "A reproduction is a different object; aura was Benjamin’s worry, not a scented candle",
    "The meeting with a thing in a room versus a JPEG. Both can be serious. Selling a fake is a crime; learning from a copy is a classroom.",
    "If I saw it on my phone I have had the experience. Resolution is presence.",
    "Visit one work in a room if you can. Write what the JPEG dropped (scale, smell, a guard, a crowd).",
    "A immersive van Gogh franchise is a business of aura-substitute. Fun maybe; substitute is the word."],
  ["vx-a-archibald-prize", "Context extras", "A portrait prize is a public argument about who counts as a face",
    "Archibald rules, a celebrity gravity, a packing-room prize as a folk veto. Packing the room is not a joke about art being fake; it is a different audience.",
    "Prizes discover the best artist. Panels are oracles. Also: prizes are always corrupt. Two cartoons.",
    "Read the eligibility. Look at who was hung. Then a year the crowd hated the winner — and why.",
    "A satirical entry that still meets the rules is a civics of a prize. Rules are a medium."],
  ["vx-a-artist-statement", "Context extras", "A statement is a claim the work should be able to survive",
    "What you did, why it is not only a moodboard, a debt to a living culture named properly. Jargon fog is the logic hub’s cousin. A statement that the work contradicts is a split brief.",
    "If the work was real it would not need words. Wall text is a scam always. Also: write a novel.",
    "Three sentences: process, question, context. Cut the words you could swap into anyone’s folio.",
    "A ‘exploring identity’ with no named tension is a mad-lib. Name the tension."],
  ["vx-a-cadmium-health", "Context extras", "Some pretty pigments are a workplace; cadmium and silica are not a vibe",
    "MSDS, a dry pastel dust, a spray can. The original studio-lungs lesson still sits here as context: bodies are in the history of the colour.",
    "If it is for art, toxicity is optional. Artists are immortal in movies.",
    "Pick a safer substitute when the brief allows. Ventilate. Do not blow pastel dust to ‘see the colour’.",
    "A Impressionist green that was arsenic is a history with a stomach. Romanticise carefully."],
  ["vx-a-disability-aesth", "Context extras", "Access can be a aesthetic, not only a ramp bolted on at the end",
    "Alt text as writing, a tactile hang, a seated sightline, audio description as a composition. ‘We forgot the ramp’ is a design of who was imagined.",
    "If I can use the stairs the building is fine. I am the measure of a museum.",
    "Design one work with a second channel (touch, caption, a lower hang). Test with someone who needed it — paid if it is extra labour.",
    "A dark installation that is a trip hazard is a lawsuit and a exclusion. Tape is not a vibe."],
  ["vx-a-national-school", "Context extras", "A ‘national school’ is a marketing of painters, not a genetics of a landscape",
    "Heidelberg, a desert colour, a myth of harsh light. Who is in the picture — and who is not — is still the subject. A tea-towel gum is a leftover.",
    "Paint a gum and you have done Australian art. Finished.",
    "Compare two landscapes a century apart. Who is missing in the older one? Who is missing now?",
    "A bushfire sky is a contemporary landscape. It is not a postcard, and it is not only a Heidelberg sequel."],
  ["vx-a-archive-as-work", "Context extras", "Some works are files, lists, and a box; the box is not a failure to paint",
    "Institutional critique, a database, a family album as a claim. Caption the box. OH&S still applies if people must rifle through.",
    "If it is paperwork it is not art. Art is a picture of a fruit.",
    "Propose the archive’s order as the argument. What is next to what. Who may touch.",
    "A stolen archive returning to a community is a different object from a student cardboard box of receipts. Do not cosplay the first."],
  ["vx-a-conceptual-retinal", "Context extras", "Duchamp’s retinal insult was a argument, not a ban on looking",
    "Ideas as material. Looking still happens. A urinal without the conversation is a plumbing. You have to know which conversation, or you are in a meme.",
    "If anyone could do it, it is a scam. Also: if it needs history it is elitist. Two traps, hold both.",
    "Pick one conceptual work. State the rule it proposed. Then whether the object still needs to be that object.",
    "A student ‘chair with a label’ that has no rule is a furniture. Write the rule first."],
  ["vx-a-repatriate", "Context extras", "Repatriation is a living claim on objects, not a extra-credit footnote",
    "Human remains, a secret-sacred, a museum’s ‘universal’ story. Consult, do not assign a project that asks students to ‘design a display’ of what is not theirs.",
    "If it is in a glass case the file is closed. Cases are law.",
    "Use artists’ and nations’ names. If you cannot, pick another brief. Support returns rather than restaging.",
    "A classroom ‘Dreaming’ pastiche remains a harm. This path is a stop sign with a reading list."],
  ["vx-a-gesture-long", "Studio extras", "A long pose still needs a gesture; freeze is not the same as stiff",
    "The 30-second action line is a foundation the three-hour sitting can kill with eyelashes. Re-gesture at the 20-minute mark. Weight on a foot still exists when the model is tired.",
    "Long poses are for detail. Gesture is a warmup you throw away.",
    "From the shoulder, one line of action, then volumes. At the hour, squint: is the spine still a verb?",
    "A dancer photo still wants a gesture. A seated exam model does too."],
  ["vx-a-thumb-six", "Studio extras", "Six stamps beat one precious A3 that fails at postage size",
    "If composition fails at 2 cm, a metre of blending will not save it. Graphic designers already knew. Painters forget because pencils feel serious.",
    "Detail first. Thumbnails are for people who cannot draw yet.",
    "Six stamps, three values each. Pick. Enlarge. Keep the stamp taped beside the work.",
    "A comic cover that only works at print size and dies as a thumbnail is a shop fail."],
  ["vx-a-master-study-label", "Studio extras", "A study after someone is a conversation; selling it as yours is a forgery file",
    "Copy to learn decisions. Caption ‘study after’. Then a piece that answers them with one rule changed (palette, who sits, a time of day).",
    "Copying is cheating. Never look at anyone dead. Also: copy and enter it as original. Two disasters.",
    "Copy, caption, change one rule. Museums have rules about copies in the gallery. Learning at home is not selling.",
    "A packed Archibald that is a photocopy of last year’s winner is a conversation the panel will notice."],
  ["vx-a-process-pages", "Studio extras", "Process pages are evidence of thinking, not a mess to hide under a clean final",
    "Thumbnails, a reject, a redo of a hand. Precious first lines are a trap. A client changing the brief is the job, not a moral failing.",
    "First try is the authentic one. Redo is cheating. Also: hide the fails so you look professional.",
    "Date the pages. Keep the ugly. Version files. Put the stamp next to the final in the folio.",
    "An exam that is one-and-polish of a weak idea is a risk. Eight stamps then polish the winner."],
  ["vx-a-sketch-ugly", "Studio extras", "A sketchbook that is only finished miniatures is a gallery, not a lab",
    "Ugly pages, tickets, a bad idea that becomes a good one in three weeks. Performing a perfect book for marks can kill the lab. Phones can be a book if you tag them.",
    "Only put finished miniatures in a sketchbook so it looks like an artist’s. Ugly means you are not an artist.",
    "Date pages. Steal with citation (a labelled master study). Fail on purpose on a Tuesday. Do not tear the fail.",
    "A teacher who marks pretty-only trains a climate of lying about process."],
  ["vx-a-still-life-triangle", "Studio extras", "A still life is a theatre of ellipses and overlaps, not a fruit altar to talent",
    "Height variety, a overlap, a cloth as a landscape of folds. A row of objects on a shelf is a lineup. Light from one key still applies.",
    "More objects is more skill. Fill the table so nobody thinks you were lazy.",
    "Three objects, one cloth, one lamp. Move until the silhouette reads. Then a fourth only if it earns the cut.",
    "A plastic fruit with no bruise can still teach ellipse. A real pear teaches a local colour that plastic skipped."],
  ["vx-a-plein-air-wind", "Studio extras", "Plein air is a time limit with weather; the studio is allowed to finish",
    "Values first because the sun moves. A clip, a limited kit. Bushfire smoke is a health stop, not a romantic haze to ‘lean into’ with lungs.",
    "Real painters never touch a landscape indoors. Purism. Also: take a photo and pretend you were there. Two cheats, name them if you use them.",
    "Block in 20 minutes. Note the sun’s direction. Leave. A studio pass should not invent a second sun.",
    "A fly in the ochre is a Australian documentation. Keep it or pick it — both are decisions."],
  ["vx-a-life-room-etiquette", "Studio extras", "A life room is a workplace with a person in it, not a zoo of anatomy",
    "Heat, breaks, no phones at the dais, a fee. Caricature without consent in a class is a harm. Gesture still comes before eyelashes.",
    "The model is a object with a pulse. Talk about them as planes only, including in the corridor.",
    "Thank them. Keep the jokes off the body. Draw. The anatomy lesson does not need a commentary.",
    "A leaked phone photo of a session is a ethics bomb and maybe a law. Bags stay closed."],
  ["vx-a-comic-gutter-time", "Studio extras", "A gutter is time the reader performs; panel size is a shout",
    "Closure: the reader fills the gap. A splash is a shout. Lettering is drawing. A pretty single frame is not a board.",
    "If the drawing is pretty the story will work. Pretty is an edit.",
    "Thumb twelve panels. One change per panel. A friend should be able to retell it. Then ink one page properly.",
    "A silent page can still shout. That is pacing, not a forgotten speech balloon."],
  ["vx-a-storyboard-arrows", "Studio extras", "Arrows are not optional if the camera moves",
    "Shot size, a 180-degree line, what the audience knows. A film that exists only as a pretty concept frame will stall in a group.",
    "Write the script in prose and film it in your head. The board is extra.",
    "Twelve frames, arrows, shot sizes. A friend should be able to shoot from it without a séance.",
    "A jump scare is a timing. Board the silence before it. Horror is a graphic design of delay."],
  ["vx-a-collage-cite", "Studio extras", "A collage is a new sentence from old images, with a citation in the folio",
    "Copyright still exists. Magazines are not a free quarry for a commercial poster. Transform with a claim, do not re-ad a perfume as your campaign.",
    "Glue random. Meaning appears in the glue. Also: if I saw it online it is mine.",
    "A clear new claim. Cite sources. Hannah Höch had a politics; a moodboard needs one too or it is a texture.",
    "A First Nations design in a collage without protocol is not a texture pack. Stop and read the living-cultures path."],
  ["vx-a-install-entry", "Studio extras", "Plan what they hear first and what they leave with; the room is a medium",
    "Walk path, smell, duration, a maquette. A dark room is a tool. A trip hazard is a lawsuit. Teachers sign off because of the hazard, not because they hate fun.",
    "Put objects on the floor. That is installation if you say so with confidence.",
    "Draw the entry. Tape the path. Test a person with a bag and a pram if the public will have both.",
    "A downpipe through a mural is a downpipe with a mural. Honesty in the site visit."],
  ["vx-a-public-plinth", "Studio extras", "A plinth is a sentence; a plaza has weather, vandals, and people who sit",
    "Scale, sightlines, shade, a memorial’s grief brief. Maintenance is a design. Studio scale and plaza scale are not a bigger print of the same file.",
    "Art in a studio and art in a street are the same file at a bigger print size.",
    "Visit a work. Photograph the site, not only the object. Who uses the shade? Who is named?",
    "A statue debate is a design-and-history class. Empty plinths are sentences too."],
  ["vx-a-craft-joint", "Studio extras", "A joint in wood is a sentence the chair has to keep saying under a body",
    "Function can be the idea. ‘Just craft’ as an insult is a class story. A cup that leaks is a sculpture that lied about being a cup — caption honestly.",
    "If it is useful it is not art. If it is art it should not work. Two slogans, no mug of tea.",
    "Make a cup that holds water and also has a point of view. Photograph the join. Test with actual tea (cool enough).",
    "A glued mitre that opens in a heater wind is a humidity lesson. Sydney southerlies teach it."],
]);
