import { pack } from "../pack.mjs";

export const BUSINESS_VOLUME = pack("business", [
  ["vx-b-working-capital", "Money", "Working capital is current assets minus current bills, a timing story",
    "Stock, debtors, cash vs creditors. A profitable firm can still choke if customers pay in 90 days and staff are weekly. That is working capital, not a vibe of busy.",
    "If the till is full at lunch you have working capital. Notes are a ratio.",
    "List what turns into cash soon and what you must pay soon. Then a delay that would break you.",
    "A café with a fridge of milk and a delayed catering invoice is this in litres."],
  ["vx-b-gross-vs-net", "Money", "Gross profit is after cost of goods, not after rent and wages",
    "Sales minus COGS. Net is after the overheads. A ‘we make 50%’ that is gross while rent eats it is a slogan.",
    "Profit is the number on the till minus the wholesale, and that is the whole story.",
    "Write three lines: sales, COGS, gross; then overheads; then net. Then GST as a separate hat.",
    "A $4 coffee with $1 beans is not $3 in the owner’s pocket. Rent, labour, breakage."],
  ["vx-b-depreciation", "Money", "Depreciation is spreading a machine’s cost across years, not the van rusting as a feeling",
    "A $40k oven over 8 years is a $5k expense per year in a straight-line cartoon. Cash left in year 1. Tax rules may differ from the cartoon.",
    "If it still works it has not depreciated. Working is a valuation.",
    "Name cost, life, method. Then cash vs expense. Then do not mix with ‘the market price of the van today’ unless you mean impairment.",
    "A laptop for a sole trader is often a write-off threshold story. The ATO has a small-asset rule that dates — check the year."],
  ["vx-b-liquidity", "Money", "Liquidity is how fast an asset becomes cash without a fire sale",
    "Cash is liquid. A custom-fitted coolroom is not. A solvent firm (assets > debts) can still be illiquid this Tuesday.",
    "If you are rich on paper you can pay today. Paper is a tap.",
    "Order assets by how fast they cash. Then a bill due this week. Then a line of credit as a buffer, with a cost.",
    "A farmer with land and no rain is solvent-ish and thirsty. Land is not wages this Friday."],
  ["vx-b-leverage", "Money", "Leverage is borrowed money amplifying a bet both ways",
    "A $20k of yours plus $80k of bank in a van fleet. Returns up and interest plus ruin down. Gearing is the ratio.",
    "Borrowed money is free if the business is confident. Confidence is collateral.",
    "Write equity, debt, and what happens if sales drop 20%. Then a covenant the bank actually wrote.",
    "A house with a huge mortgage is household leverage. Same word, same two-way."],
  ["vx-b-npv-feel", "Money", "A dollar next year is not a dollar today; NPV discounts the wait",
    "Time value, a rate that is a cost of capital cartoon. A glossy ‘$1m in year 5’ without a discount is a brochure.",
    "Add the future dollars. Dates are decoration.",
    "Pick a rate, discount each year’s cash, subtract the initial outlay. Then a sensitivity: what if the rate is higher.",
    "A school ‘is this machine worth it’ can be payback (crude) vs NPV (less crude). Name which you used."],
  ["vx-b-payback", "Money", "Payback is how long until the cash comes home, ignoring what happens after",
    "A machine that pays back in 2 years and then dies in year 2.1 looks ‘fast’ and is a trap. Payback ignores the tail and the time value.",
    "Shorter payback is always the better project. Speed is NPV.",
    "Compute the cumulative cash until it crosses zero. Then ask what you threw away after. Then a better metric if the lives differ.",
    "A solar panel with a 7-year payback and a 20-year life is a tail story. Payback alone hides the tail."],
  ["vx-b-contribution", "Money", "Contribution is selling price minus variable cost, a brick toward fixed costs",
    "After break-even, contribution is a crude profit brick. Mix of products with different contributions is a menu problem.",
    "Every extra sale is extra profit equal to the price. Variable costs are optional.",
    "Price − variable. Then how many bricks to cover rent. Then a product that ‘sells well’ with a tiny brick.",
    "A $2 extra shot of coffee that costs $0.20 is a contribution story. A $2 extra that needs a second barista at peak is not purely variable."],
  ["vx-b-fixed-step", "Money", "Fixed costs can step: one van, then a second van",
    "Rent is fixed until you need a second shop. A step cost is a stair, not a slope. Planning that ignores the stair is a surprise wage bill.",
    "Fixed means never changes, even if you open a second site. The word is a vow.",
    "Name the range where it is fixed. Then the trigger for the step. Then a chart that is a stair.",
    "A food-truck licence is fixed until a second truck. Council does not prorate your vibe."],
  ["vx-b-owner-draw", "Money", "A draw is not a wage, and a wage is not a profit",
    "Sole traders mix. Pay yourself a wage in the model or you will think a busy month is a profit when it was your unpaid hours. Super is a cousin.",
    "If you own it, money out is profit. Draws are a celebration.",
    "Line: revenue, costs including a market wage for the owner, then leftover. Then tax on the leftover as the law says.",
    "A side hustle that ‘made $8k’ with 400 hours is $20/h before tax and the kettle. Hours are a cost."],
  ["vx-b-fx-risk", "Money", "A bill in USD is a bet on the dollar as well as on the goods",
    "Invoice today, pay in 60 days, the AUD moves. Hedge is a later tool. A ‘cheap’ import can get expensive in the wait.",
    "The price on the website is the price you pay later. Screens are contracts.",
    "Quote the currency, the date you must pay, and a 10% move. Then who holds the risk in the contract.",
    "A café importing cups in USD is this. A local potter is not, unless their glaze is."],
  ["vx-b-inflation-price", "Money", "Inflation is a silent rewrite of last year’s $10",
    "A 5% general rise means your ‘same’ price is a cut in real terms. Menu costs of changing stickers. CPI is a basket with politics.",
    "If the number on the tag is the same, the price is the same. Digits are value.",
    "Index a contract or review a menu with CPI as a prompt, not a religion. Then who cannot pass it on.",
    "A $3 sausage at the footy in 2006 is not a $3 sausage now. Nostalgia is not a cost base."],
  ["vx-b-sunk-ignore", "Money", "A sunk cost is gone; decide on the future cash only",
    "The fit-out you already paid does not make the next year a good year. ‘We have to keep going because of what we spent’ is a trap with a van.",
    "Finish what you started or the money was wasted. Waste is a moral, not a forecast.",
    "Write only future inflows and outflows. Then a pride check. Then kill or pivot.",
    "A degree is a sunk cost if you are choosing a job now. The next year of fees is not sunk."],
  ["vx-b-opp-cost-time", "Money", "Opportunity cost is the path you did not walk, including your Saturday",
    "A free ticket is not free if you skip a shift. A cheap lease in a dead mall costs the lease you did not take on a busy street.",
    "If no cash leaves, there is no cost. Cash is the only account.",
    "Name the next-best alternative in dollars or hours. Then choose with eyes open.",
    "A school stall that ‘makes $200’ with 12 parent hours is a $16/h story before anyone ate the leftover cake."],
  ["vx-b-unit-econ", "Money", "Unit economics is one more customer, zoomed in, with the cost of getting them",
    "Contribution minus a share of acquisition (ads, time). A ‘we lose money on each cup but make it up in volume’ needs a very good sequel.",
    "If the average is fine the unit is fine. Averages hide a poisonous SKU.",
    "Pick one unit (a cup, a job, a seat). Then variable, then CAC, then whether it is repeat.",
    "A delivery app that takes 30% can flip a 40% gross into a shrug. The unit is the meal after the take."],
  ["vx-b-cash-cycle", "Money", "The cash conversion cycle is stock plus debtors minus creditors, in days",
    "Buy, sit, sell, wait, pay. A supermarket with negative cycle (sell before pay) is a float. A builder is often the opposite.",
    "Faster sales always mean faster cash. Sales are cash.",
    "Estimate days inventory, days receivable, days payable. Then a lever (deposit, consignment, shorter terms).",
    "A florist before Mother’s Day is a stock spike. The cycle has a season."],
  ["vx-b-mvp", "Enterprise", "An MVP is a smallest test of the risky assumption, not a crappy version of the dream",
    "If the risk is ‘will they pay’, a landing page with a buy button can be the MVP. A half-built app with no ask is a hobby.",
    "MVP means ship whatever is in the folder on Friday. Folders are products.",
    "Name the riskiest assumption. Then the cheapest test. Then a kill criterion.",
    "A school canteen ‘pre-order 20 rolls by Wednesday or we do not bake’ is an MVP. The bake is the expensive bit."],
  ["vx-b-segment", "Enterprise", "A segment is a group with a shared why, not an age bracket you liked",
    "Busy parents vs backpackers vs offices. A ‘everyone’ product is a blur. Personas are cartoons; buy reasons are data.",
    "If they have a pulse they are the segment. Pulse is a TAM.",
    "Interview five. Cluster the jobs-to-be-done. Then a message that would annoy the other cluster.",
    "A $4 coffee and a $7 oat-milk pour-over can be two segments in one shop. The menu is a map."],
  ["vx-b-tam-sam", "Enterprise", "TAM is a dream market; SAM is the bit you can serve; SOM is the bit you might get",
    "A slide with a $40bn TAM and no SAM is a fundraise costume. Bottom-up (how many customers × price) beats a Wikipedia top-down for a stall.",
    "If the industry is big we will get 1% and be rich. 1% is a plan.",
    "Write bottom-up. Then a reason the 1% would be you. Then a year-1 SOM that is embarrassing and honest.",
    "A suburb of 4000 houses and a mowing service is a SAM you can walk. A ‘global outdoor’ TAM is a poster."],
  ["vx-b-moat", "Enterprise", "A moat is a reason a copycat still loses next year",
    "Brand, network, a licence, switching costs, a secret process. A pretty logo is not a moat. A government contract can be.",
    "If we were first we have a moat. Timing is a castle.",
    "Name the barrier in a sentence a rival would hate. Then how it decays. Then do not call a discount a moat.",
    "A café on a corner with a 10-year lease and a habit crowd has a small moat. A café in a food court with a 6-month pop-up does not."],
  ["vx-b-channel", "Enterprise", "A channel is how the product physically (or digitally) reaches the buyer",
    "Retail, wholesale, marketplace, direct. Each takes a cut and a rule. ‘We will go viral’ is not a channel.",
    "If it is on Instagram it is distributed. Followers are logistics.",
    "Pick one channel, map the cut, map the power (who can delist you). Then a second as a hedge.",
    "A brand that lives only on one marketplace is a tenant. The landlord sets the rent (ads)."],
  ["vx-b-pricing-power", "Enterprise", "Pricing power is whether you can raise the tag without a stampede out",
    "A commodity milk vs a named bakery. Switching cost, uniqueness, a habit. A discount war is an admission.",
    "Lower price always wins. Buyers are calculators with no story.",
    "Test a small rise on a segment. Then watch churn. Then a version (good/better/best) instead of a race to the floor.",
    "A tradie’s call-out fee is pricing power at 7 pm. The same job at 11 am is a different tag."],
  ["vx-b-pivot", "Enterprise", "A pivot is a change of hypothesis, not a rebrand sticker",
    "Same team, new customer or new job-to-be-done. A ‘pivot’ every week is a panic. Evidence should force it.",
    "Pivoting means you failed. Real firms never change their first idea.",
    "Write the old hypothesis, the evidence, the new one. Then what you keep (code, list, skill).",
    "YouTube began as a dating idea in the folklore. The lesson is evidence, not ‘be YouTube’."],
  ["vx-b-network-effect", "Enterprise", "A network effect is when more users make the product more valuable to the next user",
    "A marketplace with buyers and sellers. A chat app. The cold start is the pain (nobody is there). A brand with no interaction is not a network effect.",
    "If it is an app it has network effects. Apps are magic.",
    "Ask: does a new user help old users? Then the cold-start plan. Then a chicken-and-egg (subsidise one side).",
    "A school buy-swap-sell group is a network. A brochure PDF is not."],
  ["vx-b-switch-cost", "Enterprise", "Switching cost is the pain of leaving, not the price of the rival",
    "Data lock-in, a learned workflow, a contract, a ‘everyone here uses it’. High switching cost can be a moat or a hostage situation (regulation may care).",
    "If the other thing is cheaper they will switch tomorrow. Price is the only friction.",
    "List the pains of leaving. Then whether you earned them (value) or trapped them (hate). Then a port-out as a kindness that can still be a strategy.",
    "A accounting file in a proprietary format is a switching cost. CSV export is a political button."],
  ["vx-b-brand-promise", "Enterprise", "A brand is a promise people can repeat, not a colour palette",
    "On time, not fancy. Cheap and cheerful. Premium quiet. If the operations cannot keep the promise, the logo is a liar.",
    "A new logo is a new brand. Design is trust.",
    "Write the promise in seven words. Then a delivery that would break it. Then the colour as a last hat.",
    "Australia Post’s promise is a logistics. A sticker of a kangaroo is a costume if the parcel is late."],
  ["vx-b-quality-fit", "Enterprise", "Quality is fitness for the promise, not a marble bench in a $4 shop",
    "A food-truck bun that holds is quality. Gold leaf on a sausage is a mismatch. ISO is a system; a taste is a spec.",
    "More expensive inputs are more quality. Cost is a certificate.",
    "Write the spec the customer actually uses. Then a test. Then do not gold-plate a disposable.",
    "A $12 sandwich that falls apart is a quality fail. A $6 one that holds is a hit for that promise."],
  ["vx-b-supply-lag", "Enterprise", "A supply chain is a lag: order now, arrive later, pay a bullwhip",
    "A small change in shop sales can whip the factory. Buffer stock vs lean. A single supplier is a chokepoint.",
    "If I ordered it, it exists. Purchase orders are physics.",
    "Map lead times. Then a second source for the critical bit. Then a forecast that is a range.",
    "Toilet paper in 2020 was a bullwhip plus a rumour. The factory was not a rumour."],
  ["vx-b-franchise", "Enterprise", "A franchise is a rented business system with a rulebook and a fee",
    "Brand, process, a territory, royalties. You own the entity, not the recipe. A ‘business in a box’ still needs local labour law.",
    "If the logo is famous you cannot fail. Logos are cashflow.",
    "Read the disclosure. Then the fees. Then what you cannot change (menu, hours). Then a territory fight.",
    "A food franchise in a dying mall is still a lease plus a royalty. Two landlords."],
  ["vx-b-nfp-econ", "Enterprise", "A not-for-profit still has economics: surplus, mission, and a grant that ends",
    "No shareholders, still wages, still rent. A surplus is allowed and often wise. Mission drift toward the grant is a trap.",
    "If it is NFP it cannot think about money. Virtue is a P&L.",
    "Write mission, then a unit cost of the service, then what happens if the grant dies. Then volunteers as a cost (training, burnout) not only a gift.",
    "A community op-shop is a retail business with a mission overlay. The overlay does not pay the power bill by itself."],
  ["vx-b-online-logistics", "Enterprise", "A web storefront is still a pick-pack-and-returns job",
    "Pick, pack, returns, a carrier, a false ‘in stock’. The website is the shopfront; the garage is the shop.",
    "If the click is pretty the parcel arrives. UX is a truck.",
    "Map the pick-path and the return rate. Then a shipping price that is honest. Then a delay message before the customer tweets.",
    "A ‘free shipping’ that is baked into a higher tag is a price, not a gift. Say it."],
  ["vx-b-award-floor", "Work", "An award is a floor of pay and conditions, not a rumour in the tearoom",
    "Classifications, breaks, penalty rates. A handshake below the award is not a vibe, it is a breach. Some roles are award-free — check, do not assume.",
    "If they agreed to $10/h it is fine. Consent deletes the law.",
    "Find the award, the level, the hours. Then super on top. Then a record. Then do not cash-in-hand a junior ‘because they asked’.",
    "A Sunday café shift is often a penalty story. The till being quiet is not a legal discount."],
  ["vx-b-super-not-bonus", "Work", "Super on a pay slip is not a bonus lollipop; it is a delayed wage with a cage",
    "SG percent, a fund, preservation. Salary-sacrifice is a different lever. Unpaid super is a debt with a regulator.",
    "Super is a gift from a kind boss. Gifts can wait.",
    "Check the percent, the fund, the date it actually left. Then a choice of fund if you have one. Then do not treat it as optional cash.",
    "A ‘higher wage instead of super’ deal is often illegal. The cage exists because future-you is a stranger."],
  ["vx-b-resume-evidence", "Work", "A resume is evidence, not a pile of adjectives",
    "Led a stall that took $4k in a day vs ‘passionate leader’. Numbers, names of tools, a result. A photo is a house-style fight (AU often skip).",
    "If the font is fancy the experience is fancy. Typography is a career.",
    "Bullet: verb, object, outcome. Then a referee who will actually pick up. Then one page unless they asked for more.",
    "A school captain line without a thing you ran is a title. Titles are not evidence."],
  ["vx-b-interview-two", "Work", "An interview is two-way evidence: they sample you, you sample the job",
    "STAR stories, a question about the worst week, a pay band. A firm that will not say the band may still be fine — or a fog. You can leave.",
    "If they like you, you must say yes. Liking is a contract.",
    "Prepare two stories and two questions about the work. Then a note the same day. Then a walk-away number.",
    "A panel that only talks about ‘culture’ and never about the tasks is a data point. Tasks are the job."],
  ["vx-b-feedback-work", "Work", "Feedback is specific and changeable, not ‘be more professional’ as a weather",
    "One behaviour, one example, a next time. Praise that names the thing is a cousin. A sandwich of fake praise is a smell.",
    "If it is uncomfortable it is feedback. Pain is a method.",
    "Write the example. Ask if they can do it next week. Then follow up. Then do not do it in the corridor as a power play if a quiet room was possible.",
    "A ‘you’re too quiet in meetings’ without a meeting name is unusable. Tape a moment (ethically) in your notes."],
  ["vx-b-whs-system", "Work", "WHS is a system of identify, control, review — not a laminated poster of a skeleton",
    "Duty of care, a risk matrix as a cartoon, consultation. A ‘she’ll be right’ on a ladder is a statement to a court later.",
    "If nobody has died the system works. Absence of a funeral is a KPI.",
    "Spot the hazard, pick a control (eliminate, then PPE last), write it, train it. Then a near-miss as a gift.",
    "A café fryer, a wet floor, a 14-year-old on a close is a WHS story. Age is a control."],
  ["vx-b-contract-words", "Work", "A contract is the words, not the handshake feeling, and not the manager’s later memory",
    "Offer, acceptance, consideration in the cartoon. Unfair terms. A casual vs permanent is a set of words with Super and leave attached.",
    "If we both meant well the contract will flex. Meaning is a clause.",
    "Read the hours, the notice, the IP, the restraint. Then a question before you sign. Then keep a copy.",
    "A ‘restraint of trade’ that bans a barista from any café in Australia is a fight. Reasonable is a legal word."],
  ["vx-b-team-friction", "Work", "A team has a task and a friction: conflict can be about the work or about the person",
    "Task conflict can help. Personal conflict is a tax. A meeting without a decision is a ritual. Psychological safety is a research word with a practical test (can you say ‘I don’t know’).",
    "If we are nice we are productive. Niceness is output.",
    "Name the task, the owner, the date. Then a disagreement on the work in the room, not in a side chat that becomes a court.",
    "A group assignment with one name on the repo and three on the cover is a team fiction. Git is evidence."],
  ["vx-b-dodgy-request", "Work", "A dodgy request is still your name: cash jobs, a lie to a customer, a forged timesheet",
    "You can say no. A job is not a hostage. Document, then a regulator or a trusted adult if it is serious.",
    "If the boss said it, it is fine. Hierarchy is a defence.",
    "Pause. Repeat the request in plain words. Then refuse the illegal bit. Then do not joke it into a group chat as if that were a policy.",
    "A ‘don’t put this through the till’ is a GST and a theft story. The till is a legal machine."],
  ["vx-b-gig-risk", "Work", "A gig is a job with the risk shifted onto you: no leave, a rating, a platform rule",
    "Contractor vs employee is a legal test, not a app label. Super, insurance, a broken bike. The flexibility is real and so is the shift.",
    "If the app says partner you are a small business in a castle. Words on a screen are a court.",
    "Read the pay after costs (time, vehicle, waiting). Then a classification. Then a union or a case if it smells like a job.",
    "A delivery in the rain at $6 after petrol is a unit-economic of a person. People are not vans."],
  ["vx-b-min-wage", "Work", "A minimum wage is a floor with models of trade-offs, not a vibe of ‘jobs will vanish’ as a complete theory",
    "Award rates, junior rates, a Fair Work number. Some models say unemployment; some say demand. Evidence is mixed and local. The floor is still the law.",
    "Economics 101 on a whiteboard cancels the award. Diagrams are legislation.",
    "Find the actual rate for the age and job. Then pay it. Then argue policy in a different hat, not at 10 pm on a till.",
    "A trial shift that is unpaid is often a breach, not a ‘look around’. Trials have rules."],
  ["vx-b-ip-at-work", "Work", "IP you make in the job may not be yours; the contract said so",
    "Copyright default vs an employment clause. A design, a photo, a bit of code. A school assignment is a different (still messy) story.",
    "If I made it I own it. Making is title.",
    "Read the IP clause. Then do not use the company’s photo in your folio without a yes. Then a personal project on a personal machine if you mean personal.",
    "A barista’s latte art is rarely a lawsuit. A designer’s logo for the shop is. Scale of the artefact."],
  ["vx-b-leave-loading", "Work", "Annual leave is a rest with a loading in some awards, not a favour",
    "Four weeks as a common floor, loading as a Christmas-shaped extra in some instruments. Casual loading is a different swap (no leave, extra percent).",
    "Leave is when it is quiet. The roster is the Act.",
    "Check the instrument. Then book, then a handover. Then do not ‘cash out’ because a manager is stressed unless the rules allow.",
    "A hospitality Christmas is when loading and penalty stack. Read both lines."],
  ["vx-b-reference", "Work", "A referee is a person who will pick up, not a celebrity who met you once",
    "Ask first. Brief them on the job. A LinkedIn ‘open to’ is not a reference. A teacher who saw the work beats an uncle who saw the birth.",
    "More referees are more proof. Volume is character.",
    "Two people who saw you work. Then a warning if you only have one. Then do not invent a title for them.",
    "A ‘please do not contact my current boss’ is a common real constraint. A good process can work with it."],
  ["vx-b-demand-curve", "Markets", "A demand curve slopes down, with exceptions you should not worship yet",
    "Higher price, less quantity demanded, holding other things. Giffen/Veblen are later rarities. A shift of the curve is not a move along it (income, tastes, a rival).",
    "If it is popular the demand curve slopes up. Popularity is a slope.",
    "Separate a price change (along) from a news shock (shift). Then ceteris paribus as a cartoon.",
    "A concert ticket that is more desired when expensive is a snob/Veblen maybe. Most milk is not."],
  ["vx-b-supply-curve", "Markets", "Supply is a willingness to sell at a price, not a warehouse photograph",
    "Higher price, more quantity supplied, usually. A drought shifts food supply. A tax can too. Short run vs long run (can we build another factory).",
    "If we have stock we will sell at any price. Stock is supply.",
    "Ask what it costs to make one more. Then a shifter (input prices, technology). Then do not mix with ‘we feel generous’.",
    "A baker at 4 am has a capacity. Extra bread at 2 pm is a different cost (stale, staff). Time is a supply story."],
  ["vx-b-shift-vs-along", "Markets", "A move along is a price change; a shift is a different world",
    "A heatwave shifts ice-cream demand. A price cut moves along. Mixing these is how a Year 11 paragraph dies.",
    "If the line moved, price caused it. Lines are prices.",
    "Name the other-thing that changed. Then redraw. Then the new equilibrium as a pair (P, Q).",
    "A GST change is a supply-ish tax story. A celebrity eating your pie is a demand shift."],
  ["vx-b-elasticity", "Markets", "Elasticity is a percent-response, not ‘people care’ as a mood",
    "Price-elastic: quantity jumps a lot. Inelastic: insulin, a peak-hour commute with no train. Revenue = P×Q lives here.",
    "If it is a need it is inelastic always, even if there are five brands. Need is a number.",
    "Compute %ΔQ / %ΔP with the midpoint if you are being careful. Then a revenue test: a rise in P on inelastic can lift revenue.",
    "A 10% coffee rise that loses 2% of cups is inelastic-ish. A 10% rise that loses 40% is a different shop."],
  ["vx-b-market-structure", "Markets", "Count the rivals and the stuckness, then name the structure",
    "Perfect competition cartoon, monopoly, oligopoly, monopolistic (many, differentiated). A café street is often the last. Collusion is a later illegal cousin.",
    "If there are two shops it is a monopoly of two. Two is one.",
    "Count the rivals, the differentiation, the barriers. Then a price you could not get away with in a commodity.",
    "A country-town servo is an oligopoly of two with a 40 km moat. Google Maps is not a third pump."],
  ["vx-b-externality", "Markets", "An externality is a bill someone else pays: smoke, bees, a noisy gig",
    "Negative: factory on a river. Positive: a vaccine, a pretty garden. Markets under-provide the good ones and over-provide the bad unless a rule or a price (tax, tradable permit) shows up.",
    "If it is not on the invoice it is not economics. Invoices are the universe.",
    "Name the third party, the harm or gift, then a tool (ban, tax, subsidy, Coase bargain if that is the cartoon).",
    "A late-night venue next to a new apartment is a classic. The apartment bought the view and the bass."],
  ["vx-b-public-good", "Markets", "A public good is non-rival and non-excludable, in the jargon — fireworks, a bit of defence, a clean street with an asterisk",
    "A sandwich is rival. A streaming login that you can share is a fight about excludable. Free-riders appear when you cannot exclude.",
    "If the government does it, it is a public good. Who pays is the definition.",
    "Test rival (does my use leave less) and exclude (can we fence it). Then a funding story.",
    "A lighthouse is the textbook. A congested road is not non-rival. Peak hour is a club good with a tantrum."],
  ["vx-b-asymmetric", "Markets", "One side knows more: lemons, doctors, a used van",
    "Akerlof’s lemons: bad vans drive out good if you cannot tell. Warranties, brands, licences are signals. A review can be a lie.",
    "If both signed, both knew. Signatures are knowledge.",
    "Ask who has the hidden fact. Then a device that shares it (inspection, a statutory warranty). Then still a leftover risk.",
    "A ‘no refunds’ on a $5 sausage is different to a $30k car. ACL still sits under a lot of this in Australia."],
  ["vx-b-trade-specialise", "Markets", "Comparative advantage is opportunity cost, not ‘best at everything’",
    "Comparative advantage is opportunity cost, not ‘who is best at everything’. A tariff is a tax on the import with a local winner and a consumer loser. Adjustment is the political word for a town that loses the factory.",
    "Trade is always win-win for every person. Models have no towns.",
    "Name the specialisation, the cheaper good, and who is hurt. Then a policy (retraining, a slow tariff cut) as a separate hat.",
    "A TCF factory in the 1990s is Australian evidence. Cheaper clothes and a closed mill can be both true."],
  ["vx-b-exchange-aud", "Markets", "A dollar buys a different pile of yen tomorrow; firms ride that",
    "Float, a rate as a price of money. Exporters like a weaker AUD in the cartoon; importers the opposite. RBA is a later hat.",
    "The rate is set by fairness. Banks are moral.",
    "Pick an importer or exporter. Then a 10% move. Then who can hedge. Then do not treat the rate as a patriotic score.",
    "A 2011 high AUD hurt manufacturers and cheapened a Gap trip. Same rate, two stories."],
  ["vx-b-bank-risk", "Markets", "A bank is a risk machine with a licence: borrow short, lend long",
    "Deposits out tomorrow, loans back in years. Liquidity vs solvency. A run is a coordination. Guarantee talk is a political patch.",
    "Banks store money in a box with your name on it. Boxes are loans.",
    "Write the mismatch. Then a capital buffer as a shock absorber. Then why a licence is a civic.",
    "A credit union is a cousin. A payday lender is a different, sharper machine."],
  ["vx-b-insurance-pool", "Markets", "Insurance is a pooled bet against a bad day, with a moral hazard and a adverse selection",
    "Premiums, excess, a flood map. If only the risky buy, the pool sickens (selection). If insured, you might be careless (hazard). Excess and exclusions are tools.",
    "If I paid I am covered for everything. Premiums are a hug.",
    "Read the PDS. Then the flood overlay. Then do not assume ‘storm’ and ‘flood’ are twins.",
    "A business interruption policy is a sequel after a fire. The wording is the product."],
  ["vx-b-cpi-basket", "Markets", "CPI is a basket with politics in the recipe: whose rent, whose steak",
    "Weights, a substitution, a quality change (a phone that is ‘the same’ but better). Indexed wages and pensions ride it. It is not ‘your inflation’.",
    "If my shopping hurt, CPI is wrong. My trolley is the method.",
    "Read what is in. Then a rise that is ‘volatile items’ vs trimmed mean as a RBA cousin. Then a contract that uses which index.",
    "A 20% tomato spike and a 0% telco can average into a number that makes nobody happy. Averages hide trolleys."],
  ["vx-b-share-vs-bond", "Markets", "A share is a slice of leftover; a bond is a promise of cash with a rank",
    "Equity vs debt. A bondholder is in the queue before the shareholder in a wreck (usually). Dividends are not a law. Interest on a bond is.",
    "Shares are safer because you own. Ownership is a cushion.",
    "Name residual vs contractual. Then risk and expected return as a pair. Then a super fund as a mix.",
    "A start-up share is a lottery ticket with a job. A government bond is a yawn with a rate. Both are ‘investing’."],
  ["vx-b-oligopoly-game", "Markets", "An oligopoly is a small club that watches each other: a price you copy by 4 pm",
    "Petrol boards, airline seats, a supermarket special that is matched. Game cartoons (prisoner’s dilemma) are a later hat. Collusion is illegal; parallel pricing can be a smell or a market.",
    "If prices match it is always a cartel. Matching is a confession.",
    "Count the firms, the matching speed, the barrier. Then a ACCC story if you have one. Then do not accuse from a Year 11 graph alone.",
    "A 7 pm petrol price jump is a data set people fight over. Time of day is a strategy."],
  ["vx-b-gst-invoice", "Tax & records", "GST is 10% in Australia with a tax invoice as a ticket to claim credits",
    "If you are registered, you collect and you credit. A missing tax invoice is a missing credit. Some foods are GST-free — the rule is a list, not a vibe of ‘healthy’.",
    "GST is a shop tax on everything equally. Stickers are the Act.",
    "Register when you must (or choose to). Then a tax invoice with the right fields. Then a BAS. Then do not keep the GST as a birthday.",
    "A $22 meal with GST included is $2 tax, not $2.20. Inclusive vs plus is a divide by 1.1."],
  ["vx-b-abn", "Tax & records", "An ABN is an identifier, not a personality and not a visa to skip the award",
    "Look it up, a GST status, a name. Sham contracting is using an ABN as a costume on a job that is employment. The number does not decide the test.",
    "If they have an ABN they are a business so no super, no leave, no award. Numbers are a classification.",
    "Check the ABN. Then the working pattern (control, hours, tools). Then pay the right way. Then do not demand an ABN of a kid for a one-off cash job as a ritual.",
    "A 16-year-old with an ABN on a Saturday shift is a red flag, not a entrepreneur origin story by default."],
  ["vx-b-bas", "Tax & records", "A BAS is a periodic GST (and more) report, not a novel",
    "Cash vs accrual can be a choice for small. Deadlines. A correction. The ATO is a creditor with a personality.",
    "If you were busy you can skip a BAS. Busy is an extension.",
    "Keep the invoices, pick the method, file on time. Then a software that matches the bank. Then a human if it is a mess.",
    "A quarterly surprise because you spent the GST is the classic. A separate account is a cheap control."],
  ["vx-b-record-7", "Tax & records", "If it is not recorded it did not happen — for the ATO and for you",
    "Invoices, receipts, a logbook. Five years is a common keep. A shoebox is a system only if you can find March.",
    "Memory is a ledger. The auditor will vibe with you.",
    "Photo, date, why. Then a folder. Then do not ‘round’ a cash till as a lifestyle.",
    "A lost receipt on a $8 coffee is a shrug. A lost receipt on a $8k machine is a different shrug."],
  ["vx-b-acl-consumer", "Tax & records", "Australian Consumer Law is a floor of promises: fit for purpose, as described, a refund path",
    "A sign ‘no refunds’ cannot eat the ACL on a faulty good. A change-of-mind may be shop policy, not the Act. Services have a due care.",
    "If you signed no-refund it is gone. Signatures eat statutes.",
    "Name the guarantee, the problem, the remedy (repair, replace, refund) as appropriate. Then the ACCC or a state office if you are stuck. Then keep the proof of purchase.",
    "A $20 blender that lasts 20 minutes is a fit-for-purpose fight. A $20 blender you decided you dislike on Tuesday may not be."],
  ["vx-b-fake-invoice", "Tax & records", "A fake invoice is a genre: a bill for a directory you never bought",
    "Urgency, a almost-ATO letterhead, a ‘renew your listing’. A real supplier has a PO trail. Slow is a control.",
    "If it has an ABN it is real. ABNs are a hologram.",
    "Check the PO, the known email, the ABN name match. Then a phone number you looked up, not the one on the fake. Then report.",
    "A ‘yellow pages’ leftover scam is still in inboxes. So is a fake BAS. Two genres."],
  ["vx-b-payg", "Tax & records", "PAYG withholding is taking tax as you earn, not a bonus the boss keeps",
    "A tax file number, a scale, a payment summary / income statement. Too little withheld is a June surprise. A contractor with a voluntary withholding is a cousin.",
    "If it is withheld it is extra cost on the wage. The boss invented it.",
    "Check the income statement in myGov. Then a return. Then a Medicare levy as a line that surprises people.",
    "A second job without a tax adjustment is how you under-withhold. The scale assumed one job."],
  ["vx-b-company-vs-sole", "Tax & records", "A company is a separate person in law; a sole trader is you with a trading name",
    "Limited liability is a legal technology with a veil that courts can still lift if you play games. ABN vs ACN. Tax rates differ. Paperwork differs.",
    "If the logo has Pty Ltd you cannot be sued. Letters are a force field.",
    "Pick the structure for risk, tax, and investors — with advice, not a TikTok. Then keep the money separate. Then do not pay the grocery from the company without a trail.",
    "A Pty Ltd that is you wearing a hat still needs minutes and a bank account that is not your holiday fund."],
  ["vx-b-audit-trail", "Tax & records", "An audit trail is who did what to a number, not a vibe of honesty",
    "User, time, a reversal not a delete. Till voids. A ‘fix’ that erases history is a smell. POS systems that allow silent voids are a control fail.",
    "If we trust the staff we do not need a trail. Trust is a control.",
    "Log voids, separate the cashier and the count, then a surprise till check. Then do not share logins.",
    "A $50 void at 21:58 every Friday is a pattern. Patterns are why trails exist."],
  ["vx-b-stocktake", "Tax & records", "A stocktake is a count that makes COGS honest",
    "Opening plus purchases minus closing = what left. Shrink (theft, rot, a mis-pick) hides in the gap. Cycle counts vs a yearly panic.",
    "The computer quantity is the stock. Software cannot rot.",
    "Count, then explain the gap, then a control (camera, a lock, a recipe). Then do not eat the gap as ‘free staff meals’ without a record if you meant a meal policy.",
    "A bottle shop’s shrinkage is a different rate to a bookshop. Category is a clue."],
  ["vx-b-job-cost", "Tax & records", "A job card is labour plus materials plus a share of overhead, or you are guessing the quote",
    "Hours, a parts list, travel. Underquoting is a marketing that eats the wage. Variations are a written extra, not a smile.",
    "If the quote felt right it was right. Feelings are a ledger.",
    "Track actual vs quote on one job. Then a rate that includes the dead time. Then a variation in writing before you do it.",
    "A bathroom reno that ‘found asbestos’ is a variation. A handshake to ‘just finish it’ is how a margin dies."],
  ["vx-b-break-even-tax", "Tax & records", "Break-even in units ignores tax and GST costumes unless you put them in",
    "Fixed / contribution per unit. GST-inclusive prices need a net contribution. Tax on profit is after break-even in the simple model — say so.",
    "Break-even is when the till equals the rent. One number, done.",
    "Use net prices, a honest contribution, then a sentence about tax. Then a sensitivity on volume.",
    "A 10% GST-inclusive café cannot use the sticker price as contribution without a 1/11 haircut. The haircut is the tax."],
  ["vx-b-privacy-customer", "Tax & records", "A customer list is personal information with a APP-shaped duty",
    "Emails, a kids’ party booking, a health note on a regular. Do not sell the list as a side hustle. A breach is a report in some cases.",
    "If they bought a muffin they are marketing property. Muffins are consent.",
    "Collect less, say why, keep it locked, delete when done. Then do not put the list on a USB in a van.",
    "A café Wi-Fi ‘login with marketing yes ticked’ is a consent design. Pre-ticked is a smell."],
  ["vx-b-director-duty", "Tax & records", "A director has duties to the company, not a licence to mix the holiday",
    "Care, good faith, not trading while insolvent as a cartoon. A signature on a guarantee is personal. Advice is cheaper than a courtroom.",
    "Pty Ltd means the company did it, always. Veils are magic.",
    "Keep books, do not pay yourself ahead of a sinking ship as a first move, get advice early. Then a minute that you did.",
    "A ‘phoenix’ that leaves wages in the wreck is a story ASIC knows. Wages are not a vibe."],
  ["vx-b-kanban-stock", "Enterprise", "A kanban or a par level is a visual ‘make more’ without a novel",
    "An empty bin that means reorder. Too much stock is cash in a box. Too little is a 86’d menu. Restaurants live here.",
    "If the fridge looks full you are fine. Volume is a system.",
    "Set a min/max on the critical SKU. Then a count. Then a supplier who actually arrives on Tuesday.",
    "A milk par for a Monday vs a public-holiday Monday is two numbers. Calendars are demand."],
  ["vx-b-seasonality", "Enterprise", "A seasonal business is a year with a peak and a quiet that still has rent",
    "Ice-cream winter, tax agents in July, a beach kiosk. Cash in the peak must fund the trough. A annual profit can hide a January death.",
    "If the year totals fine, every month is fine. Years are months.",
    "Draw twelve bars. Then a cash buffer. Then a second product for the trough (or a real closed season).",
    "A ski hire in Australia is a short peak. Diversifying into bikes is a textbook sequel."],
  ["vx-b-customer-ltv", "Enterprise", "Lifetime value is the leftover from a customer over years, minus the cost to keep them",
    "A café regular vs a tourist. Churn kills LTV. A loyalty card is a cost. CAC < LTV is the cartoon, with a discount rate if you are being fancy.",
    "If they came once they will come forever. First purchase is a marriage.",
    "Estimate repeat, contribution, a retention. Then do not spend $50 of ads to get a $4 one-off sandwich without a sequel.",
    "A gym that sells 12-month prepaid is pulling LTV into today. That is cashflow, not magic profit."],
  ["vx-b-b2b-vs-b2c", "Enterprise", "B2B is a committee and a PO; B2C is a person and a feeling",
    "Longer sales, a spec, a procurement rule. A school canteen is B2C with a B2B supplier behind. Mixing the pitch is a miss.",
    "A business buyer is just a consumer in a shirt. Shirts are a segment.",
    "Name the decision-maker, the user, the budget cycle. Then a case study not a vibe. Then a different website.",
    "Selling coffee machines to cafés is B2B. Selling cups to pedestrians is B2C. Same bean company can do both with two teams."],
  ["vx-b-onboarding", "Work", "Onboarding is a system: keys, till, allergy, a buddy — not ‘figure it out, they look keen’",
    "A first shift without a login is a labour cost and a WHS hole. Checklists beat charisma. Probation is a legal window, not a vibe of maybe.",
    "Good people do not need induction. Talent is a download.",
    "Write day-1, day-7, day-30. Then a named buddy. Then a till that is not the owner’s birthday PIN.",
    "A 15-year-old’s first café shift needs a supervisor in eyesight, not a ‘you’ll be right’ on the espresso."],
  ["vx-b-roster-fair", "Work", "A roster is a fairness machine: notice, a preference, a clopen",
    "A close then open is a clopen. Unpredictable hours smash study and care. Some awards want notice. Flexibility is a two-way word.",
    "If the shop is busy the roster can drop at 9 pm. Commerce is a siren.",
    "Publish with notice, cap clopens, then a swap process that is not a panic text. Then do not punish a no to an extra.",
    "A student with an exam on Thursday cannot be the 6 am Friday. School is a constraint the roster can honour."],
  ["vx-b-union-role", "Work", "A union is a collective bargain plus a service, not a personality type",
    "Awards often began as bargains. Right to join. A fee. A strike is a last legal tool with rules. Right-to-work talk from elsewhere is a different legal planet.",
    "Unions are for factories in 1950. Apps cannot union.",
    "Know what the union covers in that workplace. Then a delegate. Then a bargain vs the award floor.",
    "A hospitality union meeting in a break room is a civic of work. So is a boss who ‘doesn’t like unions’ as a hiring filter — that filter can be a problem."],
  ["vx-b-perf-review", "Work", "A performance review is evidence plus a next, not a once-a-year ambush",
    "If the first time you hear a problem is the form, the system failed. Goals that were never resourced are a trap. Pay links need a transparent rule.",
    "A review is a feeling about the person. Vibes are KPIs.",
    "Write the goal in January, evidence in June, no surprises. Then a development that is a course or a load change, not a poster.",
    "A 360 that is only the loudest peer is a popularity contest. Sampling is a method."],
  ["vx-b-price-disc", "Markets", "Price discrimination is charging different people different tags for a reason that sticks",
    "Student, senior, a 2 pm cinema, a yield-managed seat. Need a fence (ID, time) or they all buy the cheap. Not always illegal; some is just a menu.",
    "Different prices are always unfair so always banned. Fairness is a statute of equal stickers.",
    "Name the fence, the different willingness to pay, and a law check (race as a fence is a different, illegal planet). Then a time fence as the usual legal one.",
    "A haircut that costs more at noon Saturday is a peak. A haircut that costs more because of hair texture can be a discrimination fight. Do not mix them."],
  ["vx-b-substitute", "Markets", "Substitutes raise each other’s demand when the other’s price rises",
    "Butter and margarine in the cartoon. Complements go together (printer and ink). Cross-price elasticity is the name. A ‘unique’ product still has a substitute at a distance (not buying).",
    "If they are next on the shelf they are substitutes. Shelf is a statistic.",
    "Ask: if A’s price jumps, does B’s quantity jump? Then a complement test (opposite). Then ‘do without’ as the hidden substitute.",
    "Oat milk is a substitute with a story, not a perfect one. The story is the differentiation."],
  ["vx-b-surplus", "Markets", "Consumer surplus is ‘would have paid more’; producer surplus is ‘would have sold for less’",
    "The triangle in the cartoon. A price ceiling can move surplus around and create a shortage. Deadweight is the missing trades.",
    "Surplus means leftover stock. Warehouses are the diagram.",
    "Sketch P, Q, the willingness. Then a tax wedge as a later hat. Then do not mix with ‘surplus stock in the back’.",
    "A concert you would have paid $200 for at $80 is surplus. Scalpers try to harvest it. Harvest is a market too."],
  ["vx-b-price-ceiling", "Markets", "A price ceiling below equilibrium is a shortage machine, with a queue or a black market",
    "Rent caps in the cartoon. A ceiling above eq does nothing. Quality can rot if the cap is tight. Who gets the cheap is a political queue.",
    "A max price always helps all buyers. Caps are kindness with no geometry.",
    "Draw eq, then the cap, then Qs vs Qd. Then who is lucky in the queue. Then a quality fade.",
    "A concert ‘$0 for mates’ is a cap of a kind. The queue is a friendship market."],
  ["vx-b-tfn-privacy", "Tax & records", "A TFN is a key, not a loyalty-card number to paste in a form because the form asked nicely",
    "Employers, super, the ATO. A random website is not. Identity theft starts with a kit (TFN plus DOB plus address).",
    "If the PDF has a box, fill it. Boxes are law.",
    "Give it to the people who are allowed. Then a myGov that is yours. Then do not photo it in a group chat.",
    "A café ‘onboarding pack’ that emails 40 TFNs to a gmail is an incident. Email is not a vault."],
  ["vx-b-fbt-car", "Tax & records", "Fringe benefits are non-cash pay with a tax costume: a car, a lunch, a cheap loan",
    "FBT is a separate tax in Australia with a year that is not June. Exemptions exist (some portable devices, some food). The ‘work car’ that is a school-run car is a smell.",
    "If it is not cash it is not taxed. Cash is the only income.",
    "Ask if it is a benefit, then the FBT rule, then a logbook. Then do not invent a 100% work van that does groceries.",
    "A Christmas hamper can be a minor exemption or a paperwork. Thresholds date — check the year."],
  ["vx-b-rd-offset", "Tax & records", "An R&D tax offset is a statutory machine, not a vibe of ‘we innovate’",
    "Eligible activity, records, a regulator (AusIndustry) plus the ATO. A café ‘new muffin’ is usually not R&D. Software can be, with a file.",
    "If we did something new we get the offset. New is a definition.",
    "Read the tests, keep contemporaneous notes, then advice. Then do not claim a website refresh as science.",
    "A fake R&D mill is a genre of advisor. If it sounds like a product, it might be a product."],
  ["vx-b-import-duty", "Tax & records", "Duty and GST on imports are a border price, not a surprise you can shrug",
    "A low-value threshold that moved. A broker. A landed cost is the true COGS. ‘But the website was $12’ is not a customs argument.",
    "If it is in the post it is GST-free because post. Stamps are a tax office.",
    "Quote landed: goods, freight, duty, GST, broker. Then a price. Then a delay as a service cost.",
    "A $1000 of shop fittings from overseas is a cashflow hit at the wharf. The container is not the last invoice."],
  ["vx-b-kpi-lag", "Enterprise", "A KPI can lag (profit last month) or lead (complaints this week)",
    "Steering on a lag only is driving by the rear-view. Vanity metrics (followers) vs a metric that changes a decision. Too many KPIs is none.",
    "If it is a number it is a KPI and therefore useful. Numbers are a strategy.",
    "Pick one lead and one lag for the week. Then a meeting that acts. Then kill the dashboard jewellery.",
    "A café’s same-store sales vs a TripAdvisor star. One pays the rent. One is a lagging costume of last month’s eggs."],
  ["vx-b-culture-ops", "Work", "Culture is what you reward on a Tuesday, not a values poster in reception",
    "Who gets the extra shift, who gets blamed, who can say no. A ‘family’ that skips overtime is a story. Hiring for ‘culture fit’ can be a clone machine.",
    "If the poster is pretty the culture is pretty. Laminate is a practice.",
    "Watch a decision under stress. Then a value that would have changed it. Then fire the poster or fire the practice.",
    "A ‘we’re a family’ that texts at 11 pm is a boundary. Families have mixed reviews as employers."],
  ["vx-b-whistle", "Work", "A whistleblower channel is a legal technology, not a suggestion box with a camera over it",
    "Protections exist in companies of a size, with a policy. Retaliation is the usual failure. A small shop still has a Fair Work and a WHS regulator.",
    "If you tell the boss’s friend it is protected. Friendship is a statute.",
    "Use the written channel or a regulator. Then keep copies. Then do not only Slack a joke.",
    "A food-safety lie that could hospitalise is a WHS/Food Act path, not only a ‘culture’ chat."],
  ["vx-b-advertising-law", "Markets", "An ad that is false is a ACL problem, not a ‘puffery’ get-out for a measured claim",
    "Puffery (‘best coffee in the universe’) vs a testable ‘50% less sugar’. Fine print that contradicts the headline is a smell. Influencers have disclosure rules.",
    "If it is an ad it is allowed to lie a bit. Commerce is theatre.",
    "Make the headline true. Then the asterisk true. Then a proof file. Then #ad where it is required.",
    "A ‘was $199 now $20’ that was never $199 is a was/now fight. The ACCC has a memory."],
  ["vx-b-tender", "Enterprise", "A tender is a scored essay with a price, not a vibe meeting",
    "Criteria, a deadline, a compliance matrix. Lowest price can lose on quality weighting. A late PDF is a zero.",
    "If they like you they will fix your late tender. Liking is a criterion.",
    "Map the criteria, write to them, price with a margin, submit early. Then a debrief if you lose.",
    "A school canteen tender is still a tender. Allergen process can outscore a cute logo."],
  ["vx-b-exit", "Enterprise", "An exit is a sale, a succession, or a close — not a mystery that happens to other people",
    "A buyer wants numbers, not a personality. A family succession is a tax and a fight. A close still has leave and a lease.",
    "If it is a small business it never sells. Only start-ups exit.",
    "Keep books a buyer could due-diligence. Then a lawyer. Then do not be the only person who knows the till PIN.",
    "A café sold as ‘walk in, walk out’ is stock plus a lease assignment. The coffee machine’s finance can still be attached."],
]);
