import { pack } from "../pack.mjs";

export const CIVICS_VOLUME = pack("civics", [
  ["vx-v-nat-justice", "Rules extras", "Natural justice is a hearing and an unbiased decision-maker, not a vibe of niceness",
    "Hear the person, no secret evidence they cannot answer, a decision-maker who is not already the accuser. Schools borrow the idea even when they are not a court. A pile-on in a group chat is the opposite machine.",
    "If we all know they did it, skip the hearing. Faster is fairer.",
    "Write the steps. Do not skip the one where they speak. Recuse a teacher who is also the witness if you can.",
    "A student leadership ‘trial’ with no right to speak is a civics defect wearing a badge."],
  ["vx-v-civil-criminal", "Rules extras", "Civil is a private fight about remedies; criminal is the state and a punishment",
    "Balance of probabilities versus beyond reasonable doubt. Same facts can be both files (a punch). A ‘they were found not guilty so it never happened’ is a category error about standards.",
    "Court is court. Guilty is the only word. Compensation is a synonym.",
    "Name the parties, the standard, the remedy. Then whether a second file is still open.",
    "A famous acquittal with a later civil payout is a two-standard lesson, not a conspiracy by itself."],
  ["vx-v-precedent", "Rules extras", "Precedent is a like-cases-like machine, not a photocopy of every old feeling",
    "Ratio versus obiter. A higher court binds a lower one in the same hierarchy. Distinguishing is a lawyer’s sport. Legislatures can still overwrite with a statute — slowly.",
    "If a case is old it is law forever. Also: if I dislike it I can ignore it. Two cartoons.",
    "Find the court level, the holding in a paragraph, a later statute that moved the goalposts.",
    "Mabo is a precedent story and a statute story after. Both matter."],
  ["vx-v-statute-common", "Rules extras", "A statute is parliament’s text; common law is a pile of judgments",
    "Judges interpret statutes; they do not (usually) invent a tax. Equity is a historical cousin with maxims. A ‘the judge made it up’ rant sometimes describes interpretation and sometimes describes a tantrum.",
    "All law is in one book with a crest. Google is that book.",
    "Ask: which act, which section, which case if any. Then who can change it (parliament vs appeal).",
    "A speed limit is a statute. A negligence duty can be a common-law tree with statute grafts."],
  ["vx-v-delegated-leg", "Rules extras", "Regulations are law made under an act, not a minister’s tweet",
    "Delegated legislation, a disallowance in the Senate sometimes, a regulation that is denser than the act. Democracy’s speed versus democracy’s attention span.",
    "If it is not in the Constitution it is not law. Regulations are optional homework.",
    "Open the act’s regulation-making section. Then a regulation that actually bites a shop. Then who could disallow it.",
    "A pandemic public-health order was a crash course in delegated power. The civic question is oversight, not only whether you liked the order."],
  ["vx-v-sep-powers", "Rules extras", "Separation of powers is a diagram with leaks, not three islands",
    "Parliament makes, executive administers, courts adjudicate. Westminster mixes executive into parliament on purpose. A minister yelling at a judge is a leak with a smell.",
    "The PM is the boss of the High Court because elections. Also: judges run the army. Two US-movie imports.",
    "Draw the three boxes. Put ministers in two of them and admit it. Then a case that struck a law.",
    "A ‘law and order auction’ that promises a verdict in advance is a separation problem in a slogan."],
  ["vx-v-standard-proof", "Rules extras", "The standard of proof is a height of the hurdle, not a mood of how mad you are",
    "Beyond reasonable doubt is high because liberty is on the table. Balance of probabilities is a more-likely-than-not. A workplace investigation can be lower still. Mixing them is how a comment section retries a case.",
    "If I am very sure, that is beyond reasonable doubt. Feelings are a standard.",
    "Name the forum first. Then the hurdle. Then what a ‘not guilty’ does not prove.",
    "A school found it ‘on the balance’ and a parent yells ‘innocent until proven’. Both phrases can be true in different buildings."],
  ["vx-v-bail-not-verdict", "Rules extras", "Bail is a risk decision about showing up, not a mini-guilty",
    "Flight, interference, a community safety test. Conditions (a curfew, a phone) are still not a sentence. Tabloids that treat bail as a verdict are doing a different job from a magistrate.",
    "If they are out, the court thinks they are innocent in a deep sense. Also: if they are in, they are guilty. Two headlines.",
    "Read a bail act purpose clause. Separate the charge from the remand. Then a journalism that mixed them.",
    "A ‘who granted bail’ pile-on after a later crime is a hindsight machine. Hindsight is not the test that applied that morning."],
  ["vx-v-sentencing-purposes", "Rules extras", "Sentencing is a pile of purposes that fight: punish, deter, rehabilitate, protect",
    "A mandatory floor ties a judge’s hands. Deterrence as a theory has a research file, not only a press conference. Victims’ statements are a input, not a slider to maximum every time.",
    "Harsher is always safer. The model is a movie. Also: kindness is always safer. Two movies.",
    "Name the offence, the purpose the judge leaned on, a appeal that said they leaned wrong.",
    "A ‘one punch’ law is a civic experiment. Count outcomes, not the lectern."],
  ["vx-v-restorative", "Rules extras", "Restorative practice is a conversation with a harm at the centre, not a synonym for nothing",
    "Who was hurt, what is needed, a agreement. It can sit beside a charge or instead of one in a school. A forced apology is a theatre.",
    "If we talk it out there is no consequence. Talking is a loophole.",
    "Ask whether the person harmed wanted the process. Then whether the agreement was kept. Then where it is the wrong tool (a power gap).",
    "A workplace ‘restorative’ that makes the junior ‘share feelings’ with the bully is a capture of the word."],
  ["vx-v-admin-review", "Rules extras", "Merits review asks what the right decision was; judicial review asks whether the power was used lawfully",
    "A tribunal can stand in the decision-maker’s shoes. A court on judicial review is often about process, relevance, a legal error — not a redo of the policy you dislike. People mix them because both have wigs in the folk memory.",
    "Appeal means a second person who likes me more. Always.",
    "Name the body (AAT-successor, a state tribunal, a court). Then merits versus legality. Then the cost of showing up.",
    "A visa file, a disability payment, a licensing ban — this is where most people meet ‘the government’ as a letter."],
  ["vx-v-contempt", "Rules extras", "Contempt is the court’s power to protect the process, not a feeling that a judge was rude",
    "Sub judice, a tweeted jury theory, a protest on the steps that crosses a line. Open justice fights with a fair trial. The balance is a statute and a practice, not a vibe.",
    "I can say anything about a live trial because speech. The US First Amendment applies in Parramatta. Obviously.",
    "If you are not a journalist with a lawyer, do not name a accused as guilty on a story while a jury is out. Wait.",
    "A ‘they cannot gag the truth’ account that doxes a juror is a crime costume. The truth had a later date."],
  ["vx-v-limitation", "Rules extras", "A limitation period is a clock on a civil claim, not a moral expiry of the harm",
    "Evidence rot, a finality, exceptions for kids and some abuses. Criminal files have different clocks and sometimes none. ‘Too late’ in a tribunal can be a technical heartbreak.",
    "If it still hurts the clock has not started. Pain is a statute.",
    "Find the clock for a simple debt versus a personal injury. Then an exception. Then why a diary of dates matters.",
    "A school trip injury claimed at 28 can be a limitation story. Forms you hated filling were the clock’s friends."],
  ["vx-v-strict-liability", "Rules extras", "Strict liability is a offence that does not need a guilty mind, with a fairness fight attached",
    "Speeding, some workplace safety, a labelling. Mens rea is the usual criminal friend; strict liability leaves it at home. Defences can still exist (honest and reasonable mistake in some statutes).",
    "If I did not mean it, it is not a offence. Intent is the whole of criminal law. Always.",
    "Read whether the act says ‘knowingly’. Then a reason parliament dropped the mind (a harm that is hard to prove otherwise).",
    "A food-safety strict offence is why a café does not get to shrug ‘we forgot the fridge’. Forgetting was the point."],
  ["vx-v-prerogative", "Rules extras", "Prerogative powers are leftover crown tools sitting under statute and convention",
    "Mercy, some honours, a war-adjacent history. Courts have trimmed them. A ‘the king can do no wrong’ is a history, not a hall pass for a minister.",
    "Royal leftover means unlimited. Crowns are above diagrams.",
    "Name one prerogative that still exists and one that a statute ate. Then 1975 as a convention file, not a prerogative cartoon only.",
    "A pardon is a civic lightning bolt. It does not rewrite the verdict poster in everyone’s head. It rewrites the legal one."],
  ["vx-v-onus", "Rules extras", "Who has to prove what is a designed tilt, not a natural weather",
    "Prosecution usually carries the criminal onus. A reverse onus in a statute is a politics (drugs quantities, some defences). Civil onus sits lower and on the person who asserts.",
    "The accused must prove they are nice. That is how TV works, so law agrees.",
    "In a problem question, star who must prove the extra fact. Then whether a reverse onus is hiding in the act.",
    "A ‘prove you were not at the protest’ demand from a keyboard is not a onus. It is a vibe."],
  ["vx-v-double-diss", "Australia extras", "A double dissolution is a deadlock hammer, not a PM’s boredom button",
    "Section 57, a bill twice rejected, both houses to election, a possible joint sitting. 1974 is the famous sitting. It is not a weekly tool and it can backfire on the hammer-holder.",
    "If the Senate is annoying, just dissolve everything. Easy. Also: the GG must always say yes. Two simplifications.",
    "Track one trigger bill. Then the election result. Then whether the bill actually passed after.",
    "A joint sitting is a rare room. Do not describe ordinary Senate deals as a double dissolution because the vibe was spicy."],
  ["vx-v-supply", "Australia extras", "Supply is the money bill that keeps the lights on; blocking it is a constitutional crisis hobby",
    "1975 sits here. Ordinary budget fights are not always supply in the technical sense. A government that cannot fund itself is not a lifestyle choice.",
    "If I dislike the government I should block their pay. That is how accountability works every Tuesday.",
    "Separate a ordinary amendment from a refusal of supply. Then convention versus the letter. Then why people still yell.",
    "A US shutdown meme does not map cleanly onto a Australian supply fight. Dump the meme for this subject."],
  ["vx-v-caretaker", "Australia extras", "Caretaker convention is a pause on big new things, not a government nap",
    "After the House is dissolved, major appointments and policy wait where they can. Public service stays professional. A ‘we still have the keys’ is true and limited.",
    "In caretaker nobody can do anything, including a fire truck. Also: caretaker is fake so smash through. Two cartoons.",
    "Read a caretaker handbook paragraph. Then a controversy where someone stretched it. Then the election date as a clock.",
    "A infrastructure announcement in caretaker is a classic smell. The smell is the lesson."],
  ["vx-v-crossbench", "Australia extras", "A crossbench is a arithmetic, not a personality type",
    "Independents and minor parties who can make or unmake a majority. Confidence and supply deals. A hung House is the machine without a spare majority — deals are the fuel.",
    "Independents are just celebrities. Parties are fake. Then be surprised by a whip on a ‘independent’ who joined a ticket.",
    "Count the seats. Read the deal in a page. Then a bill that lived or died on one person.",
    "A Senate crossbench can be a government even when the House looks tidy. Two maps of power."],
  ["vx-v-informal-vote", "Australia extras", "An informal ballot is a vote that the rules could not count, sometimes by accident",
    "Numbering errors, a blank, a protest scribble. Compulsory voting plus a complex Senate paper is a informal factory. A donkey vote is still formal if it follows the numbers.",
    "If I draw a cat it is a valid first preference for cats. Art is a electoral system.",
    "Read the ballot instructions. Practise a dummy Senate paper. Then the informal rate in a electorate as a civic clue.",
    "A ‘put a 1 only’ on a paper that asked for more can be a accidental informal. The AEC’s posters exist because of this path."],
  ["vx-v-aec", "Australia extras", "The AEC is a referee with a statute, not a team mascot",
    "Enrolment, a draw of the ballot order, a count, a redistributions process. Independence is a design. Conspiracy files about ‘the count’ usually skip how scrutineers work.",
    "Whoever is in government runs the count in a back room. Obviously. Also: a private app should replace it because apps are neutral.",
    "Watch a count if you can. Read a redistribution’s ‘why’. Then a complaint process that is not a Facebook group.",
    "A how-to-vote card is advice, not a AEC instruction. The logo difference is the whole lesson."],
  ["vx-v-s44", "Australia extras", "Section 44 is a eligibility tripwire that ate a parliament for a season",
    "Dual citizenship, a office of profit, a bankruptcy. 2017–18 was a circus with a legal text that had been sitting there. Nomination forms are not a vibe.",
    "If you feel Australian you are eligible. Feeling is a section.",
    "Read s 44 in plain English. Then one disqualification. Then why a lawyer on the nomination is cheaper than a by-election.",
    "A sports star with a parent’s overseas passport is a civics, not a patriotism quiz."],
  ["vx-v-territories", "Australia extras", "Territories are not states with a tan; their self-government is a Commonwealth gift with a leash",
    "NT and ACT have assemblies. Federal override is a history (euthanasia, a territory rights fight). Residents still vote in the House. Senate representation is a different, smaller story.",
    "Canberra the city is the same as Canberra the territory government is the same as the Commonwealth. One word, one boss.",
    "Ask which parliament, which minister, which override. Then a resident who is tired of being a experiment.",
    "A pothole in Darwin can still be local. A rights experiment in a territory can be a national fight."],
  ["vx-v-national-cabinet", "Australia extras", "National Cabinet is a meeting brand, not a third house of parliament",
    "First ministers, a FOI fight about whether it is cabinet-for-secrecy purposes, a replacement costume for COAG. Useful in a crisis. A habit of calling every meeting a cabinet is a secrecy grab.",
    "If they sat together the Constitution changed. Meetings are amendments.",
    "Name who is in the room, what they can actually bind, what still needs a parliament. Then a FOI case in a paragraph.",
    "A health direction that was ‘National Cabinet decided’ still needed a state statute or a delegate. The brand was not the law."],
  ["vx-v-gst-carve", "Australia extras", "GST is a Commonwealth tax with a carve-up fight the states never finish",
    "Horizontal fiscal equalisation, a Grants Commission, a ‘why does WA / Tasmania get that’. Vertical fiscal imbalance is the boring name for Canberra collecting and states spending.",
    "The state you live in prints the GST. Also: GST is a optional donation. Two pub theories.",
    "Follow one dollar: register, collect, remit, carve. Then a premier’s presser that skipped the formula.",
    "A hospital wait can be a carve-up argument in a costume. Check which budget line before you yell."],
  ["vx-v-exclusive-power", "Australia extras", "Exclusive powers are Canberra-only; concurrent are a shared messy kitchen",
    "Customs, a currency, a defence as typical exclusives. Health and education are a overlap sport. High Court umpires the s 51 fights. Blame-shifting is the political overlay.",
    "Canberra does everything. Your mayor is ceremonial. Also: Canberra does nothing useful. Both, in one barbecue.",
    "Pick a issue (quarantine, a curriculum, a river). Ask which head of power. Then a case or a COAG deal.",
    "A vaccine rollout fight was concurrent politics with a exclusive-looking press conference. Watch the statute."],
  ["vx-v-private-member", "Australia extras", "A private member’s bill is a law proposal without the government’s machine by default",
    "Time is scarce. Conscience votes sometimes live here. Marriage-law history used a private path in the public memory — check the actual vehicle. Most die. Some change the country.",
    "Only the PM may propose a law. The rest is cosplay. Also: any tweet is a bill.",
    "Track a private bill that passed. Then the government’s attitude (help, hinder, abstain).",
    "A crossbencher’s bill that the government adopts is a victory with a stolen letterhead. Still a law."],
  ["vx-v-committees-not-qt", "Australia extras", "A committee can be work; Question Time is theatre with a accidental fact",
    "Estimates, a inquiry, a public hearing. Senators who are boring on TV can be lethal in a committee room. A clip of a gotcha is not a Hansard.",
    "If it is not in a 15-second video it did not happen in parliament. Theatre is the whole factory.",
    "Read a committee report’s recommendations. Then whether a government responded. Then a Question Time clip as a dessert, not a meal.",
    "A ‘taken on notice’ is a delay that can be a dodge or a careful check. Follow the answer in the later paper."],
  ["vx-v-redistribution", "Australia extras", "A redistribution is a population maths, not automatically a rort — and rorts still get accused",
    "Enrolment quota, a map, objections. Malapportionment is a different historical sin (some state uppers). US gerrymander memes mislead if you paste them without the AEC process.",
    "They redrew my suburb so my team loses, therefore fraud. My team winning a redraw is science.",
    "Read the quota. Look at a ‘why this boundary’ paragraph. Lodge an objection if you have a reason that is about community of interest, not a vibe.",
    "A seat named after a person is a civic memory. The drawing of its line is a census."],
  ["vx-v-preamble-const", "Australia extras", "The constitutional preamble is a sentence with a politics, not a operative power by itself",
    "1999’s republic package included a preamble fight. Recognition of First Nations has lived in preamble debates and in s 128 attempts. Courts do not treat a preamble as a blank cheque.",
    "The preamble is the vibe courts must feel. Mateship is a head of power.",
    "Read the current opening. Then a proposed sentence and who hated it. Separate poetry from s 51.",
    "A ‘we the people’ import from the US is a different constitutional culture. Do not paste it onto 1901 without a note."],
  ["vx-v-federation-deals", "Australia extras", "Federation was a set of deals, not a immaculate birth of mateship",
    "Tariffs, a railway gauge mess, a White Australia we had to unlearn, colonies as players. Civic habits are inherited and invented. A tradition can be a resource or a cage.",
    "We have always been like this. ‘This’ is a BBQ and nothing else.",
    "Pick a civic invention (the secret ballot as an export) and a civic stain. Hold both in one paragraph.",
    "A ‘she’ll be right’ can be solidarity or a shrug at a royal commission. Which, in this case?"],
  ["vx-v-implied-rights", "Rights extras", "Implied rights are a High Court construction from the text’s structure, not a hidden bill in a drawer",
    "Political communication is the famous one. It is not a US First Amendment. Limits still exist. A ‘I have implied rights’ at a airport boom gate is a folk law.",
    "We have the First Amendment. I saw it on a show. Implied means unlimited.",
    "Name the implied right, the case in a sentence, the limit. Then a statute that still stands.",
    "A protest ban will be a High Court fight sometimes, a local permit fight other times. Which layer?"],
  ["vx-v-charter-states", "Rights extras", "State and territory charters are statutes with a dialogue, not a US strike-down machine",
    "Vic, ACT, Qld. Interpretation, a declaration of inconsistency, a parliament that can still say no. Useful and limited. People import ‘unconstitutional’ from television.",
    "If a charter exists, police stop instantly. Paper is a magic wand.",
    "Read what the charter actually lets a court do. Then a case that was a dialogue, not a explosion.",
    "A hospital decision and a protest decision can both be ‘rights’ and still use different tools."],
  ["vx-v-anti-discrim-test", "Rights extras", "Direct and indirect discrimination are different tests; impact can matter when intent shrugs",
    "Protected attributes, an area (work, goods, education), a exception that is a political fight (sport, religion, occupational). ‘I am rude to everyone’ is a different bad.",
    "Free speech means I can refuse a group and the law always shrugs. Also: every joke is a federal case. Two posters.",
    "Read the attribute, the area, the exception. Then whether the claim is direct or a policy that hit unevenly.",
    "A uniform rule that forbids a religious item can be a indirect file. A ‘no hats’ culture rule is not automatically the same."],
  ["vx-v-privacy-app", "Rights extras", "APP-style privacy is a purpose-and-use rule, not a feeling of being watched",
    "Collect for a use, do not recycle into a new use without a basis, access and correction. Mission creep is the civic disease. ‘Nothing to hide’ is a history of going wrong.",
    "If you have nothing to hide you have nothing to fear. Full stop.",
    "Ask purpose, retention, who can query, a warrant. Then a scandal. Then your school’s database as a workplace of a kind.",
    "A metadata law is a civics text. ‘Not the content’ is a lawyer’s sentence that still maps a life."],
  ["vx-v-youth-layers", "Rights extras", "Age is a civic on/off in layers, not a single adulthood switch at a party",
    "Vote at 18, a licence earlier, a criminal age, a social-media age fight. ‘Nothing about us without us’ still hits kids last. Youth parliaments are practice unless a domain is real.",
    "Kids should not have views. Also: kids should run the country from TikTok. Two cartoons.",
    "List what you can legally do at 16 versus 18. Then what you should still be heard on (a bus route, a uniform, a climate file).",
    "A school strike is a protest with a truancy overlay. Adults arguing about the overlay sometimes skip the claim."],
  ["vx-v-union-bargain", "Rights extras", "An enterprise agreement is a legal technology; a vibe of ‘we are a family’ is not a award",
    "Collective versus one scared person. Strikes have rules. Non-union is a choice with a cost. Fair Work is a map, not a mascot.",
    "Unions are a 19th century costume. The gig economy abolished power imbalances. Also: unions are automatically the state. Two sermons.",
    "Read a agreement’s cover page: who, how long, a dispute clause. Then a protected industrial action versus not.",
    "A ‘scab’ is a word with a history. So is ‘freedom to work’. Look at the roster, not only the slogan."],
  ["vx-v-whistle", "Rights extras", "Whistleblowing is a protected path with a paperwork, not a random dump to a group chat",
    "Public interest disclosures, a internal channel, a journalist as a later door. Revenge leaks and protected disclosures are not synonyms. PID statutes are a maze on purpose.",
    "If I post it, I am a hero automatically. Also: snitching is always wrong. Two schoolyard rules.",
    "Read whether your workplace has a PID procedure. Then a lawyer if the file is nuclear. Then do not mix a personal grudge with a public harm without naming both.",
    "Robodebt had whistleblowers and a royal commission. A Slack rant is not automatically the same civic act."],
  ["vx-v-disability-ncc", "Rights extras", "Disability rights are a convention, a statute, and a building code — three tools, not a kindness",
    "DDA, a reasonable adjustment, a Premises Standards cousin of the NCC. A ‘we forgot the ramp’ is a design of who was imagined. Charity is not the substitute for a standard.",
    "If I can use the stairs the building is fine. I am the measure of a citizen.",
    "Name the adjustment, the unjustifiable-hardship fight, a complaint path. Then a school exam adjustment as a ordinary file, not a favour.",
    "A dark civic event that is a trip hazard is a exclusion. Tape is not a vibe, and neither is a Facebook apology."],
  ["vx-v-first-nations-voice-file", "Rights extras", "A Voice debate is a constitutional design fight, not a personality test about whether you are nice",
    "2023 was a s 128. Treaties in some states are a different tool. Native title is another. Flattening 250+ ways of being into one poster is the recurring fail.",
    "It was settled in 1788. Civic file closed. Also: one body can stand for every Nation without a argument. Two closures.",
    "Use legal words and community words. Find a local Land Council on a map. Separate the referendum question from every other First Nations file.",
    "A Welcome in language is a politics and a gift. It is not a substitute for a statute."],
  ["vx-v-citizenship-door", "Rights extras", "Citizenship is a legal status with a door; a flag feeling is not the door",
    "Birth, descent, conferral. Dual is a politics. Statelessness is a hole. Denaturalisation is a scary tool. A passport is a document.",
    "Real citizens feel a certain way about the flag. The law is a feeling. Also: a visa holder cannot be part of the civic ‘we’.",
    "Read a statute path. Then who is stuck in a queue. Then a sports captain and a visa holder as both in the ‘we’ with different files.",
    "s 44 ate dual citizens in a parliament. The same dual can be a ordinary Tuesday at a airport."],
  ["vx-v-protest-place", "Rights extras", "Protest is speech plus a place plus a time; a permit is not automatically a muzzle or a permission to smash",
    "Move-on powers, a line between assembly and a riot, a blockade as a tactic with a theory of change — or a tantrum. Civil disobedience is a choice with a bill.",
    "Real protest is only online. Streets are outdated. Also: smash is the only authentic. Two costumes.",
    "Know the local rules. A legal observer is a role. Film if law allows — and they may film you.",
    "A boom-gate airport joke is a rim. A slogan at lunch is a different rim. Place is the subject."],
  ["vx-v-consumer-acl", "Rights extras", "The ACL is a tilt against a small-print machine, not a coupon for a mood",
    "Misleading or deceptive, a consumer guarantee, a unfair contract term neighbourhood. ACCC as a regulator with a press release habit. Your photo of the shelf is evidence.",
    "Caveat emptor, full stop. The Middle Ages called. Also: if I am disappointed I am guaranteed a refund always.",
    "Keep the contract, the photo, the email. A tribunal. A fake review is a different file from a honest one.",
    "A subscription trap is a design. The law is catching up in chunks. Cooling-off is not a personality."],
  ["vx-v-foi-narrow", "Rights extras", "FOI is a narrow request with black bars, not a dump of the secrets because democracy",
    "Exemptions, a fee, a cabinet claim, a commercial-in-confidence. A journalist’s job and a student’s. A Christmas-eve dump is a tactic.",
    "If it is a democracy they email you the secrets. FOI is a vibe. Also: FOI is spying on the government and therefore treason. Two posters.",
    "Write a narrow request. Expect bars. Appeal if the bars look like panic not law.",
    "A document that is 90% black is still a civic artefact. The bars are a claim you can challenge."],
  ["vx-v-legal-aid-ration", "Rights extras", "Legal aid is a rationed good; the machine is built for lawyers",
    "Means tests, a duty lawyer, a self-represented litigant as a fairness problem. A ‘equality before the law’ poster that ignores the invoice is a poster.",
    "Everyone gets a QC if they ask. Television. Also: only the guilty need lawyers. Two myths.",
    "Find the legal aid website’s ‘we do not do this’ list. Then a community legal centre. Then why a form deadline is a trap.",
    "A small claim in a tribunal was supposed to be the accessible door. It can still eat a weekend and a nerve."],
  ["vx-v-victim-rights", "Rights extras", "A victim’s right to information is not a right to write the sentence",
    "Charters of victim rights, a VIS, a restorative door. A trial is still not a therapy and not a revenge shop. Both dignity and the standard of proof have to sit in one building.",
    "If the victim is sad the hurdle drops. Sadness is a standard. Also: victims should be silent because the state owns the file. Two cruelties.",
    "Separate the information right, the participation, the sentencing discretion. Then a support service that is not a comment section.",
    "A high-profile VIS on the news is a civic moment. It is not a substitute for the elements of the offence."],
  ["vx-v-press-owner", "Media extras", "A masthead has an owner; the owner is a civic fact, not a conspiracy by itself",
    "Proprietor, a share register, a public broadcaster charter (ABC/SBS) as a different animal. Local news collapse is a hole in the watchdog. A feed is not a country.",
    "If it is on a phone it is journalism. If it is on TV it is not. Or the reverse. Pick a prejudice and skip ownership.",
    "Ask who paid, who was sourced, what was missing. Then a second masthead. Then FOI as a tool the outlet used or skipped.",
    "A press-gallery gallery is not the whole country. Regional papers dying is a map of silence."],
  ["vx-v-defamation-share", "Media extras", "Sharing a lie is publishing; ‘allegedly’ is not a cloak of invisibility",
    "Truth, honest opinion, a public-interest defence that is work. Australia is not the US on this. A group chat pile-on of a private person is a mismatch of lawyers.",
    "If I put allegedly I can say anything. Also: public figures have no feelings. Two imports.",
    "Do not pile on a private person. Journalists have lawyers; you have a screenshot. That is a mismatch.",
    "A politician suing is a power play and sometimes a genuine harm. Courts, not a ratio, finish it."],
  ["vx-v-lobby-register", "Media extras", "A lobbyist register exists because of a smell; a lunch is not automatically a purchased statute",
    "Access, donations, a revolving door. Charity lobbies and mining lobbies are both lobbies. Weight is the question. A ‘they paid for a sandwich so the law is bought’ can be lazy and sometimes not.",
    "If they met, the law is bought. Always. No need for a diary. Also: lobbying is just speech, so registers are tyranny.",
    "Follow the donation, the meeting diary, the amendment. Then who had no lunch.",
    "A peak body and a hidden consultancy can be the same asking with different letterheads. Read the letterhead."],
  ["vx-v-abc-charter", "Media extras", "A public broadcaster is a statute with a independence fight, not a government newsletter or a rebel radio by default",
    "Charter, a board, a budget that is a political lever. Complaints process. ‘Bias’ is a industry with a method problem: compared to what.",
    "If my team is mad it is biased. If my team is happy it is a public service. Method optional.",
    "Read the charter’s words. Then a editorial standard. Then a complaint that was about a fact versus a framing.",
    "SBS’s multilingual brief is a civic design. So is the absence of a local paper. Both are media policy."],
  ["vx-v-poll-method", "Media extras", "A poll is a snapshot with a n, a house effect, and a question that can lean",
    "A 3% swing in a small poll is a maybe. Betting markets are not oracles. A push poll is a campaign call in a clipboard costume.",
    "The last poll I liked is the election. Done. Also: polls are fake because I have never been called. Two folk proofs.",
    "Ask n, date, who paid, the exact question. Then wait for a real vote. Then a house effect across pollsters.",
    "A leadership ‘preferred PM’ number can move while seat maths does not. Seats are the machine."],
  ["vx-v-hansard-search", "Media extras", "Hansard is the tape of the factory; a clip without the line is a trailer",
    "Who said what, a correction, a point of order. Boring on purpose. A ‘taken on notice’ lives here as a later paper.",
    "If it is not viral it did not happen. Also: Hansard is fake because politicians lie. Lying and recording both exist.",
    "Search a bill’s name. Read a second-reading speech. Then a committee Hansard if you are keen.",
    "A misquote that dies when you open Hansard is a media-literacy win. Open it."],
  ["vx-v-foi-journalism", "Media extras", "A document dump is a journalism of patience, not a personality of leaking",
    "FOI, a whistle, a court file. The civic skill is reading the PDF, not only the headline about the PDF. Exemptions are a designed fog.",
    "Leaks are always heroic. Also: leaks are always treason. Two movies, no PDF.",
    "Cite the document date. Note the black bars. Separate the spin paragraph from the table.",
    "A midnight drop before Christmas is a tactic. The calendar is civic. So is a quiet Tuesday report nobody quoted."],
  ["vx-v-platform-mod", "Media extras", "A platform is a private square with public effects; a CEO is not a court",
    "Moderation is a policy. Deplatforming is a company choice. eSafety is a statute. The civic ask is who should write the rules — and the harms of both answers.",
    "The internet is the public square of 1791. The First Amendment applies in a Melbourne Facebook group. Obviously.",
    "Read a community guideline. Then a statute. Then who is missing from the board. Then a pile-on that had no appeal.",
    "A pile-on is a crowd. A moderator is a bouncer. A court is a court. Do not mix the costumes."],
  ["vx-v-disinfo-design", "Media extras", "Disinformation is a designed false; misinformation can be a uncle with a share button",
    "A strategy, a bot network, a genuine uncle. Deepfakes are a accelerant. Slow sharing is the civic skill. Confirming your team is not research by itself.",
    "If it confirms my team, it is research. If not, it is fake news. Done.",
    "Check the date, the account, a reverse image, a second outlet. Then still be unsure. Then do not pile on a person who was fooled.",
    "A WhatsApp from a cousin in a war is a source with a bias, not zero. Fog is the subject."],
  ["vx-v-local-news-hole", "Media extras", "When the local paper dies, council still meets — you just do not hear the fight",
    "Court lists, a DA, a sports club grant. Civic holes are not filled by a national culture-war feed. A Facebook group is a uneven substitute with a moderator who has a job elsewhere.",
    "If it is important it will trend. Trends are a local government.",
    "Go to a council agenda. Find one item. That is the paper’s ghost. Take notes.",
    "A playground versus a high-rise is a values map at 7pm in a hall. It will not be on a global timeline."],
  ["vx-v-press-gallery", "Media extras", "A gallery is a beat with a pack; the pack can miss a suburb",
    "Access, a doorstop, a gallery joke that becomes a frame. Useful proximity. Capture is a risk. Regional and specialist beats are a different map.",
    "Canberra journalists are the country. Also: they are all useless. Two comforts.",
    "Compare a gallery frame with a local outlet on the same week. Name what each dropped.",
    "A drought story that needs a gallery permission to exist is a civic failure of attention."],
  ["vx-v-advertorial", "Media extras", "Native advertising is a ad in a journalism costume; disclosure is the civic minimum",
    "A brand studio, a ‘partner content’, a influencer who is a small masthead. Consumer law neighbourhood. A school project that copies an undisclosed ad is a media-literacy fail.",
    "If I like the person it is a diary, not an ad. Friendship is a disclosure.",
    "Look for the label. Assume a bag of rice has a price. Then the same standard for a politician’s sponsored clip.",
    "A ‘doctors hate this’ slideshow is a cousin. The doctor is not in the piece. The civic is the label."],
  ["vx-v-media-diversity", "Media extras", "Diversity of titles is not diversity of owners, and neither is diversity of beats",
    "Pluralism as a civic good. A dozen URLs with one proprietor is a costume. Diaspora media and First Nations media are part of the map, not a extra.",
    "More websites means a healthier democracy. Count the tabs, skip the share register.",
    "Sketch who owns what you read in a week. Add one outlet that is not in the pile. Then a language other than English if it is in your suburb.",
    "A merger inquiry at the ACCC is a civics class if you bother. Most people skip it and then yell about ‘the media’ as a blob."],
  ["vx-v-offrecord", "Media extras", "On the record, off the record, and background are different contracts — and they fail",
    "A source who is playing you. A journalist who burns a source. A politician who says ‘off the record’ after the sentence. None of this is a statute you can cite in a group chat.",
    "If it is in quotes it is true. If it is unattributed it is fake. Simple.",
    "Treat unnamed as a reason to triangulate, not a reason to believe harder because it feels secret.",
    "A ‘senior source’ that is the minister’s staffer is a genre. Genre is a tell."],
  ["vx-v-press-freedom-raid", "Media extras", "A raid on a journalist is a civic alarm even when the leak was real",
    "Source protection, a national security statute, a public-interest tension. Democracies raid too. A ‘nothing to hide’ about a newsroom is a category error.",
    "If the government is mad the journalist is guilty. Also: journalists are above any statute. Two posters.",
    "Read what was alleged, what was published, which warrant. Then a press-freedom group and a security spokesperson. Both.",
    "A whistleblower and a journalist are a pair with different legal clothes. Do not mash them into one martyr without the files."],
  ["vx-v-un-organs", "World extras", "The UN is a club of states with organs that do different jobs, not a world government with a police car",
    "General Assembly theatre, Security Council vetoes, agencies that vaccinate. Paralysis is a 1945 design. A resolution is not a statute in Canberra.",
    "The UN can arrest a PM. That is why people fear it. Or: the UN is useless so ignore it. Two comforts.",
    "Name an organ, a veto, a success, a peacekeeping mess. Hold the set.",
    "A WHO guideline is not an Australian act. It can still be a political fact in a presser."],
  ["vx-v-veto", "World extras", "A Security Council veto is a designed inequality, not a glitch in fairness software",
    "Five permanent members. A mass-atrocity file can die in a sentence. Reform talk is older than you. Regional blocs in the Assembly are a different maths.",
    "If it is the UN it is one-country-one-vote in every room. Also: the UN is just the US. Two skips of the chart.",
    "Pick a vetoed resolution. Who vetoed, whose interest, what happened on the ground after the theatre.",
    "A humanitarian corridor that exists in a communique and not at a checkpoint is a veto’s cousin: words versus trucks."],
  ["vx-v-ihl-distinguish", "World extras", "Distinction and proportionality are IHL’s spine; a drone does not delete them by being far away",
    "Civilians, a military objective, a war crime as a category. Having a law of war is not a blessing of war. ICC politics is a separate, spiky file for Australia.",
    "In war there are no rules. That is why we say war. Also: if our side did it, it was a mistake; if theirs, a crime. Two mirrors.",
    "Name a rule, a alleged breach, a court or a inquiry. Distance is not a legal argument by itself.",
    "A urban battle is where distinction gets hardest and most necessary. Hard is not the same as void."],
  ["vx-v-refugee-category", "World extras", "A refugee is a legal category about persecution; a migrant is a different word",
    "UNHCR, a domestic statute, asylum as a process. Deterrence is a policy with a body count and a politics. Boats are a geography that people use as a moral.",
    "They are all illegal because boats. Or: borders are fake so categories are fake. Two deletions of the file.",
    "Use the legal word, then the visa class, then a human without drowning the legal file. Then a complementary protection if that is the path.",
    "An undocumented worker, a refugee, a tourist overstay are not synonyms. Civics starts there, not at a meme."],
  ["vx-v-aid-effectiveness", "World extras", "Aid is a budget line with a strategy; 0.7% is a target many miss",
    "Emergency versus development, a national interest (yes, often), cash versus projects versus governance fights. A submarine is not the only other option in the universe of budgets.",
    "Aid is a gift from saints, or a waste that should be a submarine. Only two takes.",
    "Follow a dollar. Ask who decided the project. Then a criticism from the place, not only from a talkback host.",
    "A climate-adaptation grant is aid. A mining concession is a different file. They can sit in one country."],
  ["vx-v-isds", "World extras", "ISDS is a investor court in a trade deal, not a synonym for trade",
    "A company suing a state over a policy. Labour and environment chapters can be toothless cousins. Cheaper goods and smashed towns can both be true.",
    "Free trade is always win-win by definition. The model said so. Also: trade deals are always a secret world government. Two models.",
    "Read who gained market access, who lost a factory, what a dispute panel can do. Then whether ISDS is in the text.",
    "A banana and a streaming service can be in the same deal. ‘Trade’ is wide. So is a patent chapter."],
  ["vx-v-sovereignty-holes", "World extras", "Sovereignty is a claim to be the boss inside a border, then the holes: treaties, markets, climate, corporations",
    "Westphalian sticker. First Nations sovereignty is a different, older, living claim here. A trade deal is a slice sold or pooled.",
    "Sovereignty means you can do anything including crimes against people, and outsiders must sip tea. Also: sovereignty is fake so anything goes. Two voids.",
    "Ask who is claiming it, against whom, and what they still cannot control (a capital flight, a virus, a fire’s smoke).",
    "A carbon tariff is a global-citizen tool with a nationalist costume. Read both labels."],
  ["vx-v-icc-politics", "World extras", "The ICC is a court with a membership map; Australia’s relationship is a politics, not a wallpaper",
    "Complementarity, a powerful non-member, a accusation of bias that is sometimes a file and sometimes a shield. It is not a world police for every mad post.",
    "The ICC will get your PM next Tuesday. Or: the ICC is fake because a powerful state ignored it. Both as complete theories.",
    "Name a case, a non-member, a complementarity test. Then why a domestic war-crimes inquiry might be the adult path.",
    "A social-media ‘ICC’ under a protest photo is often a vibe. Courts have dockets."],
  ["vx-v-sanctions", "World extras", "Sanctions are a foreign policy with a grocery bill for someone, often not the named elite",
    "Targeted versus comprehensive, a humanitarian carve-out that may not work, a secondary-sanctions extra-territorial fight. They can be a alternative to shooting and a cruelty.",
    "Sanctions always work because economics. Also: sanctions never work because the poster said so. Two evaluations without a date.",
    "Ask who is hit, who is insulated, what the stated goal was, whether the goal moved. Then a Australian alignment with a larger power’s list.",
    "A olive oil and a bank SWIFT code can be in the same toolbox. ‘Sanctions’ is a family."],
  ["vx-v-peacekeeping", "World extras", "A peacekeeping mandate is a sentence that may not match the guns on the ground",
    "Consent, impartiality, a chapter of the Charter, a failure file (and a success file). Blue helmets are not a superhero franchise. Host-state politics can eat the mandate.",
    "The UN army should just fix it. There is a UN army. Also: peacekeeping is only a hotel bill.",
    "Read a mandate in a paragraph. Then a incident. Then whether the troops had the authority the public assumed.",
    "A Australian deployment can be a coalition, a UN, or a alliance. The shoulder patch is a civic."],
  ["vx-v-climate-epbc", "World extras", "An environment assessment is a delay-and-deal statute, not a market that will hug the atmosphere by itself",
    "EPBC-style federal powers, a state EPA, a court case that is a habitat. Who is too poor to appeal is the map. Climate is a civic file because of who pays.",
    "The market will fix the atmosphere because it is a market. Also: one protest is a statute. Two skips.",
    "Who assesses, who appeals, who donated. Then a condition on a approval that was a theatre.",
    "A coal mine versus a reef is a values and a statute fight. Both can hire scientists. Courts hire tests."],
  ["vx-v-ngo-account", "World extras", "An NGO is a private organisation with a public pitch; who elected them is a fair question and not a smear by itself",
    "Aid, advocacy, a fundraising machine. A local food bank and a global INGO are cousins, not twins. Accountability reports exist because of scandals and because of professionalism.",
    "NGOs are always saints, or always foreign agents. Pick a conspiracy and skip the annual report.",
    "Read money in, program out, a serious criticism. Then whether your beef is the mission or a invoice.",
    "A peak body in Canberra can be a NGO with a access that a remote clinic does not have. Access is civic."],
  ["vx-v-diplomatic-immunity", "World extras", "Diplomatic immunity is a reciprocity deal, not a superhero cloak for a crash",
    "Vienna Convention, a sending state that can waive, a persona non grata. Unfair in a street and still a reason we do not hostage each other’s staff as a hobby.",
    "If they have a flag on the car they can do anything. Also: immunity is fake in my country. Two accidents waiting.",
    "Separate a parking ticket file from a serious crime file. Then the waiver politics. Then why tit-for-tat is the design.",
    "A embassy is not the soil of another planet in every legal sense the movies sold. Still, do not raid it as a school project."],
  ["vx-v-extradition", "World extras", "Extradition is a treaty plus a dual-criminality test, not a kidnapping with better stationery",
    "A political offence exception in some texts, a death-penalty assurance, a court in the requested state. Twitter’s ‘just send them’ skips the statute.",
    "If we are mates we send people. Mateship is a treaty. Also: we never send our people. Two nationalisms.",
    "Name the treaty, the offence in both places, a human-rights gate. Then a famous refusal.",
    "A tax charge and a torture risk can sit in one file. The court has to do both, not your timeline."],
  ["vx-v-soft-power", "World extras", "Soft power is attraction and a scholarship, not a synonym for nice",
    "A broadcaster, a university, a disaster team, a mining brand that undoes the scholarship. Measurement is mushy. Still a budget line.",
    "If we are nice we are safe. Nice is a defence policy. Also: only ships matter. Two budgets.",
    "Pick a Australian soft-power tool. Then a hard-power neighbour. Then a year the tool was ignored because a alliance yelled.",
    "A firefighting deployment can be both a hug and a diplomacy. Hold both without a press kit."],
  ["vx-v-global-media-fog", "World extras", "A war’s first casualty is still a feed with a watermark you skipped",
    "State broadcasters, a diaspora WhatsApp, a platform algorithm. Foreign influence is a real file and a moral panic, sometimes both. English is not a truth serum.",
    "If it is in English it is true. If it is translated it is propaganda. Simple.",
    "Diversify sources. State-funded is a disclosure, not an auto-lie. Then ownership. Then a delay before you share a atrocity clip.",
    "A deepfake and a old clip with a new caption are cousins. Lateral reading is the civics, not a vibe of cynicism."],
  ["vx-v-src-real-domain", "Civic extras", "A student council is pedagogy; tokenism is when the decision was already made in the office",
    "Low stakes, a sausage budget, a lesson in agendas. A good one has a real domain (canteen, a charity, a uniform consultation that can actually move).",
    "If we voted on the timetable we would be a democracy. Until then, nothing counts. Also: the SRC is a parliament so skip maths.",
    "Ask what you can actually change. Minute it. Change that. Then a mock election as a rehearsal, not a substitute.",
    "A real SRC motion that dies in a drawer is a civics lesson about power. Keep the minutes."],
  ["vx-v-enrol-habit", "Civic extras", "Enrolment is a habit with a birthday clock, not a personality of being political",
    "AEC, a move of house, a first-time. Compulsory enrolment is a design. A ‘I’ll enrol when I care’ is how you miss a close one.",
    "If the system is imperfect I owe it nothing. Pure. Also: I want the hospital.",
    "Check enrolment when you move. Then a 20-minute research before the Saturday. Then a protest if you need — both can sit.",
    "A census lie is a tiny civic vandalism. A million of them is a bad map for hospitals. Enrolment is a cousin habit."],
  ["vx-v-jury-duty-show", "Civic extras", "Jury duty is a randomly unlucky education you do not research on your phone",
    "Facts versus law, a filter at empanelment, a unanimity or majority depending. It is not 12 Angry Men as a documentary. Looking up the accused is the whole point of the box to forbid.",
    "Juries decide the law according to vibes. That is democracy in a box. Also: smart people should dodge the letter. Two dodges.",
    "If you are called, tell the truth at selection. Do not google. A hung jury is a result, not a fail of the universe.",
    "A workplace that punishes jury service is a civic defect. The statute usually saw that coming."],
  ["vx-v-complaint-ladder", "Civic extras", "A complaint has a ladder: the shop, the ombuds, a tribunal — volume on the internet is not a rung",
    "Jurisdiction, a form, a wait. An ombudsman is a limited menu (maladministration, not a re-run of a policy you dislike). A school path often exists before a court.",
    "Complain to the internet and the ombuds is optional. Volume is a remedy. Also: complaining is snitching.",
    "Read the jurisdiction. Then the form. Then wait. Do not skip to a lawyer TV advertisement as a first move unless the harm is nuclear.",
    "A energy bill fight and a police complaint are different ladders. Mixing them is how you bounce."],
  ["vx-v-integrity-body", "Civic extras", "An integrity commission is a spotlight with a terms-of-reference, not a daily guillotine",
    "A brown envelope, a mate’s contract, a job for a spouse. A witch-hunt is the counter-cry, sometimes fair, sometimes a dodge. Reports can sit on a shelf — that gap is the subject.",
    "All politicians are corrupt. Therefore voting is for suckers. Therefore my team’s bags are fine. A triangle of cop-outs.",
    "Follow the contract, the meeting, the code. Then a journalist who did the work. Then whether a law changed.",
    "A pork barrel is a cousin: legal and stinky can sit together. Voters are the disinfectant if they can see."],
  ["vx-v-budget-follow-dollar", "Civic extras", "A budget is a moral document in numbers; a surplus is not automatically virtue",
    "What we tax, what we buy. Debt can be a tool. Bracket creep is a quiet rise. A ‘debt and deficit’ slogan can be true, false, or both depending on the measure and the year.",
    "Tax is theft, or tax is love. Pick a team and skip the tables.",
    "Follow one dollar: collected, appropriated, delivered. Look at who is missing. Then a MYEFO as a sequel, not a vibe.",
    "A RBA cash-rate day is civic because mortgages and savers are both citizens. The PM does not set that rate on a whim, whatever a meme said."],
  ["vx-v-local-agenda", "Civic extras", "A council agenda is the closest factory; turnout can be sleepy and still bind you",
    "Bins, a DA, rates. Planning is local politics with a clipboard. A pothole is often here. A passport is not.",
    "Local government is a training league. Real politics is only Canberra. Also: my mayor runs the army.",
    "Open this month’s agenda. Pick a fight. Go or write. That is class.",
    "A playground versus a high-rise at 7pm is a values map. It will not trend. It will still pour concrete."],
  ["vx-v-minutes-habit", "Civic extras", "Minutes are how a group remembers it decided; without them you have a vibe and a rewrite",
    "SRC, a club, a strata, a cabinet (which you will not see). A decision that is not minuted is a later fight. Boring is a technology.",
    "If we all remember, we do not need paper. Memory is a minute. Also: minutes are a bureaucracy that kills passion.",
    "Write who, what, by when. Confirm next meeting. Then a action that actually happened.",
    "A ‘we agreed’ in a chat with no names is how a volunteer burns out. Names are civic even at a sausage sizzle."],
  ["vx-v-spill", "Australia extras", "A leadership spill is an internal election; the country does not get a Saturday unless someone calls one",
    "Party room, a petition of signatures, a PM who can lose the keys without a general election. Westminster is not a presidential vibe. Voters still get a say later — and feel robbed now.",
    "The PM is directly elected as a personality like a president. Always. Spills are illegal.",
    "If they lose the party room they usually lose the Lodge. Then a election timing as a separate lever.",
    "A ‘I didn’t vote for this PM’ is a accurate feeling and a misunderstanding of the machine. Both can sit."],
  ["vx-v-gg-assent", "Australia extras", "Royal assent is usually a stamp; reserve powers are the fire extinguisher behind the glass",
    "1975 never cooled. Convention is the unwritten OS. The GG is not a British boss running the army daily, and not a mascot with zero file.",
    "The GG is a tourist in a hat. Also: the GG is a secret monarch who plots weekly. Two costumes.",
    "Separate the usual stamp from the extraordinary. Then republic versus keep as a later, honest fight.",
    "A dismissal is a civic nuclear text. Read more than a meme and more than a one-team sermon."],
  ["vx-v-preferential-flow", "Australia extras", "Preferences are a second life of a vote; a 1 is not the whole civic act",
    "If your first is last, your next number can still decide. How-to-vote cards are advice. Exhaustion depends on the system. A ‘put them last’ campaign is a preference story.",
    "Number 1 is the only civic act. The rest is doodling. Also: the card is law.",
    "Rank a dummy ballot. See who gets the flow. That is the lesson, not a slogan about ‘your vote was wasted’.",
    "A Senate paper is a different numbering contract from the House. Read the paper in front of you."],
  ["vx-v-cabinet-solidarity", "Australia extras", "Cabinet solidarity is a collective secret until a leak; a split is news because the norm is the glue",
    "Minutes you will not see. Public service supposed to be professional, not a colour. A FOI of a cabinet paper is a legal fight. Secrecy has a civic case and a cover-up case.",
    "The PM decides alone, like a king with a social account. Cabinet is furniture. Also: every leak is treason.",
    "Watch a split. Ask whether the government is sick or honest — sometimes both. Then a FOI exemption as a claim.",
    "A ‘cabinet decided’ presser that was three staffers and a poll is a branding. Branding is not a minute."],
  ["vx-v-opp-job", "Australia extras", "The Opposition is a job: to oppose and to be an alternative, not only a outrage machine",
    "Shadow ministers, a budget reply. If they only perform, they still have a constitutional job. A small crossbench can scramble the two-team diagram.",
    "Opposition means obstruct everything, including a fire truck. Also: opposition is unpatriotic. Two sermons.",
    "Watch a budget reply. Then a bipartisan moment as a data point. Then a shadow who actually read the bill.",
    "A Senate where the government lacks a majority makes ‘opposition’ a many-body problem. Count."],
  ["vx-v-royal-comm-shelf", "Rules extras", "A royal commission is a spotlight with counsel assisting; the civic gap is recommendations versus legislation",
    "Terms of reference, a witness, a report that can sit. It is not a court of guilt in the usual way. Aged care, banks, robodebt — names that are files, not close-outs.",
    "If there was a commission the problem is fixed. Reports are magic. Also: commissions are only a witch-hunt.",
    "Read the terms. Then one finding. Then whether a law changed. That last step is the whole subject.",
    "A TV apology in the hearing room is a civic moment. It is not a statute."],
  ["vx-v-mandatory-floor", "Rules extras", "A mandatory sentence is parliament tying a judge’s hands; deterrence is a research file, not a volume knob",
    "A young person in a number, a judicial discretion fight. Evidence on deterrence is live. A ‘one punch’ experiment still wants a count of outcomes.",
    "Harsher is always safer. The model is a movie. Also: judges are always soft. Two movies, no table.",
    "Name the crime, the floor, who still has a way out (a plea, an age). Then a critic and a victim group. Both.",
    "A floor that hits one community harder is a civic data point. Data is allowed in a punishment argument."],
  ["vx-v-police-power", "Rules extras", "A police power is a statute with a reason attached; a scandal is why review bodies exist",
    "Stop, search, arrest. A complaint body. ‘Just following orders’ is a thin civic file. Also: someone has to take the 000 that is a real knife. Both exist.",
    "ACAB as a full theory, or ‘thin blue line’ as a full theory. Skip the powers and the cases.",
    "Name a power, a limit, a review. Then a scandal that proved the review was needed. Then a crash where the cop was first aid.",
    "A search without a reason is a civics problem. A move-on at a protest is a different section. Cite the section."],
  ["vx-v-udhr-stick", "Rights extras", "The UDHR is a measuring stick, not a magic wand that auto-strikes an Australian statute",
    "1948, a politics of who drafted. Treaties often limp until legislated. Advocacy uses the language. Police do not keep a UDHR app that overrides the act.",
    "If it is in the UDHR, the police must stop. Instantly, everywhere. Also: if it is not in a local act, it is fake. Two deletions.",
    "Use it as a stick. Then the local enforceable tool (a charter, a DDA, a implied right). Then a gap.",
    "A treaty without implementing legislation is a promise with a limp. Lawyers will say it depends — that is the lesson."],
  ["vx-v-global-citizen-bus", "World extras", "A global citizen is a metaphor with a passport still in the drawer; the local bus still runs",
    "Climate, a pandemic, a supply chain. Duties abroad (aid, refugees, emissions) can crowd out the poor citizen in front of you if you only do the metaphor. They can also be real duties.",
    "Only the nation exists. Also: only the globe exists. Two cartoons, no local bus.",
    "Name a duty at home and a duty abroad. If they conflict, that is politics, not a failure of the metaphor only.",
    "A carbon tariff and a hospital wait can sit in one argument. Adults name the trade-off. Slogans do not."],
]);
