import { pack } from "../pack.mjs";

export const CODING_VOLUME = pack("coding", [
  ["vx-c-spec-first", "Thinking", "A spec is a test you can fail before you type",
    "Inputs, outputs, and a done-condition. ‘Make it nice’ is not a spec. Ambiguity that a human would shrug at becomes a bug.",
    "Start coding so the spec can emerge from the vibes. The compiler is a product owner.",
    "Write one example in, one example out. Then an edge. Then code toward those.",
    "A school rubric is a spec. If you cannot tick it, you do not know the job."],
  ["vx-c-idempotent", "Thinking", "Idempotent means doing it twice is the same as once",
    "A ‘set name to Kim’ can be idempotent. A ‘add $10’ is not. Retries on networks need this idea or you double-charge.",
    "If the button is pretty, clicking it twice is fine. UI is a lock.",
    "Ask what a retry would do. Then make the action safe or disable the button.",
    "A ‘submit assignment’ twice should not duplicate the file. That is a school-shaped idempotency."],
  ["vx-c-off-by-one", "Thinking", "Off-by-one lives at the fence: < vs ≤, 0 vs 1",
    "A range 1..10 inclusive is ten numbers. 0..10 exclusive of 10 is ten if you started at 0. Draw the fence posts vs the panels.",
    "Loop until it feels done. Feelings are indices.",
    "Count on paper for n=1 and n=2. Then the empty case.",
    "slice(0, 3) in Python is three items (0,1,2). The end is exclusive. That is the fence."],
  ["vx-c-state-vs-stateless", "Thinking", "State is memory the next call can trip on",
    "A function that remembers last time is stateful. A pure function is easier to test. UI is state whether you like it or not.",
    "If it works once it is stateless. Once is a proof.",
    "Name what is remembered. Then who resets it. Then a test that calls it twice.",
    "A quiz app that remembers the last score in a global is how student B sees student A. State has a privacy."],
  ["vx-c-fail-loud", "Thinking", "Failing loud is a kindness; swallowing errors is a haunted house",
    "An empty except: is how you ship a shrug. Log, then decide. A user-facing message is not a stack trace, and a stack trace is not nothing.",
    "If it did not crash it worked. Silence is success.",
    "Catch the error you can handle. Let the rest surface. Write the message you would want at 2 am.",
    "A ‘return None’ on failure without a log is how a mark of zero looks like a working program."],
  ["vx-c-binary-search-sorted", "Thinking", "Binary search needs sorted, and a midpoint that does not overflow in some languages",
    "Halve the range. If the list is unsorted you searched a rumour. Log n is the prize, not a personality.",
    "Binary search is ‘look in the middle’ of any pile. Order is optional spice.",
    "Assert sorted (or sort first, and pay n log n). Then trace two searches on paper.",
    "A phone book works because it is sorted. A bag of receipts does not."],
  ["vx-c-hash-lookup", "Thinking", "A dictionary lookup is a hash, not a scan of the universe if you stay good",
    "Average O(1) is a bet on the table. A terrible hash or a huge collision chain is a walk. Keys must be hashable (in Python, not a raw list).",
    "Dicts are magic arrays that cannot be slow. Big-O is for other people.",
    "Use a dict when you have a name→value. Use a list when order and scan are the job.",
    "if x in list is a scan. if x in set is the other hat. Pick on purpose."],
  ["vx-c-recursion-base", "Thinking", "Recursion without a base case is a stack souvenir",
    "Smaller input, guaranteed stop. A tree is a natural. A loop is often clearer for a list. Tail calls are a later luxury Python does not gift you.",
    "Recursion is always smarter. Loops are for beginners.",
    "Write the base first. Then the smaller call. Then a mental stack of depth 3.",
    "Factorial is a teaching toy. A directory walk is a real tree. Do not recurse on user data without a depth cap."],
  ["vx-c-invariant", "Thinking", "A loop invariant is what stays true while the index moves",
    "‘Everything left of i is sorted’ is a sentence you can check. If you cannot say it, you are stirring.",
    "Comments that say ‘loop here’ are invariants. The word loop is the proof.",
    "Write one sentence above the loop. Check it on the first and last iteration.",
    "Binary search’s invariant is ‘the target is in this slice if anywhere’. When the slice is empty, you are done."],
  ["vx-c-mut-vs-immut", "Thinking", "Mutation is a change in place; a new object is a different story",
    "list.append vs + that makes a new list. Hidden mutation through two names is an alias bug. Strings in Python do not mutate.",
    "If it is the same variable name it is the same object. Names are objects.",
    "Ask: did the old object change? Then who else holds a name for it.",
    "def f(x=[]): is a famous mutable default. The list lives on the function. Newcomers meet this as a ghost."],
  ["vx-c-api-contract", "Thinking", "An API is a contract about shapes, not a vibe of helpfulness",
    "Status codes, JSON keys, and versioning. Breaking a key name is a broken contract. Timeouts are part of the deal.",
    "If it returned 200 it is true. HTTP is a court.",
    "Read the docs for one endpoint. Write a tiny client that handles 4xx. Then a version header.",
    "A school API that changes overnight without a version is a lesson in why versions exist."],
  ["vx-c-complexity-talk", "Thinking", "Big-O is a growth story, not a stopwatch on n=3",
    "n² on a million is a coffee. A constant 50 ms can still be the user’s whole patience. Measure when the constant matters.",
    "If it is O(1) it is instant on a phone from 2011. Asymptotics are a battery.",
    "Count loops on the input size. Then an experiment at 10×. Then a better structure if 10× dies.",
    "Sorting then scanning can beat nested loops. n log n plus n vs n² is the usual gift."],
  ["vx-c-determinism", "Thinking", "A test that depends on a clock or a random is a flake",
    "Freeze time, seed the RNG, or inject a fake. Flakes train you to ignore red. Ignoring red is how production burns.",
    "If it failed once it was cosmic rays. Re-run until green. CI is a mood.",
    "Make the function take ‘now’ as an argument. Then a test with a fixed now.",
    "A ‘shuffle the quiz’ without a seed makes a bug you cannot replay. Replay is a civic of debugging."],
  ["vx-c-premature-opt", "Thinking", "A pretty micro-optimisation on the wrong line is a hobby",
    "Profile first. Readable then fast. A nested loop on ten items is not your villain. A network call in a loop often is.",
    "Rewrite in C before the program works. Speed is a design principle from line 1.",
    "Get it right. Measure. Then cut the actual hot spot. Then re-measure.",
    "A list comprehension is not automatically faster than a loop in a way you should care about for homework n. Readability still wins."],
  ["vx-c-naming-job", "Thinking", "A name is a comment you cannot skip",
    "d vs elapsed_days. A function called handle() handles a shrug. Verbs for functions, nouns for data — a useful default, not a law.",
    "Short names are professional. Keystrokes are expensive, bugs are cheap.",
    "Read the name without the body. If you still need the body to know the job, rename.",
    "tmp2_final_final is a archaeology. Git would have been cheaper."],
  ["vx-c-rubber-duck", "Thinking", "Explaining it out loud is a debugger that does not need a licence",
    "The bug often sits in the sentence you cannot finish. A duck, a peer, a comment. Then go back to the line.",
    "Talking is not coding. Real work is silent typing.",
    "State the expected, the actual, and the last change. Then the hypothesis.",
    "A 30-second voice note to yourself is a log. Future-you is a stranger."],
  ["vx-c-truthy-python", "Python-ish", "Empty is falsey in Python; 0 is falsey; ‘0’ is true",
    "if [] is false. if ‘0’ is true because a non-empty string. if 0.0 is false. Do not test equality to True unless you mean it.",
    "If it exists it is True. None is the only false.",
    "Use explicit is None or len, or enjoy the falsey rules on purpose. Then a test for 0 vs None.",
    "if x: pass on a numpy array is a famous trap later. Homework lists still follow the table."],
  ["vx-c-is-vs-eq", "Python-ish", "is is identity; == is equality of value",
    "Two equal lists are not the same object. None you compare with is. Interned small ints can lie to a demo.",
    "is and == are twins. Python is English.",
    "== for values, is for None/True/False (or actual aliases). Do not use is for numbers as a habit.",
    "a = []; b = []; a is b is False. a == b is True. That is the lesson."],
  ["vx-c-for-else", "Python-ish", "for/else’s else runs if you did not break",
    "A search loop: else is ‘not found’. It is not a decoration for when you feel hopeful. Most style guides hide this because it surprises.",
    "else on a for is like if/else. If the list is non-empty the else runs.",
    "Prefer a flag or a function with return. If you use for/else, comment the ‘no break’ meaning.",
    "A while/else exists too. Same surprise. Same advice."],
  ["vx-c-comprehension", "Python-ish", "A comprehension is a loop in a costume, not a speed cheat code",
    "Keep it readable. Nested comps can be a dare. A side-effect inside a comp is a crime (print, append).",
    "One-liners are always better. Width is skill.",
    "Write the loop first. Then compress if it stays obvious. Then a name for the result.",
    "[x for x in xs if p(x)] is a filter. map is a cousin. Pick one style in a file."],
  ["vx-c-unpack", "Python-ish", "Unpacking is a shape check: a, b = pair",
    "Too many values is an error. Star unpacking can eat the rest. Swap is a, b = b, a without a temp in Python.",
    "If it is a list you can always unpack three names. Length is a vibe.",
    "Match the number. Then _ for a throwaway. Then fail loud if the shape is wrong.",
    "for i, x in enumerate(xs, start=1) is unpacking a pair. Off-by-one lives in start."],
  ["vx-c-fstring", "Python-ish", "An f-string is an expression in a string, not a security fence",
    "f‘{name}’ interpolates. Do not f-string untrusted text into HTML or SQL. Format specs exist (:.2f).",
    "f-strings sanitise because they are new. New is safe.",
    "Use them for readability. Then escape or parameterise when the string leaves your trust.",
    "A debug f‘{x=}’ is a 3.8+ gift. Do not ship it in a user path without thinking."],
  ["vx-c-pathlib", "Python-ish", "A path is not a string with slashes as a personality",
    "pathlib.Path, / operator, .exists(). Windows vs POSIX. Opening without a path object still works until it does not.",
    "If it has letters it is a path. Concatenate with + and hope.",
    "Build with Path, then open. Then a test on a fake directory.",
    "User-supplied paths need a jail (no ..). That is a safety ticket, not a pathlib feature by itself."],
  ["vx-c-with-open", "Python-ish", "with open is a close that happens even when you explode",
    "A file handle is a resource. with is a context manager. Read vs write vs append are modes, not moods.",
    "Python closes files when it feels tidy. GC is a janitor with a schedule you can ignore.",
    "with open(...) as f. Then encoding=‘utf-8’ on text because Windows will surprise you.",
    "A missing encoding is how a café in a CSV becomes a salad of bytes. UTF-8 is a choice you state."],
  ["vx-c-raise-from", "Python-ish", "raise X from e keeps the chain; raise X from None hides it",
    "A wrapped error without a cause is a mystery. Chains are for humans. Do not catch Exception as a personality.",
    "Bare except and a pass is professional silence. Users love silence.",
    "Catch the specific error. Raise a clearer one with from. Then log.",
    "except Exception as e: raise MyError(‘nope’) from e is the adult. The traceback then has both."],
  ["vx-c-dataclass", "Python-ish", "A dataclass is a bundle of fields with less boilerplate",
    "Not a database. Frozen=True for a hashable record. Mutable defaults still need a factory.",
    "If it has class in the name it is OOP complete. Decorators are a degree.",
    "Use it for a plain record. Then eq/order if you mean it. Then do not hide a 400-line god object in one.",
    "@dataclass vs a dict: names and typos. A KeyError vs an attribute error. Pick for the team."],
  ["vx-c-virtualenv", "Python-ish", "A venv is a box of packages so your machine is not a soup",
    "requirements.txt is a list with versions. Two projects, two boxes. System Python is a shared kitchen.",
    "pip install into global because it is easier. Global is a community.",
    "Create venv, activate, pin versions. Then a README line. Then do not commit the venv folder.",
    "A CI that does not use the same pins is how ‘works on my laptop’ becomes a genre."],
  ["vx-c-iterator-once", "Python-ish", "An iterator can be a one-shot; a list you can walk twice",
    "map() in Python 3 is lazy. list() to reify. A for that empties a generator surprises newcomers.",
    "If it is iterable you can loop forever. Iterables are wells.",
    "If you need two passes, list it (if it fits). Then a test that does two loops.",
    "zip stops at the shortest. zip(..., strict=True) in new Python yells. Length mismatch is a bug."],
  ["vx-c-scope-le", "Python-ish", "A comprehension’s loop variable in Py3 does not leak; a for does",
    "for i in …; then i still exists. [i for i in …] does not leak i (Py3). Closures on loop variables in lambdas are a famous trap (use default arg).",
    "Variables evaporate at the indent. Python is a vacuum.",
    "Do not rely on a leftover i. Name the leftover on purpose if you must.",
    "A lambda in a loop capturing i without a default sees the last i. That bug has a body count."],
  ["vx-c-type-hint", "Python-ish", "A hint is a note for humans and linters, not a runtime fence (usually)",
    "def f(x: int) -> str still accepts a str at runtime. mypy is a separate hat. Optional[x] is x | None.",
    "If it is hinted it cannot go wrong. Types are police.",
    "Hint the public functions. Then a checker in CI if the project means it.",
    "Any is a shrug. A pile of Any is JavaScript in a trench coat."],
  ["vx-c-main-guard", "Python-ish", "if __name__ == ‘__main__’ stops import from launching the rocket",
    "Import should load functions. A script should run a main. Tests import. A missing guard is a surprise print.",
    "Python files are programs. Import is a myth.",
    "Put work in main(). Guard it. Then import the functions in a test.",
    "A circular import often appears when everyone runs on import. Guards and lazy imports are cousins."],
  ["vx-c-semantic-html", "Web", "A button is a button; a div with a click is a trap for keyboards",
    "button, a, label, heading levels in order. ARIA is a patch, not a first language. Semantic is the product.",
    "If it has an onclick it is accessible. Mice are the world.",
    "Use the native element. Then keyboard. Then a screen reader pass if you can.",
    "A <div role=button> without tabindex and keys is a museum of almost."],
  ["vx-c-css-cascade", "Web", "The cascade is origin, importance, specificity, then source order",
    "!important is a truce you will regret. A 0,1,0 class beats a 0,0,1 element. Inline is a hammer.",
    "The last rule in the file always wins. Files are a timeline of truth.",
    "Count IDs, classes, elements. Then delete a fight instead of adding a third class named final_final.",
    "A user stylesheet and a browser default sit in the origin story. That is why ‘reset’ exists."],
  ["vx-c-box-sizing", "Web", "content-box vs border-box is where the width lives",
    "border-box puts padding in the width you named. The old content-box grows the box when you pad. Layouts die here.",
    "Width is the number in the CSS. Padding is a spiritual extra that cannot count.",
    "Set box-sizing: border-box as a project default. Then measure in devtools, not in hope.",
    "A 100% + padding overflow is this. So is a 320px phone with a 20px pad each side."],
  ["vx-c-event-bubble", "Web", "Clicks bubble unless you stop them; capture is the way down",
    "A parent listener will see a child click. stopPropagation is a smell if you need it everywhere. Delegation is a list on a parent.",
    "The target is the only node that hears. Trees are silent.",
    "Know target vs currentTarget. Then one listener on a list, not a thousand on items.",
    "A modal that closes because the click bubbled to the overlay is a classic. So is a modal that will not close because you stopped too much."],
  ["vx-c-get-vs-post", "Web", "GET should not smash; POST is a change with a body",
    "Idempotent fetch vs a purchase. A GET with a side effect is a prefetch disaster. PUT/PATCH/DELETE are later verbs with meanings.",
    "If the URL is pretty it is a GET. Pretty is safe.",
    "Read for GET, change for POST. Then a CSRF token on the change. Then do not put secrets in the query string.",
    "A ‘delete?id=’ link in an email is a GET with a knife. Prefetch or a preview bot will click it."],
  ["vx-c-cors", "Web", "CORS is a browser rule about who may read a response, not a firewall of the server",
    "A server can still be hit by curl. CORS protects the user’s cookie-bearing browser. * with credentials is a no.",
    "CORS is encryption. The C is crypto.",
    "If you own both ends, set a tight origin. Then remember mobile apps and servers are not browsers.",
    "An error in the console is the browser talking. The network tab still shows the response. That split confuses everyone once."],
  ["vx-c-jwt-not-magic", "Web", "A JWT is a signed blob, not a vault, not a session by itself",
    "Anyone can read the payload. Signature checks tamper. Logout is hard if you cannot revoke. Storage (localStorage vs cookie) is a XSS vs CSRF trade.",
    "If it is a token it is unstealable. JWTs are holy.",
    "Know what is in the payload (no secrets). Then expiry. Then a server session if you need revoke.",
    "alg: none is a museum vulnerability. Libraries still need a allow-list of algs."],
  ["vx-c-xss-escape", "Web", "Untrusted text in HTML is a program unless you escape",
    "innerHTML += user is a classic. A display name can be a script. React’s default escape is a seatbelt you can still unbuckle (dangerouslySetInnerHTML).",
    "If it is in a string it cannot run. Quotes are a fence.",
    "Treat every user byte as hostile. Escape for HTML, then for attributes, then for JS contexts separately.",
    "A markdown renderer is an HTML injector. Sanitise. A profile bio is a battlefield."],
  ["vx-c-sql-param", "Web", "A parameterised query is a door; string-gluing SQL is a hole",
    "Placeholders, never f-string a name into WHERE. OR 1=1 is a cartoon that still works on amateurs.",
    "If the user is a friend they cannot do SQL. Trust is a sanitiser.",
    "Use the library’s parameters. Then least privilege on the DB user. Then do not log the raw password.",
    "A school ‘search students’ box is enough of an injection lab. Do not practise on a real roll."],
  ["vx-c-csrf", "Web", "CSRF is the browser as a confused deputy with cookies",
    "A hidden form on evil.example posts to your bank if cookies ride. SameSite helps. Tokens on state-changing forms help.",
    "If they are logged in they meant it. Cookies are intent.",
    "Token plus SameSite plus do not use GET to change. Then a test that omits the token.",
    "A ‘add admin’ GET from an image tag is a 2005 textbook and still a mood in old apps."],
  ["vx-c-http-cache", "Web", "A cache header is a contract with a shared box",
    "Cache-Control, ETag, a CDN. A user-private page with public cache is a leak. 304 is a kindness.",
    "Refresh means the server ran. The lightning bolt in the tab is a vibe.",
    "Separate public assets (long cache + hashed names) from private HTML (no-store). Then bust on deploy.",
    "A ‘it works on my machine after refresh’ can be a cache of a broken JS. Hard reload is a diagnostic, not a product."],
  ["vx-c-responsive-bp", "Web", "A breakpoint is a layout change, not a phone brand tattoo",
    "Content first, then a width where it breaks. px vs rem. A ‘iPhone 12 width’ is a yearbook.",
    "If it looks fine on your laptop it is responsive. Laptops are the web.",
    "Resize until it cries. Fix that width. Then keyboard zoom as a cousin of access.",
    "A hamburger that hides the only nav without a label is a mobile fail. Touch targets are 44 px-ish for a reason."],
  ["vx-c-a11y-alt", "Web", "Alt is a replacement, not a SEO poem, not empty on a meaningful image",
    "Decorative: empty alt. Informative: what the image does in the document. A chart needs a text equivalent, not ‘chart.png’.",
    "Alt should list every colour. More words are more access.",
    "Write the sentence you would use if the image failed. Then skip it if it is already in a caption.",
    "A CAPTCHA that is only an image is a lock on people who cannot see. That is a product choice."],
  ["vx-c-spa-route", "Web", "A client route is not a server page unless you made it so",
    "Refresh on /about can 404 if the server does not fall back. History API vs hash. SEO and share links care.",
    "If the URL changed the server knows. URLs are a fashion.",
    "Configure the fallback. Then a real URL for a real document if you need share/SEO. Then a title change on navigate.",
    "A school project on file:// will lie about fetch and routes. Use a tiny static server."],
  ["vx-c-json-shape", "Data", "JSON is a shape: types, keys, and null as a citizen",
    "Trailing commas die. Keys are strings. A number that should be a string (leading zeros, big ints) will bite. Validate against a schema if it matters.",
    "If it parsed it is true. parse is a court.",
    "Check types. Then a missing key vs null. Then a version field for later you.",
    "JSON is not JavaScript. undefined is not JSON. Comments are not JSON (usually)."],
  ["vx-c-csv-feelings", "Data", "CSV is a text format with feelings: commas, quotes, encodings",
    "A name with a comma needs quotes. Excel will eat leading zeros on postcodes. UTF-8 vs a Windows café.",
    "If it opens in Sheets it is clean. Spreadsheets are a spec.",
    "Use a real parser. Then a dialect (delimiter). Then do not double-parse.",
    "A BOM at the start is a Windows souvenir that breaks the first header. Strip or write utf-8-sig on purpose."],
  ["vx-c-join-match", "Data", "A join is a match between tables, not a vibe of relatedness",
    "Inner drops non-matches. Left keeps the left. A Cartesian product is a missing ON. Keys must mean the same thing.",
    "If two tables are in the same file they join themselves. Folders are relations.",
    "Name the key. Then inner vs left. Then a count before and after so you see the drop.",
    "A student_id that was reused next year is a key crime. Surrogate keys exist because of this."],
  ["vx-c-primary-key", "Data", "A primary key uniquely names a row, not ‘the important column’",
    "Stable, unique, not null. Email as a key fails when people change email. Composite keys are a pair that together unique.",
    "The first column is the key. Left is important.",
    "Pick a surrogate if the natural one will move. Then a unique constraint on the natural anyway if you need it.",
    "A class roll name is not a key. Two Sam Chen is a Monday."],
  ["vx-c-normalise", "Data", "A fact that repeats in many rows wanted its own table",
    "A postcode’s suburb name copied 400 times will drift. 3NF is a school stop. Denormalise on purpose for speed, with a comment.",
    "Wide tables are simpler so they are better. Spreadsheets are the ideal form.",
    "If a fact would update in many rows, it wanted its own table. Then a foreign key.",
    "A ‘year 10, year 10, year 10’ typed beside each student is a gift for typos. A year table is dull and correct."],
  ["vx-c-null-mean", "Data", "Null is a missing, a unknown, or a not-applicable — pick a dialect and stay",
    "Average that skips nulls vs zeros. A blank CSV cell vs the string ‘null’. SQL NULL is not equal to NULL.",
    "Null is zero. Empty is false. Done.",
    "Document what missing means. Then a query that does not turn missing into 0 by accident.",
    "A 0 km run vs a missing run is training data. Collapsing them is how you invent athletes."],
  ["vx-c-tidy-data", "Data", "Tidy data: one row an observation, one column a variable",
    "A spreadsheet with years as column headers is wide. Analysis wants long. Dates as dates, not strings that sort like 1, 10, 2.",
    "If it is coloured it is tidy. Fill is a schema.",
    "Melt/pivot on purpose. Then a check that n rows makes sense.",
    "A merged cell in Excel is a crime against a parser. Unmerge is a civic."],
  ["vx-c-chart-lie", "Data", "A chart can lie with a chopped axis, a 3D pie, or a dual axis",
    "Start at zero for a bar of counts. A line of temperature may not need zero. Area is not a third variable you invented with a glow.",
    "If it is colourful it is clear. Rainbow is a scale.",
    "Name the encoding (position, length). Then a lie factor. Then a plain table as backup.",
    "A truncated y-axis on a bar of ‘crime’ is a classic. Dual axis ‘likes vs temperature’ is a cousin."],
  ["vx-c-mean-code", "Data", "An average in code still needs a story: of whom, of what, missing how",
    "np.mean of an empty list is a nan or a crash depending on the library. Outliers. Weighted means.",
    "mean() is the truth. Functions are priests.",
    "Print n, min, max, mean. Then a median. Then who is in the set.",
    "A mean of means of school classes without weighting by size is how a tiny class bosses the story."],
  ["vx-c-person-data", "Data", "A dataset can be a person: re-identification is a sport",
    "Postcode plus birthdate plus gender can be a name. Anonymise is harder than deleting a column called name. Ethics forms exist.",
    "If I removed the name column it is anonymous. Columns are identities.",
    "Minimise, aggregate, and do not publish a ‘de-identified’ microfile of a small town.",
    "A school open-data portal of ‘wellbeing’ at the student grain is a incident. Grain is the ethics."],
  ["vx-c-messy-job", "Data", "Messy data is the job: types, duplicates, a unit hiding in a cell",
    "‘n/a’, ‘NA’, ‘-’, a footnote in row 40000. Dates in two continents’ formats. Duplicates that are almost.",
    "If it imported, it is clean. Import is a sacrament.",
    "Profile first (unique counts, nulls). Then a rule for each mess. Then a log of what you changed.",
    "A 5’11\" in a cm column is a unit crime. So is a kg in a g field without a header."],
  ["vx-c-index-speed", "Data", "An index is a lookup structure, not a moral ranking of columns",
    "B-tree / hash in a DB. Too many indexes slow writes. A query that does not use the index is a sequential walk in a costume.",
    "INDEX is a keyword that makes everything fast. Keywords are turbo.",
    "Explain the query. Then index the filter/join keys you actually use. Then measure writes.",
    "A LIKE ‘%foo%’ will often skip the index. Leading wildcard is a scan."],
  ["vx-c-transaction", "Data", "A transaction is all-or-nothing, not a vibe of trying hard",
    "Debit one row, credit the other, commit. A crash in the middle without a transaction is a vanished $10. Isolation levels are a later swamp.",
    "If both lines of code ran it is atomic. Lines are a transaction.",
    "Begin, two writes, commit. Rollback on error. Then do not hold a transaction while you wait for a human.",
    "A school ‘transfer house points’ without a transaction is a comedy of double-spend."],
  ["vx-c-time-tz", "Data", "A timestamp without a timezone is a fight waiting",
    "UTC store, local display. DST is a political hour. ‘Timestamp’ in some DBs is naive. ISO 8601 with an offset is a kindness.",
    "If it has a colon it is universal. Clocks are global.",
    "Store UTC. Convert at the edge. Then test a DST spring-forward.",
    "A calendar invite at 9 am Australia/Sydney is not 9 am UTC. Melbourne and Adelaide disagree on 30 minutes."],
  ["vx-c-regex-limit", "Data", "A regex is a pattern, not a parser for HTML or email as a life",
    "You can validate a shape. You cannot ‘parse HTML with regex’ as a personality. Catastrophic backtracking is a DoS on your own CPU.",
    "If it matches it is valid email. RFC 5322 is a regex you can finish tonight.",
    "Use a parser for nested grammars. Use regex for a tight token. Then a timeout if the pattern is user-supplied.",
    "A ‘valid email’ in a school form that bans + is how you fight Gmail aliases. The + is real."],
  ["vx-c-commit-sentence", "Craft", "A commit is a checkpoint with a sentence, not a dump of ‘fixes’",
    "Subject in the imperative: add tests for empty list. One idea per commit if you can. Bisect will thank you.",
    "git commit -m ‘asdf’ is a lifestyle. History is a trash can.",
    "Stage the related hunks. Write why if the what is obvious from the diff. Then do not mix a reformat with a bugfix.",
    "A 40-file ‘WIP’ on main is how you invent archaeology. Branches exist."],
  ["vx-c-branch-small", "Craft", "A branch is a parallel universe that should rejoin while it is still small",
    "Long-lived branches are merge pain. rebase vs merge is a house style. Delete the branch after.",
    "One branch for the whole term is simpler. Simpler is professional.",
    "Branch, small PR, review, merge. Then delete. Then do not force-push a shared branch without a warning.",
    "A school group with three people committing to main with no pull is a race. Pull then push is a civic."],
  ["vx-c-pr-review", "Craft", "A review is a second brain, not a spelling hunt only",
    "Correctness, tests, names, a secret. Nitpicks last. ‘LGTM’ on a 2000-line dump is a shrug.",
    "If it runs on my machine the review is done. Green is a peer.",
    "Read the diff as a user of the API. Ask for a test on the bug. Then a kind comment.",
    "A review that only restyles is a missed defect. A review that only shames is a culture bug."],
  ["vx-c-test-fail-first", "Craft", "A test is a claim that can fail; a test that cannot fail is a compliment",
    "Red, green, refactor as a ritual. Assertion on the behaviour, not on the private garnish. Flakes are a different disease.",
    "If the test is green it was always going to be. Write it after and never watch it fail.",
    "Write a failing test that names the bug. Then fix. Then watch it pass. Then a second case.",
    "assert True is a joke. Coverage 100% with no assertions is a costume."],
  ["vx-c-ci-green", "Craft", "CI is a machine that should match the README, not a unique snowflake laptop",
    "Same Python version, same pins. A hidden global package on your Mac is not CI. Fail the build on warnings if you mean it.",
    "If it is green on my laptop, CI is optional theatre. Laptops are the product.",
    "Run the same commands locally. Then pin. Then a badge that is not a lie.",
    "A skipped test in CI ‘because it is slow’ is a test that does not exist. Time is a budget, not a delete key."],
  ["vx-c-dep-clock", "Craft", "A library is a dependency with a clock: versions, licences, abandonware",
    "Pin. Read the licence (GPL vs MIT vs you-cannot-use-this-at-school). A left-pad incident is a supply chain.",
    "npm install whatever looks popular. Stars are audits.",
    "Add with a pin, a reason, and a licence check. Then fewer dependencies if a 20-line function would do.",
    "A homework that imports a 40 MB toolkit to reverse a string is a comedy. The stdlib has tools."],
  ["vx-c-readme-run", "Craft", "A README is the door: how to run, how to test, who to blame",
    "Clone, venv, command, expected output. A screenshot of an IDE is not a runbook. Assumptions about ‘obviously you have Postgres’ are bugs.",
    "Code is self-documenting. Names replace manuals.",
    "Write the commands you actually used. Then a new clone on a second machine if you can.",
    "A README that starts with the architecture novel and never shows python app.py will not get run."],
  ["vx-c-comment-why", "Craft", "A comment says why, not what the syntax already said",
    "i += 1  # increment i is a noise. A comment about a weird vendor API is gold. Dead comments that contradict the code are worse than none.",
    "Comment every line so it looks professional. Density is care.",
    "Delete the restated. Keep the constraint (legal, hardware, a bug number).",
    "A TODO without an owner is a fossil. Date it or ticket it."],
  ["vx-c-dead-code", "Craft", "Dead code is a liar that still compiles",
    "Commented-out blocks, unused functions, a flag that is always true. Readers will try to understand it. Git remembers; your file does not have to.",
    "Keep the old way in a comment in case. Comments are a backup.",
    "Delete. The history is in git. Then a test so you cannot accidentally need the ghost.",
    "if False: is a museum. So is a function only called from a test you deleted."],
  ["vx-c-log-level", "Craft", "A log is a time series for a stranger at 2 am",
    "Error vs warn vs info vs debug. Secrets in logs are incidents. A print in a library is a rude neighbour.",
    "Log everything at error so it is important. Caps are a level.",
    "Log the correlation id, the user id you are allowed to, and the outcome. Then rotate. Then do not log passwords.",
    "A ‘it failed’ without a reason is a fortune cookie. Include the input shape, not the secret."],
  ["vx-c-feature-flag", "Craft", "A flag is a runtime fork, not a second git universe forever",
    "Ship dark, test, then remove the flag. A graveyard of flags is a combinatorial explosion. Naming matters.",
    "Flags are free. Leave them all on in production as a museum.",
    "One flag, an expiry, an owner. Then delete. Then do not nest flags four deep.",
    "A school demo with a cheat flag left on is a classic. The flag is a product decision."],
  ["vx-c-code-review-self", "Craft", "A self-review of the diff is cheaper than a peer finding a console.log of a token",
    "git diff before you push. A debug sleep, a hardcoded URL, a file you did not mean. The reviewer is not your linter of first resort.",
    "Pushing is the review. The cloud will catch it.",
    "Read the PR as a stranger. Then a checklist you actually use (secrets, tests, README).",
    "A .env committed once is in the history even if you delete it. Rotate the secret. That is the extra."],
  ["vx-c-license-other", "Craft", "Other people’s code has a licence, and so should yours",
    "MIT, GPL, proprietary, ‘found on a gist’. School work still has a policy. Copying a classmate’s function is a different licence called cheating.",
    "If it is on GitHub it is free. Public is a licence.",
    "Read the LICENSE. Then attribute. Then do not paste GPL into a proprietary blob without meaning to.",
    "A screenshot of Stack Overflow with no attribution is still a source. The site’s licence is CC-BY-SA for many posts — follow it."],
  ["vx-c-secret-env", "Safety", "Secrets are not in the repo, not in the screenshot, not in the student slide",
    "env vars, a secret manager, .gitignore. A leaked API key is a bill. Rotating is the move, not hoping.",
    "If the repo is private the key is fine. Private is a vault.",
    "gitignore .env. Then a .env.example without values. Then rotate if it leaked. Then check git history.",
    "A Discord bot token in a commit is a takeover. The extra is: the token is a password."],
  ["vx-c-least-priv-key", "Safety", "A key with admin on the whole cloud is a hobby incident",
    "Scope the token. Read-only if it only reads. A CI token that can delete the org is a plot device.",
    "Admin is simpler so it is safer (fewer settings). Simplicity is a firewall.",
    "Create a role that can only the job. Then rotate. Then do not share it in a group chat.",
    "A school AWS classroom account with a root key on a slide is a horror genre. Root is a last hat."],
  ["vx-c-supply-chain", "Safety", "npm/pypi install is running someone else’s code on your machine",
    "Typosquatting, a compromised maintainer, a postinstall script. Pin and hash if you are being careful. Review sudden version jumps.",
    "If it has many stars it is safe. Popularity is an audit.",
    "Pin, use lockfiles, and be suspicious of a package with a name one letter off. Then a lockfile commit.",
    "A ‘left-pad’ deletion is availability. A malicious pad is integrity. Both are supply chain."],
  ["vx-c-input-validate", "Safety", "Validate on the server even if the form did; the client is a suggestion",
    "A hidden field, a disabled button, a React check — all skippable. Types, ranges, authz (this user may not edit that id).",
    "If the UI hides it they cannot send it. UI is a security boundary.",
    "Re-check every field on the server. Then authorise the object, not only the route. Then a test that tampers with the id.",
    "A ‘edit user 17’ while logged in as 16 is IDOR. Sequential ids make it a sport."],
  ["vx-c-authz-not-authn", "Safety", "Authentication is who; authorisation is what they may do",
    "Logged in is not ‘may delete the school’. Roles, ownership, a check on every handler. A missing check on an extra endpoint is the usual hole.",
    "If they have a cookie they are staff. Cookies are ranks.",
    "Name the role. Then a test as a lesser user. Then do not hide the button and call it authz.",
    "A student API that lists all students because the front-end only showed one is a leak. The server is the bouncer."],
  ["vx-c-https-pipe", "Safety", "HTTPS is a pipe with a lock, not a holy site, not ‘the page is good’",
    "TLS stops some snooping and tampering in transit. A phishing site can have HTTPS. Mixed content is a hole.",
    "The padlock means the company is virtuous. Certificates are morals.",
    "Use HTTPS everywhere. Then still check the domain. Then HSTS as a later hat.",
    "A cafe Wi-Fi plus HTTP is a classroom demonstration of a password in flight. Do not use real passwords."],
  ["vx-c-session-cookie", "Safety", "A session is a server-side memory plus a cookie, not a vibe of logged-in",
    "HttpOnly, Secure, SameSite. Session fixation. Logout should invalidate. A JWT in localStorage is a XSS piñata.",
    "If the browser remembers me I am authenticated forever. Remember me is a vault.",
    "Set cookie flags. Expire. Rotate on login. Then a logout that actually logs out.",
    "A shared school computer plus remember-me is an account swap. Timeouts exist because of this."],
  ["vx-c-privacy-log", "Safety", "A log of searches can be a person; minimise",
    "IP plus timestamp plus query. School systems are not exempt from being kind. Retention is a policy.",
    "Logs are for admins so they can be intimate. Admin is a family.",
    "Log ids not names if you can. Then a retention. Then access control on the log store.",
    "A ‘debug’ that prints the whole student object including address is a privacy incident in a terminal."],
  ["vx-c-untrusted-pickle", "Safety", "Pickle, YAML load, and eval are loaders that can be programs",
    "Unpickling untrusted bytes is RCE. yaml.load vs safe_load. eval on a homework ‘calculator’ is a teaching incident.",
    "If it is data it cannot run. Serialisation is a box.",
    "Use JSON for untrusted. Then a schema. Then do not eval.",
    "A ‘save game’ pickle on a USB in a class is a plot. json is boring and correct."],
  ["vx-c-path-traversal", "Safety", "A .. in a file path is a walk toward /etc",
    "User-supplied filenames. Zip slip. A download?file= is a classic. Jail to a directory and resolve, then check the prefix.",
    "If the UI only shows .txt they cannot type ..  UI is a chroot.",
    "Resolve the path, then startswith the jail. Then a test with ../../. Then do not unzip untrusted without a library that blocks slip.",
    "A school ‘image gallery’ that takes a path is enough of a lab. Do not point it at the real roll."],
  ["vx-c-ssrf", "Safety", "SSRF is your server as a proxy into places the user should not reach",
    "A ‘fetch this URL for a preview’ that hits 169.254.169.254 or an internal admin. Allow-lists of schemes and hosts.",
    "If the server fetches it it is public. Fetch is a browser.",
    "Do not fetch user URLs without a allow-list. Then block link-local and private ranges. Then a timeout.",
    "A homework ‘screenshot this page’ is a surprising SSRF lab. Cloud metadata endpoints are the treasure."],
  ["vx-c-rate-limit", "Safety", "A login without a rate limit is a password festival",
    "Slow down, captcha, lockout with care (DoS on an account). Credential stuffing is a list vs your form. MFA still wants a limit.",
    "If the password is strong they cannot guess. Strength is a rate limit.",
    "Limit by IP and by account. Then log. Then do not email ‘your password is’ in a reset.",
    "A school portal that emails the password in clear is a 2004 fossil. Reset tokens expire."],
  ["vx-c-dependency-cve", "Safety", "A CVE is a named hole; ‘we will update later’ is a calendar of exposure",
    "npm audit is noisy and still sometimes right. A pin that is three years old is a museum. Read the advisory, not only the colour.",
    "If the app works, the CVE is theoretical. Working is patched.",
    "Update, test, ship. Then a process, not a hero weekend after the news.",
    "Log4Shell was a homework in ‘do we even know what we ship’. SBOMs are a later inventory."],
  ["vx-c-threat-model", "Safety", "A threat model is who might try what, not a vibe of ‘hackers’",
    "A classmate, a sibling, a leaked laptop, a curious admin. STRIDE is a later menu. School apps have school threats (cheating, bullying, doxxing).",
    "Security is a padlock icon. Threats are movies.",
    "List assets, actors, and a cheap control. Then do the control. Then do not pentest a live roll as a dare.",
    "A ‘private’ padlet with a guessable URL is a threat model of link-sharing. Links leak."],
  ["vx-c-list-alias", "Python-ish", "b = a on a list is two names for one sticky note",
    "a.append changes b. Copy with list(a) or a[:]. Nested lists still share inner objects unless you deepcopy.",
    "If the names differ the lists differ. Names are copies.",
    "Draw two arrows to one box. Then copy if you meant a fork. Then a test that mutates one.",
    "def f(x): x.append(1) mutates the caller’s list. That is not a return. Document it or do not do it."],
  ["vx-c-status-codes", "Web", "A status code is a sentence: 2xx ok, 4xx you, 5xx us",
    "404 is missing, 403 is no, 401 is who are you, 409 is conflict, 429 is slow down. 200 with an error in JSON is a lie some APIs still tell.",
    "If the page loaded it was 200. Spinners are status codes.",
    "Pick the code that matches the contract. Then a body that a client can parse. Then do not 200 a failed login.",
    "A 302 login wall on an API is a browser costume. APIs usually want 401 plus a JSON."],
  ["vx-c-pagination", "Data", "A page of results is a window, not the table",
    "OFFSET that skips 10 million is a walk. Cursor/keyset is kinder. A client that requests page size 1e9 is a DoS.",
    "If you do not see it, it does not exist. UI is the database.",
    "Cap the limit. Prefer a stable sort plus a cursor. Then a next-page token that is not a lie.",
    "A ‘export all’ without a stream is a memory bomb. Chunk it."],
  ["vx-c-semver", "Craft", "Semver is MAJOR.MINOR.PATCH as a social contract, not a vibe of bigness",
    "Breaking change bumps major. A 0.x is a warning that anything can move. A lockfile is how you actually repeat a build.",
    "If the number went up it is better. Bigger is safer.",
    "Read the changelog before you bump major. Then pin. Then test.",
    "A library that does a breaking change in a patch is a contract break. Trust is earned in changelogs."],
  ["vx-c-owasp-top", "Safety", "OWASP Top 10 is a menu of common web holes, not a complete universe",
    "Injection, broken authz, XSS, and friends. It is a teaching list. Your homework app can still invent a new hole.",
    "If it is not on the poster it is safe. Posters are a standard.",
    "Skim the current list. Then map each to a control you actually have. Then test one.",
    "A school CRUD app hits half the list with default settings. That is why the list exists."],
  ["vx-c-n-plus-one", "Data", "N+1 is a query in a loop: one plus one per row",
    "Fetch a class, then a query per student. 31 queries for 30 kids. Join or prefetch. An ORM makes this easy to do by accident.",
    "If the code is pretty the SQL is pretty. Abstraction is efficiency.",
    "Log the queries. Then join. Then a test with n=100 that should not do 101 round trips.",
    "A page that feels fine with 3 rows and dies with 300 is this. Dev data lied."],
  ["vx-c-graceful-deg", "Web", "If the JS dies, the HTML should still mean something",
    "A form that can POST without a SPA. Progressive enhancement. A blank div#app is a single point of failure.",
    "Everyone has a fast phone and perfect JS. 2026 is finished.",
    "Render useful HTML first. Then enhance. Then a noscript or a real form.",
    "A government form that is a blank page without JS is a civic failure. Schools copy that failure for free."],
  ["vx-c-pair-nav", "Craft", "Pairing is a navigation of two minds, not a driver who types while a spectator sighs",
    "Switch. Talk the invariant. The navigator watches the pit, not their phone. Remote pairing needs a cursor both can see.",
    "The faster typist should always drive. Speed is skill.",
    "Timebox a switch. Then a goal for the next ten minutes. Then do not grab the keyboard without a sentence.",
    "A school pair where one person owns the laptop overnight is not pairing. It is a bus factor of one with a witness."],
  ["vx-c-binary-places", "Thinking", "Binary is places of two, the same idea as decimal places of ten",
    "1010₂ is 10₁₀. Bits are not ‘computer dust’. Overflow is when a place does not exist. Two’s complement is a later costume for negatives.",
    "Binary is a secret code unrelated to place value. Maths stops at the computer case.",
    "Write the place headers (8-4-2-1). Then convert a small number both ways. Then an overflow on an 8-bit toy.",
    "A colour channel 0–255 is 8 bits. 256 is not a valid byte. That is this lesson in a paint program."],
]);
