import { pack } from "../pack.mjs";

export const DIGITAL_VOLUME = pack("digital", [
  ["vx-d-passkey-phish", "Safety extras", "A passkey is a site-bound secret in a device; it does not type into a fake box the way a password does",
    "A phishing page that looks like a bank still wants a typed secret. A passkey handshake is pickier about the real domain. A backup of the passkey is still a vault you must not lose.",
    "If it is new it is unphishable forever, even if I screenshot the QR and send it to a uncle. Also: passkeys are a Apple plot so skip them.",
    "Turn them on for email and school if offered. Keep a password manager as a sibling, not a rival. Store recovery in a drawer, not a camera roll.",
    "A ‘scan this QR to recover your passkey’ text is still a script. The original phish path’s pause still applies."],
  ["vx-d-sim-swap", "Safety extras", "A SIM-swap is a thief with a telco story; SMS codes are the weaker sibling because of this",
    "They talk a shop into your number. Then the SMS MFA is theirs. App-based MFA and a hardware key are a thicker door. A PIN on the telco account is a boring civic.",
    "If they have my last four digits they are the bank. Those are on a lot of letters. Also: SIM is a tiny card so it cannot be a identity.",
    "Set a telco PIN. Prefer an authenticator app. Treat a sudden ‘no service’ as a possible swap, not only a basement.",
    "A ‘your number is moving’ SMS you did not ask for is a Tuesday to ring the telco on a number from a bill, not from the SMS."],
  ["vx-d-homograph", "Safety extras", "A lookalike letter in a URL is a costume; rnicrosoft is a classic, so is a foreign lookalike o",
    "Homograph, a punycode, a extra dash. Hover, do not click as a sport. Type the address you know. Mail merge is not magic, it is a tool.",
    "If the logo is crisp and they know my name, it is real. Also: if it is HTTPS it cannot be a costume. Padlocks are a personality.",
    "Pause. Another channel. Read the domain aloud. A password manager that will not fill on the wrong host is a seatbelt.",
    "A QR on a parking meter can be a phish with legs. Look at the sticker’s age. The original phish path already pointed; this is the letter-level."],
  ["vx-d-bec-invoice", "Safety extras", "A business-email compromise is a lookalike boss and a changed bank detail; the urgency is the product",
    "A real thread, a extra character in the domain, a ‘new account for this invoice’. Gift cards for a tax office are a cousin. Hang up and use a number from a statement.",
    "If they have the last invoice number they are accounts. Numbers are a identity. Also: if it is internal chat it cannot be a costume.",
    "Call the known number. Compare the BSB on a second channel. A $ change of destination is a stop, not a Friday favour.",
    "A school canteen ‘new supplier’ email is a BEC with a sausage. Sausages still cost a real dollar."],
  ["vx-d-macro-doc", "Safety extras", "A document that demands Enable macros to view is a plot; the invoice.odt.exe is a cousin",
    "Ransomware’s favourite foyer. A school can be a target. This is not a how-to. A USB photos-from-camp on a desk is a vector the original USB path named.",
    "If I pay I am a customer and they will honour the brand. Criminals have a Trustpilot. Also: macros are a Microsoft feature so they are safe.",
    "Do not enable. Tell an adult if the screen is a skull. Backups that are not attached. A patch. Do not open the double extension.",
    "A ‘enable content’ yellow bar on a unexpected resume is a yellow bar. Yellow is a stop, not a go."],
  ["vx-d-juice-jack", "Safety extras", "A public USB charge port is a data conversation that can pretend to be a power point",
    "A power-only cable or a wall wart you own is a boring fix. A stolen session is a different file from a empty battery. Airports are a hallway.",
    "If it is a charger it is only electrons. USB is a charger. Also: a brick with a brand is a ethics board.",
    "Carry a plug. Use a power-only pigtail if you must. Do not unlock the phone on a borrowed lead as a sport.",
    "A ‘free charging lounge’ with a extra cable already in the port is a story. Bring yours."],
  ["vx-d-cert-warning", "Safety extras", "A certificate warning is a stop sign, not a style you click through because you are late",
    "Expired, a name mismatch, a captive portal that is a cafe. HTTPS helps and is not a personality. A fake SSID that looks like the cafe is a hallway with a costume.",
    "Warnings are for other people. I am late. Also: if it is a cafe it is safe because I bought a muffin.",
    "If it is your bank, do not continue. If it is a cafe portal, use the portal then HTTPS for anything you care about — or mobile data for a bank.",
    "A ‘Free Airport WiFi’ with extra spaces is a classic. Ask the board. The original public-wifi path agrees."],
  ["vx-d-ext-malware", "Safety extras", "A browser extension is code in your logged-in life; a ‘free coupon’ add-on is a shop of a harvest",
    "Permissions to read every page. A school laptop may block them for a reason. Sideload is a foyer. Updates of a sketchy add-on are a second chance to go wrong.",
    "If it is in the store it only asks for what it needs. Stores are ethics boards. Also: more extensions is more productivity.",
    "Install few. Read the permission. Remove the coupon vampire. A separate profile for sketchy is a hat, not a personality.",
    "A ‘PDF printer’ extension that wants all sites is a printer with a appetite. OS print exists."],
  ["vx-d-sideload", "Safety extras", "A APK from a Telegram is a sideload; the store was a filter, not a vibe of capitalism you owed a rebellion",
    "Unsigned, a clone of a bank app, a game skin that is a harvest. Jailbreak/root is a extra door. School MDM exists because of this foyer.",
    "If I can get it cheaper outside the store I am smart. Sideload is a saving. Also: stores never have malware so only stores exist as a moral.",
    "Do not. If a class needs a special build, IT does it. A second-hand ‘modded’ game is a common trap.",
    "A ‘too good’ rate on a game currency is a smell. The original money-online path agrees about a walk."],
  ["vx-d-disk-crypt", "Safety extras", "A stolen laptop without disk encryption is a front door with a handle; a lock screen is only a curtain",
    "BitLocker/FileVault neighbourhood. A school device may already be on. A BIOS password is a cousin, not a substitute. Remote wipe is a policy if they offer it.",
    "If I am holding it, it does not need a lock. My hands are authentication. Also: if it is off it is safe, thieves cannot unscrew.",
    "Turn encryption on. Timeout 1–2 minutes. A friend-borrowing rule. Know whether the school already did it.",
    "A photo of a face-down phone in a change room is a story. Lock it. The original lock-device path is the curtain; this is the door."],
  ["vx-d-firmware", "Safety extras", "A router and a TV are computers with a crumb tray; default passwords and a skipped firmware are a botnet foyer",
    "The original IoT path named the toaster. Here: the home gateway is the castle gate. WPS buttons and hidden SSIDs are a theatre, not a castle.",
    "If it is a fridge it is not a computer. Computers are laptops. Safe. Also: routers are immortal, never update, it breaks the printer.",
    "Change the default. Guest network for junk IoT. Update the gateway on a calm Tuesday. A camera that is not a toilet.",
    "A ‘smart’ lock with a dead battery is a physical problem. Have a key. The original IoT path agrees."],
  ["vx-d-vpn-trust", "Safety extras", "A VPN is a shift of trust, not a invisibility cloak; the VPN can see you",
    "Useful on a cafe hallway for a bit. A ‘no logs’ is a claim. A free VPN is often a business of you. Tor is a different, slower, overclaimed cousin.",
    "If I have a VPN I am anonymous and also faster and also the bank loves me. Cloaks are a personality. Also: VPNs are only for criminals.",
    "Use mobile data for a bank. If you must, a reputable VPN plus HTTPS. Forget the cafe network after. Do not confess a crime to a void that is a log.",
    "A school VPN is a workplace of a kind. Their policy, not a cloak. The original anon path agrees about a throwaway that is still you."],
  ["vx-d-https-phish", "Safety extras", "A padlock means the costume is encrypted to someone; it does not mean the someone is the bank",
    "HTTPS on a homograph is a tidy costume. Certificate authorities are a pile of trust, not a angel. The original phish path’s hover still wins.",
    "If it is a padlock it is the bank. Padlocks are a identity. Also: padlocks are fake because I heard a podcast.",
    "Read the domain. Type the address you know. A manager that will not fill is a clue the host is wrong.",
    "A green name in a old screenshot in a textbook is a history. Browsers dropped the green. Read the words."],
  ["vx-d-remote-help", "Safety extras", "A stranger who wants AnyDesk ‘to refund you’ is a remote-access setup, not a ATO",
    "Hang up. Use a number from a statement. Gift cards are not a currency of government. A ‘stay on the line’ is the script. Old people and you both get this script.",
    "If they have my last 4 they are the bank. Also: Microsoft called because my serial is on the screen. Serials are a identity of a sticker.",
    "Hang up, tell a person in the room, call back on a known number. No remote tool for a refund. No gift card.",
    "A yellow bang in Windows is not a DC jack and not a Microsoft employee. The original scam-call path is the parent of this one."],
  ["vx-d-session-cafe", "Safety extras", "A cafe Wi-Fi is a shared hallway; a leftover session on a shared PC is a souvenir for the next stranger",
    "Captive portal, a snooper, a fake SSID. Log out. Forget the network. Do not ‘remember me’ on a library machine. HTTPS helps and is not a personality.",
    "Free Wi-Fi is a human right and therefore safe. The padlock in the cafe logo is a TLS. Also: if I delete history I deleted the session cookie. Cute.",
    "Use mobile data for a bank. If you must, HTTPS and no passwords you care about. Log out. Forget.",
    "A ‘remember me’ on a hostel computer is a gift. Hostels have a next guest."],
  ["vx-d-mdm-school", "Safety extras", "A school MDM is a workplace of a kind; a sideload rebellion can be a ticket and a ransomware foyer",
    "Admin can often see. A third-party app the teacher clicked. Do not put a secret that would wreck you if a deputy read it. A personal account is a different box.",
    "It is my laptop. Mine. The school is a wallpaper. Also: MDM is a spy so jailbreak it as a civic. Two cartoons.",
    "A second email for life. School for school. Assume a backup of the drive exists in a office. Read the policy.",
    "A chat with a crush on the school account is a folklore and a FOI-adjacent mess. Don’t. The original school-account path agrees."],
  ["vx-d-exif-strip", "Privacy extras", "The photo is the picture; the file may be a GPS — strip before you post a house",
    "EXIF, a document’s author field, a meme with a leftover crop of a student ID. A fitness heatmap of a base was a famous own-goal. Do not repeat it with a school.",
    "If I cannot see it, it is not there. Metadata is a myth of nerds. Also: if I cropped on a phone the GPS is gone always.",
    "Strip location on the camera. Check a download. A map of a run is a map of a home if you start at a driveway.",
    "A sports photo of a crowd is a different deal from a close-up of a crying stranger plus a GPS of a house. Choose."],
  ["vx-d-broker-shadow", "Privacy extras", "A broker is a company that sells a shadow of you; a leaked school list is a year of phishing",
    "People-search, an ad graph. Opt-outs are a labour. A unique email for junk. ‘Free’ was the product. A find-classmates tool is a broker costume.",
    "If I did not type it into their box they do not have it. Obviously. Also: kids have no identity to steal. Wait.",
    "Minimise what you give apps. A unique email for junk. Watch the inbox after a school leak. Freeze if a grown-up says freeze.",
    "A TFN and a birthdate is a kit. Do not send a ID photo to a ‘job’. A watermark. A myGov that is a real myGov."],
  ["vx-d-fingerprint-browser", "Privacy extras", "A tracker is a breadcrumb; a fingerprint is a breadcrumb that hates cookie-clearing as a personality",
    "Canvas, a font list, a ‘I cleared cookies so I am new’. Do Not Track was a polite note many ignored. A blocker is a tool. A price that jumps after a search is sometimes a cache and sometimes a discrimination.",
    "If I clear cookies I am a new person, always, forever, to everyone. Also: fingerprints are a myth because I used a private window once.",
    "Browser settings, a tracker list, do not click yes-to-all as a sport. An email pixel: some clients block. A second browser for the logged-in life.",
    "A ‘necessary’ cookie that is an ad graph is a naming fight. The original banner path named the maze. This is the fingerprint cousin."],
  ["vx-d-perm-torch", "Privacy extras", "A torch app that wants contacts is a story; deny location until a map needs it",
    "Camera, location always versus while using. Precise location for a shop game is a map of your house. A second profile for sketchy. Revoke.",
    "If it is in the store it only asks for what it needs. Stores are ethics boards. Also: deny everything and then be surprised the map is a blank.",
    "Install, then permissions. Deny location until a map needs it. Precise off for a torch. A while-using if you can.",
    "A ‘allow all the time’ for a discount card is a leash. Off when the shop is done. The original location-share path agrees about a window."],
  ["vx-d-dox-never", "Privacy extras", "Doxxing is publishing a person as a target; open is not a permission to weaponise",
    "Home, a school, a workplace. Illegal in some frames, always a harm. A class list in a Discord is a dox waiting. Close the Discord. Do not trade dox for dox.",
    "If it is findable it is public and therefore fine to weaponise. Open is permission. Also: if they were mean, a bill is a proportionate civic.",
    "Do not. If you are the target, a trusted adult, platform tools, police if a threat. Save URLs. eSafety sits next door.",
    "A ‘holding accountable’ that is a death threat is not accountability. It is a crime. The original cancel-mob path agrees about a process."],
  ["vx-d-app-privacy-law", "Privacy extras", "A privacy law is a rights costume that sometimes has teeth; APP, a GDPR if the company is in that net",
    "Access, delete, a why-do-you-have-this. A 14-year-old’s account is a parent-and-platform maze. A school Google is a workplace of a kind. Delete requests can be slow.",
    "If it is a website they can keep everything forever. That is the deal of 1998. Also: one email and they vanish from the earth. Two fantasies.",
    "Find the privacy policy. Use a delete request as a civics act. Know it can be slow. Skim who owns your files and how to leave.",
    "A ‘we can change this’ in the terms is a flag. The original terms path agrees. A click is a contract you did not negotiate."],
  ["vx-d-google-yourself", "Privacy extras", "A search of your name is a time machine others have; a unique handle per life is a strategy",
    "A username you reused, a forum at 12, a news of a sports win. Delete, grow. A pile-on for a 13-year-old’s post years later is a civic fight. Both true: the bomb, and the pile-on.",
    "If I delete the app it deletes the copies. The internet is a single computer with an undo. Also: if it is old it does not count. Universities disagree.",
    "Search on a calm day. Untag. A brand-new handle for a serious life. Assume a job will look — because they might.",
    "A ‘funny’ racist joke at 13 is a time bomb. Delete, grow, do not pretend it was a different species. Then a adult who piles on a child as a different civic."],
  ["vx-d-anon-fails", "Privacy extras", "Anonymous is a claim that often fails; a style, a timezone, a slip, a cross-site",
    "A throwaway can still be you. Do not confess a crime to a void that is a log. A xxDarkxx is not a cloak. A VPN is a shift of trust.",
    "A username like xxDarkxx is a cloak of invisibility. IP is a myth. Also: if I need a whistle, a random board is a journalist.",
    "If you need a real whistle, a journalist and a process, not a random board. A school harm: a trusted adult, not a secret finsta that 40 people know.",
    "A disappearing message is a hope, not a guarantee. Someone has an old phone. The original group-chat path agrees."],
  ["vx-d-live-location", "Privacy extras", "A live location is a map of a body; share for a window, then stop",
    "Find My, a story map, a come-find-me that stays on. A ex, a stranger, a burglar who knows you are at a film. Off when the meet is done. A child’s live school-run is a no.",
    "If we are friends we share location always. That is intimacy as a setting. Intimacy without a off-switch is a leash. Also: if it is a map it is not a body.",
    "Share for a window. Stop. A screenshot of a map is a copy. Do not post a child’s live school-run. A night run live-post is a map for someone you did not invite.",
    "A fitness live-post of a 5am loop that starts at a driveway is a heatmap of a home. Heatmaps are a privacy."],
  ["vx-d-school-drive", "Privacy extras", "A school login is work kit, not a diary; admin can often see",
    "A third-party app the teacher clicked. Do not put a secret that would wreck you if a deputy read it. A personal account is a different box. Assume a backup of the drive exists in a office.",
    "It is my Gmail. Mine. The school is a wallpaper. Also: if I delete it they cannot have had a copy. Cute.",
    "A second email for life. School for school. Read if they train AI on your essay — a 2020s clause. Version history is a setting.",
    "A FOI-adjacent mess of a crush chat is a folklore. Don’t. The civics FOI path is a cousin, not a dare."],
  ["vx-d-cookie-maze", "Privacy extras", "A cookie banner is often a dark pattern; reject-all versus a maze of toggles is the lesson",
    "Legitimate interest as a costume. The art hub’s ethics path and this one meet at the button. A maze is not a conversation. A browser that blocks is a tool.",
    "If they asked, it is consent. A maze is a conversation. Also: reject means the site should break, so accept all as a politeness.",
    "Look for reject. If it takes 12 clicks, that is the lesson. A tracker list. Do not click yes-to-all as a sport.",
    "A ‘necessary’ cookie that is an ad graph is a naming fight. Name it. Then a regulator if you are a adult with a spare year."],
  ["vx-d-terms-skim", "Privacy extras", "Terms of service are a contract you did not negotiate; skim who owns your files, where they live, how to leave",
    "A click, a change, an arbitration clause. Nobody reads them — that is the design. A school account’s terms are still a contract of a kind. A game that bans you with no appeal is a company court.",
    "If I did not read it, it does not bind me. Also: I want the app. Both. Also: if it is long it is fair because lawyers wrote it.",
    "Skim for: who owns your files, where they live, how to leave. A we-can-change-this is a flag. Then a export before you rage-quit.",
    "The civics hub’s platform path agrees: a CEO is not a court. Costumes mix. Do not mix them."],
  ["vx-d-lateral-tab", "Info extras", "Lateral reading is a tab to the side, not a deeper hole in the same pretty page",
    "Who is this site? A Wikipedia on the org, a fact-check, a reverse image. Wineburg’s classroom. Staying on the pretty page is how a hoax wants you. A nice .org is not a charity. A .edu can be a student page.",
    "If the About page is long they are legit. About pages never lie. Also: the first result is the truth ranked by God. Page two is for losers.",
    "Open a new tab. Search the claim plus hoax. Then the org plus funding. Then a second outlet. Then still be unsure.",
    "A medical search will scare you (availability). Use a clinic site, then a GP. The original search-literacy path is the question; this is the side tab."],
  ["vx-d-wiki-trail", "Info extras", "Wikipedia is a start, a fight, and a citation trail; the article is not a source for a serious footnote — the footnote is",
    "Talk page, a lock, a citation at the bottom. Vandalism is a cat-and-mouse. Circular wiki-blog-wiki is a snake. A medical page is a worse place to stop than a pop-culture page. Still do not stop.",
    "Anyone can edit so it is useless. Or: it is always right because a crowd. Two cartoons.",
    "Read the talk. Click two citations. If they are circular, you found a snake. Then a second venue.",
    "A politician’s page on election eve is a fight. The fight is data. So is a quiet sourced paragraph."],
  ["vx-d-deepfake-face", "Info extras", "A face can be a puppet now; audio too; doubt spectacular clips",
    "A celebrity scam, a classmate’s face on a joke that is not a joke. Provenance tools are immature. A school deepfake of a teacher is a discipline and a possible law. Not a meme unit.",
    "If it is video it is true. Film cannot lie. 1890s magicians disagree, but anyway. Also: if it is fake it is harmless even as a nude puppet.",
    "Check another source, a live event, a context. Do not share a nude puppet — that is a harm even if fake. Then a eSafety path if it is a person you know.",
    "A old clip with a new caption is a cousin of a deepfake. Lateral-read the host. The original radicalise path likes a 2am notice."],
  ["vx-d-clickbait-gap", "Info extras", "A headline that withholds the noun is a business; your time is the product",
    "Curiosity gap, a slideshow, a you-won’t-believe. The article can be a paragraph. Do not reward the gap with a share of the headline only. Doctors-hate-this is a cousin. The doctor is not in the piece.",
    "If the headline is exciting the article is a public service. Also: if I am busy the headline is enough to share. Sharing is a civic.",
    "Read past the gap. If there is no noun in 10 seconds, back. Do not share the headline only.",
    "A ‘doctors hate this’ and a ‘one weird trick’ are a family. Families have a business model. You are not the patient, you are the inventory."],
  ["vx-d-ad-costume", "Info extras", "A sponsored post is an ad in a costume; a tiny #ad is the civic minimum, not a friendship",
    "Native ads in a news site. eSafety and consumer law neighbourhood. A school project that copies an undisclosed ad is a media-literacy fail. Assume a bag of rice has a price.",
    "If they are an influencer I like, it is a diary, not an ad. Friendship. Also: if they said I bought this myself it cannot be a contract.",
    "Look for the disclosure. Label your sources. A fake organic review is a civic consumer file. The civics advertorial path agrees.",
    "A politician’s sponsored clip wants the same label as a protein powder. Labels are a civic of a feed."],
  ["vx-d-press-release-mouse", "Info extras", "A study in a feed is often a press release of a mouse; n, a species, a preprint, a correlation as a causation",
    "You met this in logic. The feed will still try you. Chocolate-cures week is a journal’s slow news day. Do not replan a life. Open the paper.",
    "If it says study it is settled. Science is a press cycle. Also: if it is in mice it is extra true because labs.",
    "Open the paper, the sample, the in-mice. Then a systematic review if it is a health choice. Then a GP.",
    "A ‘significant improvement in a mouse maze’ is not a ATAR. The logic effect-size path agrees."],
  ["vx-d-bubble-tunnel", "Info extras", "A feed is a you-shaped tunnel; subscribe to a disagreement on purpose",
    "Personalise, a watch-time, a similar. You will think the tunnel is the world. A recommended-for-you medical is a bubble with a body. Leave.",
    "If it is on my feed it is popular therefore true therefore the whole country. Also: if I leave the tunnel I will be radicalised by the other tunnel. Two tunnels, no paper.",
    "Follow one source that annoys you and is still in the evidence game. A newspaper of another city. Then the logic hub. Then a sleep.",
    "A ‘near me’ is a geography. Autocomplete is a crowd plus a company. The original search path named the box; this is the tunnel after the box."],
  ["vx-d-rabbit-hole", "Info extras", "A rabbit hole can be a design; a slight more extreme, a community that love-bombs",
    "You can leave. A joke to a worldview is a known path. This is not a how-to. A just-asking-questions channel that never lands a answer is a hole. Lateral-read the host.",
    "If the algorithm showed it, it is the centre of the culture. I am only watching. Also: noticing a hole is a conspiracy about algorithms, so skip noticing.",
    "Notice a 2am chain. Sleep. A person IRL. A trusted adult if it is a harm group (hate, a self-harm aesthetic). Then a opposite query.",
    "A ‘just asking questions’ that never lands is a hole. The logic unfalsify path likes a what-would-count-as-a-no."],
  ["vx-d-archive-snapshot", "Info extras", "A page can vanish; a archive might not — save a snapshot of a source you rely on",
    "Wayback, a citation, a we-never-said-that. Also: a archive of a harm that should not be copied. Ethics of saving. A politician’s deleted tweet is a civics and a digital path. Wayback has gaps.",
    "If it is deleted it never existed. The record is the now. Also: if it is in Wayback it is the whole truth forever.",
    "Save a snapshot of a source you rely on. Note the date. Do not archive a revenge page as a hobby. Then a citation with a date.",
    "A Christmas-eve dump is a tactic. The calendar is civic. A quiet Tuesday report nobody quoted is too. The civics FOI path agrees."],
  ["vx-d-ai-plausible", "Info extras", "A chatbot is a plausible sentence machine; it can be wrong with a smile and a citation it invents",
    "A homework that is a paste is a integrity file. A private fact you typed is a training-and-logs question. Fluency is not a truth serum. School policy on AI — read it.",
    "If it is fluent it is true. Fluency is a truth serum. 2020s magic. Also: if it listed a source the source exists. Ghosts disagree.",
    "Check a fact. Do not paste a classmate’s medical. Lateral-read a source it named. Then a human. This bench’s own paths were not a chatbot dump — that is a design.",
    "A ‘source’ the chat invented is a ghost. The logic quote-mine path still wants the paragraph, not a ghost."],
  ["vx-d-autocomplete-crowd", "Info extras", "A search is a question with a bias in the box; autocomplete is a crowd plus a company",
    "Keywords, a site:, a date. The first result is an ad sometimes. A medical search will scare you. Use a clinic site, then a GP. A better question beats a longer hole in the same page.",
    "The first result is the truth ranked by God. Page two is for losers. Also: ads are labelled so they cannot be a bias.",
    "Type a better question. Add a year. A -site to drop a junk domain. Then a second search that would hurt your view.",
    "A ‘near me’ is a geography. A ‘for kids’ is a filter that can still be a shop. Filters are a design."],
  ["vx-d-comment-public", "Civility extras", "A comment is a public, not a whisper; the person can screenshot",
    "A pile-on is a group. You will not be as funny as you think at 1am. A real-name test: would you say it at the lockers. If not, delete. A ‘jokes’ under a classmate’s photo is a bullying file.",
    "It is just the internet. Words here do not count. Also: they count when I am the target. Both.",
    "Wait a night. A real name test. If not, delete. Report, collect URLs, a trusted adult if it is a threat. Do not report as a war tactic for a disagreement.",
    "A disappearing message is a hope. Someone has an old phone. The original group-chat path agrees about a leak."],
  ["vx-d-glass-person", "Civility extras", "A person is at the other end of a thin glass; a ratio is still a pile of humans",
    "Tone, a delay, a missing face. Assume a human. Block is a tool; brigade is a mob. A creator is a person with a sleep. A parasocial is a one-way. Do not be a debt collector of their time.",
    "If they have a blue tick they are not a person. If they have 12 followers they are not a person. Convenient. Also: if they post they owe me a reply in 30 seconds. The app said so with a badge.",
    "Read once as if it is a letter to you. Then reply or don’t. A DM to a stranger with a demand is a vibe check you will fail.",
    "A like is a sugar; a body is still a body. The original wellbeing path and the health hub were not a different planet."],
  ["vx-d-crowd-court", "Civility extras", "A crowd can be a court without a process; a pile-on does not have an appeal",
    "A real harm versus a joke from 2012 versus a smear. Process is the civic tech from the civics hub. You can still refuse to join. Do not dox. Do not threaten. A school has a process — use it if it is a school harm.",
    "If the crowd is loud the evidence is in. Volume is a trial. Also: if the crowd is loud it is a witch-hunt always, so skip a real harm. Two cartoons.",
    "Wait. Primary. A consequence that fits. Do not dox. A holding-accountable that is a death threat is a crime. Discern.",
    "A mass-report to silence a journalist is a tactic. A report of a death threat is a duty. The original report-abuse path asked you to discern."],
  ["vx-d-steel-comment", "Civility extras", "A steel-man works in a comment too; quote, then the because; you will not finish the internet",
    "A straw is easier and cheaper. Block after if they are a firehose. You do not owe a debate to a firehose. One point. A source. A stop.",
    "Win the thread. The last word is the truth. Also insult their hair. Also: if you block you lost. Two schoolyards.",
    "One point. A source. A stop. A so-you-are-saying that they are not saying is a straw. Logic hub. Use it.",
    "A ‘ratio’ is still a pile of humans. Winning a pile is not a court. The civics platform path agrees about costumes."],
  ["vx-d-chat-leak", "Civility extras", "A group chat is a room with a leak; assume 30 people and a teacher",
    "A screenshot, a forward, a member you forgot. A safe-space chat that piles on a classmate is not safe. Do not put a photo they did not allow. Leave if it is a pile-on. A admin is a power — use it.",
    "If it is private it cannot be copied. Physics of screenshots. Also: disappearing is a physics. Physics disagrees.",
    "Do not put a photo they did not allow. Leave if it is a pile-on. A disappearing message is a hope. Someone has an old phone.",
    "A class list in a Discord is a dox waiting. Close the Discord. The original dox path is the parent."],
  ["vx-d-meet-mute", "Civility extras", "A video call is a room with a mute button; recording without a tell can be a law",
    "Mute, a background, a raise-hand. A chat side-channel can be a pile-on of a teacher. Don’t. A Zoom-bomb is a trespass with a joke. Passwords on the meeting.",
    "If I can see them I can record. That is a souvenir, not a consent. Also: if it is school it is already recorded so extra recording is a vibe.",
    "Mute when you are a lawnmower. Camera policy is a school’s. Do not deepfake a classmate’s breakout room. Password on the meeting.",
    "A lawnmower is a Australian civic of a mute. So is a cockatoo. Mute is a kindness."],
  ["vx-d-photo-consent", "Civility extras", "A photo of a person is their face as a file; ask; under-18 sexual images are a bright legal line — never",
    "A crowd, a baby, a drunk. Revenge is a crime in a lot of places. A sports photo of a crowd is a different deal from a close-up of a crying stranger. Crop. Do not tag a location that is a home.",
    "If they were in public I can do anything. Public is a licence. Also: if I am in the photo I own everyone’s faces. Two licences that are not law.",
    "Ask. Crop. Delete if they ask — kindness and sometimes law. Never a sexual image of a minor. That is a stop, not a vibe.",
    "A intimate image without consent has a path. Use it. Shame the sharer, not the person in the photo. eSafety sits here."],
  ["vx-d-mod-burnout", "Civility extras", "A moderator is a volunteer court with burnout; appeal without a pile-on of the volunteer",
    "Rules, a mute, a ban. A free-speech that is a slush of slurs is a different product. Build the product you want to sit in. A Discord that is a class is school-adjacent. The teacher’s rules still sit on top. Yes, even at 9pm.",
    "Mods are tyrants. Also: why isn’t anyone moderating. Both, in the same thread. Also: dox the volunteer, they volunteered.",
    "Read the rule. Then a calm appeal. If you hate the court, leave and build. Do not dox the volunteer.",
    "A school Discord at 9pm is still a school-adjacent. Deputies have a FOI-adjacent. The original community-mod path is the parent."],
  ["vx-d-notify-sugar", "Tools extras", "A notification is someone else’s priority in your pocket; a red badge is a product",
    "Batch, a grayscale, a charge-across-the-room. FOMO is a product. Sleep is a health hub; this is the button. A 4-hour quick-look is a failure mode. A I’ll-just-check is the slot-machine handle.",
    "If I do not answer in 30 seconds I am a bad friend. The app said so with a red badge. Also: streaks that make you sick are a loyalty.",
    "Turn off badges. One check after dinner. A real alarm clock. A break that is a walk, not a 40-minute short. Notice the hand on the handle.",
    "A focus mode is a tool. A like is a sugar. The original time path and wellbeing path agree. The health posture path agrees about a walk."],
  ["vx-d-meme-holiday", "Tools extras", "A meme is often someone else’s photo on a holiday; fair dealing in Australia is a narrow door, not a vibe",
    "A school assignment has a citation path. A shop on a tote is a shop. Content ID is a robot lawyer. You will meet it. Cite. Do not sell.",
    "If it is a meme it is public domain. That is the law of funny. Also: if I transformed 10% it is mine. Folk law.",
    "Cite. Do not sell. A remix that is a new sentence is a stronger fair-dealing story — still not a business plan without advice. Music on a YouTube is a meeting with a robot lawyer.",
    "A First Nations design as a meme without protocol is not a texture pack. The art living-cultures path is a stop sign."],
  ["vx-d-cc-badge", "Tools extras", "A Creative Commons is a permission with a condition; BY, NC, SA, ND — read the badge",
    "A found-on-Google-images is not a licence. Wikimedia is a start with a file page. NC means your stall is a no. SA means your remix might have to wear the same badge. That is the deal you clicked.",
    "Google images is a licence. The thumbnail is a contract. Also: if it is on the internet it is CC. Cute.",
    "Filter by licence. Keep the attribution. NC means your stall is a no. The file named LICENCE is the licence, not a screenshot of code.",
    "A share-alike into a closed assignment if the teacher forbade it is a ask-first. The original open-source path agrees about a GPL."],
  ["vx-d-cloud-else", "Tools extras", "A cloud is a computer in someone else’s building; terms, a jurisdiction, a lock-out",
    "School Google is a workplace. A deleted that is in a bin for 30 days. Two-factor on the cloud or the cloud is a single password from a leak. A ransomware of a cloud without a version history is a sad. Versioning is a setting.",
    "If it is in the cloud it is immortal and private. Both. Magic building. Also: if I deleted it, it is gone from every backup. Cute.",
    "Know where the homework lives. A second copy of the thing you cannot lose. Read if they train AI on your essay — a 2020s clause. Version history on.",
    "A 3-2-1 is a civic of files. Three copies, two kinds of media, one offsite. A USB in the same bag as the laptop is not offsite."],
  ["vx-d-321-restore", "Tools extras", "A backup you never restored is a Schrödinger’s backup; test a restore",
    "3-2-1: three copies, two kinds of media, one offsite. A photo library is a life. A phone-only photo life is a one-copy life. A wash is a funeral of a year. A weekly dump. A drive at a grandparent’s.",
    "If it is on the laptop it is fine. Laptops are immortal. Also: cloud is immortal so skip a second copy. Two immortalities that die.",
    "A weekly dump. Cloud plus a drive at a grandparent’s. Test a restore. Then a phone that is not the only copy of a year.",
    "A ransomware of a attached backup is a kidnapping of the backup too. Offsite means not plugged in. The original ransomware path named the unplugged."],
  ["vx-d-vault-master", "Tools extras", "A password manager is a database with a lock you must not lose; a screenshot of a vault is a vault on a camera roll",
    "A master, a backup of the vault. A browser-saved pile is a weaker cousin. A parent’s shared vault is a family policy. A notebook is stealable too. Pick a reputable one.",
    "If the manager has my passwords, they will sell them. Therefore a notebook is safer. (A notebook is stealable too.) Also: one clever password everywhere, plus a birthday.",
    "Pick a reputable one. A master you can remember and nobody else can guess. A paper backup of recovery in a drawer. Do not screenshot the vault.",
    "A sticky note on a webcam is a movie joke and a real audit fail. The original password path is the parent. This is the vault."],
  ["vx-d-backup-codes", "Tools extras", "A lost phone should not be a lost life; print backup codes on a calm Tuesday, not at an airport",
    "A second device, a printed set. A SIM-only recover is a SIM-swap gift. Account recovery questions are a research project for a stranger. A school account with no recovery is a helpdesk ticket with tears.",
    "If I lose the phone I will just guess. Future-me is clever. Also: SMS is enough forever. SIM-swap disagrees.",
    "Print codes. A drawer. A second key. Do this on a calm Tuesday. Then a telco PIN while you are there.",
    "A hardware key is a later flex that is actually good. The original MFA path preferred app over SMS. This is the drawer."],
  ["vx-d-blocker-chisel", "Tools extras", "The same laptop is a workshop and an arcade; choose a mode, not a personality forever",
    "A blocker, a full-screen, a paper draft. Multitask 12 tabs is a skill of the gifted — evidence optional. One tab, a timer, a phone in another room. A break that is a walk, not a 40-minute short.",
    "Multitask 12 tabs is a skill of the gifted. Evidence optional. Also: if I am sad the app will hug me. That is the business model as a friend.",
    "One tab, a timer, a phone in another room. The health posture path agrees. Then a walk. Notice the hand on the I’ll-just-check handle.",
    "A notification is someone else’s priority. This path is the chisel. The notify-sugar path is the sugar. Same pocket."],
  ["vx-d-alt-text", "Tools extras", "Access is a civic of the screen; captions, alt, a contrast, a keyboard",
    "You will be temporarily disabled (a broken arm, a glare). Design as if. The art hub’s colour-blind path agrees. A PDF that is a photo of text is a wall. Real text. A font that is a costume can be a wall.",
    "If I can use it, it is accessible. I am the measure of a man and a website. Also: access is a extra if we have budget leftover.",
    "Turn on a screen reader for 10 minutes on your site. Caption your video. Real text in a PDF. A pattern plus a hue, not hue-only for bad.",
    "A dark installation that is a trip hazard is a lawsuit in the art hub. A uncaptioned video is a wall in this one. Walls are a design."],
  ["vx-d-right-repair", "Tools extras", "A right-to-repair is a civic of stuff; a glued battery is a policy, e-waste is a geography",
    "A part pair, a PDF manual. A school laptop you cannot open is a policy. A planned-obsolete printer is a business and a digital-citizenship of waste. Both hubs. Do not stab a swollen lithium pack — the tech hub’s safety.",
    "If it is old, bin it. New is virtue. The mountain of waste is a cloud, not a place. Also: if I can open it I void a universe, so never open.",
    "A repair cafe, a part, a screwdriver. Then when it is a lithium fire risk — do not stab a pack. Then a manual PDF you actually kept.",
    "A printer that demands a official chip is a business. A mountain in a other country is a geography. The geography waste path agrees if it is in the extra set."],
  ["vx-d-licence-read", "Tools extras", "Open source is a licence and a peek, not automatically safe; a supply-chain npm was a parable",
    "You can read it; you might not. A school project can still use it with a citation. I changed 3 lines is not I own the licence if the licence says share-alike. Visible is not a proof of a absent backdoor.",
    "If I can see the code it cannot have a backdoor. Visible is virtuous and complete. Also: open source is a communism so skip it in a assignment.",
    "Read the licence. Update. Do not paste a GPL into a closed assignment if the teacher forbade it — ask. The file named LICENCE is the licence.",
    "A screenshot of code is not a licence. A ‘I found it on a gist’ is a origin, not a permission. Origins still want a file."],
  ["vx-d-esafety-office", "Safety extras", "eSafety is a real office, not a vibe; a complaint, a removal, not a magic delete of the internet",
    "A school’s eSafety policy. A threat is a police file too. Do not pay a we-will-delete-it random on Instagram. Intimate image without consent has a path. Use it. Shame the sharer, not the person in the photo.",
    "The internet is lawless. Also: my team should be protected by a law. Both, when convenient. Also: reporting is snitching.",
    "Report, collect URLs, a trusted adult. Do not pay a random. A intimate image path — use it. Police if a threat.",
    "A mass-report to silence a journalist is a tactic. A report of a death threat is a duty. Discern. The original report-abuse path is the sibling."],
  ["vx-d-catfish-collage", "Safety extras", "A person can be a collage; a reverse image, a video call, a send-money-for-a-ticket is a industry",
    "Romance is a industry. A classmate secret account can be a cruelty. I’m-on-a-oil-rig is a genre. A genre is a tell. No money. Tell a person.",
    "If they are attractive and love me quickly, that is just Europeans. Or Americans. Or a prince. Also: video is optional because they are shy. Shy is a industry.",
    "Video. A reverse search. No money. Tell a person. If it is a classmate being cruel, a school process.",
    "A ‘I’m on a oil rig’ is a genre. A job that is a mule is a crime. You can be used. If a stranger pays you to move money, stop. The original money-online path named the mule."],
  ["vx-d-gift-card-ato", "Safety extras", "A gift card is not a currency of government; a urgency plus a card is a script",
    "ATO, Microsoft, a grandson in jail. Hang up. Use a number from a statement. A refund that needs a remote tool is a setup. Old people and you both get this script.",
    "If they have my last 4 digits they are the bank. Those are on a lot of letters. Also: gift cards are a modern tax because they said so.",
    "Hang up, tell a person in the room, call back on a known number. No cards. No remote. No stay-on-the-line.",
    "A yellow bang is not a employee. A serial on a sticker is not a identity of a Microsoft. The original scam-call path is the parent."],
  ["vx-d-mule-job", "Safety extras", "A job that is a move-this-money is a crime with your name on the transfer; you can be used",
    "A too-good rate, a Discord investment, a refund scam. A parent’s card is a crime if you were not allowed. A game skin can still be a real dollar. A family rule. A spend cap.",
    "If it is a number on a screen it is not real money. Therefore a 12-year-old’s $400 is a lesson, not a theft. Also: if a stranger trusts me I am a professional.",
    "A family rule. A spend cap. A too-good rate is a smell. If a stranger pays you to move money, stop. Tell a grown-up.",
    "A homework on how blockchain works is not a homework on put the rent in a token. Split the files. The original crypto-scam path agrees about a seed phrase someone asks for."],
  ["vx-d-seed-phrase", "Safety extras", "A seed phrase someone asks for is a theft; a send-to-this-wallet-to-double is a theft",
    "A guaranteed, a celebrity, a coin with a story. This is not investment advice — it is a trap map. The business hub’s if-you-do-not-understand agrees. Maths cannot lie about a rug — the rug is a social.",
    "If it is on a chain it is maths therefore safe. Maths cannot lie about a rug. Also: if a celebrity is in the thumbnail the maths is extra.",
    "If a stranger needs your seed, it is a theft. A send-to-double is a theft. Walk. Split a how-it-works homework from a rent token.",
    "A screenshot of a seed is a seed on a camera roll. Camera rolls leak. The vault path agrees about a screenshot."],
  ["vx-d-tfn-kit", "Safety extras", "A TFN and a birthdate is a kit; a school form and a leaked list are a year of phishing",
    "A phishing we-need-to-confirm. A tax file is not a meme. Credit in your name is a future. I’m a kid so I have no identity to steal — wait. A myGov that is a real myGov.",
    "I’m a kid so I have no identity to steal. Cute. Wait. Also: if they have my name they are the ATO. Names are on a lot of sports lists.",
    "Do not send a ID photo to a job. A watermark. A parent. A myGov that is a real myGov. Watch the inbox after a leak. Freeze if a grown-up says freeze.",
    "A leaked school database is a year of phishing. Watch the inbox. The broker path is a cousin of the same kit."],
  ["vx-d-wellbeing-cap", "Safety extras", "A like is a sugar; a body is still a body; a time cap is a tool, a GP if the dark is sticky",
    "Sleep, a comparison, a posture. Mute words. A sport IRL. 000 / Kids Helpline if you are unsafe. You already saw this in health — it still applies on a phone. A streak that makes you sick is a product win and a you loss. Break the streak.",
    "If I am sad the app will hug me. That is the business model as a friend. Cute. Also: if I am sad I should stay in the app to process. Process is a watch-time.",
    "Time cap. A friend in a park. A GP if the dark is sticky. 000 / Kids Helpline if you are unsafe. Break the streak.",
    "A focus mode is a tool. A 4-hour quick-look is a failure mode. The notify path is the button. This is the body."],
  ["vx-d-update-door", "Safety extras", "A patch is a door someone already used; delay is a window; never-update is a museum strategy",
    "Restart is part of the patch. A managed school laptop is not your laboratory. A zero-day is a race. You will not win it by reading a forum. Patch. A glued battery is a different civic (repair) — do not mash a update skip into a repair ethic.",
    "Updates are only toolbars and slowdowns. Skip. Also: if it is old, bin it, new is virtue. Two wastes.",
    "On for OS and a browser. Night restart. Then a firmware of a router on a calm Tuesday. Then still a backup because patches can still go wrong.",
    "A ‘I’ll update after the assignment’ that becomes a year is a window. Windows get used. The original update path is the parent."],
  ["vx-d-found-stick", "Safety extras", "A found stick is a plot device in real life; do not plug it into a machine you like",
    "A rubber duck types faster than you. School: give it to IT, not to curiosity. A USB drop is a known test. You can fail it in a car park. A photos-from-camp on a desk is a vector.",
    "Free USB. Lucky. Plug in to see the holiday photos. Then run the file called definitely_not_a_virus. Also: if it has a cute sticker it is a student’s, kind to return via a port.",
    "Leave it. Or a dedicated sacrificial machine if you are a professional. You are probably not. Give it to IT.",
    "A charging cable that is a extra computer is a cousin of a stick. The juice-jack path is the port cousin."],
  ["vx-d-router-theatre", "Safety extras", "Hiding an SSID and a MAC filter are a theatre; a guest network and a changed default are a castle gate",
    "WPS buttons are a foyer. Firmware is a door someone already used. A printer on the same LAN as a tax file is a hallway. Separate the junk IoT.",
    "If the name is hidden it cannot be found. Hide is a cloak. Also: MAC filters are a military. Stickers on a printer say otherwise.",
    "Change the default. Guest network for bulbs and toasters. Update the gateway. A camera that is not a toilet. A key for a smart lock’s dead battery.",
    "A ‘smart’ fridge with a default admin is a botnet foyer. The original IoT path named the crumb tray. This is the gate."],
  ["vx-d-bluetooth-pair", "Safety extras", "A Bluetooth pair is a door with a PIN you should actually look at; a speaker in a cafe can be a stranger’s mic",
    "Unexpected pair requests, a headset that is not yours, a car that keeps a phonebook. Forget the cafe speaker after. A AirDrop from a stranger is a hallway.",
    "If it is radio it is short so it is safe. Short is a ethics. Also: pair all the pop-ups, they are the OS being helpful.",
    "Check the PIN on both screens. Forget public speakers. Turn off the discoverable when you are done. Do not AirDrop a photo to everyone in a train.",
    "A stolen session in a borrowed car is a phonebook souvenir. Delete the phone from the car when you sell the car — and when you leave a hire."],
  ["vx-d-find-my", "Safety extras", "A find-my is a map of a body you own; a stolen phone with find-my off is a brick with a photo life",
    "Mark as lost, a remote wipe, a lock. A school policy may already own the wipe. Encryption still matters if they unscrew the disk. A live share is a different, leakier map.",
    "If I can see it on a map I should confront the thief. Maps are a bravery. Also: find-my is a spy so skip it and also want the phone back.",
    "Turn it on before the bag is gone. Do not play hero in a car park. Remote wipe if the policy says. Then the backup you tested.",
    "A photo library that only lived on the phone is a funeral of a year after a wipe. The 3-2-1 path wanted a second copy first."],
  ["vx-d-bio-legal", "Safety extras", "A biometric is convenience with a legal footnote; a PIN is a secret you can refuse, a face is a face you carry",
    "Compulsion varies by jurisdiction. A friend-borrowing rule still exists. A lock timeout is the first bouncer. Do not use a face to unlock a phone you are handing to a officer without knowing the local file — this is not legal advice, it is a pause.",
    "If I am holding it, it does not need a lock. My hands are authentication. Also: biometrics are unforgeable so skip a PIN.",
    "Timeout 1–2 minutes. A PIN as a backup. A friend-borrowing rule. Pause on a compulsion question and ask a adult with a lawyer if the file is nuclear.",
    "A photo of a face-down phone in a change room is a story. Lock it. The original lock-device path is the parent."],
  ["vx-d-calendar-invite", "Safety extras", "A calendar invite can be a foyer; a unexpected .ics from a stranger is a link with a costume",
    "A Teams impersonation, a font download, a codec you must install to see the video of the meeting. The invoice.odt.exe family. Do not enable macros. Do not install a codec from a pop-up.",
    "If it is in the calendar it is a meeting. Calendars are a identity. Also: if the logo is crisp it is the deputy.",
    "Decline, another channel, type the address you know. No codec. No macro. No extra font pack from a stranger.",
    "A ‘your mailbox is full’ cousin with a calendar attachment is still a play about urgency. Pause."],
  ["vx-d-typosquat", "Safety extras", "A extra letter in a domain is a shop of a harvest; paypals.com is a costume, not a vibe of a typo you made",
    "Homograph’s cousin. Mail merge is a tool. A password manager that will not fill is a seatbelt. Type the address you know. QR stickers age.",
    "If they know my name it is real. Mail merge is magic. Also: HTTPS on a typo is still the bank because padlock.",
    "Hover. Read aloud. Manager fill as a test of the host. Another channel for a bank detail change.",
    "A school canteen supplier with a extra letter is a BEC with a sausage. The bec-invoice path is the sibling."],
  ["vx-d-captive-portal", "Safety extras", "A cafe portal is a hallway ticket; the padlock in the cafe logo is not a TLS to your bank",
    "A fake SSID that looks like the cafe. HTTPS after the portal for anything you care about — or mobile data for a bank. Forget the network after. A leftover remember-me on a shared PC is a souvenir.",
    "Free Wi-Fi is a human right and therefore safe. Also: if I bought a muffin the AP is a ethics board.",
    "Portal, then HTTPS. Mobile data for a bank. Log out. Forget. Do not continue through a cert warning on a bank.",
    "A ‘Free Airport WiFi’ with extra spaces is a classic. Ask the board. The original public-wifi path is the parent."],
  ["vx-d-audience-graph", "Privacy extras", "The default is often share with the graph; friends-of-friends is a city",
    "A past post that was funny at 14, a tagged photo. Review. Settings move. A close-friends list. Assume a screenshot exists. A parent tagged you in a bath photo from 2006. That is a conversation and a privacy event.",
    "If I set it once in 2019 it is still true. Settings never move. Also: if it is friends it is not a city.",
    "Audit yearly. Untag. A close-friends list. Assume a screenshot. Talk to a parent about a old tag.",
    "A university search of your name is a time machine. The google-yourself path is the machine. This is the graph setting."],
  ["vx-d-email-pixel", "Privacy extras", "A pixel in an email is a breadcrumb that reports a open; some clients block, a tracker list helps",
    "Do Not Track was a polite note. A price that jumps after you searched is sometimes a cache and sometimes a discrimination. Watch. A second browser for the logged-in life.",
    "If I clear cookies I am a new person to the pixel too. Always. Also: if I do not click, they cannot know I opened. Pixels disagree.",
    "Block remote images when you can. A tracker list. Do not click yes-to-all as a sport. Then still a screenshot of a map as a copy.",
    "A newsletter that is a shop with a pixel is a shop. Shops are allowed. The breadcrumb is the lesson, not a ban on shops."],
  ["vx-d-export-leave", "Privacy extras", "How to leave is a civic of a cloud; export before you rage-quit, a bin can be 30 days",
    "Who owns your files, where they live, a jurisdiction. A we-can-change-this is a flag. Two-factor on the cloud. A school drive is a workplace copy.",
    "If I delete the app it deletes the copies. Undo is a physics of a company. Also: if I never export I am free.",
    "Skim how to leave. Export. Then a second copy of the thing you cannot lose. Then a delete request as a civics act that can be slow.",
    "A game that bans you with no appeal is a company court. Export was the bag you packed. The civics platform path agrees about a CEO."],
  ["vx-d-reverse-image", "Info extras", "A reverse image is a tab to the side of a pretty photo; a old clip with a new caption is a cousin of a puppet",
    "Lateral reading’s picture tool. A celebrity scam, a protest photo from another year. Wayback as a sibling. Ethics of saving a harm you should not copy.",
    "If it is a photo it is now. Cameras are a clock. Also: if it is blurry it is secret and therefore true.",
    "Reverse the image. Check a date. A second outlet. Then still be unsure. Do not share a nude puppet.",
    "A war’s first casualty is still a feed with a watermark you skipped. The civics global-media path agrees about a delay."],
  ["vx-d-talk-page", "Info extras", "A Wikipedia talk page is a fight you can read; a lock is a weather, not a halo",
    "The citation at the bottom is the serious footnote. Circular wiki-blog-wiki is a snake. A medical page is a worse place to stop. A politician on election eve is a fight. The fight is data.",
    "If it is locked it is true. Locks are oracles. Also: if anyone can edit it is useless so skip the footnotes too.",
    "Read the talk. Click two citations. If they are circular, snake. Then a second venue. Then a date.",
    "A pop-culture page can be a fine start. A medical page is a start that must not be a stop. GP after."],
  ["vx-d-preprint-halo", "Info extras", "A preprint is a conversation, not a halo; a retraction is a system working, late",
    "Peer review is a filter, not a sacrament. A mega-journal with a fee is a new ecology. A ‘studies show’ without a study is a costume. Open the paper, the n, the mice.",
    "If it is published it is true forever. If it is a preprint it is fake. Two oracles. Also: if they rejected my paper I am a martyr.",
    "Look at venue, a replication, a conflict. Then the in-mice. Then a systematic if it is a body choice.",
    "A chocolate-cures week is a slow news day. Do not replan a life. The logic file-drawer path is a sibling."],
  ["vx-d-site-search", "Info extras", "A site: operator is a fence around a domain; a first result that is an ad is a shop in a costume",
    "Keywords, a date, a -site to drop junk. Autocomplete is a crowd plus a company. A better question beats a longer hole. Page two is not a moral fail.",
    "The first result is the truth ranked by God. Ads are labelled so they cannot be a bias. Also: operators are for nerds, vibes are for citizens.",
    "Type a better question. Add a year. A site: for a clinic. A -site for a junk domain. Then a search that would hurt your view.",
    "A medical scare is availability. Clinic site, then a GP. The original search-literacy path is the parent. This is the fence."],
  ["vx-d-screenshot-court", "Civility extras", "A screenshot is a publication with a crop; a pile-on of a cropped joke from 2012 is a court without a rest of the thread",
    "Process is the civic tech. Wait. Primary. A consequence that fits. You can refuse to join. A disappearing message is a hope. Someone has an old phone.",
    "If I cropped it the rest did not exist. Crops are a truth. Also: if it is old it cannot harm. Universities and a target disagree sometimes — both can be true as a bomb and as a pile-on.",
    "Wait. Open a primary. Ask whether the crop dropped a joke’s target or a context. Then a school process if it is a school harm. Do not dox.",
    "A quote-mine is the logic cousin. Open the paragraph. The original quote-context path wants before and after."],
  ["vx-d-parasocial-debt", "Civility extras", "A parasocial is a one-way; do not be a debt collector of a creator’s sleep",
    "A DM to a stranger with a demand is a vibe check you will fail. A blue tick is still a person. A 12-follower account is still a person. Block is a tool; brigade is a mob.",
    "If they post they owe me a reply in 30 seconds. The app said so with a badge. Also: if they have a brand they are not a person. Convenient.",
    "Read once as a letter. Reply or don’t. A time cap. A friend in a park. Do not brigade a person who did not reply to a demand.",
    "A like is a sugar. A body is still a body. The wellbeing path wants a GP if the dark is sticky, not a extra hour of a demand."],
  ["vx-d-raise-hand", "Civility extras", "A raise-hand is a queue; a side-chat pile-on of a teacher is still a pile-on in a classroom costume",
    "Mute when you are a lawnmower. Camera policy is a school’s. Recording without a tell can be a law. Passwords on the meeting. A Zoom-bomb is a trespass with a joke.",
    "If I can see them I can record. Souvenir, not a consent. Also: the side chat is private because it is small. Screenshots disagree.",
    "Mute. Raise a hand. Do not deepfake a breakout room. Password on the meeting. Do not pile-on in the chat.",
    "A cockatoo is a Australian mute. So is a mower. Mute is a kindness. The original meet path is the parent."],
  ["vx-d-admin-power", "Civility extras", "A group-chat admin is a power; use it to stop a pile-on, not to pin a humiliation",
    "Leave if it is a pile-on. Do not put a photo they did not allow. A class list in a Discord is a dox waiting. Close the Discord. A school Discord at 9pm is still school-adjacent.",
    "If I am admin I am a tyrant if I mute, and a coward if I do not. Both, in the same thread. Also: pinning a photo is a joke, jokes cannot be a harm.",
    "Mute the pile-on. Remove the photo they did not allow. Leave if you cannot. Tell a trusted adult if it is a threat. Do not dox.",
    "A volunteer mod burnout is the public cousin. Appeal without a pile-on of the volunteer. The original community-mod path agrees."],
  ["vx-d-grayscale", "Tools extras", "A grayscale and a charger across the room are a design of a pocket; FOMO is a product",
    "Batch notifications. A real alarm clock. A 4-hour quick-look is a failure mode. I’ll-just-check is the slot-machine handle. Notice the hand. A walk, not a 40-minute short.",
    "If I do not answer in 30 seconds I am a bad friend. Streaks are a loyalty. Also: grayscale is a aesthetic, not a tool, so skip it.",
    "Badges off. One check after dinner. Phone in another room for a hour. A walk. Break a streak that makes you sick.",
    "A focus mode is a tool. A like is a sugar. Same pocket as the chisel path. Modes, not a personality forever."],
  ["vx-d-fair-dealing", "Tools extras", "Fair dealing is a narrow Australian door, not a 10% folk law; a tote shop is a shop",
    "A school assignment has a citation path. A remix that is a new sentence is a stronger story — still not a business plan without advice. Content ID is a robot lawyer. Music on a YouTube is a meeting.",
    "If it is a meme it is public domain. Transform 10% and it is mine. Also: if I changed the hue it is a new work in every country. Folk law.",
    "Cite. Do not sell. Filter by a CC badge if you need a permission with a condition. Keep the attribution. NC means your stall is a no.",
    "A First Nations design as a texture pack is a stop sign. The art path and this one agree. Protocol is not a vibe of inspiration."],
  ["vx-d-version-history", "Tools extras", "Version history is a setting; a cloud without it is a ransomware of a one-copy life",
    "A deleted that is in a bin for 30 days. Know where the homework lives. A second copy of the thing you cannot lose. School Google is a workplace. A 2020s clause about training AI on your essay — read it.",
    "If it is in the cloud it is immortal and private. Both. Also: if I hit save I have a history. Saves are not a version by themselves on every tool.",
    "Turn versioning on. A weekly dump offsite. Test a restore. Then a export before a rage-quit.",
    "A USB in the same bag as the laptop is not offsite. 3-2-1 is a civic of files. The 321-restore path is the drill."],
  ["vx-d-paper-recovery", "Tools extras", "A paper backup of recovery in a drawer is a civic of a Tuesday; a airport is a bad Tuesday",
    "Backup codes, a second key, a master you can remember and nobody else can guess. A screenshot of a vault is a vault on a camera roll. A SIM-only recover is a SIM-swap gift. Recovery questions are a research project for a stranger.",
    "If I lose the phone I will just guess. Future-me is clever. Also: I will print it at the airport because that is when I feel the risk. Airports have copiers with a memory.",
    "Print codes. A drawer. A second device. A telco PIN. Do this on a calm Tuesday. Then a hardware key if you want a flex that is actually good.",
    "A school account with no recovery and a lost phone is a helpdesk ticket with tears. Set it up. The original 2fa-backup path is the parent."],
  ["vx-d-pdf-wall", "Tools extras", "A PDF that is a photo of text is a wall for a lot of people; real text is a civic of a file",
    "Captions, alt, a contrast, a keyboard. You will be temporarily disabled (a broken arm, a glare). Design as if. A costume font can be a wall. A screen reader for 10 minutes is a test, not a vibe.",
    "If I can use it, it is accessible. I am the measure. Also: a photo PDF is a security because they cannot copy. Walls are not a security of a public flyer.",
    "Real text. Caption your video. Alt on a image that is not decoration. Pattern plus hue. Turn on a reader for 10 minutes on your site.",
    "A uncaptioned assembly video is a wall. A trip-hazard installation is a lawsuit in art. Walls are a design in both hubs."],
  ["vx-d-repair-cafe", "Tools extras", "A repair cafe is a civic of a screwdriver; a glued battery is a policy, a swollen pack is a fire file",
    "E-waste is a geography. A school laptop you cannot open is a policy. A planned-obsolete printer is a business. Do not stab a lithium pack. A PDF manual you actually kept is a kindness to future-you.",
    "If it is old, bin it. New is virtue. The mountain of waste is a cloud, not a place. Also: opening it voids a universe, so never, even a screw that is a CRU.",
    "A repair cafe, a part, a screwdriver. Then a fire-risk stop. Then a manual. Then a right-to-repair as a civic, not a dare on a glued pack.",
    "A Cybenetics PSU and a 80 Plus sticker were a tech shop path. This is the waste-and-screwdriver civic of the same object’s later life."],
  ["vx-d-supply-chain", "Tools extras", "A dependency you did not write is still in your homework; a supply-chain parable is why you update and you cite",
    "Open source is a licence and a peek, not automatically safe. I changed 3 lines is not I own the licence. Visible is not a absent backdoor. A gist is a origin, not a permission.",
    "If I can see the code it cannot have a backdoor. Also: if it is a famous package it is a ethics board. Famous is a target too.",
    "Read the licence. Update. Cite. Ask a teacher before a GPL in a closed assignment. The file named LICENCE is the licence, not a screenshot.",
    "A ‘I found it on a gist’ is a origin. Origins still want a file. The original open-source path is the parent. This is the chain."],
  ["vx-d-intimate-path", "Safety extras", "An intimate image without consent has a path; use it; shame the sharer, not the person in the photo",
    "eSafety, a school, a police file if a threat. Under-18 sexual images are a bright legal line — never. A nude puppet is a harm even if fake. Do not pay a we-will-delete-it random.",
    "If it is a meme it is a joke. Jokes cannot be a crime. Also: if they sent it they asked for a share. Consent is not a forever licence.",
    "Save URLs. Report. Trusted adult. eSafety path. Police if a threat. Do not pile-on the person in the photo. Do not trade dox.",
    "A bright legal line is a stop, not a vibe. The original share-photo and esafety paths are the parents. This is the path you actually use."],
  ["vx-d-streak-break", "Tools extras", "A streak that makes you sick is a product win and a you loss; break the streak",
    "FOMO is a product. A red badge is a product. Sleep is a health hub. 000 / Kids Helpline if you are unsafe. A friend in a park. A GP if the dark is sticky. You already saw this in health — it still applies on a phone.",
    "If I am sad the app will hug me. Streaks are a loyalty of a friend. Also: breaking a streak is a betrayal of a past-me who was a better person. Past-me was a product.",
    "Break the streak. Time cap. Badges off. A walk. A person IRL. Helplines if you are unsafe. A GP if the dark is sticky.",
    "A I’ll-just-check is the handle. Notice the hand. Modes, not a personality forever. The chisel path and this one share a pocket."],
  ["vx-d-kids-helpline", "Safety extras", "If you are unsafe, 000 and Kids Helpline still exist on a phone; a feed is not a clinic",
    "A sticky dark, a threat, a image you did not want. eSafety is a office. A GP if the dark is sticky. A trusted adult. This hub will not give a method. It will name a door.",
    "If I am sad the app will hug me. The business model is a friend. Also: asking for help is a snitch. Two lies.",
    "Time cap. A person IRL. A GP. 000 / Kids Helpline if you are unsafe. Report a threat. Shame a sharer, not a person in a photo.",
    "A streak that makes you sick is a product win. Break it. The health hub was not a different planet. Neither is a phone at 2am."],
  ["vx-d-export-then-delete", "Privacy extras", "A delete request is a civics act that can be slow; export first, then the bin of 30 days",
    "APP teeth, a GDPR if the company is in that net. A 14-year-old’s maze. A school Google is a workplace copy. A we-can-change-this is a flag. How to leave is a skim, not a vibe of a uninstall.",
    "If I delete the app it deletes the copies. One email and they vanish from the earth. Two fantasies. Also: if it is slow they have refused, so pile-on a intern.",
    "Export. Then a delete request. Know it can be slow. A second copy of the thing you cannot lose. Then a unique email for junk going forward.",
    "A broker shadow can still have a leftover. Opt-outs are a labour. The original broker path named the labour. This is the leave."],
]);
