import { pack } from "../pack.mjs";

export const ENGLISH_VOLUME = pack("english", [
  ["vx-e-subject-verb-distance", "Sentences", "Agreement can hide behind a pile of extra nouns",
    "The box of biscuits is… not are. The head of the noun phrase owns the verb. Of-phrases are decoration that lie.",
    "Agree with the nearest noun. Biscuits are plural so the verb is.",
    "Find the head, ignore the prepositional pile, then conjugate. Read it aloud without the extras.",
    "A pack of wolves is hunting — pack is the head. Unless you mean the wolves as the topic and rewrite."],
  ["vx-e-which-that", "Sentences", "That defines; which often adds (in the fussy school rule)",
    "The book that won is a restriction. The book, which won, is an extra after a comma. American/Australian house styles differ; pick one and stay.",
    "Which and that are twins. Commas are optional jewellery.",
    "If dropping the clause changes which thing you mean, you needed the restrictive one. Then punctuate.",
    "A style guide is a contract. Markers who were trained on that/which will mark the contract, not the universe."],
  ["vx-e-who-whom", "Sentences", "Whom is the object form; who is the subject — when you are in that register",
    "Whom did you ask? You asked them. Who asked you? They asked. Informal speech mostly uses who. Formal writing still tests whom after a preposition.",
    "Whom is just who with a cape. Use it everywhere to sound clever.",
    "Substitute he/him. If him fits, whom. Then decide if the piece actually wants that formality.",
    "To whom it may concern is a fossil that still works. Who it may concern to will get a red pen."],
  ["vx-e-its-its", "Sentences", "It’s is it is; its is possession without an apostrophe",
    "The dog lost its bone. It’s raining. Possessive pronouns (his, hers, its, ours) do not take apostrophes. Nouns do (the dog’s).",
    "Add apostrophes to its until it looks owned. More punctuation is more grammar.",
    "Expand it’s. If you cannot say it is or it has, you wanted its.",
    "Who’s vs whose is the same family. Who’s = who is. Whose bone?"],
  ["vx-e-fewer-less", "Sentences", "Fewer is count; less is mass — in the school rule",
    "Fewer biscuits, less milk. Checkout signs that say ‘10 items or less’ are a dialect, not a moral collapse.",
    "Less is always wrong with numbers. Grammar police first, meaning second.",
    "Ask if you would count it in ones. Then pick. In casual speech, less is spreading. Know your marker.",
    "Less than 10 km is measurement as mass. Fewer than 10 cars is count. Distance is not a car."],
  ["vx-e-parallel-correl", "Sentences", "Either/or and not only/but also want matching clothes",
    "Not only the plot but also the pacing… both nouns, or both clauses. Mixing a noun and a whole clause is a limp.",
    "If the sentence is long it is parallel. Length is symmetry.",
    "Line up the two halves. Same grammatical job after each signpost.",
    "Either you revise or failing is not parallel. Either you revise or you fail."],
  ["vx-e-dash-vs-hyphen", "Sentences", "A hyphen glues words; a dash breaks a thought",
    "Well-known (hyphen in a compound before a noun). A dash — like this — is a louder comma/parenthesis. Minus signs are not dashes in prose.",
    "Any short horizontal line is a hyphen. Typography is optional.",
    "Hyphen in compounds that would misread (small-business owner vs small business-owner). Dash for an interrupt.",
    "Em and en dashes are a house-style rabbit hole. Consistency beats a manifesto in a Year 10 essay."],
  ["vx-e-fragment-fix", "Sentences", "A fragment often still has a capital and a full stop",
    "‘Which is why we left.’ has a verb shape and is still dependent. Attach it or make a main clause.",
    "If it feels like a punchy advert it is a sentence. Ads set the rules.",
    "Find a finite verb and a subject that is not trapped in a subordinate. Then punctuate as one job or two.",
    "Stylistic fragments can work in narrative. Academic paragraphs still owe a complete job most of the time."],
  ["vx-e-tense-sequence", "Sentences", "Reported speech often steps the tense back",
    "She said she was tired (she said, ‘I am tired’). Historical present is a choice, not a leak. Do not wander from past to present without a reason.",
    "If it is exciting, use present, even in the middle of a past paragraph. Excitement is a tense.",
    "Pick a base tense. When you quote, decide direct vs indirect and keep faith.",
    "A novel can shift for a memory. Flag it. A history essay usually should not time-travel for flavour."],
  ["vx-e-voice-agency", "Sentences", "Passive is a tool for hiding or for focusing the done-to",
    "The window was broken. By whom? Lab reports like passive for method. Politics likes it for blame dodge.",
    "Passive is always weasel. Active is always honest.",
    "Ask who did it and whether that actor belongs in the subject slot. Then choose.",
    "Mistakes were made is a famous dodge. The reagent was added is a method."],
  ["vx-e-modifier-place", "Sentences", "Put the modifier next to the thing it limits",
    "I almost ate all the biscuits vs I ate almost all. Only is a famous wanderer. ‘Only I said’ vs ‘I only said’ vs ‘I said only’.",
    "Adverbs can live anywhere. English is free jazz.",
    "Park only/almost/even next to the word they bite. Read both versions aloud.",
    "A dangling ‘walking to school, the rain started’ attaches rain to walking. Rewrite the subject."],
  ["vx-e-comma-intro", "Sentences", "A long introductory clause often wants a comma",
    "After the bell rang, we ran. Short ones can skip it. A missing comma can fuse the intro into the subject (After the student left the teacher sighed — who left?).",
    "Never comma after an opener. Openers are fused on purpose.",
    "If you pause and the subject has not started, consider the comma. Then check you did not splice two sentences.",
    "Because we were late we ran can be readable. Because we were late, the bus — wait, finish the job."],
  ["vx-e-quote-punct-au", "Sentences", "Australian school quoting often puts commas and full stops outside if they are yours",
    "Styles fight (US vs UK/AU). The honest move is: the punctuation belongs to whoever’s sentence it is. A question mark can belong to the quote.",
    "Always put the full stop inside the quote because America is on television.",
    "Ask: is this mark part of what they said? Then place it. Stay consistent in the piece.",
    "He asked, ‘Are we late?’ The question is theirs. He said we were ‘late’."],
  ["vx-e-runon-fix-ways", "Sentences", "A run-on has three legal exits: stop, join, or subordinate",
    "Full stop. Semicolon if cousins. Comma plus and/but/so. Or make one clause dependent. Comma alone is the illegal fourth.",
    "A longer breath means a comma. Lungs are grammar.",
    "Spot two main clauses. Pick an exit. Do not sprinkle and until it is a sausage.",
    "We arrived we sat is a run-on. We arrived, we sat is a splice. We arrived and sat can be one clause with two verbs."],
  ["vx-e-noun-phrase-head", "Sentences", "The head of a noun phrase is the noun the rest hangs on",
    "A slightly dented red bike from the shed — bike is the head. Adjectives and prepositional leftovers are modifiers.",
    "The last word is always the head. From is a noun.",
    "Cross out extras until the sentence still names the thing. That leftover noun is the head.",
    "Subject–verb agreement keys off the head. This is why of-biscuits lies."],
  ["vx-e-clause-types", "Sentences", "Noun, adjective, and adverb clauses do different jobs",
    "What she said (noun) annoyed him. The book that won (adjective) is here. When the rain started (adverb) we left. Same ‘that/when’ can be different jobs.",
    "If it has a conjunction it is an adverb. Labels are stickers from Year 5.",
    "Ask the clause’s job: a thing, a describer, or a when/why/if. Then name it.",
    "A relative clause is an adjective clause with a relative pronoun. The family is the job, not the first word."],
  ["vx-e-imply-infer", "Reading", "Writers imply; readers infer",
    "The text leaves a trail; you draw a because. Infer is not ‘guess from your weekend’. The evidence has to be in the piece (plus ordinary world knowledge).",
    "Imply and infer are twins. Teachers are fussy for no reason.",
    "Quote the trail, then write the because. If you cannot point, you invented.",
    "A character slams a door. You may infer anger if the rest of the scene supports it, not if you were angry on the bus."],
  ["vx-e-theme-vs-topic", "Reading", "A topic is a noun; a theme is a contestable claim about it",
    "Topic: power. Theme: power without witness turns bureaucratic. If your ‘theme’ could fit any book, it is a poster.",
    "The theme is the plot. What happened is the meaning.",
    "Write theme as a sentence that could be disagreed with. Then show two places it is earned.",
    "Love is not a theme; it is a bucket. ‘Love is shown as a transaction in this text’ can be a theme."],
  ["vx-e-unreliable-signs", "Reading", "Unreliable narration is a designed leak, with tells",
    "Contradiction, special pleading, a gap other characters fill. Not ‘I dislike them so they lie’.",
    "First person is always a lie. Third person is always a court transcript.",
    "List the mismatches. Then ask what the author gets by making you work.",
    "A child narrator can be unreliable about adult plots and still true about fear. Reliability is about what, not a character score."],
  ["vx-e-structure-shift", "Reading", "A structural shift is a door: time, voice, place, or knowledge",
    "A new chapter in a new city is not automatically deep. Ask what the reader now knows that they did not. Volta in a sonnet is a famous cousin.",
    "If the font changes, the meaning changed. Design is destiny.",
    "Mark where the ground moves. Name the old contract and the new.",
    "A flashback that explains a scar is a knowledge door. A random new cafe might just be scenery."],
  ["vx-e-connotation-pair", "Reading", "Slim vs skinny vs slender is a political weather on the same body",
    "Denotation overlaps; connotation does not. A news writer choosing ‘riot’ vs ‘protest’ is a frame, not a synonym hunt.",
    "Synonyms are identical. The thesaurus is a truth serum.",
    "Swap the word, keep the referent, name what attitude arrived. Then ask whose interest that attitude serves.",
    "‘Youths’ in a headline is often a scare costume. ‘Students’ is another. Count which paper uses which."],
  ["vx-e-irony-kinds", "Reading", "Verbal irony says the opposite; dramatic irony lets the audience know more",
    "Situational irony is a mismatch of purpose and result (a fire station burns). Coincidence is not automatically irony. Rain on a wedding is weather.",
    "Irony means sarcastic, always. If it is dry it is irony.",
    "Name the type. Then the extra knowledge or the reversed outcome. Do not tattoo ‘irony’ on coincidence.",
    "Alanis’s song is a useful argument about the word, not a sacred text. Teachers still mark the distinction."],
  ["vx-e-motif-repeat", "Reading", "A motif is a repeating detail that accrues; a symbol can sit once",
    "A recurring locked door, a colour, a joke. If it happens once it might still symbolise; motif wants the echo. Pattern is the tell.",
    "If a bird appears, freedom. Birds are a franchise.",
    "Track the repeat and what changes at each return. Then claim a function, not a poster.",
    "Green light in one famous novel is both motif and symbol because it returns and points. One green dress is just a dress until the text works it."],
  ["vx-e-form-sonnet", "Reading", "A sonnet’s argument often turns; the form is a machine",
    "14 lines, a volta, rhyme as a memory aid. Shakespearean vs Petrarchan is a volta location. Form is not a prison that deletes meaning; it shapes the thought.",
    "Sonnets are love poems so the content is always love. Count to 14 and stop thinking.",
    "Find the turn. Say what claim flips. Then how rhyme tightens or loosens.",
    "A ‘sonnet’ with 15 lines is a poem wearing a hat. Name the hat, then read it anyway."],
  ["vx-e-free-verse-not-formless", "Reading", "Free verse still has line breaks, cadence, and a reason to pause",
    "No metre contract is not ‘type until the margin’. A line break can be a volta in miniature. Enjambment vs end-stop is a choice.",
    "Free verse means grammar is optional and spelling is a vibe.",
    "Read it aloud twice: once for sentences, once for lines. The gap is the technique.",
    "A prose poem refuses lineation on purpose. That refusal is still a form."],
  ["vx-e-narrative-voice", "Reading", "Person and focalisation are not the same knob",
    "Third person can still sit in one skull (limited). First person can be a camera on the street. Omniscient is a claim of access, not a synonym for ‘fancy’.",
    "Third person is objective. First person is biased. Done.",
    "Ask: whose knowledge limits the scene? Then which pronoun. Two answers.",
    "A free indirect style smuggles a character’s words into third person. That is a tell of modern prose, not a typing error."],
  ["vx-e-juxtapose", "Reading", "Juxtaposition is a collision the writer arranged",
    "A picnic beside a briefing on casualties. The meaning is in the cut, like film. Not every two things in a room are a juxtaposition worth writing an essay on.",
    "If two images are in one book, they are juxtaposed and deep. Binding is technique.",
    "Name the two, the cut, and the extra meaning that is not in either alone.",
    "A split screen in a film is a cousin. Comics’ gutter is another. Same brain, different medium."],
  ["vx-e-allusion", "Reading", "An allusion is a nod that expects a shared library",
    "Biblical, Shakespearean, meme, Country. If the reader lacks the library, it is a closed door. Footnotes are a kindness, not a crime.",
    "Allusion is plagiarism with a wink. Always cite or it is theft.",
    "Identify the source, what is borrowed, and what is twisted. Then what a knowing reader gains.",
    "A ‘David and Goliath’ headline is an allusion so worn it is almost a dead metaphor. Still name it if it is doing work."],
  ["vx-e-satire-target", "Reading", "Satire needs a target; parody needs a form; both can miss",
    "If nobody is being criticised, it might just be silly. Punching down vs punching up is an ethics of the joke, not a metre.",
    "If it is funny it is satire. Laughter is the definition.",
    "Name the target and the exaggeration tool (irony, grotesque, mock-heroic). Then who might think they are not the target.",
    "A modest proposal that readers take straight is a reception problem. Swift counted on that risk."],
  ["vx-e-context-enough", "Reading", "Context is the bit of world that changes a reading, not a biography dump",
    "A 1915 recruitment poem and a 2015 reading of it are two contexts. Author’s breakfast is usually not. Historical situation, publication, audience.",
    "Google the author and paste three wars. That is context.",
    "Pick the fact that alters a line. Leave the rest in the unused notes.",
    "Knowing a poet was a pacifist can matter. Knowing their cat’s name usually does not. Be cruel to your own research."],
  ["vx-e-visual-grammar", "Reading", "Images have shots, angles, and a gaze, not only ‘colours are sad’",
    "High angle can diminish; close-up can trap. Salience is what the composition shoves first. A caption is a linguistic overlay.",
    "If there is a person they are the meaning. Faces cancel technique.",
    "Name framing, vector (where eyes/lines go), and anchorage (caption). Then ideology as a claim, not a mood.",
    "A government ad and a meme can share a composition trick. Compare the demand they make on you."],
  ["vx-e-thesis-arguable", "Writing", "A thesis is a fight someone could have with you",
    "‘This text uses language’ is not a thesis. ‘This text makes complicity feel like manners’ might be. Arguable, specific, about this text.",
    "The thesis is the title plus the word important. Importance is a thesis.",
    "Write a sentence that would annoy a reasonable reader who disagrees. Then preview how you will show it.",
    "A three-part list of techniques is a tour, not a thesis. Techniques are evidence later."],
  ["vx-e-topic-sentence-job", "Writing", "A topic sentence is a job ad for the paragraph",
    "It should be a claim, not ‘Another example is…’. The rest of the paragraph is the employment history.",
    "First sentence is the quote. Then you explain the quote until the page fills.",
    "Claim → evidence → explanation → link. If the claim could be cut and nothing happens, it was a label.",
    "TEEL is a scaffold, not a religion. A paragraph can still have a job without the acronym tattoo."],
  ["vx-e-quote-integrate", "Writing", "A quotation is a passenger in your grammar",
    "As X states, ‘…’ is a speech-tag. Better: The city is ‘a machine for forgetting’ (Author year). Your sentence owns the grammar; the quote supplies a phrase.",
    "Dump a block quote and run away. The quote is self-explanatory because it is famous.",
    "Trim to the working words. Cite. Then a sentence that could not have been written without that quote.",
    "A floating quote (a line that is only quotation) is a fragment wearing inverted commas."],
  ["vx-e-explain-not-label", "Writing", "Naming a technique is not analysing it",
    "‘This is a metaphor’ is a label. ‘This metaphor makes the state a weather you cannot sue’ is analysis. Markers can smell a technique hunt.",
    "The more techniques you list, the higher the mark. Density is insight.",
    "After the name, write so what for your thesis. If so what is ‘it is effective’, you have not finished.",
    "A table of techniques in the margin is a draft tool. It is not the paragraph."],
  ["vx-e-hedge-modality", "Writing", "Hedge when the evidence is thin; do not hedge a fact into mush",
    "Might, suggests, can be read as. Academic caution is a tool. ‘It could perhaps possibly seem’ is fog. Match the strength to the proof.",
    "Always write maybe so you cannot be wrong. Wrongness is a style error.",
    "If you showed it, say it. If you inferred it, mark the inference. Then stop stacking adverbs.",
    "The data show vs the data would seem to potentially indicate is a confidence tell. Readers notice."],
  ["vx-e-paragraph-unity", "Writing", "If a paragraph needs ‘also’ six times, it wanted a split",
    "One job. A new claim is a new house. Transition words are not glue for unrelated bricks.",
    "A page-long paragraph is deep. Length is development.",
    "Highlight the claim. Anything that does not serve it leaves or starts a neighbour.",
    "A narrative paragraph can move through time as one job. An essay paragraph usually cannot also start a new thesis."],
  ["vx-e-intro-map", "Writing", "An introduction earns the next line; it does not summarise the Wikipedia",
    "Text, focused claim, a map of the argument. Not the author’s childhood and a dictionary definition of love.",
    "Start with since the dawn of time. Dawn is a citation.",
    "Name the text and the fight. Promise the steps. Then go.",
    "A hook can be a precise moment from the text. A hook that is a cliché about society is a tax on the marker."],
  ["vx-e-conclusion-turn", "Writing", "A conclusion is a last turn, not a copy-paste of the intro with ‘in conclusion’",
    "So what for a reader who already believed you for three pages. A new example is usually too late; a sharper implication is not.",
    "Repeat the thesis louder. Volume is closure.",
    "Answer ‘why this reading matters’ in one tight move. Do not open a new text.",
    "In conclusion is a traffic cone. You can do without it if the turn is visible."],
  ["vx-e-register-shift", "Writing", "A slang joke in a formal paragraph is a costume change, not spice by default",
    "Register is audience plus purpose. You can shift on purpose (a character’s voice in a creative piece). Accidental shift looks like two essays glued.",
    "Bigger words are always more formal. Utilise is a tuxedo.",
    "Read a sentence aloud. If it belongs in a group chat, park it in dialogue or cut it.",
    "Academic does not mean unclear. Precision beats Latinate fog."],
  ["vx-e-show-specific", "Writing", "Specific sensory is show; a label is tell — and you need both on purpose",
    "The enamel mug clicked on the sink vs she was sad. Show costs words. Tell can move time. The crime is accidental tell when you promised a scene.",
    "Show means never say an emotion word. The rule is a cult.",
    "Pick the beats that must be felt, make them concrete. Summarise the rest.",
    "A whole story of only objects with no interior can be a style. Call it a style, not a missed feeling."],
  ["vx-e-dialogue-tag", "Writing", "Said is a pane of glass; a thesaurus tag is a circus",
    "He ejaculated is a 19th-century accident in a 21st-century scene. Action beats can replace tags. Punctuation belongs with the speech in the usual school system.",
    "Every line needs a colourful verb. Said is dead.",
    "Use said, ask, and an action. Then a new paragraph when the speaker changes.",
    "‘Hello,’ she whispered quietly is a tautology. The adverb is doing the verb’s job twice."],
  ["vx-e-plan-beats", "Writing", "A plan is cheaper than a middle that shrugs",
    "Beginning contract, midpoint turn, ending that pays the contract. Pantsing is allowed if you then reverse-outline. Submission without a spine is a vibe.",
    "Planning kills creativity. Real writers wake up in a trance.",
    "Write five beats on a sticky note. If beat four is ‘stuff happens’, you do not have a beat.",
    "Creative and essay both want a contract. The reader can feel a missing one."],
  ["vx-e-edit-pass", "Writing", "Editing is a different hat: one pass for sense, one for sound, one for ticks",
    "You will not see the repeated word until you search it. Read aloud. Change is not betrayal of the muse.",
    "Spellcheck is editing. The green underlines are a teacher.",
    "Print or change the font to see it. Cut 10%. Then fix the ticks you know you have (it’s/its, then/than).",
    "A peer who only says ‘it’s good’ is a friend, not an editor. Ask them to point at a confusing sentence."],
  ["vx-e-citation-trail", "Writing", "A citation is a trail so a sceptic can follow",
    "Author, year, page or URL as the house requires. A link that dies is a problem; a quote with no source is a worse one. AI paste with fake authors is an own goal.",
    "Footnotes are snobbery. Real knowledge is vibes plus a URL to a shop.",
    "Cite when the idea is not yours or the fact is not common. When unsure, cite.",
    "Common knowledge: water boils. Not common: a critic’s reading of a line. The second needs a name."],
  ["vx-e-title-case-it", "Writing", "A title is a contract, not a spoiler dump or a vague noun",
    "The Great Gatsby vs My Essay on Themes. Even a school task title can name the text and the angle. Italics vs quote marks are a style rule for works.",
    "Call it Essay. The filename is the title.",
    "Name the text and the fight in fewer than a dozen words if you can. Then match the running header if required.",
    "A question as a title can work if the essay answers it. A question you forget to answer is a trap you set yourself."],
  ["vx-e-synonym-trap", "Words", "A thesaurus without a connotation check is how you write ‘the protagonist masticated the sandwich sadly’",
    "Near-synonyms differ in register, intensity, and collocation. Strong tea, not powerful tea. Collocation is who the word hangs out with.",
    "If the thesaurus lists it, it fits. Roget is a grammar.",
    "Check a corpus or your ear: would this noun wear this adjective in this neighbourhood?",
    "Big vs large vs great vs major. Only some go with ‘mistake’. Try them."],
  ["vx-e-collocation", "Words", "Words have friends: make a decision, not *do a decision (in standard English)",
    "Learners notice this; natives only notice when it breaks. Make/do/take/have are famous traps. Australian English still has these habits.",
    "Any light verb plus a noun is fine. Prepositions are garnish.",
    "When in doubt, look up the noun and see which verb sits next to it in real sentences.",
    "Depend on, not depend of (usual). Different from/to/than is a dialect fight — pick a house and stay."],
  ["vx-e-nominalisation-cost", "Words", "Turning a verb into a noun can hide who did it",
    "The implementation of the policy vs they implemented the policy. Nominalisation packs and can smother agency. Scientific style loves it; civic writing often should not.",
    "Longer nouns are smarter. -tion is a degree.",
    "If you cannot see the actor, put the verb back and name them. Then decide if you still want the pack.",
    "Consideration should be given is a fog machine. We should consider is a person."],
  ["vx-e-dead-metaphor", "Words", "A dead metaphor is a fossil that used to be a picture",
    "Deadline, broadcast, understanding. You can revive one on purpose or trip over a mixed metaphor (we’ll burn that bridge when we come to it).",
    "All metaphors are equally alive. Pictures never fade.",
    "If two pictures fight (water and fire, journeys and buildings), pick one or go literal.",
    "Kick off a new chapter of growth that weathers the storm is a pile-up. One picture, then rest."],
  ["vx-e-idiom-not-lego", "Words", "Idioms are chunks; swapping a word can kill them",
    "Kick the bucket vs *kick the pail. Learners who are logical suffer. Explain, then memorise the chunk.",
    "Idioms are just metaphors you can rebuild from parts. Always.",
    "Teach as a unit. Then the warning: formal essays may not want a bucket at all.",
    "Bite the bullet is not improved as chew the ammunition. The picture is historical and stuck."],
  ["vx-e-false-friend-en", "Words", "A word that looks shared across languages (or registers) can be a trap",
    "Eventually vs éventuellement. Fabric vs fábrica. Inside English: literally now meaning ‘very’. False friends are social.",
    "If it looks like English it is English. Spelling is a passport.",
    "Check a learner’s first language and a usage example, not a vibe from the letters.",
    "Billion in older British vs American was a famous number trap. Date your source."],
  ["vx-e-spelling-pattern", "Words", "English spelling is patterns plus outlaws, not a personality test",
    "I before e except… has a famous hole. Morphology helps (sign/signature). Australian licence (n) vs license (v) in some house styles; US license both — pick a dictionary.",
    "Spelling is random so effort is pointless. Guess from personality.",
    "Learn the pattern, list the outlaws, use a spellchecker as a second pass not a first brain.",
    "Practise/practice is a UK/AU split. A marker with a US spellchecker will still ‘correct’ you. Know the contract."],
  ["vx-e-morphology-root", "Words", "A root is a map: aqua, scrib, dict — then prefixes flip the job",
    "Un- is not a decoration. Mis- vs dis- are different insults. Etymology is a hint, not a law (nice used to mean ignorant).",
    "If it is Latin it is formal and correct. Roots are tuxedos.",
    "Split prefix–root–suffix. Then check a modern dictionary meaning, because drift happens.",
    "Inflammable vs flammable is a morphology prank. Both can burn. Prefer a plain warning."],
  ["vx-e-ambiguity-scope", "Words", "Ambiguity is often a scope problem: who owns the modifier",
    "She saw the man with the telescope — who has it? Legal English tries to kill this. Poetry keeps it on purpose.",
    "If two readings exist the sentence is broken. Always.",
    "Rewrite to pin the modifier. Or keep the fork and claim it as a technique.",
    "No smoking rooms available is a hotel classic. Rooms that do not smoke vs none available for smokers."],
  ["vx-e-euphemism", "Words", "A euphemism is a soft costume over a hard fact",
    "Passed away, downsizing, collateral. Sometimes kindness; sometimes a fog for harm. Read what is under the costume.",
    "Polite words are always ethically better. Soft is good.",
    "Name the blunt version. Then ask who benefits from the soft one.",
    "Enhanced interrogation is a political euphemism. Restroom is a social one. Do not treat them as the same sin."],
  ["vx-e-jargon-audience", "Words", "Jargon is precision for insiders and fog for outsiders",
    "A doctor’s acronym in a patient leaflet is a failure of audience. The same acronym in a lab note is a mercy.",
    "Smart people use jargon; plain words are dumbed down. Always.",
    "Match the term to the reader. Define once if you must keep it.",
    "Stakeholders in a school newsletter can mean ‘we did not want to say parents and students’. Sometimes say parents and students."],
  ["vx-e-tone-word-choice", "Words", "Tone is a weather made of small choices, not a sticker on the file",
    "Could you vs you must. Kid vs child vs offspring. A bureaucratic passive vs a second-person instruction. Tone is cumulative.",
    "Tone is whether you used an exclamation mark. Punctuation is personality.",
    "Cluster three word choices and name the attitude. Then check it matches the purpose.",
    "A funeral notice in matey slang can be a community voice or a misfit. Audience decides, not a universal rule."],
  ["vx-e-aust-english", "Words", "Australian English is a variety, not a typo of American",
    "Colour, organise, metre (the unit), program/programme fights, arvo in speech. School essays usually want standard written AU, not a transcript of the bus.",
    "Correct English is American because of the software. Red underlines are law.",
    "Set the document language. Then keep slang in dialogue or in a voice piece, not as accidental drift.",
    "Mate in a formal letter to a minister is a register crash unless the relationship already owns it."],
  ["vx-e-inclusive-lang", "Words", "People are not their labels as a whole self — and names beat categories",
    "Person-first vs identity-first (person with autism vs autistic person) is community-specific. Ask or follow the style the community you are writing with uses. Do not invent a kindness from a forum.",
    "The longest phrasing is the most respectful. Word count is ethics.",
    "Use the name they use. Avoid outdated slurs even when quoting unless the quote is the point and you handle it.",
    "A style guide (government, newspaper, community org) is a contract. It will date. Dating is expected."],
  ["vx-e-ethos-how", "Speaking & media", "Ethos is ‘why listen’ built from competence, care, and character",
    "A lab coat, a lived experience, a track record. Fake ethos is a costume (stock photos in a white coat). It can be earned in the speech too.",
    "Ethos means ethics, so if you are nice you have ethos. Niceness is a credential.",
    "Name the credibility move. Then whether it is relevant to the claim (a celebrity vitamin is a mismatch).",
    "A student speech can build ethos by showing the work, not by pretending to be a minister."],
  ["vx-e-pathos-how", "Speaking & media", "Pathos is feeling on purpose, with a target",
    "A single named story vs a statistic. Both can be pathos. Manipulation is pathos that hides the ask. Tears are not an argument by themselves.",
    "If I cried it was a good speech. The body is a rubric.",
    "Name the feeling, the device (image, anecdote, music), and the action it wants.",
    "A charity ad with a soundtrack in a minor key is a pathos machine. You can still agree with the cause and name the machine."],
  ["vx-e-logos-chain", "Speaking & media", "Logos is a because-chain, not a number in a slide",
    "Premises, a warrant, a conclusion. A chart can still be a bad inference. False precision (7.42% of students feel) is a costume of logos.",
    "If there is a graph it is logical. Axes are arguments by themselves.",
    "Write therefore and see if the steps hold. Then check the data’s source.",
    "A speech with three numbered points can still be three slogans. Numbers are not logos without links."],
  ["vx-e-speech-breath", "Speaking & media", "A speech lives in breath: pause is punctuation",
    "A comma on the page is not a gulp in the room. Emphasis is volume, pause, and slowing — not underlining every word. Time the ending.",
    "Faster is more passionate. Fill every silence so they know you are clever.",
    "Mark breaths on the script. Practise looking up. End before the bell trains them to clap from relief.",
    "Um is human. A wall of um is a planning problem. Notes are allowed in most school settings — check."],
  ["vx-e-audio-rhetoric", "Speaking & media", "Podcast and radio have no italics: voice does the work",
    "Pace, music beds, and who gets the last word in an edit. A ‘raw’ tape is still cut. Silence can be a device or a glitch.",
    "If it is audio it is authentic. Microphones cannot frame.",
    "Listen twice: once for claims, once for the bed and the cuts. Name an edit as a choice.",
    "A laugh track is an instruction to the body. A true-crime sting is a genre promise about danger."],
  ["vx-e-ad-target", "Speaking & media", "An ad is a targeting machine: offer, fear, identity",
    "AIDA is a scaffold (attention, interest, desire, action). Algorithms now pick the audience before the slogan. The creative is not the whole ad.",
    "If it is pretty it is not selling. Art cannot be commercial.",
    "Name the ask, the implied audience, and the feeling. Then what is left out (price, labour, harm).",
    "A native ad that looks like an article is a costume. The disclosure line is part of the text — if it exists."],
  ["vx-e-news-angle", "Speaking & media", "A news angle is a chosen front door, not ‘what happened’ as a gas",
    "Conflict, novelty, proximity, elite people. Two outlets, one event, two doors. Headline and lead are the angle; the tenth paragraph might be the other story.",
    "News is a camera on reality with no editor. Events arrive pre-angled.",
    "Compare two leads. Name the values. Then whose door is missing (workers, Country, the boring cause).",
    "If it bleeds it leads is a market claim, not a law of the universe. Still a useful suspicion."],
  ["vx-e-caption-frame", "Speaking & media", "A caption is a frame that can contradict the image on purpose",
    "Anchorage (Barthes) ties the floating image. A sarcastic caption is a second text. Alt text is a civic cousin for access.",
    "Captions are labels. Labels cannot lie because they are small.",
    "Read image without caption, then with. The difference is the caption’s job.",
    "A stock photo of a handshake plus ‘community consultation’ can be a hope or a lie. The caption is the claim."],
  ["vx-e-stereotype-cost", "Speaking & media", "A stereotype is a shortcut that bills someone",
    "It speeds a joke and taxes the group not in the room. Tropes can be flipped on purpose; the flip still needs the original to land.",
    "Stereotypes are true on average so they are fine in art. Averages are ethics.",
    "Name the shortcut, who it excludes, and whether the text is using or exposing it. Then evidence.",
    "A ‘bogan’ gag on Australian TV is a class camera. Ask who is laughing and who is the furniture."],
  ["vx-e-intertext", "Speaking & media", "Texts talk to other texts: sequel, sample, meme, canon",
    "You understand this poster because you have seen that film. A closed intertext is a club. School English often wants the named partner.",
    "If I have not read the other book, this book is broken. Authors owe you a prequel pack.",
    "Name the earlier text, what is borrowed, what is new. Then what a knowing reader extra-gets.",
    "A Shakespeare play that is also a teen film is an adaptation chain. Cite both dates."],
  ["vx-e-pitch-order", "Speaking & media", "A pitch has an order that does work: problem, stakes, ask",
    "Do not start with the budget line if they do not yet care. Demo, then logistics. Timebox. A pitch is not a plot dump.",
    "Start with your childhood and end with the logo. Feelings first, always, for ten minutes.",
    "Write the ask in one sentence. Put it where they still have attention. Then the next step, not the whole novel.",
    "A school pitch for a podcast still needs audience and length. ‘It will be good’ is not a beat."],
  ["vx-e-inclusive-address", "Speaking & media", "How you name the room is a politics: guys, folk, you lot",
    "Guys as generic is a dialect some accept and some do not. Ladies and gentlemen misses people. You is often enough.",
    "The traditional address is neutral because it is old. Age is a solvent of bias.",
    "Pick an address that includes the actual room. If you get it wrong, correct without a TED talk about your journey.",
    "A principal’s ‘boys and girls’ to a mixed staff meeting is a register fossil. Fossils still land."],
  ["vx-e-slide-not-script", "Speaking & media", "Slides are a visual aid, not the speech printed in 10-point",
    "If you read the slide, the room can read faster than you talk and will. One claim, a picture, or a number. Notes are for you.",
    "More bullet points are more professional. Density is respect.",
    "Cut until the slide is useless without you. That is the point.",
    "A wall of text is a handout. Send a handout. Do not perform a handout."],
  ["vx-e-interview-listen", "Speaking & media", "An interview is a listen with a planned follow-up, not a questionnaire recitation",
    "Open questions, silence as a tool, and a follow-up on the interesting word they used. Recording consent is a civic.",
    "Ask the list in order no matter what they say. The list is the job.",
    "Write three must-asks, then park them if a better door opens. Transcribe honestly.",
    "A nod is not a question. ‘That’s so interesting’ can be a filler that stops them. Let the pause work."],
  ["vx-e-rhetoric-kairos", "Speaking & media", "Kairos is timing: the same speech on a different day is a different text",
    "A climate speech during a fire week vs during a sports final. Opportunity is part of persuasion. Too late and too early both fail.",
    "Good arguments work in any week. Truth has no calendar.",
    "Name the moment you are speaking into. Then what would change if the date changed.",
    "A Year 12 oral the morning after a scandal at school will be heard through that scandal. Pretending otherwise is a choice."],
  ["vx-e-medium-afford", "Speaking & media", "A medium affords some moves and blocks others",
    "SMS has no footnote. Theatre has bodies in a room. TikTok has a timer. Do not analyse a play as if it were a tweet, or a tweet as if it were a novel.",
    "Content is content. Platform is wallpaper.",
    "Name what this medium can do that the other cannot. Then the constraint as a technique (character limit as punchline).",
    "A novelistic inner monologue in a group chat is a mismatch unless the piece is about that mismatch."],
  ["vx-e-active-listening", "Speaking & media", "Listening is a showing: paraphrase, then disagree if you must",
    "Steel-man their point in a clause. Then your but. Debate that skips this is two monologues with a timer.",
    "Listening means waiting to talk. Silence is agreement.",
    "Repeat the claim fairly. Ask if you got it. Then the critique.",
    "In a classroom, this is how you avoid the straw man you will later write an essay about."],
  ["vx-e-multimodal-cohere", "Speaking & media", "Multimodal means the modes should talk, not stack",
    "Image, text, sound, space. If the slide says RUN while the voice says wait, you made a third meaning (maybe on purpose). Coherence is a design.",
    "More modes are more marks. Add a GIF.",
    "Pick a boss mode for each beat. The others support. Then test with the sound off and with the picture covered.",
    "A poster with five fonts and a QR and a poem is a pile. Hierarchy is a kindness."],
  ["vx-e-then-than", "Words", "Then is time; than is comparison",
    "Bigger than, then we left. Autocorrect will not save a tired brain. Than also lives in rather than.",
    "They sound alike so they are alike. Spelling is a vibe after 9 pm.",
    "Substitute next (then) vs compared with (than). One will look absurd.",
    "If you want a mnemonic, then vs than: than has a comparison a in it if you squint. Unreliable. Just check."],
  ["vx-e-affect-effect", "Words", "Affect is usually the verb; effect is usually the noun",
    "The rain affected play. The effect was a delay. Exceptions: to effect change (verb ‘bring about’); affect as a psychology noun. School mostly wants the first pair.",
    "They are interchangeable because both are about change. Pick by mood.",
    "Try substituting influence (verb) vs result (noun). Then the rare exceptions if you need them.",
    "A weather ‘affect’ on a tennis court is a verb. A special effect is a noun with a Hollywood hat."],
  ["vx-e-who-that-people", "Sentences", "People often take who; things take that — as a courtesy rule",
    "The students who… The policy that… Companies as they vs it is a house style. A that for a person is common in speech and still marked in some essays.",
    "Who is only for questions. That is for everyone else.",
    "If the head is a person you are treating as a person, prefer who. Then stay consistent.",
    "The team who vs the team that depends on whether you see a club of people or a unit. Pick and do not wobble."],
  ["vx-e-semicolon-list", "Sentences", "A semicolon can separate list items that already have commas",
    "We invited Kim, the coach; Sam, the captain; and Jo. Commas alone would be a pile-up. This is not a licence to semicolon every pause.",
    "Semicolons are fancy commas. Sprinkle for tone.",
    "If a list item has its own comma, upgrade the separators. Otherwise a comma is enough.",
    "A colon still introduces the list. The semicolons work inside it. Two jobs."],
  ["vx-e-foil-character", "Reading", "A foil is a character who shows another by contrast",
    "Not an enemy automatically. A cautious friend can foil a reckless lead. Contrast is the job; conflict is optional.",
    "Foil means the baddie. Opposite equals villain.",
    "Name the trait pair and a scene where they sit side by side. Then what we now see in the lead.",
    "A comic sidekick can be a foil and a relief valve. Two jobs, still contrast."],
  ["vx-e-setting-pressure", "Reading", "Setting is a pressure, not a postcard",
    "Heat, a closed room, a border, a school bell. If you can swap Sydney for ‘a city’ and nothing happens, the setting was wallpaper.",
    "Setting is where. Where is a Google pin. Done.",
    "Ask what the place prevents or allows. Then weather as a mood-machine only if the text earns it.",
    "A bushfire novel that could be a snowstorm with the same plot did not need that Country. Some texts do."],
  ["vx-e-genre-contract", "Reading", "Genre is a contract of promises and allowed surprises",
    "A detective story promises a puzzle. Breaking the contract can be the point (anti-detective) but you have to know the contract to break it.",
    "Genre is a prison. Real literature has none.",
    "Name the promise (romance union, horror survival, tragedy fall). Then what this text keeps or twists.",
    "A ‘literary’ novel still has habits. Refusing the word genre is often a class move, not a description."],
  ["vx-e-counterclaim", "Writing", "A counterclaim you steel-man is worth more than a scarecrow",
    "State the best opposing view, then why your evidence still wins (or where you concede a bit). Concession is not collapse.",
    "Mention the other side in three sneering words so they look stupid. That is rebuttal.",
    "Write their best sentence. Answer it with a source, not a vibe. Then return to your thesis without a new one.",
    "Some school tasks want a paragraph of this. A whole essay of only rebuttal never stated a case."],
  ["vx-e-sentence-variety", "Writing", "A page of identical sentence lengths is a drum machine",
    "Short for a hit. Long for a complex because. Variety is not random; it follows the thought. A rhetorical fragment can be a hit if the rest pays tax.",
    "Longer sentences are smarter. Always combine with which and and.",
    "Read aloud. Where you gasp, split. Where it patters, combine a pair.",
    "A punchy one-sentence paragraph is a spice. A whole essay of them is an advert."],
  ["vx-e-common-error-apostrophe-s", "Words", "Plural is -s; possessive is ’s — they are not a flavour of the same mark",
    "Dogs, dog’s, dogs’. 1980s usually no apostrophe. CDs, not CD’s, for a plain plural. Names: James’s vs James’ is a house fight — pick a guide.",
    "Apostrophes make words fancy and plural. More marks, more grammar.",
    "Ask: more than one, or belonging? Then the mark. Never in a simple decade plural if your guide says so.",
    "Its/it’s is the celebrity cousin of this rule. Do that one first."],
  ["vx-e-preposition-end", "Sentences", "A preposition at the end is often English, not a crime",
    "Who did you give it to? is how people speak. To whom did you give it? is a formal costume. Churchill’s joke about ‘up with which I will not put’ is the usual cartoon.",
    "Never end with a preposition. Latin said so, and Latin owns English.",
    "If the sentence is clear, a terminal preposition is fine in most school writing. Recast only if it sounds like a stumble.",
    "A stranded preposition with no object is a different bug: ‘This is the book I told you about it’ — extra it."],
  ["vx-e-compare-contrast-lens", "Reading", "A comparison essay needs a lens, not two summaries stapled",
    "Theme, form, or context as the shared question. ABAB by point beats all-of-A then all-of-B for most markers. The last paragraph should not discover the link.",
    "Write about book one, then book two, then say they are both books. Staple is structure.",
    "State the lens in the thesis. Each paragraph should touch both (or clearly why one).",
    "Differences are not a failure of the comparison. Contrast is the point of a lens."],
  ["vx-e-anecdote-limit", "Writing", "An anecdote is a spotlight, not a census",
    "One story can open an issue. It cannot prove a rate. Pair it with a source if you are in persuasive civic mode.",
    "If it happened to my uncle it is national data. Family is a methodology.",
    "Use the story to make a person visible, then the evidence for how common. Or stay in creative mode and drop the pretend stats.",
    "A speech that is only anecdote plus volume is pathos without a floor. Some rooms still clap. Markers may not."],
  ["vx-e-headline-noun", "Speaking & media", "A headline that hides the actor is a choice",
    "‘Mistakes made in payroll’ vs ‘Council underpaid staff’. Nominalisation and passive are news tools. The missing noun is often power.",
    "Headlines are too short to name anyone. Space is innocence.",
    "Ask who did what to whom. If you cannot see it, the headline is a fog. Then read the lead to check if the fog continues.",
    "A tabloid and a broadsheet on the same court case will name different nouns first. That is the angle."],
  ["vx-e-rhetoric-repetition", "Speaking & media", "Repetition is a drum: anaphora, chorus, slogan",
    "I have a dream is anaphora. A chorus in a song is the same family. Overdo it and it is an advert jingle whether you meant it or not.",
    "Repeating is padding. Cut every echo.",
    "Repeat the phrase that is the claim, not the filler. Then stop one beat before they can chant it without you — or let them, if that is the design.",
    "A school speech with three ‘we must’ can work. Thirty ‘we must’ is a filling machine."],
  ["vx-e-subtext-dialogue", "Writing", "Subtext is the fight under the small talk",
    "‘Nice weather’ during a breakup scene is often not meteorology. If the subtext never surfaces in behaviour, you wrote a weather report.",
    "Good dialogue explains the theme in complete sentences. Characters are lecturers.",
    "Write what they will say in public. Then what they want. Cut until the want leaks in the gaps.",
    "A character who says ‘I am angry because of my father’ is text, not sub. Sometimes you need that. Call it on-the-nose on purpose or cut it."],
  ["vx-e-proofread-homophone", "Words", "Homophones survive spellcheck: their, there, they’re",
    "Grammar checkers catch some and miss others. Read the sentence for meaning, not for red squiggles. To/too/two is the same family.",
    "If there is no red line it is correct. Software is a senior marker.",
    "Search each homophone you personally mix. Fix in a dedicated pass, not while drafting.",
    "Australian they’re still equals they are. Their is possession. There is a place or a dummy subject. Three jobs."],
  ["vx-e-reader-position", "Reading", "A text positions you: ally, judge, eavesdropper, customer",
    "Second person you, a confiding I, a cold chart. Positioning is not always consent. You can refuse the seat and still describe it.",
    "If I felt it, the text made me feel it correctly. My feeling is the reading.",
    "Name the seat you were offered. Then whether you sat. Then a line that offered it.",
    "An ad positions you as a lack. A tragedy may position you as a witness who cannot help. Different civic jobs."],
]);
