import { pack } from "../pack.mjs";

export const GEOGRAPHY_VOLUME = pack("geography", [
  ["vx-g-grid-vs-mag", "Maps", "Grid north is the map’s north; magnetic north wanders",
    "Declination is the gap. A compass without a correction walks a slow diagonal. Grid north is the easting lines, not a feeling of ‘up the page’ if the map is rotated.",
    "North is the top of the paper. Always. Compasses are theatre.",
    "Read the declination diagram, add or subtract as the map year says, and recheck if the map is old.",
    "Magnetic north moves. A 1980s map’s diagram is a historical document. Bushwalks want a current figure."],
  ["vx-g-isobar", "Maps", "Isobars are pressure twins; tight packing is a wind",
    "Lines of equal pressure. Close lines, steep gradient, stronger wind. A ‘round high’ is not a hill on land.",
    "Isobars are temperature because iso means weather.",
    "Read the interval, find the gradient, then wind roughly along the lines in the Southern Hemisphere’s clock (Buys Ballot as a later hat).",
    "A forecast map’s isobars are a model, not a photograph of air. Fronts are extra symbols."],
  ["vx-g-dot-map", "Maps", "A dot map is a count in place, and dots can lie about size",
    "One dot = n people or farms. Stacked dots in a CBD can look like a disease. Random placement inside a LGA hides the street.",
    "More dots always means more important. Size of the paper is the data.",
    "Read the legend’s n, then whether dots are true points or ‘somewhere in the polygon’.",
    "A single huge dot for Western Australia’s population parked in the desert is a placement crime."],
  ["vx-g-cartogram", "Maps", "A cartogram warps area to a number, on purpose",
    "Countries swell by votes or by CO₂. You cannot measure a true km on it. That is the point and the trap.",
    "The biggest shape is the biggest country. Area is still land.",
    "Read what variable ate the area. Then do not navigate with it.",
    "A population cartogram makes Australia skinny and Japan chunky. That is people, not geology."],
  ["vx-g-flow-map", "Maps", "A flow map is a thickness of movement, not a road atlas",
    "Arrows of migrants, trade, or water. Width should be the quantity. A spaghetti of arrows is a design fail, not ‘complexity’.",
    "If there is an arrow, people walked that exact line. GIS is a GPS trace.",
    "Read the legend’s width scale. Ask origin, destination, and time window.",
    "Net flow vs gross flow: two arrows can hide that both directions are busy. Tourism vs migration are different cargos."],
  ["vx-g-legend-argument", "Maps", "A legend is an argument about classes",
    "Jenks vs equal interval vs quantiles change who looks ‘high’. A rainbow on ordinal data is a lie of smoothness.",
    "Darker is worse, always, and the legend is a sticker.",
    "Read class breaks. Then who sits just below a break and looks ‘fine’.",
    "A 7-class choropleth of a tiny sample is jewellery. Fewer classes, more honesty."],
  ["vx-g-gps-not-map", "Maps", "A GPS pin is a guess with satellites; a map is a model with a date",
    "Canyons, CBD towers, and a wrong datum (GDA94 vs WGS84 leftovers) shift you. Battery dies; contours do not.",
    "The blue dot is truth. Paper is for museums.",
    "Carry a map and a charged plan. Check datum. Then a bearing as backup.",
    "What3words is a commercial grid, not a replacement for a topographic name in an emergency radio call — know what the SES wants."],
  ["vx-g-time-zone-long", "Maps", "Fifteen degrees of longitude is a clock hour in the crude model",
    "360/24 = 15. Political zones ignore the model (China is one zone; Broken Hill sits on a choice). Daylight saving is a further political hour.",
    "If it is east it is later, always, by the number of kilometres.",
    "Use longitude for a first estimate, then the actual zone map, then DST if in season.",
    "The International Date Line is a kink around islands so a nation can share a calendar. It is not the 180° meridian as a religion."],
  ["vx-g-scale-bar", "Maps", "A scale bar survives photocopy better than a verbal scale",
    "Measure the bar, not the memory of ‘1 cm was 1 km’ after a resize. Representative fraction dies in a screenshot crop.",
    "If you zoom a PDF the RF is still true. Software is honest.",
    "Use the bar printed on that image. Recheck after any resize.",
    "A north arrow that was cropped off is how you walk into a swamp with confidence."],
  ["vx-g-inset-map", "Maps", "An inset is a second scale, not a sticker",
    "A city inset at 1:10 000 beside a 1:1 000 000 nation. Measuring across the neatline is a crime. The locator globe is a third map.",
    "Everything on one sheet shares one scale. Obviously.",
    "Read each frame’s scale. Then which frame the question is about.",
    "An inset of Antarctica on an Australia map is a political cousin of ‘who we are’, not a walking map."],
  ["vx-g-proportional-sym", "Maps", "A proportional symbol’s area (not radius) should carry the number",
    "Double the people is double the area, which is not double the radius. Eyes still misread area. A 3D sphere is worse.",
    "Taller symbol, bigger number, even if it is a 3D oil drum. Height is truth.",
    "Check whether they scaled radius or area. Then mistrust your gut on the big circles.",
    "A huge circle over the NT can mean one mine’s output, not ‘the Territory is full’. Read the unit."],
  ["vx-g-mental-blank", "Maps", "What you cannot sketch is a bias, not a personal failing only",
    "Pacific nations vanish. Country names vanish. The US inflates. Sketch-from-memory is a test of media, school, and travel, not IQ.",
    "If I drive there my map is complete. Driveways are atlases.",
    "Draw Australia from memory, then add neighbours. Notice who is missing (often Timor-Leste, often PNG inland).",
    "A Sydney-first Australia with a vague ‘north’ is a document of a coastal urban life."],
  ["vx-g-remote-date", "Maps", "A satellite scene without a date is a pretty rumour",
    "Flood, fire scar, crop, snow. Yesterday vs last year is the whole claim. Cloud is not land use.",
    "From space is now and true. Orbit is a court.",
    "Read timestamp, band (false colour), and resolution. Then ground-truth if the decision is expensive.",
    "A green oval in a drought can be a golf course’s privilege. Colour is not virtue."],
  ["vx-g-6fig-grid", "Maps", "Eastings then northings: along the corridor, then up the stairs",
    "6-figure is a 100 m square, not a doormat. 4-figure is 1 km. A helicopter to a 4-figure picnic is a comedy.",
    "Northings first because north is more important. Up then along.",
    "Right, then up. Quote map name and edition. Then the grid letters if the sheet uses them.",
    "A GPS six decimal degrees is a different language. Do not paste it into a six-figure box."],
  ["vx-g-projection-pick", "Maps", "Pick a projection for the job: navigate, area, or pretty classroom",
    "Mercator for rhumb lines; equal-area for comparing land; polar for the ice. There is no innocent default.",
    "The classroom wall is true shape. Childhood is a datum.",
    "Ask what must not lie (area? angle?). Then whose land looks bigger as a political effect.",
    "Australia on Mercator is less distorted than Greenland. That is latitude, not national virtue."],
  ["vx-g-bearing-back", "Maps", "A back bearing is plus 180°, wrapped at 360",
    "Walk 045, return 225. Three digits. Magnetic vs grid still applies. ‘The opposite feeling’ is not a number.",
    "Turn around is 90° because a right angle feels like reverse.",
    "Add 180, subtract 360 if you pass it. Then check with the compass while standing still.",
    "A closed traverse that does not close is error, not a new landform."],
  ["vx-g-orographic", "Earth systems", "Orographic rain is a mountain wringing a moist wind",
    "Windward wet, leeward rain shadow. The Divide does this to eastern Australia in a textbook cartoon that is still useful. Convection is a different cloud factory.",
    "Mountains are wet because they are high and cold, even with dry winds. Altitude is a tap.",
    "Name wind direction, the barrier, and which side you are on. Then a town pair (Cairns vs Hughenden as a rough cousin, not a law).",
    "A rain shadow is not a desert visa. It is a relative drying."],
  ["vx-g-convection-storm", "Earth systems", "Convectional rain is ground-heated air going up",
    "Afternoon storms, tropical build-ups. The land heats, a parcel rises, cools, dumps. Not the same as a front’s factory.",
    "All rain is orographic if you wait. Mountains hide everywhere.",
    "Time of day and season first. Then instability (hot land, cold aloft) as the fuel.",
    "A Sydney February storm can be convection plus a sea breeze collision. Real air stacks mechanisms."],
  ["vx-g-front-weather", "Earth systems", "A cold front is a shoving match, not a temperature sticker only",
    "Colder air wedges under warmer. A line of storms, a wind shift, a dry slot after. Warm fronts are a different, gentler slope in the cartoon.",
    "If the mercury drops it was a front. Night is a front.",
    "Read a sequence: wind, cloud, rain, change. Then the map’s blue triangles.",
    "Southern Australia’s ‘change’ is often this. The tropics have other habits (monsoon trough)."],
  ["vx-g-coriolis-feel", "Earth systems", "Coriolis is a deflection on a spinning planet, not a plug-hole law",
    "Long-range winds and currents feel it. Your sink does not. Southern Hemisphere deflection is opposite the north in the standard story.",
    "Toilets prove the hemisphere. Plumbing is a lab.",
    "Use it for gyres and cyclones (rotation sense), not for bath time.",
    "A tropical cyclone’s eye is a pressure and rotation story. Category is wind, not a moral."],
  ["vx-g-ocean-gyre", "Earth systems", "A gyre is a basin-scale loop; rubbish can ride it",
    "East coasts of continents often get warm poleward currents in the simple model (EAC off NSW). West coasts can upwell. Plastic is a passenger, not a continent of rubbish as a solid island.",
    "The ocean river goes where Google Maps draws a blue arrow on the beach.",
    "Name the basin, the boundary current, and the human cargo. Then upwelling as a fishery gift with a climate vulnerability.",
    "El Niño can slack the usual upwelling elsewhere. Australia’s east coast still has its own EAC moods."],
  ["vx-g-albedo", "Earth systems", "Albedo is a reflectivity; ice is a bright shield that can vanish",
    "Dark water eats sunlight. Snow sends it back. A melt-water feedback is a trapdoor. Clouds have their own albedo story.",
    "White is cold because white is ice cream. Colour is temperature as a law.",
    "Ask what surface replaced what. Then the feedback direction.",
    "A city of dark roofs is a small albedo experiment. Ice sheets are the big one."],
  ["vx-g-carbon-sink-time", "Earth systems", "A sink stores carbon for a while, not forever as a slogan",
    "Forest, ocean, soil. A bushfire un-sinks a forest quickly. Geological sinks are slow. Planting a tree is not a coal mine in reverse on a human deadline unless the accounting is honest.",
    "If it is green it is a permanent vault. Leaves are a safe.",
    "Name the pool, the residence time, and the leak (fire, warming soils, acidifying ocean).",
    "Blue carbon in mangroves is a real pool with a coastal development threat. Do not double-count it in a school poster and a company ad."],
  ["vx-g-soil-slow", "Earth systems", "Soil is a slow factory of rock plus life plus time",
    "Horizons, texture, and a climate. Erosion can spend a factory in a storm. Salinity is a different spend (water table plus salt).",
    "Dirt is dirt. A desert and a volcanic loam are equivalent brown.",
    "Name parent rock, climate, and organisms. Then a human practice (clearing, tillage) as a rate change.",
    "Australian ancient soils can be nutrient-poor. That is why fertiliser and fire management are not footnotes."],
  ["vx-g-delta-estuary", "Earth systems", "A delta builds with sediment; an estuary is a drowned valley mixing salt",
    "Not every river mouth is a delta. Wave-dominated coasts may not bother. Mangroves like the mix.",
    "If it is muddy it is a delta. Mud is the definition.",
    "Ask sediment supply vs sea energy. Then salinity as a habitat machine.",
    "The Murray mouth is a political estuary with a dredge. A textbook Nile is not a template you paste on SA."],
  ["vx-g-longshore", "Earth systems", "Longshore drift is a sideways conveyor along a beach",
    "Waves at an angle, swash up, backwash down. Groynes starve the downdrift neighbour. A ‘fixed’ beach is a political choice.",
    "Beaches sit still. Sand is furniture bolted to the council.",
    "Draw the wave approach, then the net transport. Then who loses sand after a wall.",
    "A storm can do a year of work in a night. Drift is the average thief."],
  ["vx-g-weathering-split", "Earth systems", "Weathering breaks in place; erosion moves the bits",
    "Freeze-thaw, salt, roots, hydrolysis. Gravity, water, wind, ice then take. A cliff that sheds is both, in sequence.",
    "Weathering is weather. A rainy day is a landform.",
    "Name the in-place process, then the transport. Then a landform (tors, soil, caves).",
    "Uluru’s surface is a weathering story with a cultural one. The science sentence does not replace the cultural one."],
  ["vx-g-monsoon-au", "Earth systems", "A monsoon is a seasonal wind reversal, not ‘tropical rain’ as a brand",
    "The Top End’s wet/dry is this family. Build-up, then storms, then a dry. Timing shifts; ‘failed wet’ is a livelihood word.",
    "Monsoon means it rains on public holidays. Calendar is climate.",
    "Name the wind flip and the wet-season months for that place. Then ENSO as a shifter of odds.",
    "Darwin in July is dry-season trade. A tourist in a raincoat in August misread the poster."],
  ["vx-g-biome-limit", "Earth systems", "A biome is climate plus life, with messy edges",
    "Savanna vs wet sclerophyll vs desert. Soil and fire can veto a climate’s ‘should’. Australia’s sclerophyll is a fire-and-nutrient story as much as a rainfall one.",
    "If it is hot it is jungle. Latitude is a vegetation app.",
    "Match temperature and rainfall first, then fire, soil, and people. Then admit ecotones.",
    "A mapped biome on a school wall is a cartoon. Useful cartoon. Not a fence on Country."],
  ["vx-g-ice-landform", "Earth systems", "Glacial ice carves valleys and banks sea level, not Christmas ads",
    "Glaciers carve and dump (U-valleys, moraine). Ice sheets store sea level. Australia’s ice is a heritage of older glaciations plus alpine leftovers, not a Greenland.",
    "Ice is only scenery for Christmas ads. It does not do geography.",
    "Name erosion vs deposition features. Then melt as a water-resource and sea-level ticket.",
    "The Snowy hydro catchment is a water-tower politics. Ice and snow are not the same storage."],
  ["vx-g-ring-of-fire", "Earth systems", "The Ring of Fire is a plate-edge club, not a camping brand",
    "Pacific subduction, volcanoes, quakes. Australia sits inside the plate, which is why we still get intraplate shocks (Newcastle) without being ‘on the ring’ as a tattoo.",
    "If you can see the Pacific you are on the Ring. Beaches are plate boundaries.",
    "Map trenches and volcanoes. Then our plate’s northward shove as a different, slower story.",
    "A tsunami warning for the NSW coast is usually a far-field cousin, not a local subduction factory. Still listen."],
  ["vx-g-dtm-stages", "People & places", "The demographic transition is a model of birth and death rates, not a moral ladder",
    "Death rates fall (health), then birth rates fall (many reasons), population growth in the gap. Stage numbers are a cartoon. Some countries stall; some skip.",
    "Poor countries are in stage 1 because they are behind. The model is a race.",
    "Sketch crude birth and death. Then ask what the model hides (migration, women’s rights, HIV, oil money).",
    "Australia is not ‘done’. Ageing and migration rewrite the pyramid while we sit in a late stage cartoon."],
  ["vx-g-dependency", "People & places", "A dependency ratio is kids plus older people over working-age — a blunt stick",
    "Who counts as working age is a policy. Unpaid care is invisible. A ‘youthful’ pyramid and an ‘ageing’ one stress different services.",
    "If there are lots of kids the country is poor. Pyramids are GDP.",
    "Compute with the ages they gave. Then say what the ratio cannot see (unemployment, FIFO, disability).",
    "Japan and Nigeria are the usual textbook pair. Do not paste them onto a remote NT community without data."],
  ["vx-g-remittance", "People & places", "Remittances are wages travelling home, a quiet GDP",
    "A nurse in Sydney sending money to Manila. It can beat aid. It can also drain care from the origin and tie families to a visa.",
    "If they left they stopped belonging. Money is not geography.",
    "Map the corridor, the fee, and the dependency. Then a shock (COVID, a ban) as a test.",
    "Pacific-Australia labour schemes are this in policy costume. Read who pays the plane."],
  ["vx-g-gentrify", "People & places", "Gentrification is capital rewriting a neighbourhood’s guest list",
    "Rent up, cafes up, old tenants out. Culture can be a marketing aftertaste of the people who were priced off. Not every new cafe is this — look at tenure and class.",
    "If it looks nicer it is development. Nice is a synonym for just.",
    "Track rent, displacement, and who owns. Then heritage paint as a possible weapon.",
    "An inner-Sydney terrace with a wine bar can be this. A new suburb on the fringe is usually a different machine (greenfield)."],
  ["vx-g-primate-city", "People & places", "A primate city dwarfs the second city; a rank-size story is a different shape",
    "Bangkok vs a Thai second city is the usual cartoon. Australia is oddly multi-metropolitan, not a single primate like some states. Sydney vs Melbourne is a rivalry, not a 10× primate gap.",
    "The capital is always primate because it is the capital. Law of flags.",
    "Compare the first and second urban populations. Then colonial history as a why.",
    "South Australia looks more primate (Adelaide) than NSW. Scale inside a state, not only a country."],
  ["vx-g-informal-work", "People & places", "Informal work is a system with rules, not ‘chaos’ as a slur",
    "Street vending, cash jobs, unregistered rentals. It can be survival and a tax hole and a safety hole. Formalising can help or smash a livelihood.",
    "If it is not in the GDP it is not work. Spreadsheets are reality.",
    "Ask who enforces which rule (police, gangs, guilds). Then a statistic’s undercount.",
    "An Australian cash economy is informal too. Do not only aim the word at a megacity in a textbook photo."],
  ["vx-g-tnc-chain", "People & places", "A TNC is a firm that can shop for labour, tax, and law across borders",
    "Headquarters, factories, and a brand. A T-shirt’s geography is this. States still set the rules — or fail to.",
    "Global companies have no geography. They live in the cloud.",
    "Map HQ, production, and sale. Then a disaster (Rana Plaza) as a node that was always there.",
    "An Australian mining TNC in another country’s pit is a power geography. The royalty is a political number."],
  ["vx-g-container", "People & places", "The container is a box that rewired ports and labour",
    "TEU, cranes, and a hinterland of trucks. A port that did not deepen lost the game. Waterside jobs changed.",
    "Ships are ships. Boxes are packaging, not geography.",
    "Name a port, a gauge of ship size, and an inland rail/truck story. Then a chokepoint (Malacca, Suez) as a risk.",
    "Botany and Melbourne docks are landscapes of this. A cruise terminal is a different passenger box."],
  ["vx-g-timespace", "People & places", "Time-space compression is cheaper/faster links, not the death of distance",
    "A Zoom meeting and a delayed visa. Some places squeeze; some stay far (no cable, no airport). Compression is uneven.",
    "The internet made geography over. This subject can close.",
    "Ask for whom the trip shrank. Then who still needs a 14-hour bus.",
    "A FIFO worker compresses home and pit in a fortnight. That is a household geography."],
  ["vx-g-cultural-landscape", "People & places", "A cultural landscape is meaning stuck to a place, not ‘scenery plus people’",
    "A mosque, a mission, a mural, a songline that is not a tourist overlay. UNESCO words can freeze a living place into a postcard.",
    "Culture is festivals. On Tuesday the landscape is only geology.",
    "Name the group, the mark, and the contest (whose mark is heritage).",
    "Uluru’s renamed dual-name story is policy on a cultural landscape. The rock was never only a rock."],
  ["vx-g-push-pull-extra", "People & places", "Push and pull are a pair, and a chain can add a third place",
    "A drought pushes; a job pulls; a cousin in Dandenong is a network. Step migration (regional then city) is common. ‘They came for the weather’ is a cartoon.",
    "Migrants always arrive for the benefits. Pull is a voucher.",
    "List a push, a pull, and a barrier (visa, cost, sea). Then a personal network as a multiplier.",
    "Internal migration (Qld sunbelt) uses the same words without a passport. Do not reserve ‘migration’ for boats."],
  ["vx-g-liveability-index", "People & places", "A liveability index is a consultant’s weighted shopping list",
    "Safety, cafes, schools — whose safety, whose rent. Melbourne-as-world’s-most-liveable was a brand with a method. A remote community can score ‘low’ and still be home.",
    "If the list is published it is objective. Rankings are science.",
    "Read the weights. Then who is missing (Country, racism, heat). Then rent as a veto the index underplays.",
    "A high score with a homelessness count in the same CBD is a geography of two cities."],
  ["vx-g-mode-share-politics", "People & places", "Mode share is a political geography of kerb and timetable",
    "Percent of trips by car/walk/train. A new motorway can grow car share. A frequent bus can grow the other. ‘Choice’ sits on infrastructure.",
    "People drive because they love cars as a personality. Asphalt is a preference.",
    "Read the percent, the year, and what was built. Then who cannot drive (age, disability, cost).",
    "A school gate that is 90% car is a land-use plus timetable story. Staggered hours are a lever."],
  ["vx-g-food-miles-limit", "People & places", "Food miles are one slice; water, season, and methane can outweigh the truck",
    "A NZ apple in July vs a hot-house local. Lamb vs lentils. The slogan is a start, not a life-cycle analysis.",
    "Local is always kinder. Kilometres are carbon, full stop.",
    "Ask production method, then transport, then waste. A rotting ‘local’ lettuce is not a win.",
    "A mango from NT in Darwin is a different mile to a mango in Hobart in July. Season is geography."],
  ["vx-g-tourism-leak", "People & places", "Tourism money can leak to an airline and a chain hotel",
    "All-inclusive vs a locally owned tour. A cruise that eats in the ship is a floating leak. Jobs can still be real and seasonal and fragile.",
    "If tourists come, the town is rich. Suitcases are GDP.",
    "Map who owns the bed, the food, and the tour. Then a shock (fire, reef bleaching, pandemic).",
    "A backpacker farm visa is a labour geography wearing a tourism hat. Count the power."],
  ["vx-g-gab-water", "Australia", "The Great Artesian Basin is a buried water inheritance with a tap fight",
    "Confined groundwater, bores, and a slow recharge. Waste at a free-flowing bore is a 20th-century landscape. It is not an underground lake you could boat.",
    "The outback has a secret sea. Drill anywhere.",
    "Name recharge zones, bore control, and who holds a licence. Then a coal/gas overlap as a contest.",
    "A mound spring is a place and a cultural site, not a leak to ignore."],
  ["vx-g-cyclone-coast", "Australia", "Tropical cyclones have a season, a coast, and a category that is wind not rain",
    "November–April, north-west and north-east especially. Storm surge is the killer cousin. Category 1 can still flood you with rain.",
    "Cyclones are Queensland’s brand so WA is safe. Brands are meteorology.",
    "Read the track, the surge map, and the rain forecast as three tickets. Then building codes as a vulnerability story.",
    "A name is a communication tool. The hazard is the wind, water, and your roof."],
  ["vx-g-wheatbelt", "Australia", "The wheatbelt is a climate-plus-market ribbon, not a permanent yellow on the map",
    "Rainfall margins, soil, and a rail to a port. Climate shift and prices move the ribbon. Towns shrink when the ribbon does.",
    "If it was wheat in a 1960s atlas it is wheat. Atlases are covenants.",
    "Overlay rainfall reliability, then a silo, then a closed shop. That is the geography.",
    "A ‘drought’ here is a livelihood word with a line on a rainfall chart. Both matter."],
  ["vx-g-fifo-town", "Australia", "FIFO is a labour geography that can empty a main street at 3 pm",
    "Fly-in fly-out: camp, roster, and a coastal home. A mining town can be a clock without families. Housing booms and ghosts follow the commodity.",
    "If there is a mine there is a community. Shafts are neighbours.",
    "Ask where people are enrolled to vote, where they sleep, and who staffs the school. Then the roster as a social time zone.",
    "A donga is an artefact. So is a coastal mortgage paid by a pit."],
  ["vx-g-nullarbor", "Australia", "The Nullarbor is a limestone plain with a highway myth",
    "Not ‘no trees’ as a total fact in every corner; the name is a boast. Bight, cliffs, and a rail. Services are a spacing problem.",
    "It is empty therefore it is nobody’s. Emptiness is a land title.",
    "Map water, fuel, and Country. Then the tourist crossing as a performance of isolation.",
    "A whale on the Bight is a marine geography stuck to a road trip story. Two layers."],
  ["vx-g-bass-strait", "Australia", "Bass Strait is a fetch, a cable, and a ferry",
    "Shallow, rough, a wind farm of waves. Tasmania’s energy and people link sits here. A shipping forecast is not a vibe.",
    "Straits are calm because they are narrow. Geography is a shelter.",
    "Name the fetch, the ports, and the infrastructure (Basslink as a political cable). Then a swell that cancels a ferry.",
    "An island state’s freight cost is a strait. That cost is a liveability input."],
  ["vx-g-alpine-snow", "Australia", "Australian snow is a low-latitude, high-country, climate-exposed factory",
    "Short season, hydro catchments, and a tourism that melts. ‘We have Alps’ is a marketing cousin of a small, real cryosphere.",
    "If it is called alpine it is Switzerland. Names are climate.",
    "Map elevation, then a warming trend’s effect on snow-make and frogs. Then fire in the high country as a new neighbour.",
    "A snow-make machine is an adaptation with an energy bill. It is not a glacier."],
  ["vx-g-perth-water", "Australia", "Perth’s water is a drying climate plus a desalination machine",
    "Gnangara mound, dams that sit empty-ish, and plants that eat power. A ‘garden city’ is a political plant list.",
    "Western Australia is dry so they must be used to it. Culture is hydrology.",
    "Track sources (groundwater, dam, desal, reuse). Then a restriction as a social practice.",
    "A sprinkler at noon is a cultural artefact. So is a native garden rebate."],
  ["vx-g-brisbane-flood", "Australia", "A Brisbane flood is a catchment plus a tide plus a memory of 2011 and 2022",
    "Wivenhoe is a dam with a dual job (supply and mitigation) that can be a political object. A river city has a floodplain of suburbs.",
    "If it flooded once it will not again because we remember. Memory is a levee.",
    "Read the catchment, the tide, and the planning overlay. Then insurance as a retreat signal.",
    "A house restumped after 1974 is a document. A new fill pad is another."],
  ["vx-g-indigenous-calendar", "Australia", "Many First Nations seasonal calendars have more than four imported boxes",
    "Six or more seasons in some systems, tied to signs (a flower, a wind, a fat fish). The four-season poster is a colonial import that still runs the bureau’s public face.",
    "Weather is January–December. Nature uses the Gregorian app.",
    "Name a local calendar if you have a licensed source. Then what it changes about ‘when to burn’ or harvest.",
    "A bureau forecast and a seasonal calendar can sit together. Hierarchy is the political bit."],
  ["vx-g-port-hinterland", "Australia", "A port is a node with a hinterland of trucks and a foreland of ships",
    "Fremantle, Botany, Townsville: different cargos. A mine-to-port rail is a private hinterland. The town can be a bystander.",
    "The water is the port. Cranes are decoration.",
    "Map cargo, gauge, and who owns the rail. Then a bottleneck (one bridge, one union dispute, one cyclone).",
    "A coal terminal and a cruise ship can share a harbour and fight for air. That is land-use at sea’s edge."],
  ["vx-g-torres-strait", "Australia", "Torres Strait is a border, a sea Country, and a climate front line",
    "Islands, a treaty with PNG, and king tides that eat cemeteries. It is not ‘Queensland scenery’ as a complete description.",
    "If it is on the map of Australia it is just more reef. Scale is a beach.",
    "Read sea-level stories from the people who live there. Then the legal border as a second layer.",
    "A high-tide in a living room is a geography of vulnerability, not a postcard."],
  ["vx-g-land-clearing", "Australia", "Land clearing is a habitat and carbon decision with a state law map",
    "Qld vs NSW rules, remnant woodland, and a beef or development motive. ‘Unofficial’ clearing still shows in satellite. Extinction is a rate.",
    "If it is private land it is not geography. Fences cancel ecology.",
    "Use a satellite time pair, then the local law, then a species. Then export markets as a distant driver.",
    "A paddock tree in a wheat paddock is a leftover ecology. Counts of them are a landscape metric."],
  ["vx-g-mining-boom-bust", "Australia", "A mining town is a clock that can stop",
    "Housing, FIFO, and a civic that may not outlast the ore. Diversification is a speech. Ghost infrastructure is a landform of capital.",
    "Resources are forever if we are clever. Geology is a business plan.",
    "Name the commodity, the remaining years, and the public assets. Then a bust photo as a source.",
    "A ‘for sale’ row of dongas is a cultural landscape of a bust. So is a still-running school."],
  ["vx-g-urban-sprawl-au", "Australia", "Sprawl is a land-use machine: fringe estates, cars, and a heat sheet",
    "Melbourne and SEQ as textbooks. Infills vs greenfield. A ‘quarter-acre’ is a historical density, not a human right in a statute.",
    "Cities grow out because families need lawns. Biology is zoning.",
    "Measure density, then km to jobs, then bushfire interface. Then water and sewer as a cost.",
    "A new estate named after the woodland it replaced is a toponymy joke. Read the name as a source."],
  ["vx-g-hazard-vuln", "Issues", "Disaster = hazard × vulnerability × exposure, not the wind alone",
    "Same cyclone, different death tolls. Poverty, age, building, warning, racism. A ‘natural disaster’ slogan hides the social half.",
    "If the weather is big the disaster is nature’s fault. Insurance agrees.",
    "Map the physical event, then who was in the way and why they could not leave. Then a mitigation that is political (a levy, a buy-back).",
    "A heatwave kills more in some suburbs because of trees and work, not because the mercury had a favourite postcode."],
  ["vx-g-climate-justice", "Issues", "Who cooked vs who burns is a geography of emissions and harm",
    "Per-capita vs historical totals vs a Pacific island. Australia is a high per-capita cooker with a vulnerable north and a coal export. Justice is a word with numbers.",
    "The weather is fair. Rain falls on all postcodes equally in effect.",
    "Separate responsibility, capability, and vulnerability. Then a policy (loss and damage, a domestic target).",
    "A coal port and a bleaching reef can sit in one national brochure. That tension is the subject."],
  ["vx-g-plastic-gyre", "Issues", "Ocean plastic is a flow with a gyre and a river mouth, not a floating country",
    "Microplastics vs bottles. Fishing gear is a huge share. A beach clean is local; the factory and the catch are upstream.",
    "If we ban straws the gyre empties. Cutlery is the climate.",
    "Name the polymer, the pathway, and the policy (design, waste trade, fishing). Then a wildlife impact as evidence not a mascot only.",
    "Australia’s waste export bans moved the geography of the pile. The pile did not vanish."],
  ["vx-g-overfish", "Issues", "Overfishing is a stock vs a fleet vs a subsidy",
    "Maximum sustainable yield is a model with a political number. Illegal catch is a map of flags of convenience. A no-take zone is a spatial tool.",
    "The ocean is infinite protein. Horizon is a warehouse.",
    "Read a quota, a patrol, and a livelihood. Then climate as a shifter of where the fish are.",
    "A Southern Ocean toothfish is a governance story (CCAMLR) as much as a menu."],
  ["vx-g-sealevel-atoll", "Issues", "Sea-level rise on an atoll is water plus salt in the well plus a legal ‘statehood’ question",
    "Not only a drowning postcard. Freshwater lenses fail first. Migration with dignity is a diplomacy.",
    "Islands will sink so we can ignore them until they do. Timing is a luxury of elsewhere.",
    "Name inundation, groundwater, and a treaty or visa pathway. Then coral growth as a maybe, not a plan.",
    "A cemetery in the tide in the Torres Strait is this issue with an Australian address."],
  ["vx-g-lithium-mine", "Issues", "A ‘green’ mineral pit is still a pit with a water and Country file",
    "Batteries need dirt. Who consents, who gets the job, who gets the tailings. Energy transition is a new extractive map, not a cloud.",
    "If it is for EVs it is not mining. Ethics is the end use.",
    "Map the deposit, the water, and the benefit agreement. Then a recycling hope as a later geography.",
    "An Australian lithium town can boom like an iron town. The clock metaphor still fits."],
  ["vx-g-insurance-retreat", "Issues", "Insurance retreat is a market drawing a new coastline of ‘too dear to live’",
    "Premiums, flood overlays, and a lender who says no. Managed retreat is a planning word for a fight. Not everyone can sell and leave.",
    "If you love the view you accept the risk. Love is a flood policy.",
    "Read a premium map against an overlay. Then who cannot move (renters, aged, Country).",
    "A house that is unsaleable is a stranded asset with a kitchen. That is urban geography."],
  ["vx-g-water-trade", "Issues", "Water trading in the Murray–Darling is a market on a river with a mouth",
    "Licences, carryover, and a town that still needs a tap. Efficiency on-farm can reduce return flows. The river is not a warehouse of identical litres.",
    "If it has a price it is allocated fairly. Markets are rain.",
    "Follow a megalitre from a licence to a crop to the Coorong. Then a buyback as a political tool.",
    "A cotton crop in a dry year is a geography of rules, not only of rainfall."],
  ["vx-g-deforestation", "Issues", "Forest loss is a carbon, water, and people system — and a satellite time series",
    "Amazon headlines vs Australian woodland vs palm oil. Drivers differ (cattle, soy, logs, fire). A ‘tree planting’ ad can ignore old-growth structure.",
    "Trees are trees. A plantation is a forest in the slogan.",
    "Use a definition (primary vs planted), a driver, and a livelihood. Then a certification scheme’s leak.",
    "A fire in a logged coupe is a different fuel story to a fire in a wet gully. Management is geography."],
  ["vx-g-heat-deaths", "Issues", "Heat is a hazard with a body and a suburb of trees",
    "Older people, outdoor workers, blackouts. A hot night is worse than a hot afternoon for some bodies. Night temperatures are a city design.",
    "Heat is uncomfortable, not political. Air-con is a personality.",
    "Map land surface temp, then housing quality, then a cooling centre. Then work rules (when to stop a site).",
    "A November grand final in a warming climate is a cultural geography of risk. Sport is not outside the subject."],
  ["vx-g-border-decision", "Issues", "Borders are drawn decisions; a mountain did not vote",
    "River, 19th parallel, a reef. Passports are young. A chokepoint (a bridge, a tunnel) can be a border in practice without a line on a school atlas.",
    "Borders are natural like mountains. Mountains voted.",
    "Ask who drew it, who crosses it daily, and what cargo is stopped. Then an exclave as a curiosity with lives in it.",
    "The SA–Vic border is a surveyor’s story. The Australia–PNG line in the Strait is a maritime one."],
  ["vx-g-chokepoint", "Issues", "A chokepoint is a narrow power: a strait, a canal, a rail gauge",
    "Hormuz, Malacca, Suez. A ship sits across it and prices move. Australia’s iron ore still sails through someone else’s gate.",
    "The ocean is wide so chokepoints are a myth. Width is freedom.",
    "Name the cargo, the alternative route’s extra days, and who can close it. Then a domestic cousin (a single bridge into a city).",
    "A rail gauge break at a state border was a 19th-century chokepoint. Some still bite."],
  ["vx-g-sustain-three", "Issues", "Sustainable is a three-legged stool that wobbles: environment, economy, social",
    "A mine that funds a school and kills a creek is a wobble. The word on a bottle is not a method. Strong vs weak sustainability is a later argument about substituting capital.",
    "If the logo is green the stool is level. Design is ethics.",
    "Score each leg with evidence. Then who defined ‘we’ in we can keep doing this.",
    "A tourism town that loves the reef and the diesel boat is a wobble you can measure in bleaching and in jobs."],
  ["vx-g-energy-mix-map", "Issues", "An energy mix is a map of fuels, wires, and vetoes",
    "Coal plants, rooftop solar, a stalled transmission line. A target without a wire is a poster. NIMBY vs a fair share of turbines is a political geography.",
    "Electricity is just generated in ‘the grid’ which is a cloud. No map required.",
    "Map generation, then the constraint (coal jobs, a ridge, a blackout). Then a interconnection as a trade.",
    "South Australia’s wind-plus-interconnector story is a state geography. The NEM is a market on a map."],
  ["vx-g-gdp-blunt", "Issues", "GDP is a blunt liveability stick: it counts oil spills as activity if we pay to mop",
    "Unpaid care, Country, and a smash repair can all distort. HDI and a happiness index are other blunt sticks. Use more than one.",
    "If GDP is up the place is better. Growth is a moral.",
    "Pair GDP with a distribution and an environment metric. Then a community’s own measure if they have one.",
    "A mining boom GDP and a closed aged-care bed can share a year. That is the bluntness."],
  ["vx-g-transect", "Fieldwork", "A transect is a line of samples, not a stroll with a clipboard vibe",
    "Equal spacing, a start that is justified, and a record of what you skipped. A beach from dune to swash is a classic. Bias is walking where it is pretty.",
    "Walk until you are tired; that is a sample. Fatigue is a method.",
    "Mark the line on a map first. Then the interval. Then a photo at each point with a scale.",
    "A broken transect because of a fence is data about the fence. Record the break; do not invent the missing points."],
  ["vx-g-sample-size", "Fieldwork", "n is a claim: too small is a story, too biased is a different story",
    "Ten pebbles is not a beach. A random-ish grid beats ‘the nice ones’. Power is a later word; honesty about n is Year 10.",
    "If you counted it is science. One is a census of your mood.",
    "State n, the method of pick, and a limitation in one sentence. Then do not overclaim.",
    "A viral photo of a polluted drain is a sample of one place at one time. Still useful as a prompt, not a mean."],
  ["vx-g-risk-assess", "Fieldwork", "A risk assessment is a method, not a school’s dislike of fun",
    "Tide, sun, traffic, a needle in a dune. Groups, a phone, an adult. Geography kills people who treat the coast as a set.",
    "If it is for school it is safe. Clipboards cancel rips.",
    "Name the hazard, the control, and the abort rule. Then do the abort if the rule trips.",
    "A king tide plus a rock platform is a classic. The data can wait."],
  ["vx-g-field-sketch", "Fieldwork", "A labelled sketch is an argument; a pretty drawing is a hobby",
    "Horizon, a scale, two landforms, a human bit. North arrow. A photo without labels is a memory aid, not the analysis.",
    "Sketching is for art class. Geographers only ping a phone.",
    "Draw less, label more. Then a sentence of process (this dune is moving that way because…).",
    "A sketch that copies the postcard angle copies the postcard’s politics. Move your feet."],
  ["vx-g-survey-vs-talk", "Fieldwork", "A survey is a closed box; an interview is a door — different ethics, different data",
    "n and a Likert vs a 20-minute talk. Leading questions are a trap in both. People are not scenery and not a vending machine for quotes.",
    "Ask until they agree with your hypothesis. That is rapport.",
    "Write the question, pilot it, then consent. Then do not name a shopkeeper in a report if you promised not to.",
    "A clipboard at a station is a sample of who has time at 4 pm. Night-shift nurses are missing."],
  ["vx-g-count-bias", "Fieldwork", "A traffic count at 11 am is not a day",
    "Peak, weekend, weather. A bike counter that misses e-scooters. Your eyes skip the ordinary and grab the red car.",
    "If I stood there it is typical. Presence is a random sample.",
    "State the hour, the weather, and what you could not see. Then a second slot if you can.",
    "A ‘quiet street’ that is a rat-run at 8:10 is a time geography. Your 11 am clipboard lied."],
  ["vx-g-landuse-map", "Fieldwork", "A land-use map is a classification fight in coloured pencils",
    "Residential vs mixed vs ‘other’. A garage as home office. Categories invent the pattern you then ‘find’.",
    "The council colour is the truth. Zoning is the land.",
    "Write a key first. Then walk. Then a photo of the hard cases. Then admit the key’s politics.",
    "A shop that is also a house is mixed. Forcing it into one colour is a choice you should footnote."],
  ["vx-g-photo-ethics", "Fieldwork", "Field photos of people need consent, not a public-street shrug",
    "Consent, children, a ceremony, a house number. Blur is a tool. A wide streetscape can still identify a rare shop.",
    "Public street means public forever. Law is a camera.",
    "Ask, crop, or do not take it. Then storage (a school drive is still a drive).",
    "A fieldwork Flickr dump is a 2010s artefact of a missing ethics form."],
  ["vx-g-repeat-measure", "Fieldwork", "A repeat measure is how you tell weather from a change",
    "One beach profile is a day. Monthly is a story. A storm between visits is a named event, not ‘the beach is like this’.",
    "If it matches the textbook photo once, the process is proven. Textbooks are field.",
    "Same method, same place, dated. Then a difference that exceeds your error.",
    "A dune you measured after a blowout is a different landform. Say so."],
  ["vx-g-control-site", "Fieldwork", "A control site is a comparison, not a ‘clean’ place in a moral sense",
    "Upstream vs downstream, fenced vs grazed. If your control is also treated, you have two treatments and a shrug.",
    "The nice end of the beach is the control because it is nice. Aesthetics is a method.",
    "Match as much as you can (slope, rock) and change one thing. Then admit what you could not match.",
    "A ‘pristine’ control that is a tourist postcard is often a different management, not a time machine."],
  ["vx-g-error-talk", "Fieldwork", "Error is a neighbour of the result, not a confession of failure",
    "A tape that sagged, a GPS that jumped, a count you estimated. Random vs systematic. A neat table with no error line is the suspicious one.",
    "If the number is neat it is true. .00 means love.",
    "Name the biggest error source and which way it probably pushed. Then do not quote three decimal places of a boot-count.",
    "A 4.627 m dune from a 0.5 m pacing error is comedy. Round to the method."],
  ["vx-g-eval-method", "Fieldwork", "Evaluation is what you would change, not ‘it was fun’",
    "Reliability, validity, bias, safety. A better n, a better hour, a permission you lacked. Markers want the adult voice.",
    "Say the method was perfect so the conclusion is safe. Confidence is a rubric.",
    "Pick the weakest link. Propose a fix that is actually cheaper or safer, not a fantasy drone army unless you mean it.",
    "A group that lost the quadrat photos has a storage evaluation. That is still geography of data."],
  ["vx-g-gis-after", "Fieldwork", "A GIS layer after the walk is a second map with a date",
    "Your points plus a flood overlay plus a cadastral guess. Privacy of house points. A screenshot is not an analysis until you ask a question.",
    "If it is in the computer it is GIS and therefore true. Software is a sacrament.",
    "Join your field to one other layer. State both dates. Then a limitation of the join (different scales).",
    "A heat map of ‘where we walked’ is a map of the assignment, not of the suburb. Do not confuse the two."],
  ["vx-g-field-notes", "Fieldwork", "Notes in the wind beat a novel written that night from a vibe",
    "Time, weather, a smell, a number, a doubt. A neat journal that was copied at home is a different source. You will not remember the wind direction.",
    "Memory is a high-resolution sensor. Write later when it is poetic.",
    "Two-line notes at the point. Then a photo of the page as backup. Then do not tidy the doubt out.",
    "A ‘the locals seemed angry’ without a quote or a context is a tourist novel. Get a sentence or drop it."],
  ["vx-g-dew-point", "Earth systems", "Dew point is the temperature where the air’s water gives up",
    "A high dew point is sticky air. Fog when the surface cools to it. Relative humidity is a cousin that depends on the current temperature — 100% at dawn can be a small water content.",
    "Humidity is how wet you feel, so it is the percent on the app, always comparable across days.",
    "Use dew point to compare muggy days. Then fog as a cooling-to-dew-point story.",
    "A 24°C dew point in Darwin is a different body to a 24°C dry heat in the inland. The number is the stickiness."],
  ["vx-g-gravity-model", "People & places", "A gravity model says bigger and closer places interact more — a cartoon of flows",
    "Population product over distance. It fails for a cultural corridor, a cheap flight, a visa wall. Still a first guess for shop catchments.",
    "People always go to the biggest city. Distance died.",
    "Use it as a baseline, then name the barrier that broke it (a river with no bridge, a language, a fare).",
    "Adelaide–Melbourne is not a simple gravity with Perth. The Bight is a distance with a desert personality."],
  ["vx-g-great-div-weather", "Australia", "The Divide is a weather machine and a river director, not only a hiking brand",
    "Short steep rivers east, long inland systems west. Orographic lift on easterlies. A gap is a pass and a climate leak.",
    "The Divide is a line on a tourist map. Rain cannot read.",
    "Stand a town pair either side and compare rainfall and river direction. Then a gap (Hunter) as a leak.",
    "A ‘west of the Divide’ frost is a winter story the coast does not owe you. Elevation plus continentality."],
  ["vx-g-waste-flow", "Issues", "A yellow lid is not a closed loop",
    "A kerbside yellow lid is not a closed loop. Contamination is a geography of behaviour plus a MRF. Someone’s backyard is the sink.",
    "If I put it in the right bin it is gone. Bins are a magic.",
    "Follow one object from shop to sink. Then a policy (export ban, container deposit) as a reroute.",
    "A container deposit in NSW rerouted cans. The leftover plastic film is still a sink problem."],
  ["vx-g-quadrat-limit", "Fieldwork", "A quadrat has an edge rule and a toe bias",
    "Too small misses the rare. Too few and you sampled a patch. Tossing ‘randomly’ at your feet is a toe bias.",
    "If it is a square it is objective. Geometry is a method.",
    "Fix size to the organism, randomise the placement for real, and count the edge rule (in if it touches the top).",
    "A 1 m quadrat on trees is a joke. A 1 m on clover can work. Match the life."],
  ["vx-g-people-not-view", "Fieldwork", "People are not scenery in a coastal photo",
    "A fisher is a livelihood. A houseless camp is a housing policy. Asking without consent is a harm. ‘Colour’ in a sketch can be a slur in a pencil.",
    "If they are in public they are data. Public is a licence to publish.",
    "Ask, anonymise, or leave them out. Then write the process (fishing, commuting) not the body as a type.",
    "A ‘typical local’ caption is a stereotype with a clipboard. Get a name or do not typecast."],
]);
