import { pack } from "../pack.mjs";

export const HEALTH_VOLUME = pack("health", [
  ["vx-w-vo2-not-moral", "Body", "VO₂ max is a capacity, not a moral score",
    "How much oxygen you can use in hard work. Genetics, training, altitude. A class ranking of it is PE cosplay, not a character test.",
    "The highest VO₂ wins as a person. Labs are a personality.",
    "Treat it as one fitness component. Then a test protocol that is actually the protocol. Then do not shame a body that is ill or new.",
    "A rowing machine estimate is not a lab cart. Say ‘estimate’."],
  ["vx-w-blood-pressure", "Body", "Blood pressure is two numbers: squeeze and rest of the artery",
    "Systolic / diastolic. A one-off high at the dentist is a white-coat story. Hypertension is a pattern plus a clinician, not a PE lesson diagnosis.",
    "If you feel fine the numbers cannot matter. Feelings are a cuff.",
    "Sit, cuff on, two readings if you are in a program that says so. Then a GP if the program says so. Then do not tweet a diagnosis.",
    "Salt, meds, and a family story can sit behind a number. School does not adjust your meds."],
  ["vx-w-core-not-abs", "Body", "Core is a cylinder of control, not a six-pack photo",
    "Breath, pelvic floor, deep abdominals, back. A crunch that yanks the neck is a circus. Bracing for a lift is a skill.",
    "If you can see abs you have a core. Visibility is function.",
    "Train anti-extension/rotation with a coach-ish cue. Then a dead bug that is boring and useful. Then do not add 200 sit-ups as a punishment.",
    "A sore back after ‘core day’ is a technique ticket. Pain is data, not a badge."],
  ["vx-w-posture-trade", "Body", "Posture is a trade of tasks, not a Victorian moral",
    "The best posture is the next one. Sitting all day plus a ‘sit up straight’ yell is not a physio. Load variety beats a statue.",
    "If you slouch you are lazy. Spine is a character.",
    "Change positions, screen height, a walk. Then a bag that is not a one-shoulder boulder. Then a clinician if pain persists.",
    "A 6 kg backpack on one Year 8 is a physics problem. Two straps, both used."],
  ["vx-w-rpe", "Body", "RPE is a 1–10 of how hard it felt, a useful lie-detector on gadgets",
    "Talk test: can you sentence. A watch that says 150 bpm while you can still gossip is a watch. Illness and heat change RPE.",
    "The watch is truth. Bodies are decorative.",
    "Use RPE plus a plan (easy / hard). Then a deload if RPE is always 9. Then do not race a classmate’s watch.",
    "A 7/10 that is actually a 9 because you slept 4 hours is still a 9. Sleep is a load."],
  ["vx-w-do-ms", "Body", "DOMS is delayed muscle soreness, not proof the session was elite",
    "24–72 h, micro-damage plus inflammation as a cartoon. New movements DOMS more. Stretching it away is a limited tool. Load management is the adult.",
    "If it does not hurt it did not work. Pain is hypertrophy.",
    "Progress load slowly. Then distinguish DOMS from a sharp injury. Then do not add a punishment session on sore quads.",
    "A first hill walk in Term 1 is a DOMS factory. Term 3 on the same hill is less. That is adaptation."],
  ["vx-w-flexibility-skill", "Body", "Flexibility is a range you can control, not a circus split photo",
    "Mobility + stability. Stretching a cold muscle as a warm-up is a old habit. Strength at end range is often the missing bit.",
    "The most flexible person is the healthiest. Gumby is a KPI.",
    "Warm, then a stretch with a purpose (a sport position). Then stop bouncing ballistic as a dare.",
    "Hypermobile is not ‘lucky’. It can need strength more than extra stretch. A physio sentence, not a TikTok."],
  ["vx-w-immune-sleep", "Body", "Sleep is immune and mood hardware, not a lazy optional",
    "Less sleep, more bugs and a shorter fuse in the cartoon of the evidence. Adolescents often need more than they get. A 5 am training that destroys Monday is a trade.",
    "You can catch up on Saturday for a week of 4-hour nights. Banks work that way.",
    "Protect a window. Then a consistent get-up. Then do not brag about 4 hours as a grind.",
    "A phone in bed is a light and a stimulus. Both fight sleep. One extra hour of sleep can beat an extra set."],
  ["vx-w-circadian-teen", "Body", "A teenage clock often runs late; a 8:30 start is a policy on biology",
    "Melatonin later, a social jetlag on Monday. Light in the morning helps. Not a moral of ‘they should try harder to be 1990’.",
    "Teens stay up because they are undisciplined. Clocks are parenting.",
    "Morning light, dim evenings, a consistent wake. Then a school that cannot move start times still can drop a 11 pm assignment pile.",
    "A 2 am gaming raid plus a 7 am bus is a jetlag you chose. The clock still exists."],
  ["vx-w-hydration-wee", "Body", "Thirst is late; wee colour is a crude dashboard, not a lab",
    "Pale straw vs apple juice. A once-dark after beetroot is a food, not a kidney TikTok. Heat and altitude change the need. Over-water is a rare sport story (hyponatraemia) — do not medicalise a PE lesson.",
    "If you drink 4 L you are healthier. Volume is virtue.",
    "Sip around activity, more in heat, check colour as a crude. Then a teacher if a student is dizzy. Then do not force a chug contest.",
    "A 40°C oval in November is a medical plan, not a ‘toughen up’."],
  ["vx-w-uv-invoice", "Body", "UV is a delayed invoice: burn now, risk later",
    "Slip slop slap slide seek as a system. Cloud still transmits. A tan is injury, not a nutrient. Vitamin D is a different, real ticket — not a licence to fry.",
    "If it is cloudy you cannot burn. Clouds are sunscreen.",
    "Sleeve, SPF, hat, shade, glasses. Then a time around noon that is shorter. Then a mole that changes is a GP, not a PE theory.",
    "A cricket day in January is an occupational UV for the umpire too. Roles need shade."],
  ["vx-w-teeth-biofilm", "Body", "Teeth are a biofilm plus sugar time, not a brushing personality",
    "Plaque is a community. Frequency of sugar beats a single ‘healthy’ lolly if it sits. Fluoride is a public-health cousin. Floss is the side they do not see.",
    "If they look white they are fine. Colour is enamel.",
    "Twice a day, fluoride, less grazing sugar. Then a dentist, not a charcoal powder as a religion.",
    "A sports drink at every training is a sugar-time story. Water in the bottle is a dental policy."],
  ["vx-w-vaccine-herd", "Body", "A vaccine is personal training plus a herd maths",
    "Memory cells, a coverage percent, people who cannot vax. A rumour mill is not a journal. School requirements are a policy, not a biology exam you can ‘win’.",
    "If I am fit I cannot carry a bug. Fitness is a steriliser.",
    "Use the official schedule. Then a GP for personal history. Then do not harass a classmate about a status you do not know.",
    "Coverage is a geography. A low-vax pocket is a outbreak map waiting."],
  ["vx-w-antibiotic-steward", "Body", "Antibiotics are for bacteria, with a leftover that trains resistance",
    "Finish as advised. Viral colds laugh. Sharing leftover pills is a lottery. Stewardship is a civic of medicine.",
    "Stronger is better so take two. Strength is a dose.",
    "GP, the right drug, the right days. Then do not save ‘a few’ for next time as a kit.",
    "A sore throat that is strep is a different ticket to a viral one. Tests exist. TikTok does not."],
  ["vx-w-puberty-range", "Body", "Puberty is a hormonal timetable with a wide on-time window",
    "Tanner stages as a clinician tool, not a class ranking. Early/late is often still normal. A worry is a GP, not a forum.",
    "If they have not finished by 14 they are broken. Calendars are medicine.",
    "Teach the range, the respect, the private. Then a trusted adult. Then do not comment on a classmate’s body as a joke.",
    "A growth plate is why kids are not small adults in the gym. Load is a age story."],
  ["vx-w-concussion-chem", "Body", "Concussion is a chemical chaos, not only a knockout photo",
    "You can walk and still be concussed. Second hit in the window is the nightmare. Return-to-play is a protocol, not a coach’s vibe.",
    "If they did not black out they are fine. Consciousness is a scan.",
    "Remove, recognise, refer. Then a gradual return. Then do not ‘shake it off’ as a brand.",
    "A header, a tackle, a fall from a bike. Same brain. Rugby is not the only file."],
  ["vx-w-feeling-info", "Mind", "A mood is a weather report, not a verdict on your worth",
    "Anxiety can be a false alarm or a true one. Naming it (affect labelling) can turn the volume down a notch. It is not a personality tattoo.",
    "If you feel it it is the truth about you forever. Moods are identity.",
    "Name it, locate it in the body, then a next action (walk, a person, a task). Then professional help if it owns the week.",
    "A 988-shaped resource is for crisis in some countries; in Australia a Kids Helpline / Lifeline is the usual pointer. Do not invent a method of harm."],
  ["vx-w-stress-dose", "Mind", "Stress is a dose: too little is fog, too much is a crash",
    "Yerkes-Dodson as a cartoon. Exam arousal can help then smash sleep. Chronic is a different animal to a 400 m start.",
    "All stress is bad. Calm is the only healthy. Or: all stress is good because grind.",
    "Match the dose to the task. Then a recovery. Then cut a chronic pile (job plus care plus feed) with a person, not a slogan.",
    "A ‘I work well to deadline’ can be a adrenaline habit that wrecks the next day. Deadlines are a design."],
  ["vx-w-phone-bed", "Mind", "A phone in bed is a stimulus machine plus a blue-ish light",
    "Notifications are other people’s priorities. A charger across the room is a cheap control. FOMO is a designed loop.",
    "If I am tired I will sleep anyway. Tiredness cancels silicon.",
    "Park the phone, a book, a consistent wind-down. Then do-not-disturb as a default. Then a real alarm clock if you must.",
    "A group chat that pings at 12:40 is a social jetlag. Mute is a civic of the thread."],
  ["vx-w-feed-not-body", "Mind", "A feed is not a body; a filter is not food",
    "Compare-and-despair is a product. Bodies in sport and dance are a selected sample. A ‘what I eat in a day’ is often a job.",
    "If they posted it, it is the average Tuesday. Posts are a census.",
    "Limit the compare accounts, follow a range, then a real meal with a real person. Then help if the mirror is a war.",
    "A school change-room comment can outrun a feed. Language is a climate."],
  ["vx-w-help-skill", "Mind", "Help-seeking is a skill: who, when, what to say",
    "A trusted adult, a GP, a headspace, a line. Rehearsing the sentence helps. Friends can listen and still not be clinicians.",
    "If you were strong you would not ask. Strength is silence.",
    "Pick one person, one sentence of the problem, one ask (listen vs appointment). Then a backup if they freeze.",
    "A ‘I need to see the counsellor’ note is a valid PE/health move. Gatekeeping it as weakness is a culture bug."],
  ["vx-w-bully-power", "Mind", "Bullying is repeated harm with a power tilt, not a one-off clash",
    "Intent, repetition, a power gap. Online is a 24 h campus. A ‘both sides’ that ignores the tilt is a miss. Bystanders are a climate.",
    "Kids will be kids. Nature is a hierarchy.",
    "Name it, record it, use the school process. Then do not tell the target to ‘just ignore’ as a complete plan. Then a check on the group chat.",
    "A ‘joke’ that only one person can stop is a power. Laughter in the circle is not a defence."],
  ["vx-w-consent-ongoing", "Mind", "Consent is ongoing and can be withdrawn, including a laugh that was not a yes",
    "Free, informed, enthusiastic, specific. A past yes is not a forever. Alcohol is a fog. School policy and the law have ages — this is not a how-to.",
    "If they did not say no it was yes. Silence is a contract.",
    "Ask, listen, stop. Then a culture that makes stop cheap. Then an adult if a line was crossed.",
    "A photo that was ok at the party can be a no tomorrow. Sharing it is a second act."],
  ["vx-w-addiction-learn", "Mind", "A hijacked loop is a learning story, not a cartoon villain only",
    "Reward prediction, a cue, a shrinking other life. Substances and some apps share loops; they are not the same legal or medical object. Recovery is a practice.",
    "If they wanted to stop they would. Will is a cure.",
    "Reduce cues, a person, a professional path. Then do not shame a relapse as a character. Then a school that can still be a stable bit.",
    "A vape that is ‘just flavour’ is still a nicotine delivery. Marketing is a loop designer."],
  ["vx-w-rumination", "Mind", "Rumination is a loop of the same movie, not a problem-solving session",
    "Past tense, no new plan. A walk or a written ‘then I will…’ can break it. Night rumination loves a phone.",
    "Thinking hard is always useful. Loops are depth.",
    "Notice the rerun, park a 10-minute worry slot, then a body task. Then help if it owns sleep.",
    "A ‘why am I like this’ at 1 am is rarely a lab. Morning is a better lab."],
  ["vx-w-self-talk", "Mind", "Self-talk is a coach in your skull: useful specific vs a slur at yourself",
    "‘You always ruin it’ is a cognitive cartoon. A ‘next serve, bounce, toss’ is a cue. Sport psych is a toolkit, not a personality transplant.",
    "Positive vibes only. Any critique is toxic. Or: elite people hate themselves into excellence.",
    "Swap a global slur for a next-action cue. Then a evidence check (always? really?). Then a person if the slur is winning.",
    "A missed penalty is a skill moment. A ‘I am garbage’ is a identity moment. Different repairs."],
  ["vx-w-social-jetlag", "Mind", "Social jetlag is a weekend clock vs a Monday clock",
    "Shift of several hours is a mini jetlag. Consistency beats a heroic lie-in that smashes Monday. Shift workers have a harder, real version.",
    "Sleeping 12 hours on Sunday fixes the week. Banks again.",
    "Keep wake time nearer. Then a Saturday that is not a 4 am. Then a nap as a tool not a third night.",
    "A 16th with a job plus sport plus a feed will try to steal the clock. The clock still bills Monday."],
  ["vx-w-grief-not-linear", "Mind", "Grief is not a five-stage exam you pass",
    "Kübler-Ross was a model, not a timetable. People bounce. Anniversaries. A school that allows a wobble is a health system.",
    "If they still cry at month 4 they are doing it wrong. Calendars are grief.",
    "Presence, not a slogan. Then a service if it is stuck. Then do not rank whose loss counts.",
    "A pet, a parent, a country you left. Different, all real. Do not ‘at least’."],
  ["vx-w-attention-train", "Mind", "Attention is a muscle with a environment: notifications are a gym thief",
    "Deep work cartoons, a 25-minute block, a single tab. ADHD is a clinical story, not a vibe of ‘I like phones’. Do not diagnose a classmate.",
    "If you cared you would focus. Care is a neurotransmitter.",
    "Change the environment first (phone out). Then a block. Then a professional path if school is a wall.",
    "A open laptop with 12 tabs in a exam review is a design. Full screen is a control."],
  ["vx-w-body-image-sport", "Mind", "A sport’s ‘look’ can be a health risk dressed as performance",
    "Weight-class, aesthetic sports, a comment from a coach. Energy availability (RED-S) is a medical file. Thin is not a time.",
    "Lighter is always faster. Mass is a enemy.",
    "Fuel the work, a coach who does not comment bodies, a GP if periods/injury pile. Then a culture that claps fuel.",
    "A rowing eight that skips lunch is a performance bug. The boat does not vote."],
  ["vx-w-loneliness", "Mind", "Loneliness is a health risk, not a personality fail of ‘being boring’",
    "Quantity of people vs quality. A crowded feed can be lonely. Clubs, a shift, a library as a third place.",
    "If you had more followers you would not be lonely. Counts are a cure.",
    "One repeating in-person, a low-stakes club, then a service if it is a pit. Then do not force ‘just go out’ as a complete plan for social anxiety.",
    "A new school in Term 1 is a loneliness factory. Buddies are a WHS of belonging."],
  ["vx-w-fibre-not-punish", "Food", "Fibre is a plant structure your microbes eat, not a punishment cereal",
    "Vegetables, legumes, whole grains. Rapid jumps can bloat. A powder is a supplement hat, not a vegetable.",
    "If it tastes like cardboard it is working. Virtue is texture.",
    "Add, do not only subtract. Then water, because fibre without water is a traffic jam. Then a dietitian if a gut disease is in the room.",
    "A white-bread lunch every day is a fibre story. A bean chilli is a different story. Both can exist in a canteen."],
  ["vx-w-salt-hidden", "Food", "Salt is a hidden default: bread, sauces, a wrap",
    "Sodium vs salt (a conversion). Blood pressure as a population story. Athletes in heat are a different sweat ticket — do not copy a marathon ad in Year 8 PE.",
    "If I do not add the shaker I have no salt. Shakers are the food supply.",
    "Read per 100 g, then sauces as a lever. Then a GP if you are told to restrict. Then do not panic a single chip night.",
    "A ‘low fat’ product that is a salt bomb is a swap trap. Fat was never the only dial."],
  ["vx-w-sugar-time", "Food", "How often sugar hits the teeth and the insulin story beats a one-day saint",
    "Grazing a sports drink vs a meal with dessert. Fruit in a skin is not a can. ‘Natural sugar’ is still sugar with a fibre maybe.",
    "If it is honey it does not count. Bees are a health claim.",
    "Park sweet with meals more than as a all-day sip. Then water as the default bottle. Then a dentist.",
    "A canteen ‘fruit’ juice that is 250 mL of apple is a sugar-time. Eat the apple."],
  ["vx-w-protein-spread", "Food", "Protein is amino acids; spreading it across the day beats a 2 am shake religion",
    "Needs scale with size and some training. Food first. A supplement is a convenience with a purity and a school-sport ban list (informed sport).",
    "More protein is always more muscle. Powder is a law.",
    "A protein at each meal from food. Then a need that is not a bodybuilder ad. Then a banned-list check if you compete.",
    "A 15-year-old copying a 90 kg influencer’s 200 g/day is a expensive wee. Size is a dose."],
  ["vx-w-fat-kinds", "Food", "Fats are not a single villain; trans industrial is the usual punchable one",
    "Unsaturated, saturated as a population dial, trans from some processing. Fried food is a pattern. Your body needs some fat to absorb some vitamins.",
    "Fat makes you fat as a 1:1. Words are biochemistry.",
    "Cook with a unsaturated default, then a pattern not a single fry. Then a clinician for a cholesterol file — not a PE guess.",
    "A ‘low fat’ muffin can be a refined-starch delivery. The muffin is a pattern, not a morality."],
  ["vx-w-ultra-process", "Food", "Ultra-processed is a NOVA-ish pattern, not ‘anything in a packet’",
    "A frozen pea is processed and still a pea. A packaged snack engineered for a Bliss Point is a different object. The evidence is population-level; it is not a purity cult.",
    "If it has a wrapper it is poison. Wrappers are a toxin.",
    "Cook when you can, then a packet that is beans on toast without shame. Then read the pattern of the week.",
    "A hiking bar is ultra and useful. A Tuesday of only bars is a pattern. Context."],
  ["vx-w-allergy-not-pref", "Food", "An allergy is an immune event; a preference is a like; coeliac is an autoimmune of gluten",
    "Traces, a EpiPen as a prescribed device, a kitchen that does not shrug. ‘A little bit will be fine’ is how people get hurt. Intolerance is another file (dose, misery, not always anaphylaxis).",
    "Allergy is a fussiness. Fuss is a character.",
    "Read the plan, do not share food, then a first-aid that is their plan. Then do not test them as a joke.",
    "A canteen with a ‘may contain’ is a risk statement. Risk is not a dare."],
  ["vx-w-bacteria-time", "Food", "Bacteria like warmth, time, and a protein picnic",
    "2-hour/4-hour as a food-safety cartoon in Australia (the zone). Reheat leftovers once as a habit. A cracked egg on a benchtop is a clock.",
    "If it smells fine it is fine. Noses are a lab.",
    "Fridge, a lid, a clock. Then a cooler for the oval. Then do not thaw on the dash in January.",
    "A sausage sizzle without a thermometer is a civic of hope. 75 °C in the middle is a number."],
  ["vx-w-caffeine-half", "Food", "Caffeine is a drug with a half-life that can sit in a 10 pm brain",
    "Adenosine blockade as a cartoon. A teen, a energy drink, a heart that races. Sleep is the invoice. Pregnancy and some meds are clinician territory.",
    "Caffeine is not a drug because it is in tea. Plants are innocent.",
    "Count mg if you use it, park it after mid-arvo, then do not stack four cans as a study plan.",
    "A ‘natural guarana’ is still caffeine. Marketing is a leaf."],
  ["vx-w-alcohol-depress", "Food", "Alcohol is a depressant that lies about being a stimulant at the start",
    "GABA, a disinhibition, a sleep that is junk. Standard drinks. School-age brains are a development story. This is not a pour guide.",
    "If you can still talk you are fine to drive. Speech is a BAC.",
    "Know a standard drink as a civic, then a plan that is not a dare. Then adult help if use owns the week. Then do not mix with a unknown pill as a party trick.",
    "A ‘sober curious’ month is a experiment some adults use. Teens have a simpler legal line."],
  ["vx-w-per100g", "Food", "Per 100 g is how you compare; per serve is how they hide a tiny serve",
    "A ‘lite’ that is 30 g serve vs a 100 g of the rival. kJ vs Cal (×4.2-ish). A health star is a algorithm with politics.",
    "The front of pack is the nutrition. Claims are a lab.",
    "Turn over, per 100 g, then a ingredient list that is a order of mass. Then a serve-size laugh test.",
    "A muesli bar that is a lolly with oats still reads as a lolly on per 100 g sugar. Oats are a costume."],
  ["vx-w-fad-before", "Food", "A fad is a story with a before photo and a enemy food",
    "Demonise a nutrient, sell a book. Rapid loss is often water and glycogen. A diet that bans a food group needs a dietitian, not a forum.",
    "If it worked for that influencer it is a protocol. N=1 is a trial.",
    "Ask the mechanism, the evidence, the leftover food pattern. Then a slow habit. Then a clinician for a eating-disorder smell.",
    "A ‘no carbs after 6’ is a clock, not a biochemistry. Clocks can still help some people as a practical — say practical, not law."],
  ["vx-w-culture-food", "Food", "A food culture is a health and a identity, not a ‘should eat quinoa’ lecture",
    "Share plates, a fasting month, a hunting practice. Nutrient advice that erases a culture is a colonial leftover. Harm reduction still exists (a safer cook, a iodine).",
    "Healthy is a supermarket of the global north. Other kitchens are a fail.",
    "Start with the pattern they already cook. Then a small lever. Then respect a feast day as a feast.",
    "A school nutrition unit that only uses a Mediterranean poster in a Pacific classroom is a miss. Plates differ."],
  ["vx-w-energy-in-out", "Food", "Energy in vs out is a cartoon that hides hormones, sleep, and a scale obsession",
    "kJ matter in a physics sense. Bodies defend a range. A PE ‘just eat less’ at a growing teen is a harm. Growth is a output.",
    "Calories are a moral. Burn them as a punishment.",
    "Fuel the day, especially if you train and grow. Then a GP if weight is the war. Then do not weigh a class as a sport.",
    "A ‘calories in calories out’ poster next to a eating-disorder assembly is a mixed message. Mixed messages land."],
  ["vx-w-supplements-food", "Food", "A supplement is a extra, with a purity and a interaction",
    "Food first. Some (vitamin D in a low-sun story, iron with a diagnosis) are medical. A fat-burner is a marketing. Sport bans exist.",
    "If it is in a health shop it is safe and useful. Shops are a TGA.",
    "Name a deficiency with a test, then a product with a batch, then a pharmacist. Then do not stack six powders as a personality.",
    "A creatine that is a well-studied powder is still not a Year 8 need. Age is a context."],
  ["vx-w-warmup-rehearse", "Movement", "A warm-up is a dress rehearsal of the skill, not a random jog plus a bounce stretch",
    "Pulse, then the movement pattern, then a build. RAMP as a coach acronym. A static split before a sprint is a old poster.",
    "If you sweat the warm-up worked. Sweat is readiness.",
    "Copy the sport in slow-mo, then faster. Then a time cap so it does not eat the lesson. Then skip the 20-minute stretch circle as a religion.",
    "A 100 m that starts from cold in July is a calf ticket. July is a warm-up month."],
  ["vx-w-overload", "Movement", "Progressive overload is a little more, not a hero day then a sofa week",
    "Load, reps, density, skill complexity. Deloads. A teenager copying a 1RM challenge from a feed is a growth-plate story.",
    "Soreness is the program. If you can walk it was too light.",
    "Add a small bit when the current bit is clean. Then a note. Then a coach for bars on a back.",
    "A push-up that is a worming hip is not a extra rep. Quality is a load."],
  ["vx-w-skill-reps", "Movement", "A skill wants reps with attention, not a 400-rep slop",
    "Blocked vs random practice as a coaching fight. Feedback that is a cue, not a novel. Fatigue ruins the pattern you meant to groove.",
    "More reps are more skill. Volume is motor learning.",
    "Short, sharp, a target (a cone, a time). Then a rest. Then a random-ish mix when the pattern exists.",
    "A hockey hit that is 3 good and 40 sloppy is 40 sloppy in the nervous system. Stop sooner."],
  ["vx-w-rules-game", "Movement", "Rules are the game; modified rules are still a game with a different skill",
    "A smaller field, a softer ball, a no-contact. Inclusion is a design. ‘Real sport’ as a gate is a culture.",
    "If it is not the adult rulebook it is not sport. FIFA is a biology.",
    "Pick the constraint that teaches the thing (space, time, contact). Then play. Then a reflection that is not only the score.",
    "A 4v4 on a half court can teach more decisions than a 15-a-side park. Density of decisions is a pedagogy."],
  ["vx-w-fitness-components", "Movement", "Fitness has components that do not trade 1:1: strength is not a 5 km",
    "Aerobic, strength, power, agility, mobility, a skill. A beep-test religion misses a thrower. Programs should say which component.",
    "Fit is a look. Looks are VO₂.",
    "Name the component the lesson is for. Then a test that matches. Then do not rank a class on one test as a human ranking.",
    "A gymnast and a distance runner can both be ‘fit’ and fail each other’s test. That is the point."],
  ["vx-w-recovery", "Movement", "After a session you are a repair job: sleep, food, a easy day",
    "Protein-ish meal, a sleep, a not-another-max. Ice baths as a maybe for some goals and a hype for others. Rest is a training block.",
    "If you are not training you are getting worse every hour. Rest is decay.",
    "Plan the easy day as a day. Then a meal you will actually eat. Then a injury that is a rest not a extra stretch.",
    "Two-a-days in a school week plus a job is a overreach factory. The factory bills the hamstring."],
  ["vx-w-technique-load", "Movement", "Technique is a load limit; a heavy slop is a different exercise",
    "A squat that is a good-morning is not a squat. Ego load is a Instagram. Spotters and pins are a WHS.",
    "Weight on the bar is the only KPI. Plates are a method.",
    "Film a side view, cut the load, then add when the pattern holds. Then a coach for Olympic lifts.",
    "A school weights room without a induction is a incident waiting. Induction is a warm-up of the brain."],
  ["vx-w-fartlek-interval", "Movement", "Intervals are a designed yes/no; fartlek is a play of speeds",
    "Work:rest is a number. A beep is a protocol. Playing with speeds on a trail is a valid aerobic. Mixing them without a plan is a shrug.",
    "If it hurts more it is a better interval. Pain is a protocol.",
    "Write the work, the rest, the reps. Then a easy week. Then do not ‘just go hard’ as a complete aerobic plan.",
    "A 30:30 on a oval in heat needs a shorter set. Heat is a interval variable."],
  ["vx-w-left-right", "Movement", "Asymmetry is normal; a huge gap plus pain is a ticket",
    "Hands, a kick, a scoliosis maybe. Forcing a ‘even’ can be a aesthetic, not a performance. A physio for a gap that is a limp.",
    "You must be even or you will snap. Symmetry is a law of bone.",
    "Train the sport, then a extra on the weak if a coach said so. Then do not invent a 50/50 religion from a post.",
    "A cricket fast bowler is a asymmetry job. The job is the program."],
  ["vx-w-play-vs-train", "Movement", "Play is a variability that training can forget",
    "Pickup, a different surface, a laugh. Specialise-early is a burnout and a overuse factory in some sports. Sampling is a development cartoon with evidence fights.",
    "If it is not in the program it is wasted. Play is a leak.",
    "Keep a play slot. Then a late specialise in many sports. Then a fun that is still a pulse.",
    "A kid in four organised sessions and no backyard is a calendar, not a childhood. Calendars injure."],
  ["vx-w-ada-first", "Safety", "DRSABCD is an order, not a slogan you shout as a pile",
    "Danger, response, send, airway, breathing, CPR, defibrillation as the usual Australian first-aid spine. You update on a course. This is not a full course.",
    "If you remember CPR you can skip danger. Heroes skip look.",
    "Look for danger, then the rest in order. Then a real course. Then an AED that is actually on the wall you know.",
    "A oval with a AED in a locked staff room is a geography of a fail. Keys are a minute."],
  ["vx-w-bleed-pressure", "Safety", "Severe bleed is pressure and a pack, not a tourniquet cosplay as a first reflex",
    "Courses teach a sequence. Tourniquets have a place and a training. Elevation as-taught, not as a TikTok. Gloves if you have them.",
    "A belt as a tourniquet is always the move because movies. Movies are a protocol.",
    "Do the course. Then pressure. Then triple-zero. Then do not practise a tourniquet on a classmate as a dare.",
    "A school first-aid kit that is a empty biscuit tin is a WHS. Stock is a drill."],
  ["vx-w-burn-water", "Safety", "Cool running water, about 20 minutes, not butter, not ice as a burn-into-the-skin",
    "Remove jewellery, cool, cover as taught, then a hospital threshold (size, face, chemical, electric). Butter is a folklore insulator.",
    "Ice is colder so it is better. Colder is kinder.",
    "Water, time, then a dressing that is not fluffy cotton as a souvenir in the wound. Then a course update.",
    "A camp stove in a wind is a burn factory. Wind is a control."],
  ["vx-w-choke-cough", "Safety", "A choke that can cough is a cough; a silent choke is a emergency sequence from a course",
    "Back blows / thrusts as currently taught — you update. Do not invent a upside-down shake of a child from a memory of 1998.",
    "Hit them on the back as hard as cinema. Cinema is a guideline.",
    "If they can cough, they cough. If they cannot, the trained sequence and a call. Then a course. Then do not practise on a person who is eating as a joke.",
    "A grape, a hot dog, a laugh while eating. Supervision of little kids is a food-safety."],
  ["vx-w-water-stronger", "Safety", "The water is stronger than your mood: rips, a flood, a rock platform",
    "Swim between the flags as a system, not a vibe. A rip is a river in the sea — you do not muscle it as a personality. Floodwater is a soup of unknown.",
    "If you can swim 50 m in a pool you can swim a rip. Pools are oceans.",
    "Flags, a float, a never dive in unknown. Then a flood that you do not drive. Then a rock platform that is a wave magnet.",
    "A king tide plus a camera at the edge is a classic. The photo is not a float."],
  ["vx-w-phone-wheel", "Safety", "A phone is a steering-wheel thief; a second is a miss",
    "Even a glance is a swerve. Hands-free is still a brain-free-ish. A pedestrian in a feed is a car’s problem and their own.",
    "I can multitask because I am good. Skill is a exemption.",
    "Phone in the bag, drive, then a pedestrian who looks up. Then a law that already exists — this is not a dare to test it.",
    "A school kiss-and-go with a parent on a call is a WHS of the gate. Gates have children."],
  ["vx-w-heat-emergency", "Safety", "Heat illness is a medical emergency waiting in a November carnival",
    "Cramps to exhaustion to stroke as a cartoon of severity. Stop, shade, cool, a call at the serious end. ‘Push through’ is a how-to for a disaster.",
    "Sweat means they are fine. Sweat is a all-clear.",
    "Schedule, shade, water, a stop. Then a wet towel. Then do not wrap in space blankets as a heat plan.",
    "A black jumper on a synthetic oval at 2 pm is a radiative oven. Uniform is a control."],
  ["vx-w-cold-judgement", "Safety", "Cold steals judgement first, then fingers, then a hero plan",
    "Hypothermia is a quiet. Wet plus wind is a multiplier. A ‘I will just quickly’ on a alpine is a last sentence. Layers, a group, a turnaround time.",
    "If you are shivering you are fine because shivering is heat. Shivers are a all-clear.",
    "Plan the turnaround, stay dry-ish, then a huddle. Then a call. Then do not split the group to ‘go get help’ as a first reflex without a plan.",
    "A school camp in the high country is a weather file. The file includes a no-go."],
  ["vx-w-asthma-plan", "Safety", "An asthma action plan is a document, not a rumour in the staffroom",
    "Reliever, a spacer, a 4×4 or whatever the current plan says — you follow THEIR plan. A reliever is not a fitness lolly. Smoke and sport are triggers for some.",
    "If they have an inhaler they should ‘just run it off’. Running is a treatment.",
    "The plan, the spacer, the call if it is the red zone. Then a spare in the sport bag. Then do not share puffers as a friendship.",
    "A bushfire haze day is a PE modification. Haze is a timetable."],
  ["vx-w-anaphylaxis", "Safety", "Anaphylaxis is a time emergency with a prescribed autoinjector",
    "Train, know where the device is, call. A ‘maybe they will be fine’ wait is the fail. Traces. A second device. This is not a DIY medical.",
    "Antihistamine first always, because it is a allergy. Tablets are a adrenaline.",
    "Their device, their plan, a 000. Then a course. Then a canteen that does not shrug.",
    "A camp kitchen that ‘mostly’ avoids peanuts is a risk statement. Mostly is a dose."],
  ["vx-w-blood-sport", "Safety", "Blood in sport is a supply-chain of other people’s viruses plus a dignity",
    "Stop, gloves, a out until the bleed is managed as the code says. A ‘warrior’ that plays on is a teammate risk. HIV/hep fear has a history of stigma — treat blood as blood, not as a moral of a group.",
    "If they are a teammate they cannot have a virus. Friendship is a sterile field.",
    "The blood rule, gloves, a bin. Then a sub. Then do not joke a player as a contamination.",
    "A boxing cut is a protocol. So is a netball nose. Codes exist because of this."],
  ["vx-w-medicine-name", "Safety", "A medicine is a dose and a name, not a ‘white pill from mum’s drawer’",
    "Same-looking pills. A sharing is a poison and a sports-ban. Paracetamol has a liver ceiling. This is not a dosing guide — read the pack and a pharmacist.",
    "If it helped me it will help you. Bodies are copies.",
    "Own pack, own name, a adult. Then a ban list if you compete. Then do not mix with alcohol as a experiment.",
    "A ‘study pill’ from a friend is a criminal and a medical story. Friends are not a PBS."],
  ["vx-w-hand-hygiene", "Safety", "Hands are a public transport for microbes; soap is a timetable",
    "20-ish seconds as a cartoon, a food line, a nose. Sanitiser is a alcohol for a when-soap-is-not, not a glitter ritual that replaces a wash when they are dirty with soil.",
    "If they look clean they are clean. Eyes are a culture.",
    "Wash at the food and toilet moments. Then a sanitiser that is actually alcohol. Then a cut that is covered.",
    "A sausage sizzle without a wash station is a norovirus hope. Hope is not a HACCP."],
  ["vx-w-sti-stigma", "Safety", "Bodies and infections do not care about your reputation; testing is a civic",
    "Condoms, a clinic, a conversation. Stigma delays tests. School sex-ed is a policy with a parent bit — this is not a how-to of risk. Confidentiality exists in clinics for a reason.",
    "If they look healthy they are negative. Looks are a PCR.",
    "A clinic, a honest, a wait for results as taught. Then do not dox a rumour. Then a vaccine that exists for some (HPV).",
    "A joke in a change room is a climate that delays a test. Climate is a public health."],
  ["vx-w-public-health", "Public extras", "Public health is prevention at a population, not a lecture at one body",
    "Water, vax, a road rule, a tobacco law. The hero is often a boring engineer. Individual ‘choice’ sits on a designed street.",
    "Health is only gym and kale. Populations are just many gyms.",
    "Name a upstream control (a speed limit, a fluoridation). Then a downstream hospital. Then who paid.",
    "A seatbelt law is a public health. A personal trainer is a downstream cousin."],
  ["vx-w-social-determin", "Public extras", "A postcode can predict a health number better than a kale receipt",
    "Income, housing, racism, a job. Behaviours still matter and are not the whole file. Blaming a person for a postcode is a category error.",
    "If they tried they would be healthy. Effort is a suburb.",
    "Map a rate, then a housing, then a clinic access. Then a program that is a housing as well as a pamphlet.",
    "A remote store price on fruit is a determinant. A lecture about fruit is a pamphlet on a expensive apple."],
  ["vx-w-screen-time-nuance", "Public extras", "Screen time is a content and a displacement, not a single evil hour",
    "What it replaced (sleep, a walk, a person). A call to a grandparent is not a loot-box. Guidelines are a cartoon of a average.",
    "All screens are equal and bad. Pixels are a toxin.",
    "Ask what it bumped, then a house rule that is a sleep and a meal. Then a game that is a club vs a game that is a wallet.",
    "A PE theory lesson on a laptop can be a screen that is school. Displacement still exists if it ate the walk home."],
  ["vx-w-vape-nicotine", "Public extras", "A vape is often a nicotine delivery with a marketing of fruit",
    "Developing brains, a gateway fight in the evidence, a illegal sale to minors as a policy. Flavour is a design. Dual use with cigarettes is a file.",
    "If there is no smoke it is safe. Smoke is the only harm.",
    "The law, a help to quit, then do not share a device as a friendship. Then a school policy that is a consistent, not a lucky dip.",
    "A ‘just flavour’ that still hits is a labelling. Labels lie."],
  ["vx-w-sunsmart-policy", "Public extras", "A SunSmart school is a timetable and a hat, not a assembly once",
    "No hat no play as a system. Uniform that is a sleeve. A carnival at 1 pm in January is a policy fail even with a speech.",
    "If they were told they are protected. Assemblies are a SPF.",
    "Shade, a timetable, a sleeve, a modelled teacher hat. Then a parent who still gets the note.",
    "A teacher in a singlet on duty is a curriculum of UV. Modelling is a policy."],
  ["vx-w-food-env", "Public extras", "A food environment is what is in reach at 3:10, not a willpower exam",
    "Canteen, a servo, a price. Zoning of junk near a school is a fight. A lunch that is a time to eat is a environment.",
    "If they wanted salad they would bring salad. Want is a fridge at 3:10.",
    "Change the default (water, a decent line), then a price, then a time to eat that is not 8 minutes. Then a skill to cook as a extra, not as the only lever.",
    "A school that bans a bottle but sells a sports drink is a mixed environment. Mixed is a curriculum."],
  ["vx-w-health-promo", "Public extras", "A campaign is a message plus a environment, not a poster of a sad organ",
    "Ottawa charter as a cartoon: build policy, a skill, a reorient of services. Fear ads have a evidence fight (they can freeze, not change).",
    "If the poster is scary it works. Amygdala is a behaviour.",
    "Pick a action that is possible this week, then a environment that makes it easier, then a evaluation that is not ‘we printed 400’.",
    "A ‘don’t smoke’ poster in a staff room of smoke is a irony. Policy beats a organ photo."],
  ["vx-w-data-privacy-health", "Public extras", "A wellbeing survey is health data with a consent and a storage",
    "Who sees, a identifiability, a mandatory report line. A class ‘how anxious are you, hands up’ is a method fail.",
    "If it is for school it is private by magic. Schools are a vault.",
    "Anonymous when you can, a need-to-know, a lock. Then a not in a hallway. Then a follow-up that is a person, not a graph in assembly.",
    "A published ‘our Year 9 anxiety %’ that is a small n is a identification risk. n is a ethics."],
  ["vx-w-first-nations-health", "Public extras", "First Nations health is a sovereignty, a clinic, and a history, not a deficit graph as a complete story",
    "Strength, a community control, a Closing the Gap that is a political number. Racism in a waiting room is a determinant. Do not use a class as a exhibit.",
    "If the graph is bad the people are the problem. Graphs are a culture.",
    "Listen to community-controlled voices, then a history (dispossession, a stolen file), then a strength. Then a not a ‘they’ from a non-Indigenous teacher as a expert.",
    "A ACCHO is a geography of care. A fly-in clinic is another. Models differ."],
  ["vx-w-mens-health-help", "Public extras", "A ‘harden up’ culture is a health intervention with a body count",
    "Help-seeking gaps, a suicide statistic that is a public file, a mateship that can be a door or a lock. Sport clubs as a site of a conversation.",
    "Men do not talk and that is biology. Biology is a culture.",
    "A door (a GP, a mate who can listen, a line), then a club that models a appointment. Then do not wait for a ‘rock bottom’ as a policy.",
    "A coach who only yells is a mental-health climate. Climate is a season ticket."],
  ["vx-w-womens-sport-acl", "Public extras", "ACL rates in some women’s sports are a loading and a access story, not a ‘women are fragile’",
    "Codes, a surface, a strength program, a history of underfunded prep. Biology plus a system. Prevention programs exist as a evidence.",
    "Women should not play those sports. Knees are a destiny.",
    "A prep that is a strength, a landing, a calendar that is not a pile. Then a code that funds it. Then a not a ban as a safety.",
    "A 6-week preseason that is actually 6 days is a ACL geography. Time is a control."],
  ["vx-w-period-health", "Public extras", "Periods are health data, not a punchline, and iron is a sport file",
    "A missed period in a heavy trainer can be a RED-S clue. Products, a toilet that is a lock and a bin. Endo is a pain that is not ‘just cramps’ as a complete.",
    "If they play they should not mention it. Silence is a professionalism.",
    "A toilet that works, a education that is a fact, a GP for a pain that owns the month. Then a iron check if a clinician says. Then a not a weigh-in as a team.",
    "A carnival without a bathroom plan is a participation barrier. Barriers are a equity."],
  ["vx-w-sleep-policy", "Public extras", "A 11:59 due date is a sleep policy",
    "Schools set a clock. A pile of 11:59s is a jetlag. Workplaces that email at 10 pm are a cousin. Adolescent biology plus a policy is a collision.",
    "Deadlines teach grit. Grit is a melatonin.",
    "Due at 8 pm, a coordinated calendar, then a workplace that does not reward the 2 am email. Then a student who still needs a skill of a plan.",
    "A LMS that timestamps 00:01 as a fail is a sleep curriculum. Timestamps are a pedagogy."],
  ["vx-w-rpe-session", "Movement", "A hard day needs an easy day in the week or the week is a one-note",
    "Polarised cartoons, a 80/20-ish. A school sport that is match-match-match is a overreach. Variety is a periodisation lite.",
    "Every session should be a PB. PBs are a week.",
    "Colour the week: green easy, red hard, a rest. Then a coach. Then a exam week that is a deload.",
    "A carnival plus a club plus a PE beep is a three-peat. Three-peats injure."],
  ["vx-w-landing", "Movement", "How you land is a ACL and a ankle file",
    "Soft knee, a hip, a quiet foot as cues. Fatigue ruins landings. A prevention program is a evidence in some codes.",
    "If you are brave you land stiff. Stiff is powerful.",
    "Jump, land quiet, film. Then a strength that is a hamstring. Then a not a 50 cm drop on day 1 of Year 8.",
    "A netball stop is a landing. So is a basketball. Codes share a knee."],
  ["vx-w-cross-train", "Movement", "Cross-training is a different pattern that can save a overuse",
    "A runner who swims. A identical load every day is a shin. Specificity still matters for a event — mix is not a replacement of the skill forever.",
    "If it is not the sport it does not count. Pools are a leak.",
    "Keep the sport, add a different, then a injury that is a swap not a sofa. Then a not a random extra that is a ego lift.",
    "A swimmer with a shoulder who rows badly is a second shoulder. The swap needs a brain."],
  ["vx-w-iron-food", "Food", "Iron is a oxygen taxi; food plus a vitamin C cousin, tea as a binder",
    "Haem vs plant. A teen, a period, a vegan pattern can need a plan — a GP, not a PE guess. Over-iron is a harm too.",
    "If you are tired you need a tablet from a friend. Tired is a ferritin.",
    "Food first, a test if a clinician says, then a tablet that is theirs. Then do not stack a random from a gym.",
    "A tea with a lentil meal is a absorption story. Time the tea. Stories are a dietitian."],
  ["vx-w-iodine", "Food", "Iodine is a thyroid mineral with a iodised salt and a seafood geography",
    "Australia has a history of a salt program. Pregnancy is a clinician file. A rock-salt fashion can skip the iodise.",
    "If it is salt it is iodised. Rocks are a public health.",
    "A iodised default, then a pregnancy advice from a professional, then a not a kelp tablet as a hobby without a reason.",
    "A inland diet without a iodised and without a fish is a geography of a gland. Geography is a nutrient."],
  ["vx-w-mindful-eat", "Food", "Eating while a screen is a speed; hunger cues are a slower dashboard",
    "A packet that vanishes. Fullness lags. A mindful is a attention, not a moral of a slow chew cult. Some ADHD/autistic patterns need a different, kinder frame.",
    "If you eat slow you are virtuous. Virtue is a gastric.",
    "A plate, a sit, a check at half. Then a screen-off as a experiment. Then a not a shame if a pattern is a neurotype.",
    "A 7-minute lunch bell is a environment that kills cues. Bells are a policy of gobble."],
  ["vx-w-peer-pressure", "Mind", "A dare is a social load; a scripted no is a skill",
    "Broken-record, a exit, a ally. Substances, a lift that is a ego, a send of a photo. A laugh as a pressure.",
    "If they were a real friend they would not ask. Friendship is a filter that never fails — or: if you say no you have no friends.",
    "A sentence you practised, a leave, a person later. Then a not a lecture in the moment if a exit is safer.",
    "A party that is a car without a licence is a safety, not a popularity. Cars are a law."],
  ["vx-w-body-comment", "Mind", "A comment on a body is a load, even if you meant a compliment",
    "‘You look like you lost’ can be a eating-war. A coach’s weigh joke. A family at Christmas. Opt out of the commentary.",
    "If it is nice it cannot harm. Nice is a ethics.",
    "Talk about what they did, not the meat. Then a house rule. Then a coach education.",
    "A ‘gain season’ joke at a jumper is a climate. Jumpers are a person."],
  ["vx-w-sun-eye", "Body", "UV hits eyes too; a wrap-around is a organ PPE",
    "Pterygium, a cataract later, a snow and a water bounce. Cheap dark without UV filter can be a pupil that opens to a dose. Look for a standard mark.",
    "If it is dark it blocks UV. Darkness is a rating.",
    "A wrap, a standard, a hat as a extra. Then a not a look-at-the-sun. Then a weld as a different, serious PPE.",
    "A cricket outfield is a bounce. The bounce is a lens."],
  ["vx-w-noise-ear", "Body", "Noise is a dose: a concert, a mower, a bud at a max",
    "Time × intensity. Tinnitus as a extra. A occupational on a farm. Buds that seal can be a higher dose than you think.",
    "If it is music it cannot damage. Art is a PPE.",
    "A lower volume, a break, a muff when a machine. Then a not a cotton as a NRR. Then a audiology if a ring stays.",
    "A school formal next to a speaker is a dose. Speakers are a occupational for the DJ too."],
  ["vx-w-backpack-two", "Body", "Two straps, close to the back, a load that is not a furniture move",
    "A percent-of-body cartoon (take as a guide, not a law). A locker as a geography. A one-shoulder is a scoliosis folklore more than a evidence — still a pain.",
    "If they can lift it it is fine. Lift is a all-day.",
    "Both straps, a weigh of the bag as a experiment, a locker. Then a school that does not require 12 textbooks as a personality.",
    "A laptop plus a sport kit plus a water plus a 800-page is a mule. Mules are a timetable problem."],
  ["vx-w-otc-mix", "Safety", "Two over-the-counter can share a paracetamol or a interaction",
    "A cold-and-flu plus a extra panadol is a double. A grapefruit is a pharmacist story for some. This is not a list — a pharmacist is.",
    "If it is on the supermarket shelf it cannot stack. Shelves are a liver.",
    "One pack at a time, a pharmacist, a not a mix as a experiment. Then a sport-ban if you compete.",
    "A ‘natural’ plus a prescription is still a chemistry. Naturals are a molecule."],
  ["vx-w-cpr-update", "Safety", "CPR ratios change; your uncle’s 1994 memory is a historical document",
    "A current course. Compression depth as taught. A phone speaker on 000. A fear of legal is a Australia Good Samaritan cartoon — still do the course.",
    "If you remember any CPR it is fine forever. Memory is a accredited.",
    "A course this year-ish, a AED, a hands. Then a not a practise on a person. Then a wall that is unlocked.",
    "A oval with a AED and nobody who will walk to it is a second fail. Walking is a drill."],
]);
