import { pack } from "../pack.mjs";

export const HISTORY_VOLUME = pack("history", [
  ["vx-h-anachronism", "Skills extras", "An anachronism is a time-travelling object in the story",
    "A wristwatch on a Roman statue is a tell. So is expecting a 1788 governor to tweet. Chronology is a skill, not a vibe.",
    "If it is in a movie it was available then. Costume departments are archives.",
    "Ask ‘could this exist yet?’ before you use a source as a window. Period films are arguments.",
    "A 1901 federation poster with a 1950s Holden is a teaching joke, not evidence of cars at federation."],
  ["vx-h-presentism", "Skills extras", "Presentism is judging them only by our current kit",
    "People in 1850 did not have germ theory as a public habit. You can still name harm. The skill is reconstructing their available ideas, then evaluating.",
    "If they were good people they would have had our opinions. History is a moral IQ test.",
    "State their world, then your criteria. Do not skip the first step to get to the sermon.",
    "Abolitionists existed inside slave societies. ‘Everyone thought X’ is often lazy."],
  ["vx-h-turning-vs-trend", "Skills extras", "A turning point is a hinge; a trend is a slope",
    "1945 can be a hinge for empires and a continuation of industrial killing. You need to say for whom and for what.",
    "If a textbook chapter starts there, it was the only cause. Headings are destiny.",
    "Name the before/after for a specific thread (rights, borders, technology). Then admit what did not turn.",
    "Federation 1901 turned a legal status and did not turn a lot of working lives overnight."],
  ["vx-h-agency-structure", "Skills extras", "Agency is a person pushing; structure is the room they are in",
    "A union secretary and a wool price and a racist statute can all be in one strike story. ‘Great men’ vs ‘impersonal forces’ is a false exclusive.",
    "History is only kings. Or only prices. Pick a team and stay.",
    "Ask who could choose, who could not, and which rules boxed the choice.",
    "Pearl Gibbs had agency inside structures that were trying to erase it. Both sentences can be true."],
  ["vx-h-intended-unintended", "Skills extras", "Intended policy and side effects are different tickets",
    "White Australia intended a racial labour market. It also shaped who could be a neighbour. Unintended is not ‘accidental therefore innocent’.",
    "If they did not mean that result, it does not count as history.",
    "Read the stated aim, then the measurable outcomes, including ones they denied.",
    "Prohibition in the US intended less drink and grew organised crime. The gap is the lesson."],
  ["vx-h-scale-jump", "Skills extras", "A local story and a world story can share a date and not a meaning",
    "A 1930s dole riot in Sydney and a 1930s German election are both ‘Depression’ only at a high zoom. Scale is a choice.",
    "If the year matches, the cause matches. Calendars are glue.",
    "State the scale: street, colony, empire, planet. Then what travels between them (prices, ideas, ships).",
    "Spanish flu was planetary and still hit a particular boarding house. Both zooms."],
  ["vx-h-significance-test", "Skills extras", "Significance is a claim: remarkable, remembered, resulting, revealing",
    "Partington-style tests (or similar) stop ‘it is significant because it is in the exam’. A forgotten massacre can still be revealing.",
    "If it is famous it is significant. If it is obscure it is trivia.",
    "Apply a test out loud. Say for whom. Anzac is remembered; other wars are revealing and less branded.",
    "A family letter can be significant for a community and not for a national myth. That is allowed."],
  ["vx-h-corroborate", "Skills extras", "Corroboration is overlap plus leftover disagreement",
    "Two diaries that match on a date and fight on a motive are useful. Perfect match can be a copy.",
    "If two sources agree, the past is solved. Stop.",
    "List what is independent (different authors, different interest). Then what still conflicts.",
    "A newspaper and a police file can corroborate a crowd size poorly — both may guess. Independence matters."],
  ["vx-h-provenance", "Skills extras", "Provenance is who, when, why, and how it survived",
    "A 1916 recruiting poster wants bodies. A 2016 replica wants heritage tourism. The later one is a source about memory.",
    "Old paper is honest. New paper is fake. Age is virtue.",
    "Write origin, purpose, audience, and the journey to your desk. Then use it.",
    "A digitised photo without a caption is a pretty file. The missing provenance is a limit, not a vibe."],
  ["vx-h-oral-history", "Skills extras", "Oral history is evidence of memory, with timing and audience",
    "A 1980s interview about 1942 is primary for the remembering, slippery for the bombing timetable. Trauma and pride edit.",
    "If they said it on tape it is exactly what happened at 3 pm.",
    "Use it for experience, language, and what was later sayable. Check against contemporaneous traces.",
    "Indigenous oral traditions can be knowledge systems with different rules than a court transcript. Do not flatten them into ‘anecdote’."],
  ["vx-h-quant-source", "Skills extras", "A table is a source with a category machine inside",
    "Census, shipping lists, casualty counts: they include and exclude. ‘Chinese’ in 1901 is a bureaucratic box, not a DNA test.",
    "Numbers cannot lie. Only speeches lie.",
    "Ask who was counted, who was not, and who invented the columns. Then do the arithmetic.",
    "Indigenous people were long under-counted. A ‘population’ line can be a political artefact."],
  ["vx-h-counterfactual", "Skills extras", "‘What if’ is a tool for causes, not a fanfic exam",
    "If you cannot name a plausible fork (a lost vote, a delayed ship), the counterfactual is a mood. Historians use small, disciplined ones.",
    "If Napoleon had a phone he would have won. Gadgets decide.",
    "Change one variable, keep the rest sticky, and say what you are testing (necessity of a cause).",
    "‘No Gallipoli’ is a huge fork. ‘If that barge had landed 200 m left’ is a tighter one. Pick for the question."],
  ["vx-h-continuity", "Skills extras", "Continuity is what failed to turn when the flag did",
    "1967 changed a count and a Commonwealth power; it did not install equality as a vending machine. Change and continuity in one paragraph is the adult move.",
    "A new law is a new world by sunrise. Gazettes are magic.",
    "Name one changed practice and one that stuck. Dates are not detergents.",
    "Women’s suffrage changed who voted and not who owned the wool store the next Monday."],
  ["vx-h-empathy-limit", "Skills extras", "Empathy is reconstructing a world; it is not a hug for the archive",
    "You can understand a squatter’s fear of land courts without blessing dispossession. Understanding ≠ endorsing.",
    "To study them you must like them. Dislike is unprofessional.",
    "Reconstruct motives and constraints, then evaluate harm with your stated criteria.",
    "A perpetrator diary is still a source. Reading it is not a loyalty oath."],
  ["vx-h-periodise", "Skills extras", "A period is a box we made for a purpose",
    "‘Interwar’ is a European-shaped box. Australia’s 1920s have other names (returned soldiers, conscription leftover, White Australia). Borrowed period names leak.",
    "Decades are nature. The 1960s started on 1 January 1960 everywhere the same way.",
    "Say whose periodisation. Then what it hides (women, Indigenous time, regional offset).",
    "‘Postwar’ in 1946 Darwin is a different weather from 1946 London. The box still has uses."],
  ["vx-h-absence-evidence", "Skills extras", "Absence in the file is not absence in the past",
    "Illiterate lives, banned languages, burnt records, unfilmed massacres. ‘We have no sources’ can mean ‘the state did not keep their words’.",
    "If it is not in the archive it did not happen. Filing cabinets are God.",
    "Look for traces (archaeology, oral, later inquiries). Name the silence as a fact about power.",
    "The Frontier Wars were under-written in some official series and over-present in oral Country. That mismatch is evidence."],
  ["vx-h-agri-revolution", "World stories", "Farming was a slow trap with a surplus, not a eureka vegetable",
    "Domestication staggered. Surplus fed specialists and states. Inequality and disease often rose with grain. ‘Progress’ is a later slogan.",
    "Someone invented bread on a Tuesday and civilisation arrived on Wednesday.",
    "Separate domestication, surplus, and states. Different places, different crops (wheat, rice, maize, taro).",
    "Australia’s Indigenous food systems were not ‘waiting for farming’ as a failed exam. Different land management is a different sentence."],
  ["vx-h-writing-states", "World stories", "Writing often arrives as a state tool: lists, taxes, gods",
    "Cuneiform receipts are not novels. Literacy was rare. A ‘civilisation’ defined as ‘has writing’ is a circular club.",
    "As soon as people spoke they wrote. Speech and script are twins from the start.",
    "Ask who could write and what was worth clay. Then who is missing.",
    "Oral law can be as complex as a code. Writing is a technology of memory, not a morality."],
  ["vx-h-indian-ocean", "World stories", "The Indian Ocean was a monsoon highway before steam",
    "Dhows, spices, enslaved people, ideas. Swahili coasts, Gujarat, Srivijaya, later Europeans as violent newcomers to an old web.",
    "Trade begins when the Dutch arrive. Oceans were empty waiting rooms.",
    "Map monsoon timing and ports. Then goods and religions as passengers.",
    "Macassan trepang fleets to northern Australia sit on this ocean, not on a European discovery timeline."],
  ["vx-h-islamic-world", "World stories", "A medieval Islamic world was a knowledge machine as well as an empire set",
    "Translation, algebra’s name, hospitals, paper. It was not a single calm utopia nor a cartoon villain. Dynasties differ.",
    "The ‘Dark Ages’ were dark everywhere because Europe is the world.",
    "Name a city (Baghdad, Córdoba, Cairo) and a practice. Then the political fractures.",
    "Latin Europe borrowed and fought. Both are history. A clash-of-civilisations poster is a later product."],
  ["vx-h-black-death", "World stories", "The Black Death was a biological event with a labour price",
    "Yersinia pestis plus fleas/rats/people (debated details). Labour shortages, wages, revolts, piety, and scapegoats. Not ‘the end of the Middle Ages’ as a single switch.",
    "Plague happened because people were dirtier than us as a species. Hygiene is destiny always.",
    "Track mortality estimates as ranges, then social effects that are evidenced (statutes of labourers, flagellants, pogroms).",
    "Later plagues (1665, Pacific ports) are sequels, not the same outbreak. Date your epidemic."],
  ["vx-h-reformation", "World stories", "The Reformation was a media and state event, not only a monk’s mood",
    "Print, princes, and indulgences. Luther, Calvin, Catholic reform. Wars of religion were about power as well as salvation.",
    "One thesis on a door invented modern individualism before lunch.",
    "Separate theology, printing, and princely interest. England’s break is a different cocktail (Henry, then others).",
    "Australia’s later sectarian school fights are a distant echo, not a replay of 1517."],
  ["vx-h-scientific-rev", "World stories", "A ‘scientific revolution’ is a later label for messy practices",
    "Instruments, print, courts, and new authority claims. Galileo vs a cartoon Church is a school play. Women and artisans are often edited out.",
    "Science started in 1687 when a book was hard. Before that, only superstition.",
    "Name a practice (observation, maths, experiment) and a patron. Then who got credit.",
    "Chinese, Islamic, and Indian knowledge traditions are not a prequel logo. They are concurrent machines."],
  ["vx-h-enlightenment", "World stories", "Enlightenment was a quarrel in print, including about who counts as human",
    "Rights talk, salons, and empires. Some philosophes defended slavery with the other hand. ‘Reason’ had a guest list.",
    "The Enlightenment freed everyone equally on publication day.",
    "Read a claim (sovereignty, religion, race) and ask who is in the room. Haitian revolutionaries used and exceeded those texts.",
    "Australian colonists could quote liberty while fencing Aboriginal land. The quote is evidence of a contradiction, not a solvent."],
  ["vx-h-haitian-rev", "World stories", "Haiti 1791–1804 was a successful slave revolution with a bill",
    "Saint-Domingue’s enslaved majority overthrew a plantation machine. France, Britain, and the US reacted with fear and debt traps. It is not a footnote to Paris.",
    "The French Revolution freed the colonies automatically because the poster said liberty.",
    "Centre Black agency, then the diplomatic punishment that followed. Sugar and geopolitics.",
    "News of Haiti travelled. Slaveholders in other empires read it as a nightmare manual."],
  ["vx-h-opium-wars", "World stories", "The Opium Wars were drug profits plus gunboats plus a legal story",
    "British (and others’) silver/opium imbalance, Qing restriction, unequal treaties. ‘Free trade’ here is a slogan with artillery.",
    "China was closed because it was scared of tea. Britain just wanted a chat.",
    "Follow the commodity, the silver, and the treaty ports. Then extraterritoriality as a legal technology.",
    "Australian colonies drank tea and wore the empire’s wars at a distance. The connection is imperial, not ‘Sydney did it’ as a cartoon."],
  ["vx-h-scramble-africa", "World stories", "The scramble was a conference plus rifles plus a map with a ruler",
    "Berlin 1884–85, maxim guns, concession companies. African states and resistance (Ethiopia at Adwa) are part of the story, not a blank.",
    "Africa had no politics until Europe arrived with flags. The interior was empty.",
    "Map claims vs control on the ground. Then extractive economies and invented borders.",
    "A later independence flag on a colonial border is continuity of a line, not of a people automatically."],
  ["vx-h-russian-rev", "World stories", "1917 was two revolutions and a civil war, not a single crowd scene",
    "February toppled the tsar; October brought the Bolsheviks. War, land, and soviets. Stalin is a later consolidation, not the street in 1917.",
    "Lenin pressed a button labelled communism and the 20th century arrived.",
    "Sequence 1914 war → 1917 dual power → civil war → NEP → later Stalin. Do not squash.",
    "Australian radicals and conservatives both used ‘Bolshevik’ as a local weapon in the 1920s. That is reception, not a Moscow branch."],
  ["vx-h-influenza-1918", "World stories", "The 1918–19 influenza was a wartime pandemic with a public-health theatre",
    "Troop ships, crowded camps, second-wave deadliness. Masks, closures, and blame. Australia’s maritime quarantine is a local chapter.",
    "It was ‘Spanish’ because it started in Spain. Names are medical facts.",
    "Track movement with the war, then local responses. Death estimates are ranges.",
    "First Nations communities were hit hard in some regions. A national death rate can hide that."],
  ["vx-h-decol-india", "World stories", "1947 was independence plus a partition with a body count",
    "Congress, Muslim League, British exhaustion, and a rushed line. Partition violence is not a side effect you mention once.",
    "The British left because they were nice now. Flags were a gift.",
    "Name nationalist movements, wartime strain, and the partition mechanism. Then Kashmir as an unfinished file.",
    "Colombo Plan students in Australia are a later, related world. Different ticket."],
  ["vx-h-cuban-missiles", "World stories", "1962 was a nuclear bargaining week, not a movie about nerves only",
    "Soviet missiles in Cuba, US missiles in Turkey as context, blockade/quarantine, back-channel. The world did not ‘almost end’ as a video game; it was still a near miss with procedures.",
    "Kennedy stared; Khrushchev blinked; history is a cowboy contest.",
    "List the weapons, the geography, and the deal. Then the hotline as a later patch.",
    "Australia’s alliance meant we lived in the blast radius of other people’s decisions. That is alliance history."],
  ["vx-h-macassan", "Australia extras", "Macassan trepang fleets are a northern contact story before 1788’s usual start",
    "From Sulawesi to Arnhem Land: trade, language loans, tamarind, diplomacy, and conflict. It is not ‘pre-history waiting’.",
    "Nothing maritime happened until Cook. The north is a blank.",
    "Use Yolngu and Macassan traces together. Then what British colonisation later interrupted.",
    "A dugout or a loanword can be a document. Not every document is a despatch from Whitehall."],
  ["vx-h-convict-system", "Australia extras", "Transportation was a punishment machine with a labour market",
    "Assignment, tickets of leave, secondary punishment (Port Arthur, Moreton Bay). Not all convicts were ‘for bread’. Women convicts are not a joke reel.",
    "Australia was only a jail, then it was only a nation. Two costumes, no overlap.",
    "Read a convict record as labour plus discipline. Then emancipation as a legal status, not a personality makeover.",
    "Aboriginal land was the unasked foundation under the gaol. The system sat on Country."],
  ["vx-h-myall-creek", "Australia extras", "Myall Creek 1838 is a massacre that went to court — unusually",
    "At least 28 Wirrayaraay people killed. Some white perpetrators hanged. The rarity of that outcome is the point, not a proof the frontier was lawful.",
    "If there was a trial, the frontier was fair. Courts are a full stop.",
    "Use the trial papers and the oral/Country memory. Then ask why so few other massacres were prosecuted.",
    "A hanging can be a settler panic about ‘our people’ as well as a justice event. Motives stack."],
  ["vx-h-eureka", "Australia extras", "Eureka 1854 was a tax and representation fight on a goldfield, later a brand",
    "Licences, southern cross flag, a short rebellion, a court that would not convict. It is not ‘the birth of democracy’ as a single dad.",
    "Eureka invented the eight-hour day, the ALP, and the Anzac legend before breakfast.",
    "Read the licence grievance, the Ballarat conditions, and the later myth. Separate 1854 from 1915.",
    "Chinese miners on the same fields had a different state. Eureka’s ‘us’ had a guest list."],
  ["vx-h-sa-suffrage", "Australia extras", "South Australia 1894 enfranchised women, including (on paper) some Aboriginal women — then practice pinched",
    "First in Australia for (most) women to vote and stand. Aboriginal inclusion was legally messy and later restricted in practice. ‘First in the world’ needs a careful sentence.",
    "All Australian women voted from 1901 because federation was magic.",
    "Date the colony, then the Commonwealth Franchise Act 1902 which excluded ‘Aboriginal natives’ in most cases. Two calendars.",
    "New Zealand’s 1893 is the usual ‘first national’ comparison. Do not steal their sentence."],
  ["vx-h-wave-hill", "Australia extras", "Wave Hill 1966 was a walk-off about wages, dignity, and land",
    "Gurindji workers left Lord Vestey’s station. Vincent Lingiari, nine years, then Whitlam’s sand. It is labour history and a land rights hinge.",
    "It was only about award wages. Land was a later PR stunt.",
    "Start with station conditions, then the handback as a political sequel, then unfinished business.",
    "The photo of pouring sand is a memory object. The legal title story continues after the camera."],
  ["vx-h-whitlam-sacked", "Australia extras", "11 November 1975 was a constitutional crisis, not a personality quiz only",
    "Supply, Senate, Kerr, Fraser, Whitlam. Convention vs text. People still fight about whose convention.",
    "The Queen fired him because she was bored. Palaces run Australia daily.",
    "Sequence the money bills, the governor-general’s choice, and the election that followed. Then reform debates (double dissolution, convention).",
    "A dismissal is not a coup in the textbook sense, and calling it only ‘politics as usual’ erases why people marched."],
  ["vx-h-maralinga", "Australia extras", "Maralinga was British nuclear testing on Aboriginal land with a cleanup that leaked",
    "1950s–60s tests, Anangu displacement, contamination, later royal commission. Alliance is not a synonym for care.",
    "The desert was empty so tests were fine. Empty is a land-use category.",
    "Read the tests as imperial science plus a sovereignty story. Then veteran and Anangu harm as evidence, not atmosphere.",
    "Emu Field and Monte Bello are siblings. ‘Maralinga’ is sometimes used as a brand for the set."],
  ["vx-h-snowy-scheme", "Australia extras", "The Snowy was a nation-building dam set with migrant labour and a displaced high country",
    "Postwar hydro, irrigation politics, European recruits, and environmental costs later re-argued. It is not only a feel-good documentary.",
    "The Snowy made the desert bloom without losers. Concrete is kindness.",
    "Name energy, irrigation, and workforce. Then Aboriginal dispossession and river ecology as the invoice.",
    "A ‘populate or perish’ labour market sat underneath the tunnels. Migration policy is in the rock."],
  ["vx-h-franklin-dam", "Australia extras", "The Franklin campaign was environment plus federal power plus a river",
    "Tasmanian hydro vs wilderness. 1983, Hawke, World Heritage, High Court. Green politics as a national force.",
    "A dam is always progress. Blocking it is anti-jobs as a complete theory.",
    "Follow the protest method, the election, and the constitutional lever (external affairs/World Heritage).",
    "Wilderness as a word can erase Aboriginal presence. The campaign’s language is itself a source."],
  ["vx-h-mabo-native-title", "Australia extras", "Native title after Mabo is a statutory machine, not a vibe of fairness",
    "1992 Mabo, 1993 Native Title Act, Wik, later amendments. Pastoral leases and ‘connection’ tests. Winning in court is not a farm gate opening by itself.",
    "Mabo gave the land back as a simple return-to-sender. The Act was a ribbon.",
    "Separate common-law recognition from the Act’s filters. Then a specific determination if you are writing a case.",
    "Terra nullius as a doctrine was rejected. Lots of dispossession remains legally sticky. Both true."],
  ["vx-h-apology-2008", "Australia extras", "The 2008 Apology was a speech act with a politics of what it did not do",
    "Rudd, Stolen Generations, bipartisan theatre, and the compensation argument that continued. A sorry is not a settlement cheque by itself.",
    "Once a PM apologises, the history is finished. Speeches close files.",
    "Read the text, the audience, and the policy that did or did not follow. Then Bringing Them Home as the earlier document.",
    "Howard’s refusal is part of the same file. Memory wars are sources."],
  ["vx-h-voice-2023", "Australia extras", "The 2023 Voice referendum was a constitutional proposal with a long campaign",
    "A First Nations Voice to Parliament: failed nationally, passed in some inner-city booths, failed in others. It is too recent to mythologise as destiny.",
    "Referendums fail because Australians hate Indigenous people as a monolith. One cause, done.",
    "Read the question, the 1967 comparison (carefully — different questions), and the ‘details’ fight. Then regional vote maps.",
    "Uluru Statement from the Heart is a prior text. Voice, Treaty, Truth was a sequence, not a single button."],
  ["vx-h-conscription-vn", "Australia extras", "Vietnam conscription was a birthday lottery with a street fight",
    "National Service, 1960s–72, moratoriums, and a coalition government. Not every veteran was conscripted; not every protester hated soldiers.",
    "If you opposed the war you spat on every returned man. The myth is a primary source about later memory.",
    "Separate alliance strategy, the ballot, and the domestic movement. Then the later welcome-home politics.",
    "The ‘birthday ballot’ marbles are a museum object with a legal machine behind them."],
  ["vx-h-colombo-plan", "Australia extras", "The Colombo Plan was Cold War students as diplomacy",
    "Asian students in Australian universities, 1950s on. Soft power, White Australia still on the books, and later multiculturalism’s prequel.",
    "Australia was always multicultural in policy because someone had a curry in 1961.",
    "Read it as foreign policy plus education. Then the lived racism and the later skilled-migration sequel.",
    "A Colombo Plan memoir is a source about hospitality and surveillance both."],
  ["vx-h-factory-time", "Rights & everyday", "Factory time was a new clock on the body",
    "Bells, fines, child labour, then campaigns for shorter days. The eight-hour slogan is a Melbourne 1850s brand with incomplete coverage.",
    "Work was always 9–5 with weekends. Nature invented the roster.",
    "Use a rule book or a royal commission on sweating. Then who was excluded (women’s hours, Aboriginal labour, homework).",
    "A time clock is an artefact of discipline. So is a smoko. Both are history."],
  ["vx-h-sewer-city", "Rights & everyday", "Sewerage was a public-health politics, not a plumber’s hobby",
    "19th-century cities killed with water. Nightsoil, then pipes, then rates bills. Who got connected first is a class map.",
    "Germs vanished when people became nicer. Morality is sanitation.",
    "Follow cholera/typhoid scares, engineers, and municipal rates. Then remaining outhouses as evidence of unevenness.",
    "A nightcart schedule is a source. So is a Board of Health report that blames ‘the poor’ for the pipe the council refused."],
  ["vx-h-compulsory-school", "Rights & everyday", "Compulsory schooling is a state grabbing childhood",
    "Late 19th-century acts: attendance, a curriculum, inspectors. It made literacy and also a mould. Aboriginal children often got a different, crueller system.",
    "Schools exist because kids love exams. The state noticed and helped.",
    "Read an education act, then truancy records, then who was exempted or segregated.",
    "A slate and a cane are artefacts. The cane is a discipline history, not a joke about ‘the old days were fine’."],
  ["vx-h-weekend-leisure", "Rights & everyday", "The weekend is a political product with a beach attached",
    "Saturday half-holiday campaigns, early closing, then the two-day weekend as a 20th-century spread. Leisure is not nature.",
    "People always surfed on Saturdays. Oceans invented unions.",
    "Track shop closing laws, union wins, and who still worked (nurses, farmers, domestic staff).",
    "A 1950s beach photo is a source about bodies, class, and who had transport. Not a national soul."],
  ["vx-h-consumer-law", "Rights & everyday", "Consumer rights are a 20th-century legal technology",
    "Caveat emptor toward implied warranties, then Australian Consumer Law. Fine print is a battleground, not a personality test of shoppers.",
    "If you bought it you deserved it. Markets are moral.",
    "Use a case (a lemon car, a dodgy ad) and the rule that caught it. Then who can actually sue.",
    "A ‘was $199 now $198’ ticket is a later ACL-shaped artefact. Dating the ad matters."],
  ["vx-h-disability-rights", "Rights & everyday", "Disability rights shifted from charity to legal personhood — incompletely",
    "Institutions, then DDA 1992, NDIS as a later machine. Access is a fight, not a ramp that appeared from kindness.",
    "Once we got a logo with a wheelchair the job was done. Stickers are ramps.",
    "Read a campaign (sterilisation, institutions, education) then a statute. Then remaining gaps as present history.",
    "A ‘ugly law’ overseas and a local asylum file are comparable technologies of hiding. Compare with care."],
  ["vx-h-marriage-law-au", "Rights & everyday", "Marriage law is a state definition with a moving guest list",
    "Women’s legal personhood, Indigenous marriage recognition, 2017 postal survey and amendment. The law is not ‘love’ as a gas.",
    "Marriage is older than the state so the state cannot define it. History agrees with a slogan.",
    "Date the legal change, the campaign, and who was still outside (age, cousin rules, recognition of other rites).",
    "A wedding photo is not a statute. The 2017 certificate change is. Use both as different sources."],
  ["vx-h-indigenous-vote", "Rights & everyday", "Indigenous voting rights are a patchwork calendar, not one sunrise in 1967",
    "Some voted earlier in some colonies; 1962 Commonwealth franchise for Aboriginal people; 1967 was not ‘the right to vote’ as a slogan.",
    "1967 gave the vote. Every poster said so, so it is true.",
    "Make a timeline by jurisdiction. Then barriers (distance, literacy, intimidation) after the legal yes.",
    "A how-to-vote in language is a later inclusion artefact. Enrolment drives are history too."],
  ["vx-h-refugee-convention", "Rights & everyday", "1951 Refugee Convention is a legal category born from a European wreck",
    "Non-refoulement, a definition, later 1967 protocol expanding geography. Australia’s later boat politics sit on this law and strain it.",
    "Refugee means anyone sad at a border. Feelings are the convention.",
    "Read the legal test, then a specific intake (Displaced Persons, Vietnamese, later). Then the politics of the word ‘queue’.",
    "A visa class is not a moral grade. It is a bureaucratic machine with a history."],
  ["vx-h-un-declaration", "Rights & everyday", "The UDHR 1948 is a list with no army, and a long shadow",
    "Aspirational, Cold War-shaped, used by later movements. It did not end empires that week. Australia had a hand in the drafting story (Evatt) and a domestic racial state.",
    "Once signed, rights arrived in every police station as a poster that bound officers.",
    "Treat it as a toolkit later activists cited. Then the gaps (Indigenous, women, colonies).",
    "A school classroom poster of the UDHR is a 21st-century source about civic pedagogy."],
  ["vx-h-pension-fight", "Rights & everyday", "An aged pension was an argument about deserving and surveillance",
    "1908 Commonwealth pension with tests: race, character, means. Welfare is a moral sorting hat with a cheque.",
    "Pensions exist because we are nice now. Kindness is the only cause.",
    "Read eligibility rules as a source of who counted as a citizen-in-practice.",
    "A ‘pension inspector’ visiting a home is a state in the kitchen. Files of those visits exist."],
  ["vx-h-public-broadcast", "Rights & everyday", "The ABC (1932) is a state broadcaster with a culture war attached",
    "Wireless as nation, then TV, then digital. Charter vs commercial rivals. A royal charter cousin in the BBC, local fights here.",
    "The ABC is ‘the government’ in the sense of a press release factory only. Always was.",
    "Use a charter clause, a controversial program, and a funding fight as three source types.",
    "A 1930s radio licence fee is an artefact of how ‘public’ was paid for."],
  ["vx-h-green-ban", "Rights & everyday", "Green bans were union power plus resident action on concrete",
    "BLF, Jack Mundey, The Rocks, Kelly’s Bush. Heritage and class in one blockade. Not a vegan picnic.",
    "Unions only ever wanted higher pay. Trees are a 21st-century invention for them.",
    "Read a ban as a labour tactic with an environmental outcome. Then the later demolition of the BLF as politics.",
    "A saved terrace in The Rocks is an artefact of a ban, not of a tasteful developer."],
  ["vx-h-decrim-cal", "Rights & everyday", "Decriminalisation is a calendar of states, not a national mood swing",
    "Homosexuality laws fell in different years; South Australia 1975 is an early mark. Police practice can lag the Gazette.",
    "When Sydney had a parade, the law was finished everywhere. Floats repeal statutes.",
    "Table the jurisdictions. Then remaining police powers and the AIDS crisis as a later overlapping file.",
    "A 78ers oral history is a source about law and street both."],
  ["vx-h-museum-label", "Sources & museums", "A museum label is an argument in 80 words",
    "What is named, what is not, whose quote. A 1950s label and a 2020s relabel of the same spear are two exhibits.",
    "If it is behind glass it is neutral. Glass is a solvent of politics.",
    "Read the label as a source about the museum’s year, not only about the object’s year.",
    "A ‘discovered by’ line that names a European and not the maker is a provenance tell."],
  ["vx-h-repatriation", "Sources & museums", "Repatriation is a return of remains and objects with a legal and moral machine",
    "Ancestral remains in European collections, community requests, museum policy. It is not ‘the past being deleted’. It is a present ethics of holding.",
    "Scientists own all bones because knowledge. Communities own feelings only.",
    "Follow a specific case’s paper trail. Then the difference between loan, copy, and return.",
    "A plaster cast left on display while remains go home is a compromise artefact. Read it."],
  ["vx-h-memorial-fight", "Sources & museums", "A memorial is a sentence in stone that later crowds rewrite",
    "Who is named, who is ‘etc.’, where it sits. Adding a plaque, or a protest, is a new source. Pulling it down is also a source.",
    "Statues are history itself. Bronze cannot lie.",
    "Date the memorial, the inscription, and the later argument. Three times.",
    "A blank space where a statue was is a document of 2020s politics as much as of 1860s bronze."],
  ["vx-h-heritage-list", "Sources & museums", "Heritage listing is a legal spell on a place",
    "What qualifies, whose architecture, whose sacred site. A listed pub and an unlisted mission dormitory can sit in one town.",
    "Old plus pretty equals heritage. Rust is the criterion.",
    "Read the citation. Ask what fabric is protected and what stories are not.",
    "A reconstructed ‘historic street’ can be a 1980s shopping idea. Dating the bricks matters."],
  ["vx-h-digitise-gap", "Sources & museums", "Digitised is a sample with a scanner and a copyright",
    "Trove is huge and still not ‘the past’. Optical character errors, paywalled papers, unphotographed boxes. Searchability is a bias toward print.",
    "If Google cannot find it, it did not happen. The index is the world.",
    "Say what corpus you searched and what formats never entered it (oral, private, Country).",
    "A fuzzy scan of a 19th-century paper is a 21st-century artefact of a library budget."],
  ["vx-h-photo-crop", "Sources & museums", "A photograph’s crop and caption are half the claim",
    "Staging, print technology, and later Photoshop cousins. A ‘typical native camp’ image can be a studio. Still useful — as a claim.",
    "Cameras cannot take sides. Light is objective.",
    "Ask who held the camera, who could not refuse, and where the negative sat.",
    "A 1988 Bicentennial image and a 1988 protest image of the same harbour are a pair. Use both."],
  ["vx-h-map-claim", "Sources & museums", "A historic map is a claim on paper, often with empty Country drawn as blank",
    "Terra nullius as cartography: interior labelled ‘unknown’ while people lived there. Scale, dedication, and who paid the surveyor.",
    "Maps are the land. If it is surveyed it was empty before the chain.",
    "Read silences, compass roses, and the date of the survey vs the date of printing.",
    "A pastoral run map with Aboriginal names in the margins is a contact document. Those names are data."],
  ["vx-h-census-box", "Sources & museums", "A census category is a political invention with a count attached",
    "Race boxes change. ‘Half-caste’ is a violence in a column. 1967’s counting story is related but not identical to the referendum myth.",
    "The census is a mirror. People are the boxes.",
    "Compare two years’ questions. The change is the finding.",
    "A household schedule filled by a neighbour because someone was ‘away on Country’ is a quality footnote."],
  ["vx-h-hansard", "Sources & museums", "Hansard is a script of the factory floor of law",
    "What was sayable in the chamber, interruptions, later corrections. It is not a recording of the nation. Lobbyists are off-mic.",
    "If a minister said it, it happened in the country that afternoon.",
    "Use Hansard for intended meanings and for insults. Then the Act as passed, which can differ.",
    "A 1901 White Australia speech is a source about parliament, not a survey of every voter."],
  ["vx-h-newspaper-public", "Sources & museums", "A newspaper made a public with ads and enemies",
    "Owners, wire services, ‘letters to the editor’ as a curated crowd. A 1916 conscription paper is a campaign, not a weather report.",
    "Old papers are truth because they are yellow. Ageing is a method.",
    "Name the paper’s politics, the page (news vs comment), and the ads as a second text.",
    "A classifieds page can tell you rents and jobs when the leader is a sermon."],
  ["vx-h-object-biography", "Sources & museums", "An object has a biography: make, use, discard, display",
    "A possum-skin cloak, a convict love token, a plastic bag in a time capsule. The museum moment is one chapter.",
    "Things do not have history. Only kings do. Objects are mute.",
    "Write the chapters you can evidence. Then the missing use-life.",
    "A ‘contact’ metal tool on Country is a document of trade and of theft. The wear pattern is a sentence."],
  ["vx-h-living-history", "Sources & museums", "Re-enactment is an argument in costume, with a safety briefing",
    "What they will not re-enact (massacre, disease) is a choice. Authenticity is a spectrum from thread to feeling.",
    "If the musket smokes it is 1804 again. Smoke is a time machine.",
    "Treat the event as a source about now: who volunteers, who watches, who is invited to speak.",
    "A ‘pioneer village’ that starts in 1835 with no Aboriginal people is a thesis in buildings."],
  ["vx-h-archive-access", "Sources & museums", "Access rules are a politics: closed files, cultural protocols, paywalls",
    "Fifty-year rules, still-in-use personal data, men’s/women’s business restrictions. ‘Open’ is not the only ethical good.",
    "Everything should be online because sunlight. Protocols are bureaucracy.",
    "State why a file is closed. Then what you can ethically use. Do not scrape a sacred image because the JPEG loaded.",
    "A researcher’s ethics form is a 21st-century source about how we now handle the 19th."],
  ["vx-h-family-history", "Sources & museums", "Family history is a method with a missing persons problem",
    "BDM indexes, shipping, and the relative who was institutionalised and dropped from the story. Pride edits trees.",
    "Your grandmother’s story is the national story if she is yours. Scale is love.",
    "Corroborate oral with certificates. Then sit with the silence (adoption, shame, Stolen Generations).",
    "A DNA kit is a commercial source about the present, not a 1788 passenger list. Use it as such."],
  ["vx-h-war-memorial", "Sources & museums", "A local cenotaph is a list with a politics of whose names fit",
    "Empire wars, Frontier Wars usually absent, later plaques for later wars. The silence can be the loudest line.",
    "If they died for us the list is complete. Stone is a census of honour.",
    "Count names, wars, and who is not there. Then Anzac Day as a ritual source around the stone.",
    "A 1920s memorial and a 2020s Frontier Wars ceremony at the same park are a palimpsest. Read both."],
  ["vx-h-tv-memory", "Sources & museums", "A miniseries is a 1980s argument about the 1940s",
    "Costume, casting, and what the ratings allowed. Useful for memory, slippery for tactics on a beach.",
    "If my pop said the show was accurate, it is a primary source for 1942.",
    "Date the production. Then what archives they used and what they invented for plot.",
    "The Dismissal (1983) on TV is a source about 1983 as much as 1975. Two dates on the citation."],
  ["vx-h-cold-war-au", "Twentieth century extras", "Australia’s Cold War was alliance, uranium, and a referendum that failed",
    "ANZUS, Korean War, Petrov, 1951 anti-communist referendum loss, later Vietnam. It was not only ‘somewhere else’.",
    "The Cold War skipped the southern hemisphere because it was cold up north.",
    "Track US/UK alignment, domestic surveillance, and resource exports. Then the Labor split as a local fracture.",
    "A school ‘duck and cover’ drill, if it happened here, is a source about imported fear. Check if it actually did in that town."],
  ["vx-h-postwar-migrate", "Twentieth century extras", "Postwar migration was a labour plan with a ‘populate’ slogan",
    "Displaced Persons, then assisted British, then broader Europe, then the White Australia unwind. Hostels, bone-graft jobs, and new suburbs.",
    "Multiculturalism started in 1788 as a policy name. We always said the word.",
    "Periodise intakes. Then the dictation test’s death (1958) as a legal hinge, not a feeling.",
    "A migrant hostel photo is a source about class and welcome both. Nissen huts are artefacts."],
  ["vx-h-equal-pay", "Twentieth century extras", "Equal pay decisions were staged, not a single 1970s sunrise",
    "Harvester 1907 as a male breadwinner logic, 1969 and 1972 equal pay cases, then the gap that stayed. Law vs pay packet.",
    "When a court said equal, the pay slips matched that afternoon.",
    "Read the case names, who was excluded (race, occupation), and later superannuation as a cousin gap.",
    "A women’s strike in a factory is a source that can precede the case. Sequence them."],
  ["vx-h-whitlam-program", "Twentieth century extras", "Whitlam’s program was a stacked reform with a short clock",
    "Medibank, no-fee unis, China trip, family law, some land rights. Inflation, loans affair, 1975. Do not reduce to the sacking only.",
    "Everything good in Australia was Whitlam; everything bad was Fraser. Teams.",
    "Pick two reforms and one constraint (Senate, money, time). Then the later Hawke/Keating unwind or keep.",
    "A Medibank card is an artefact of a health politics. Private insurance is the sequel source."],
  ["vx-h-hawke-keating", "Twentieth century extras", "Hawke–Keating opened the economy and remade Labor’s kit",
    "Float the dollar, tariff cuts, enterprise bargaining, Mabo-era politics, compulsory super. Winners and regions that lost factories.",
    "The 1980s were only shoulder pads and the America’s Cup. Economy is a mood.",
    "Name a market reform and a social trade (Medicare kept, Accords). Then a town that deindustrialised.",
    "A closed textile mill in 1992 is a source about a tariff. A super statement is a source about the same government family."],
  ["vx-h-hanson-1996", "Twentieth century extras", "Hanson 1996 was a media and electoral shock with older roots",
    "One Nation, race and immigration talk, Howard’s response. It did not invent Australian racism; it branded a moment.",
    "Before 1996 nobody had a racial politics. The 90s invented it.",
    "Read the maiden speech as a text, then the older White Australia leftovers, then the later digital sequel.",
    "A talkback tape is a source. So is a One Nation how-to-vote in a regional booth."],
  ["vx-h-tampa-2001", "Twentieth century extras", "Tampa 2001 was a ship, an election, and a legal improvisation",
    "Rescue, SAS board, Pacific Solution. Border politics as a campaign. People on the boat are the centre, not a prop — and were treated as a prop.",
    "Borders are natural like reefs. Ships cannot make history.",
    "Sequence the rescue, the legislation, and the election. Then later Nauru/Manus as a system.",
    "A press conference about ‘we decide’ is a source about sovereignty talk. A refugee testimony is a source about the same week."],
  ["vx-h-digital-1990s", "Twentieth century extras", "The 1990s internet in Australia was expensive, slow, and a new public",
    "Dial-up, ISPs, and the first online news. Not yet the feed. Institutions still on paper.",
    "The internet arrived fully formed in 2007 with a phone. Before that, no digital history.",
    "Date the access (university vs home), then what publics formed (forums, email lists).",
    "A printed Telstra bill with 40 hours of downloads is an artefact of scarcity. Scarcity shaped behaviour."],
  ["vx-h-freedom-ride", "Australia extras", "The 1965 Freedom Ride was a bus, a pool, and a camera",
    "Charles Perkins and SAFA students confronted NSW country colour bars. It is not ‘the moment racism was discovered’. It is a media-era tactic.",
    "Once the bus left, segregation was over. Television is a solvent.",
    "Use footage as a source about 1965 publics, then local Aboriginal testimony as the longer file.",
    "A Moree pool photograph is an artefact of a rule, not of a swimming carnival."],
  ["vx-h-kokoda-memory", "Australia extras", "Kokoda is a campaign and a later pilgrimage industry",
    "1942, terrain, militia and AIF, a Japanese operational limit. The track as national myth is a 1990s–2000s boom as well as a 1942 file.",
    "If it is sacred now it was experienced as sacred then by every private. Memory is the event.",
    "Separate operational history from Anzac branding. Then Papua New Guinean carriers as agents, not scenery.",
    "A ‘fuzzy wuzzy angel’ label is a source about Australian memory, often not a name."],
  ["vx-h-bringing-home", "Australia extras", "Bringing Them Home 1997 is a report that named a practice",
    "Stolen Generations evidence, recommendations, and a politics of ‘genocide’ as a word. The report is a source about the 1990s as well as the removals.",
    "A report fixes the past. Numbered recommendations are a time machine.",
    "Read a testimony excerpt as oral history, then the government’s response as a second source.",
    "The later Apology cites this file. Citation is a chain, not a replacement."],
  ["vx-h-holocaust-machine", "World stories", "The Holocaust was a bureaucratic killing machine, not a mood of ‘war is hell’",
    "Legal exclusion, ghettos, Einsatzgruppen, camps, railways. Unique in combination, comparable in using modern state tools. Do not flatten it into ‘all civilian deaths’.",
    "In wars everyone suffers equally. Numbers are a drawing.",
    "Use perpetrator documents and survivor testimony as different source types. Then local collaborators as a European map.",
    "Australian responses (refugees refused, later remembrance) are a reception history. Date them."],
  ["vx-h-bandung-1955", "World stories", "Bandung 1955 was a newly independent club with a communiqué",
    "Asian–African conference, non-alignment’s stage, a challenge to a two-bloc map. Not a cuddle: states had interests.",
    "The Third World was a waiting room for NATO or Moscow. No third script existed.",
    "Read the communiqué’s language, then who was invited and who was not. Then later NAM fractures.",
    "Australia watched as an ally of empires. That watching is a source about our map of Asia."],
  ["vx-h-arbitration", "Rights & everyday", "Compulsory arbitration was a court for wages, a distinctive Australian machine",
    "Harvester, awards, a ‘new province for law and order’ (Higgins). Later enterprise bargaining rewired it. Not ‘the free market with extra forms’.",
    "Wages were always a handshake in a pub. Courts are European cosplay.",
    "Use an award document as a source of hours, margins, and who was classified out.",
    "A metal trades award and a domestic worker’s exclusion can sit in one year. Guest lists again."],
  ["vx-h-medicare-83", "Rights & everyday", "Medicare is a 1984 rebuild of a health-funding fight",
    "Medibank to Medicare, bulk-billing as a practice, private insurance as a parallel. It is a levy plus a politics, not ‘free doctors from the sky’.",
    "Once invented, health was free and finished. Cards close history.",
    "Track the levy, the schedule fee, and the later gap. Then a GP bulk-bill rate as a present source about the past design.",
    "A paper Medicare card in a wallet is an artefact of a Whitlam–Hawke sequence."],
  ["vx-h-port-arthur-gun", "Twentieth century extras", "Port Arthur 1996 was a massacre that rewired gun law",
    "National Firearms Agreement, buyback, a rare cooperative federalism. Grief plus a Prime Minister’s window. Not a complete vanishing of guns.",
    "Australia had no guns before 1996, then had none after. Two zeroes.",
    "Read the agreement as a legal source, then remaining licences as the limit of the story.",
    "A melted firearm in a buyback photo is an artefact. So is a later ‘not all guns’ lobby flyer."],
  ["vx-h-gst-2000", "Twentieth century extras", "GST 2000 was a tax mix shift with a compensating story",
    "Howard–Lees deal, 10%, food fights, and a new invoice culture. Not a tiny surcharge on snacks only.",
    "GST is just a shop sticker. History does not happen at the till.",
    "Use the legislation, a compensation package, and a small-business BAS as three sources.",
    "A ‘GST included’ menu from 2000 is a material culture of a tax. Keep one if you teach this."],
  ["vx-h-olympics-2000", "Twentieth century extras", "Sydney 2000 was a festival with a bill and a reconciliation performance",
    "Infrastructure, Cathy Freeman’s lap, and debates about whose land the flame crossed. Mega-events are policy plus TV.",
    "If the opening ceremony was moving, the politics were solved. Fireworks are treaties.",
    "Separate bid promises, budget, and Indigenous symbolism as a designed moment. Then the leftover stadiums.",
    "A souvenir torch replica is a commodity. Freeman’s win is also a source about national wanting."],
  ["vx-h-gfc-australia", "Twentieth century extras", "The GFC here was a stimulus and a mining buffer, not a US sequel copy-paste",
    "2008–09, bank guarantees, BER school halls, China demand. Unemployment rose less than some peers. ‘We avoided it’ is a boast with footnotes.",
    "Australia does not have economic history after 1991 because we are lucky. Luck is a policy.",
    "Read a stimulus program, a job number, and a town that still lost shifts. Then the later debt argument.",
    "A ‘Building the Education Revolution’ plaque on a hall is an artefact of a crisis toolkit."],
  ["vx-h-un-founding", "World stories", "The UN 1945 was a winners’ club with a speech about peace",
    "Charter, Security Council veto, Evatt’s small-power push. It did not abolish empire. Trusteeship was a word with colonies inside.",
    "The UN is a world government that started on time. Flags did the work.",
    "Read the veto as a design, then a decolonisation file as a later use. Then Australia’s role as both idealist and imperial leftover.",
    "A 1945 San Francisco photo of delegates is a source about who was allowed to found ‘the world’."],
]);
