import { pack } from "../pack.mjs";

export const LANGUAGES_VOLUME = pack("languages", [
  ["vx-l-productivity", "How language extras", "Productivity is why a handful of sounds can name a universe you have not seen yet",
    "You can make a new sentence tomorrow. Bees’ dance is impressive and still not this. A phrasebook is a map of a few streets, not the city.",
    "If I memorise 50 nouns I speak the language. Grammar is extra. New sentences are just the 50 in a blender.",
    "Build a sentence you have never heard, about a thing in the room. Then a hypothetical about Thursday. That is the trick.",
    "A brand name that becomes a verb (to google) is productivity with a lawyer attached."],
  ["vx-l-duality-bits", "How language extras", "Phonemes are not meaning; morphemes start to be — that is duality of patterning",
    "Small sounds combine into many words. That is why a language is not a unique noise per idea. Brunch is a Saturday of the same machine.",
    "Each idea has its own unique noise, unrelated to other noises. That would be efficient.",
    "Split un-happi-ness. Swap a bit. That is morphology class in one line.",
    "A blend and a acronym are productivity having a weekend. The weekday is still phoneme plus morpheme."],
  ["vx-l-arbitrariness-rose", "How language extras", "The sound-to-meaning link is mostly a social deal, not a onomatopoeia religion",
    "Dog, chien, 犬. A rose by any other name is the point. Onomatopoeia is the exception people over-love. A brand that sounds ‘fast’ in English might sound like a snack elsewhere.",
    "Words sound like what they mean. Heavy is a heavy word. That is why language is easy.",
    "Compare two languages’ word for the same thing. Then a false friend. Then a onomatopoeia that still differs (a rooster’s noise).",
    "A ‘it just sounds right’ about a made-up product name is a ear trained by English, not physics."],
  ["vx-l-displacement-lie", "How language extras", "Displacement lets you talk about not-here; lying is a dark twin of the same trick",
    "Yesterday, a myth, a plan. A rumour is displacement plus a social virus. Animals do bits; humans go feral with it.",
    "Language only names what is in front of your face. That is honesty. Also: if it is not here it is not language.",
    "Tell a past. Then a hypothetical. Then a lie you label as a example. You just did a human stack.",
    "A alibi is displacement with a lawyer. A myth is displacement with a community."],
  ["vx-l-pidgin-to-creole", "How language extras", "A pidgin is a contact toolkit; a creole is that toolkit with kids as native speakers",
    "Nativisation is the childhood rush. Haitian Creole is a language. Tok Pisin is a national story. ‘Broken English’ is a prejudice with a army-and-navy joke behind it.",
    "Creole means sloppy. Real languages have navies. Status is physics.",
    "If it has kids as native speakers and a grammar, it is a language. Then a classroom target variety as a power, not a physics.",
    "A school that treats a creole as a error pile is a gate. Name it a gate."],
  ["vx-l-standard-is-dialect", "How language extras", "Standard is a dialect with a school and a job market, not a dialect-free air",
    "Every speaker has a variety. Aboriginal English has rules. A Queensland drawl has rules. AAPMB has rules. A test that only honours one is a gate.",
    "If it is not in the textbook it is wrong. Always correct it out of people. Kindness is a red pen.",
    "Describe a rule of a variety without sneering. Then when to codeswitch for a job — that is power, not correctness-as-physics.",
    "A ‘talk properly’ at the shops can be a safety advice and a class weapon. Split the files."],
  ["vx-l-codeswitch", "How language extras", "Codeswitching is a skill with an audience map, not a confusion of a broken brain",
    "A sentence that changes jackets. Bilinguals do it on purpose. A teacher who panics at a mix can miss a pragmatic win. A exam still wants a target variety — name the gate.",
    "Two languages will break a child. Mixing is the break. Pick the useful one.",
    "Record a family conversation (with consent). Mark the switches. Ask what the switch did (joke, a precision, a solidarity).",
    "A ‘heritage speaker’ who understands and will not speak is a tender profile. A switch can be a door back."],
  ["vx-l-lingua-franca-tilt", "How language extras", "A lingua franca is a bridge with a power tilt; native speakers can be the worst at accommodating",
    "English now, French in a court, Swahili in a region. ELF has its own pragmatics. Slow down, drop the idioms, check back.",
    "The bridge language is neutral. Nobody is at a disadvantage. Cute. Also: if you are native you are the teacher of everyone in the room.",
    "In a mixed group, one idea per sentence. Then a check-back. Then a interpreter budget if it is a conference, not a vibe of ‘they’ll cope’.",
    "A conference in English in a non-English city is a cost on someone. Native speed is a tax."],
  ["vx-l-world-englishes", "How language extras", "Englishes, plural: a ‘wrong’ that is a local right still meets a exam gate",
    "Singapore, India, Nigeria, Aboriginal English. Kachru’s circles as a map with holes. A newscast feature that is consistent is not a one-off slip.",
    "There is one English. The exam board’s. The rest is error. Also: anything goes, so skip the board. Two cop-outs.",
    "Listen to a newscast from another English. List a stable feature. Then what the local marker wants anyway.",
    "A marker who only honours RP is a gate. You may still need the gate. Name it."],
  ["vx-l-gender-bin", "How language extras", "Grammatical gender is a noun bin, not a biology lesson glued to a chair",
    "A table can be feminine. Learn the article with the noun. Living changes (a non-binary pronoun fight) are people leading dictionaries. Respect sits beside the bin the language actually uses.",
    "If a language has gender it is sexist in the same way on every street. Done. Also: bins are destiny.",
    "Learn the article with the noun. Do not assign a personality to a chair unless the poem does.",
    "A learner who says ‘the table she’ is doing a transfer. A person who asks for a pronoun is doing a different file. Do not mash."],
  ["vx-l-aspect-shape", "How language extras", "Aspect is the shape of the event, not only a clock hand",
    "Walked versus was walking versus have walked. Slavic and Mandarin mark this in ways English students miss. A ‘when’ can still be incomplete.",
    "Tense is the only time. If it has a past ending it is a finished movie. Always.",
    "Draw a timeline: a dot, a bar, a bar that includes now. Then the sentence. Then a ‘I have gone to Paris in 2010’ as a clash to hunt.",
    "A state verb ‘I am knowing’ is a interlanguage cousin. Aspect and stative fights sit in one paragraph."],
  ["vx-l-article-file", "How language extras", "A/an/the is a tracking system for known versus new, not a sprinkle of importance",
    "The is a pointer: we both know which. A is a new file. Languages without articles do the job with other tools. Learners overuse the.",
    "Put the on everything important. Importance is a the. Also: skip all articles to sound fluent. Two errors.",
    "Ask: new or known? Unique in the room (the sun)? Then skip when English skips (I like cheese).",
    "I kicked the ball versus a ball is a different story about whose ball. Football commentary lives here."],
  ["vx-l-rel-sticker", "How language extras", "A relative clause is a sticker on a noun; some languages glue it before the noun",
    "Who/which/that, a comma that changes extra-info. Japanese can put the sticker first. English learners drop the sticker’s verb or double the object.",
    "Longer sentences are smarter. Stack who-which-that until the reader faints. Also: never use a relative, too fancy.",
    "One sticker per noun until you can juggle. Read aloud. If you gasp, split. Then a ‘the man I saw him’ as a double to kill.",
    "A legal sentence with five stickers is a job, not a personality. Pay the drafter."],
  ["vx-l-svo-habit", "How language extras", "SVO is a habit, not a human default; SOV is a ordinary Tuesday elsewhere",
    "English likes subject-verb-object. Japanese can sit SOV. A question flip in English is a remnant. Word order is grammar you can point at.",
    "All languages put the doer first. That is logic. The rest is decoration. Also: Yoda is the only SOV. Cute.",
    "Write a three-word sentence in a language you study. Mark S, V, O. Then a question. Then a scramble that the case language can survive and English cannot.",
    "A ‘time-manner-place’ habit in one language versus another is a word-order cousin. Textbooks that skip it create a polite mess."],
  ["vx-l-case-sticker", "How language extras", "Case is a sticker for a job in the sentence; English mostly spent it on pronouns",
    "Nominative/accusative, a German der/den. When case is rich, order can relax. Between you and I is a hypercorrection of a muscle we barely train.",
    "If the word order is SVO you do not need case. Ever. Also: him is just a sound, never a job.",
    "Swap two nouns in a case language and see if the meaning holds. Then in English (it often flips). Then he/him without a vibe of posh.",
    "A Latin leftover in who/whom is a trap for a newsletter. Whom is a tool, not a personality."],
  ["vx-l-classifier-hat", "How language extras", "A classifier is a counting hat for a kind of thing; English has a few and hides them",
    "Mandarin 本 for books, 条 for long thin. A loaf of, a sheet of. You cannot skip the hat in languages that require it. Three bread is a learner who skipped our hat too.",
    "A number plus a noun is universal. Hats are extra cute. Skip them.",
    "Learn five high-frequency hats in the language you study. Stick them to the nouns. Then a English hat you also skip (cattle, police as a different mess).",
    "A coffee ‘one cup’ versus ‘one coffee’ is a hat fight in a café. Baristas already knew."],
  ["vx-l-minimal-pair", "Sounds extras", "A phoneme is a difference that makes a word difference; your ear is a trained filter",
    "Ship/sheep, bit/pit. /l/ versus /r/ is a famous training story, not a mouth failure. Aspirated p in pin versus spin is a fact many speakers never notice.",
    "If I cannot hear it, it is not a real sound. My language is the human default. Also: if I can write it with English letters it is the same sound.",
    "Find a pair in English. Then a pair you struggle with in a language you are learning. Train that pair with a recording, not a vibe.",
    "A teacher who only says ‘listen harder’ without a pair is a coach without a drill."],
  ["vx-l-ipa-map", "Sounds extras", "IPA is a map of mouths; English spelling is a tourist brochure with lies",
    "One symbol, a sound, in principle. Schwa is the star of unstressed English. A dictionary’s IPA line is a gift. Ignore it and you are guessing.",
    "English letters are international. IPA is extra nerd. Also: IPA is a font, not a mouth.",
    "Transcribe your name. Then a word with th. Feel the mouth. Then a schwa in a function word you swallow.",
    "A spelling bee is an English-specific sport. It is not a general intelligence test, and IPA would ruin the sport."],
  ["vx-l-stress-word", "Sounds extras", "English stress can invent a new word; tone languages invent a new word with pitch as a letter",
    "REcord versus reCORD. Mandarin tone is not sing-songy English. Japanese pitch accent is another system — do not mash it into ‘like Chinese’.",
    "Volume is the only emphasis. Tone languages are just English with a melody plugin.",
    "Mark stress on ten English words. If you study a tone language, treat tone as a letter, not a hat. Humble on ‘mother’ versus a swear.",
    "A pitch error can be a social spill before it is a exam mark. Record, do not only read."],
  ["vx-l-syllable-repair", "Sounds extras", "A loanword will get rebuilt to fit the syllable habit of the house",
    "Onset, nucleus, coda. Japanese likes a CV rhythm; English stacks consonants. McDonald’s as a famous repair. Strengths is a English flex.",
    "Syllables are just the vowels. Consonants do not count. Also: every language allows strengths. Universal.",
    "Clap a word. Then a cluster. Count honestly. Then a loan into a CV language and watch the extra vowels appear.",
    "Haiku in English versus mora in Japanese is a tourist fight. Do not be the tourist."],
  ["vx-l-connected-gonna", "Sounds extras", "Fast speech eats sounds; the page did not warn you",
    "Gonna, linking r, a dropped t. Slow is a skill; fast is a different skill. A mondegreen is your brain forcing English words it already owns onto a song.",
    "If they ate a sound they are uneducated. Always. Also: if it is not on the page it is not the language.",
    "Transcribe a slow then a fast sentence. Note the corpses of consonants. Then a song lyric you misheard.",
    "A learner who only knows the page will not hear a station announcement. Stations are connected speech with a PA."],
  ["vx-l-schwa-reduce", "Sounds extras", "Unstressed English collapses toward schwa; saying every vowel ‘clearly’ can sound foreign and also kind",
    "Photograph as a stress shift with a schwa. Function words reduce. A newsreader over-enunciating is a register. A learner keeping full vowels in every syllable is a different accent, not a moral.",
    "Proper English says every letter. Spelling is a mouth. Also: reduce everything into mush to sound native by Friday.",
    "Mark the stressed syllable. Reduce the neighbour. Record. Then a careful slow version for a classroom, on purpose.",
    "A public-speaking ‘clear’ that re-inflates schwa is a register, not a IPA fail. Name the job."],
  ["vx-l-voice-onset", "Sounds extras", "VOT is why a English p and a French p are not the same stop even if the letter is",
    "Aspiration after a English voiceless stop at the start of a stressed syllable. A learner’s ‘unaspirated p’ can sound like b to a English ear. This is milliseconds, not laziness.",
    "P is p. Letters are sounds. If it is the same letter it is the same mouth.",
    "Hold a page in front of the lips for pin versus bin. Then a language with a different VOT. Then do not mock the millisecond.",
    "A ‘they cannot say p’ folk tale is often a VOT mismatch plus a racism. Train the pair."],
  ["vx-l-nasal-place", "Sounds extras", "English has three nasal places; a language may have more, or a vowel nasalisation instead",
    "M, n, ŋ (sing). A n before a k often becomes ŋ in haste (income). French vowel nasalisation is a different tool. Learners add a ghost n.",
    "Ng is n plus g always. Singg. Also: ng cannot start a word so it is fake. Vietnamese would like a word.",
    "Feel the tongue for n versus ŋ. Then a word that spells ng and actually has a g (finger) versus not (singer).",
    "A singer/finger pair is a morphology of a suffix, not a random. Finger is older guts."],
  ["vx-l-th-family", "Sounds extras", "English th is two sounds; many languages have zero, and a substitution is a system, not a joke",
    "Think versus this (θ versus ð). Replacing with t/d or s/z or f/v is a map of a L1. Mocking it is a cheap sport. A dental stop is a neighbour, not a fail of trying.",
    "If they cannot do th they are not trying. My tongue is the human default. Also: th is posh, skip it.",
    "Put the tongue on the teeth. Voice on and off. Then accept a accent that substitutes while you train, without a roast.",
    "Australian English th-fronting in some speakers is a change in progress, not a Year 3 error only."],
  ["vx-l-intone-tune", "Sounds extras", "Intonation is a tune with a grammar; a rising statement can be a question or a list or a Valley-ish habit",
    "Fall for a finish in many English statements. Rise for a yes-no. A high rise terminal is a researched Australian/NZ file, not only a ‘unsure girl’ meme. The meme is a sexism.",
    "If they go up at the end they are unsure. Always. Science of a sitcom.",
    "Record a question, a list, a statement. Draw the pitch. Then a HRT that is a solidarity, not a question.",
    "A teacher who trains ‘always go down to sound confident’ is flattening a dialect. Confidence is not a fall."],
  ["vx-l-auslan-space", "Sounds extras", "Auslan is a language in space; fingerspelling is a bridge, not the language",
    "Its own grammar, a Deaf culture, regional variation. Interpreters are professionals. A caption is not an interpreter. Access is both sometimes.",
    "Sign is mime. Anyone can fake it for a video. Also: it is just broken English on the hands.",
    "Learn a greeting from a proper source. Do not invent a ‘sign name’ as a joke. Eye contact and a visual room. Do not stand in the light as a silhouette joke.",
    "A school that only teaches the alphabet in ‘sign’ taught a bridge and called it a language. Name the gap."],
  ["vx-l-prosody-chunk", "Sounds extras", "Chunking and stress-timing are how English can sound like a machine gun to a syllable-timed ear",
    "Content words take stress; function words duck. A learner who stresses every word is intelligible and exhausting. A poem’s metre is a cousin, not the same job.",
    "Every syllable equal is clearer, so it is better English. Also: mumble to sound native. Two bad coaches.",
    "Clap only the content words in a sentence. Then a syllable-timed language you study and clap every beat. Feel the different clocks.",
    "A PA announcement that stresses function words is a robot. Robots are a register."],
  ["vx-l-allophone", "Sounds extras", "An allophone is a variant that does not change the word; dark l versus light l is a English pair",
    "Feel versus lull. Aspirated versus not. Learners who over-pronounce a dark l everywhere still get understood and still sound like a textbook. Phonemes are the difference that matters for meaning.",
    "If it sounds different it is a different letter. Always. Also: variants are sloppy.",
    "Say leap versus peel slowly. Feel the tongue. Then a language that contrasts them as phonemes — humility.",
    "A spelling that uses one l for both is why English speakers never notice until a class. Spelling hid the mouth."],
  ["vx-l-liaison", "Sounds extras", "Liaison and a linking r are glue between words, not extra letters you invented",
    "Law and order with a r for some English speakers. French liaison is a grammar of a register. A learner who never links sounds like a list of dictionary citations.",
    "If it is not written, do not say it. Spelling is a audio. Also: always add r everywhere because it sounds posh.",
    "Mark a linking r in a sentence you actually say. Then a French liaison that is required versus a optional. Then do not mix the systems.",
    "A non-rhotic Australian linking r is a real glue. Rhotic imports from US media are a different glue."],
  ["vx-l-tone-letter", "Sounds extras", "In a tone language, pitch is a letter; treating it as a mood is how you invent a swear",
    "A contour versus a level. Sandhi can change a tone next to another. Humble. A textbook that prints tone marks you then ignore is a decoration you will pay for.",
    "Tone is optional decoration, like italics. Also: tone languages are just angry or sing-song. Two racisms.",
    "Treat the mark as a letter. Minimal pairs. A teacher who is a speaker, not only a app that guesses.",
    "A ‘mother’ pair in a class is a warning, not a joke to perform at lunch."],
  ["vx-l-alphabet-lie", "Scripts extras", "An alphabet is roughly phoneme-to-letter, with a lie rate; English’s lie rate is high",
    "Ough. Finnish’s rate is low. A spelling reform is a political bomb. A spelling bee is a sport of the lie rate.",
    "Once you know the alphabet you can read any word first try. That is the deal. Also: spelling is intelligence.",
    "Learn a regular language’s spelling to feel the difference. Then forgive English a bit, not entirely. Then a dictionary, not a vibe.",
    "A ‘English is random’ shrug skips history (Great Vowel Shift, a loan pile). Random is a feeling; etymology is a map."],
  ["vx-l-abjad-vowels", "Scripts extras", "An abjad leans on consonants; vowels can be optional marks a beginner still needs",
    "Arabic, Hebrew as typical stories. Context fills. A Qur’an edition with extra marks is a kindness. Adding ‘our vowels to help them’ is a colonial hobby.",
    "If the vowels are missing the language is incomplete. Also: marks are for children so adults who use them are failing.",
    "See a word with and without vowel marks. Feel the load on the reader. Then a beginner text that keeps the marks on purpose.",
    "A name on a form without vowels is a different load from a news sentence. Load is the subject."],
  ["vx-l-abugida-tick", "Scripts extras", "An abugida is a consonant with a default vowel plus ticks; a killer mark deletes the vowel",
    "Devanagari as a classroom example. It is not ‘an alphabet with decorations’. Tamil versus Devanagari is a respect, not a mash.",
    "All Indian scripts are the same as English plus extra curls. Squint. Also: they are pictograms.",
    "Copy one akshara. Then change the vowel tick. That is the unit. Then a virama.",
    "A keyboard that types a conjunct badly is a software boss fight, not a proof the script is ‘too hard’."],
  ["vx-l-syllabary-kana", "Scripts extras", "A syllabary has a symbol per syllable-ish; kana is the friendly example, kanji is the other half of that house",
    "Cherokee has a syllabary with a history of invention. Calling Japanese ‘pictograms’ is a tourist fail. A symbol per idea is not a syllabary.",
    "A symbol per idea is a syllabary. That is also what kanji is. Same thing. Also: kana is a alphabet.",
    "Write a word in hiragana as a chain of beats. Feel why McDonald needs extra vowels. Then a kanji that carries a morpheme.",
    "A learner who only knows romaji is in a foyer. The foyer is allowed for a week, not a year."],
  ["vx-l-logograph-radical", "Scripts extras", "A character can carry a morpheme more than a sound; phonetic components still hide inside many",
    "It is not a drawing of a sheep every time. A radical is a filing cabinet, not a comic. A ‘fire’ radical in a word that is not fire is a history.",
    "Every character is a tiny picture of the thing. Read by looking at the art. Also: no phonetic hints exist, it is pure magic.",
    "Learn a radical as a cabinet. Then a phonetic hint. Then a word where both lie to you — humility.",
    "A tattoo of a ‘wrong character’ is this path with a needle. Second dictionary, then a human."],
  ["vx-l-bidi-text", "Scripts extras", "RTL plus a number is a bidirectional boss fight; a web page that breaks it is a bug",
    "LTR, RTL, boustrophedon in history, vertical newspaper habits. A back button of your brain. Numbers in an Arabic sentence can still run LTR.",
    "Left to right is natural because time goes that way. Clocks proved it. Also: computers cannot do RTL so skip those languages.",
    "Open a RTL page. Design a slide that does not smash it. Then a name field that stores the string correctly, not as a screenshot.",
    "A PDF that is a photo of Arabic is a wall for a search and a screen reader. Real text."],
  ["vx-l-script-reform", "Scripts extras", "A script reform is a political bomb: literacy can jump and a past can feel cut",
    "Turkey’s alphabet, Vietnamese quốc ngữ, simplified characters. Neither is ‘just fonts’. A classroom that still teaches the old form is a politics too.",
    "Pick the easiest letters. Culture will follow. Easy is the only civic value. Also: never change a letter, ever.",
    "Read one reform’s winners and mourners. Then a keyboard layout as a script politics you feel in your thumbs.",
    "A simplified/traditional choice in a diaspora Saturday school is a identity file, not a font menu only."],
  ["vx-l-romaji-foyer", "Scripts extras", "Romanisation is a foyer map; it is not the house, and systems disagree",
    "Pinyin, Hepburn, a McCune–Reischauer. Tone marks you drop. A learner who stays in the foyer cannot read a street. A linguist’s romanisation is a different job from a passport.",
    "If I can type it in English letters I can read the language. Also: romanisation is fake, never use it even as a bridge.",
    "Learn the foyer for pronunciation, then leave. Check which system a textbook used before you mix a Wikipedia name with a library catalogue.",
    "A passport romanisation that murdered a vowel is a bureaucracy, not a IPA. Do not learn pronunciation from a passport only."],
  ["vx-l-punctuation-conv", "Scripts extras", "Punctuation is a convention with a history; a inverted question mark is not a cute extra",
    "Chinese full stops, a Japanese period, quotation marks that differ, a lack of spaces in a script that uses other chunking. A English comma lecture does not travel as physics.",
    "Everyone uses our quotes and spaces. Civilisation is a spacebar. Also: punctuation is optional in every language because chat exists.",
    "Copy a sentence in the script you study, punctuation included. Then a chat register that drops it — as a register, not as the language.",
    "A legal translation that ‘fixes’ punctuation into English habits can change a condition. Pay people."],
  ["vx-l-orthography-depth", "Scripts extras", "Orthographic depth is how much the spelling hides the sound; shallow is not ‘more primitive’",
    "Finnish shallow, English deep. A dyslexia profile can interact with depth. A spelling reform bargain is always a loser somewhere (etymology, a dialect).",
    "Deep orthography means a smarter culture. Also: shallow means a language for children. Two racisms.",
    "Compare a regular spelling language with English on a timed read-aloud. Then humility about ‘they learn to read faster’ as a orthography, not a IQ.",
    "A English invented-spelling in Year 1 can be a developmental path. A adult public sign with the same is a different file."],
  ["vx-l-hanzi-borrow", "Scripts extras", "Characters travelled; Japanese kanji, Korean hanja, a Vietnamese history are not ‘Chinese but worse’",
    "Borrowing a script is a ordinary empire-and-neighbour story. Local readings, a simplification, a later hangul as a designed alphabet. Respect the local system.",
    "If they use characters they are basically Chinese. Squint. Also: hangul is a font of kanji.",
    "Pick one borrowing. Name what changed (a reading, a simplification, a replacement). Then a nationalist fight about the script as a civic, not a linguistics only.",
    "A restaurant font that mashes three scripts as ‘Asian flavour’ is a design fail and a languages fail."],
  ["vx-l-cursive-join", "Scripts extras", "A joined hand can be a different visual from the printed letter; learners who only know print bounce off a menu",
    "Arabic joining, a English cursive that schools dropped, a Japanese sodoku. A font is not a hand. A signature is a legal object with a visual.",
    "If I know the print I can read everything. Menus are print. Also: cursive is the only real writing.",
    "Read a handwritten note in the language you study. Then a printed version. List the corpses of joins.",
    "A doctor’s hand is a stereotype. A form that requires ‘block letters’ exists because of this path."],
  ["vx-l-emoji-not-script", "Scripts extras", "Emoji are a extra channel, not a writing system that replaced grammar",
    "A sequence can be a dialect of a platform. Searchability dies. Tone is a pragmatic. A legal contract in emoji is a joke with a invoice attached.",
    "Emoji is a universal language. UN should use it. Also: emoji is rotting the young. Two panics.",
    "Translate a emoji-only message into a clause. See the forks of meaning. Then a punctuation that did a similar job (a ?).",
    "A court that admitted a emoji as a threat is a pragmatics class. Context still sits on the bench."],
  ["vx-l-calligraphy-art", "Scripts extras", "Calligraphy is a art of a script; it is not ‘the language’ and not a font you downloaded",
    "A brush, a reed, a proportion. Islamic, East Asian, a Western italic — different ethics of the line. A tattoo in a script you cannot read is this hub’s needle warning again.",
    "Fancy letters are the culture. If it looks old it is authentic. Also: calligraphy is elitist so skip form.",
    "Copy one stroke family from a proper source. Then a digital font that is a costume. Then do not hang the costume as a mastered language.",
    "A café chalkboard in fake Arabic-shaped squiggles is a design of othering. Draw real letters or do not."],
  ["vx-l-false-friend-gift", "Meaning extras", "A false friend is a trap with a smile; gift in German is poison",
    "Preservative in a Romance language can be a condom story. Sympathetic versus sympathique is a social spill. Dictionaries exist.",
    "If it looks like English it is a free mark in the exam. Always. Also: never trust a cognate, burn them all.",
    "Keep a list of the mean ones in your language. Do not guess in a pharmacy. Then a second dictionary.",
    "A ‘I am embarrassed’ versus embarazada is a clinic story. Clinics are why this path exists."],
  ["vx-l-loan-suitcase", "Meaning extras", "A loanword is a suitcase that gets relabelled; handy in German is not our handy",
    "Café, tsunami, kangaroo (a messy etymology). Chai tea as a tautology to some ears. Loans stack. Citation still exists as a ethics even when the word has settled.",
    "If we borrowed it, we own the original culture now. No citation. Also: never borrow, keep the language pure. Two nationalisms.",
    "Trace one word. Then a false friend. Then a calque (skyscraper to gratte-ciel). Then a kangaroo as a warning about folk etymology.",
    "A menu that ‘corrects’ a loan back to a English word can sound like a lecture. Service is a register."],
  ["vx-l-semantic-drift", "Meaning extras", "Meanings drift; nice once meant ignorant-ish and awful was full of awe",
    "A prescriptivist can cry; a historian can take notes. A slur reclamation is a shift with a who-is-allowed, not a free-for-all. Kitchen-meaning-from-childhood is not a court.",
    "Words have one true meaning, the one in my childhood kitchen. Also: words mean whatever I want today. Two voids.",
    "Pick a word, a 200-year jump, a quote. That is a mini research. Then a style guide that froze a sense for a workplace.",
    "A legal word that drifted in the street but not in the act is a civics of meaning. Courts pick a sense."],
  ["vx-l-metaphor-we-live", "Meaning extras", "We live in metaphors we forgot were metaphors; time as money is a rent",
    "Argument as war. A language can prefer a different metaphor (time as a landscape). Lakoff is a door, not a religion. Deadline is a metaphor that can kill a weekend.",
    "Metaphors are for poems. Ordinary talk is literal. Also: every metaphor is a lie so skip them.",
    "List time-is-money talk in a day. Then try to talk about time without it. Hard. Then a different language’s habit if you have one.",
    "A ‘war on’ everything is a metaphor with a budget. The budget is civic. The metaphor is this hub."],
  ["vx-l-calque", "Meaning extras", "A calque is a loan of a structure, not a suitcase of a noun",
    "Skyscraper as a grated sky. Already as a perfect in some contact Englishes. Purists cry. The language lives. A classroom still has a target for a mark.",
    "Grammar cannot be borrowed. Only nouns. That is science. Also: calques are fake English.",
    "Spot a structure that looks like another language’s. Then whether the school wants it in the essay. Then a I am knowing as a state-verb clash.",
    "A ‘it goes without saying’ that is a translation of a French habit can still be English. Frequency is the resident permit."],
  ["vx-l-polysemy", "Meaning extras", "A dictionary line is a cluster of senses; the first translation is a blunt instrument",
    "Bank as money versus river. A bilingual dictionary’s first hit can be a lawsuit. A learner’s dictionary and a corpus show how it sits. Google Translate is a drunk intern.",
    "The first translation is the meaning. Done. Also: words have infinite senses so meaning is fake.",
    "Check an example sentence. Then a second dictionary. Then a human if it is a tattoo or a medical.",
    "A bank of a river in a exam sentence is a trap the writer laid. Context is the subject."],
  ["vx-l-collocation", "Meaning extras", "Collocation is which words actually hold hands; a strong tea is not a powerful tea",
    "Make versus do, a heavy rain. A dictionary that lists a synonym will not save a collocation. Chunks are how fluency feels.",
    "Any synonym is interchangeable. Thesaurus-driven essays prove it. Also: never vary a word.",
    "Collect ten chunks. Use them unedited. Then vary one slot. Then a corpus search if you have one.",
    "A ‘do a mistake’ is a collocation miss, not a intelligence. Frequency drills kill it, not a yell."],
  ["vx-l-connotation", "Meaning extras", "Denotation is the filing cabinet; connotation is the smell",
    "Slim versus skinny versus thin. A thesaurus that ignores smell is a trap. A translation that keeps the cabinet and loses the smell can insult.",
    "If the dictionary definition matches, the word is fine. Always. Also: only connotation matters, definitions are fake.",
    "Pick three near-synonyms. Rank the smell. Then a formal register that wants a dull cabinet.",
    "A real-estate ‘cosy’ is a connotation with a square-metre lie. Cabinets and smells both sell."],
  ["vx-l-untranslatable", "Meaning extras", "Untranslatable often means ‘needs a footnote’, not ‘mystical hole in the human’",
    "A culture word with a pack of habits. A joke, a rhyme, a legal force — you choose the loss. A machine will pick a sense at random when tired.",
    "A word-for-word is the most faithful. Always. Even if it sounds possessed. Also: if it needs a footnote the language is untranslatable and we should not try.",
    "Translate a proverb two ways: literal and sense. Then a third for a poster. Then a legal translation as a different job from a poem.",
    "A ‘they have no word for X’ viral post is often a lie about a paraphrase. Paraphrase is allowed."],
  ["vx-l-speech-act-do", "Meaning extras", "Some sentences do a thing: I promise, I name this ship, I apologise",
    "Conditions can fail (you cannot marry people without a licence). A ‘I apologise if you were offended’ can be a non-apology. A bet is a speech act. So is a I do.",
    "Talking is only describing. Doing is only hands. Also: saying it always makes it so, like magic.",
    "Find a performative in a ceremony. Then a fake one. Then a classroom ‘I promise’ that nobody believed because of a history.",
    "A terms-of-service ‘you agree’ is a speech act with a scroll. Scrolls are a design of consent."],
  ["vx-l-implicature", "Meaning extras", "Can you pass the salt is a request, not a strength test; implicature is the extra meaning",
    "Grice as a door. A literal robot fails dinner. Texting strips tone — hence /s. A family fight’s meant-versus-said is pragmatics, not gossip only.",
    "Words mean what they mean. Context is cheating. Also: everything is implicature so the sentence is fake.",
    "List what was meant versus said in a short dialogue. Then a sarcastic great. Then a legal clause that tries to kill implicature and still fails.",
    "A ‘we should have lunch’ that is not a lunch is a politeness, not a diary event. Learners get stranded."],
  ["vx-l-presuppose", "Meaning extras", "A presupposition sneaks a file in as already true; have you stopped X is a trap",
    "The king of France, a ‘again’, a cleft. Lawyers and journalists hunt them. A question can be a weapon without a swear.",
    "If it is in a question it is neutral. Questions cannot smuggle. Also: everything is a trap so never speak.",
    "Spot the already-true file. Deny it if you need, not only the surface yes/no. Then a headline that presupposed a crime.",
    "A ‘when did you stop cheating’ in a group chat is a courtroom toy. You do not owe the when."],
  ["vx-l-prototype", "Meaning extras", "A bird is a robin before it is a penguin; categories have a best example and a edge",
    "Prototype theory versus a classical checklist. A legal ‘vehicle’ fight is a edge. A learner’s vocab list is often prototypes only, then a exam penguin.",
    "Every member of a category is equal. Dictionaries are checklists of nature. Also: categories are fake so skip words.",
    "Name a prototype, a odd member, a legal edge. Then a translation that picked the prototype and missed the penguin.",
    "A ‘fruit’ that is a tomato in a kitchen and a vegetable in a shop is a category with two bosses. GST has opinions too."],
  ["vx-l-redup-job", "Meaning extras", "Reduplication is a grammar, not a stutter; it can mean plural, intensity, or a sort-of",
    "Malay-style, a bit-bit, a goody-goody English uses more than the textbook admits. Small-small in some Englishes is a real grammar, not a broken volume knob.",
    "Saying it twice is childish. Real grammar says it once. Also: reduplication is only for comic books.",
    "Find a reduplication in a language you study. Name the job. Then a English one you already say.",
    "A ‘very very’ is a intensifier with a register. A grammar of a full redup is a different job. Name it."],
  ["vx-l-face-polite", "Culture extras", "Politeness is a face-saving technology; more please is not more polite globally",
    "Brown and Levinson neighbourhood: do not threaten my image. Indirectness is a tool. A culture that is ‘rude’ to you may be honest in their file.",
    "Polite means lots of please. More please is more polite, globally. Also: my culture is clear; theirs is sneaky. Always.",
    "Learn how to refuse in the language without a war. Then a email that is a violence or a kindness depending on the file.",
    "A ‘we should have lunch’ stranding is this path. Ask a second question when the air is heavy."],
  ["vx-l-honorific-map", "Culture extras", "Honorifics are grammar plus a social map; the fanciest form always is not a seatbelt in every culture",
    "Who is older, a customer, a teacher. Dropping them can be intimacy or an insult. A -san for everyone is a learner strategy. A -sama for a classmate is a joke or a crush.",
    "Use the fanciest form always so you cannot be wrong. Also: skip them to be authentic. Two spills.",
    "Learn the default for a shop and a friend. When unsure, one step polite is a seatbelt in many cultures — not all. Ask.",
    "A keigo error in a job email is a career event. A textbook will simplify; a drama will not. Watch the drama after the textbook."],
  ["vx-l-taboo-voltage", "Culture extras", "A taboo word is a social high-voltage; arbitrary does not mean consequence-free",
    "Swearing, a sacred name, a death word. Borrowing a slur you do not own is not ‘just a word’ because a linguist said arbitrary. A minced oath is a fossil.",
    "If I can say it in linguistics class I can say it in the playground. Science. Also: never analyse a taboo, too dirty for school.",
    "Know the voltage. Quote with a purpose in analysis. Do not perform it for status. Then a minced oath’s history as a cute.",
    "A classroom that pretends swear words do not exist still has a oval. The oval will teach them with a worse theory."],
  ["vx-l-kinship-split", "Culture extras", "Kinship words are a map of who matters; English uncle is a poor bin",
    "Some languages split mother’s brother versus father’s. A cousin can be a brother in a way that is not a translation error. A skin system in some Australian languages is a map you do not invent from English.",
    "Family words are natural. Everyone means the same by uncle. Also: if it is not in English it is exotic decoration.",
    "Draw your family with the target language’s words. Notice the extra lines. If you study a Australian language, study it with people, not a worksheet only.",
    "A school form with mother/father only is a kinship politics. Forms are a language."],
  ["vx-l-gesture-airport", "Culture extras", "A gesture can be a word and a trap at an airport; thumbs-up is not a universal blessing",
    "OK circle, a nod that means no in some places. Emblems are language-like. Beat gestures are different. Mime is not a UN language.",
    "Hands are universal. Mime is a global language. Also: gestures do not count as language so skip them.",
    "Learn two dangerous gestures for a country you might visit. Then do not invent ‘funny’ ones. Then a pointing with a foot as a disrespect in a place.",
    "A shoe on a table can be a language too. Objects are in the culture file."],
  ["vx-l-high-low-context", "Culture extras", "High context puts the message in the air; low puts it in the clause — a stereotype if you apply it to a billion people",
    "Hall’s idea, still a useful warning. A yes can be a maybe. A blunt email can be a violence or a kindness. A contract culture versus a relationship culture is a business path.",
    "My culture is clear; theirs is sneaky. Always. Also: context is cheating, only clauses count.",
    "Ask a second question when the air feels heavy. Do not assume a yes. Also do not assume a no. Then a written follow-up if the file is money.",
    "A ‘as soon as possible’ is a low-context costume with a high-context fight. Dates beat ASAP."],
  ["vx-l-name-order", "Culture extras", "A name is a legal and sometimes a sacred object; family-first is not a ‘last name’ you guessed",
    "Patronymics, a dead name, a skin name that is not for a poster. Ask how to say it. Repeat. Do not give them an English one as a kindness without asking.",
    "I’ll shorten it. They’ll thank me. Easier for everyone. Also: unusual names are a burden on me so they should change.",
    "Ask pronunciation. Write a phonetic hint for yourself. Do not laugh. Then a form that has room for the actual order.",
    "A mispronounced name every day is a small civic violence. This hub and the English hub agree."],
  ["vx-l-au-multilingual", "Culture extras", "Australia is not a monolingual island except in the myth; English is a powerful default, not the only file",
    "First Nations languages (many endangered), migrant languages, Auslan. A Welcome in language is a politics and a gift. A bilingual sign is a policy; so is the absence of one.",
    "Everyone here should only speak English. That is fairness. Also: English is not from here so skip it. Two cartoons.",
    "Name the language of the Country you are on if it is offered. Then a community language in your suburb. Then a Saturday school as a civic institution.",
    "A ‘this is Australia, speak English’ at a hospital is a safety fail. Safety is a interpreter, not a yell."],
  ["vx-l-endanger-policy", "Culture extras", "A language can die because of a policy, not a vibe that it was not useful",
    "Schools that banned, a stolen generation of speech, a prestige of English. Revival is labour. A dictionary is not a speaker. A plaque greeting is a start; a child at the shops is a continuation.",
    "Languages die because they are not useful. English is useful. Evolution. Also: outsiders should own a revival because they have a grant.",
    "If you are an outsider, support speakers, do not own a revival. If you are in family, a word a day is a politics. Then a Master-Apprentice as a method, not a romantic.",
    "A classroom Dreaming pastiche in a invented ‘Aboriginal-style words’ is a harm. This path is a stop sign with a reading list."],
  ["vx-l-interpret-ethics", "Culture extras", "Interpreting is live with a brain lag; a child as a hospital interpreter is a harm",
    "Consecutive versus simultaneous. Ethics: say what was said, not what you wish. Bilingual is not a court qualification. Whispered simultaneous in a class is a skill; mumbling is a leak.",
    "Bilingual means you can interpret a court. Naturally. Also: machines replaced interpreters so skip the booking.",
    "If you are bilingual, still do not volunteer for a medical consult. Get a professional. You can still support. Then a booking that is actually funded.",
    "A police interview without a qualified interpreter is a civic and a languages fail. Both hubs."],
  ["vx-l-register-tv", "Culture extras", "Register is the clothing of the situation; mate versus sir is a social spill when it misses",
    "T-V distinction, a keigo, a email in all-caps. Getting it wrong is not only a grammar spill. Kings and babies do not get the same hey as a authentic personality.",
    "Be casual always. Authenticity. Also: be formal always so you cannot be wrong. Two costumes, one mess.",
    "Learn one polite and one casual path in a language you study. Then when each is safe. Then a all-caps as a register you already have in English.",
    "A bow and a handshake are a register of the body. Airports mix them. Watch the host."],
  ["vx-l-pragmatics-text", "Culture extras", "A sarcastic great is a tone plus a shared file; texting strips the tone",
    "/s exists because of this. A literal reading of a family chat is a weapon. A delay can be a meaning. Read once as if it is a letter.",
    "Words mean what they mean on a screen, always. Context is cheating. Also: if they used a emoji the meaning is obvious globally.",
    "When the air is weird, ask. Do not hold a three-day trial in your head. Then a phone call if the file is a relationship.",
    "A teacher’s short email is a time poverty, not always a anger. High-context readers will invent a fire."],
  ["vx-l-lingua-accom", "Culture extras", "Accommodation is slowing down and dropping idioms; it is a skill for English speakers abroad, not a personality transplant",
    "ELF pragmatics. A joke that needs a cricket file will die. Check-back questions. Native speakers who refuse to accommodate are a tax on the room.",
    "If they came to my language they can keep up. Speed is a right. Also: baby-talk them. Two insults.",
    "One idea per sentence. Then a paraphrase. Then a interpreter if the stakes are a hospital or a court.",
    "A conference without a budget for access is a languages policy. Policy is money."],
  ["vx-l-input-flood", "Learning extras", "You need a flood of understandable input; a grammar book without a story is a bone without a dog",
    "Krashen as a door: i+1. A story without any grammar notice is a fog. Mix. A kid’s show is a tool, not a shame. L1 subtitles can become a crutch.",
    "Translate every word, then you know the language. Input is lazy. Also: never look at a grammar, only vibes.",
    "Listen to something you almost get. Repeat. L2 subs, then none, is a ladder. Then a grammar notice of one pattern in the flood.",
    "A subtitle in your L1 on a whole series can grow a reader and freeze a listener. Notice which you became."],
  ["vx-l-output-repair", "Learning extras", "Output forces the gap to show; a silent classroom can still grow a reader, a speaker needs a loop",
    "Fossilisation is a real fossil. Shame is not a pedagogy. A 2-minute talk with a checklist, a record, one repair. A tandem who only wants your English is a deal — trade fairly.",
    "Speak from day one, perfectly, or do not speak. Also: never speak until you are perfect. Two silences.",
    "A 2-minute talk. Record. One repair. Not a roast. Then a person on Thursday, not only a app.",
    "A ‘goed’ is a over-regular. That is progress. Celebrate a more advanced error, then fix the high-frequency one."],
  ["vx-l-interlanguage", "Learning extras", "Your in-between language is a system, not a broken target with random stains",
    "Interlanguage has rules. Each error is not a random fail. The goal is still the target for a mark, and the path is still a system. The informations can fossilise for 20 years.",
    "Each error is a random fail. Punish each equally. Also: errors mean you should stop speaking.",
    "Pick one target for a session. Ignore the rest for ten minutes. Then a second pass. Frequency of correction plus input, not a single yell.",
    "A recast (say it back correctly) is a gentle tool. A ‘NO: -S’ is a hammer. Both have a time."],
  ["vx-l-cognate-catch", "Learning extras", "Cognates are freebies with a catch; a Latinate English speaker gets a French academic head start and a street trap",
    "Nation/nación. Then the liars. A -tion festival in a science text is a party. A café conversation might not invite you.",
    "If it looks like English, skip the dictionary. Always. Also: never use a cognate, they are all liars.",
    "Highlight true cognates in a paragraph. Circle the liars. Then a street word that is not Latinate.",
    "A exam that only tests academic cognates can flatter a English speaker and hide a oral fail. Oral is a different gym."],
  ["vx-l-chunk-first", "Learning extras", "Chunks are how fluency actually feels; tourists with chunks survive a station",
    "On the other hand, see you later, a formula. Grammar rules glue later. Always-from-atoms is a slow way to miss the train. How do you say is a meta chunk and allowed.",
    "Always build from atoms. Never learn a phrase. That is cheating. Also: only phrases, grammar is fake.",
    "Collect ten chunks. Use them unedited. Then vary one slot. Then a grammar notice of the slot.",
    "A memorised oral that ignores the question is a zero with extra steps. Chunks still need a ear."],
  ["vx-l-dict-blunt", "Learning extras", "A bilingual dictionary is a blunt instrument; one word, five senses",
    "A corpus or a learner’s dictionary shows how it sits. The first translation is not the meaning. A tattoo is the warning. A machine will smile while wrong.",
    "The first translation is the meaning. Done. Also: never use a dictionary, guess from the universe.",
    "Check an example sentence. Then a second dictionary. Then a human if it is a tattoo, a medical, or a legal.",
    "A ‘false friend’ you could have caught with a second line is a 30-second save. Take the 30 seconds."],
  ["vx-l-immersion-bubble", "Learning extras", "Immersion is not a holiday with a beach; a two-week tour can be English in a different kitchen",
    "Hours, a need to speak, a community. Change the phone, the friends, the fear. A study-abroad that stays in an expat bubble is a geography, not an immersion.",
    "If I am in the country I will absorb it through the skin. No work. Also: immersion is only a expensive program, so skip if you are in Bankstown with the language at the shops.",
    "Set a no-L1 hour. A club. A job if you can. Then still study. Then a suburb that already is a immersion if you walk in.",
    "A phone in English in a Japanese street is a portable bubble. The bubble is a setting."],
  ["vx-l-attrition", "Learning extras", "A language you do not use is a muscle you skip; once-learned-forever is a bike lie",
    "A weekly ritual beats a heroic month then nothing. Heritage speakers have a different, often painful, path. A community language school is a civic institution. Show up.",
    "Once learned, forever known. Like riding a bike. Except it is not a bike. Also: if you forgot you never really learned. Cruel.",
    "A podcast commute. A book on the phone. A person on Thursday. Then a word a day in a family language without a punishment frame.",
    "A ‘I used to be fluent’ is often a self-report with a generous past. A recording from then versus now is kinder and harsher."],
  ["vx-l-exam-washback", "Learning extras", "A language exam is a game with a rubric; washback means you will study what is marked",
    "Criteria, a time, an oral that is a performance. Still talk to humans. Passionate without tense is not a mark. A memorised oral that ignores the question is a zero with extra steps.",
    "If I am passionate the marker will feel it and ignore tense. Also: exams are fake so skip them and also want the ATAR.",
    "Past papers, a recording of yourself, one grammar that always costs you — hunt it. Then a human conversation that is not in the paper.",
    "A oral that is a monologue because you feared the listen is a strategy. Listen, then speak. The criterion said so."],
  ["vx-l-error-priority", "Learning extras", "Not every error is worth the same stop; a polite bomb outranks a third-person s in a flowing story",
    "Meaning-breaking first. Teachers who stop every atom kill the story. A recast is a gentle tool. A stain theory of every error is a climate of silence.",
    "Every error is a stain. Stop the speaker. Always. That is rigour. Also: never correct, it is mean. Two climates.",
    "Pick one target for a session. Ignore the rest for ten minutes. Then a second pass. Then a recast of the bomb.",
    "A fossilised the informations can last 20 years. Frequency plus input, not a single yell in Year 8."],
  ["vx-l-listen-shadow", "Learning extras", "An ear before a mouth is a strategy; shadowing is a gym, not a delay of a lazy student",
    "Babies do a listen-first. Adults can too, a bit. A mouth that never heard the rhythm will invent an English rhythm in the new language. A song you love is a ear gym if you look up the words after.",
    "Speak immediately so you activate. Hearing is passive and therefore fake. Also: only listen for a year, never speak. Two religions.",
    "A week of heavy listen on one dialogue. Then shadow. Then the page. Then a 2-minute output.",
    "A podcast at 1.5× in a language you almost get is a gym. A podcast at 1.5× in a language you do not is a noise."],
  ["vx-l-bilingual-myth", "Learning extras", "Bilingualism is not a delay as a destiny; mixing is not a disorder by itself",
    "Myths about confusion. A speech pathologist still exists for real disorders. Do not use a language as a punishment. A delay versus a disorder is a professional’s call.",
    "Two languages will break a child. Pick one, the useful one. Also: bilingual kids are automatically geniuses. Two myths, hold neither as a policy.",
    "Support both. Do not shame a mix. Then a professional if a worry is a real disorder, not a aunt’s folklore.",
    "A heritage speaker who understands but will not speak is common and tender. Patience is a pedagogy."],
  ["vx-l-maintenance-school", "Learning extras", "A Saturday school is a civic languages institution, not a extra-curricular cute",
    "Community, a script, a identity. Attrition fights a English week. Showing up is a politics. A school that clashes Saturday sport with it is a values map.",
    "If the mainstream school is English, extra language is optional decoration. Also: Saturday school is clannish so skip it for fairness.",
    "If it is your family language, a word a day plus a community. If you are an outsider, support, do not own. Then a script homework that is not a font poster only.",
    "A Welcome in language at a assembly is a start. A child using it at the shops is a continuation. This path and the endanger path agree."],
  ["vx-l-morpheme-glue", "How language extras", "A morpheme is a smallest meaning bit; un-help-ful is three, not a vibe of long words",
    "Bound versus free. A cranberry morpheme (cran- in cranberry) is a leftover. Productivity of -ness is why you can invent a Tuesday word. A blend is a different machine.",
    "Longer words are smarter. Count the letters, skip the bits. Also: never coin, only the dictionary is real.",
    "Split five words into morphemes. Then a fake word a child might say (goed). Then why the child is a scientist.",
    "A legal un- before a already-negative is a mess. Drafters still do it. Bits have a order."],
  ["vx-l-register-email", "How language extras", "An email in all-caps is a register; so is a bow — clothing of the situation travels across languages",
    "T-V, a mate versus a sir, a keigo. Getting it wrong is a social spill. A phrasebook that only has casual will strand you in a office.",
    "Be casual always. Authenticity. Kings and babies get the same hey. Also: the fanciest email is always safest worldwide.",
    "Write the same request casual and formal in a language you study. Then pick with a map of the person, not a personality of you.",
    "A auto-translate that drops honorifics can start a small war. Machines are a intern."],
  ["vx-l-vowel-space", "Sounds extras", "A vowel chart is a mouth map; English ‘same letter’ is not the same colour of vowel across languages",
    "High/low, front/back, a rounded. Ship/sheep was a phoneme pair; this is the continuous space under it. A learner’s ‘a’ from Italian will sit different in cat.",
    "Vowels are the five we write. A E I O U. Science of a alphabet poster. Also: extra vowels are posh.",
    "Say beat, bit, bet, bat with a hand on your jaw. Then a language with a vowel you do not have. Then do not mock the millisecond of a miss.",
    "A Australian trap-bath split is a geography of a vowel. Maps are allowed in a sounds class."],
  ["vx-l-glottal-stop", "Sounds extras", "A glottal stop is a sound; some Englishes use it in butter and some languages use it as a letter",
    "Uh-oh is a English cameo. Hawai‘i is a letter. Learners who skip the ‘okina change a name. A Cockney-ish t-glottal is a dialect, not a laziness sermon by itself.",
    "If it is not a letter in English it is not a sound. Also: glottal is sloppy, always correct it out.",
    "Feel the catch in uh-oh. Then a name with a ‘okina. Then a butter with a t versus a catch — describe, do not roast.",
    "A font that drops the ‘okina is a software of a disrespect. Names are a sounds file."],
  ["vx-l-spaces-optional", "Scripts extras", "Spaces are a convention; some scripts chunk with other tools and a English spacebar is not civilisation",
    "Thai, a Chinese line, a Japanese mix. A learner who inserts English spaces into a wrong place can break a search. A legal translation that ‘fixes’ spacing can change a condition.",
    "Everyone uses our spaces. Civilisation is a spacebar. Also: spaces are optional in English now because of hashtags, so skip them.",
    "Copy a sentence without adding English spaces. Then a search box that needs a exact string. Then humility.",
    "A website that wraps a Thai line on a English space algorithm will slice a word. That is a bug, not a cute."],
  ["vx-l-diacritic", "Scripts extras", "A diacritic is a letter-feature; dropping it can change a name or a tense",
    "Accents in French, a umlaut, a macron in a Māori word. A keyboard without them is a politics. A ALLCAPS that strips them is a data fail.",
    "Decorations are optional. Real letters are the ones on a US keyboard. Also: if it is hard to type it is not a real name.",
    "Type the name with the marks. Save a keyboard layout. Then a database that stored a stripped version — demand a fix if it is your system.",
    "A macron on a place name is a sounds and a civic. Maps that drop it are a choice."],
  ["vx-l-sense-relation", "Meaning extras", "Synonym, antonym, hyponym are a map of a cabinet, not a thesaurus of interchangeable stickers",
    "A dog is a hyponym of animal. A powerful tea is a collocation miss we already met; synonym is the cabinet, collocation is the handshake. A exam ‘replace with a synonym’ can wreck a register.",
    "Any synonym is interchangeable. Thesaurus-driven essays prove it. Also: opposites are always neat pairs in nature.",
    "Draw a small tree: animal, dog, kelpie. Then a antonym that is a scale (hot) versus a binary (dead). Then do not thesaurus a legal term.",
    "A GST fight about a food hyponym is a meaning class with a invoice. Tomato again."],
  ["vx-l-deixis-here", "Meaning extras", "Deixis is a pointing in language; here, I, tomorrow need a body in a place",
    "A recorded message’s tomorrow is a trap. This in a email without a attachment is a ghost. Learners mix come/go because the pointing is a different map.",
    "Here is a GPS. Words do not point, they name. Also: I always means the writer, even in a quoted law.",
    "Rewrite a message so a stranger in a week could still follow the pointing. Then a come versus go in a language you study.",
    "A ‘see you tomorrow’ text sent at 1am is a deixis of a calendar. Calendars disagree at midnight."],
  ["vx-l-face-refuse", "Culture extras", "A refusal is a speech act with a costume; a bald no can be a kindness or a war",
    "Indirectness, a excuse, a alternative. A culture that is ‘rude’ may be saving a different face. Learners who only know yes will drown in a maybe.",
    "Just say no clearly always. Authenticity. Also: never say no, it is rude globally. Two drownings.",
    "Learn two refusal formulas in the language you study. Then a email that offers a alternative. Then do not assume a yes from a silence.",
    "A shop ‘we should have lunch’ is this path’s cousin. Diaries versus air."],
  ["vx-l-srs-spacing", "Learning extras", "A spaced repetition is a calendar for a memory, not a personality of being a nerd",
    "A card that is a sentence beats a card that is a naked noun. Translation-only cards grow a dictionary, not a mouth. A heroic pile you never review is a museum.",
    "Cram the night before. Memory is a night. Also: SRS is cheating, real learners suffer.",
    "Make ten cards from a dialogue you actually heard. Review on the commute. Then speak one card to a person, not only a button.",
    "A deck of 4000 nouns with no verb is a brick. Bricks do not buy a train ticket."],
  ["vx-l-transfer-l1", "Learning extras", "Your first language will leak; transfer is a system, not a stain of a stupid",
    "Word order, a article, a th. Some leaks help (a cognate). A teacher who only says ‘think in the language’ skipped a useful map of the leak. Think-in is a later hat.",
    "Each error is random. Also: never use L1, it poisons. Two religions that ignore transfer research.",
    "List three leaks you actually do. Drill those, not a random grammar island. Then a translation as a diagnostic, not as the only method.",
    "A I am knowing is a stative leak some L1s invite. Name the L1, then the English file. Naming is a kindness."],
]);
