import { pack } from "../pack.mjs";

export const LOGIC_VOLUME = pack("logic", [
  ["vx-o-modus-ponens", "Arguments extras", "Modus ponens is if P then Q, P, therefore Q — a shape, not a vibe of therefore",
    "The conditional has to be in good shape first. A hidden extra premise can still sit under the if. Valid is the shape; sound is the world.",
    "If I said therefore, it is modus ponens. Therefore is a magic word. Also: formal names are for pedants so skip the shape.",
    "Write P and Q on two lines. Check the if. Then whether P actually arrived, or only a cousin of P.",
    "A ‘if it rains the oval is wet; it is wet; therefore rain’ is the wrong shape. That is affirming the consequent, next door."],
  ["vx-o-modus-tollens", "Arguments extras", "Modus tollens is if P then Q, not Q, therefore not P — the useful no",
    "Science lives here with a humble face: the prediction missed, so the if takes a hit. A auxiliary hypothesis can still save P for a while (the ad hoc path).",
    "If the test missed, the whole theory is dead forever. Also: missed tests never count. Two religions.",
    "Name the prediction. Name the miss. Then whether a extra patch appeared in the same breath.",
    "A ‘if they were guilty they would run; they did not run; so innocent’ needs the if to be true. Innocent people run too. Shape plus world."],
  ["vx-o-affirm-consequent", "Arguments extras", "Affirming the consequent is if P then Q, Q, therefore P — a popular wrong shape",
    "Wet oval, therefore rain, skipping the sprinkler. Medical tests and folk diagnoses love this shape. A Bayesian can still raise P a bit without a therefore of certainty.",
    "If the then-bit happened, the if-bit happened. Time runs backwards through a conditional. Obviously.",
    "Invent a second path to Q. If you can, the therefore P was a leap. Then a test that would split the paths.",
    "A ‘good people succeed; they succeeded; therefore good’ is a prosperity sermon in this shape. Sermons can still be false."],
  ["vx-o-deny-antecedent", "Arguments extras", "Denying the antecedent is if P then Q, not P, therefore not Q — the other popular wrong",
    "If it is a dog it is a mammal; it is not a dog; therefore not a mammal. A cat would like a word. Policy ‘if we do A we get B; we will not do A; so no B’ skips other roads to B.",
    "If the trigger did not happen, the result cannot. Triggers are monopolies.",
    "Name another road to Q. Then rewrite with only if if you actually meant a monopoly.",
    "A ‘if you go to uni you get a job; I did not go; so no job’ is this shape with a labour-market extra. Extra is the subject."],
  ["vx-o-contrapositive", "Arguments extras", "The contrapositive of if P then Q is if not Q then not P — same claim, different jacket",
    "Useful for proofs and for spotting a tollens. A inverse (if not P then not Q) is a different claim. Students mash the jackets.",
    "Any rearrangement of if and not is the same. Logic is a blender. Also: jackets never matter, only vibes.",
    "Write the if. Write the contrapositive. Then the inverse and the converse as different animals. Then which you actually need.",
    "A ‘no ticket, no entry’ is a biconditional costume that people treat as a one-way if. Read the sign."],
  ["vx-o-biconditional", "Arguments extras", "If and only if is a two-way door; a ordinary if is one-way",
    "P iff Q is P if Q and P only if Q. Maths loves it. Speeches say iff when they mean a vague if. A definition often wants iff and a slogan does not.",
    "If, only if, and iff are a style choice. Fancy is iff. Also: only if means if. Dictionaries of a pub.",
    "Replace iff with two arrows. Then a counterexample on one arrow. Then whether a definition was hiding.",
    "A legal ‘if and only if’ in a insurance clause is a two-way door with a invoice. Do not read it as a vibe of if."],
  ["vx-o-quantifier-scope", "Arguments extras", "Some, all, and none are a scope machine; a not can sit in two places and start a war",
    "Not all swans are white is not all swans are not white. A politician’s ‘nobody is saying X’ can be a not-all in a costume. Draw a oval.",
    "Some means a few, never most. All means I feel strongly. None means I have not met one. Folk maths.",
    "Rewrite with a oval: all inside, some overlap, none. Then move the not. Then a headline that moved it for you.",
    "A ‘all cops’ versus ‘not all cops’ thread is a quantifier with a moral. The oval still helps, even when the moral is the point."],
  ["vx-o-counterexample", "Arguments extras", "A single honest counterexample kills a all; it does not kill a some",
    "Black swan, a exception that is in the class. A ‘no true’ move that expels the counterexample is a fence on wheels (the Scotsman path). A some survives a miss.",
    "One story that fits my team kills their all. One story that fits theirs is a exception. Convenient.",
    "Ask whether the claim was all, most, or some. Then whether the exception is in the class. Then a rate if it was most.",
    "A Australia as a black-swan classroom is a logic cliché because it worked. Use it, then find a less cute one."],
  ["vx-o-charity-first", "Arguments extras", "Charity is reconstructing the least stupid version, then attacking that — not a surrender",
    "A hidden premise supplied in a fair form. A steel-man is a cousin. Online prefers a scarecrow because scarecrows lose on time.",
    "Charity is for after you win. First, the weakest version, publicly. Also: charity means you agree.",
    "Rewrite their view so a smart enemy would thank you. Then dissent. Then a hidden board you added — flag it as yours.",
    "A TED talk can still be a thin argument with a nice light. Charity does not invent the missing numbers."],
  ["vx-o-hidden-board", "Arguments extras", "An enthymeme is an argument with a missing board; drag it into the light before you punch",
    "Of course he is guilty, he ran hides the innocent never run. Ads hide you are incomplete without this. Cringe is the lesson when you write it down.",
    "Missing bits are fine. We all know. That is community. Also: if it was missing it was not an argument.",
    "Supply the hidden premise in the least stupid form. Then see if you still buy it. Then a ad as homework.",
    "A ‘of course’ is often a board. Of course is a tell."],
  ["vx-o-valid-not-true", "Arguments extras", "A valid argument can be garbage if the premises are; sound is the gold",
    "All cats are planets, Tibbles is a cat, therefore Tibbles is a planet — valid and silly. Folk ‘valid’ means I agree. Precision is the whole subject.",
    "Valid means I agree. Sound means loud. Also: if it is valid it is true of the world.",
    "Invent a valid silly. Then a sound small one (a room, a fact, a therefore that has to follow). Then a courtroom ‘valid’ as a different dialect.",
    "A legal ‘valid will’ is not this word. Do not mash a statute into a intro-logic quiz."],
  ["vx-o-induct-bet", "Arguments extras", "Deduction promises necessity; induction promises a bet — a black swan is a induction problem",
    "All men are mortal, Socrates versus 1000 white swans. Science lives here with a humble face. A single counterexample kills a deduction of a all; it updates a induction.",
    "Induction is just deduction with extra steps. Or: induction is fake so skip evidence. Two cop-outs.",
    "Label a paragraph. If a single counterexample could kill that claim as stated, it was not a deduction of that claim. Then a cautious most.",
    "A Europe-all-swans-white was a data limit. Australia was a logic class. The class still applies to a feed."],
  ["vx-o-analogy-map", "Arguments extras", "An analogy holds if the relevant bits hold; a colour is not a mechanism",
    "Schools are not businesses in every way. Sometimes they are in a budget way. Name the relevant. A body-is-a-temple can support care or a diet cult.",
    "If A is like B in one way, all arguments about A transfer. That is why we say like. Also: analogies are fake, never use them.",
    "List shared, list unshared. Only then transfer the conclusion. Then a ‘like a’ in a speech as a map you can grade.",
    "A ‘the economy is a household’ analogy is a famous leaky boat. Households cannot tax in the same way. Mapping is the work."],
  ["vx-o-necessary-recipe", "Arguments extras", "Necessary is the oxygen; sufficient is a whole recipe — mix them and you get a law-exam fail",
    "You need oxygen to live. Oxygen is not sufficient. A degree may be necessary for a posting and still not sufficient. 400 applicants.",
    "If it is needed it is enough. If it is enough it is needed. Same thing. Also: only if means if.",
    "Write only if versus if. Then a Venn. Then a job ad as a test. Then still a human in the 400.",
    "A ‘you only live once’ is not a necessary-and-sufficient about skydiving. Slogans skip the recipe."],
  ["vx-o-vague-line", "Arguments extras", "A vague word can smuggle a win; soon, harm, real music want a test even if the test is messy",
    "A heap paradox is cute; a policy on offensive without a test is a power. Precise is not only for accountants. A zero tolerance that is not zero is a slogan.",
    "Vague means deep. Precise is for accountants. Also: if you cannot name the exact grain, the word is meaningless. Delete child, green, heap.",
    "Replace the word with a number or a test. If the argument dies, it was a fog machine. Then a stipulated line for a law (18 years) as a civic cousin.",
    "A speed limit is a sorites with a sign. 50 versus 51 is a civic, not a metaphysics, in the courtroom."],
  ["vx-o-equivocate", "Arguments extras", "The same word, two jobs, a magic trick; free in free speech versus free beer",
    "Man as human versus male. Law as statute versus regularity. A pun is a joke; in a brief it is a cheat. Dictionaries have more than one line.",
    "If the word is the same, the meaning is the same. Also: every word is infinitely ambiguous so skip precision.",
    "Star the word each time. If the sense jumped, rewrite with two words. Then a slogan that needed the jump to work.",
    "A ‘taxation is theft’ can be a persuasive definition until you argue the ethical bit. Unpack. The define path agrees."],
  ["vx-o-genetic", "Fallacies extras", "A genetic fallacy is attacking the origin as if origin were the content — except when origin is a conflict of interest",
    "A idea from a bad person can still be true. A idea from a saint can still be false. A paid study is a reason to look harder, not to skip the methods. Split.",
    "If they are a hypocrite the claim is false. Always. Smoking doctors cannot know lungs. Also: origin never matters, even a forged dataset.",
    "Split: is this about the birth of the claim or the claim. Keep the claim if it stands. Then a COI as a trust file, not a chemistry.",
    "A ‘that idea came from a company’ can be a genetic dodge or a methods alarm. Open the paper."],
  ["vx-o-poison-well", "Fallacies extras", "Poisoning the well is a pre-emptive smear so nothing they say can count",
    "Before they speak: they are a X, so skip. A conflict disclosure is a different, fair well-label. A identity that is not a conflict is often a smear.",
    "If I warn the room about them I have done logic. Warnings are premises about the world. Always.",
    "Let the claim land. Then a relevant COI. Then a smear you can delete without losing a reason.",
    "A ‘as a mother’ can be a relevant experience or a status trump. The status path next door. Split."],
  ["vx-o-appeal-tradition", "Fallacies extras", "We have always done it is a history, not a warrant — unless the warrant is ‘this is a convention we chose’",
    "A civic habit can be a resource or a cage. Natural is a cousin (hemlock is natural). Novelty as a automatic good is the mirror fallacy.",
    "If it is old it is wise. If it is new it is better. Two clocks, no because.",
    "Ask what the tradition was for. Then whether the world that fitted it is still here. Then a keep as a choice, not a physics.",
    "A ‘she’ll be right’ can be solidarity or a shrug at a royal commission. Which, in this case, wants a because."],
  ["vx-o-appeal-novelty", "Fallacies extras", "New is a date, not a proof; a 2020s app can still be a 19th century scam in a hoodie",
    "Disruption as a sermon. A peer-reviewed old can beat a preprint new. A genuine improvement still has to name the mechanism, not the year.",
    "If it is on a phone it is better. Dates are quality. Also: new is always a decay of the West. Two sermons.",
    "Name what is new: the interface or the claim. Then a old study. Then a RCT if it is a body file.",
    "A ‘traditional’ supplement that is a Instagram is novelty in a tradition costume. Costumes are a fallacy pair."],
  ["vx-o-ignorance-gap", "Fallacies extras", "Appeal to ignorance is a gap treated as a yes; absence of evidence is not evidence of absence — except when you looked hard",
    "Russell’s teapot. A ‘prove it is safe’ versus ‘prove it is harmful’ is a policy choice, not only logic — name it. A conspiracy that demands you archive the world is a burden trick.",
    "If you cannot disprove my claim I win. That is science. Also: if a study has not been done, the thing is safe. Two gaps.",
    "Who moved? They bring evidence. You do not owe a 40-page no. Then a case where a good search would have found it if it were common.",
    "A rare side effect can still be real with a empty RCT of n=40. Empty is a power problem, next door in evidence."],
  ["vx-o-whatabout", "Fallacies extras", "Whataboutism is a red herring with a moral costume; a tu quoque is a you-too about the same rule",
    "A scandal, a joke, a ‘what about their side’. The original claim sits unfed. Hypocrisy is a character file; the claim can still be true. Split the herring from the you-too.",
    "If it is interesting it is relevant. Attention is a logic. Also: if they did it, the rule is void forever.",
    "Write the original Q. Draw an arrow. If the new bit does not feed it, you were herded. Then a separate ‘and you should stop too’ if that is the actual claim.",
    "A climate lecture on a plane is a tu quoque magnet. The emissions maths can still stand. So can a practice-what-you-preach as a different claim."],
  ["vx-o-nirvana", "Fallacies extras", "A nirvana fallacy rejects a option because it is not heaven; a perfect-solution cousin waits forever",
    "A policy that reduces harm but not to zero ‘fails’. Seatbelts, a needle program, a exam resit. Sometimes the third door is real (false dilemma). Sometimes heaven is a stall.",
    "If it is not perfect it is useless. Also: any first step is Z (a slope without gears). Two stalls.",
    "Ask compared to what. Then a remaining harm you still name. Then whether a third door exists without inventing a cartoon.",
    "A ‘exam or failure’ that ignores a resit is a false dilemma. A ‘the vaccine is not 100%’ is often nirvana. Name the comparison."],
  ["vx-o-fallacy-fallacy", "Fallacies extras", "Calling a fallacy is not a disproof of the conclusion; even a messy arguer can be right about the rain",
    "A ad hominem that was actually a COI. A valid point in a rude jacket. Logic class can become a gotcha sport that never looks at the world.",
    "If they named a fallacy they won. Latin is a verdict. Also: fallacies are fake because smart people use them. Two cop-outs.",
    "Steel the claim without the bad move. Then see if it stands. Then a world check (a look outside).",
    "A rude person pointing at a fire can still be pointing at a fire. Put the fire out. Then the manners file."],
  ["vx-o-moving-posts", "Fallacies extras", "Moving the goalposts is a new hurdle after the old one was met; a honest update is a named new question",
    "A conspiracy that needed a leak, then ‘that leak is a plant’. Science can raise a standard with a reason (a better instrument). The tell is a unnamed slide.",
    "Raising a standard is always cheating. Also: I never move, I was always this strict. Two autobiographies.",
    "Write the original hurdle. Tick it. Then whether the new hurdle was announced as a new question. Then a unfalsifiable soup if both ‘they hide it’ and ‘they show it as a double bluff’ appear.",
    "A ‘first they ignore you’ quote used as a proof of any ignored claim is a goalpost that is a proverb. Proverbs are not a method."],
  ["vx-o-texas-shoot", "Fallacies extras", "A Texas sharpshooter paints the target after the shots; a cluster can be a story you drew",
    "Cancer-cluster folk, a data mine, a lucky pattern in a big enough pile. Premature drawing of a bullseye. Pre-registration is a later patch in science.",
    "If I can see a shape it is a aim. Shapes are intentions. Also: clusters never exist, always ignore a town’s cancer.",
    "Ask whether the hypothesis was written before the look. Then a multiple-comparisons hit. Then still a cluster that deserves a real epi, not a meme.",
    "A ‘successful people who woke at 5am’ book selected on success. The 5am failures did not get a book. Survivorship is a cousin."],
  ["vx-o-cherry", "Fallacies extras", "Cherry-picking is a selected sweet; the bowl still exists",
    "A quote mine is a cousin. A graph’s time window. A ‘studies show’ that shows one study. You met selection in the original evidence path — this is the folk name.",
    "If it is the data we have, it is the data that is. Missing is nothing. Also: one vivid cherry is a orchard.",
    "Ask for the bowl: a systematic, a time window reason, a contrary study. Then still a cherry that is a real case report — structured, not a orchard.",
    "A politician’s ‘jobs created’ month versus a decade is a cherry with a podium. Read the axis."],
  ["vx-o-middle-not-wise", "Fallacies extras", "The middle is not automatically wise; two mad claims do not make their average true",
    "Sometimes one side has the evidence. A false balance in media is this fallacy with a tie. A budget fight might be a real middle. A 99–1 scientific fight is not.",
    "Always meet in the middle. That is maturity. Even between the earth is round and flat. Also: never compromise, purity.",
    "Ask which claim has the weight. A compromise on a number can still be right as a number, not as a moral average of two slogans.",
    "A ‘both sides’ on a climate file can be a middle fallacy. A both-sides on a parking time might be a adult. Files differ."],
  ["vx-o-bandwagon-feet", "Fallacies extras", "Many feet is not a proof; a poll is a civic file when the vote is the point, not when the world is",
    "A trend, a ‘nobody believes that anymore’. Truth is not a majority vote except in some civic files where the vote is the point. A popular medical wrong is a history book.",
    "If it is popular it is true. Markets and crowds are oracles. Also: if it is popular it is false, I am a rebel. Two oracles.",
    "Separate people like it from it works. Then a fashion that knows it is a bandwagon. Then a medical fad that does not.",
    "A ‘real Australians think’ is a bandwagon with a flag. Flags are not a census of a mechanism."],
  ["vx-o-emotion-warrant", "Fallacies extras", "Emotion is a reason to care, not a warrant by itself; a sad case opens a file, a rate sets a policy",
    "Pathos plus logos is a civic adult. If you cried you lost, or you won — two schoolyard rules, both thin. A single hospital photo versus a table of outcomes: both jobs.",
    "If you cried you lost the argument. Also: if they did not cry they do not care. Two schoolyards.",
    "Keep the story. Add the rate. If the rate kills the story’s lesson, you have a problem. Then still care — and know the rate.",
    "A bushfire photo is a reason to care. A building code is a rate and a statute. You need both jobs."],
  ["vx-o-composition-pile", "Fallacies extras", "What is true of a bit is not always true of the pile; division is the reverse",
    "A player is best, the team is not automatically best. A cheap atom, an expensive machine. Weight does aggregate. Best might not. Each tax cut is small versus the budget.",
    "The whole is the sum in every way. Obvious. Teamwork is a poster. Also: the team is good so each is. Always.",
    "Ask if the property aggregates. Then a ‘invisible parts, invisible whole’ toy. Then a budget as a pile that was the point.",
    "A ‘I can waste a little water’ times a city is a composition. Droughts are a pile class."],
  ["vx-o-relative-risk", "Evidence extras", "A relative risk without a base rate is a lottery poster; 50% more of rare is still rare",
    "Absolute risk, a NNT if you are in a clinic neighbourhood. A headline ‘doubles’ a 0.2% into a panic. Bayes later; the habit is now: how common before.",
    "If the test or the drug is 50% better it is a coin flip made good. Percentages on a box are a story. Also: absolute numbers are a pharma trick, always use relative.",
    "Ask how common before. Then the extra cases per 1000. Then a harm rate in the same unit. Then still a value about which harm you fear.",
    "A ‘accurate 99%’ test on a rare thing is a false-positive factory. Security scanners at a million people a day are a queue of misery."],
  ["vx-o-p-value-folk", "Evidence extras", "A p-value is not the odds the hypothesis is true; it is a ‘this weird if the null were true’ neighbourhood",
    "A 0.05 is a habit, not a nature. A n tiny can miss a real effect (power). A n gigantic can make a tiny useless effect ‘significant’. Effect size is a adult.",
    "If p is small the story is true. If not, the story is false. Also: p is a conspiracy of statisticians so skip numbers.",
    "Look at the effect size, the n, a pre-registration if any. Then a replication. Then still be unsure after one paper.",
    "A ‘borderline p’ that became 0.049 with a extra analysis is a garden of forks. Pre-register, or admit the garden."],
  ["vx-o-file-drawer", "Evidence extras", "A file drawer is the studies you did not see; publication bias is a filter on the bowl",
    "Journals like a yes. A mega-journal with a fee is a new ecology. A systematic review that skips grey literature can still be a cherry orchard with a method section.",
    "If it is published it is true forever. Journals are oracles. Also: if it is unpublished it is the real truth the cabal hid. Two oracles.",
    "Look at a funnel plot if you are in a review. Then a replication. Then a conflict. Then a preprint as a conversation, not a halo.",
    "A ‘my paper they rejected’ can be a martyr story or a bad paper. You need more than the martyr. Peer review is a filter, not a halo."],
  ["vx-o-simpson", "Evidence extras", "Simpson’s paradox is a trend that flips when you split the groups; the lurking group is the story",
    "A hospital that looks worse because it takes the harder cases. A average that hides a shape — you met means in the original path. Here the split is the move.",
    "The overall number is the truth. Splits are cheating. Also: any split I like is the truth. Two cherries.",
    "Ask what the groups were. Then whether you should combine. Then a mechanism (who goes to which hospital).",
    "A ‘women’s university results’ story that flipped after a course-mix split is a famous classroom. Course mix is a civic too."],
  ["vx-o-confound", "Evidence extras", "A confound is a third gear that turns both knobs; ice cream and drowning is a temperature",
    "A lurking variable, a reverse, a coincidence in a big pile. Together is not because. Name three stories: A→B, B→A, C→both. Then what would distinguish.",
    "If r is big, the story is over. Cause found. Ship it. Also: if you can name a confound, the correlation is fake and useless. Epidemiology still exists.",
    "Name three stories. Then a control, a dose-response, a mechanism. Then still humility. A lighter-and-cancer is a C (smoking).",
    "A ‘people who carry umbrellas get wet’ is a reverse plus a C (rain). Folk causation is a sport."],
  ["vx-o-operationalise", "Evidence extras", "A pretty word still needs a measurement recipe; happiness that is a one-item survey is a recipe",
    "Construct, a proxy, a SMART-ish. GDP as a map that drops a lot (the map-territory path). A ‘engagement’ that is a click is a business recipe, not a soul.",
    "If I can say it in a sentence it is measured. Grammar is a lab. Also: measurement is always a violence so skip numbers.",
    "Write the recipe: who, what scale, when. Then what the recipe dropped. Then whether the drop matters for this decision.",
    "A NAPLAN number is a operationalisation of a slice of literacy. A slice is not a child. Both can still inform a school."],
  ["vx-o-replication", "Evidence extras", "A replication is a second look at the same claim, not a insult; a crisis was a methods story",
    "Same direction, a smaller effect often. A conceptual replication is a cousin, easier to ‘succeed’ by changing the thing. Pre-registration helps the sharpshooter problem.",
    "If it replicated it is true forever. If it did not, the first team were frauds. Two cartoons. Fraud exists and is not the whole crisis.",
    "Look for a replication before you rebuild a life. Then a systematic. Then still a case report as a signal, not a law.",
    "A psychology classroom classic that failed a replication is a humility gym. The gym is the subject, not a gotcha only."],
  ["vx-o-effect-size", "Evidence extras", "Statistically detectable is not the same as worth doing; a tiny r with a million rows is a microscope of a nothing",
    "Cohen-ish neighbourhood, a MCID in a clinic (minimal important difference). A policy that moves a rate 0.01% can still be huge if the population is a country — name the unit.",
    "If it is significant it matters. If it is not, it does not. p is a value system. Also: only huge effects are real.",
    "Ask the unit, the size, the cost of the intervention, a harm. Then a NNT. Then a value (whose harm).",
    "A ‘significant improvement in a mouse maze’ is a press release. Mice are not a ATAR. The scientific-click path in digital agrees."],
  ["vx-o-power-n", "Evidence extras", "A small n can miss a real effect; a empty study is not a proof of a zero",
    "Power is a ‘would we have seen it’. Rare side effects need a different machine (pharmacovigilance). A n=12 influencer trial is a anecdote with a blender.",
    "If they did a study and did not find it, it is false. Empty is a no. Also: small n is fine if I like the product.",
    "Ask n, a expected size, a rare-harm file. Then a registry. Then do not generalise your n=1 body to a species — and still log your body.",
    "A n=1 of a rare side effect can still be a signal. Report it. Do not therefore ‘it is poison for all’ from a vibe."],
  ["vx-o-blinding", "Evidence extras", "A blind is a wall between hope and a score; some questions cannot be blinded and still count as knowledge",
    "Placebo, a double when you can. A surgery placebo is a ethics bomb. Observational is not nothing — it is a different strength. Parachutes are the joke paper.",
    "If it is not an RCT it is not knowledge. Delete epidemiology. Also: blinding is always possible if you are rigorous. Two cartoons.",
    "Ask what the control would look like. If you cannot imagine one, you might still have a dose-response or a mechanism. Then a ethics that blocked the RCT.",
    "A before/after without a control is a post hoc magnet. A pandemic policy is hard to RCT. Humility plus the best available."],
  ["vx-o-quote-context", "Evidence extras", "A quote with the middle cut out is a weapon; the original paragraph is the adult",
    "Ellipses, a sarcasm that was the point. A scientist’s we do not know X yet cut to we do not know. A meme is the child.",
    "The best bit of the sentence is the whole meaning. Cut the hedges. Stronger. Also: context is a elite stall.",
    "Open the source. Read before and after. If the meaning flips, you were mined — or you mined. Then a Hansard if it is a politician.",
    "A ‘studies show’ without a study is a costume. Ask for the study, then the paragraph, not a pull-quote."],
  ["vx-o-primary-source", "Evidence extras", "A source has a location and a motive; I read it somewhere is a location called nowhere",
    "Primary, secondary, a PR, a preprint. A URL is a start; a method is a continuation. If it is a PDF it is not automatically true. If it is a tweet it is not automatically false.",
    "PDFs are true. Tweets are false. Simple. Also: primary means I liked it first.",
    "Name author, date, venue, a conflict. Then whether you could find a contradicting venue. Then a circular wiki-blog-wiki snake.",
    "A press release of a mouse is a scientific-click. Open the paper, the sample, the in-mice."],
  ["vx-o-base-rate", "Evidence extras", "A base rate will humble a vivid case; how common was it before the test",
    "Rare diseases, a false positive. Bayes is a later mountain; the idea is now. A 99% accurate test on a rare thing is still a maybe.",
    "If the test is accurate, a positive is a yes. Percentage on the box. Also: vivid is common because I can picture it (availability).",
    "Ask how common before. Then the error rate. A sketch, not a formula panic. Then still go to a GP if the body file is a body.",
    "A security scanner with 1% false positives at a million people a day is a queue of misery. Base rate. Airports already knew."],
  ["vx-o-mean-shape", "Evidence extras", "An average hides a shape; mean versus median, a bimodal, a CEO in a wage pile",
    "The average is not the typical just because a pub said so. A 2.2 children family is a joke and a warning. Ask the distribution.",
    "The average is the typical. Always. That is what average means in the pub. Also: medians are a lefty trick.",
    "Ask median, a range, a picture. Then the mean if you need a total. Then a bimodal you mashed into a one-hump story.",
    "A ‘average income’ presser that is a mean is a design. Designers of charts can refuse the mash."],
  ["vx-o-graph-axis", "Evidence extras", "A chart is an argument in ink; a truncated axis can turn 2% into a crisis",
    "3D pies, a dual axis that forces a marriage. The title is a claim. Tufte as a saint with a style. Jobs created versus a rate is a switch.",
    "If it is a graph it is data. Data cannot lie. People can, but not graphs. Also: all graphs are lies so skip them.",
    "Read the axis from zero if it is a magnitude. Read n. Read who made it. Then a dual axis as a shotgun wedding.",
    "A ‘crime up’ that is a count in a growing city versus a rate is a civic. The civics hub’s poll path agrees about methods."],
  ["vx-o-and-independent", "Probability extras", "AND of independents multiplies, and independence is a claim; a detailed story can be less likely",
    "A coin and a die. If they hug, you cannot multiply as if they did not. People treat and as a pile-on of certainty — the opposite of the maths. Linda is this path with a name.",
    "The more details I add, the more likely the story (a representative heuristic). The novelist wins. Also: never multiply, just pick the smallest.",
    "If independent, multiply. If not, stop and draw a table. A detailed plausible story can be less likely. Then a bank-teller versus feminist-bank-teller.",
    "A ‘they did A and B and C in a row by plan’ conspiracy is a conjunction. Conjunctions get smaller if independent. Plots can still be real — with a because, not a novel."],
  ["vx-o-or-overlap", "Probability extras", "OR of disjoint adds; overlapping needs a minus; English or is a mess of exclusive versus inclusive",
    "A card that is heart or king: do not double-count the king of hearts. A speech’s this or that can be exclusive for drama.",
    "OR means pick the bigger one and ignore the other. Simpler. Also: or always means both can happen, always. Two pubs.",
    "Venn. Add, subtract the overlap if you counted twice. Then whether the English was exclusive. Then a legal or that a drafter should have made a and/or.",
    "A ‘this or that’ in a manifesto can hide a both. Check the Venn before you pick a team."],
  ["vx-o-expected-ruin", "Probability extras", "Expected value is a long-run mean, not a promise tonight; insurance can be negative EV and still rational",
    "A lottery with a negative EV is a donation to a dream. Ruin is a separate question from EV. Utility is not always the dollar. A casino vig is a designed leak.",
    "If the prize is big the EV is big. Look at the prize, ignore the odds. Hope is a number. Also: EV is the only rationality, buy no insurance.",
    "Multiply, add, compare to the cost. Then a can I afford to lose as a separate question. Then a side bet with a 10% vig as a walk.",
    "A pokie that talks in your head about being due is a gambler’s-fallacy cousin. Walk. The original gambler path agrees."],
  ["vx-o-update-a-bit", "Probability extras", "New evidence should move you a bit, not a flip always; a modest study, a modest move",
    "A shocking single is a modest move if the base was strong. Bayes is the name; the habit is the path. A conspiracy community that never down-updates is a prior of 1.",
    "One article and my view is 100% the other way. Flexibility as a personality. Also: never update, that is flip-flopping. Two civic insults.",
    "Write a prior in words (pretty sure). Then what this evidence should do (a bit less sure). Then stop at 100% unless you are doing tautology.",
    "A motivated-reasoning gym (climate, a vaccine thread) is this path with a team jersey. You are not immune. The original motivated path is a mirror."],
  ["vx-o-regression-mean", "Probability extras", "Extreme, then back a bit, is a statistical weather; the son of a giant is often tall but less giant",
    "A star season then a slump can be regression plus a real slump. Sports commentary often skips this. A punishment that ‘worked’ after a worst-ever week can be weather.",
    "If they were great they stay great. If they failed they are washed. No mean to return to. Also: everything is regression so skip causes.",
    "After a wild data point, expect a milder next unless you have a mechanism of a new mean. Then a control group. Then still a coaching change that was real.",
    "A NAPLAN dip then a bounce after a poster campaign can be regression. A control school helps. Education is a probability."],
  ["vx-o-independent-reset", "Probability extras", "The coin has no memory; a streak does not owe you a tails",
    "Independent trials. A hot hand in sport is a different, empirical fight — do not import it to a roulette. A deck without replacement is a different game (count).",
    "It is due. The universe balances. That is fairness as physics. Also: streaks prove a rigged coin always.",
    "If independent, reset. If not (a deck), then count. Then a pokie design that talks like a memory. Walk.",
    "A ‘I am due a win’ is how a machine is designed to talk in your head. The digital money-online path agrees about a walk."],
  ["vx-o-prosecutor", "Probability extras", "A prosecutor’s fallacy mixes P(evidence | innocent) with P(innocent | evidence) — a DNA match is not a automatic dock",
    "Base rate of a profile in a city. A 1-in-a-million in a 5-million city is not a 1-in-a-million guilt. Defence can run a mirror fallacy. Courts need both.",
    "If the match is rare they did it. Rare is a dock. Also: DNA is fake because of the fallacy name. Two cartoons.",
    "Ask how common the profile is in the relevant population. Then a non-DNA because. Then still a match as a strong update, not a skip of a trial.",
    "A ‘accurate 99%’ cousin in a clinic is the same mix. This hub and health share a brain."],
  ["vx-o-monty", "Probability extras", "Monty Hall is a host with a rule; switching wins 2/3 if the host always opens a goat",
    "If the host is a random or a trickster the fraction moves. Intuition hates it. A simulation on paper (three cards) beats a argument at a BBQ.",
    "It is 50-50 after a reveal because two doors. Two is a half. Also: switching is always magic in every game show. Rules dropped.",
    "Play 15 rounds with cups. Count. Then name the host’s rule. Then a variant where the host can open the car — and watch the fraction die.",
    "A ‘new information always splits remaining doors equally’ is the folk rule. Folk rules fail here. That is the point of the path."],
  ["vx-o-mutually-excl", "Probability extras", "Mutually exclusive is cannot both; independent is one does not change the other — they are not synonyms",
    "A coin’s heads and tails are exclusive and dependent in a strong sense (if heads, not tails). Two coins can be independent and not exclusive. Students mash the words.",
    "If they cannot both happen they are independent. Words are a vibe. Also: exclusive means rare.",
    "Draw two ovals that do not overlap (exclusive). Then two that overlap but a table of a coin and a die (independent). Then a speech that mashed them.",
    "A ‘this or that, independently’ in a manifesto can be a mash. Venn first."],
  ["vx-o-condition", "Probability extras", "A conditional probability is a smaller world; given the test is positive is not the same as in the whole city",
    "A table beats a formula panic. Bayes is a bookkeeping of tables. A screening program is a civic of conditionals.",
    "Given is a fancy if, skip it. Also: conditionals are a trick to make people feel stupid, so skip medical tests.",
    "Write a 1000-person table. Fill the disease row. Fill the false positives. Then the given-positive column. Then a GP as a human, not a table only.",
    "A mammogram debate is this table with a ethics. Tables do not replace values. They stop a folk 99%."],
  ["vx-o-utility-not-ev", "Probability extras", "A dollar EV can be a bad map of a life; a certain loss versus a bet is a Kahneman neighbourhood",
    "Ruin, a insurance, a exam study hour. Utility is not always the money. A risk you cannot afford is a different animal from a casino with rent money you do not need.",
    "EV is the only rationality. Insurance is for cowards. Also: follow your gut, numbers are a vibe.",
    "Compute the EV. Then a can I afford to lose. Then a value (a night’s sleep). Then a pokie as a designed bad utility.",
    "A ‘YOLO’ skydiving is a utility claim. Name it a value, not a maths of a mean. The necessary-recipe path agrees about slogans."],
  ["vx-o-gambler-due", "Probability extras", "Due is a story the universe does not owe; fairness is not a physics of a streak",
    "A reset if independent. A deck is a different file. A ‘hot’ table in a casino is a interior design. Walk is a strategy.",
    "The universe balances. That is fairness as physics. Also: I can feel a due in my bones, bones are a statistic.",
    "If independent, reset. Name whether replacement happened. Then leave a machine that talks about due.",
    "A lottery ‘overdue’ map on a news site is a business of this fallacy. Maps of due are a product."],
  ["vx-o-avail-picture", "Puzzles extras", "What comes easy to mind feels common; a plane crash on the news versus a car",
    "Availability heuristic. A friend’s disease. Media is a availability machine. Shark week versus a vending machine (the boring comparison).",
    "If I can picture it, it is likely. Imagination is a census. Also: if I cannot picture it it is fake.",
    "Ask for a rate, not a picture. Then still be scared of the picture — and know you are. Then a drive that is still the dangerous one.",
    "A bushfire summer is available for a reason: it is a real rate in a place. Availability can track a world. Check a rate anyway."],
  ["vx-o-confirm-hug", "Puzzles extras", "You look for the hug, not the slap; a Wason card is a classroom of the hug",
    "Confirmation bias. Science is a culture that tries to make the slap cheaper. A search query that includes your conclusion is a confirm machine.",
    "Looking for support is research. Looking for disproof is negativity. Skip it. Also: I do not have this bias because I am smart. IQ is a halo.",
    "Write what would change your mind. Then look for that, for ten minutes. A ritual. Then the opposite query.",
    "A team jersey on a climate or vaccine thread is a gym. You are not immune. This path is a mirror, not a lecture for the other side only."],
  ["vx-o-sunk-ticket", "Puzzles extras", "The ticket is gone; the film is now — sunk cost in a logic hat",
    "Future hours versus past hours. A degree you hate in year 3 is a hard real version. A we have come too far to stop the project is a political sunk cost.",
    "Finish because you started. That is character. Always. Even a burning building if you paid for the tour. Also: always quit, past is nothing, promises are fake.",
    "Ask: ignore the past cost, what now? Then a separate I keep promises to myself if that is a value — name it a value, not a logic of money.",
    "A ‘we already spent the stadium money’ is a civic sunk. Voters can still say stop. The budget path in civics agrees."],
  ["vx-o-occams-tie", "Puzzles extras", "Simpler is a tie-break, not a proof; fewer extra beings if they explain equally",
    "A conspiracy with 400 silent people is a complex. Sometimes the truth is a mess. Occam is a razor, not a guillotine. Simple means the one I already like is a fake Occam.",
    "The simplest story is always true. Simple means the one I already like. Also: complex is always deeper.",
    "Count extra claims. Prefer the fewer if they explain equally. Then test. Then a coincidence-plus-error versus a 400-person silence.",
    "A ‘they all forgot to tell the truth in the same way’ versus a error plus a incentive. Weigh. Incentives can make a complex true."],
  ["vx-o-unfalsify-soup", "Puzzles extras", "If nothing could count against it, it is not in the evidence game; a shape-shifter excuse for every miss",
    "Astrology with a fog. A scientific claim names a miss. Popper as a door, with later footnotes. A conspiracy that uses both they hide it and they show it as a double bluff is soup.",
    "If it is meaningful it cannot be tested. That is depth. Also: if it can be tested it is shallow. Two depth sermons.",
    "Ask: what would you accept as a no? If nothing, you have a faith or a tautology. Fine, but do not call it a lab result.",
    "A moving-posts cousin. Write the hurdle before the look. Then a miss that still gets a extra moon."],
  ["vx-o-category-kind", "Puzzles extras", "A category error is a square in a round hole of kinds; what is the number 7’s colour",
    "A mind as a thing you can weigh like a stone, maybe. Ryle as a ghost-in-a-machine warning. Society wants is often a shortcut for many people.",
    "If I can say it in a sentence it is a coherent kind. Grammar is ontology. Also: kinds are fake so skip the question.",
    "Ask what kind of thing. Then whether the predicate fits that kind. Then unpack a society-wants into who wants.",
    "A ‘the economy wants’ is a category fog with a presser. Economies are not a person. Unpack into firms, a RBA, a household."],
  ["vx-o-circular-loop", "Puzzles extras", "A circle is a premise that is the conclusion in a hat; the book is true because it says so",
    "Begging the question in the old sense. A dictionary loop. A tight circle can be a definition — then it is not evidence of the world. Molière’s dormitive virtue is a costume.",
    "Repeating is proving. Volume times 3. Also: if it is a definition it proves the world. Definitions are labs.",
    "See if you can deny the conclusion without denying a premise that is the same. If you cannot, it was a loop. Then a stipulative let n be as a honest circle.",
    "A ‘true freedom is what my team does’ is a persuasive definition circle. The original define path unpacks it."],
  ["vx-o-thought-pump", "Puzzles extras", "A thought experiment is a lab in the head with a leak; tweak one bit and see if your view is a mood",
    "Trolley, a violinist, a swampman. It can reveal a principle. It can smuggle a intuition pump (Dennett’s warning). A trolley with a fat man is a famous pump. Still useful if you admit the pump.",
    "If it cannot happen it cannot teach. Only real labs. Also: thought experiments are the only ethics, skip hospitals.",
    "Change a feature. If your ethic flips on a hat colour, it was a pump. If it holds, you found a spine. Then a real hospital as a check.",
    "A ‘would you still say that if it was your kid’ can be a pump or a relevant analogical map. Name which."],
  ["vx-o-theseus-job", "Puzzles extras", "A ship of Theseus is a question about what same is doing; different jobs, different answers",
    "Parts swap, a replica, a you-over-time. Legal same company and same person fights start here. A band with no original members is a Theseus. So is a restored guitar.",
    "Same is obvious. Atoms. If the atoms changed it is not the same. Done. Then you never step in the same river, and also you are not you.",
    "Ask what the same is for (law, love, a warranty). Then a answer for that job. Then a different job’s answer without a gotcha that philosophy is dummy.",
    "A restored Holden with a new chassis is a registry problem. Registries pick a job. That is the path."],
  ["vx-o-liar-loop", "Puzzles extras", "This sentence is false — a loop in the language; you do not need to solve it to learn that language can bite itself",
    "A type theory, a do-not-allow-it-to-talk-about-itself as a patch. A form that says tick if you did not tick this is a liar in a clipboard. Programming languages forbid some self-ref for a reason.",
    "If it is a paradox it is deep and all logic is fake. Or: it is a word game, ignore. Two shrugs.",
    "See the loop. Then why a programming language forbids some self-ref. Then a legal clause that loops. Then a stop.",
    "A policy that refers to this policy as void if it is valid is a drafter’s dare. Dare is a bug."],
  ["vx-o-heap-line", "Puzzles extras", "A heap with one grain gone is still a heap until it is not; a law still needs a line",
    "Bald man. A policy needs a line (18 years) that is a bit fake and still needed. Fuzzy is a later tool. A speed limit is a sorites with a sign.",
    "If you cannot name the exact grain, the word is meaningless. Delete heap, child, green. Also: any line is a violence so skip laws.",
    "Use a stipulated line for a law. Use a range for a description. Do not pretend the line is in nature if it is not. Then a 50 versus 51 as a civic.",
    "A ‘adult content’ age gate is a sorites with a checkbox. Checkboxes are a design. Design is not a metaphysics."],
  ["vx-o-map-not-hill", "Puzzles extras", "The map is not the territory; a model, a stereotype, a GDP — useful, lying",
    "Korzybski via a hundred posters. Do not eat the menu. If the model is elegant it is not automatically the world. Physics envy for a society. A 2D map of a 3D hill still helps.",
    "If the model is elegant it is the world. Also: models are fake so skip them and also want a weather app.",
    "Ask what the model dropped. Then whether the drop matters for this decision. Then a contour that still lies a bit.",
    "A ‘the economy’ as a household is a map with a leak (the analogy path). Leak plus map is a double class."],
  ["vx-o-other-minds-fanfic", "Puzzles extras", "You do not live in their skull; a they meant it as I would is a daily bias",
    "Charity plus evidence of their words. Do not skip either. A they are plotting from a face is a mind-reading with a threat bias. Anxiety loves this. Logic is a treatment, not a cure-all.",
    "I know what they think. I would think it. Therefore they do. Telepathy as default. Also: other minds are unknowable so skip asking.",
    "Ask, or use a pattern of their behaviour, not a fanfic of their soul. Then still be wrong sometimes. Then a night’s delay on a text trial.",
    "A ‘they are plotting’ from a rest face is a threat bias. The digital empathy-screen path agrees about a glass."],
  ["vx-o-gettier", "Puzzles extras", "A Gettier case is a true justified belief with a luck leak; knowledge is a more annoying word than a exam wants",
    "A stopped clock that is right twice. A job of a definition. You do not need to solve it to stop treating a lucky true as a know. Courts still need a practical know.",
    "If it is true and I believe it I know. Also: knowledge is impossible, scepticism as a lifestyle. Two cop-outs.",
    "Invent a lucky true. Then whether you want the word know. Then a practical standard for a court or a clinic that cannot wait for a philosophy department.",
    "A ‘I knew it’ after a lucky guess is a Gettier folk. Sport commentary lives here. Replay is a luck leak."],
  ["vx-o-hume-habit", "Puzzles extras", "Tomorrow’s sunrise is a habit of a expectation, not a deduction from yesterday’s",
    "Induction’s itch. Science still bets. A black swan is the itch with a bird. You do not get to skip the bet and also want a plane.",
    "If it happened before it must. Deduction. Also: past is useless, skip evidence. Two planes you will not board.",
    "Name the bet. Name the miss that would update. Then still fly, with a humble face. Then a conspiracy that treats a miss as a extra moon.",
    "A ‘science was wrong before so skip this consensus’ is a induction-about-science that skips a rate of which wrongs. Rates again."],
  ["vx-o-ad-hoc-patch", "Puzzles extras", "An ad hoc patch saves a claim from a miss by adding a extra moon that does only that job",
    "Auxiliary hypotheses can be honest (a instrument error you then test). A patch you would not have mentioned without the miss is the tell. Unfalsifiable soup is a pile of patches.",
    "If they added a extra bit they cheated. Always. Also: never patch, abandon at first miss. Two cartoons of a lab.",
    "Ask whether the patch predicts a new thing. Then test that. Then a miss that only grew a moon.",
    "A ‘the aliens avoided the cameras because they know’ is a extra moon. Cameras were the test. The moon ate the test."],
  ["vx-o-prisoner", "Puzzles extras", "A prisoner’s dilemma is a dominant play that can make both worse; a repeat is a different game",
    "Nash neighbourhood without the exam algebra: the temptation, a sucker payoff. Climate and a arms race are a civic cousins. A one-shot versus a neighbour you will see tomorrow.",
    "The rational is always the nasty. Also: the rational is always the nice. Two sermons, no matrix.",
    "Write the four payoffs. Then whether you will meet again. Then a institution (a treaty, a cop) that changes the payoffs. Then still a free-rider.",
    "A group project where one person slacks is a dilemma with a rubric. Rubrics can change payoffs. Teachers already knew."],
  ["vx-o-newcomb", "Puzzles extras", "Newcomb’s box is a fight about whether a predictor breaks a causal story you liked",
    "One box or two. Expected value versus a dominance. You can use it to notice which intuition you treat as sacred. You do not have to join a cult of a box.",
    "If it is a paradox it is fake. Skip. Also: whichever box I like is the only rationality. Sacred.",
    "Name the two intuitions. Then which you would actually pick. Then a real predictor (a exam rank, a credit score) that is a pale cousin, not a alien.",
    "A credit score is a predictor that changes your options. Civic, not a alien. Still a Newcomb-ish itch."],
  ["vx-o-pascal", "Puzzles extras", "Pascal’s wager is a expected-value sermon with a extra gods problem and a belief that may not be a switch",
    "A infinite, a tiny probability, a mixing of a bet with a faith. A many-gods objection. A ‘I will just believe’ that psychology may not offer. Still a useful toy about EV versus a life.",
    "If the prize is infinite the EV is infinite so skip the odds. Hope is a number. Also: EV cannot touch a faith so skip the toy.",
    "Write the matrix with one extra god. Then a belief-as-a-switch problem. Then a real insurance that is a finite cousin.",
    "A lottery ad is a finite Pascal with a worse maths. Walk. The expected-ruin path agrees."],
  ["vx-o-straw-sign", "Fallacies extras", "A straw man is a scarecrow you built to punch; if they would not sign it, you cheated",
    "Weaken their claim, then win. Steel-man first if you are not a coward. They want to ban all cars when they wanted a bus lane is a classic. Parody is not automatically the real view.",
    "Parody is always the real view. Easier to fight. Also: steel-manning is surrender.",
    "Write their view as they would sign it. Then your attack. If they would not sign, you cheated. Then the interesting disagreement, which was the point.",
    "A so-you-are-saying that they are not saying is a straw in a comment. The digital disagree path agrees."],
  ["vx-o-slip-gears", "Fallacies extras", "A slippery slope needs grease you can show; if A then Z with no gears is a poster",
    "Sometimes slopes are real (a precedent). Then name the gears, not a cartoon. Video games to a coup is a fake. Erosion of a norm with examples can be a real slope.",
    "Any first step is Z. That is why we never change anything. Also: slopes are never real, so skip precedents.",
    "Ask for the mechanism of slide. If it is then chaos, you have a poster, not an argument. Then a real precedent chain if you have one.",
    "A mandatory-sentence floor that expands to a neighbour offence is a slope with a Hansard. Hansard is a gear."],
  ["vx-o-third-door", "Fallacies extras", "A false dilemma hides the third door; with us or against us is a poster, a binary lab test might not be",
    "A continuum, a mix. Do not invent a third to dodge a real hard choice either. Exam or failure that ignores a resit is a fake fork. Jump or burn in a fire might not be.",
    "If I name two options I have mapped the universe. Efficiency. Also: there is always a secret third, so skip hard choices.",
    "Invent a plausible third. If you can, the dilemma was a trap. If you cannot, maybe it was a real fork. Then a resit as a third.",
    "A ‘tax is theft or tax is love’ is a dilemma that skips a table. The civics budget path wants the table."],
  ["vx-o-person-or-claim", "Fallacies extras", "Attacking the person is not attacking the claim — except when the file is trust, not chemistry",
    "An insult is a miss. A conflict-of-interest is relevant to trust, not always to the reaction. A paid study is a reason to look harder, not to skip the methods section.",
    "If they are a hypocrite the claim is false. Always. Smoking doctors cannot know lungs. Also: people never matter, even a forged CV.",
    "Split: is this about the person or the reason? Keep the reason if it stands. Then a COI as a trust file.",
    "A ‘as a mother’ can be a relevant experience or a status trump. Split. The status path is next."],
  ["vx-o-scotsman-fence", "Fallacies extras", "No true Scotsman is a moving fence; fix the definition before the fight",
    "When a counterexample appears, you redefine the group to spit them out. Sometimes a definition was actually tight — then say so at the start. A no-true-fan purity spiral is a treatment case for this class.",
    "If they did a bad thing they were never really one of us. By definition. So we stay pure. Also: definitions may never tighten.",
    "Fix the definition before the fight. Then live with the members. Then a counterexample you do not expel.",
    "A ‘real Australians’ who shrink to my suburb after a vote is a fence on wheels. Fences are a civic too."],
  ["vx-o-status-sneer", "Fallacies extras", "A status-play can dress as a reason; a sneer is not a because about the world",
    "A credential flex, a in-this-house-we. Social is real. It is not a substitute for a because. Write the claim without the sneer. If nothing is left, it was a status move.",
    "The highest status person in the room is the conclusion. Primates plus a meeting. Also: status never matters, skip a relevant expertise.",
    "Write the claim without the sneer. Then a relevant expert-in-this as a different file (the authority path). Then a as-a-mother split.",
    "A ‘in this house we believe’ poster can be a value premise or a sneer. Values can be named without a sneer."],
  ["vx-o-jargon-translate", "Arguments extras", "Jargon can be a precision or a fog machine; if they cannot say it to a smart 15-year-old they might not have it",
    "A term of art versus a synergy of paradigms. Sometimes they do have it (a maths term). Test. A medical jargon to a patient can be a harm. A physics jargon to a physicist can be a kindness. Audience.",
    "Long words are smarter. Always. That is why we buy them. Also: short words are always clearer, skip needed terms.",
    "Translate. If the translation is empty, it was fog. If it is a packed sentence, it was precision. Then an audience check.",
    "A ‘synergy of paradigms’ in a school plan is a fog. A ‘contrappositive’ in this hub is a tool. Tools survive a translation."],
  ["vx-o-motivated-team", "Evidence extras", "Motivated reasoning is a brain that lawyers for the team; numerate people can be better at twisting",
    "Identity is a prior. A ritual of what would change my mind is a patch, not a personality transplant. Smart people are not unbiased by definition. IQ is not a halo.",
    "Smart people are unbiased. That is what smart means. Also: everyone is biased so skip evidence. Two cop-outs.",
    "Write the team you are on. Then a fact that would sting if true. Look for that fact on purpose. Then still a value you will not sell — name it a value.",
    "A climate or a vaccine thread is a gym. You are not immune. This path is the mirror, not a lecture for them only."],
  ["vx-o-selection-net", "Evidence extras", "A selected sample is a story about the net, not the sea; name who could not appear",
    "Survivorship (the planes that came back), a hospital, a volunteer. You met bias in maths. Logic says: name the net. A successful-people-at-5am book selected on success.",
    "If it is the data we have, it is the data that is. Missing is nothing. Also: missing means the opposite is true. Two nets.",
    "Ask who could not appear. Then the conclusion’s limit. Then a volunteer bias in a survey you liked.",
    "A ‘planes that came back’ armour story is a survivorship. The holes in the missing planes were the point. Wald’s class."],
  ["vx-o-moral-luck-split", "Puzzles extras", "A result can make a same act look like a different person; two drunk drivers, one kills",
    "We punish the result. Nagel/Williams neighbourhood. Law still uses result (murder versus attempt) — name the tension, do not pretend it vanishes. Only-the-outcome and only-the-intention are two cartoons.",
    "Only the outcome matters. Or: only the intention. Two cartoons. Also: luck is fake, skip the itch.",
    "Split the act and the luck. Then which a court should count. Civics sits next door. Then still a feeling that they got away with it.",
    "A ‘they got away with it’ versus a ‘they are a murderer’ from the same night of luck. Feel the itch. That is the path."],
  ["vx-o-is-ought", "Puzzles extras", "An is does not, by itself, mint an ought; a extra premise about a value is doing the minting",
    "Hume’s fork as a door. A ‘nature does X so we should’ is a extra. You can still argue oughts — just do not pretend the lab did the ought by itself. Hemlock is natural.",
    "If it is natural it is good. If it is a fact it is a duty. Also: facts never touch values so skip science in a policy. Two cop-outs.",
    "Star the value premise. Then whether you share it. Then a lab result as a map of a is, not a vote.",
    "A ‘the market will’ is a is with a hidden ought about who pays. Unpack. The civics climate path wants who pays."],
  ["vx-o-goodhart", "Puzzles extras", "When a measure becomes a target it can stop being a good measure; a NAPLAN as a school’s whole soul is a Goodhart",
    "Clicks as engagement, a hospital wait as a gaming of a list, a police clearance rate. Operationalisation’s dark twin. Maps that get hunted, lie harder.",
    "If we measure it we improve it. Always. Also: never measure, vibes only. Two schools of a disaster.",
    "Name the measure, the gaming you can already see, a second measure that would catch the game. Then still a number, with a adult.",
    "A ‘engagement’ that is a like is a business Goodhart. The digital time path agrees about a sugar."],
  ["vx-o-planning-fallacy", "Puzzles extras", "A planning fallacy is a inside view of a hope; the outside view is a class of similar jobs that also slipped",
    "Kahneman’s recipe: look at a reference class. A Year 12 folio due ‘Sunday’ on a Thursday. A stadium. Sunk cost often sits next door when the slip is denied.",
    "This time is different because I am motivated. Motivation is a calendar. Also: always pad until the project never starts.",
    "Name three similar jobs and their actual times. Then a pad. Then a drop of a feature rather than a fantasy of a 40-hour Sunday.",
    "A ‘she’ll be right’ about a exam timetable is a planning fallacy with a national costume. Timetables still bite."],
  ["vx-o-framing-loss", "Probability extras", "A 90% survive versus a 10% die can move a choice with the same maths; framing is a jacket",
    "Loss aversion neighbourhood. A sure loss versus a bet. Disclose the jacket. A ‘discount’ versus a ‘cash price’ is a shop of a frame.",
    "If the number is the same the choice is the same. Jackets are decoration. Also: jackets are the whole truth so skip numbers.",
    "Rewrite the option in the other jacket. See if you flip. Then a number in both jackets on a consent form.",
    "A surgery consent that only says 10% die is a jacket. 90% survive is a other jacket. Ethics wants both, not a trick."],
  ["vx-o-anchor", "Probability extras", "An anchor is a first number that drags a later guess; a ‘was it more or less than 9000’ is a hook",
    "A shop’s was-$399. A negotiation. A jury of a damages. You can notice the hook and still feel it. A outside view (a class of prices) is a patch.",
    "First numbers are a irrelevance I am immune to because I am careful. Also: first numbers are a wisdom of a crowd.",
    "Guess before you see their number, write it down. Then see theirs. Then a class of similar prices. Then still a feeling — and a written first.",
    "A ‘was-$’ that never was is a consumer civic and a anchor. The ACL path likes a photo of the shelf."],
  ["vx-o-overfit-story", "Evidence extras", "A story that fits every wiggle of a small n is a overcoat; a simple curve that predicts a next is a coat that travels",
    "Overfitting neighbourhood without the exam algebra. A sharpshooter’s bullseye after the shots. Pre-registration is a patch. A extra moon is a overfit of a miss.",
    "More parameters is more science. Fit is truth. Also: simple is always true (a fake Occam). Two coats.",
    "Ask whether the story predicted a new bit. Then a hold-out. Then a replication. Then still a mechanism you can name in a sentence.",
    "A ‘the data is the story’ of 12 mice is a overcoat. Mice plus a mechanism plus a next study is a travel coat."],
  ["vx-o-reverse-cause", "Evidence extras", "B then A can still be A caused by B in the world; a reverse is a story you should name",
    "Sick people take a medicine, therefore the medicine makes them sick — a reverse plus a indication. Ice cream and drowning can be a C. Lighters and cancer can be a C. Name three stories.",
    "If B followed A, A did B. Time is causation. Obvious. Also: time never matters.",
    "Name A→B, B→A, C→both. Then a time order you actually have. Then a intervention that would split them.",
    "A ‘people with umbrellas get wet’ is a reverse plus rain. Folk causation is a sport. The confound path shares a brain."],
  ["vx-o-mill-difference", "Evidence extras", "Mill’s method of difference is a one-knob comparison; if many knobs moved you do not have a difference, you have a mess",
    "Two classrooms, one change, a outcome. A pandemic year that changed twelve knobs is a mess. RCTs are a industrialised difference. Ethics can block a knob.",
    "If anything changed, that thing did it. Also: if you cannot randomise, you know nothing. Two cartoons.",
    "List the knobs that moved. If more than one, you need a extra design (a control, a dose). Then a humility. Then still a best available.",
    "A ‘we banned phones and grades rose’ year that also hired tutors is a two-knob. Tutors are a knob."],
  ["vx-o-use-mention", "Arguments extras", "Use versus mention is a quote-mark job; ‘no’ has two letters is a mention, no is a answer",
    "A slurs-as-analysis versus a slur-as-a-weapon. Linguistics class can mention. A playground can use. Scare quotes can be a sneak. A legal clause that mentions a word is not always using it as a performative.",
    "If it is in quotes it is harmless. Always. Also: mentioning is the same as using, so skip analysis.",
    "Ask whether the word is being talked about or done. Then a audience. Then a quote that was a sneak of a use.",
    "A classroom that pretends a taboo cannot be mentioned still has a oval. Mention with a purpose, not a performance. The languages taboo path agrees."],
]);
