import { pack } from "../pack.mjs";

export const MATHS_VOLUME = pack("maths", [
  ["vx-m-place-vs-face", "Number sense extras", "Face value is the digit; place is the chair",
    "In 4 080 the first 4 is four thousands, the 8 is eight tens. Face value of 8 is 8; place value is 80.",
    "Every 4 in a number is worth four, because 4 is 4.",
    "Name the place out loud (ones, tens, hundreds), then write the value as digit × place.",
    "4 080 and 4 008 share digits and not values. Zeros are chairs, not decoration."],
  ["vx-m-divis-three", "Number sense extras", "Divisible by 3 is a digit-sum test",
    "A number is divisible by 3 if the sum of its digits is. 147 → 1+4+7=12, and 12 is a multiple of 3.",
    "If it ends in 3 it divides by 3. Endings are the whole religion.",
    "Add the digits, repeat if you like, then check the small sum. Keep the original number for the actual divide.",
    "Divisible by 9 uses the same digit-sum idea with a stricter target. Do not mix the two."],
  ["vx-m-hcf-share", "Number sense extras", "HCF is the biggest shared factor, not the friendliest",
    "HCF/GCD of 12 and 18 is 6. It is the largest number that divides both. A Venn of prime factors is a picture, not a vibe.",
    "HCF of 12 and 18 is 12×18 because you want a big number.",
    "List factors or use primes. The overlap product is HCF; the union product is LCM.",
    "HCF of 8 and 9 is 1. They are coprime. That is a word, not an insult."],
  ["vx-m-lcm-timetable", "Number sense extras", "LCM is the next time both buses arrive",
    "LCM of 4 and 6 is 12. Least common multiple, not ‘least common factor’ (that phrase is a trap).",
    "LCM is smaller than both numbers, because least means tiny.",
    "Primes with the highest power of each, or list multiples until they meet.",
    "Two coprime numbers: LCM is the product. 8 and 9 → 72."],
  ["vx-m-prime-two-factors", "Number sense extras", "A prime has exactly two distinct factors",
    "7 is 1 and 7. 1 is not prime: it has one factor. 9 is 1,3,9 — composite. 2 is the even prime, not a scandal.",
    "Odd numbers are prime. 9 is odd so 9 is prime.",
    "Test divisibility up to the square root. Do not stop at ‘it looks prime’.",
    "1 is the lonely exception people fight about. The definition already settled it."],
  ["vx-m-bodmas-same-line", "Number sense extras", "× and ÷ share a rung; + and − share a rung",
    "Left to right on the same precedence. 8÷2×4 is 16, not 1. Brackets still win first.",
    "Always do every multiply before any divide, even if divide is on the left.",
    "Brackets, then indices, then ×÷ left to right, then +− left to right. Write the rewrite.",
    "A mnemonic is not a licence to skip left-to-right. BODMAS without that note is how 8÷2×4 becomes a meme."],
  ["vx-m-minus-minus", "Number sense extras", "Minus a minus is a plus, because direction",
    "3 − (−2) is 3 + 2. You walked left of left. −3 + (−2) is −5. The signs are a number-line story, not a decoration.",
    "Two minuses in a sentence always make a plus, including 8 − 3 − 1 = 8 + 3 + 1.",
    "Rewrite −(−) as +, then walk the line. Keep the operations in order.",
    "−(5 − 7) is −(−2) = 2. Distribute the outer minus before you panic."],
  ["vx-m-abs-distance", "Number sense extras", "Absolute value is distance from zero",
    "|−4| = 4. Distance is not negative. |a−b| is how far a is from b, either way.",
    "|−4| = −4 because the minus is still printed.",
    "Drop the sign after you know it is a distance. |3−10| = 7, not −7.",
    "Equations like |x| = −2 have no real x. Distance is not a debt."],
  ["vx-m-factor-vs-multiple", "Number sense extras", "Factors go in; multiples come out",
    "3 is a factor of 12. 12 is a multiple of 3. People swap the words and then fail a worded question.",
    "Multiples are smaller because multi- means many tiny pieces.",
    "Ask: does it divide exactly (factor) or is it in the times table (multiple)?",
    "The factors of 12 are finite. The multiples of 12 go on. That is the tell."],
  ["vx-m-estimate-first", "Number sense extras", "A rough estimate is a lie detector",
    "19.6 × 4.9 is about 20 × 5 = 100. A calculator 960 is a missed point. Estimation is not cheating; it is a check.",
    "Estimates are for people who cannot do real maths. Skip them.",
    "Round to 1 s.f. or friendly numbers, compute, then compare to the precise answer.",
    "Money: $19.95 × 3 is about $60, not $6. The dollar place is the estimate’s job."],
  ["vx-m-square-array", "Number sense extras", "A square number is an n by n array",
    "5² = 25 is a square of dots. 6² − 5² = 11, not a random jump. Squares grow by odd numbers.",
    "Squaring means multiply by 2. 5² = 10.",
    "Picture the array, or write n × n. Square root asks ‘which n?’ for a perfect square.",
    "√25 = 5 (principal). (−5)² is also 25. The extra sign is a different question."],
  ["vx-m-cube-number", "Number sense extras", "A cube is n × n × n, not n × 3",
    "2³ = 8, 3³ = 27. Volume of a cube of side 3 is 27 cubes, not 9.",
    "Cube means multiply by 3. 4³ = 12.",
    "Write the three factors. Cube root undoes it for perfect cubes.",
    "2³ is 8, not 6. The little 3 is how many n’s you multiply, not ‘add 3’."],
  ["vx-m-consecutive", "Number sense extras", "Consecutive integers differ by 1",
    "n, n+1, n+2. Their sum is 3n+3 if three of them. Even consecutives differ by 2.",
    "Consecutive means they are all even, because they hang out.",
    "Name the first n, write the next, then translate the sentence.",
    "Three consecutives that sum to 48: n+(n+1)+(n+2)=48 → n=15. Check 15+16+17."],
  ["vx-m-remainder-mod", "Number sense extras", "A remainder is leftover wholes, not a decimal",
    "17 ÷ 5 = 3 remainder 2. That is 3 + 2/5, not remainder 0.4 as a leftover object.",
    "The remainder is the decimal part of the calculator, copied.",
    "How many groups fit, what is left. Remainder must be smaller than the divisor.",
    "A remainder equal to the divisor means you had another group to take. Finish the divide."],
  ["vx-m-even-odd-product", "Number sense extras", "One even factor makes the product even",
    "Even × anything integer is even. Odd × odd is odd. 2k is the even costume.",
    "Odd × odd can be even if the numbers are big.",
    "Check one factor for a 2. For sums: even+even=even, odd+odd=even, mixed=odd.",
    "n(n+1) is always even: two consecutives, one of them even. That is a proof seed."],
  ["vx-m-equiv-frac", "Fractions extras", "Equivalent fractions are the same amount, different slices",
    "1/2 = 2/4 = 50/100. You multiplied (or divided) top and bottom by the same non-zero number.",
    "Add the same number to top and bottom to keep it equal. 1/2 = 2/3.",
    "Scale numerator and denominator together. Cancel common factors to go the other way.",
    "A pizza 2/4 is still half. The extra cuts are presentation."],
  ["vx-m-lowest-terms", "Fractions extras", "Lowest terms means the HCF of top and bottom is 1",
    "18/24 ÷6 = 3/4. You are not making it smaller in value; you are writing a neater name.",
    "Cancel any digit that matches, like the 8s in 18/24, because they look alike.",
    "Divide top and bottom by the HCF. Stop when they are coprime.",
    "6/8 is not lowest; 3/4 is. 6/8 and 3/4 are the same number."],
  ["vx-m-mixed-improper", "Fractions extras", "A mixed number is a whole plus a leftover fraction",
    "2 1/3 = 7/3 because 2 = 6/3. Improper means numerator ≥ denominator, not ‘wrong’.",
    "2 1/3 means 2 × 1/3 = 2/3. The gap is multiplication.",
    "Wholes × denominator, add the numerator. Going back: divide, remainder over denominator.",
    "A calculator 2.333… is 2 1/3 if it was a third. Repeating 3s are a clue, not a proof by themselves."],
  ["vx-m-add-unlike-den", "Fractions extras", "Unlike denominators need a common slice size",
    "1/2 + 1/3 = 3/6 + 2/6 = 5/6. The LCD is an LCM of the denominators.",
    "Add the denominators and add the numerators: 1/2+1/3=2/5.",
    "Find LCD, convert, add numerators, keep the LCD, then simplify.",
    "1/2 + 1/2 = 1, not 2/4 unless you simplify back. 2/4 is equivalent, not a different pizza."],
  ["vx-m-sub-mixed-borrow", "Fractions extras", "Subtracting mixed numbers may need a borrow of one whole",
    "5 1/4 − 2 3/4: you cannot take 3 from 1 in that costume. Rewrite 5 1/4 as 4 5/4, then subtract.",
    "Subtract wholes and fractions separately even if the fraction goes negative, and leave it.",
    "Compare the fraction bits first. If you must, break a whole into the denominator’s slices.",
    "A number line from 5.25 back by 0.75 lands at 4.5, which is 4 1/2. Check in two costumes."],
  ["vx-m-multiply-frac", "Fractions extras", "Multiply fractions: tops together, bottoms together",
    "2/3 × 4/5 = 8/15. Cancel common factors before you multiply if you want smaller numbers.",
    "Multiply means LCD first, like adding. 2/3 × 4/5 needs fifteenths before you start.",
    "Multiply numerators, multiply denominators, simplify. Of means ×.",
    "A fraction times a whole: 3 × 2/5 = 6/5. The 3 is 3/1."],
  ["vx-m-divide-reciprocal", "Fractions extras", "Dividing by a fraction is multiply by its reciprocal",
    "2/3 ÷ 4/5 = 2/3 × 5/4. You are asking how many 4/5 fit in 2/3.",
    "Keep change flip the first fraction, not the second. Or flip both for luck.",
    "Leave the first, take reciprocal of the divisor, multiply. Then simplify.",
    "6 ÷ 1/2 = 12, not 3. How many halves in 6? Twelve."],
  ["vx-m-fraction-of", "Fractions extras", "Of a quantity is multiply, then interpret the unit",
    "3/4 of 24 is 18. 3/4 of $24 is $18. The unit survives.",
    "Of means add. 3/4 of 24 is 24 + 3/4.",
    "Write ×, cancel if you can, keep the unit in the answer sentence.",
    "3/4 of a 24 m ribbon is 18 m, not 18 ribbons."],
  ["vx-m-compare-frac", "Fractions extras", "Compare fractions with a common denominator or a cross-multiply",
    "3/7 vs 2/5: 15 vs 14, so 3/7 is larger. Same numerator: bigger denominator is smaller pieces.",
    "Bigger denominator always means bigger fraction. 1/8 > 1/2 because 8 > 2.",
    "LCD or cross-multiply (positives). Benchmarks: 0, 1/2, 1.",
    "7/8 is closer to 1 than 3/8 is. Distance to 1 is the missing piece."],
  ["vx-m-reciprocal", "Fractions extras", "A reciprocal is the flip that multiplies to 1",
    "The reciprocal of 2/3 is 3/2. Of 5 is 1/5. Of 0 does not exist.",
    "Reciprocal means change the sign. Reciprocal of 2 is −2.",
    "Flip numerator and denominator. Check product is 1.",
    "Dividing is multiply by reciprocal. That is why the flip shows up."],
  ["vx-m-term-repeat-den", "Fractions extras", "Terminating decimals have only 2s and 5s in the denominator’s primes",
    "1/8 = 0.125 ends. 1/6 = 0.1666… repeats. After simplifying, look at the denominator’s prime factors.",
    "If the fraction looks simple it terminates. 1/3 looks simple.",
    "Simplify, then check 2 and 5 only for terminating (in base 10).",
    "1/7 repeats with period 6. A calculator that rounds can hide the repeat."],
  ["vx-m-frac-gt-one", "Fractions extras", "A fraction bigger than 1 is still a fraction",
    "9/4 is 2 1/4. Improper is a costume. On a number line it sits past 1.",
    "Numerators must be smaller or it is not a fraction any more.",
    "Compare to 1 by asking if numerator > denominator. Convert if the question wants mixed.",
    "9/4 of a cake is two cakes and a quarter. The language still works."],
  ["vx-m-keep-change-flip-trap", "Fractions extras", "KCF only applies to divide, and only the second fraction",
    "Keep-change-flip is a mnemonic for ÷. Using it on + or × is how 1/2 + 1/3 becomes a crime.",
    "KCF all four operations so you have a system.",
    "Name the operation first. Reciprocal only for division. LCD for +/−. Straight multiply for ×.",
    "A poster is not a theorem. If you cannot say why, do not flip."],
  ["vx-m-whole-as-frac", "Fractions extras", "A whole number is a fraction with denominator 1",
    "5 = 5/1 = 10/2. That is how 5 × 2/3 becomes 10/3 without a new rule.",
    "Wholes cannot enter fraction arithmetic until they grow a decimal point.",
    "Write n as n/1, then use the fraction rules you already have.",
    "5 − 2/3 = 15/3 − 2/3 = 13/3. Same slice size."],
  ["vx-m-cross-multiply-eq", "Fractions extras", "Cross-multiplying is for equations (and comparisons), not for adding",
    "If a/b = c/d then ad = bc (b,d ≠ 0). Adding 1/2 + 1/3 by cross-multiplying into 3+2 over 2×3 is actually LCD in a trench coat — do not confuse with equality.",
    "Cross-multiply any two fractions you see. It is a universal hammer.",
    "Use it to solve proportion equations. For addition, say LCD out loud.",
    "2/x = 5/10 → 20 = 5x → x=4. Check by substituting back."],
  ["vx-m-percent-per-hundred", "Percentages extras", "Percent is a fraction with a silent 100",
    "17% = 17/100 = 0.17. The % is not a decoration; it moved the point two places.",
    "17% means 17. The hundred is optional branding.",
    "Write /100 or move the point. Then compute. Keep % out of the middle of an algebra line unless you convert.",
    "0.17 and 17% are the same number. 17 is not."],
  ["vx-m-percent-of-find", "Percentages extras", "P% of N is P/100 × N",
    "15% of 80 is 12. 10% is a tenth; 5% is half of that. 1% is divide by 100.",
    "15% of 80 means 15 × 80 because of means times the numbers you see.",
    "Find 10%, 1%, or convert to a decimal, then multiply. Units stay with N.",
    "15% of $80 is $12, not 12%. The answer’s costume matches the quantity."],
  ["vx-m-percent-increase", "Percentages extras", "Increase by p% is multiply by (1 + p/100)",
    "A $50 ticket up 10% is $55. You add 10% of the original, not 10% of a future number you have not got.",
    "Increase 50 by 10% is 50 + 10 = 60, because 10% looks like 10.",
    "Compute p% of the original, add it. Or ×1.10 for 10%.",
    "Two 10% rises is ×1.1×1.1 = 1.21, a 21% rise, not 20%."],
  ["vx-m-percent-decrease", "Percentages extras", "Decrease by p% is multiply by (1 − p/100)",
    "A $80 jumper off 25% is $60. 25% of 80 is 20, then subtract.",
    "Off 25% means subtract 25 dollars if the tag has two digits.",
    "Find p% of original, subtract. Or ×0.75 for 25% off.",
    "A 100% decrease is 0. A 110% decrease would go negative — usually a bogus ad."],
  ["vx-m-reverse-percent", "Percentages extras", "After a change, the new amount is not the original base",
    "A price is $110 after 10% GST on the pre-GST amount: 110 = 1.1 × original, so original = 100. Do not take 10% of 110 and subtract as if that were the same tax.",
    "To undo 10% up, subtract 10% of the new price. Always.",
    "Write new = original × multiplier. Divide to go back. State which amount is 100%.",
    "A $110 bill with GST included: GST is $10, not $11. The $11 error is the trap."],
  ["vx-m-successive-pct", "Percentages extras", "Two percent changes are multipliers in a row",
    "Up 10% then down 10% is ×1.1×0.9 = 0.99, a 1% loss, not back to start.",
    "Up 10 then down 10 cancel. Percent is a polite plus and minus.",
    "Multiply the factors. Do not add the percents unless they share a base you still have.",
    "A shop that marks up 50% then ‘half price’ is not back to cost if the 50% was on cost — check which base."],
  ["vx-m-points-vs-percent", "Percentages extras", "A percentage point is a subtraction of percents, not a percent of a percent",
    "Interest from 4% to 5% rose 1 percentage point, which is a 25% relative rise. News often mixes these.",
    "From 4% to 5% is a 1% increase. Point and percent are twins.",
    "Subtract the rates for points. Divide the change by the old rate for a relative percent.",
    "Unemployment 6% to 9% is 3 points, and a 50% relative increase. Both sentences can be true."],
  ["vx-m-gst-included", "Percentages extras", "GST-inclusive divides by 1.1 in Australia’s 10% story",
    "A $22 meal with GST included: GST = 22 − 22/1.1 = $2. The 10% sits on the pre-tax amount.",
    "GST included means 10% of the till price is GST. $22 → $2.20 tax.",
    "If included, divide by 1.1 to find pre-GST. If plus GST, multiply by 1.1.",
    "The trap of 10% of the inclusive price overstates the tax. ATO-shaped questions love that."],
  ["vx-m-discount-then-gst", "Percentages extras", "Order of discount and GST is a policy, not a vibe",
    "10% off then +GST is not always GST then 10% off. The receipt’s order is the contract.",
    "Percents commute, so do them in any order. 10 and 10 are symmetric.",
    "Write the multipliers in the order the shop applies them. Check a $100 dummy.",
    "10% off then ×1.1 vs ×1.1 then 10% off can differ if the discount is on GST-inclusive vs exclusive."],
  ["vx-m-markup-vs-margin", "Percentages extras", "Markup is on cost; margin is on price",
    "Cost $40, sell $50: markup 25% on cost, margin 20% on price. Same dollars, different bases.",
    "Markup and margin are the same percent because both are profit.",
    "Ask ‘percent of what?’ Cost or selling price. Write the base.",
    "A 100% markup doubles the cost. A 100% margin would mean cost is $0. Different planets."],
  ["vx-m-percent-error", "Percentages extras", "Percentage error is |estimate − true| / true × 100%",
    "Guess 48, true 50: 4% error. The true value is the denominator, not the guess.",
    "Divide by the guess because that is the number you made.",
    "Absolute error first, divide by the true (or agreed) value, ×100%.",
    "A 2 cm error on a 4 cm insect is huge; on a 2 m snake it is not. The percent tells that."],
  ["vx-m-over-100-percent", "Percentages extras", "More than 100% is allowed; it means more than one whole",
    "150% of 80 is 120. 200% is double. 0% is none. Negative percent is a decrease in a trench coat.",
    "Percents stop at 100 because a pie cannot be 150%.",
    "Convert and multiply. 150% = 1.5. Do not cap at 1 unless the context is a share of a pie that cannot overlap.",
    "A 150% increase is ×2.5, not ×1.5. Increase vs ‘of’ is the wording trap."],
  ["vx-m-original-after-off", "Percentages extras", "Sale price is a remainder percent of original",
    "20% off means you pay 80%. Original = sale / 0.8. A $64 sale was $80, not $64 + $20.",
    "Add the off-percent of the sale price to get original. $64 + 20% of 64.",
    "Pay% = 100 − off%. Divide the sale by that decimal.",
    "Stacking ‘extra 20% off already-reduced’ is 0.8 × 0.8 if both are on the previous ticket."],
  ["vx-m-compound-two-year", "Percentages extras", "Two years of r% compound is ×(1+r)², not ×2r",
    "$1000 at 10% p.a. compound for 2 years is $1210. Simple would be $1200. The $10 is interest on interest.",
    "10% for 2 years is 20% so $1200, and compound is a bank trick that does the same.",
    "Multiply by (1+r) once per compounding period. State if it is per year.",
    "Compounding monthly is a different r/n story. Do not use the yearly button on a monthly problem."],
  ["vx-m-pie-percent", "Percentages extras", "A pie slice is a percent of 360°, not a percent of ‘looking big’",
    "20% is 72°. The area (angle) carries the percent. A 3D exploding slice is a lie of emphasis.",
    "The slice that looks fattest is the biggest percent, even if the chart is 3D.",
    "Percent × 3.6 = degrees. Check they sum to 100% before you draw.",
    "A missing ‘other’ slice is how a pie sums to 86% and still gets printed."],
  ["vx-m-one-percent-bridge", "Percentages extras", "1% is a bridge: find it, then scale",
    "If 8% is 64, then 1% is 8, and 100% is 800. This undoes ‘percent of’ when you have the part.",
    "If 8% is 64, 100% is 64. Percents are labels.",
    "Divide the known part by the known percent (as a number of percents), then ×100.",
    "8% = 64 → 100% = 800. 1% = 8. Same story."],
  ["vx-m-repeating-bar", "Decimals", "A bar over digits marks the repeat, not a highlight",
    "0.\\overline{3} = 1/3. 0.\\overline{12} = 12/99. The bar’s length is the period.",
    "A bar means ‘round these digits’. 0.\\overline{3} is 0.3.",
    "Write enough repeats to see the block, then convert with the 9s method if asked.",
    "0.1666… is 0.1 + 0.\\overline{6}, which is 1/6. Do not call it 0.16 exactly."],
  ["vx-m-compare-09-1", "Decimals", "0.09 is nine hundredths; 0.1 is one tenth",
    "0.10 = 0.1 > 0.09. Extra zeros after the last non-zero do not help 0.09 catch 0.1.",
    "0.09 is bigger than 0.1 because 9 > 1.",
    "Line up the points, fill zeros, compare place by place from the left.",
    "Money: $0.09 is 9 cents, $0.10 is 10 cents. The shop knows."],
  ["vx-m-dec-to-frac", "Decimals", "A terminating decimal is a fraction over a power of 10",
    "0.375 = 375/1000 = 3/8. Simplify. Repeating decimals need the 9s (or algebra) method.",
    "0.375 is 375/10 because there are digits.",
    "Count places for the denominator (10, 100, 1000…), then HCF-simplify.",
    "0.2 = 1/5, not 1/2. 0.5 is 1/2."],
  ["vx-m-money-round-cash", "Decimals", "Cash rounding is a 5-cent story in Australia, cards are exact",
    "A $1.97 cash total may round to $1.95 or $2.00 depending on the rule in force. Card still takes $1.97. Rounding is policy plus place.",
    "Always round money to the nearest dollar because coins are heavy.",
    "Know whether you are rounding to 5 cents or to cents. Cards and EFTPOS usually skip cash rounding.",
    "GST calculations still want cents. Rounding the tax too early drifts the receipt."],
  ["vx-m-thousandths", "Decimals", "The third decimal place is thousandths",
    "0.007 is 7 thousandths, not 7 hundredths. 7 mm is 0.007 m. The zeros are chairs.",
    "Three decimal places means thousandths, so 0.007 is bigger than 0.07 because more digits.",
    "Name tenths, hundredths, thousandths. Then compare.",
    "A 0.007 second photo finish is 7 milliseconds, not 7 hundredths of a second."],
  ["vx-m-unit-rate-60", "Ratio & rate", "Per 60 minutes is still a divide",
    "90 km in 75 minutes is 90 ÷ 1.25 = 72 km/h, or 90 × 60/75. Units have to match before you divide.",
    "90 km in 75 min is 90/75 km/h because the 60 will cancel in spirit.",
    "Convert time to hours (or km to per-minute then ×60). Write units through the calculation.",
    "A 90 km/h claim for 90 km in 90 minutes is 60 km/h. Minutes are not hours."],
  ["vx-m-best-buy-per", "Ratio & rate", "Compare cents per 100 g, not the louder pack",
    "750 g for $5.40 vs 1 kg for $6.80: per 100 g is the shop’s honest column. Prominence is marketing.",
    "The bigger pack is always cheaper per gram. That is why it is bigger.",
    "Divide price by mass in the same unit. Watch 2-for deals that assume you want two.",
    "A ‘was $8 now 2 for $11’ can lose to a single $5.50 if you only needed one."],
  ["vx-m-exchange-rate", "Ratio & rate", "An exchange rate is a multiply or a divide, pick once",
    "AUD to USD at 0.66 USD per AUD: multiply AUD by 0.66. The other way, divide. The rate’s sentence tells you.",
    "Always multiply by the rate, even when going backwards. Rates are one-way streets that work both ways.",
    "Write 1 AUD = … then scale. Invert the rate if the sentence flips.",
    "A $3 coffee in Tokyo needs the yen rate and a brain, not a vibe from a 2019 holiday."],
  ["vx-m-density-rate", "Ratio & rate", "Density is mass per volume, a rate with a name",
    "ρ = m/V. 800 g in 1 L of a liquid is 0.8 g/mL. Oil floating on water is this number talking.",
    "Denser means heavier always, even for a speck versus a boulder.",
    "Keep units: g/mL or kg/m³. Convert before you compare.",
    "A 2 kg brick and a 2 kg of feathers share mass. Density is why one is a small cube."],
  ["vx-m-map-ratio-cm", "Ratio & rate", "1 cm to 2 km is still a ratio; convert one unit first",
    "1:200 000 means 1 cm : 2 km. 4.5 cm → 9 km. Mixing cm with km without converting is the usual crash.",
    "1:200 000 means 1 cm = 200 000 km because the zeros look like distance.",
    "Convert until both sides use the same unit, then scale the measured length.",
    "A 1:25 000 bushwalk map is more zoomed in than 1:250 000. Small-scale vs large-scale is the other trap."],
  ["vx-m-part-part-whole", "Ratio & rate", "A ratio 2:3 is five parts if it is the whole",
    "2:3 of a $40 split is $16 and $24 if those parts make the whole. 2:3 can also mean 2 compared to 3 of something else — read the sentence.",
    "2:3 of 40 is 2/3 of 40. The colon is a fraction slash.",
    "Add parts only when they partition the whole. Then × each fraction of the total.",
    "A ratio of sugar to flour 1:3 is not ‘25% sugar’ of the universe, only of that mix."],
  ["vx-m-speed-average", "Ratio & rate", "Average speed is total distance over total time",
    "50 km at 50 km/h then 50 km at 100 km/h is not 75 km/h. Times are 1 h and 0.5 h, total 1.5 h, average 100/1.5 ≈ 66.7 km/h.",
    "Average the two speeds if the distances match. 50 and 100 make 75.",
    "Add distances, add times, divide. Harmonic mean if you like names.",
    "A Sydney–Melbourne split of speeds without times is a trap. You need the times."],
  ["vx-m-index-divide", "Algebra extras", "Same base divide: subtract the indices",
    "a⁷ ÷ a² = a⁵. a ≠ 0. This is the multiply rule in reverse.",
    "Divide bases, divide indices. a⁷ ÷ a² = (a/a)⁷⁻ something wait, 7/2.",
    "Write the fraction of powers, cancel a’s, or subtract exponents.",
    "a³ ÷ a³ = a⁰ = 1, not 0. Cancelling everything leaves 1."],
  ["vx-m-index-power", "Algebra extras", "A power of a power multiplies the indices",
    "(a³)⁴ = a¹². (2³)² = 8² = 64 = 2⁶, not 2⁵.",
    "Add the indices because power means more. (a³)⁴ = a⁷.",
    "Multiply the exponents. Distribute over a product: (ab)ⁿ = aⁿbⁿ.",
    "(a²b)³ = a⁶b³. The 2 only sits on a until you say otherwise."],
  ["vx-m-index-neg", "Algebra extras", "A negative index is a reciprocal, not a negative number",
    "a⁻² = 1/a². 2⁻³ = 1/8, not −8 and not −6.",
    "Negative power means negative answer. 2⁻³ = −8.",
    "Flip to a denominator and make the index positive. Then evaluate.",
    "10⁻² = 0.01. Scientific notation’s negative exponents are this rule."],
  ["vx-m-factor-quad-ac", "Algebra extras", "A quadratic ax²+bx+c wants two numbers that multiply to ac and add to b",
    "2x² + 7x + 3: numbers 6 and 1, split the middle, factor by grouping.",
    "Always factor as (2x+3)(x+1) by staring until it feels true, without a method.",
    "ac method or product-sum, then check by expanding back.",
    "If it does not factor nicely, completing the square or the formula is the adult."],
  ["vx-m-complete-square", "Algebra extras", "Completing the square is a rewrite, not a new equation",
    "x² + 6x + 5 = (x+3)² − 9 + 5 = (x+3)² − 4. You add and subtract the same square.",
    "Add (b/2)² to one side only, because squares are gifts.",
    "Take half the x-coefficient, square it, balance both sides or add-subtract in one line.",
    "Vertex form falls out: y = (x+3)² − 4, vertex (−3, −4). That is the point of the costume."],
  ["vx-m-quad-formula", "Algebra extras", "The quadratic formula is a completed square in a can",
    "x = [−b ± √(b²−4ac)] / (2a). Discriminant D = b²−4ac tells you how many real roots.",
    "The formula is ±b / 2a. The square root is extra for gifted classes.",
    "Identify a,b,c including signs, compute D, then the two (or one) x’s. Check in the original.",
    "D<0: no real roots. D=0: a repeated root. D>0: two. Complex later, not ‘no roots in the universe’."],
  ["vx-m-sim-eq-elim", "Algebra extras", "Elimination adds equations to kill a variable",
    "If 2x+3y=7 and 2x+y=3, subtract: 2y=4. Same coefficient, opposite sign, add instead.",
    "Add every system you see. Extra numbers will vanish from kindness.",
    "Scale so one variable matches, add or subtract, back-substitute. Check both originals.",
    "A pair of parallel lines (same slope, different intercept) has no solution. The algebra will contradict."],
  ["vx-m-sim-eq-sub", "Algebra extras", "Substitution is solve one, plug into the other",
    "y = 2x+1 into 3x+y=10 → 3x+(2x+1)=10. Do not substitute into the same equation you solved.",
    "Substitute into both and also into a third invented equation for luck.",
    "Isolate the easiest variable, substitute once, then find the second variable.",
    "A non-linear pair can have two intersections. A circle and a line is a later story."],
  ["vx-m-ineq-numberline", "Algebra extras", "An inequality solution is a ray (or a segment), not always a point",
    "x > 3 is an open circle at 3 and an arrow. ≤ is filled. Combining two inequalities can be an AND segment.",
    "Solve like an equation, then pick any integer you like as ‘the answer’.",
    "Do the algebra, flip if you multiplied by a negative, then draw the line.",
    "2 < x < 5 is AND, not OR. x<2 or x>5 is the outside."],
  ["vx-m-func-notation", "Algebra extras", "f(x) is a machine, not f times x",
    "f(3) means plug 3 into the rule. f(x) = x² + 1, f(3) = 10. f(x+1) is a shift, not f(x)+1 automatically.",
    "f(x) means f × x. So f(3) is 3f.",
    "Replace every x with the input, brackets on substitutions like (−2)².",
    "f(x)+2 is up; f(x+2) is left. Horizontal shifts annoy everyone once."],
  ["vx-m-seq-geometric", "Algebra extras", "A geometric sequence multiplies by the same r each step",
    "2, 6, 18, 54… r=3. Term n is arⁿ⁻¹. r can be a fraction (decay) or negative (alternating).",
    "Geometric means each term adds geometry. 2,6,12,20 because gaps grow.",
    "Divide consecutive terms to get r (if it is constant). Then write the general term.",
    "A 50% increase each year is r=1.5, not r=0.5. Decay of 50% is r=0.5."],
  ["vx-m-nth-term-lin", "Algebra extras", "The nth term of an arithmetic sequence is a + (n−1)d",
    "5, 8, 11, 14… a=5, d=3, Tₙ=3n+2. Check T₁. The ‘+2’ is not a coincidence; it is a−d.",
    "Tₙ is always n + the first term. Tₙ = n+5.",
    "Find d from a difference, write a+(n−1)d, simplify, test n=1 and n=2.",
    "Position 10 is not ‘the 10th difference’. Plug n=10 into the formula."],
  ["vx-m-alg-frac-lcd", "Algebra extras", "Algebraic fractions need a common denominator too",
    "1/x + 1/(x+1) = [(x+1)+x]/[x(x+1)]. Domain: x≠0, x≠−1.",
    "Add numerators and add denominators: 1/x+1/(x+1)=2/(2x+1).",
    "Factor, LCD, combine, simplify, state excluded values.",
    "Cancelling a factor that could be zero is how you lose a hole or a solution."],
  ["vx-m-rearrange-make-x", "Algebra extras", "Making x the subject is undoing in reverse order",
    "y = 3x+2 → y−2 = 3x → x=(y−2)/3. Inverse operations, both sides.",
    "Move the 3 first because it is next to x in the printed line, always.",
    "Undo +/− before ×÷ if they happened last (PEMDAS reverse). Check by substituting back.",
    "A formula with x on both sides needs x collected first, like an equation."],
  ["vx-m-pythag-converse", "Geometry extras", "If a²+b²=c², you have a right angle (converse)",
    "A 6-8-10 triangle is right-angled. 5-6-7 is not. The converse is a test, not a decoration.",
    "If it is a triangle, Pythagoras applies to every side as hypotenuse in turn.",
    "Square, add the two smaller, compare to the largest square. Equal means right; bigger hypot means acute, etc.",
    "Obtuse vs acute from the comparison is a useful extra: c² > a²+b² means obtuse at the join."],
  ["vx-m-trig-sohcahtoa", "Geometry extras", "SOH CAH TOA names ratios, not a triangle’s personality",
    "sin = opp/hyp, cos = adj/hyp, tan = opp/adj. The hypotenuse is opposite the right angle, always.",
    "Sine is always the smallest side over 2. It is a constant.",
    "Label opp/adj relative to the angle you own, then pick the ratio that uses the sides you have.",
    "A non-right triangle wants sine/cosine rules, not SOHCAHTOA as a hammer."],
  ["vx-m-trig-elev-dep", "Geometry extras", "Elevation is up from horizontal; depression is down",
    "Angle of elevation from your eye to a kite. Depression from a cliff to a boat. They can be equal as alternate angles on parallels.",
    "Elevation is the kite’s height in metres. Depression is weather.",
    "Draw horizontal, mark the angle, right triangle, then trig. Eye height is a length you must not skip.",
    "A 20° depression from a 40 m cliff is not tan20 = 40/x if you mixed opp and adj."],
  ["vx-m-circle-area", "Geometry extras", "Area of a circle is πr², not πd², not 2πr",
    "2πr is circumference. πr² is area. Diameter in the area formula needs r = d/2 first.",
    "Area is πd because d is the important number printed on the tin.",
    "Find r, square it, ×π. Units: cm². A sector is a fraction of that area.",
    "r=3, d=6: area 9π, not 36π. Squaring the diameter is the classic own-goal."],
  ["vx-m-sector-arc", "Geometry extras", "A sector is a pizza slice; an arc is the crust",
    "Fraction θ/360 of circumference or area (degrees). In radians, ½r²θ and rθ.",
    "Arc length is the sector area because both are ‘the curved bit’.",
    "Write the fraction of the full circle, multiply 2πr or πr². Keep degrees vs radians consistent.",
    "A 90° sector of r=4 has area 4π, not 2π. Quarter of 16π is 4π."],
  ["vx-m-similar-area", "Geometry extras", "Similar areas scale with k²; volumes with k³",
    "Lengths ×k, areas ×k², volumes ×k³. A k=2 statue uses 8 times the bronze, not 2.",
    "If it is similar, every measurement ×k, including litres and square metres.",
    "Find k from two matching lengths, then raise to 2 or 3 for the quantity’s dimension.",
    "A 1:2 model plane is 1/8 the volume. Paint (area) is 1/4."],
  ["vx-m-cong-sss", "Geometry extras", "Congruent is same shape and size; SSS/SAS/AAS/RHS are tests",
    "AAA is similar, not congruent (scale can differ). SSA is the ambiguous swamp, not a standard school ticket to trust.",
    "If three angles match, the triangles are congruent. Angles fix size.",
    "Tick a valid test with corresponding sides/angles. Write the correspondence of vertices.",
    "Corresponding means matching the equal angles, not ‘first letter of the alphabet’."],
  ["vx-m-parallel-angles", "Geometry extras", "Corresponding, alternate, co-interior: names for a transversal",
    "On parallel lines, corresponding are equal, alternate equal, co-interior add to 180°. If the lines are not parallel, stop using the club.",
    "Any two angles that look nearby are equal if the diagram is pretty.",
    "Mark the parallel arrows, name the pair, then equal or supplementary.",
    "A transversal is a line that cuts. Without it, ‘corresponding’ is a blank stare."],
  ["vx-m-interior-polygon", "Geometry extras", "Interior sum is (n−2)×180°, not n×180°",
    "A hexagon is 720°, not 1080°. Regular means equal, so divide by n for one interior angle.",
    "Each interior of a regular n-gon is 180°. Always. Hexagon is six triangles from the centre… wait.",
    "Count sides, (n−2) triangles from one vertex, ×180. Regular: divide by n.",
    "Exterior of a regular polygon: 360°/n. Interiors and one exterior at a vertex add to 180°."],
  ["vx-m-coord-distance", "Geometry extras", "Distance on the plane is Pythagoras on the run and rise",
    "d = √[(x₂−x₁)²+(y₂−y₁)²]. The squares kill the signs. Midpoint is average, a different tool.",
    "Distance is (x₂−x₁)+(y₂−y₁). Manhattan is the plane.",
    "Subtract, square, add, square-root. Leave exact surds unless asked to round.",
    "(1,2) to (4,6) is 5. A 3-4-5 triangle in costume."],
  ["vx-m-gradient-parallel", "Geometry extras", "Parallel lines share gradient; perpendiculars multiply to −1",
    "m₁ = m₂ for parallel (unless vertical). m₁m₂ = −1 for perpendicular (neither vertical/horizontal pair of axes-aligned is the −1 story; those are 0 and undefined).",
    "Perpendicular means the gradients are the same with a minus. m=2 and m=−2.",
    "Find m from two points or from y=mx+c. Compare with equal or product −1.",
    "Vertical lines have undefined gradient and are parallel to each other. They are perpendicular to horizontals."],
  ["vx-m-mode-vs-mean", "Data & chance", "The mode is the most frequent; it can be absent or many",
    "2,2,3,5,5,5,9: mode 5. Mean is a share. Bimodal is a thing. Categories can have a mode; they cannot have a mean without a hack.",
    "Mode is the middle when you are in a hurry. It is a lazy median.",
    "Tally, pick the tallest column. Say if there are two. Do not average the two modes unless a method says so.",
    "All unique values: no mode (or every value is a mode, depending on the teacher — state the convention)."],
  ["vx-m-mean-from-freq", "Data & chance", "A frequency table mean is Σ(fx)/Σf, not the mean of the x row",
    "If 10 people scored 3 and 2 scored 10, the mean is not 6.5. Weight by how many.",
    "Average the listed scores on the left column. Frequencies are artwork.",
    "Multiply value × frequency, add, divide by total frequency.",
    "Grouped data uses midpoints. That is an estimate, and you should say so."],
  ["vx-m-grouped-midpoint", "Data & chance", "A grouped mean uses the midpoint as a stand-in",
    "Class 10–20 with frequency 8 uses 15 as the ghost value. You lost the raw list; this is the cost.",
    "Use the upper bound for every class because hope is high.",
    "Midpoint × frequency, sum, divide by n. Call it an estimate.",
    "Unequal class widths make histogram heights a density story, not raw frequency as bar height."],
  ["vx-m-relative-freq", "Data & chance", "Relative frequency is a fraction of the trials, an estimate of p",
    "7 sixes in 60 rolls ≈ 7/60, not proof the die is fair or loaded by itself. More trials, closer (usually) to the model p.",
    "If you got 7/60, the true p is 7/60 forever. The die has spoken.",
    "Count / trials. Compare to the theoretical p with a grain of salt if n is small.",
    "A sample of 5 is a story, not a law. Law of large numbers wants large."],
  ["vx-m-tree-diagram", "Data & chance", "A tree multiplies along a branch, adds across alternatives",
    "With/without replacement changes the second-branch denominators. Write the probabilities on the edges.",
    "Add along a branch because the path is ‘and then’. Multiply the ends because they look separate.",
    "AND along, OR across mutually exclusive complete paths. Check the second-stage totals.",
    "Without replacement: 2 red from 5 cards then 4 left. The second fraction changes. That is the point."],
  ["vx-m-cond-prob-words", "Data & chance", "Given that is a reduced sample space",
    "P(A|B) = P(A and B)/P(B). ‘Of those who play sport, how many…’ is a row of a two-way table.",
    "Given that means multiply by P(B) again for luck.",
    "Restrict to the given, then find the fraction of that group. Or use the formula.",
    "P(music|sport) is not P(sport|music) without extra work. Order in English matters."],
  ["vx-m-quartile-split", "Data & chance", "Quartiles split an ordered list into quarters, approximately",
    "Methods differ on even n (include median or not). State the method. Q2 is the median.",
    "Quartiles are the four smallest numbers. Quarter means tiny.",
    "Order, find median, find medians of the halves per the agreed rule, then IQR = Q3−Q1.",
    "An IQR of 0 means the middle half is a spike, not that ‘there is no data’."],
  ["vx-m-std-dev-feel", "Data & chance", "Standard deviation is a typical distance from the mean",
    "A small s means a tight pack. Units match the data. It is not the range, not the IQR, not a percent unless someone standardised.",
    "Standard deviation is the average of the data. That is why it is standard.",
    "Use the calculator carefully (sample vs population). Compare spreads with the same units.",
    "A mean of 50 and s of 0 means all 50s. s cannot be negative."],
  ["vx-m-percentile-rank", "Data & chance", "A percentile is a position in an ordered crowd",
    "80th percentile of heights means 80% of the group is shorter (give or take a definition). It is not ‘80% tall’.",
    "80th percentile means 80 cm, because 80 is in the name.",
    "Order, find the location, interpolate if your method says so. Say the group.",
    "You can be 90th percentile in a small club and average in the state. The crowd is the story."],
  ["vx-m-fair-die-model", "Data & chance", "A fair model is an assumption, not a personality test of the plastic",
    "P(6)=1/6 if we model fairness. A real die can be off. The model is the ‘if’.",
    "If it came up 6 twice, the next cannot be 6. The die remembers.",
    "Write the sample space, equally likely if that is the model, then count.",
    "Gambler’s fallacy is this trap: independent rolls do not compensate."],
  ["vx-m-sample-space", "Data & chance", "The sample space is the list of possible outcomes you are using",
    "Two coins: {HH, HT, TH, TT} if order matters in your model. {2 heads, mix, 2 tails} is a different grouping with different probabilities.",
    "Two coins have 3 outcomes: 0,1,2 heads, all equally likely.",
    "List, then assign probabilities that sum to 1. Grouped outcomes are not equally likely just because there are three names.",
    "HT and TH are two of four equally likely if the coins are distinct in the model. That is why P(one head)=1/2."],
  ["vx-m-misleading-graph", "Data & chance", "A truncated y-axis is a drama machine",
    "A bar chart that starts at 48 instead of 0 makes a 50-to-52 change look like a cliff. 3D pies and dual axes are cousins.",
    "If the graph is in colour it is honest. Colour is a citation.",
    "Check zero, check scale, check whether area encodes the number. Then read the claim.",
    "A pictogram with uneven icons (one cow twice as tall, four times the area) lies in area."],
  ["vx-m-census-vs-sample", "Data & chance", "A census is everyone in the named group; a sample is a slice",
    "Australia’s Census tries a census of people in the country that night. A class poll of ‘Australians’ is a sample with a location bias.",
    "Big samples are censuses. 1000 is basically everyone.",
    "Name the population. If you missed some by design, it is a sample. Then ask how they were chosen.",
    "A voluntary web poll of 50 000 is still a volunteer sample. Size did not cure the method."],
]);
