import { pack } from "../pack.mjs";

export const MUSIC_VOLUME = pack("music", [
  ["vx-mu-anacrusis", "Time", "A pickup bar is an incomplete first bar, not a free extra beat",
    "Anacrusis: the missing beats return at the end. Counting still starts on 1 as the downbeat of a full bar. Conductors give the remaining.",
    "Pickup notes are a free intro so the first bar can be 5/4 as a vibe.",
    "Count the full bar as 1 even if you enter late. Then check the last bar completes the debt.",
    "Happy Birthday’s ‘hap-py’ is a pickup. The downbeat is BIRTH."],
  ["vx-mu-hemiola", "Time", "A hemiola is 3 against a 2-feel, a borrowed grouping",
    "Two bars of 3/4 felt as three bars of 2. Baroque cadences love it. It is not a wrong bar-line; it is a designed argument.",
    "If it feels weird the player is rushing. Feelings are a time signature.",
    "Tap the old pulse, then the new grouping, then both. Then write the brackets if you are analysing.",
    "A Leonard Bernstein 6/8–3/4 flip is a Broadway cousin. Same family."],
  ["vx-mu-swing-ratio", "Time", "Swing is a ratio of long-short, not ‘play jazzy’ as a sticker",
    "A triplet-ish 2:1 at a medium, a milder at a fast. Straight eights in a swing chart are a written exception. Listen to the ride.",
    "Swing means play late on every note. Late is a style.",
    "Hear the ride, match the ratio, then do not swing a written triplet as a double-swing. Then a recording of the year, because ratios moved.",
    "A 2010s pop ‘swing’ can be a 16th shuffle. The word is a family."],
  ["vx-mu-subdivide", "Time", "A subdivision is how you prove the beat is still there",
    "Quavers inside a slow crotchet. A fermata is a stop of the counting contract; after it, a new cue. Metronomes on the off can be a training.",
    "If it is slow you do not need a brain of smaller notes. Slow is a holiday.",
    "Set the click on the smaller. Then mute it and keep. Then a rest that is still a count.",
    "A 40 bpm adagio without a subdivision is a drunk walk. 80 on quavers is a kindness."],
  ["vx-mu-rit-vs-rubato", "Time", "Ritardando is a planned slow-down; rubato is a steal that should pay back",
    "Rall. vs a tempo. Rubato that only steals and never returns is a panic. Chopin is a argument about how much payback.",
    "Expressive means slower always. Feeling is a rit.",
    "Write where time bends, then a click after. Then do not rit every phrase ending as a default religion.",
    "A choir that rit into every comma is a soup. One rit at the end is a punctuation."],
  ["vx-mu-additive", "Time", "Additive metre is 2+2+3, not a 7/8 that you feel as a 4 with a limp",
    "Balkan, a Bartók, a progressive-rock. Accents tell the additive. A 7/8 can be 3+2+2 or 2+2+3 — pick.",
    "Odd metres are for showing off. Audiences cannot dance so it is not music.",
    "Bracket the groups, stamp them, then a melody that sits on the stamps. Then a 4/4 neighbour as a rest for the brain.",
    "Take Five is 5/4 as 3+2 in the usual. The piano pattern is the teacher."],
  ["vx-mu-double-time", "Time", "Double time is a new pulse at twice, not ‘play faster as a panic’",
    "The bar can stay while the feel chops. Half time is the cousin. Drummers change the ride, not only the BPM number on a sticker.",
    "If the BPM doubled the form doubled. Forms are a tempo.",
    "Keep the form map, change the ride. Then a chart that says double-time feel vs a new metronome mark. They differ.",
    "A metal half-time chorus is a weight. The kick pattern is the evidence."],
  ["vx-mu-fermata", "Time", "A fermata is a held event with a cut-off that someone owns",
    "The conductor (or the singer) kills it. A fermata on a rest is a silence with a wait. Ensemble fermatas without a cue are a smear.",
    "Hold until you get bored. Boredom is a duration.",
    "Watch, breathe together, cut. Then a next downbeat that is a new contract. Then do not add a rit into every fermata unless it is marked.",
    "A school choir fermata that is a competition of lungs is a texture, not a hold."],
  ["vx-mu-ostinato", "Time", "An ostinato is a stubborn loop; the interest is what changes over it",
    "A bass, a riff, a Reich. Hypnosis vs a boredom is a arrangement. Changing only the lyrics on a identical ostinato is a folk tool.",
    "Loops are cheating. Real music never repeats.",
    "Lock the loop, then a layer that moves. Then a break that proves you had a form.",
    "A didgeridoo pulse plus a changing voice is a ostinato culture, not a plugin."],
  ["vx-mu-clave", "Time", "A clave is a 3-2 or 2-3 skeleton, not a decoration shaker",
    "Son, rumba, a reverse. If the ensemble disagrees on 3-2 vs 2-3 the song is two songs. It is a organiser.",
    "Latin means add shakers until it is spicy. Spice is a timeline.",
    "Learn the 5-stroke skeleton, then sit everything on it. Then do not clap the clave as a even 4.",
    "A pop song that quotes a clave and then ignores it is a costume. Costumes still need a skeleton if you named it."],
  ["vx-mu-mixed-metre", "Time", "A mixed-metre bar is a new count, not a misprint you ‘correct’ to 4",
    "Stravinsky, a musical, a prog. The barline is a information. Counting 1-2-1-2-3 is a adult.",
    "If it is printed 5/4 the editor failed. Editors want 4.",
    "Count the new 1 every bar. Then a conductor pattern that matches. Then a click that changes.",
    "A West Side Story 6/8–3/4 flip is mixed feel. The snap is a cue."],
  ["vx-mu-polyrhythm", "Time", "A polyrhythm is two groupings at once, 3:2 as a handshake",
    "Three in the space of two. Hands apart. A 4:3 is a later. It is not a rush; it is a grid.",
    "If two people play different things it is a mistake. Unison is a professionalism.",
    "Tap one part, then the other, then both slow. Then a grid on paper (a least common).",
    "A West African bell vs a clap can be a 3:2 family. School claves can learn it without a exotic sticker as a complete lesson — still name a source."],
  ["vx-mu-backbeat", "Time", "A backbeat is 2 and 4 as a social contract in many pop/rock rooms",
    "Snare as a civic. A reggae can flip. A jazz ride can make 2 and 4 a different conversation. Do not clap 1 and 3 in a backbeat song unless you mean a gospel extra.",
    "Clap on 1, it is safer. Downbeats are a kindness always.",
    "Find 2 and 4, then a 1 that is a bass. Then a genre that wants 1 (a waltz, a some electronic).",
    "A school assembly that claps 1 and 3 on a soul tune is a texture. Teach 2 and 4 as a ear."],
  ["vx-mu-tactus", "Time", "The tactus is the pulse you actually tap, which may not be the written crotchet",
    "A 6/8 felt in 2. A 3/4 felt in 1 at a fast. Conducting patterns follow the tactus. Analysis can still name the written.",
    "The bottom number of the time signature is what you tap. Always. Maths is a pulse.",
    "Ask what a dancer would tap. Then conduct that. Then still read the written if you are sitting in a orchestra.",
    "A 12/8 shuffle felt in 4 is a blues tactus. The 12 is a subdivision."],
  ["vx-mu-asymmetric-bar", "Time", "A 5/4 bar still has a 1; it is not a floating soup",
    "Accent a internal (3+2). A Take Five piano. A Mission: Impossible. Without a internal it is a stumble of 5 equal.",
    "Odd means accent every note. Odd is a staccato law.",
    "Choose 3+2 or 2+3, mark it, lock it. Then a melody that agrees.",
    "A film ostinato in 5 can hide the barline. The kick still knows."],
  ["vx-mu-click-live", "Time", "A live click is a grid the band serves, not a jail you pretend to ignore",
    "In-ears, a latency, a drummer who is the cop. Playing ahead/behind on purpose still refers to the grid. A dropped click is a incident.",
    "If it is live it should feel human so throw the click. Human is a drift.",
    "Set the latency, a count-in, a drummer. Then a taste of ahead/behind. Then a rehearsal with the click on from bar 1, not from the drop.",
    "A school musical with a pit click and a choir without is a train wreck geography. Share the grid."],
  ["vx-mu-enharmonic", "Pitch", "Enharmonic is a same key on a piano, a different job in a key signature",
    "G♯ and A♭. In a G♯ minor world they are not twins in spelling. Voice-leading wants the spelling that moves as a letter.",
    "If it sounds the same it is the same in the score. Ears are a orthography.",
    "Spell toward the next note. Then a key signature that matches. Then a guitarist who still thinks in shapes — both hats.",
    "A chromatic run spelled as all sharps can be a kindness or a crime depending on the key."],
  ["vx-mu-tetrachord", "Pitch", "A major scale is two tetrachords of T-T-S with a tone in the gap",
    "Build from a tonic. The 7th wants the 8th. A tetrachord is a 4-note brick, not a chord of 4 automatically.",
    "Major is ‘happy’ as a definition. Feelings are a formula.",
    "Write T-T-S, gap, T-T-S. Then a different tonic. Then a minor as a different brick set.",
    "F major’s B♭ is a tetrachord job. The brick demanded it."],
  ["vx-mu-relative-minor", "Pitch", "Relative minor shares a key signature, not a personality transplant",
    "A minor is C major’s relative. The tonic moved. Parallel minor (C minor) shares a tonic, not a signature. Do not mix the words.",
    "Minor is just major but sadder on the same tonic always. Relatives are parallels.",
    "Count down 3 semitones for the relative. Then a raised 7th if it is harmonic. Then a melody that cadences in the new tonic.",
    "A pop ‘minor chorus, major verse’ can be relative or parallel. Check the tonic, not the mood sticker."],
  ["vx-mu-leading-tone", "Pitch", "A leading tone is a 7th that wants 1, a tension with a job",
    "Harmonic minor raises it. A flattened 7th (mixolydian, a blues) is a different want. Do not raise it in a modal folk if the folk did not.",
    "The 7th should always go up. Laws of gravity.",
    "Name the scale, then whether 7 is leading. Then a cadence that uses the want.",
    "A mixolydian rock riff that ‘corrects’ to a leading tone is a genre leak. Leaks can be a choice."],
  ["vx-mu-inversion-chord", "Pitch", "A inversion is a new bass, not a new identity card of the triad",
    "C/E is still C major. Figured bass as a later. Slash chords in a pop chart. The bass is a smoothness of a line.",
    "If E is in the bass it is a E chord. Bass is a root.",
    "Find the triad, then the bass as a member. Then a progression that uses inversions as a glue (a descending bass).",
    "A I–V6–vi is a bass that steps. The step is the point."],
  ["vx-mu-secondary-dom", "Pitch", "A secondary dominant is a V of a chord that is not I, a brief house move",
    "V/V is a D7 in C. It tonicises. It is not a modulation until you cadence and stay. Jazz extends this as a chain.",
    "Any 7th chord is a modulation. Sevenths are a passport.",
    "Find a chord that is a V of the next. Then a resolution. Then a still-in-C until a new signature or a cadence that stays.",
    "A ii–V–I is a tonicisation engine. The ii is a pre-V, not a random minor."],
  ["vx-mu-mode-colour", "Pitch", "A mode is a scale with a home note, not a ‘medieval sticker’ only",
    "Dorian, mixolydian as a pop/jazz everyday. The characteristic degree (♭7, ♮6) is the colour. Playing the notes without a home is a soup.",
    "Modes are for jazz geniuses. Pop cannot.",
    "Drone the tonic, then the characteristic. Then a riff that leans on it. Then do not play a leading tone that undoes the mode unless you mean a borrow.",
    "A mixolydian guitar verse that cadences with a B♭ in G is a ♭7 colour. The B♭ is the lesson."],
  ["vx-mu-pentatonic", "Pitch", "A pentatonic is 5, a subset that avoids a half-step fight",
    "Major pentatonic is 1-2-3-5-6. Minor is a relative. Blues adds a extra chromatic as a dialect. Many world systems are pentatonic without being ‘a blues’.",
    "Pentatonic means Chinese. Geography is a scale.",
    "Remove 4 and 7 from major as a start. Then a improvisation that cannot hit a wrong-ish. Then a named tradition if you are using one.",
    "A school xylophone that is a pentatonic is a pedagogy of cannot-clash. Pedagogy is a subset."],
  ["vx-mu-circle-fifths", "Pitch", "The circle of fifths is a neighbour map of signatures, not a magic roundabout",
    "Each step a sharp or a flat. Relative minors inside. Distant keys are a jump. Modulation along the circle is a smooth; a tritone jump is a jolt.",
    "The circle tells you what is in tune. Circles are a tuner.",
    "Walk one step, add a sharp. Then a piece that modulates one step. Then a jump as a drama.",
    "A song that goes to the ♭VI is a chromatic neighbour, not a circle step. Both are tools."],
  ["vx-mu-just-vs-eq", "Pitch", "Equal temperament is a compromise; a choir 3rd can still be a just-ish",
    "12 equal is a keyboard peace. A string 5th is a different peace. Barbershop 7ths. Do not retune a piano between every chord as a homework.",
    "If it is in tune on a tuner app it is in tune for a choir. Cents are a choir.",
    "Tune the fifths and thirds by ear in a unaccompanied. Then a piano as a different contract. Then a not a war.",
    "A cappella plus a piano entry is a temperament fight. Pick a boss."],
  ["vx-mu-range-voice", "Pitch", "A voice part is a range plus a colour, not a personality gender as a law",
    "Tessitura is where it lives, not a one high note. Changing voice in a teen. Transgender and countertenor exist. Write a kind range.",
    "Soprano is a girl. Biology is a clef.",
    "Check tessitura of the page, then a option. Then a not a scream as a high. Then a changing-voice dignity.",
    "A Year 9 ‘tenor’ who is a baritone in a change is a health of a larynx. Transpose."],
  ["vx-mu-transpose", "Pitch", "Transposition is a interval move of all, not a ‘play it in C because C is easy’ on a B♭ trumpet",
    "B♭ trumpet writes a C to sound a B♭. Concert pitch vs written. A choir that ‘sits too high’ can move a tone.",
    "If the player is good they can read any as C. Skill deletes transposition.",
    "Know the instrument’s interval, then a concert chord. Then a software that transposes a part, then a check of a clarinet’s extra key.",
    "A school band in a ‘all play C concert’ without a written part is a mess of fingers. Parts exist."],
  ["vx-mu-drone", "Pitch", "A drone is a unmoving pitch that makes every other note a interval against it",
    "Bagpipe, a tanpura, a folk fiddle. Harmony is a over the drone, not a Bach SATB. Changing the drone is a event.",
    "Drones are boring so they are beginner. Pedals are a fail of imagination.",
    "Hold the drone, then a melody that plays the intervals. Then a change of drone as a modulation cousin.",
    "A didgeridoo plus a voice is a drone culture. Analyse the intervals, do not only sticker ‘drone’ and leave."],
  ["vx-mu-blue-note", "Pitch", "A blue note is a flexible pitch, not a wrong note you then ‘fix’ to equal temp",
    "♭3, ♭5, ♭7 as a dialect, a slide, a scoop. Forcing it to a piano grid can be a translation. Credit the African-American history, not a ‘jazz spice’ as a complete.",
    "Blue notes are out of tune. Tuners are a ethics.",
    "Slide, then a chord that can hold it. Then a source. Then do not write a ♭3 as a mistake in a blues and ‘correct’ it.",
    "A school ‘blues scale’ sheet that never mentions a people is a extraction. Name a artist."],
  ["vx-mu-cadence-types", "Pitch", "Perfect, plagal, interrupted, imperfect: they are punctuation, not a mood ring only",
    "V–I with soprano on 1 is a textbook perfect. IV–I amen. V–vi a interrupted. A half cadence stops on V. Pop often uses a plagal-ish or a loop that refuses a full stop.",
    "Cadence means the song ended. Ends are a V–I always.",
    "Name the two chords, the soprano, then a function. Then a pop loop that is a plagal or a mixolydian that never V–I.",
    "A Amen IV–I in a school assembly is a plagal. The word Amen is a hint, not a proof."],
  ["vx-mu-adsr", "Sound", "ADSR is a envelope: a organ vs a piano vs a pad",
    "Attack, decay, sustain, release. A slap vs a swell. Synthesisers make it a knob. Acoustic still has a envelope (a bowed vs a plucked).",
    "If it is loud it has a fast attack. Loud is a envelope.",
    "Listen to the start and the tail. Then a synth that copies. Then a mix that leaves tail space.",
    "A school xylophone is a fast A, no S. A choir is a slow A. Arrange them as envelopes, not only as pitches."],
  ["vx-mu-eq-cut", "Sound", "EQ is often a cut of a mud, not a boost of a ‘more’",
    "200–500 Hz pile in a school mix. A high-pass on a vocal as a start. Boosting everything is a loudness war of a EQ.",
    "More treble is more professional. Shelves are a quality.",
    "Cut a mud, then a little air if it needs, then a reference track. Then do not EQ a bad take into a good one.",
    "A 7-mic choir without a HPF is a rumble of a air-con. The air-con is a EQ problem."],
  ["vx-mu-comp-ratio", "Sound", "Compression is a automatic volume: ratio, threshold, a attack that can kill a transient",
    "A 2:1 kiss vs a 8:1 squash. A too-fast attack on a drum is a dull. Makeup gain is a loudness costume.",
    "If it is compressed it is radio-ready. Squash is a genre of all music.",
    "Slow the attack to keep a snap, then a gentle ratio, then ears not a preset named ‘vocal god’.",
    "A school podcast with a 20:1 on a quiet student is a breathing monster. The monster is a attack/release."],
  ["vx-mu-reverb-pre", "Sound", "Pre-delay is how you keep a word before the room arrives",
    "A hall without a pre-delay is a smear of consonants. Short rooms for a rhythm, long for a pad. A reverb that is a wet 80% on a lyric is a swimming.",
    "More reverb is more emotional. Wet is a feeling.",
    "A 20–40 ms pre-delay as a start, then a send not a insert as a default, then a drier verse.",
    "A chapel recording already has a room. Adding a hall plugin is a double room. Double is a mud."],
  ["vx-mu-clip-red", "Sound", "Red clipping is a brick wall of a waveform, not a ‘hot’ professionalism",
    "Digital 0 dBFS is a ceiling. Analog tape saturation is a different (still a taste). A red school mixer is a distortion of a consonant.",
    "If it is louder it is better. Peaks are a quality.",
    "Leave a headroom, then a limiter as a last, then a not a red as a target. Then a LUFS as a later broadcast hat.",
    "A assembly track that is a square wave is a fatigue. Fatigue is a mix."],
  ["vx-mu-mic-axis", "Sound", "A microphone is a axis and a distance, a polar as a neighbour-reject",
    "Cardioid off-axis is a dull. Proximity bass. A omni in a gym is a gym. Aim the null at a monitor.",
    "If it is on a stand it will sound like the record. Stands are a Neumann.",
    "Aim, a distance, a polar. Then a not a cup of a singer’s hands as a default (it is a EQ). Then a wind on a outdoor.",
    "A choir with 8 cardioids pointing at a wall of reflections is a phase soup. Fewer, farther, a pair."],
  ["vx-mu-phase-combo", "Sound", "Two mics on a source can be a comb filter, a hollow",
    "3:1 rule as a cartoon. Flip a phase button as a test. A stereo pair is a designed, not a two-mics-because-two.",
    "More mics are more fidelity. Count is a quality.",
    "Listen in mono, then a move, then a kill of a extra mic. Then a XY/ORTF as a named pair.",
    "A snare top and bottom without a flip is a cancellation. The flip is a polarity, often called phase in the desk."],
  ["vx-mu-midi-velocity", "Sound", "MIDI velocity is a instruction of how hard, not a ‘volume knob’ only",
    "A piano library that maps velocity to a sample. A 100 on every note is a machine gun. Aftertouch is a extra. MIDI is not audio until a sound.",
    "If it is MIDI it is a fake so velocity does not matter. Fake is a flat.",
    "Draw a human-ish velocity, then a slight timing, then a not a quantise to 100% as a religion.",
    "A school ‘MIDI trumpet’ on a ff with a velocity 40 is a mismatch of a marking. Markings want a map."],
  ["vx-mu-freq-range", "Sound", "Instruments own neighbourhoods; a mix is a seating plan",
    "Kick vs bass, a vocal vs a guitar 2–4 kHz fight. Panning is a extra seat. A all-centre wall is a school default.",
    "If they are in tune they cannot fight. Pitch is a EQ.",
    "Carve with a cut, then a pan, then a arrangement that is a less notes. Then a reference.",
    "A sax and a vocal in the same 1 kHz is a arrangement problem first. Arrange, then EQ."],
  ["vx-mu-monitor-foldback", "Sound", "Foldback is what they hear, not what the room hears",
    "A wedge that is a scream of a vocal is a feedback. In-ears are a isolation with a mix that can be too dry. A choir that only hears a piano in a delay is a late.",
    "If it is loud on stage it is loud enough. Stage is a FOH.",
    "Less on the wedge, a ring-out, a talkback. Then a not a extra mic as a ‘more me’ first move.",
    "A feedback at 2 kHz is a polar plus a gain. Ring it, cut a narrow, then a still a technique of a singer."],
  ["vx-mu-hearing-dose", "Sound", "Hearing is a dose: a time × a dB, not a ‘I will rest it later’ as a infinite",
    "In-ear isolation can let you turn down. A foam. A 90 dB rehearsal of 4 hours is a file. Tinnitus as a extra.",
    "If it is music it is safe. Art is a NRR.",
    "A plug, a quieter, a break. Then a not a earbud at a max on a bus as a extra dose. Then a audiology if a ring stays.",
    "A drummer without a shield or a plug is a occupational. Occupations have a PPE."],
  ["vx-mu-di-box", "Sound", "A DI is a impedance and a earth lift, not a ‘guitar into the desk’ as a hope",
    "Passive vs active. A ground loop hum. A split to a amp. A bass DI plus a mic is a blend with a phase.",
    "If it is a jack it can go in a XLR hole with a adapter and a prayer. Adapters are a DI.",
    "DI, a lift if it hums, a pad. Then a not a guitar cable of 20 m as a antenna.",
    "A school keyboard into a mic input is a mismatch of a level. DI is a match."],
  ["vx-mu-stereo-mono", "Sound", "A stereo that collapses to a hole in mono is a phase crime",
    "Club PA, a phone speaker, a AM radio as a mono. A wide chorus plugin that is a out-of-phase. Check mono.",
    "Stereo is always better. Width is a professionalism.",
    "Hit the mono button, then a width that survives. Then a not a 100% ping-pong on a vocal as a default.",
    "A assembly hall that is a one-column PA is a mono. Your wide synth vanished. Check."],
  ["vx-mu-noise-floor", "Sound", "A noise floor is a hiss of a preamp plus a room plus a computer",
    "Gain staging: enough to hide the hiss, not a clip. A gate as a extra. A ‘denoise’ plugin that chews a consonant is a trade.",
    "If you hear a hiss the take is ruined. Hiss is a fail of a musician.",
    "Set a gain, a close mic, a quiet computer. Then a not a 80 dB of a denoise as a first.",
    "A laptop fan in a quiet guitar take is a floor. Move the laptop. Floors are a geography."],
  ["vx-mu-cue-mix", "Sound", "A cue mix is a headphone world; a too-loud click can steal a dynamic",
    "Singers push against a loud cans. Latency in a interface. A 0 ms monitoring as a direct. A late cans is a drunk timing.",
    "If they can hear they will sing in tune. Volume is a pitch.",
    "A reasonable cans, a direct monitor, a click that is a tick not a club. Then a not a full FOH in the cans as a default.",
    "A 8 ms round-trip is a smear of a tight riff. Buffer is a time."],
  ["vx-mu-blend-vowels", "Ensemble", "A blend is a vowel family, not a volume war of a loudest soprano",
    "Same [a], a tall, a not a chew. A section that is a 5 diphthongs is a chorus of a different words. Dynamics as a extra.",
    "If everyone is loud it blends. Forte is a blend.",
    "One vowel, a circle, a record. Then a not a ‘more’ as a first note. Then a seating of a matching colour.",
    "A Australian ‘dance’ vowel vs a RP in a English anthem is a blend fight. Pick a dialect for the piece."],
  ["vx-mu-count-in", "Ensemble", "A count-in is a tempo and a prep, not a ‘1-2-3-go’ of a different speed",
    "The last two beats of a count are the tempo. A breath on 4. A conductor’s prep beat. A dropped count in a exam is a incident.",
    "Count as fast as you are nervous. Nerves are a metronome.",
    "Count in the tempo of the piece, a clear 1, then a start that is not a extra 5. Then a not a ‘yeah’ as a extra beat.",
    "A jazz head that is a finger snap on 2 and 4 as a count is a dialect. Snaps are a tempo."],
  ["vx-mu-tuning-temp", "Ensemble", "Tuning is a moving target: a cold hall, a hot gym, a wind",
    "A=440 vs a 442. A brass that sharpens as it warms. A retune after a interval. A piano that cannot move so you move.",
    "If you tuned at 9 am you are done. Tuning is a morning.",
    "A note, a drift, a retune. Then a not a electronic drone that nobody listens to as a ritual only.",
    "A outdoor carols in a wind is a pitch and a clothespin. Weather is a ensemble."],
  ["vx-mu-inner-part", "Ensemble", "An inner part is a harmony job, not a failed melody you should ‘correct’ to the tune",
    "Alto that is a 3rd. A pride of a inner. Balance so the tune still leads unless the inner is a featured. Choir SATB is a social.",
    "If you cannot hear yourself you should sing louder than the tune. Self is a blend.",
    "Know the function (3rd, 7th), then a less, then a pride. Then a not a jump to the melody as a safety.",
    "A school ‘everyone knows the tune’ on a SATB is a unison. Unison is a different piece."],
  ["vx-mu-rehearsal-mark", "Ensemble", "A rehearsal mark is a GPS, not a decoration of a letter",
    "Start at C, a bar number as a extra. A conductor who says ‘the bit that goes dun-dun’ wastes a hour. Pencils.",
    "If you know the piece you do not need letters. Memory is a score.",
    "Number, a mark, a pencil of a breath. Then a not a start from the top as a religion of a 2-hour.",
    "A 90-bar start-from-top to fix bar 88 is a pedagogy of a freeze. Marks exist."],
  ["vx-mu-cut-off", "Ensemble", "A cut-off is a consonant and a eye, not a fade of a 12 extra beats",
    "T’s together. A conductor’s close. A fermata cut. A recording without a cut is a amateur tail of a noise.",
    "End when you run out of air. Air is a barline.",
    "Watch, a consonant on a rest, a still. Then a not a hum after. Then a page turn that is not a extra note.",
    "A Amen that is a 8 different t’s is a texture of a mess. One t."],
  ["vx-mu-balance-melody", "Ensemble", "Balance is a seating and a dynamic, a social skill of a who has the tune",
    "Accompaniment vs a solo. A brass that is a default f. A string that is a default p in a school. A conductor’s palm.",
    "If it is my favourite line it should be loudest. Favourites are a mix.",
    "Who has the tune, then a less of a other, then a seat. Then a not a ‘all f’ as a exciting.",
    "A sax section that is a wall in front of a singer is a geography. Move, or a dynamic."],
  ["vx-mu-chamber-cue", "Ensemble", "A chamber cue is a breath and a body, not a conductor as a missing parent",
    "Eye, a sniff, a cello’s bow. A quartet. A lack of a eye is a late entry of a 2nd violin.",
    "If there is no conductor you just start when you feel. Feelings are a upbeat.",
    "Assign a leader of a moment, a look, a breath. Then a not a nod that is a 5 different times.",
    "A flute trio that stares at the floor is a three solos. Eyes are a barline."],
  ["vx-mu-section-lead", "Ensemble", "A section leader is a bowing and a style, not a loudest ego",
    "Strings: a bowing that is a unified. Brass: a mute as a together. A leader who listens. A democracy of a wrong bowing is still a wrong.",
    "The best player should drown the section so it is in tune. Loud is a tune.",
    "Copy the leader’s bow/articulation, then a question in a rehearsal not in a concert. Then a not a rogue accent.",
    "A violin 1 that is a 8 bowings in a 8 stands is a texture of a scratch. Pencil the leader."],
  ["vx-mu-pit-orchestra", "Ensemble", "A pit is a balance under a singer, a click, a sightline of a MD",
    "Shorter, a mute, a not a concert f. A delay of a vocal foldback. A scene change that is a vamp.",
    "If it is a musical you play like a symphony. Pits are a Carnegie.",
    "Watch the MD, a dynamic under a word, a vamp until a cue. Then a not a solo that is a 16 bars because you can.",
    "A pit trumpet into a singer’s mic is a bleed. Bleed is a polar and a dynamic."],
  ["vx-mu-choir-divisi", "Ensemble", "A divisi is a split, a who-sings-what, not a ‘all sing both’ as a cluster",
    "Soprano I/II. A balance of a split. A small choir that is a 1 on a divisi is a hole. A unison marking is a gift.",
    "Divisi means louder because more notes. More is a f.",
    "Assign, a count of a bodies, a simplify if a 2-on-a-part. Then a not a guess in a concert.",
    "A SSAATTBB on a 18-choir is a optimism. Reduce. Optimism is a cluster."],
  ["vx-mu-call-response", "Ensemble", "A call and response is a conversation, a time to leave a hole",
    "Gospel, a work song, a jazz. The response can be a identical or a comment. A overlapping that is a designed. Credit a source.",
    "If you know the tune you sing over the call. Knowledge is a texture of a pile.",
    "Leave the hole, then a in-time, then a not a fill of a every gap as a nervous. Then a named tradition.",
    "A school ‘African call and response’ without a people is a extraction. Name a song and a place."],
  ["vx-mu-drone-ensemble", "Ensemble", "A drone in a group is a tuning of a everyone to a one, a social pitch",
    "A tanpura, a pipe, a synth. If the drone is a out, the ensemble is a out. Who owns the drone’s pitch.",
    "Drones are a background so they can be a wrong. Background is a optional pitch.",
    "Tune to the drone, then a do not retune a other A. Then a volume of a drone that is a bed not a solo.",
    "A bagpipe plus a choir is a temperament fight. Pick a boss pitch."],
  ["vx-mu-form-map", "Listening", "A form map is a letter: AABA, a 12-bar, a through-composed",
    "Listen for a return. A bridge that is a B. A coda. Pop’s verse-chorus is a map with a pre-chorus as a extra letter. Do not call everything a rondo as a panic.",
    "If it repeats it is a verse. Repeats are a form name.",
    "Write letters as you go, then a timestamp. Then a not a Wikipedia as a first listen — listen, then check.",
    "A 32-bar AABA is a jazz standard neighbourhood. The bridge is a 8 that feels like a away."],
  ["vx-mu-motif-develop", "Listening", "A motif is a small cell that gets a job: sequence, invert, a fragment",
    "Beethoven 5 as a cartoon. A film leitmotif. Development is a work, not a new tune every 4 bars as a only tool.",
    "If it is catchy it is a motif. Catchy is a analysis.",
    "Hum the cell, then find a mutation. Then a timestamp. Then a not a every note as a motif (then nothing is).",
    "A Jaws two-note is a motif of a interval. The interval is the shark."],
  ["vx-mu-genre-contract", "Listening", "A genre is a contract of drums, a harmonic speed, a vocal",
    "A trap hat, a four-on-the-floor, a 12-bar. Crossing a contract is a fusion or a fail of a expectation. Contracts date (a 1962 vs a 2022 pop).",
    "Genre is a prison of a snob. Real music has no drums rules.",
    "Name 3 promises, then a keep or a break. Then a year. Then a not a ‘this has no genre’ as a analysis (that is a genre of a claim).",
    "A country song with a 808 is a contract mash. Mash is a interesting if you can name both contracts."],
  ["vx-mu-diegetic", "Listening", "Diegetic is in the world of the picture; underscore is a comment",
    "A radio in a car vs a orchestra they cannot hear. A switch can be a joke (a character starts to sing the underscore). Games: a adaptive that is a state.",
    "If it is in a film it is background. Background is a diegetic.",
    "Ask: can a character hear it? Then a function. Then a switch as a extra.",
    "A Baby Driver chase that is a diegetic-ish radio is a designed. The designed is a analysis."],
  ["vx-mu-texture-words", "Listening", "Monophony, homophony, polyphony, a heterophony: they are a count of a stories",
    "One line, a chordal, a independent, a simultaneous variants. A pop vocal plus a pads is a homophony with a extra. A fugue is a polyphony of a job.",
    "If there are many instruments it is polyphony. Count is a texture.",
    "Count independent tunes, then a word. Then a change of a texture as a event (a drop to a unison).",
    "A heterophonic folk (a many versions of a one tune) is not a ‘they cannot play together’. It is a texture."],
  ["vx-mu-hook-constraint", "Listening", "A hook is memorable under a constraint of a time and a range",
    "A 3-note, a lyric stress, a syncopation. A 12-bar guitar that is a riff. A hook that is a 2-octave is a less singable in a pub.",
    "Hooks are cheap so they are not art. Art is a through-composed only.",
    "Hum it after one hear, then a why (a rhythm, a interval). Then a constraint (a word on a 1).",
    "A ‘Nah’ of a 2010s pop is a hook of a phonetic. Phonetics are a melody."],
  ["vx-mu-lyric-stress", "Listening", "A lyric needs a stress that matches a English (or a other language) stress",
    "A ‘the’ on a 1 is a bump. A melisma that is a designed. A translation that wrecks a stress is a new song.",
    "If the word is important it goes on a high note always. Height is a grammar.",
    "Speak the line, then a sing, then a move a word. Then a not a squeeze of a 8 syllables into a 3-beat as a default.",
    "A ‘Austraya’ vs a ‘Australia’ in a anthem is a dialect of a stress. Pick for the choir."],
  ["vx-mu-au-more-than-pub", "Listening", "Australian music is a many: a art music, a hip-hop, a First Nations, a pub as a one chapter",
    "A Yothu Yindi, a Sia, a Elena Kats-Chernin, a Baker Boy. A ‘Aussie music’ as a pub-only is a curriculum fail. Country as a First Peoples, not a empty.",
    "Australian means a chorus of a motel. Motels are a canon.",
    "Name a work that is not a pub, then a context. Then a not a token one slide. Then a living culture rule if a song is a restricted.",
    "A school ‘Waltzing Matilda’ as a complete is a 19th-century costume. Costumes are a chapter."],
  ["vx-mu-world-not-spice", "Listening", "A ‘world music’ bin is a industry, not a analysis; name a people and a function",
    "A wedding, a protest, a court. A sample without a credit is a extraction. A pentatonic is not a ‘exotic’ as a complete.",
    "If it is not Western it is a percussion and a drone. West is a default of a real.",
    "Name the language, the job of the music, a source. Then a not a ‘ethnic’ as a adjective of a drum.",
    "A Gamelan is a court and a community, not a ‘bells’ in a GCSE-ish sticker. Stickers are a fail."],
  ["vx-mu-score-map", "Listening", "A score is a map: a transposing part, a octave, a not a photo of a air",
    "What you see is a instruction. A sounding pitch. A guitar 8vb. A analysis from a reduction that lost a inner.",
    "The score is the music. Paper is a performance.",
    "Check a clef, a transpose, a sounding. Then a recording as a extra map. Then a not a piano reduction as a full orchestration truth.",
    "A horn in F that looks like a C is a concert B♭. Looking is a trap."],
  ["vx-mu-critique-because", "Listening", "A critique is a evidence plus a because, not a ‘I liked it’ as a complete",
    "A timestamp, a parameter (a texture, a mix, a lyric). A taste is a extra sentence, not a banned. A ‘objectively good’ is a fight.",
    "If I felt it the analysis is done. Feelings are a rubric.",
    "Timestamp, a term, a function. Then a taste if you want. Then a not a artist-insult as a extra.",
    "A ‘the drop slapped’ without a 1:12 and a bass filter is a vibe. Vibes are a start."],
  ["vx-mu-silence-event", "Listening", "A rest is a written event; a general pause is a drama of a zero",
    "A G.P. A jazz stop-time. A pop filter-drop. A school band that fills a rest is a nervous texture.",
    "Silence is a nothing so it cannot be a composition. Zeros are a empty.",
    "Count the rest, then a still. Then a not a cough as a extra instrument. Then a analysis of a why the zero.",
    "Cage’s four-thirty-three is a frame of ambient sound. The frame is the piece. Do not only joke it."],
  ["vx-mu-program-music", "Listening", "Program music points at a extra-musical; absolute refuses a story as a must",
    "A symphony of a Faust vs a ‘Symphony in C’. A listener can still story a absolute. A composer’s title is a clue, not a police of your ear forever.",
    "All music tells a story of a battle. Stories are a law of a notes.",
    "Read the title, then a if it is a need. Then a parameter that would work without a story too.",
    "A Pastoral symphony is a program. A listener who hears a creek is a allowed, not a exam of a correct creek."],
  ["vx-mu-leitmotif", "Listening", "A leitmotif is a ID of a character or a idea that mutates",
    "Wagner as a cartoon, a film as a everyday (a Hedwig, a Imperial). A mutation (a minor, a thin) is a narrative. A motif that never changes is a logo.",
    "If a theme returns it is a leitmotif. Returns are a ID.",
    "Name the idea, a first hear, a mutation at a timestamp. Then a not a every chord as a person.",
    "A ring theme that is a brass then a broken is a mutation of a power. Mutation is a plot."],
  ["vx-mu-practice-loop", "Craft", "Practice is a loop: a small, a right, a then faster — not a hour of a slop",
    "A 4-bar, a 80%, a metronome. A mistake that is a repeated is a practice of a mistake. A phone is a enemy of a loop.",
    "Longer is better. Hours are a skill.",
    "Isolate, a slow right, a notch up. Then a not a start-from-the-top as a 40-minute. Then a note of a what failed.",
    "A 20-minute of a bar 47 is a adult. A 20-minute of a whole piece with a crash at 47 is a 19-minute of a lie."],
  ["vx-mu-slow-right", "Craft", "Slow is a microscope; fast is a result, not a method",
    "A brain that is a fast slop encodes a slop. A dotted rhythm at a slow. A then a in-tempo as a test, not as a only.",
    "If I cannot play it fast I should play it fast more. Speed is a teacher.",
    "Half, a right, a 10% up. Then a not a 100% jump. Then a rest of a brain.",
    "A semiquaver run at a adagio that is a even is a win. The allegro is a later."],
  ["vx-mu-chunking", "Craft", "A chunk is a bar-group the brain can hold, not a page as a only unit",
    "A 2-bar, a link, a overlapping. A memory that is a muscle plus a analysis (a chord). A random start in a middle is a test of a chunk.",
    "Memorise from bar 1 always. Order is a memory.",
    "Chunk, a link, a random entry. Then a not a panic of a blank as a only start-over.",
    "A concerto that is a 12 chunks with a join is a map. Maps beat a fog of a 20 pages."],
  ["vx-mu-perf-arousal", "Craft", "Performance is a different skill: a arousal, a recovery, a not a bedroom",
    "A dry mouth, a tempo that is a 8% up. A run-through in a hall. A mistake protocol (a keep, a smile of a not a face of a crash).",
    "If you can play it in a bedroom you can play it in a hall. Rooms are a optional.",
    "A mock, a clothes, a start of a piece not a bar 40. Then a recovery of a next bar. Then a not a stop-and-swear.",
    "A exam that is a 3-minute of a 0-mistake religion is a different to a gig that is a communication. Know which hat."],
  ["vx-mu-copyright-song", "Craft", "A song is a property: a composition and a recording are a two",
    "A cover licence, a sample, a school APRA as a extra. A TikTok that is a loud is still a property. A ‘I changed 2 notes’ is a not a automatic legal.",
    "If it is on the internet it is free. Internet is a public domain.",
    "Assume it is owned, then a licence, a credit. Then a not a whole track as a backing of a exam without a path.",
    "A school musical that is a bootleg of a Broadway is a incident. Incident is a letter from a publisher."],
  ["vx-mu-lead-sheet", "Craft", "A lead sheet is a melody plus a chord, a job of a arranger in a head",
    "A Nashville number as a extra. A slash. A not a full orchestration. A ‘play C’ that is a 8 different textures.",
    "If the chords are there the piano should play a wall of a 4 notes every beat. Walls are a lead sheet.",
    "Melody, a change, a rest. Then a texture that is a not a block. Then a bass that is a root as a start, a inversion as a later.",
    "A jazz lead sheet that is a ‘C7’ is a world of a voicing. Worlds are a craft."],
  ["vx-mu-bowing-mark", "Craft", "A bowing is a articulation and a string, not a decoration of a u/n",
    "A down-bow on a downbeat as a default of a some. A hooked. A not a every note as a separate as a default of a panic.",
    "Bowings are a optional if you feel. Feelings are a section.",
    "Copy a leader, a pencil, a not a change in a concert. Then a retake that is a breath of a bow.",
    "A school orchestra of a 8 bowings is a scratch chorus. Pencil is a blend."],
  ["vx-mu-fingering-edit", "Craft", "A fingering is a editor’s suggestion, a hand that is a yours may differ",
    "A 4-3 that is a edition. A small hand. A pencil of a better. A not a ink as a sacred.",
    "Printed fingerings are a law. Editors are a composer.",
    "Try, a change, a consistent. Then a not a different fingering every bar of a same pattern.",
    "A Grade piece with a 1 on a black key that is a stretch is a optional. Optional is a pain save."],
  ["vx-mu-annotation", "Craft", "A pencil is a memory of a breath, a dynamic, a not a vandal of a hire score",
    "A photocopy law as a extra. A sticky. A not a highlighter through a staff as a only. A hire that is a erase.",
    "If it is mine I can ink. Ink is a always.",
    "Pencil, a meaning, a erase of a hire. Then a not a 12 colours as a rainbow of a none meaning.",
    "A borrowed orchestral part with a ink of a 1994 is a archaeology. Archaeology is a other person’s breath."],
  ["vx-mu-backing-limit", "Craft", "A backing track is a grid that will not wait; a live is a wait",
    "A count that is a buried. A key that is a wrong of a 1 semitone of a download. A click in a ear. A not a karaoke of a missing a instrument you needed.",
    "If it is a track it is a easy. Tracks are a safety.",
    "A check of a key, a count, a fail plan (a unplug). Then a not a 100% of a exam as a only if a rule bans.",
    "A eisteddfod that is a track of a 0.5% slow is a drunk. Check a BPM."],
  ["vx-mu-arrange-thin", "Craft", "An arrangement is a thin of a texture, a who-stops, a not a all-play-all",
    "A verse that is a guitar. A chorus that is a add. A drop. A school arrangement that is a tutti of a 32 bars is a fatigue.",
    "More instruments are more arrangement. Count is a craft.",
    "A who-plays-map, a rest as a event, a feature. Then a not a doubling of a 8 octaves as a default.",
    "A sax that is a unison of a vocal of a whole song is a karaoke of a extra. Unison is a texture of a one, still a pile of a timbre."],
  ["vx-mu-click-practise", "Craft", "A click in a practice is a truth-teller; a musical time still refers to it",
    "A behind, a ahead as a taste once it exists. A 100% quantise of a MIDI is a different to a human plus a click. A drop of a click is a skill of a keep.",
    "Clicks make you robotic. Robots are a unmusical always.",
    "A week of a click, a then a off, a then a taste. Then a not a only-off as a ‘I am expressive’ of a 20% drift.",
    "A drummer who is a click and a band who is a not is a train wreck. Share."],
  ["vx-mu-score-study", "Craft", "A score study without a instrument is a hearing of a inner",
    "A harmonic, a cue, a transpose. A conductor. A not a only a recording as a first (a recording is a one interpretation).",
    "If you cannot play it you cannot study it. Hands are a analysis.",
    "A silent read, a piano reduction as a extra, a then a record. Then a not a Wikipedia form as a only.",
    "A horn cue that is a concert vs a written is a study of a transpose. Study saves a rehearsal minute."],
  ["vx-mu-tritone-sub", "Pitch", "A tritone substitution is a dominant with a shared 3rd and 7th, a jazz house move",
    "D♭7 for G7 in C. The bass jumps a half-step down in a ii–V. It is not a random chromatic. Voice-leading is the why.",
    "Any chord a tritone away is a substitute. Distance is a function.",
    "Find a V, swap a bass a tritone, keep a 3rd/7th. Then a still-resolve to I. Then a not a every bar as a sub.",
    "A ‘tritone’ as a devil interval in a medieval sticker is a different ticket. This is a functional bass."],
  ["vx-mu-overtone", "Sound", "An overtone is a extra frequency that is a timbre, not a extra note you wrote",
    "A 2nd harmonic is a octave. A brass that is a missing fundamental as a party trick. A EQ that is a harmonic neighbourhood.",
    "Timbre is a mystery unrelated to a spectrum. Magic is a FFT.",
    "Hear a harmonic on a string, then a brass. Then a not a ‘warm’ as a only word — say a even/odd as a start.",
    "A distorted guitar is a extra harmonics. Distortion is a spectrum, not a volume only."],
  ["vx-mu-vamp", "Ensemble", "A vamp is a loop until a cue, a pit and a jazz tool",
    "A MD’s nod. A not a 32 extra of a panic. A singer who is a late of a costume. A still a in-time.",
    "Vamp means play as loud as a end. Ends are a vamp.",
    "A agreed groove, a eye, a out-bar that is a planned. Then a not a new fill every repeat as a default.",
    "A panto ‘he’s behind you’ is a vamp culture. Cues are a civic of a pit."],
  ["vx-mu-sonata-cartoon", "Listening", "A sonata form is a exposition–development–recap cartoon, a argument not a sandwich law",
    "A two themes, a modulate, a work, a home. A 19th-century that is a stretched. A not a every first movement as a perfect sandwich.",
    "Sonata means a piano. Forms are a instrument.",
    "Find a away and a home, then a work in a middle. Then a coda as a extra. Then a not a Wikipedia as a listen-replacement.",
    "A pop song is not a sonata for a fail of a recap. Different contract."],
  ["vx-mu-12bar-map", "Listening", "A 12-bar is a I–I–I–I–IV–IV–I–I–V–IV–I–V neighbourhood with dialects",
    "A quick four, a minor blues, a jazz extra ii–V. A lyric that is a AAB. Credit a history, not a ‘easy chords’ as a complete.",
    "12-bar means 12 bars of a one chord. Bars are a number only.",
    "Count 12, a chord of a bar, a turnaround. Then a artist. Then a not a ‘blues scale over a major’ as a only without a ear.",
    "A school ‘blues’ that is a 8-bar is a other neighbourhood. Count."],
  ["vx-mu-sightread-eye", "Craft", "Sight-reading is a eye ahead, a not a stare of a now-note",
    "A window of a 1–2 beats. A pattern (a scale, a arpeggio). A keep going as a law of a exam. A not a stop-and-fix as a default.",
    "If you look at a finger you will read. Fingers are a score.",
    "Scan a key, a time, a hardest bar. Then a ahead. Then a not a 0-mistake religion of a first read.",
    "A exam that is a stop at a error is a fail of a keep. Keep is a mark."],
  ["vx-mu-dynamic-plan", "Craft", "A dynamic plan is a architecture, a not a mf as a life",
    "A terrace vs a swell. A terraced Baroque as a cartoon. A romantic that is a wave. A school default mf is a fog.",
    "Loud is exciting so f is a default of a concert. Excitement is a dynamic.",
    "Pencil a shape of a phrase, a peak, a then a not a every downbeat as a accent of a extra.",
    "A 32-bar of a mf is a brochure. Architecture is a interest."],
  ["vx-mu-articulation", "Craft", "A staccato is a space, a tenuto a full, a accent a front — they are not a random dots",
    "A style of a era (a Baroque short vs a Romantic). A matching of a section. A not a staccato as a faster.",
    "Dots mean play as short as a flea always. Fleas are a period.",
    "Match a style, a section, a bow/tongue. Then a not a mix of a 8 lengths as a ‘expressive’.",
    "A Mozart that is a heavy Martelé is a era leak. Leak can be a choice if you name it."],
  ["vx-mu-rest-count", "Craft", "A multi-bar rest is a still a count, a cue that is a neighbour",
    "A 24-bar of a horn. A cue of a flute. A not a phone as a extra. A concert that is a late of a 1 is a 24 of a fail.",
    "If you are not playing you are off. Off is a rest of a brain.",
    "Count, a cue, a prep of a 2 bars. Then a not a chat. Then a not a 25.",
    "A school brass that is a chat of a 16 is a entry of a smear. Chats are a rest fail."],
  ["vx-mu-page-turn", "Craft", "A page turn is a arranged rest, a copy, a not a crash of a left hand",
    "A photocopied (a law), a extra bar, a silent turn. A orchestra hire that is a bad turn is a pencil of a copy.",
    "Turn as fast as a panic. Panic is a rest.",
    "A copy, a early, a silent. Then a not a 1/16 of a extra as a turn. Then a digital as a extra hat.",
    "A piano exam that is a 0-time turn is a fail of a copy. Copies are a craft."],
]);
