import { pack } from "../pack.mjs";

export const SCIENCE_VOLUME = pack("science", [
  ["vx-s-closed-mass", "Matter extras", "Mass is conserved in a closed flask, even when the look changes",
    "A precipitate or a gas still has mass. If the flask is closed, the total does not vanish because the mixture went cloudy.",
    "Fizzing means mass left the universe. The bubbles ate it.",
    "Close the system, weigh before and after. If gas can leave, you weighed an open story.",
    "Burning steel wool in air gains mass because oxygen joins. The extra was in the room."],
  ["vx-s-shells-not-orbits", "Matter extras", "Electron shells are energy addresses, not tiny planets",
    "Bohr’s rings are a model. Electrons do not circle like Neptune. Shells fill with a capacity (2, 8, 8…) as a first school map.",
    "Electrons sit on wires around the nucleus and can fall off if you shake the atom.",
    "Use the shell model to explain ions and light, then admit it is a map, not a photograph.",
    "A quantum orbital is a later, foggier address. Do not mix the two sentences in Year 8."],
  ["vx-s-ion-vs-atom", "Matter extras", "An ion is an atom (or group) that lost or gained electrons",
    "Na⁺ is not a sodium atom with a plus sticker for enthusiasm. The proton count stayed; the electron count did not.",
    "Ions are excited atoms. Heat makes Na⁺.",
    "Name the parent atom, then the electron change. Cations +, anions −. Opposite charges attract.",
    "A polyatomic ion (SO₄²⁻) is a group that travels together. It is still an ion, not a mixture."],
  ["vx-s-acid-metal-h2", "Matter extras", "Acid + metal often makes a salt and hydrogen",
    "Mg + 2HCl → MgCl₂ + H₂. The pop test is hydrogen, not ‘acid gas’. Unreactive metals (Cu, Au) shrug.",
    "Acids always dissolve every metal because they are sour.",
    "Check the reactivity series first. Collect gas, pop test, and do not treat hydrogen as a party balloon near a flame.",
    "Acid + carbonate is CO₂, a different gas (limewater). Do not mix the two tickets."],
  ["vx-s-neutralise-salt", "Matter extras", "Neutralisation is acid + base → salt + water",
    "HCl + NaOH → NaCl + H₂O. Neutral is about H⁺ and OH⁻ pairing, not ‘the liquid looks calm’.",
    "If it stops fizzing it is neutral. Fizz is the pH meter.",
    "Use an indicator or a pH probe. Name the salt from the ion pair.",
    "Excess acid means the mixture can still be acidic after ‘some’ base. Stoichiometry, not vibes."],
  ["vx-s-displace-series", "Matter extras", "A more reactive metal can kick a less reactive ion out of solution",
    "Fe in CuSO₄ grows a copper coat. The series is an empirical ladder, not a moral ranking.",
    "Any metal displaces any other if you wait. Chemistry is patience.",
    "Check the series: only a metal above can displace the ion below. Then look for the colour change.",
    "Carbon and hydrogen appear on some series too. That is for oxide reductions, a cousin ticket."],
  ["vx-s-bond-energy-exo", "Matter extras", "Making bonds releases energy; breaking bonds costs it",
    "Exothermic overall means the new bonds paid back more than the old bonds cost. A cold pack is the other way.",
    "Breaking bonds releases energy because you can hear a snap.",
    "Sketch a reaction profile: up to the transition, down to products. Catalyst lowers the hill, not the start/finish heights.",
    "Combustion is exothermic because CO₂ and H₂O bonds are a bargain relative to fuel + O₂."],
  ["vx-s-balance-atoms", "Matter extras", "A balanced equation conserves atoms, not coefficients as a vibe",
    "You may change numbers in front, not the little formulae. H₂O is not HO₂ because you needed even hydrogens.",
    "If it looks uneven, edit the subscripts until it is pretty.",
    "Count each element on both sides. Adjust coefficients. Recount.",
    "2H₂ + O₂ → 2H₂O. The 2s are multipliers of whole molecules."],
  ["vx-s-mole-count", "Matter extras", "A mole is a counted pile (Avogadro’s number), not a burrowing animal",
    "6.02 × 10²³ particles. Moles let you compare recipes. n = m/M is a later tool, but the idea is a count.",
    "A mole is a mass of 1 g, always, because metric.",
    "Ask ‘how many particles?’ If the number is silly, use moles as the unit of amount.",
    "One mole of H₂ molecules is twice as many hydrogen atoms as a mole of He atoms? No: one mole of H₂ is N_A molecules, hence 2N_A atoms."],
  ["vx-s-solubility-vs-rate", "Matter extras", "How much can dissolve is not how fast it dissolves",
    "Solubility is a maximum at a temperature. Stirring and surface area change rate, not the ceiling (unless temp/pressure changes).",
    "Stirring makes more sugar able to sit in the tea forever. Rate is capacity.",
    "Name saturation vs speed. Heat often lifts both for solids, but say which question you were asked.",
    "A saturated solution can still look clear. Undissolved bits are the giveaway, not cloudiness alone."],
  ["vx-s-allotropes-c", "Matter extras", "Allotropes are the same element in different structural costumes",
    "Diamond, graphite, graphene, buckminsterfullerene: all carbon. Hardness and conductivity differ because the bonding network differs.",
    "Allotropes are mixtures of elements that hang out. Graphite is carbon plus ink.",
    "Same atoms, different lattice or molecule. Properties follow the structure.",
    "O₂ and O₃ are oxygen allotropes. Ozone is not ‘more oxygeny air’ in a useful sense; it is a different molecule."],
  ["vx-s-metallic-sea", "Matter extras", "Metals are a lattice of ions in a sea of delocalised electrons",
    "That sea is why they conduct and why they are malleable: ions can slide, electrons keep the glue.",
    "Metals conduct because they are shiny. Shine is a wire.",
    "Link property to the sea: conductivity, heat, malleability. Rust is a chemical change on top, not the bonding model dying instantly.",
    "A salt crystal is ionic, not metallic. It conducts when molten or dissolved, not as a dry rock."],
  ["vx-s-polymer-repeat", "Matter extras", "A polymer is a long chain of repeating monomers",
    "Polyethene is many ethene units. Plastics, proteins, and cellulose are polymer stories with different monomers.",
    "Polymer means many mermaids. It is a biology joke, not chemistry.",
    "Name monomer → polymer. Cross-links change flexibility. Recycle codes are not a chemical formula.",
    "Heating a thermoplastic can remelt it; a thermoset is a one-way network. That is a processing ticket."],
  ["vx-s-rust-redox", "Matter extras", "Rust is iron oxidised with help from water and oxygen",
    "Fe becomes Fe³⁺ oxides/hydroxides. Salt water speeds the electrochemical cell on the surface. Paint is a barrier, not a vibe.",
    "Rust is dirt that iron attracts because it is magnetic.",
    "Keep water and oxygen off (paint, grease, sacrificial zinc). Name oxidation as electron loss if you are at that rung.",
    "Stainless steel cheats with a chromium oxide skin. Scratch it badly in chloride and you can still have a local cell."],
  ["vx-s-filter-vs-distil", "Matter extras", "Filtration catches insolubles; distillation rides boiling point",
    "Sand from salt water: filter. Salt from water: evaporate or distil. Ink dyes: chromatograph. The method matches the difference you are using.",
    "Boil everything; whatever remains is pure gold. Heat is a universal separator.",
    "Ask: solid/liquid, dissolved or not, similar boiling points or not. Then pick the tool.",
    "A condenser in distillation is where the gas becomes liquid again. Without it you just made steam in the room."],
  ["vx-s-chroma-rf", "Matter extras", "R_f is distance of the spot over distance of the solvent front",
    "Chromatography separates because substances spend different time on paper vs solvent. R_f is a ratio ≤ 1.",
    "The tallest spot is the heaviest molecule. Height is mass.",
    "Measure from the origin, not the bottom of the paper. Same solvent, same paper, if you want comparable R_f.",
    "Two spots with the same R_f might still be different. A second solvent is a check."],
  ["vx-s-solar-lunar-eclipse", "Earth & space", "A solar eclipse is the Moon covering the Sun; lunar is Earth’s shadow on the Moon",
    "Alignment: Sun–Moon–Earth for solar, Sun–Earth–Moon for lunar. Not every new moon, because the orbit is tilted.",
    "Eclipses happen every night. That is what night is.",
    "Draw the three bodies in a line. Solar is daytime-scary; lunar is a reddened full moon.",
    "A cloud over the Sun is weather. An eclipse is geometry. Do not mix them in a report."],
  ["vx-s-equinox-solstice", "Earth & space", "Solstices are the tilt extremes; equinoxes are the even-day crossings",
    "June solstice: Southern Hemisphere winter. Equinox: roughly equal day and night. Seasons are tilt, not ‘closer to the Sun’ as the main act.",
    "Summer is when Australia is closer. Perihelion is summer by law.",
    "Name the hemisphere, then the tilt toward/away. Equinox is a calendar geometry, not a picnic brand.",
    "Perihelion in early January actually makes Southern summers a bit more intense — a footnote, not the main season engine."],
  ["vx-s-light-year", "Earth & space", "A light-year is a distance, not a birthday",
    "The distance light travels in a year in vacuum. Proxima is about 4 ly. Looking far is looking back in time.",
    "A light-year is how long light feels. Nearby stars are a few years old.",
    "Treat ly as kilometres with a huge conversion, or as a yardstick. Do not add it to seconds.",
    "A parsec is another distance unit. Sci-fi that ‘makes the Kessel Run in parsecs’ is mixing speed and length as a joke or a mess."],
  ["vx-s-redshift-away", "Earth & space", "Redshift is a stretch of light from recession (often)",
    "Distant galaxies’ spectral lines shift red. Hubble’s observation: farther, faster away, on average. It is not ‘red because they are hot’.",
    "Redshift means the galaxy is angry or on fire. Red is heat.",
    "Compare known lines to observed lines. Interpret with the expansion model, not a traffic light.",
    "Blueshift exists too (Andromeda is incoming). Expansion is large-scale, not every neighbour."],
  ["vx-s-constellation-line", "Earth & space", "A constellation is a line-of-sight doodle, not a family of stars",
    "Stars in the Southern Cross are at different distances. They are not a cluster holding hands.",
    "Constellations are bound systems. Gravity drew the picture on purpose.",
    "Use them as a sky map. Do not infer they formed together unless you are talking about an actual cluster.",
    "A star cluster (Pleiades) is a physical group. Different ticket from the zodiac’s fanfiction."],
  ["vx-s-earth-magnet", "Earth & space", "Earth’s magnetic field is a dynamo, not a bar magnet souvenir only",
    "Molten outer core motion plus rotation. It shields against some solar wind. Magnetic north wanders; it is not a tattoo on the ice.",
    "Compasses point to the North Pole because a giant fridge magnet is buried there.",
    "Separate geographic poles from magnetic poles. Declination is the gap on a map.",
    "A solar storm can mess with satellites and grids. The field is a system, not a lucky charm."],
  ["vx-s-atmosphere-layers", "Earth & space", "The troposphere is weather; the stratosphere holds the ozone layer we fuss about",
    "Temperature profile is not ‘colder as you go up’ forever. The stratosphere warms with ozone chemistry.",
    "Air ends at the clouds. Planes fly in space.",
    "Name the layer by job: weather, ozone, meteors (mesosphere), auroras (thermosphere-ish).",
    "Mount Everest is still troposphere. You can need oxygen and still not be in space."],
  ["vx-s-groundwater-aquifer", "Earth & space", "An aquifer is stored water in rock pores, not an underground lake cartoon",
    "Porosity and permeability. Over-pumping drops the water table. Recharge can be slow.",
    "Groundwater is a river you could boat if you found the cave.",
    "Talk recharge, bore depth, and salt intrusion near coasts. Do not draw a hollow Earth lake by default.",
    "The Great Artesian Basin is a famous Australian aquifer story — confined water, not a mythic sea."],
  ["vx-s-elnino-au", "Earth & space", "El Niño and La Niña are Pacific patterns that shove Australia’s odds",
    "El Niño: often drier for much of eastern Australia. La Niña: wetter odds. They are not a single thunderstorm you can blame in court.",
    "If it rained on Tuesday, La Niña lives in your suburb now.",
    "Treat them as shifted probabilities for seasons, then still look at the actual forecast.",
    "Indian Ocean Dipole is another dial. Australia’s droughts are a stack, not a mascot."],
  ["vx-s-fire-triangle-sci", "Earth & space", "Fire needs fuel, oxygen, and heat — and weather loads the dice",
    "Bushfire behaviour also wants dryness, wind, and slope. The triangle is the chemistry; the fire weather is the multiplier.",
    "Water makes fire stronger because steam is energy. Always add water to a grease fire.",
    "Remove one of fuel/heat/oxygen in a controlled way. In the landscape, forecast wind and curing.",
    "Spotting ahead of a front is embers, not magic. That is how a road stops being a barrier."],
  ["vx-s-tsunami-quake", "Earth & space", "A tsunami is a water column shoved, often by an undersea quake",
    "Not a tidal wave (tides are the Moon). A withdrawal of the sea can be a warning, not a bargain hunt.",
    "Tsunamis are extra-big surf. Bring a board.",
    "If you feel a long quake on the coast, head high and inland per local advice. Do not wait for a phone push.",
    "Landslides and volcanoes can also shove water. The mechanism is displaced water, not ‘a big wind’."],
  ["vx-s-volcano-viscous", "Earth & space", "Sticky magma traps gas and explodes; runny magma flows",
    "Silica-rich (andesite/rhyolite) vs basaltic. Shield vs composite is a shape with a personality.",
    "All volcanoes explode. Lava is a bomb by definition.",
    "Link viscosity, gas, and eruption style. Then hazards: ash, pyroclastic flow, lava, gas.",
    "Australia has old volcanoes (Newer Volcanics in Victoria). ‘We don’t have any’ is folk geology."],
  ["vx-s-soil-not-dirt", "Earth & space", "Soil is a living profile; dirt is soil out of place",
    "Horizons, organic matter, mineral bits, water, air, organisms. Erosion is the profile leaving.",
    "Soil is brown stuff. Any brown stuff is equivalent.",
    "Talk structure, pH, and organic content if you are being scientific. ‘Dirt’ is the informal cousin.",
    "A sandy soil drains; a clay holds water and nutrients differently. Texture is a test, not a colour."],
  ["vx-s-met-vs-meteorite", "Earth & space", "Meteoroid in space, meteor in the sky, meteorite on the ground",
    "The streak is heated air and ablating rock. Most never land as souvenirs.",
    "Shooting stars are stars that fell. The constellation is thinner now.",
    "Use the three words for location. A crater is a landing (or explosion) story.",
    "The Moon’s craters last because there is no weather to erase them. Earth’s weather is an editor."],
  ["vx-s-day-sidereal", "Earth & space", "A solar day is not quite a 360° spin relative to the stars",
    "Earth must spin a bit extra to face the Sun again. Sidereal day is shorter. This is why stars shift with seasons at a given clock time.",
    "A day is 24 hours because the Sun said so in SI. Stars agree exactly.",
    "Separate ‘facing the Sun’ from ‘facing the same star’. Then the calendar’s leap-year cousin makes more sense.",
    "A year is the orbit. Leap days patch the leftover fraction. Different ticket, related mess."],
  ["vx-s-ozone-vs-greenhouse", "Earth & space", "Ozone depletion is not the same dial as the greenhouse effect",
    "Ozone (stratosphere) blocks UV. Greenhouse gases (troposphere mainly) trap IR. CFCs were an ozone villain and also greenhouse gases — still two mechanisms.",
    "The ozone hole causes climate change because hole means heat gets in. One hole, all problems.",
    "Name the layer, the wavelength, and the human chemical. Do not merge the posters.",
    "The Antarctic ozone hole has a recovery story after the Montreal Protocol. That success is not a climate slogan."],
  ["vx-s-enzyme-shape", "Body systems", "An enzyme is a shape-specific catalyst, usually a protein",
    "Lock-and-key / induced fit: the active site holds the substrate. Heat and pH can denature the shape, and then the job stops.",
    "Enzymes are living creatures that eat substrate. They get full.",
    "Name substrate, enzyme, product. Talk temperature optimum, then denaturation past that.",
    "They are reused. A catalyst is not consumed as the main story. Stomach pepsin likes acid; mouth amylase does not."],
  ["vx-s-antigen-blood", "Body systems", "Blood type is antigens on red cells plus antibodies in plasma",
    "Type A has A antigens. Transfusion fights are immune, not ‘the blood was the wrong colour’.",
    "O negative can donate to anyone so type does not matter any more. Skip matching.",
    "Match antigens to antibodies that would attack. Rh factor is the extra +/−.",
    "A hospital still types and cross-matches. Folk ‘universal donor’ is a start, not a skip."],
  ["vx-s-rbc-wbc", "Body systems", "Red cells carry oxygen; white cells fight; platelets plug",
    "Haemoglobin is the iron-containing oxygen taxi. Anaemia is a capacity story. WBC are immune; they are not ‘white because they are clean’.",
    "Blood is red because it is angry. White blood is for peace.",
    "Name the three jobs. Then say why a full blood count has several numbers.",
    "Plasma is the liquid. It is not ‘empty’. It carries hormones, nutrients, and CO₂ as bicarbonate too."],
  ["vx-s-reflex-arc", "Body systems", "A reflex can close in the spinal cord before you ‘decide’",
    "Receptor → sensory neuron → relay → motor → effector. Pain arrives in the brain a beat later. Speed is the point.",
    "You choose to pull your hand off the stove after a meeting.",
    "Draw the arc. Distinguish reflex from a considered action. The doctor’s knee tap is this.",
    "Some ‘reflex’ talk in sport is trained, not spinal. Do not mix the vocab."],
  ["vx-s-insulin-glucose", "Body systems", "Insulin is a signal to store/use glucose, not the sugar itself",
    "High blood glucose → pancreas (beta cells) → insulin → cells take up glucose. Glucagon is the opposite dial.",
    "Insulin is a type of sugar you inject to have more energy immediately in the blood.",
    "Name the stimulus, hormone, and effect. Diabetes is a family of failures of this loop — do not diagnose from a lesson.",
    "Adrenaline also yanks glucose around. Stress can look like a glucose story for a minute."],
  ["vx-s-vaccine-memory", "Body systems", "A vaccine trains memory cells without giving you the full disease job",
    "Antigen exposure (weakened, killed, or a piece) → memory. Later infection is a faster, bigger antibody response.",
    "Vaccines are antibiotics in a syringe. They kill viruses in the bottle.",
    "Talk antigen, immune memory, and herd effects as a population layer. Skip the rumour mill.",
    "Antibiotics do not train viral immunity. Different ticket: drugs vs immune education."],
  ["vx-s-antibiotic-not-virus", "Body systems", "Antibiotics target bacteria; viruses do not have those targets",
    "Cell walls, bacterial ribosomes. A cold is usually viral. Resistance is evolution in a dish we keep feeding.",
    "Antibiotics are strong medicine so they knock out viruses faster. Strong means universal.",
    "Ask bacteria vs virus. Finish prescribed courses as advised by a professional. Do not share leftover pills as lollies.",
    "Antiviral drugs exist for some viruses. They are still not ‘an antibiotic with a new name’."],
  ["vx-s-dna-vs-rna", "Body systems", "DNA stores; RNA is often the working copy",
    "DNA is double-stranded in the nucleus (eukaryotes). mRNA carries a codon copy to ribosomes. T vs U is a letter swap.",
    "RNA is leftover DNA. If you have DNA you do not need RNA.",
    "Central dogma as a first map: DNA → RNA → protein. Then admit reverse transcriptase exists in retroviruses.",
    "A gene is a stretch of DNA. A chromosome is a packaged stick of many genes."],
  ["vx-s-gene-vs-chrom", "Body systems", "A chromosome is a package; a gene is a recipe on it",
    "Humans: 46 chromosomes in body cells, 23 in gametes. Genes are loci. Alleles are versions.",
    "You have 46 genes, one per chromosome. That is why numbering is easy.",
    "Zoom: genome → chromosome → gene → allele. Karyotypes show packages, not every letter.",
    "Sex chromosomes vs autosomes is a later split. SRY is a gene on Y, not ‘the Y is the gene’."],
  ["vx-s-dom-rec", "Body systems", "Dominant is expressed with one copy; recessive needs two — in the simple model",
    "Dominant does not mean common or healthy. A rare dominant can be rare. Recessive can hide in carriers.",
    "Dominant means the better gene. Evolution voted.",
    "Write alleles, Punnett, phenotype. Then say the model is a cartoon of real regulation.",
    "Incomplete dominance and codominance (AB blood) break the ‘one wins’ slogan on purpose."],
  ["vx-s-heart-valves", "Body systems", "Valves stop backflow; they are doors, not pumps",
    "AV valves between atria and ventricles; semilunar to arteries. A murmur can be turbulence. The muscle is the pump.",
    "Valves squeeze the blood. That is their gym job.",
    "Follow one drop: vena cava → right atrium → right ventricle → lungs → left atrium → left ventricle → aorta.",
    "Left ventricle is thicker because body pressure is a longer fight than lungs."],
  ["vx-s-capillary-exchange", "Body systems", "Capillaries are the exchange shop; arteries are the highway",
    "Thin walls, slow flow, huge area. Oxygen, CO₂, glucose, wastes. Arteries are high pressure pipes, not the swap meet.",
    "Arteries exchange because they are closer to the heart, so they are more important.",
    "Name vessel by job: artery away (usually oxygenated, except pulmonary), vein return, capillary swap.",
    "Lymph is the leftover fluid return plus immune traffic. A cousin of the capillary leak."],
  ["vx-s-peristalsis", "Body systems", "Peristalsis is a muscle wave, not gravity’s kindness",
    "You can swallow in weird orientations because circular/longitudinal muscle pushes a bolus. The gut is not a chute you install once.",
    "Food falls into the stomach. Standing up is required biology.",
    "Talk coordinated contraction. Sphincters are gates. Diarrhoea/constipation are rate stories (among others).",
    "The oesophagus is not ‘a bone’. Choking is a blocked airway — first aid is a different, serious ticket."],
  ["vx-s-hormone-vs-nerve", "Body systems", "Nerves are fast and targeted; hormones are slower and broadcast",
    "Adrenaline can be both a nerve ending chemical and a blood hormone. The endocrine system is a radio; the nervous system is a phone.",
    "Hormones are tiny nerves. They spark like wires.",
    "Pick the time scale and the audience (one synapse vs the whole blood).",
    "A feedback loop (thyroid, glucose) is how a broadcast system does not scream forever."],
  ["vx-s-liver-hub", "Body systems", "The liver is a chemical factory, not just a filter sticker",
    "It makes bile, stores glycogen, processes drugs/alcohol, makes proteins. ‘Detox tea’ is not a spare liver.",
    "The liver’s only job is to soak up toxins like a sponge you can wring on the weekend.",
    "List two or three real jobs. Bile is an emulsifier for fats, stored in the gall bladder.",
    "Hepatic portal vein brings gut blood in for first pass. That is why some pills are designed around it."],
  ["vx-s-ke-half-mv2", "Energy extras", "Kinetic energy grows with speed squared, not linearly",
    "KE = ½mv². Double speed, quadruple KE. Braking distance stories live here. Mass is linear.",
    "Twice as fast is twice the energy. v² is a decoration.",
    "Plug SI units: kg, m/s, joules. Compare two speeds with a ratio of squares.",
    "A 110 km/h crash is not ‘10% worse’ than 100. Square the speeds (after converting if you are being careful)."],
  ["vx-s-gpe-mgh", "Energy extras", "Gravitational potential energy is mgh near Earth’s surface",
    "m in kg, g ≈ 9.8 N/kg, h in metres above a chosen zero. The zero is a bookkeeping choice.",
    "Higher is more GPE even if you pick a zero above the object. Negative height is extra energy.",
    "Choose a zero, measure h, multiply. A falling object trades GPE for KE if drag is small.",
    "On a mountain, g is a bit less. School mgh ignores that, and should say so."],
  ["vx-s-energy-conserved", "Energy extras", "Energy changes costume; the total in a closed account holds",
    "Heat, sound, and deformation ‘lose’ useful energy from the motion account. Conservation is not ‘the machine stays cold’.",
    "Energy is used up. That is what used means. The universe deletes it.",
    "Track forms: GPE, KE, thermal, chemical, electrical. The missing bit is usually thermal.",
    "A bouncing ball that stops did not violate conservation. It warmed the floor and itself."],
  ["vx-s-work-fd", "Energy extras", "Work is force along a displacement, a joule is a newton-metre",
    "W = Fd when force and movement align. Holding a brick still is tiring and still zero physics work on the brick.",
    "If you get tired, you did physics work. Muscles prove it.",
    "Check there is movement in the force’s direction. Then W = Fd (or a component).",
    "Carrying a bag across a flat room: gravity’s work is zero if height is constant. Your body still burns food. Different accounts."],
  ["vx-s-power-e-over-t", "Energy extras", "Power is energy per time; a watt is a joule per second",
    "A 60 W globe uses 60 J each second. A 2 kW kettle is not ‘stronger voltage’; it is a faster energy dump.",
    "Power is the same as energy. Watts and joules are nicknames.",
    "P = E/t. For electrical, P = VI is a cousin when you are in circuits.",
    "A big electricity bill can be a small power over a long time. kWh is energy, not power."],
  ["vx-s-insul-rvalue", "Energy extras", "Insulation slows heat flow; R-value is a stubbornness rating",
    "Heat still flows from hot to cold. Insulation is a thinner trickle. A gap of still air is often the trick.",
    "Insulation keeps heat out in summer by producing cold. It is a fridge blanket.",
    "Name conduction path, add resistance (layers, air gaps), and do not crush bulk insulation flat.",
    "A brick house can still need insulation. Thermal mass is a different gift (slow swing), not the same as a high-R wall."],
  ["vx-s-heat-three-ways", "Energy extras", "Conduction is contact, convection is fluid movement, radiation is EM",
    "A spoon in tea: conduction. Boiling water rolling: convection. Sun on skin: radiation. Vacuum stops the first two, not the third.",
    "Heat only rises. That is why floors are cold and the model is complete.",
    "Pick the path in the question. Silvered flasks cut radiation; vacuum cuts conduction/convection.",
    "Land breeze / sea breeze is convection at landscape scale. Same word, bigger theatre."],
  ["vx-s-series-parallel-i", "Energy extras", "Series shares one current; parallel shares one voltage",
    "A series string of globes: one dies, the path dies. Parallel: branches. Household lights are parallel for a reason.",
    "Parallel is always brighter because more is more. Series is for experts.",
    "Draw the loop(s). Series: add resistances. Parallel: extra paths, lower total R.",
    "Batteries in series add voltage; in parallel add capacity (roughly) at the same voltage. Match cells."],
  ["vx-s-voltage-per-charge", "Energy extras", "Voltage is energy per charge, a push, not a stuff that sits in the wire",
    "A 1.5 V cell gives 1.5 J per coulomb. Current is the flow rate of charge. You can have voltage with tiny current (static).",
    "Voltage is the amount of electricity in the battery, in litres.",
    "Separate V, I, and R. Ohm’s law is V = IR for many metals at constant temperature.",
    "A bird on one wire is not in a circuit. The potential difference across the bird is the danger, not ‘touching electricity’ as a substance."],
  ["vx-s-ohm-ratio", "Energy extras", "Resistance is how much voltage you need per amp",
    "R = V/I. A resistor is a designed bottleneck. Temperature can change R (filaments, thermistors).",
    "Resistance is the opposite of current, so if current is 2 A, R is −2.",
    "Measure V and I, divide. Or read the colour code if you are in that lab.",
    "Short circuit: R near 0, I huge, heat, trip. That is Ohm’s law screaming, not a ghost."],
  ["vx-s-wave-v-f-lambda", "Energy extras", "Wave speed is frequency times wavelength",
    "v = fλ. In one medium, raising f shortens λ if v is fixed. Sound in air is ~340 m/s, not ‘the speed of light’.",
    "Higher frequency means the wave goes faster. f is speed.",
    "Keep v as a property of the medium (approximately). Then f and λ trade.",
    "Light in vacuum is c. In glass it is slower — that is refraction’s energy-account cousin."],
  ["vx-s-long-vs-trans", "Energy extras", "Transverse shakes perpendicular; longitudinal shakes along",
    "Light is transverse EM. Sound in air is longitudinal compressions. A slinky can do both if you are cruel.",
    "Sound waves are little light waves you can hear. Same shape, quieter.",
    "Draw the oscillation vs the travel direction. Then name the wave.",
    "P-waves (longitudinal) and S-waves (transverse) in earthquakes: S cannot swim through liquid outer core. That is a planetary ultrasound."],
  ["vx-s-refract-bend", "Energy extras", "Refraction is a speed change that can bend the path",
    "Into a slower medium, the wave bends toward the normal (usual school case). Wavelength drops; frequency stays (steady source).",
    "Light bends because glass is sticky. The photons get tired and turn left.",
    "Draw the normal. Apply the toward/away rule. Snell’s law if you have sines.",
    "A straw looks broken in a glass. The light path is bent, not the straw (usually)."],
  ["vx-s-half-life", "Energy extras", "Half-life is a waiting time for half the nuclei, not a half-dead sample vibe",
    "After one half-life, half remain (on average, for large N). After two, a quarter. You cannot make a nucleus ‘hurry’ by heating it (ordinary chemistry temperatures).",
    "Half-life means the sample is 50% as radioactive in personality, so it is safer by half immediately and then stays.",
    "Count remaining fraction (1/2)^n after n half-lives. Carbon-14 dating is this with a calibration story.",
    "A short half-life is intense then gone. A long one is a long low glow. Activity is not ‘how evil’."],
  ["vx-s-nuclear-vs-chem", "Energy extras", "Nuclear energy changes are millions of times bigger per atom than chemical",
    "Chemistry moves electrons. Nuclear rearranges nuclei. That is why a tiny mass defect is a city-scale energy in E = mc² talk.",
    "Nuclear is just a strong chemical bond. Same joules, better branding.",
    "Keep the accounts separate. A chemical explosion is not a tiny nuke.",
    "Sunlight started as nuclear fusion, then travelled as radiation, then became chemical in a leaf. The chain can be long."],
  ["vx-s-producer-consumer", "Living extras", "Producers fix energy; consumers eat; decomposers recycle",
    "Plants and some bacteria photosynthesise or chemosynthesise. Arrows in a food chain point to the eater (energy flow), not ‘who likes whom’.",
    "Arrows point to the food, like a menu. The cow points at the grass.",
    "Label trophic level, then follow energy as heat loss up the chain. 10% is a cartoon, not a law.",
    "A mushroom is often a decomposer, not a plant that forgot chlorophyll as a moral failing."],
  ["vx-s-photo-resp-loop", "Living extras", "Photosynthesis and respiration are reverse-ish energy stories, not optional hobbies",
    "Photosynthesis stores light in sugar; respiration releases it to ATP. Plants respire too, including at night.",
    "Plants only photosynthesise and animals only respire. Night plants hold their breath.",
    "Write the word equations. Then say plants do both. Animals do not photosynthesise (usual school set).",
    "The oxygen we breathe is a photosynthetic by-product. The carbon in the sugar came from CO₂."],
  ["vx-s-osmosis-water", "Living extras", "Osmosis is water through a semi-permeable membrane, down its own gradient",
    "Water moves to the saltier side (higher solute) in the simple tale. Cells in distilled water can burst; in strong syrup they shrivel.",
    "Osmosis is salt marching through the membrane. The salt wants to explore.",
    "Name water, membrane, solute concentrations. Then predict swell or shrink.",
    "Diffusion is the wider word for net movement down a gradient. Osmosis is water’s special case."],
  ["vx-s-diffusion-random", "Living extras", "Diffusion is net movement from higher to lower concentration",
    "Particles still move at equilibrium; the net is zero. Temperature and gradient steepness change the rate.",
    "Diffusion only happens in liquids. Air is immune.",
    "Perfume in a room, oxygen in alveoli: same idea, different theatre. Stirring is not required but helps in bulk.",
    "Active transport spends ATP to go against a gradient. That is the other ticket."],
  ["vx-s-membrane-select", "Living extras", "A cell membrane is a selective gate, not a plastic bag",
    "Phospholipid bilayer plus proteins. Small nonpolar things sneak; ions need channels. ‘Semi-permeable’ is the school stamp.",
    "If it is a membrane it blocks everything. That is why cells are lonely.",
    "Ask size, charge, and whether a protein helper exists. Then passive vs active.",
    "Surface area to volume is why cells stay small. A giant cube cannot feed its middle by diffusion alone."],
  ["vx-s-xylem-phloem", "Living extras", "Xylem is water up; phloem is sugar traffic",
    "Xylem: dead tubes, transpiration pull. Phloem: living tissue, sources to sinks. A ring-bark can kill by cutting phloem.",
    "All plant pipes carry the same green juice. Xylem is a brand.",
    "Name the cargo and the direction (mostly). Then transpiration as evaporation from leaves pulling the column.",
    "Root hairs are surface area for water/minerals. Mycorrhizae are fungal helpers, a common extra."],
  ["vx-s-keystone", "Living extras", "A keystone species punches above its biomass",
    "Sea otters, some dingoes in thought-experiments, a top predator that keeps grazers in check. Remove it, the web lurches.",
    "Keystone means the biggest animal. Whales are automatically keystones.",
    "Ask what collapses if it is removed. That is the test, not charisma.",
    "A keystone is context-specific. The same species is not a keystone in every paddock."],
  ["vx-s-carrying-cap", "Living extras", "Carrying capacity is a ceiling the habitat can support, not a vibe",
    "Food, water, nesting, disease. A population can overshoot then crash. K is a model letter, not a fence you can see.",
    "Carrying capacity is the number we like. Ethics sets K.",
    "Name limiting factors. Then exponential vs logistic cartoons, and admit real habitats move.",
    "Introduced rabbits in Australia overshot in a landscape without their old checks. That is this idea with teeth."],
  ["vx-s-cane-toad-intro", "Living extras", "A cane toad is an introduced predator/competitor with toxic skin",
    "Brought for cane beetles, spread anyway. Native predators that mouth them can die. Control is messy.",
    "Introduced means it has a passport. Toads filled in the forms.",
    "Separate ‘not native’ from ‘pest impact’. Then evidence of harm, not a feeling about ugly animals.",
    "Not every introduced species is a cane toad story. Wheat is introduced and we still eat it. Impact is the word."],
  ["vx-s-nitrogen-cycle", "Living extras", "Nitrogen in air is mostly unusable until bacteria (or industry) fix it",
    "N₂ is triple-bonded and stubborn. Fixers, nitrifiers, denitrifiers. Fertilizer is industrial fixing. Algal blooms can be a nitrogen/phosphorus dump.",
    "We breathe nitrogen into proteins directly. Lungs are nitrogen factories.",
    "Follow N from air → plants → consumers → decomposers → air. Name at least one bacterial job.",
    "Lightning fixes a little. Haber–Bosch fixes a lot. Both are ‘making nitrogen available’."],
  ["vx-s-denature-heat", "Living extras", "Too much heat unfolds proteins; that is denaturation, not ‘killing the germ with spicy vibes’ only",
    "Cooking an egg sets the white. Fever has limits. Enzymes have an optimum then a cliff.",
    "Hotter is always faster biology. Boil the enzyme to speed the lab.",
    "Talk shape, active site, irreversible vs a merely slow cold enzyme (cold is often reversible slowing).",
    "Acid can denature too (ceviche, stomach). Different agent, similar unfolding story."],
  ["vx-s-punnett-box", "Living extras", "A Punnett square is a probability map of gamete combinations",
    "Each parent’s alleles split. Boxes are equally likely if that is the model. 3:1 is a large-sample expectation, not a family of four with a quota.",
    "A 3:1 ratio means exactly three kids will show the trait if you have four.",
    "Write gametes on the edges, fill combinations, then convert to phenotype with dominance rules.",
    "Real families are small samples. 0,1,2,3, or 4 affected is all allowed by chance."],
  ["vx-s-nat-sel-not-need", "Living extras", "Natural selection is differential survival/reproduction of variants, not a species trying",
    "Variation, heritability, selection pressure. Giraffes do not stretch necks and pass on the stretch as a Lamarck cartoon.",
    "If it needs a trait, it grows it this generation and the kids inherit the gym membership.",
    "Name the pressure, the existing variation, and who leaves more offspring. Time is many generations.",
    "Antibiotics and resistant bacteria are selection in a dish. The bacteria did not ‘learn chemistry’ as a school."],
  ["vx-s-biodiversity-more", "Living extras", "Biodiversity is genes, species, and ecosystems, not a zoo headcount only",
    "A wheat monoculture can have many plants and low diversity. A hotspot (SW Australia) is richness plus endemism plus threat.",
    "Biodiversity means lots of green. A lawn is peak diversity because blades.",
    "Ask which level: genetic, species, ecosystem. Then threats: habitat loss, invasives, climate, exploitation.",
    "Evenness matters. 99 of one species and 1 of another is not the same as a mixed bush."],
  ["vx-s-cell-theory", "Living extras", "Cell theory is three claims, not ‘cells look boxy’",
    "Living things are made of cells; cells are the basic unit; cells come from cells. Viruses pick a fight with the first two on purpose.",
    "Cell theory means all cells are cubes. Theory means a guess.",
    "State the three. Then exceptions/edge cases (syncytia, viruses) as a grown-up footnote.",
    "Hooke’s cork cells were walls of dead plant tissue. Schleiden/Schwann/Virchow is the usual name-drop set."],
  ["vx-s-prok-euk", "Living extras", "Prokaryotes lack a nucleus; eukaryotes package DNA in one",
    "Bacteria: prokaryote. Plants, animals, fungi, protists: eukaryote. Size and organelles differ. Prokaryote is not ‘worse’.",
    "Prokaryote means professional cell. Eukaryote is amateur.",
    "Nucleus present? Membrane organelles? Then classify. Bacteria still have ribosomes and DNA.",
    "Archaea are prokaryotes too, genetically their own domain. Do not say ‘bacteria’ for every no-nucleus cell if you are being careful."],
  ["vx-s-stimulus-response", "Living extras", "A tropism is a plant’s directed growth; a taxis is an animal’s directed move",
    "Phototropism: auxin story in shoots. Chemotaxis: bacteria swimming up a gradient. Both are stimulus → response, different hardware.",
    "Plants move to the lounge because they like the view. Tropism is walking.",
    "Name the stimulus (photo-, geo-, hydro-) and whether growth or locomotion.",
    "A venus flytrap snap is fast plant action, still not a neuron like yours. Do not require a brain for ‘response’."],
  ["vx-s-abiotic-biotic", "Living extras", "Abiotic is the non-living stage; biotic is the living cast",
    "Temperature, light, pH, salinity: abiotic. Competitors, predators, pathogens: biotic. A bushfire is a physical event with living consequences.",
    "Abiotic means dead organisms. Bones are abiotic factors.",
    "Sort the factor first. Then say how it limits or enables a species.",
    "Soil is a mash: mineral abiotic plus a living community. Real habitats refuse tidy boxes, but the words still help."],
  ["vx-s-inertia-mass", "Energy extras", "Inertia is mass’s stubbornness, not a force you add to a diagram",
    "Newton 1: constant velocity unless net force. A seatbelt is about inertia of your organs. Mass is the measure, not ‘how lazy’.",
    "Inertia is a force that keeps you going. Draw it as an arrow out the back.",
    "Find net force. If zero, velocity stays (including staying still). Do not draw an inertia arrow.",
    "A bigger mass needs more force for the same acceleration (Newton 2). That is related, not a third law mix-up."],
  ["vx-s-action-reaction", "Energy extras", "Action–reaction pairs are on two bodies, not a cancel on one",
    "You push the water back; the water pushes you forward. They do not cancel because they do not act on the same object.",
    "Every force cancels with its pair, so nothing can accelerate. Newton 3 forbids sport.",
    "Name the two objects. The pair is equal, opposite, same type. Then look at each object’s own net force.",
    "A book on a table: gravity (Earth on book) pairs with book on Earth, not with the normal force. Normal/weight can balance without being a third-law pair."],
  ["vx-s-density-float", "Matter extras", "Floating is density and displaced weight, not ‘being light as a personality’",
    "If average density < fluid, it floats. A steel ship is mostly air. Ice is less dense than liquid water — a rare solid trick.",
    "Heavy things sink. Ships are heavy, so they sink, but paint saves them.",
    "Compare densities or use Archimedes: buoyant force = weight of displaced fluid.",
    "Dead Sea floating is extra-dense brine. That is salt, not a miracle of holiday morale."],
  ["vx-s-ph-log", "Matter extras", "Each pH unit is a tenfold H⁺ change, not a one-step sour",
    "pH 2 vs 3 is 10×, not ‘a bit’. pH 7 is neutral in the water story at usual T. Indicators are dyes with a range, not a moral.",
    "pH 2 is twice as acidic as pH 4 because 2×2=4.",
    "Remember log scale. Strong vs weak is about dissociation, not the pH number alone.",
    "Stomach ~1–3, lemon ~2, soap basic. Do not taste the lab."],
  ["vx-s-pressure-pfa", "Energy extras", "Pressure is force over area, why a sharp knife cuts",
    "P = F/A. Same force, smaller area, bigger pressure. Snowshoes are the opposite trick. Pascals are N/m².",
    "Pressure is the same as force. A bigger boot hits harder because it is bigger.",
    "Name F and A, divide, keep units. A drawing pin vs a wall is this in hardware.",
    "Hydraulic jacks use P constant in a fluid (school Pascal) to multiply force with area. That is a later gift."],
  ["vx-s-hooke-f-kx", "Energy extras", "Hooke’s law is F = kx in the elastic range, not forever",
    "Double extension, double force, until you pass the limit and the spring sulks. k is stiffness, not ‘how long the spring is’.",
    "A longer stretch is always twice the force, even after it is a pretzel.",
    "Stay in the linear bit. Measure k from a gradient. Do not assume a rubber band is Hooke.",
    "Energy stored is ½kx², not kx. The triangle under the graph is the work."],
  ["vx-s-em-spectrum", "Energy extras", "The EM spectrum is one family: radio to gamma, same c in vacuum",
    "Energy and frequency climb together; wavelength drops. Visible is a sliver. UV is not ‘strong light’ as a brand; it is higher f.",
    "Radio is sound. Gamma is loud radio. They are different substances.",
    "Order by wavelength or frequency. Then jobs: comms, heat (IR), vision, UV damage, X-ray imaging, gamma from nuclei.",
    "All of them can be waves and, in the particle hat, photons. School can wear one hat at a time."],
  ["vx-s-convex-lens", "Energy extras", "A convex lens converges; a concave diverges (in the usual glass-in-air case)",
    "Ray diagrams: parallel → focal point for convex. The eye’s lens is a living convex story. A camera is cousins.",
    "Lenses magnify because they are thick. Thickness is power.",
    "Draw two rays, find the image, then real vs virtual. Focal length is a property, not a vibe.",
    "Water on a phone camera is an accidental lens. That is refraction, not a new app."],
  ["vx-s-chloro-mito", "Living extras", "Chloroplasts bank light; mitochondria release it to ATP",
    "Plant cells usually have both. Animal cells have mitochondria, not chloroplasts. The endosymbiosis story is a later wow.",
    "Mitochondria photosynthesise if you believe in them. Powerhouse means solar.",
    "Match organelle to process. Then remember plants respire in mitochondria too.",
    "A leaf in the dark still needs ATP. That is stored sugar, not moonlight photosynthesis as a default."],
  ["vx-s-stomata-gas", "Living extras", "Stomata are adjustable pores: CO₂ in, water vapour out",
    "Guard cells open/close. Hot windy days can close to save water and then starve photosynthesis of CO₂. A trade.",
    "Leaves sweat through tiny mouths to be polite. Stomata are manners.",
    "Link transpiration, gas exchange, and wilting. A waxy cuticle is the other water-saving hat.",
    "Lower leaf surface often has more stomata. A microscope slide is the check, not a poster."],
  ["vx-s-pollination-seed", "Living extras", "Pollination is pollen to stigma; fertilisation is fusion; a seed is the sequel",
    "Wind vs animal pollination are different offers. Fruit is often a bribe for seed travel. They are not synonyms.",
    "If a bee visits, the plant is pregnant. Pollination is fertilisation.",
    "Sequence: pollination → pollen tube → fertilisation → seed/fruit. Then dispersal as a separate job.",
    "A seedless supermarket fruit can be a human breeding trick. Biology still had an ancestor with seeds."],
  ["vx-s-succession", "Living extras", "Succession is a community changing through time after a disturbance",
    "Primary (bare rock) vs secondary (soil left). Pioneer species, then later trees in the textbook cartoon. Real sites skip stages.",
    "Succession means the biggest animal wins and the story ends at lions.",
    "Name the starting surface, early colonisers, and that ‘climax’ is a contested word now.",
    "A bushfire can start a secondary succession. Some species are counting on that fire return time."],
  ["vx-s-vector-arrow", "Energy extras", "A vector has size and direction; a scalar is size only",
    "Displacement, velocity, force, momentum: vectors. Distance, speed, mass, time: scalars. 3 m north is not 3 m.",
    "If it has a unit it is a vector. Units are arrows.",
    "Ask ‘does direction matter to add these?’ If yes, arrows or components, not just + on calculators.",
    "A −5 m/s is a direction in 1D. The minus is not ‘less speed’ as a mood."],
  ["vx-s-moment-turn", "Energy extras", "A moment is force times perpendicular distance from the pivot",
    "M = Fd⊥. A longer spanner is not a stronger person; it is a bigger d. Clockwise vs anticlockwise balance.",
    "Moments are memories of force. If you remember pushing, it turns.",
    "Mark the pivot, use the perpendicular lever arm, then sum to zero for a balanced beam.",
    "A see-saw with a heavy adult close to the pivot can balance a child far out. That is this, not magic."],
  ["vx-s-specific-heat", "Energy extras", "Specific heat capacity is joules to lift 1 kg by 1°C",
    "Water’s high c is why oceans moderate climate and why a pot takes ages. Q = mcΔT in the school form.",
    "If it is hotter it has more specific heat. Temperature is the capacity.",
    "Name m, c, ΔT. Water vs sand at the beach is this in sandals.",
    "A small mass of oil can out-heat a large mass of water if ΔT and c play along. Do the product."],
  ["vx-s-rock-cycle", "Earth & space", "The rock cycle is a set of paths, not a compulsory circle",
    "Melt → igneous; weather/deposit → sedimentary; heat/pressure → metamorphic. A rock can skip the scenic route.",
    "Every rock must visit all three types to graduate. It is a school.",
    "Name the process that would change THIS rock, not a poster loop you recite.",
    "Sydney sandstone is sedimentary. The fold belts inland have metamorphic stories. Same continent, different paths."],
]);
