import { pack } from "../pack.mjs";

export const TECH_VOLUME = pack("tech", [
  ["vx-t-so-dimm-notch", "Hardware extras", "SO-DIMM will not fake a DIMM slot",
    "SO-DIMM is a smaller outline with a different notch. A desktop DIMM does not clip into a laptop, even if both say DDR4.",
    "Buy any DDR4 stick; laptop slots are just short DIMMs with an adapter vibe.",
    "Match generation, form factor, and the service manual. SODIMM vs DIMM is not an adapter job.",
    "Some boards mix soldered LPDDR with one SODIMM. Dual channel may need matched pairs."],
  ["vx-t-nvme-2280", "Hardware extras", "2280 is a length, not a speed grade",
    "M.2 2230, 2242, 2260, and 2280 name millimetres of module length. A 2280 stick will not sit in a 2242-only bracket without the right standoff.",
    "2280 means PCIe 4.0×4. The number is a performance SKU.",
    "Check length, keying, and the standoff screw hole on the board photo before you order.",
    "A 2230 WWAN card in an NVMe slot is the wrong key and the wrong protocol, even if both are ‘M.2’."],
  ["vx-t-sata-ssd-not-nvme", "Hardware extras", "A SATA SSD is a different conversation from NVMe",
    "2.5-inch SATA and M.2 SATA speak AHCI over SATA. NVMe speaks PCIe. A SATA M.2 in an NVMe-only slot does nothing useful.",
    "Any stick labelled SSD is NVMe and will boot from any M.2 hole.",
    "Read SATA vs NVMe on the box and the board diagram. Clone tools must see the destination protocol.",
    "A 2.5-inch SATA SSD still needs a data cable and a SATA power lead. It will not plug into M.2."],
  ["vx-t-usbc-pd-logo", "Hardware extras", "A PD print on a brick is a negotiation, not a wattage",
    "USB Power Delivery profiles are a handshake. 20 V at 5 A needs an e-marked 5 A cable. A 65 W laptop may refuse a cheap 20 W phone cube.",
    "Any USB-C brick with a lightning bolt charges any USB-C notebook at full tilt.",
    "Match PD wattage, e-marker, and whether the port is charge-only or also Alt Mode.",
    "A 3 A cable on a 100 W supply is a slow charge, not a dying battery pack."],
  ["vx-t-liion-storage-soc", "Hardware extras", "Store Li-ion near half, not full or flat",
    "Calendar ageing is faster at 100% and at hot shelves. Shops store packs around 40–60% if they will sit. Do not freeze a pack to ‘preserve’ it.",
    "Leave every loaner at 100% on the charger all holidays so it is ready.",
    "Park long-term stock at a mid state of charge, cool, and not in a metal tool drawer that cooks in a van.",
    "A pack stored at 0% can fall into protection and look dead. That is chemistry plus a gauge, not a Windows setting."],
  ["vx-t-wifi-bt-combo", "Mobile extras", "Wi-Fi and Bluetooth often share one M.2 card",
    "Many laptops use a combo CNVi or M.2 card. One antenna lead is Wi-Fi, one is Bluetooth/aux. Swapping ‘just Wi-Fi’ can kill BT in Device Manager.",
    "Bluetooth is a tiny USB dongle soldered forever. Wi-Fi is a different planet.",
    "Photograph antenna colours, reseat both U.FL, and install the combo driver pack, not a random Intel Wi-Fi-only INF.",
    "A missing BT radio after a card swap is often the white/black lead on the wrong pin, not a Windows feature off."],
  ["vx-t-hinge-antennas", "Mobile extras", "The antennas live in the lid, not the palm rest",
    "Wi-Fi traces run through the hinge. A cracked hinge or a pinched eDP/antenna bundle is a one-bar ticket after a drop.",
    "Weak Wi-Fi is always a driver. Reinstall Intel PROSet until bars grow.",
    "Reseat U.FL, check the hinge cable for crush, and test an external USB NIC before you condemn the board.",
    "Metal lids need antenna windows. A third-party lid without them is a Faraday souvenir."],
  ["vx-t-dc-jack-barrel", "Mobile extras", "A DC jack is a mechanical fuse",
    "Barrel jacks fatigue. A wiggle-to-charge laptop is often the jack, not the brick. USB-C PD machines still have board-side controllers that burn.",
    "If it only charges at an angle, buy a more expensive charger with a thicker brick.",
    "Strain-relief the cable, inspect the jack solder, and do not yank the lead by the wire.",
    "A yellow bang in Windows is not a DC jack diagnosis. Meter the brick first, then the pin."],
  ["vx-t-80plus-psu", "Hardware extras", "80 Plus is efficiency, not a 12 V promise",
    "80 Plus Bronze/Gold says how much wall power becomes DC at a test load. A Gold 450 W unit can still starve a GPU’s 12 V rail.",
    "Gold in the logo means it can feed any 450 W-class PC, including a 350 W card plus RGB.",
    "Read the 12 V amperage, the CPU/GPU 8-pin count, and the continuous rating, not the sticker poetry.",
    "Cybenetics and 80 Plus are lab labels. Cheap units still sag when the GPU spikes."],
  ["vx-t-wwan-card", "Mobile extras", "WWAN is a card plus an antenna plus a SIM path",
    "LTE/5G in a laptop needs a WWAN-ready M.2 slot (often 3042/3052), antennas in the lid, and a SIM or eSIM. A Wi-Fi slot is not a consolation prize.",
    "Drop any M.2 4G card into the NVMe hole and you have mobile broadband.",
    "Check the service manual for WWAN support, antenna connectors, and BIOS whitelist ghosts on some brands.",
    "Airplane mode kills WWAN and Wi-Fi together. That is a switch, not a dead card."],
  ["vx-t-digitizer-vs-lcd", "Mobile extras", "A digitizer is not the LCD",
    "Glass/digitizer is the touch surface. The LCD/OLED is the image. A cracked glass with a perfect picture is not ‘a new screen’ as one blob unless the shop kits them together.",
    "If touch is wrong, replace the whole lid because they are the same part in every model.",
    "Test touch vs image separately. Order the FRU the manual names: glass, panel, or assembly.",
    "A stylus that needs AES/WGP is not saved by a cheap capacitive glass with no digitizer IC."],
  ["vx-t-battery-cycle-count", "Mobile extras", "Cycle count is wear, not a calendar curse",
    "A cycle is roughly a full 0–100 in pieces. 80% health at 400 cycles can be normal. A 2-year pack at 99% that swells is still a safety ticket.",
    "If Task Manager shows 100%, the pack is new. Cycle count is a scam.",
    "Read the OEM battery report, look at the chassis for swell, and replace on health plus safety, not vibes.",
    "Calibration (full drain/charge) is a gauge trick, not a chemistry spa. Do it rarely."],
  ["vx-t-edp-hinge-cable", "Mobile extras", "The eDP cable is a hinge victim",
    "Flicker on lid angle is often the eDP/LVDS cable, not a GPU that hates Tuesdays. Reseat both ends; do not yank the panel clips.",
    "Lid-angle flicker means Windows needs a GPU driver from a forum.",
    "Open to the service position, inspect the cable for pinch, and test an external monitor to split panel vs GPU.",
    "A torch test still matters: faint image with a flashlight is backlight, not eDP."],
  ["vx-t-fru-vs-cru", "Mobile extras", "CRU is customer; FRU is the shop",
    "CRUs are the bits the vendor expects a careful owner to swap (some batteries, SODIMMs). FRUs may need torque maps and hidden clips.",
    "If iFixit has a guide, the warranty is automatically fine. Always.",
    "Follow the HMM, use the screw map, and do not chase a CRU price on a glued FRU pack.",
    "Some ‘user-replaceable’ packs still void a sealed-unit policy. Read the SKU, not a Reddit vibe."],
  ["vx-t-keyboard-ribbon", "Mobile extras", "A laptop keyboard is a ribbon, not a USB stick",
    "ZIF/FFC cables hate a 45-degree yank. A few keys dead in a rectangle is often the membrane; a whole matrix dead is the cable or controller.",
    "If E and R fail, reinstall the HID driver and call it a day.",
    "Reseat the ZIF, check for liquid, and test a USB keyboard to split OS vs hardware.",
    "Backlight LEDs on the board can die while keys still work. That is not a Windows theme."],
  ["vx-t-trackpad-haptic", "Mobile extras", "Haptic pads are a board, not a click plastic",
    "Precision touchpads and haptic engines need the right driver and a seated cable. A ‘dead click’ can be firmware or a bent plate, not a missing mouse setting.",
    "Turn up pointer speed to restore a dead haptic click.",
    "Reseat the trackpad FFC, install the OEM pad driver, and check for a swollen battery lifting the pad.",
    "A battery swell that lifts the pad is a safety swap first, a click feel second."],
  ["vx-t-webcam-privacy", "Mobile extras", "A shutter is not a driver, and a driver is not a shutter",
    "Hardware shutters block the lens. A kill-switch can cut the USB camera device. A missing camera in Device Manager after a drop is often the cable in the lid.",
    "If the LED is off, the CIA stole the sensor. Reinstall Windows.",
    "Check the shutter, the function-key kill, Device Manager, then the lid cable.",
    "An LED that stays on with no app is a privacy bug — treat it as a real ticket, not a joke."],
  ["vx-t-laptop-sim-esim", "Mobile extras", "SIM and eSIM are different doors",
    "A nano-SIM tray is not an eSIM profile. WWAN still needs the radio. A phone hotspot is a workaround, not a SIM slot.",
    "If the laptop has USB-C it can take a phone SIM. Physics.",
    "Find the tray or the eSIM UI, confirm WWAN hardware, and do not wedge a micro-SIM with cardboard.",
    "Carrier locks and APN settings kill data with full bars. That is provisioning, not antenna grief."],
  ["vx-t-qi-coil-phone", "Mobile extras", "Qi is a coil alignment job",
    "Wireless charge needs a coil over a coil and a case that is not a magnet museum. Foreign-object detection will cut power rather than cook a coin.",
    "Any wireless pad charges through a wallet of cards and a pop-socket.",
    "Align, uncase metal, and check the phone supports the pad’s wattage. Heat is a throttle.",
    "MagSafe-style rings are alignment, not a promise that a random Qi puck will hit 15 W."],
  ["vx-t-imei-vs-serial", "Mobile extras", "IMEI is the radio; serial is the chassis",
    "IMEI/MEID identify the cellular identity. A laptop serial is a warranty name. MDM and blacklists key off the right one.",
    "Quote the battery serial to the carrier to unlock a phone.",
    "Dial *#06# or read the SIM tray laser for IMEI. Use the OEM serial for repair tickets.",
    "A swapped board can change IMEI. That is a compliance story, not a sticker you ignore."],
  ["vx-t-mdm-activation-lock", "Mobile extras", "Activation Lock is not a forgotten PIN",
    "Find My / Knox / Android Factory Reset Protection ties the device to an identity. A wipe without the owner is a brick with a progress bar.",
    "DFU restore always clears iCloud lock because Apple loves technicians.",
    "Get the owner to release the lock. Do not buy ‘unlock services’ from a comments section.",
    "A school MDM leftover on a second-hand Mac is a paperwork ticket, not a T2 failure."],
  ["vx-t-microsd-vs-soldered", "Mobile extras", "A microSD is not the 256 GB in the spec sheet",
    "Phone/tablet soldered UFS is the internal store. A card is extra, slower, and easy to eject into a washing machine.",
    "Format the SD as internal and it becomes as fast and as safe as soldered flash.",
    "Photograph whether the SKU is 128+slot or 128 including a card in the box.",
    "Adoptable storage is a messy marriage. Back it up like a disk you can lose."],
  ["vx-t-usb-otg", "Mobile extras", "OTG is a host hat, not a charge brick",
    "USB-OTG/USB-C dual-role lets a phone talk to a stick. A charge-only cable will not. Some phones need a setting or a proper OTG dongle.",
    "Any USB-C cable turns a phone into a PC with ports.",
    "Use a data-capable cable/dongle, enable OTG if the OEM hid it, and do not expect a 2 TB spinning disk to be happy without power.",
    "A Y-cable that feeds power plus data is a special part, not a hope."],
  ["vx-t-trrs-headset", "Mobile extras", "CTIA vs OMTP is why one mic is silent",
    "TRRS headsets wire mic and ground differently. A 3-pole TRS guitar lead is not a headset. USB-C analog adapters are their own mess.",
    "If the headset mic is dead, the phone’s cellular radio is broken.",
    "Try a known-good CTIA headset, then the USB-C dongle, then the software input device.",
    "A TRS dongle on a TRRS phone can short the mic bias. That is a pop, not a feature."],
  ["vx-t-nfc-tap", "Mobile extras", "NFC is a tap field, not Wi-Fi",
    "NFC is centimetres, for pairing and payments. It is not a file pipe. Android Beam nostalgia is not how you move a 4 GB video.",
    "Hold the phones a metre apart so NFC can breathe.",
    "Tap the marked zone (often camera hump), unlock, and use a real share method for big files.",
    "A metal case or a misaligned coil is a ‘doesn’t tap’ ticket, not a dead eSE by default."],
  ["vx-t-lightning-vs-usbc-phone", "Mobile extras", "Lightning and USB-C are not ‘a cable’",
    "Pins, authentication chips, and PD rules differ. A Lightning brick with a USB-C plug on the wall side is still a Lightning conversation at the phone.",
    "If both ends are metal, it will charge and sync every phone ever made.",
    "Match the phone’s port, MFi/e-marker where it matters, and whether you need data or charge-only.",
    "A charge-only Lightning lead will not restore a phone in Finder. That is the cable, not iOS."],
  ["vx-t-ip-rating-port", "Mobile extras", "IP68 is not a diving licence for a charging port",
    "Ingress ratings are lab tests. A wet USB-C port can corrode or refuse charge. Liquid contacts indicators exist for a reason.",
    "IP68 means you can rinse it in the surf and plug it in wet to dry it faster.",
    "Power off, dry, do not rice as a ritual, and wait for the port to actually dry.",
    "Rice dust in a port is a new fault. Silica and time beat folklore."],
  ["vx-t-phone-battery-swell", "Mobile extras", "A phone that won’t sit flat is a pack, not a case",
    "Li-ion swell lifts screens. Heat and cheap cases bake it. Do not clamp, puncture, or ‘massage’ it flat.",
    "Warm it with a hair dryer so the glue yields and the bulge hides.",
    "Power down, stop charging, bag it, and replace at a shop that recycles packs properly.",
    "A slight lift at the camera bump is enough. Do not wait for the glass to become a spring."],
  ["vx-t-digitizer-ghost-touch", "Mobile extras", "Ghost touch is often glass, moisture, or a case",
    "Phantom taps can be a cracked digitizer, a wet screen protector, or a metal plate case. A software calibration is a maybe, not a first god.",
    "Ghost touch means malware. Factory reset from a cafe.",
    "Dry it, uncase it, boot safe/safe-ish, then replace glass if the grid is physically wrong.",
    "A swollen pack that presses the glass from behind is a safety swap, not a ‘touch firmware’."],
  ["vx-t-laptop-gpu-mux", "Mobile extras", "A mux switch is why HDMI might ignore the RTX",
    "Advanced Optimus / muxed laptops can drive the panel from iGPU or dGPU. An HDMI port soldered to the iGPU will not ‘see’ the discrete card the way a gamer expects.",
    "If NVIDIA Control Panel exists, every port is the NVIDIA port.",
    "Read which output is wired where. Set the mux/Ultimate mode only as the OEM documents.",
    "External 4K@120 wants the right port plus DP bandwidth, not a prayer to the GeForce overlay."],
  ["vx-t-cmos-coin-cell", "Hardware extras", "The coin cell is a clock, not a Windows password",
    "CR2032 keeps RTC and some BIOS settings. A dead cell is ‘wrong time every boot’, not a dead CPU.",
    "Replace the CMOS battery to clear a BitLocker PIN you forgot.",
    "Note settings, power down, swap the cell, then reset time and boot order.",
    "Some boards need a jumper plus the cell. A laptop cell can be a 2-pin lead, not a coin you pry."],
  ["vx-t-am5-lga-socket", "Hardware extras", "Pins live on the CPU or the board, not both as a vibe",
    "AM4/AM5 put pins on the CPU (PGA). Intel desktop LGA puts lands on the CPU and pins in the socket. A bent socket pin is a board, not a ‘reseating’ hobby.",
    "If it does not drop in, push harder. Gold can take it.",
    "Check orientation notches, do not scrape paste into the socket, and use the arm, not a palm strike.",
    "A dropped screw in an LGA socket is a warranty photo, not a magnet adventure."],
  ["vx-t-atx-sfx-tfX", "Hardware extras", "SFX is not a cute ATX",
    "ATX, SFX, TFX, FlexATX are shapes and mounting. An SFX-L may still need a bracket. Cables are not always the same kit.",
    "If the wattage matches, the PSU fits any case that says ‘ATX’ on a forum.",
    "Measure the cage, check the spec sheet, and do not force a modular cable from brand A into brand B.",
    "A TFX in a slim desktop is a special bird. An ATX brick will not origami into it."],
  ["vx-t-eps-8pin", "Hardware extras", "CPU 8-pin is not a GPU 8-pin in spirit",
    "EPS12V/ATX12V CPU power and PCIe GPU power can look like cousins. The pinout and the side they feed are not interchangeable as a lifestyle.",
    "An 8-pin is an 8-pin. Split a GPU cable to the CPU to save money.",
    "Follow the board silk: CPU/ATX12V vs PCIe. Use the cables that came with that PSU.",
    "A 4+4 CPU cable in a 8-pin GPU socket is how you invent smoke."],
  ["vx-t-nvme-heatsink-dram", "Hardware extras", "A DRAM-less NVMe still needs air, not a sticker",
    "DRAM cache vs HMB is a performance personality. A heatsink can be required to stop thermal throttle. A pretty heatsink that hits the GPU is a clearance problem.",
    "If it is NVMe it cannot throttle. PCIe is ice-cold by law.",
    "Check DRAM vs HMB for the workload, and check heatsink height against the GPU and M.2 shield.",
    "Some OEM shields are the thermal pad. Lose the pad, gain a thermal cliff."],
  ["vx-t-xmp-expo", "Hardware extras", "XMP/EXPO is an overclock with a brochure",
    "JEDEC is the safe table. XMP/EXPO is a vendor profile. A kit can POST at JEDEC and fail at the pretty number on the heat spreader.",
    "If the box says 6000 MT/s, the board owes you 6000 out of the bag.",
    "Enable the profile, test with a memory stresster, and drop a step if the IMC is the limit.",
    "Mixing kits kills XMP even if both say DDR5-6000. Train, then admit defeat."],
  ["vx-t-sata-power-data", "Hardware extras", "SATA data is not SATA power",
    "The L-shaped data lead is not the wide power lead. A 3.3 V pin on some power cables can keep a disk from spinning (the ‘orange wire’ folklore has a real cousin).",
    "One cable does both if you push. Gold is gold.",
    "Click data until it seats, seat power fully, and check the port is enabled in BIOS.",
    "A SATA-to-USB bridge that swallows TRIM is a different ticket from a missing power lead."],
  ["vx-t-molex-sata-adapter", "Hardware extras", "Molex-to-SATA adapters are a fire rumour with a body count",
    "Cheap moulded Molex-to-SATA can miswire 12 V onto 5 V. That is a disk fryer. Use the PSU’s native SATA power.",
    "Adapters are how professionals add disks. More adapters, more better.",
    "Native SATA power from the same PSU. If you must adapt, use a known-good, not a market-stall moulding.",
    "A drive that dies the second it gets power is a wiring autopsy, not ‘bad sectors from the factory’."],
  ["vx-t-gpu-sag-slot", "Hardware extras", "PCIe slots are not structural beams",
    "A heavy card twists the slot. Sag braces exist. A cracked slot is a board, not a driver.",
    "If it seats, the plastic latch will hold a 2 kg card in a van.",
    "Support the card, use the case bracket screws, and do not carry the PC by the GPU.",
    "Riser cables add flex and signal issues. A mining riser is not a silent workstation part."],
  ["vx-t-case-airflow", "Hardware extras", "Intake and exhaust are a path, not a fan count",
    "Front/bottom in, rear/top out is a common plan. Fighting fans make turbulence and dust sculptures. Mesh vs glass is a thermal choice.",
    "More RGB fans always drop CPU temps, even if they all blow at each other.",
    "Pick a direction, dust-filter the intakes, and check the GPU is not in a dead pocket.",
    "A USB-powered fan in the window is not a case airflow design."],
  ["vx-t-thermal-throttle", "Hardware extras", "Throttle is a temperature policy, not a crash",
    "CPUs and GPUs slow clocks to stay in a TDP box. A game at 30 fps with a quiet fan curve can be a thermal limit, not a ‘dead GPU’.",
    "If it still displays, thermals cannot be the problem. Only blue screens are heat.",
    "Log temps, clean dust, reseat the cooler, and check the fan header actually spins.",
    "Laptop heat pipes clogged with old paste throttle first, then they look like ‘Windows is slow’."],
  ["vx-t-m2-key-bm", "Hardware extras", "B-key, M-key, and B+M are not a mood",
    "M-key NVMe uses PCIe. B-key is often SATA or WWAN. A B+M SATA stick will not run NVMe speeds in an M-key slot just because it fits loosely.",
    "If it slides in, the protocol matched. Keying is decorative.",
    "Look at the notch vs the socket. Match SATA/NVMe/WWAN to the silk screen.",
    "A pin you force past a key is a board repair, not a victory."],
  ["vx-t-ahci-raid-boot", "Hardware extras", "AHCI vs RAID in BIOS is a boot personality",
    "Intel RST RAID mode needs drivers at install. Flip to AHCI after install without the right dance and you get INACCESSIBLE_BOOT_DEVICE.",
    "RAID in BIOS makes the disk faster even with one stick. Always on.",
    "Pick the mode before you install. If you must switch, follow the OEM’s safe procedure, then repair the boot.",
    "A fake-RAID 0 of two NVMe boots fast and dies together. That is not a backup."],
  ["vx-t-pcie-bifurcation", "Hardware extras", "×16 is a lane budget, not a promise to every slot",
    "CPU and chipset share lanes. A second ×16 slot may be ×8/×4/×1 when an NVMe is filled. Bifurcation is a BIOS feature, not a sticker.",
    "Every black slot is ×16 from the CPU. Count the plastic.",
    "Read the board’s slot table with your actual CPU and M.2 population.",
    "A USB4 card, an NVMe, and a GPU can fight. The winner is the diagram, not hope."],
  ["vx-t-cpu-cooler-socket", "Hardware extras", "AM4 brackets are not LGA 1700 brackets",
    "Mounting kits are socket-specific. An offset ILM and a wrong bracket is a crushed corner or a spinning fan with no contact.",
    "If the screws bite, the cooler is compatible. Torque is a vibe.",
    "Use the kit for that socket, apply a pea of paste, and check cooler pressure is even.",
    "A pump header on a SYS_FAN at 30% is a dying AIO that looks like a CPU fault."],
  ["vx-t-front-panel-pins", "Hardware extras", "Power SW is two pins, not a rainbow",
    "Front-panel HD-AUDIO, USB, and the tiny power/reset cluster are easy to swap. A PC that ‘won’t power on’ with a working PSU is often the switch leads.",
    "If the case is metal, the board will find the pins by magnetism.",
    "Jump the power pins with a screwdriver to test, then seat the labelled cluster or cables.",
    "A USB 3.0 front header forced into a USB 2.0 pin row is a bent-pin story."],
  ["vx-t-cat6-vs-cat6a", "Networking extras", "Cat6A is a spec, not a colour of plastic",
    "Cat5e/6/6a differ in bandwidth and alien crosstalk. 10G over copper wants Cat6A for the full 100 m story. A flat ‘Cat6’ from a bargain bin can be a lie.",
    "If it clicks into RJ45 it is Cat6A. The latch is the certification.",
    "Read the jacket print, match the job (PoE, 10G, length), and terminate to the stated T568.",
    "A 30 m cheap patch that overheats on PoE++ is a gauge and copper-purity ticket."],
  ["vx-t-t568a-b", "Networking extras", "A and B are pinouts, not quality grades",
    "T568A and T568B swap the orange and green pairs. A cable with A on one end and B on the other is a crossover, which modern NICs usually survive — and testers still flag.",
    "Mix A and B so the colours look festive. Gigabit loves chaos.",
    "Pick one standard for the building and stick to it. Punch both ends the same unless you meant a crossover.",
    "A split pair that still ‘pings’ can fail 1G. The tester’s wiremap is the adult."],
  ["vx-t-poe-budget", "Networking extras", "PoE is a budget, not a personality",
    "802.3af/at/bt are watt classes. A switch with 60 W total cannot feed eight 15 W cameras. Unmanaged ‘PoE’ injectors are still a power supply.",
    "If the port says PoE, it can run a heater. Physics is optional.",
    "Add device watts, leave headroom, and match af/at/bt to the camera/AP class.",
    "A device that boots then dies is often budget exhaustion, not a ‘bad PoE chip’ first guess."],
  ["vx-t-wifi-bands-246", "Networking extras", "2.4, 5, and 6 GHz are different rooms",
    "2.4 goes further and is crowded. 5/6 are faster and die on brick. A ‘Wi-Fi 6’ AP still has a 2.4 radio that can be a swamp.",
    "The highest GHz number always has the best range. 6 GHz is for paddocks.",
    "Put IoT on 2.4 if it must, put people on 5/6, and stop hiding SSID as a plan.",
    "A mesh node on 6 GHz through two plaster walls will look like a broken backhaul."],
  ["vx-t-channel-width", "Networking extras", "80 MHz is a width, not a speed cheat code",
    "20/40/80/160 MHz eat more spectrum. Neighbours and DFS make wide channels flake. A quiet 40 can beat a screaming 80.",
    "Always set 160 MHz so the box speed on the carton comes true.",
    "Start 40 on 5 GHz in dense flats, watch retries, then widen if the air is actually empty.",
    "A DFS hit looks like the SSID vanished for a minute. That is radar, not a rebooting modem."],
  ["vx-t-dfs-channels", "Networking extras", "DFS channels can go on holiday",
    "Some 5 GHz channels must yield to radar. The AP vacates, clients sulk. A ‘Wi-Fi died for 10 minutes’ can be DFS, not a WAN outage.",
    "If the SSID disappears, the NBN box is always the villain.",
    "Pick non-DFS channels in flight paths if you need stubborn uptime, or accept the pause.",
    "Weather radar and airports are why your CBD office AP is superstitious."],
  ["vx-t-mac-vs-ip", "Networking extras", "MAC is the nametag; IP is the address for today",
    "L2 uses MAC. L3 uses IP. A reservation is DHCP tying an IP to a MAC. Cloning a MAC to steal a reservation is a ticket, not a skill.",
    "If the IP ping works, the MAC cannot matter. Ever.",
    "Read ARP when two devices fight an IP. Check the reservation against the actual MAC.",
    "A printed MAC on a sticker can be the Wi-Fi radio, not the Ethernet port. Quote the right one."],
  ["vx-t-default-gateway", "Networking extras", "The gateway is the door off this subnet",
    "No default gateway means local-only. A wrong gateway is a confident path into a wall. Traceroute is the story, not ipconfig as poetry.",
    "Set the gateway to 1.1.1.1 because that is ‘the internet’.",
    "Gateway must sit in the same subnet as the host. Then test a hop past it.",
    "Two gateways without policy routing is a coin flip. Pick one on a simple LAN."],
  ["vx-t-slash24-mask", "Networking extras", "/24 is 256 addresses, not 24 hosts",
    "A mask of 255.255.255.0 is /24: 254 usable in the usual private tale. /16 is a different size. Writing 255.255.255.255 as a host mask is a special (and usually wrong) move.",
    "/24 means 24 computers are allowed. The slash is a headcount.",
    "Match mask on host, gateway, and DHCP pool. Then count usable addresses before you promise a lab.",
    "A printer at .0 or .255 on a /24 is a folk tale that sometimes works and often does not."],
  ["vx-t-crimp-vs-punchdown", "Networking extras", "A crimp is a plug; a punchdown is a block",
    "RJ45 plugs are crimped. Keystone/patch panels are punched. A ‘crimp a wall jack’ is how you invent a mystery fail.",
    "If the pair is untwisted for 8 cm it is fine, because gigabit is magic.",
    "Keep twists to the termination, use the right die, and test wiremap plus length.",
    "A pass-through plug that you do not trim is a short waiting for a boot."],
  ["vx-t-fibre-lc-sc", "Networking extras", "LC, SC, and ST are ferrule religions",
    "LC is small and latchy, SC is square, ST is twist-bayonet. The fibre type (OS2 vs OM3/4) is the other half of the ticket.",
    "If it is glass it is all the same. Colour is decorative.",
    "Match connector, polish (UPC/APC), and mode. Do not stare into a live fibre.",
    "APC green is an angle. Mixing APC and UPC makes a lossy prayer."],
  ["vx-t-smf-vs-mmf", "Networking extras", "Single-mode is not ‘better multi’",
    "OS2 single-mode is a different core and laser. OM3/OM4 multimode is VCSEL-friendly. An SMF SFP in MMF (or the reverse) is a dim link, not a firmware.",
    "Yellow jackets are always faster. Orange is old and therefore wrong.",
    "Match transceiver, fibre, and distance. Read the optic’s coded type.",
    "A 10G-SR optic on 10 km of OS2 will not find religion. SR is short-reach multimode."],
  ["vx-t-sfp-plus", "Networking extras", "SFP and SFP+ are cousins, not twins",
    "SFP is 1G. SFP+ is 10G. Some cages accept both; some optics will not clock down. A copper 10G DAC is a cable with SFP+ ends, not a miracle RJ45.",
    "If it clicks into the cage it will run at the switch’s fastest number.",
    "Check the switch’s supported list, the optic’s speed, and whether you needed a DAC, AOC, or RJ45 transceiver.",
    "A 1G RJ45 SFP in a 10G-only port is a silent hole. The LED will not save you."],
  ["vx-t-loopback-plug", "Networking extras", "A loopback plug tests the NIC, not the universe",
    "An RJ45 loopback ties TX to RX. A good NIC can show link without a switch. It does not prove the wall run.",
    "If loopback works, the building cable is fine. Obviously.",
    "Use loopback for the NIC, a toner/tester for the run, and a known-good patch for the last metre.",
    "A fibre loopback is a different part. Do not jam an RJ45 loop into an SFP cage."],
  ["vx-t-tone-probe", "Networking extras", "Tone and probe find a pair, not a subnet",
    "A toner sings on a pair. A probe hears it in a bundle. It will not tell you VLAN 40 from VLAN 50.",
    "The loudest tone is the correct pair even if you are on the shield.",
    "Isolate, tone from one end, probe at the panel, and label both ends in the same breath.",
    "PoE on the pair can confuse some toners. Know your tool."],
  ["vx-t-link-light-split", "Networking extras", "No link light is a layer-1 sentence",
    "Speed LED vs link LED vs activity. A cable with a broken TX can still look pretty. Autoneg fail is a duplex cousin of this ticket.",
    "If the OS shows ‘connected’, the LED cannot matter. Trust Windows.",
    "Known-good cable, other port, other NIC. Then the wall. Then the switch config (shutdown, VLAN, errdisable).",
    "err-disabled from a loop or BPDU guard looks like a dead port. Read the switch log."],
  ["vx-t-managed-vs-unmanaged", "Networking extras", "An unmanaged switch has no VLAN opinions",
    "Unmanaged is a dumb repeater of frames (plus maybe jumbo). VLANs, QoS, and ‘guest’ live on managed boxes. A $30 8-port will not isolate IoT.",
    "Any switch with more ports is a firewall if you believe hard.",
    "Buy managed when you need VLANs or PoE budgets you can see. Leave unmanaged for a simple bench.",
    "A loop between two unmanaged switches is a broadcast storm with no off switch but yank."],
  ["vx-t-wifi-roaming-sticky", "Networking extras", "Sticky clients hug a weak AP",
    "Phones hold a familiar BSSID until it is awful. Fast roaming (11r/k/v) is a design, not a checkbox you tick without testing.",
    "More transmit power on the office AP makes roaming perfect. Always raise power.",
    "Tune power down so cells overlap politely, match SSIDs, and test a walk with logs.",
    "A mesh ‘satellite’ on the wrong channel plan is a sticky-client factory."],
  ["vx-t-captive-portal", "Networking extras", "A captive portal is a hijack with a form",
    "HTTPS can look ‘broken’ until the portal is satisfied. Some clients need a random HTTP hit. It is not a CA failure first.",
    "If Google is sad, the fibre is cut. Ignore the hotel login page.",
    "Open a plain HTTP site or the portal URL, authenticate, then test DNS again.",
    "A never-expires guest voucher on the shop Wi-Fi is how the neighbour prints on your till."],
  ["vx-t-fast-startup", "OS extras", "Fast Startup is a hybrid hibernation",
    "Windows Fast Startup skips a cold kernel. Driver and firmware tickets can hide until you shut down for real. ‘Restart’ and ‘Shut down’ are not twins here.",
    "Shut down always clears RAM and firmware fights. That is why it is named shut down.",
    "Disable Fast Startup when a dock, GPU, or BIOS setting will not stick. Use Restart to force a real kernel unload.",
    "A laptop that only boots after a 30-second hold is often this plus a half-asleep NVMe."],
  ["vx-t-gpt-vs-mbr", "OS extras", "GPT is the modern map; MBR is the 2 TB museum",
    "UEFI wants GPT for Windows on most PCs. MBR plus CSM is a compatibility hat. A 4 TB disk with MBR wastes a future.",
    "Convert to MBR to make any OS happier. Old is stable.",
    "Match firmware mode to disk style. Do not convert a live OS disk with a random one-click tool.",
    "A USB installer that boots as BIOS will refuse a GPT target and look like a ‘dead stick’."],
  ["vx-t-uefi-vs-csm", "OS extras", "CSM is a backwards hat, not a speed boost",
    "Compatibility Support Module emulates BIOS. Secure Boot wants UEFI native. A ‘no bootable device’ after a board swap is often CSM vs GPT.",
    "Enable every legacy option so the PC becomes more modern.",
    "Pick UEFI+GPT for current Windows, and only dip into CSM for a museum OS.",
    "A network PXE that only offers IPv4 BIOS will ignore a UEFI-only NIC option."],
  ["vx-t-winre-vs-media", "OS extras", "WinRE is on the disk; install media is a USB",
    "WinRE can be broken if the recovery partition is toast. A full ISO on USB is a different toolkit. Reset this PC still needs a healthy store.",
    "WinRE re-downloads Windows from Bing. Always.",
    "If RE fails, boot known-good media, and do not format until you have the files off.",
    "A 100 MB EFI partition is not the 500+ MB recovery partition. Do not merge them as a vibe."],
  ["vx-t-ntfs-exfat-apfs", "OS extras", "A file system is a contract with an OS",
    "NTFS is Windows-native with permissions. exFAT is a camera/USB peace treaty. APFS is Apple. Linux ext4 will look like ‘format?’ in Explorer.",
    "Format everything NTFS because Windows is the world.",
    "Pick the FS for the hosts that must write. Use a tool that understands the other side’s permissions.",
    "A Time Machine disk you format NTFS is a paperweight with a pretty cable."],
  ["vx-t-pagefile-vs-ram", "OS extras", "The pagefile is not free RAM",
    "When RAM is full, Windows pages. A tiny SSD with no pagefile will hard-fail before it politely slows. Task Manager’s ‘compressed’ is another cousin.",
    "Set pagefile to 0 to make the PC faster. Disk is slow so avoid it.",
    "Leave a sensible pagefile on the OS disk. Add RAM if you are paging a video edit all day.",
    "A ‘low memory’ popup with 8 GB free is often a 32-bit process cap, not a pagefile sermon."],
  ["vx-t-hiberfil", "OS extras", "hiberfil.sys is a sleep souvenir",
    "Hibernate writes RAM to disk. Disable hibernate to reclaim the file. Fast Startup uses a related trick. A full disk can be this file, not photos.",
    "Delete hiberfil.sys in Explorer like a screenshot. It will stay gone.",
    "powercfg /hibernate off when you mean it, after you know you do not need hybrid sleep.",
    "A dock that will not wake is sometimes hibernate vs sleep vs Fast Startup in a trench coat."],
  ["vx-t-diskpart-clean", "OS extras", "clean is a murder; format is a haircut",
    "diskpart clean drops the partition table. format drops a volume’s files. The wrong disk index is a career event.",
    "clean all and format are the same, and both are undoable from Recycle Bin.",
    "List disks, check size, check serial, then type with both eyes. Backup first.",
    "A USB installer that ‘disappeared’ was often disk 0 vs disk 1 in a panic."],
  ["vx-t-macos-smc", "OS extras", "SMC/T2/reset dances are model-specific",
    "Apple power/SMC/NVRAM resets are not one Google result. Apple silicon made some of these museum steps. A wrong hold can just reboot.",
    "Hold every button for 40 seconds on every Mac. It is tradition.",
    "Use the support article for that exact year. Then check power, display, and startup disk.",
    "A firmware password is not an SMC. Do not promise a reset that needs the owner."],
  ["vx-t-linux-liveusb", "OS extras", "A live USB is a test hat, not an install",
    "Booting a live image proves CPU/RAM/display without touching the disk — until you hit Install. Persistent live vs full install is a choice.",
    "If the live session works, the installed disk cannot be the problem later. Ever.",
    "Test hardware from live, then install to the intended disk with a verified checksum ISO.",
    "Secure Boot may refuse an unsigned live stick. That is a key, not a dead USB port."],
  ["vx-t-secure-boot-keys", "Security extras", "Secure Boot is a signature chain, not an antivirus",
    "The firmware checks bootloaders against keys. Dual-boot dances and some GPUs trip it. Turning it off to ‘make Linux work’ is a trade, not a flex.",
    "Secure Boot makes the OS faster and cooler. That is why gamers disable it.",
    "Keep it on for Windows. Enrol keys the distro documents if you dual-boot.",
    "A cloned disk with the wrong BCD can look like a Secure Boot failure. Read the actual message."],
  ["vx-t-bios-vs-windows-pw", "Security extras", "A firmware password is not the user PIN",
    "Supervisor/BIOS passwords gate settings and sometimes boot. Windows Hello is a different lock. Clearing CMOS may or may not drop the firmware password — model lottery.",
    "The Windows PIN unlocks the BIOS. One lock to rule them.",
    "Document who holds the firmware password. Do not ‘reset CMOS’ as a first move on a locked board.",
    "Some laptops need a vendor hash/challenge. That is paperwork, not a jumper."],
  ["vx-t-bitlocker-suspend", "Security extras", "Suspend is not decrypt",
    "Suspend BitLocker for a firmware change so TPM measurements can change without a recovery prompt. Decrypt is a full wipe of the protector scheme.",
    "If you are updating BIOS, decrypt the whole disk overnight. It is the only way.",
    "Suspend, change firmware, resume. Keep recovery keys out of the laptop bag.",
    "A board swap is a new TPM. Have the 48-digit key before the screwdriver."],
  ["vx-t-cable-lock-kensington", "Security extras", "A cable lock is delay, not a vault",
    "Kensington slots slow a grab-and-run. They do not stop a determined person with time. Policy still wants encryption and a lock screen.",
    "If it has a lock slot, the data is safe in a cafe. Skip BitLocker.",
    "Use the lock as a delay, encrypt the disk, and do not leave it overnight on a hook.",
    "A slot you strip with the wrong tool is a chassis repair plus a false sense of safety."],
  ["vx-t-privacy-filter", "Security extras", "A privacy filter is geometry, not magic glass",
    "Microlouvres cut side angles. They do not stop a camera behind you. Brightness will look worse; that is the trade.",
    "If the screen is matte, shoulder surfers cannot read it. Science.",
    "Fit the right size, warn the user about brightness, and still lock the session.",
    "A filter on a touch laptop can ruin the digitizer feel. Test before you kit twenty of them."],
  ["vx-t-dumpster-drive", "Security extras", "A bin disk is still a disk",
    "Decommissioned HDDs in office bins are a classic leak. Policy wants wipe or shred with a record.",
    "If it failed SMART it cannot be read. Toss it.",
    "Asset-tag, sanitise per standard, and bin only the chassis that is empty.",
    "SSDs still hold remnants until a real sanitise. ‘I deleted the partition’ is not that."],
  ["vx-t-firmware-update-source", "Security extras", "A BIOS file from a forum is an incident",
    "Firmware needs integrity. Vendors sign updates. A ‘unlocked’ BIOS is how you own a fleet.",
    "Newer is better, so any GitHub dump is a gift.",
    "Download from the OEM, verify the model string, and keep AC power on during the flash.",
    "A laptop that dies mid-flash wants a vendor recovery, not a second random file."],
  ["vx-t-rma-packaging", "Shop craft", "RMA packing is part of the repair",
    "A GPU in a bag in a box without a brace is a new fault. ESD bags, foam, and the original serial photo live here.",
    "If it already failed, packing cannot matter. Throw it in a satchel.",
    "Photo, serial, ESD bag, immobilise the cooler, and quote the RMA on the outside.",
    "A leaking AIO in an RMA without a bag is how you share coolant with someone else’s board."],
  ["vx-t-thermal-camera-vs-ir", "Shop craft", "An IR gun is a spot; a camera is a map",
    "A cheap pyrometer averages a spot and lies on shiny metal. A thermal camera finds a hot VRM or a cold pump. Emissivity is a real knob.",
    "Point any red laser thermometer at a heat spreader and trust the number to 0.1°C.",
    "Use contact or a known-emissivity tape on metal. Compare sockets, not absolute poetry.",
    "A ‘hot’ charger brick is often normal. Compare to a known-good under the same load."],
  ["vx-t-cannibalise-parts", "Shop craft", "Cannibalising is a loan with a serial",
    "A RAM stick from a waiting unit must be tagged back. Otherwise you invent two faults and one mystery.",
    "If both PCs are broken, mix all parts until one boots. Speed is kindness.",
    "One donor, one part, labels both ways, and a ticket note.",
    "A ‘known-good’ that never returns is how the drawer becomes folklore."],
  ["vx-t-loaner-pool", "Shop craft", "A loaner is an asset, not a souvenir",
    "Loaners need images, asset tags, and a wipe on return. A user’s files on a loaner is a privacy ticket.",
    "Let the user keep the loaner if their PC is slow. It is simpler.",
    "Sign out, image, wipe, and check the charger came back with the same wattage.",
    "A 45 W loaner brick on a 100 W workstation laptop is a slow-charge complaint you created."],
  ["vx-t-backup-before-reload", "Shop craft", "Reload is a last hat, not a first spell",
    "An OS reload without a file pass is how you become a story. Browser profiles and PST files hide.",
    "Format is faster than asking which folders matter. Do it.",
    "Copy Desktop/Documents/Downloads, browser data, and the actual line-of-business folder, then reload.",
    "OneDrive ‘known folders’ can look empty locally and full in the cloud. Check both."],
  ["vx-t-image-vs-inplace", "Shop craft", "An in-place repair is not a golden image",
    "In-place upgrade keeps apps and can fix component store rot. A golden image is a known baseline. They answer different tickets.",
    "Sysprep images fix every app crash. Always reimage first.",
    "Try repair/in-place when the profile and apps are the value. Image when the OS is compost.",
    "A 3-year-old image with a 2020 CU is a new incident the moment it hits the network."],
  ["vx-t-compressed-air-vac", "Shop craft", "Air moves dust; a vacuum at the intake catches it",
    "Canned air inside a laptop without a vacuum nearby paints the room and the fans in reverse. Hold fans so they do not become generators.",
    "Spin the fans with air for a nice turbine sound. It is fine.",
    "Hold the fan, blow out, vacuum the cloud, and replace filters.",
    "A data-centre vacuum with ESD rating is not your home vacuum on a motherboard."],
  ["vx-t-laptop-screw-map", "Shop craft", "A screw map is a document, not a memory sport",
    "Laptop screws differ in length by 1 mm and will punch a board. Photos and a grid beat a pile.",
    "If it threads, it was the right screw. Keep going.",
    "Photograph each stage, sort by length, and do not mix hinge screws with SSD screws.",
    "A hinge screw in a battery bay is a puncture waiting for a swell."],
  ["vx-t-connector-click", "Shop craft", "Seated is a click, not ‘it went in’",
    "Display, battery, and M.2 cables can look seated and not be. A backlight flicker after a ‘resit’ is this.",
    "If it is under the tape it is seated. Tape is torque.",
    "Feel the click, tug-test gently, and replace tape that was structural.",
    "A battery connector that is one pin off is a board-killer. Look before you press."],
  ["vx-t-nopost-vs-noboot", "Shop craft", "No POST is not no boot",
    "No POST: no logo, maybe beeps, fans may spin. No boot: POST then a disk/OS story. Mixing them wastes hours.",
    "No display means Windows. Reinstall from a phone torch.",
    "Split: power, then POST codes/beeps, then display, then boot device, then OS.",
    "A USB installer that never appears can still be a POST-complete machine with a bad boot order."],
  ["vx-t-intermittent-vs-hard", "Shop craft", "Intermittent wants a log; hard fail wants a swap",
    "A once-a-week freeze is heat, power, or a driver. A never-POSTs is RAM/board/CPU/power. Treat them differently.",
    "If it is intermittent, replace the motherboard first to save time.",
    "Reproduce, log temps/events, then swap one variable. Hard fail: known-good RAM/PSU/display.",
    "A van that only fails on hot days is a thermal ticket with a calendar."],
  ["vx-t-warranty-sticker-myth", "Shop craft", "A warranty sticker is not always the law",
    "Some regions limit void-for-sticker games. Still: liquid indicators and impact are real. ACL in Australia has opinions vendors sometimes forget.",
    "If you opened it, you owe the full retail price forever. That is physics.",
    "Check the actual warranty terms and consumer law, photograph the fault, and do not lie on the RMA.",
    "A ‘void if removed’ hologram on a user-CRU door is a vibe, not a statute."],
  ["vx-t-quote-vs-t-and-m", "Shop craft", "A quote is a cap; T&M is a meter",
    "Time and materials without a written cap is how a $90 DC jack becomes a $600 board plus labour. Say the risk before the screwdriver.",
    "Start work and see. Money is a later conversation.",
    "Write the diagnosis fee, the likely FRU, and the no-fix outcome. Get a yes.",
    "A ‘while you are here’ extra is a new quote, not a free dessert."],
  ["vx-t-customer-data-swap", "Shop craft", "A swapped disk still has their life on it",
    "RMA and ‘dead’ NVMe units hold data. Policy: wipe, encrypt-at-rest, or destroy. A ‘it doesn’t enumerate’ disk can still be imaged in a lab.",
    "If Windows cannot see it, nobody can. Bin it.",
    "Follow the sanitisation standard, record the asset, and do not reuse a customer disk in a loaner.",
    "A cloned donor disk that goes back to the customer with your test files is a privacy incident."],
  ["vx-t-multimeter-continuity", "Shop craft", "Continuity is a beep, not a voltage",
    "Ohms/continuity with power off. Voltage with power on and a plan. Measuring 12 V in continuity mode is how you learn about fuse icons.",
    "If it beeps, 12 V is present. The beep is power.",
    "Power off for continuity. Meter the brick on voltage. Do not pierce a Li-ion pack to ‘see 11 V’.",
    "A DC jack that has continuity to ground on the centre pin may be a short — or you are on the wrong pad."],
  ["vx-t-psu-paperclip", "Shop craft", "A paperclip test is a spin, not a load test",
    "Jumping PS_ON on ATX can spin a fan. It does not prove 12 V under a GPU. A shorted board can still twitch a fan.",
    "If the PSU fan moves, the PSU is good. Install it.",
    "Use a tester or a known-good load. Then swap. Do not paperclip a SFX with a mystery adapter.",
    "A ‘click no spin’ can be a shorted rail on the board, not a dead PSU. Split the diagnosis."],
  ["vx-t-toner-safety", "Shop craft", "Toner is a powder with rules",
    "Do not vacuum toner with a home vac (fine dust + static). Skin and lungs are not a filter spec. Laser techs use rated vacs.",
    "Blow toner with canned air in the office so it leaves. Kind.",
    "Contain, use the right vac, and do not bake a cartridge in an oven ‘to revive it’.",
    "A leaking cartridge in a van is a contamination story. Bag it."],
  ["vx-t-chain-of-custody", "Shop craft", "A police PC is not a normal bench ticket",
    "Legal holds and HR seizures need a chain: who touched it, when, and whether you powered it. Curiosity is a discovery event.",
    "Boot it to see if it works. That is helpful.",
    "Stop, follow the process, photograph seals, and do not run a USB ‘antivirus’.",
    "A forgotten memory dump you generated can be a legal souvenir. Do not make one for fun."],
]);
