import type { Project } from "../types";

export const makeLifeProjects: Project[] = [
  {
    id: "english-howto",
    subject: "english",
    title: "How-to that a stranger could follow",
    blurb: "One job, numbered steps, no ghost ingredients.",
    goal: "A how-to of 150–250 words for a real task you can do, tested on a second person or your future self.",
    materials: [
      "A task you can actually perform (boil rice, reset a modem, fold a fitted sheet)",
      "Notes, then a clean draft",
    ],
    steps: [
      {
        id: "s1",
        title: "Name the reader and the end state",
        body: "Who is this for, and what does ‘done’ look like? “Someone who has a kettle” is better than “everyone”.",
      },
      {
        id: "s2",
        title: "List materials and the dangerous bit",
        body: "If a step can scald, shock, or delete files, put it before step 1. Numbered steps, one action each.",
      },
      {
        id: "s3",
        title: "Cut the performance",
        body: "Delete jokes that hide a measurement. Prefer verbs. Read it aloud; where you stumble, the reader will too.",
      },
      {
        id: "s4",
        title: "Test it",
        body: "Hand it to someone, or follow only the page tomorrow. Write the step that failed. Fix that step, not the vibe.",
      },
    ],
    checklist: [
      { id: "d1", label: "Reader and done-state are stated in the opening" },
      { id: "d2", label: "Materials and any hazard sit before the numbered actions" },
      { id: "d3", label: "Steps are numbered, one action each, 150–250 words total" },
      { id: "d4", label: "A test (other person or delayed self) produced one fix" },
    ],
    pathIds: ["e-sentence-vs-fragment", "e-active-passive", "e-parallel"],
    difficulty: "easy",
    minutes: 35,
    xp: 90,
  },
  {
    id: "english-sentence-surgery",
    subject: "english",
    title: "Sentence surgery",
    blurb: "Five broken sentences. Same meaning, fewer accidents.",
    goal: "A before/after sheet: fragment, splice, agreement, tense, and a dangling modifier — each fixed with a why.",
    materials: [
      "The five patients in step 1, or five from your own draft",
      "Paper",
    ],
    steps: [
      {
        id: "s1",
        title: "Admit the patients",
        body: "Use these or swap in your own: “Because the bus was late.” / “The quiz was hard, I guessed.” / “The list of answers were wrong.” / “Yesterday she walks in and sits.” / “Running for the train, the coffee spilled.”",
      },
      {
        id: "s2",
        title: "Name the injury",
        body: "Fragment, splice, agreement, tense shift, dangle. If you misname it, the fix will be theatre.",
      },
      {
        id: "s3",
        title: "Operate once",
        body: "One clean sentence each. Keep the meaning. Do not inflate into a paragraph to hide the join.",
      },
      {
        id: "s4",
        title: "Write the rule in your mouth",
        body: "A six-word reminder per injury you would actually remember in a SAC or an email.",
      },
    ],
    checklist: [
      { id: "d1", label: "Five before sentences are quoted" },
      { id: "d2", label: "Each injury is named correctly" },
      { id: "d3", label: "Each after sentence keeps the meaning and stands alone" },
      { id: "d4", label: "A short remember-rule exists for each fix" },
    ],
    pathIds: ["e-comma-splice", "e-run-on", "e-subject-verb", "e-tense-shift", "e-modifier-dangle"],
    difficulty: "medium",
    minutes: 30,
    xp: 120,
  },
  {
    id: "english-reading-moves",
    subject: "english",
    title: "Annotate a short article",
    blurb: "Claim, evidence, load-bearing word. Then one disagreement.",
    goal: "An annotated printout or screenshot of a 400–800 word piece with margin moves, plus a 80-word reply.",
    materials: [
      "A news or explainer article you may legally copy for study",
      "Pen or tablet markup",
    ],
    steps: [
      {
        id: "s1",
        title: "Find the claim",
        body: "One sentence the writer wants you to leave with. If there are two, say which is load-bearing.",
      },
      {
        id: "s2",
        title: "Mark three moves",
        body: "Example, statistic, anecdote, expert, contrast. Write the move name in the margin, not a highlighter rainbow.",
      },
      {
        id: "s3",
        title: "Circle a loaded word",
        body: "A verb or adjective that smuggles a judgement. Swap it for a calmer cousin and see what falls out.",
      },
      {
        id: "s4",
        title: "Reply without pile-on",
        body: "Eighty words: where you agree, where the evidence is thin, and one question the piece never asked.",
      },
    ],
    checklist: [
      { id: "d1", label: "The article is identified (title, outlet, date)" },
      { id: "d2", label: "A load-bearing claim is quoted" },
      { id: "d3", label: "Three rhetorical or evidential moves are named in the margin" },
      { id: "d4", label: "An 80-word reply includes agreement, a thin spot, and a missing question" },
    ],
    pathIds: ["e-active-passive", "e-sentence-vs-fragment"],
    difficulty: "medium",
    minutes: 40,
    xp: 120,
  },
  {
    id: "art-poster-redesign",
    subject: "art",
    title: "Poster redesign with one job",
    blurb: "Same event, clearer hierarchy. Design is a decision, not a filter.",
    goal: "A before/after poster for a real event (school, gig, lost pet, sausage sizzle) with a written hierarchy.",
    materials: [
      "A messy original (photo of a noticeboard is perfect)",
      "Paper, Canva, or any tool — the decisions matter more than the brand",
    ],
    steps: [
      {
        id: "s1",
        title: "Name the job",
        body: "What must a walker understand in two seconds? Date, place, action. Write the order of those three.",
      },
      {
        id: "s2",
        title: "Audit the original",
        body: "Too many typefaces, a QR bigger than the date, clip-art fighting the title. Three faults, not twenty.",
      },
      {
        id: "s3",
        title: "Rebuild with constraint",
        body: "Two type sizes, two colours plus the paper, one image or none. Put the two-second job at the top.",
      },
      {
        id: "s4",
        title: "Stand back",
        body: "Squint or stand three metres away. If the date vanishes, fix hierarchy, not decoration. Write what you changed and why.",
      },
    ],
    checklist: [
      { id: "d1", label: "The poster’s two-second job is written as an ordered list" },
      { id: "d2", label: "Original is shown or described with three specific faults" },
      { id: "d3", label: "Rebuild uses a tight type and colour constraint" },
      { id: "d4", label: "A squint / distance check is noted with one hierarchy fix" },
    ],
    pathIds: ["a-value-squint", "a-shape-pos-neg", "a-line-weight"],
    difficulty: "medium",
    minutes: 40,
    xp: 120,
  },
  {
    id: "art-colour-study",
    subject: "art",
    title: "Limited palette still life",
    blurb: "Three colours plus the paper. Seeing is the work.",
    goal: "A small still life using only three chosen colours, with a note on the mixing you actually did.",
    materials: [
      "Paint, markers, or digital with a locked swatch",
      "Two objects and a lamp or window",
    ],
    steps: [
      {
        id: "s1",
        title: "Lock three colours",
        body: "Write the names or hex. No emergency fourth from the pencil case. Paper or background counts as a fourth only if you say so now.",
      },
      {
        id: "s2",
        title: "Squint the values first",
        body: "Where is the darkest dark? Block it. Colour later. If digital, desaturate a snapshot of your sketch and check the shapes still read.",
      },
      {
        id: "s3",
        title: "Mix on purpose",
        body: "One object should contain a mix of two of your three. Write the mix. Accidental brown still counts if you can name the parents.",
      },
      {
        id: "s4",
        title: "Stop before pretty",
        body: "Photograph the study. Write one thing the limit taught you that a full palette would have hidden.",
      },
    ],
    checklist: [
      { id: "d1", label: "Three colours are named before painting" },
      { id: "d2", label: "A value-first pass exists (squint or greyscale check)" },
      { id: "d3", label: "At least one mix of two locked colours is described" },
      { id: "d4", label: "A finished study is photographed with one written lesson" },
    ],
    pathIds: ["a-value-squint", "a-edge", "a-gesture"],
    difficulty: "easy",
    minutes: 45,
    xp: 90,
  },
  {
    id: "art-layout-grid",
    subject: "art",
    title: "Grid a magazine page",
    blurb: "Columns, margins, one cheat. Layout is a decision.",
    goal: "A traced or rebuilt grid over a real page, plus a second version that uses the same grid for new content.",
    materials: [
      "A magazine, PDF, or webpage printed or screenshotted",
      "Ruler / digital guides",
    ],
    steps: [
      {
        id: "s1",
        title: "Trace the hidden grid",
        body: "Margins, columns, a baseline if you can see it. Count the columns. Note the gutter.",
      },
      {
        id: "s2",
        title: "Find the cheat",
        body: "An image that spans two columns, a pull-quote that breaks the measure. Cheats are allowed when they are conscious.",
      },
      {
        id: "s3",
        title: "Rebuild with new words",
        body: "Same grid, your headline and two paragraphs of filler or a real notice. Keep the cheat or drop it on purpose.",
      },
      {
        id: "s4",
        title: "Name the hierarchy",
        body: "What is first, second, third in both versions. If they match, the grid is doing its job.",
      },
    ],
    checklist: [
      { id: "d1", label: "Column count, margins, and gutter are written on the trace" },
      { id: "d2", label: "One grid cheat is identified" },
      { id: "d3", label: "A second page uses the same grid with new content" },
      { id: "d4", label: "Hierarchy (1st/2nd/3rd) is named for both versions" },
    ],
    pathIds: ["a-shape-pos-neg", "a-perspective-1", "a-line-weight"],
    difficulty: "medium",
    minutes: 35,
    xp: 120,
  },
  {
    id: "music-four-bar",
    subject: "music",
    title: "Name a four-bar beat",
    blurb: "Clap it, then write what the parts are doing.",
    goal: "A four-bar groove (original or copied with credit) with pulse, metre, and two named layers.",
    materials: [
      "Hands, a table, or a DAW / voice memo",
      "Paper for counts",
    ],
    steps: [
      {
        id: "s1",
        title: "Lock the pulse",
        body: "A tempo you can keep for four bars. Count 1-2-3-4 aloud. Write bpm if you have a tap tempo, or “walking pace”.",
      },
      {
        id: "s2",
        title: "Choose a metre",
        body: "4/4 unless you have a reason. Mark the backbeat if there is one. If you clap only on 1, that is also information.",
      },
      {
        id: "s3",
        title: "Add a second layer",
        body: "Kick vs snare, bass vs hat, or two hand parts. Name them. Record or notate counts (1 & 2 &).",
      },
      {
        id: "s4",
        title: "Name one device",
        body: "Syncopation, a rest that hurts, a fill into bar 5 you did not play. Write where it sits in the four bars.",
      },
    ],
    checklist: [
      { id: "d1", label: "Tempo / pulse is written and was kept for four bars" },
      { id: "d2", label: "Metre is named and counts are written" },
      { id: "d3", label: "Two layers are named and notated or recorded" },
      { id: "d4", label: "One device (rest, syncopation, fill) is located in the bars" },
    ],
    pathIds: ["mu-beat-pulse", "mu-metre", "mu-syncopa", "mu-groove"],
    difficulty: "easy",
    minutes: 25,
    xp: 90,
  },
  {
    id: "music-listen-log",
    subject: "music",
    title: "Active listening log",
    blurb: "One track, three passes. Hear the parts, then name them.",
    goal: "A timed listening sheet: texture, a hook, and one production or performance choice.",
    materials: [
      "Headphones and one track you may play (school-legal)",
      "Timer and notes",
    ],
    steps: [
      {
        id: "s1",
        title: "Pass one: body",
        body: "No skipping. Write tempo feel (slow / walking / rushing) and metre guess. Do not hunt lyrics yet.",
      },
      {
        id: "s2",
        title: "Pass two: layers",
        body: "List instruments or sound sources as they enter. Note a drop-out. Texture words: thin, stacked, call-and-response.",
      },
      {
        id: "s3",
        title: "Pass three: the sticky bit",
        body: "Where is the hook? Time it (0:47). Is it melody, lyric, or a drum pattern? Credit the track title and artist.",
      },
      {
        id: "s4",
        title: "One choice",
        body: "A mute, a key change you felt, lo-fi noise, a shouted count-in. Why it changes how you hear the hook.",
      },
    ],
    checklist: [
      { id: "d1", label: "Track title and artist are recorded" },
      { id: "d2", label: "Three passes are dated with different jobs" },
      { id: "d3", label: "A hook is timed and named as melody, lyric, or rhythm" },
      { id: "d4", label: "One production or performance choice is tied to that hook" },
    ],
    pathIds: ["mu-phrase", "mu-tempo", "mu-rest"],
    difficulty: "medium",
    minutes: 30,
    xp: 120,
  },
  {
    id: "music-clap-pattern",
    subject: "music",
    title: "Notate a clap pattern",
    blurb: "If you can clap it, you can write the counts.",
    goal: "A one-bar or two-bar clap ostinato written in counts, taught to someone else or to a recording of you.",
    materials: [
      "Hands",
      "Paper",
      "Optional: a second person",
    ],
    steps: [
      {
        id: "s1",
        title: "Invent or steal with credit",
        body: "A pattern you can loop. If it is a known clave or a TikTok, write where it came from.",
      },
      {
        id: "s2",
        title: "Write 1 e & a",
        body: "Or 1 & 2 & if that is all you have. Mark claps vs rests. If you cannot write a rest, you do not have the pattern.",
      },
      {
        id: "s3",
        title: "Loop eight times",
        body: "Record. The drift is data. Adjust the notation to what you actually clapped, not what you meant.",
      },
      {
        id: "s4",
        title: "Hand it over",
        body: "Someone else claps from your notation only. Note the bar they tripped. Fix the notation.",
      },
    ],
    checklist: [
      { id: "d1", label: "Pattern source is credited (original or borrowed)" },
      { id: "d2", label: "Counts include rests, not only hits" },
      { id: "d3", label: "A loop recording exists" },
      { id: "d4", label: "A second person (or delayed self) clapped from the page and one notation fix was made" },
    ],
    pathIds: ["mu-beat-pulse", "mu-polyrhythm", "mu-rest"],
    difficulty: "medium",
    minutes: 25,
    xp: 120,
  },
  {
    id: "business-price-service",
    subject: "business",
    title: "Price a small service",
    blurb: "Follow the cash, not the slogan. What must you charge to not go backwards.",
    goal: "A one-page price for a real service you could offer, with costs, time, and a GST note.",
    materials: [
      "Notes or a sheet",
      "A service you could actually do (mowing, tutoring, photo set, packing)",
    ],
    steps: [
      {
        id: "s1",
        title: "Name the offer",
        body: "One job, a duration, a place. “Tutoring” is not an offer. “Year 9 maths, 60 minutes, online” is.",
      },
      {
        id: "s2",
        title: "List costs that are not vibes",
        body: "Travel, materials, software, a slice of the phone plan, tax set-aside. Unpaid time to prep counts as cost.",
      },
      {
        id: "s3",
        title: "Set a price and a floor",
        body: "Price to the customer, and the lowest you can take before you are volunteering. If GST applies at your scale, say so; if you are under the threshold, say that too — do not invent an ABN story.",
      },
      {
        id: "s4",
        title: "Compare one competitor",
        body: "A public price (Airtasker, a neighbour, a shop). Are you cheaper because you skipped a cost? Write that honestly.",
      },
    ],
    checklist: [
      { id: "d1", label: "Offer is specific (job, duration, place)" },
      { id: "d2", label: "Costs include time and at least two money costs" },
      { id: "d3", label: "Customer price and a walk-away floor are both written, with a GST note" },
      { id: "d4", label: "One public comparison price is cited" },
    ],
    pathIds: ["b-price-cost", "b-profit", "b-opp-cost"],
    difficulty: "medium",
    minutes: 35,
    xp: 120,
  },
  {
    id: "business-cash-week",
    subject: "business",
    title: "One-week cash in and out",
    blurb: "Profit is not cash. A week of movement that you can point at.",
    goal: "A seven-day cash log for a tiny real or simulated stall, with opening and closing balances.",
    materials: [
      "A table",
      "Numbers from a real week, a market stall thought-experiment, or a canteen shift",
    ],
    steps: [
      {
        id: "s1",
        title: "Opening balance",
        body: "Cash on hand or in the account you will use. Write the number first or the rest is fiction.",
      },
      {
        id: "s2",
        title: "Every in and out",
        body: "Seven days. Stock, a refund, float, a personal snack you should not have taken from the till. Label personal vs business if both appear.",
      },
      {
        id: "s3",
        title: "Closing vs profit story",
        body: "If you bought stock that is unsold, cash dropped while “profit” might still look fine later. Write one sentence that separates the two.",
      },
      {
        id: "s4",
        title: "One rule for next week",
        body: "A float, a no-personal-spend rule, or invoice timing. Tie it to a line in the log.",
      },
    ],
    checklist: [
      { id: "d1", label: "Opening balance is written before the week’s lines" },
      { id: "d2", label: "Seven days of in/out exist (quiet days marked zero, not skipped)" },
      { id: "d3", label: "Closing balance matches the arithmetic" },
      { id: "d4", label: "A sentence separates cash from profit and a next-week rule is tied to the log" },
    ],
    pathIds: ["b-cashflow", "b-budget", "b-profit"],
    difficulty: "easy",
    minutes: 30,
    xp: 90,
  },
  {
    id: "business-one-pager",
    subject: "business",
    title: "One-page offer",
    blurb: "Who it is for, what they get, what it costs, why you.",
    goal: "A single page a parent or a stranger could say yes/no to, without a slogan paragraph.",
    materials: [
      "The service from ‘Price a small service’ or a new one",
      "One page",
    ],
    steps: [
      {
        id: "s1",
        title: "Audience in one line",
        body: "Year 8 families in this suburb, or time-poor shift workers who need a Tuesday slot. If the audience is ‘everyone’, stop.",
      },
      {
        id: "s2",
        title: "The get",
        body: "Deliverable and duration. What is not included. People buy edges.",
      },
      {
        id: "s3",
        title: "Proof that is not a vibe",
        body: "A sample, a qualification, a before/after, or “I have done this six times for relatives”. No fake testimonials.",
      },
      {
        id: "s4",
        title: "The ask",
        body: "Price, how to pay, how to book, what happens if it rains. Read the page to someone; if they still ask “so what do you do?”, rewrite the get.",
      },
    ],
    checklist: [
      { id: "d1", label: "Audience is narrow enough to picture" },
      { id: "d2", label: "Deliverable, duration, and a not-included line are present" },
      { id: "d3", label: "Proof is specific and non-fictional" },
      { id: "d4", label: "Price and a booking / rain-check path are on the same page" },
    ],
    pathIds: ["b-price-cost", "b-opp-cost"],
    difficulty: "medium",
    minutes: 30,
    xp: 120,
  },
  {
    id: "health-habit-7",
    subject: "health",
    title: "Seven-day habit log",
    blurb: "One habit with a reason. Not a guilt poster.",
    goal: "Seven dated rows for one chosen habit, with a cue, a difficulty note, and a keep-or-tweak decision.",
    materials: [
      "A log (notes or paper)",
      "A habit that is safe and yours (water, stretch, lights-out, walk)",
    ],
    steps: [
      {
        id: "s1",
        title: "Pick a habit with a why",
        body: "Tied to sleep, mood, or a class you can feel. Not a punishment. Write the smallest version (two minutes counts).",
      },
      {
        id: "s2",
        title: "Attach a cue",
        body: "After I put the kettle on… After the last class… Cues beat willpower speeches.",
      },
      {
        id: "s3",
        title: "Log seven days",
        body: "Done / partial / skipped, plus a one-word energy note. Skipped days stay on the page.",
      },
      {
        id: "s4",
        title: "Decide",
        body: "Keep, shrink, or swap the cue. This is not a medical plan and not a challenge-bro streak for clout.",
      },
    ],
    checklist: [
      { id: "d1", label: "Habit, why, and smallest version are written" },
      { id: "d2", label: "A cue is named" },
      { id: "d3", label: "Seven dated rows exist, including skips" },
      { id: "d4", label: "A keep / shrink / swap decision is written from the log" },
    ],
    pathIds: ["w-sleep", "w-hydration", "w-circadian"],
    difficulty: "easy",
    minutes: 15,
    xp: 90,
  },
  {
    id: "health-first-aid-kit",
    subject: "health",
    title: "First-aid kit audit",
    blurb: "What is in the box, what is expired, what is missing for this house.",
    goal: "An inventory of a real kit (home, car, or sport bag) with expiry notes and one restock list.",
    materials: [
      "A real kit you are allowed to open",
      "Phone torch",
      "Notes — this is not a first-aid certificate",
    ],
    steps: [
      {
        id: "s1",
        title: "Empty it onto a table",
        body: "Photograph the spread. List items. Do not practise invasive care from a YouTube video.",
      },
      {
        id: "s2",
        title: "Find dates and damage",
        body: "Expired gel, a sterile pack that is open, sunscreen that lived in a hot car. Write what you would bin (with a parent if it is not your kit).",
      },
      {
        id: "s3",
        title: "Match the place",
        body: "A beach bag wants different extras than a kitchen drawer. Note allergies in the house if they change what you stock (and whose job that is).",
      },
      {
        id: "s4",
        title: "Restock list",
        body: "Three items to add or replace, plus where the kit lives so it can be found in a hurry. Emergency numbers are a fridge job, not a flex.",
      },
    ],
    checklist: [
      { id: "d1", label: "A photo or complete item list of a real kit exists" },
      { id: "d2", label: "Expiry or damage is noted on at least the time-sensitive items" },
      { id: "d3", label: "The kit is judged against the place it lives" },
      { id: "d4", label: "A three-item restock list and a findable location are written" },
    ],
    pathIds: ["w-skin-sun", "w-heart-rate"],
    difficulty: "easy",
    minutes: 25,
    xp: 90,
  },
  {
    id: "health-sleep-log",
    subject: "health",
    title: "Sleep and energy log",
    blurb: "Clock times, not moral grades. Five nights is enough to see a pattern.",
    goal: "Five nights of lights-out, wake, and a noon energy score, plus one change that is not ‘try harder’.",
    materials: [
      "A log",
      "The clock you actually use",
    ],
    steps: [
      {
        id: "s1",
        title: "Write the window you wanted",
        body: "Target lights-out and wake, as a plan, before night one. This is observation, not a diagnosis.",
      },
      {
        id: "s2",
        title: "Record five nights",
        body: "Lights-out, wake, whether a screen was in the last 30 minutes, a 1–5 energy score at noon. No guilt column.",
      },
      {
        id: "s3",
        title: "Find a pattern, not a villain",
        body: "Late caffeine, weekend drift, a hot room. One pattern the table actually shows.",
      },
      {
        id: "s4",
        title: "One environmental change",
        body: "Charge the phone out of reach, a cooler room, a fixed wake on one weekday. Not a supplement stack. If sleep is a health worry, that is a GP conversation — this log is a study tool.",
      },
    ],
    checklist: [
      { id: "d1", label: "A planned sleep window is written before the log" },
      { id: "d2", label: "Five nights include lights-out, wake, and a noon energy score" },
      { id: "d3", label: "One pattern is quoted from the table" },
      { id: "d4", label: "One environmental change is chosen (not a medical plan)" },
    ],
    pathIds: ["w-sleep", "w-circadian"],
    difficulty: "medium",
    minutes: 15,
    xp: 120,
  },
  {
    id: "digital-privacy-audit",
    subject: "digital",
    title: "Privacy audit of one account",
    blurb: "Open the settings. Write what is actually shared. Then tighten one thing.",
    goal: "A settings inventory for one real account (email, social, or school) with three findings and one change you made.",
    materials: [
      "One account you own",
      "Notes — do not share passwords in the log",
    ],
    steps: [
      {
        id: "s1",
        title: "Pick the account and stay there",
        body: "Do not wander into a friend’s phone. Write the service name and whether this is a personal or school login.",
      },
      {
        id: "s2",
        title: "Inventory three surfaces",
        body: "Profile visibility, connected apps / sessions, and 2FA or recovery. Screenshot for yourself if you want; do not paste secrets into TicketBench.",
      },
      {
        id: "s3",
        title: "Name the audience",
        body: "Who can see a post, a story, a number? “Friends of friends” is an audience. Write it in English.",
      },
      {
        id: "s4",
        title: "Change one setting",
        body: "Kill an old session, drop a forgotten app, turn on 2FA, or lock a phone number. Write before and after. This is not a CompTIA lab and not legal advice.",
      },
    ],
    checklist: [
      { id: "d1", label: "One owned account is named (no passwords in the notes)" },
      { id: "d2", label: "Visibility, sessions/apps, and recovery/2FA are each noted" },
      { id: "d3", label: "The real audience of a post or profile is written in English" },
      { id: "d4", label: "One setting was changed and before/after is recorded" },
    ],
    pathIds: ["d-password", "d-mfa", "d-lock-device"],
    difficulty: "medium",
    minutes: 30,
    xp: 120,
  },
  {
    id: "digital-scam-playbook",
    subject: "digital",
    title: "Scam message playbook",
    blurb: "One real or realistic message. Mark the pressure, the ask, the check.",
    goal: "An annotated scam (SMS, email, or call script) with pressure tactics labelled and a verification step that does not use the message’s own link.",
    materials: [
      "A message you received, a public scam example, or a constructed one labelled as such",
      "Notes",
    ],
    steps: [
      {
        id: "s1",
        title: "Paste or transcribe",
        body: "Redact your name and any one-time codes. If you invent the example, write INVENTED at the top so you do not train on fiction as a memory.",
      },
      {
        id: "s2",
        title: "Label the moves",
        body: "Urgency, authority, fear, a too-good refund, a shortened link, a slightly-wrong domain. At least three labels.",
      },
      {
        id: "s3",
        title: "Write the check that ignores the bait",
        body: "Type the bank URL yourself, call the number on the card, ask a human beside you. Not “the link looks okay”.",
      },
      {
        id: "s4",
        title: "What you would tell a relative",
        body: "Five lines, no scorn. People fall for these because they were busy, not stupid.",
      },
    ],
    checklist: [
      { id: "d1", label: "Message is recorded and personal codes are redacted" },
      { id: "d2", label: "At least three pressure or spoofing moves are labelled" },
      { id: "d3", label: "A verification step that avoids the message’s own link/number is written" },
      { id: "d4", label: "A five-line relative-safe explanation exists" },
    ],
    pathIds: ["d-phish", "d-scam-call", "d-ransomware"],
    difficulty: "easy",
    minutes: 25,
    xp: 90,
  },
  {
    id: "digital-share-before",
    subject: "digital",
    title: "Before-you-post checklist",
    blurb: "The internet is a place with consequences. Run a post through a gate.",
    goal: "A reusable seven-point gate applied to one real draft post (you do not have to publish).",
    materials: [
      "A draft caption, story, or comment you almost sent",
      "This checklist, copied into your notes",
    ],
    steps: [
      {
        id: "s1",
        title: "Park the draft",
        body: "Paste it into notes. Do not post during this project. Write the platform and the audience (class story vs public).",
      },
      {
        id: "s2",
        title: "Run seven questions",
        body: "(1) Who is in the photo and did they agree? (2) Does it locate a home or a school in the background? (3) Could it be searched in five years? (4) Is a joke punching down? (5) Any secret that is not yours? (6) Would you say it to their face? (7) What does the platform keep even after delete?",
      },
      {
        id: "s3",
        title: "Edit or kill",
        body: "Change the draft or write KILL with a reason. Either is a pass.",
      },
      {
        id: "s4",
        title: "Save the gate",
        body: "Keep the seven questions somewhere you will see them. TicketBench will not nag you later — the file is yours.",
      },
    ],
    checklist: [
      { id: "d1", label: "A real draft is parked with platform and audience" },
      { id: "d2", label: "All seven questions have a written answer" },
      { id: "d3", label: "The draft is edited or killed with a reason" },
      { id: "d4", label: "The seven questions are saved outside this page" },
    ],
    pathIds: ["d-public-wifi", "d-password"],
    difficulty: "easy",
    minutes: 20,
    xp: 90,
  },
];
