import type { Project } from "../types";
import { diagramFigure } from "../figures";

export const stemProjects: Project[] = [
  {
    id: "tech-cable-map",
    subject: "tech",
    title: "Cable and port map",
    blurb: "Draw every lead on one real desk so the next swap is not a guess.",
    goal: "A labelled diagram of one workstation: each cable, the ports it uses, and what happens if you pull it.",
    materials: [
      "Paper or a notes app",
      "One real computer and its peripherals",
      "Optional: phone camera for the rear I/O",
    ],
    steps: [
      {
        id: "s1",
        title: "Pick one machine",
        body: "Use a real desk — yours, a family PC, or a lab box. Do not invent a fantasy tower. Photograph the rear I/O if you cannot sit behind it for long.",
      },
      {
        id: "s2",
        title: "Name every cable",
        body: "Trace each lead from device to port. Write the connector (HDMI, DisplayPort, USB-A, USB-C, Ethernet, DC barrel) and a colour or length if twins look the same.",
        figure: diagramFigure(
          "usb-c-roles",
          "USB-C as three different jobs: charge only, DisplayPort Alt Mode, and Thunderbolt.",
          "If two USB-C holes look identical, still write which one drove the monitor.",
        ),
      },
      {
        id: "s3",
        title: "Mark power versus data",
        body: "Circle anything that carries mains or a brick. Star anything that is data-only. Note USB-C ports that do both. This is the map you want when a screen is black and you are about to unplug the wrong brick.",
      },
      {
        id: "s4",
        title: "Write a do-not-pull list",
        body: "Three cables that would drop network, display, or power if yanked. That list is the deliverable, not a pretty sketch.",
      },
    ],
    checklist: [
      { id: "d1", label: "Every visible cable is named with a connector type" },
      { id: "d2", label: "Power bricks and data leads are distinguished" },
      { id: "d3", label: "At least one USB-C or video port is labelled with what it actually drives" },
      { id: "d4", label: "A three-line do-not-pull list sits on the same page as the diagram" },
    ],
    pathIds: ["hardware", "networking"],
    difficulty: "easy",
    minutes: 30,
    xp: 90,
    figure: diagramFigure(
      "rear-io",
      "Example rear I/O with HDMI, DisplayPort, USB-A, USB-C, RJ45 and DC labelled as power or data.",
      "Your desk will differ. Copy the habit: name the connector and whether it carries power, data, or both.",
    ),
  },
  {
    id: "tech-wifi-map",
    subject: "tech",
    title: "Home Wi-Fi coverage map",
    blurb: "Walk the rooms. Measure the signal. Stop guessing why the hallway drops.",
    goal: "A floor sketch with signal notes in at least four spots, plus one change you would actually try.",
    materials: [
      "Phone with Wi-Fi settings or a free analyser",
      "Rough floor sketch (boxes are fine)",
      "The household router, left where it already sits",
    ],
    steps: [
      {
        id: "s1",
        title: "Sketch the floor",
        body: "Boxes for rooms, a mark for the router, and doors. You are not submitting architecture. Label the SSID you are testing so you do not mix guest and main.",
      },
      {
        id: "s2",
        title: "Stand still and read",
        body: "In four places — next to the router, the usual desk, the worst room, and one outdoor or hallway spot — write bars or dBm if the phone shows it. Note 2.4 vs 5 GHz if you can see both.",
      },
      {
        id: "s3",
        title: "Name the obstacle",
        body: "Brick, fridge, fish tank, foil-backed insulation, a neighbour’s AP on the same channel. One sentence: what is eating the signal, not “Wi-Fi is bad”.",
      },
      {
        id: "s4",
        title: "Propose one change",
        body: "Move the AP, kill a duplicate SSID, change channel, or add a wired backhaul later. Write why that change matches the map. Do not buy a mesh because a YouTube thumbnail said so.",
      },
    ],
    checklist: [
      { id: "d1", label: "Floor sketch includes the router and four labelled test spots" },
      { id: "d2", label: "Each spot has a signal note (bars or dBm) written at the time" },
      { id: "d3", label: "One physical obstacle is named in plain English" },
      { id: "d4", label: "One change is proposed with a reason tied to the map" },
    ],
    pathIds: ["networking", "hw-net-troubleshooting"],
    difficulty: "medium",
    minutes: 40,
    xp: 120,
    figure: diagramFigure(
      "wifi-rooms",
      "Four rooms in a line from the router to a far room, with bar glyphs for signal strength.",
      "Walk it. Bars (|||| vs |) beat a colour blob. Tie one change to the weakest room.",
    ),
  },
  {
    id: "tech-helpdesk-reply",
    subject: "tech",
    title: "Helpdesk reply case",
    blurb: "Write the reply you would actually send — not a dump of theory. Lab tickets wait after this.",
    goal: "A short ticket reply that restates the problem, lists what you tried, and asks for one missing fact.",
    materials: [
      "Notes app",
      "Optional: open Lab afterwards for a generated ticket",
      "The scenario below — do not invent a different outage",
    ],
    steps: [
      {
        id: "s1",
        title: "Read the user once",
        body: "User: “My docking station in Parramatta stopped driving two monitors after I moved desks. Laptop still works on its own screen. HDMI dongle from the drawer also fails. I already rebooted.” Circle facts versus guesses. The move is a fact. “The dock is dead” is a guess.",
      },
      {
        id: "s2",
        title: "Pick a first test that is cheap",
        body: "Known-good cable, different USB-C port, one monitor only, or a Windows display detect. Write why that test splits “cable / port / dock / OS” faster than reinstalling a driver pack.",
      },
      {
        id: "s3",
        title: "Draft the reply",
        body: "Four short paragraphs: (1) restated problem in your words, (2) what you already believe from their message, (3) the one test you want them to run, (4) what to send back (photo of rear I/O, exact dock model). No jargon trophy.",
      },
      {
        id: "s4",
        title: "Cut the lecture",
        body: "Delete anything that does not help this user today. If you want a generated A+ ticket after this, open Lab — this project is the writing habit, not the simulator.",
      },
    ],
    checklist: [
      { id: "d1", label: "Reply restates the docking / dual-monitor symptom without adding new fiction" },
      { id: "d2", label: "One cheap test is named with what outcome would split the cause" },
      { id: "d3", label: "The user is asked for one concrete missing fact (model, photo, or error)" },
      { id: "d4", label: "The draft is short enough to send — no driver-DVD sermon" },
    ],
    pathIds: ["operational-procedures", "hw-net-troubleshooting", "hardware"],
    difficulty: "medium",
    minutes: 25,
    xp: 120,
  },
  {
    id: "maths-weekly-budget",
    subject: "maths",
    title: "Weekly budget that balances",
    blurb: "Seven days of real money, GST-aware where it matters, no magic leftover.",
    goal: "A one-week income and spend table that adds up, with one decision you would change next week.",
    materials: [
      "Notes or a spreadsheet",
      "A week of actual or realistic receipts (bus, food, phone)",
      "Calculator — you still write the sums",
    ],
    steps: [
      {
        id: "s1",
        title: "List money in",
        body: "Pay, allowance, or a made-up but realistic casual shift. Write the amount before and after tax if you know it. Do not start with leftover hope.",
      },
      {
        id: "s2",
        title: "List money out",
        body: "At least eight lines: food, transport, data, a want, a bill slice. If a price is GST-inclusive, note that you are not adding 10% again. Australian receipts already include it unless they say otherwise.",
      },
      {
        id: "s3",
        title: "Make the difference honest",
        body: "Income minus spend. If it is negative, do not hide it in rounding. If it is positive, name where that cash actually sits (account, jar, unspent).",
      },
      {
        id: "s4",
        title: "Change one line",
        body: "Cut or swap one spend so next week is $10 kinder without pretending rent vanished. Write the percentage that line was of the week.",
      },
    ],
    checklist: [
      { id: "d1", label: "Income and at least eight spend lines are written with dollars and cents" },
      { id: "d2", label: "The weekly difference is calculated and matches the table" },
      { id: "d3", label: "GST is not double-counted on inclusive prices" },
      { id: "d4", label: "One next-week change is named with that line as a percentage of spend" },
    ],
    pathIds: ["percentages", "number-sense"],
    difficulty: "easy",
    minutes: 35,
    xp: 90,
    figure: diagramFigure(
      "cash-flow",
      "Two boxes: solid money in and dashed money out, reminding that GST is already in Australian receipts.",
      "The weekly difference is arithmetic, not hope. Inclusive prices already contain GST.",
    ),
  },
  {
    id: "maths-room-scale",
    subject: "maths",
    title: "Room to scale",
    blurb: "Measure a real room. Draw it so one centimetre means something.",
    goal: "A scale plan of one room with furniture that would actually fit, plus the scale written as a ratio.",
    materials: [
      "Tape measure or a phone measure app you then check with a ruler",
      "Graph paper or a squared notes page",
      "Pencil",
    ],
    steps: [
      {
        id: "s1",
        title: "Measure the empty rectangle",
        body: "Length and width of one room to the nearest centimetre. Ignore the skirting poetry. Note the door swing as a quarter-circle so you do not park a desk in it.",
      },
      {
        id: "s2",
        title: "Choose a scale you can draw",
        body: "1 cm : 20 cm or 1:50 — write it. Convert both walls. If the page is too small, pick a smaller scale on purpose, not by squashing.",
      },
      {
        id: "s3",
        title: "Place two pieces of furniture",
        body: "Bed, desk, or table — measure the real objects, convert, draw. If they overlap the door swing, that is a finding, not a failure.",
      },
      {
        id: "s4",
        title: "Check one distance two ways",
        body: "Pick a diagonal or a gap. Calculate it from the plan, then measure it in the room. Write both numbers. A 5% miss is worth a sentence; a factor-of-ten miss means the scale lied.",
      },
    ],
    checklist: [
      { id: "d1", label: "Room length and width are recorded in centimetres" },
      { id: "d2", label: "Scale is written as a ratio and both walls are converted" },
      { id: "d3", label: "Two furniture pieces are drawn from real measurements" },
      { id: "d4", label: "One plan distance is checked against a real-world measure" },
    ],
    pathIds: ["geometry-measure", "m-convert-metric"],
    difficulty: "medium",
    minutes: 40,
    xp: 120,
    figure: diagramFigure(
      "room-scale",
      "Plan of a room at 1 cm to 20 cm with a desk rectangle and a dashed door swing.",
      "Write the ratio. Dashed line is the door swing — furniture that hits it does not fit.",
    ),
  },
  {
    id: "maths-survey-chart",
    subject: "maths",
    title: "Tiny survey chart",
    blurb: "Ask a real question, tally honest answers, draw a chart that does not lie.",
    goal: "A question, at least ten responses, a table, and a bar or pie that matches the table.",
    materials: [
      "Ten people you can actually ask (class, family, group chat)",
      "Paper or a sheet",
      "Ruler for bars",
    ],
    steps: [
      {
        id: "s1",
        title: "Ask one closed question",
        body: "Three or four options, not “how do you feel about lunch”. Example: walk / bus / car / other to school or work. Write who you asked so the sample is not “the internet”.",
      },
      {
        id: "s2",
        title: "Tally without editing",
        body: "If someone refuses, that is not a vote for your favourite. Ten answers minimum. Convert tallies to counts and to percentages that add to 100% (or say why rounding stole 1%).",
      },
      {
        id: "s3",
        title: "Draw bars that share a scale",
        body: "Same baseline, same unit. Label axes. A 3D pie is banned. If you use a pie, the slices must match the percentages you just wrote.",
      },
      {
        id: "s4",
        title: "Write the sentence the chart earns",
        body: "One claim the data supports, and one it does not. “Most people in this sample catch the bus” is allowed. “Sydney prefers buses” is not.",
      },
    ],
    checklist: [
      { id: "d1", label: "Question and sample (who was asked) are written down" },
      { id: "d2", label: "At least ten responses are tallied into counts and percentages" },
      { id: "d3", label: "A bar or pie matches the table and uses a shared scale" },
      { id: "d4", label: "One supported claim and one overclaim are both written" },
    ],
    pathIds: ["number-sense", "percentages"],
    difficulty: "easy",
    minutes: 35,
    xp: 90,
  },
  {
    id: "science-kitchen-experiment",
    subject: "science",
    title: "Kitchen experiment with a control",
    blurb: "Change one thing. Keep the rest still. Write what actually happened.",
    goal: "A fair test using kitchen materials, a control, and a result that could have gone the other way.",
    materials: [
      "Bicarb and vinegar, or salt/sugar and water, or two tea bags",
      "Two identical cups or jars",
      "Timer and notes",
    ],
    steps: [
      {
        id: "s1",
        title: "State the question",
        body: "One independent variable. Example: does warmer water dissolve a teaspoon of sugar faster than cold? Write the prediction before you pour.",
      },
      {
        id: "s2",
        title: "Lock the rest",
        body: "Same cup size, same amount of water, same stir count. The second cup is the control. If you change two things, you will not know which one mattered.",
      },
      {
        id: "s3",
        title: "Measure something countable",
        body: "Seconds to clear, height of foam, or whether a bag sinks. Do the run twice if you can. Write the numbers — “it fizzed more” is not a result.",
      },
      {
        id: "s4",
        title: "Explain without magic",
        body: "Particles, temperature, or acid–carbonate. Then one limit: kitchen scales, leftover syrup in the cup, or a lid you forgot. Safety: no oven experiments, no tasting chemicals that are not food.",
      },
    ],
    checklist: [
      { id: "d1", label: "Question, prediction, and single independent variable are written first" },
      { id: "d2", label: "A control cup or run is described with what was kept the same" },
      { id: "d3", label: "A numeric or clearly comparable result is recorded" },
      { id: "d4", label: "An explanation plus one honest limit is written; the method was kitchen-safe" },
    ],
    pathIds: ["atoms-matter", "s-physical-vs-chem", "energy-systems"],
    difficulty: "medium",
    minutes: 35,
    xp: 120,
  },
  {
    id: "science-weather-log",
    subject: "science",
    title: "Seven-day weather log",
    blurb: "Look outside. Then check a forecast. See where they disagree.",
    goal: "A week of local observations beside a published forecast, with one pattern named.",
    materials: [
      "Notebook or a table in notes",
      "A window or a balcony you can use at a set time",
      "A public forecast (BOM or similar) — not a vibe",
    ],
    steps: [
      {
        id: "s1",
        title: "Fix the time and place",
        body: "Same hour each day if you can, same suburb. Write estimated cloud (oktas or just clear / patchy / full), wind feel, and whether the ground is wet.",
      },
      {
        id: "s2",
        title: "Copy the forecast before you look outside",
        body: "Morning: write today’s forecast max and a rain word. Then observe. Cheating the order trains you to confirm, not to test.",
      },
      {
        id: "s3",
        title: "Hold for seven rows",
        body: "Seven days, even if two are boring. Boring is data. If you miss a day, mark it missed — do not invent sunshine.",
      },
      {
        id: "s4",
        title: "Name a miss",
        body: "Where did the forecast and the window disagree? Sea breeze, a storm that missed you, or a max that felt hotter in a brick schoolyard. One physical reason, not “BOM is useless”.",
      },
    ],
    checklist: [
      { id: "d1", label: "Place and roughly the same daily time are recorded" },
      { id: "d2", label: "Seven rows exist (missed days marked, not faked)" },
      { id: "d3", label: "Each day has a forecast note and an observation" },
      { id: "d4", label: "One forecast miss is explained with a local physical reason" },
    ],
    pathIds: ["energy-systems", "s-endothermic"],
    difficulty: "easy",
    minutes: 20,
    xp: 90,
  },
  {
    id: "science-food-chain",
    subject: "science",
    title: "Local food web, not a poster lion",
    blurb: "Name producers and eaters from a place you can actually visit or remember.",
    goal: "A food web of at least eight species from one Australian place, with one human pressure marked.",
    materials: [
      "Paper",
      "A park, backyard, creek, coast, or a honest memory of one",
      "Optional: iNaturalist or a field guide after you draft from memory",
    ],
    steps: [
      {
        id: "s1",
        title: "Pick the place",
        body: "A named suburb park, a beach, a paddock, or the school oval. Not “the African savanna”. Write what you have actually seen there — magpies, paperbarks, skinks, ibis.",
      },
      {
        id: "s2",
        title: "Start from the sun",
        body: "Two producers, then herbivores or detritivores, then at least one predator. Arrows mean “is eaten by” in one consistent direction. Say which direction you chose.",
      },
      {
        id: "s3",
        title: "Add a decomposer",
        body: "Fungi, bacteria, or a detritivore. Energy does not vanish when the ibis leaves. If you cannot name a species, name the role and why it belongs.",
      },
      {
        id: "s4",
        title: "Mark a human cut",
        body: "Cats, mowing, runoff, bread feeding. Circle one species that would wobble if that pressure rose. One sentence, not a TED talk.",
      },
    ],
    checklist: [
      { id: "d1", label: "The place is named and at least eight living things are local to it" },
      { id: "d2", label: "Arrows have one consistent meaning and include producers" },
      { id: "d3", label: "A decomposer or detritivore is included" },
      { id: "d4", label: "One human pressure is linked to a species that would feel it" },
    ],
    pathIds: ["ecosystems-au", "cells-life"],
    difficulty: "medium",
    minutes: 35,
    xp: 120,
    figure: diagramFigure(
      "food-web",
      "Sun to paperbark and grasses, then possum and insect, then magpie.",
      "Use species you have actually seen. This drawing is a template, not a Victorian forest poster.",
    ),
  },
  {
    id: "coding-study-timer",
    subject: "coding",
    title: "Study timer page",
    blurb: "A tiny page that counts down. One job. You can see every line.",
    goal: "A local HTML/JS (or Python) timer that starts, pauses, and announces done — no framework required.",
    materials: [
      "A text editor and a browser, or a REPL you already use",
      "This project’s spec, not a copied pomodoro app",
    ],
    steps: [
      {
        id: "s1",
        title: "Write the recipe first",
        body: "Inputs: minutes. States: idle, running, paused, done. Outputs: remaining time and a visible done state. If you cannot say this in four lines, you are not ready to paste.",
      },
      {
        id: "s2",
        title: "Make time move",
        body: "setInterval or a loop with sleep. Subtract one second, render mm:ss. Pause must actually stop the ticking, not just hide it.",
      },
      {
        id: "s3",
        title: "Guard the edges",
        body: "Zero minutes, a non-number, and double-click start. Done should not keep going negative. Write a comment above each guard.",
      },
      {
        id: "s4",
        title: "Show someone the file",
        body: "Three lines of what you would change next (sound, 25/5 presets, save last duration). Do not add them yet unless they are already done.",
      },
    ],
    checklist: [
      { id: "d1", label: "A short state recipe exists before or beside the code" },
      { id: "d2", label: "Timer starts, pauses, and reaches a clear done state" },
      { id: "d3", label: "Invalid or zero input cannot send the display negative" },
      { id: "d4", label: "You can point to the lines that tick and the lines that stop" },
    ],
    pathIds: ["c-program-recipe", "c-trace", "c-edge-case"],
    difficulty: "medium",
    minutes: 45,
    xp: 120,
    figure: diagramFigure(
      "timer-wire",
      "Wireframe of a timer page showing 12:00, a solid Start button and a dashed Pause button.",
      "Draw states first. CSS can wait. Pause must stop the tick, not hide it.",
    ),
  },
  {
    id: "coding-quiz-shuffle",
    subject: "coding",
    title: "Quiz shuffle script",
    blurb: "Shuffle questions without lying about randomness or mutating by accident.",
    goal: "A function that takes a list of questions and returns a new shuffled list; original order still intact.",
    materials: [
      "Editor or REPL",
      "A list of at least six question strings (TicketBench quiz lines are fine)",
    ],
    steps: [
      {
        id: "s1",
        title: "Store the items",
        body: "An array of six prompts. Print it. That print is your before-photo.",
      },
      {
        id: "s2",
        title: "Shuffle a copy",
        body: "Fisher–Yates or a language shuffle on a copied array. If you sort by Math.random(), write why that is biased and then use a fairer loop anyway.",
      },
      {
        id: "s3",
        title: "Prove the original survived",
        body: "Print the source list after shuffle. If it moved, you mutated. Fix it. Then shuffle twice and show the two results can differ.",
      },
      {
        id: "s4",
        title: "Deal a paper",
        body: "Take the first five of the shuffled copy as “today’s quiz”. Write how you would avoid repeating last session (seed, leftover pile) — you do not have to build it.",
      },
    ],
    checklist: [
      { id: "d1", label: "A source list of at least six questions is printed before shuffling" },
      { id: "d2", label: "Shuffle runs on a copy (original order unchanged afterwards)" },
      { id: "d3", label: "Two shuffle runs can produce different orders" },
      { id: "d4", label: "A five-question ‘today’ slice is taken from the shuffled copy" },
    ],
    pathIds: ["c-algo-vs-code", "c-debug-hypothesis", "c-pattern"],
    difficulty: "easy",
    minutes: 30,
    xp: 90,
  },
  {
    id: "coding-bug-trio",
    subject: "coding",
    title: "Bug-fix trio",
    blurb: "Three small lies in a snippet. Hypothesise, then prove each fix.",
    goal: "A before/after for three bugs: off-by-one, bad comparison, and a name that shadows.",
    materials: [
      "Editor",
      "The snippet in the first step — type it, do not only stare",
    ],
    steps: [
      {
        id: "s1",
        title: "Type the broken program",
        body: "A list of scores [4, 7, 2]. A loop that is supposed to print how many are above 3, using i <= scores.length, comparing with = instead of a proper greater-than, and a total variable named the same as the list. If your language disagrees, keep the three bug kinds.",
      },
      {
        id: "s2",
        title: "Hypothesise before you run",
        body: "Write what each bug will do: crash, infinite, wrong count, or silent overwrite. Then run. Match or update the hypothesis — do not delete it.",
      },
      {
        id: "s3",
        title: "Fix one at a time",
        body: "Off-by-one first, then comparison, then naming. After each fix, run again. A bundle-fix that “just works” teaches nothing.",
      },
      {
        id: "s4",
        title: "Leave a comment for the next human",
        body: "One comment per fix: what was wrong in English. That comment is part of the deliverable.",
      },
    ],
    checklist: [
      { id: "d1", label: "The broken snippet was typed and run (or traced) before fixing" },
      { id: "d2", label: "A written hypothesis exists for each of the three bug kinds" },
      { id: "d3", label: "Fixes were applied one at a time with a run in between" },
      { id: "d4", label: "Each fix has a one-line English comment" },
    ],
    pathIds: ["c-debug-hypothesis", "c-edge-case", "c-trace"],
    difficulty: "medium",
    minutes: 35,
    xp: 120,
  },
  {
    id: "logic-viral-claim",
    subject: "logic",
    title: "Viral claim fact-check",
    blurb: "Take one claim that travelled. Separate what was said from what was shown.",
    goal: "A claim card: exact wording, source, what would count as evidence, and a verdict with a doubt remaining.",
    materials: [
      "One post, headline, or chain message (screenshot is fine)",
      "Two sources you did not write",
      "Notes",
    ],
    steps: [
      {
        id: "s1",
        title: "Quote the claim",
        body: "Exact words, who said them, and where you saw them. If it is a screenshot with no date, write that the date is missing. Do not steelman yet.",
      },
      {
        id: "s2",
        title: "Name the test",
        body: "What observation would make this true, and what would make it false? If nothing could falsify it, you are holding a slogan, not a claim.",
      },
      {
        id: "s3",
        title: "Check two places that disagree or drill down",
        body: "A primary page, a stats body, or a reputable explainer. Write what each actually says — not what you hoped. Note funding or axe if it is obvious.",
      },
      {
        id: "s4",
        title: "Verdict with leftover doubt",
        body: "Supported / unsupported / mixed, in one sentence, plus the fact you still do not have. Sharing a correction is optional; the card is the work.",
      },
    ],
    checklist: [
      { id: "d1", label: "Exact claim wording and source location are recorded" },
      { id: "d2", label: "A falsifying test is written in plain English" },
      { id: "d3", label: "Two external sources are quoted or paraphrased with links or titles" },
      { id: "d4", label: "Verdict is labelled and one remaining doubt is named" },
    ],
    pathIds: ["o-claim-prem", "o-causal", "o-generalise"],
    difficulty: "medium",
    minutes: 40,
    xp: 120,
    figure: diagramFigure(
      "claim-test",
      "Three boxes: quote the claim, name a falsifying test, check two sources and leftover doubt.",
      "If nothing could prove it false, you are holding a slogan. Write the test before you google.",
    ),
  },
  {
    id: "logic-bias-experiment",
    subject: "logic",
    title: "Tiny bias experiment",
    blurb: "Catch a slide in yourself: same facts, two frames.",
    goal: "A mini experiment that shows framing or confirmation on a harmless question, with your own answers included.",
    materials: [
      "Two friends or classmates (or two passes on yourself a day apart)",
      "Paper",
    ],
    steps: [
      {
        id: "s1",
        title: "Pick a harmless question",
        body: "Not medical advice, not a fight at home. Example: is a $4 coffee ‘expensive’? Or which queue looks faster in a photo. Write the factual core that should not change.",
      },
      {
        id: "s2",
        title: "Write two frames",
        body: "Frame A emphasises loss or risk. Frame B emphasises gain or ease. Same numbers. You are testing the frame, not the coffee.",
      },
      {
        id: "s3",
        title: "Ask without coaching",
        body: "One person (or you) sees A first; the other sees B. Record the answers. If you leaked the point of the experiment, mark the trial as contaminated.",
      },
      {
        id: "s4",
        title: "Interpret small",
        body: "n is tiny. You may only claim “in this trial, the frame moved the answer” or “it did not”. Name the bias you were hunting (framing, confirmation, anchoring).",
      },
    ],
    checklist: [
      { id: "d1", label: "The factual core and two frames are written down" },
      { id: "d2", label: "At least two responses are recorded (or two self-passes)" },
      { id: "d3", label: "Contamination is noted if anyone was coached" },
      { id: "d4", label: "The write-up names the bias and refuses to over-generalise n" },
    ],
    pathIds: ["o-hidden-p", "o-ded-ind", "o-valid-sound"],
    difficulty: "medium",
    minutes: 30,
    xp: 120,
  },
  {
    id: "logic-rewrite-argument",
    subject: "logic",
    title: "Rewrite a weak argument",
    blurb: "Find the hidden premise. Then write a version that could actually survive a question.",
    goal: "A before/after: original argument, labelled parts, and a rebuilt version with one named limit.",
    materials: [
      "A comment, letter to the editor, or a paragraph you wrote last month",
      "Notes",
    ],
    steps: [
      {
        id: "s1",
        title: "Paste the weak version",
        body: "Keep it short. Example: “We should ban phones at lunch because students are addicted and Finland did it.” Number the sentences.",
      },
      {
        id: "s2",
        title: "Label claim and premises",
        body: "Circle the claim. List premises. Write the hidden one (addiction is the same as use; Finland is comparable; bans do only what we hope). Name a fallacy if it is really there — do not collect fallacy stickers.",
      },
      {
        id: "s3",
        title: "Rebuild",
        body: "Same topic, fewer leaps. Each premise something a sceptic could check. If you need a statistic you do not have, write TODO instead of inventing 87%.",
      },
      {
        id: "s4",
        title: "Add a limit",
        body: "Who this does not apply to, or what evidence would make you drop the claim. A strong argument without a limit is still performing.",
      },
    ],
    checklist: [
      { id: "d1", label: "Original text is quoted and numbered" },
      { id: "d2", label: "Claim, premises, and at least one hidden premise are labelled" },
      { id: "d3", label: "Rebuilt argument has checkable premises and no invented stats" },
      { id: "d4", label: "A limit or defeating observation is included" },
    ],
    pathIds: ["o-claim-prem", "o-hidden-p", "o-analogy"],
    difficulty: "hard",
    minutes: 40,
    xp: 150,
  },
];
