import type { Project } from "../types";
import { diagramFigure } from "../figures";

export const worldProjects: Project[] = [
  {
    id: "history-local-sources",
    subject: "history",
    title: "Local place, three sources",
    blurb: "A park, a plaque, a street name. Who said what, and when.",
    goal: "A source table for one named place near you: three materials of different kinds, plus what they cannot prove.",
    materials: [
      "A place you can visit or recall with a name (park, station, memorial, suburb)",
      "Phone camera or notes",
      "One library / Trove / council / plaque text",
    ],
    steps: [
      {
        id: "s1",
        title: "Name the place",
        body: "Official name and the name people actually use. Write Country if you know it — do not invent a nation to look serious. One sentence on why this place, not a capital-H History topic from a textbook cover.",
      },
      {
        id: "s2",
        title: "Collect three kinds",
        body: "Example mix: a plaque, a map or photo from another decade, a newspaper or oral note. Label each primary or secondary and the year if you have one. A Wikipedia dump is not three sources.",
      },
      {
        id: "s3",
        title: "Ask what each wants",
        body: "A council plaque is not neutral. A real-estate ad is not a census. Write the purpose of each source in one line.",
      },
      {
        id: "s4",
        title: "Write the gap",
        body: "What would you still need to say who was here before the plaque? Name that missing source type. That gap is the point of the project.",
      },
    ],
    checklist: [
      { id: "d1", label: "The place is named (official and everyday if they differ)" },
      { id: "d2", label: "Three sources of different kinds are listed with dates where known" },
      { id: "d3", label: "Each source has a one-line purpose / bias note" },
      { id: "d4", label: "A missing source type is named — what you still cannot prove" },
    ],
    pathIds: ["historical-thinking", "h-primary-secondary", "h-corroborate"],
    difficulty: "medium",
    minutes: 45,
    xp: 120,
  },
  {
    id: "history-then-now",
    subject: "history",
    title: "Then-and-now street",
    blurb: "One street, two times. What changed is a claim that needs a photo or a map.",
    goal: "A paired description of the same viewpoint now and in an older image, with three changes and one continuity.",
    materials: [
      "An old photo, postcard, or map of a street you can stand on (Trove, family, council)",
      "Your own photo or a careful sketch from the same spot",
    ],
    steps: [
      {
        id: "s1",
        title: "Match the viewpoint",
        body: "Stand where the photographer likely stood. If you cannot, say so and work from two maps instead. Write the year of the old image and today’s date.",
      },
      {
        id: "s2",
        title: "List three changes",
        body: "Buildings, trees, tram vs car, shop names, a missing creek. Each change needs a visible cue, not a vibe.",
      },
      {
        id: "s3",
        title: "List one continuity",
        body: "A alignment of the road, a church, a ridgeline. Continuity stops the story becoming “everything is new”.",
      },
      {
        id: "s4",
        title: "Refuse the moral",
        body: "Do not end with “progress” or “ruin” unless a source uses that word. End with a question the pair still cannot answer (who was moved, who owned the block).",
      },
    ],
    checklist: [
      { id: "d1", label: "Old image/map has a date (or an honest ‘date unknown’)" },
      { id: "d2", label: "A now photo or sketch is paired with the same viewpoint or map extent" },
      { id: "d3", label: "Three evidenced changes and one continuity are listed" },
      { id: "d4", label: "The write-up ends with a question the images cannot answer" },
    ],
    pathIds: ["making-australia", "h-periodise", "country-contact"],
    difficulty: "medium",
    minutes: 40,
    xp: 120,
  },
  {
    id: "history-object-story",
    subject: "history",
    title: "Object with a paper trail",
    blurb: "One object in the house. Where it came from is a research problem.",
    goal: "A 200-word object biography with at least two sources, including what you cannot know.",
    materials: [
      "An object (coin, appliance, school badge, vinyl, tool)",
      "Maker’s mark, receipt, or family story",
      "One external source (manual, catalogue, museum page)",
    ],
    steps: [
      {
        id: "s1",
        title: "Describe before you google",
        body: "Material, marks, damage, where it lives now. A photo. Family story goes in quotes so it does not become a fact by accident.",
      },
      {
        id: "s2",
        title: "Find a maker or a date range",
        body: "Stamp, logo, patent, or style. If you only have “Mum says the 80s”, label it oral. Corroborate if you can.",
      },
      {
        id: "s3",
        title: "Put it in a wider story",
        body: "Trade, a factory town, a war surplus, a plastic boom. One paragraph, sourced. This is not a brand tribute.",
      },
      {
        id: "s4",
        title: "Draw the line",
        body: "Two things you still do not know (who sold it locally, whether it was stolen land money, a repair). History without a line is advertising.",
      },
    ],
    checklist: [
      { id: "d1", label: "Object is described from looking, with a photo or sketch" },
      { id: "d2", label: "Family story is quoted separately from checked facts" },
      { id: "d3", label: "At least one external source supports a date, maker, or use" },
      { id: "d4", label: "Two unknowns are listed at the end" },
    ],
    pathIds: ["historical-thinking", "h-silence-archive", "twentieth-century"],
    difficulty: "easy",
    minutes: 40,
    xp: 90,
  },
  {
    id: "geography-suburb-services",
    subject: "geography",
    title: "Suburb services map",
    blurb: "Who can walk to a shop, a park, a clinic — on a map you drew.",
    goal: "A sketch map of one suburb with at least six services and a note on who is left far away.",
    materials: [
      "Paper and a reference map (phone is fine)",
      "A suburb you know on foot or by bus",
    ],
    steps: [
      {
        id: "s1",
        title: "Set the frame",
        body: "North arrow, a scale guess (minutes walking or metres), and the suburb name. A screenshot with doodles on top still needs those three.",
      },
      {
        id: "s2",
        title: "Plot six services",
        body: "Food, green space, health, transit stop, school or library, and one more that matters locally (mosque, pool, servo). Use the same symbol set twice and you fail your own legend.",
      },
      {
        id: "s3",
        title: "Mark a gap",
        body: "A block that is far from fresh food or a crossing that chops a walking route. Write who that gap hits (no car, shift workers, a steep hill).",
      },
      {
        id: "s4",
        title: "One sentence of liveability that a map can bear",
        body: "Not “this suburb is good”. “Most mapped services sit on the highway side of the rail line” is geography.",
      },
    ],
    checklist: [
      { id: "d1", label: "Map has a name, north, and a scale or walking-time note" },
      { id: "d2", label: "Six different services are plotted with a legend" },
      { id: "d3", label: "A service gap is marked and linked to who it affects" },
      { id: "d4", label: "The closing sentence is something the map can actually show" },
    ],
    pathIds: ["g-scale-map", "g-thematic", "g-gis-layer"],
    difficulty: "medium",
    minutes: 40,
    xp: 120,
    figure: diagramFigure(
      "suburb-map",
      "Sketch map with a north arrow, shop and park symbols, a walking-time note, and a legend.",
      "North, scale or walking time, and a legend. A screenshot with doodles still needs those three.",
    ),
  },
  {
    id: "geography-catchment",
    subject: "geography",
    title: "Where does the rain go?",
    blurb: "From a roof or a path to a drain, creek, or bay — a water story of one block.",
    goal: "A flow diagram of stormwater from one hard surface to the next named water body, plus one pollution risk.",
    materials: [
      "Shoes and a dry-day walk after you have seen it rain once",
      "Notes / sketch",
    ],
    steps: [
      {
        id: "s1",
        title: "Start at a hard surface",
        body: "Roof downpipe, car park, or school asphalt. Where does the water want to go? Follow downhill, not the road name.",
      },
      {
        id: "s2",
        title: "Find the drain or the soak",
        body: "Grate, swale, garden, or a river of gutter. Photograph the grate if you can. Write whether it looked blocked.",
      },
      {
        id: "s3",
        title: "Name the next water",
        body: "A creek, canal, bay, or “underground then the harbour”. Use a map if the grate swallowed the story. Country and catchment names if you know them.",
      },
      {
        id: "s4",
        title: "Add a risk",
        body: "Oil, dog bags, leaf litter, a building site. One sentence on what a first-flush rain would carry from your start point.",
      },
    ],
    checklist: [
      { id: "d1", label: "A starting hard surface is named and located" },
      { id: "d2", label: "The path to a drain, soak, or channel is sketched" },
      { id: "d3", label: "The next named water body or harbour is identified" },
      { id: "d4", label: "One pollution or blockage risk is tied to that path" },
    ],
    pathIds: ["g-contour", "g-topo-spot", "g-lat-long"],
    difficulty: "easy",
    minutes: 35,
    xp: 90,
  },
  {
    id: "geography-climate-pair",
    subject: "geography",
    title: "Two Australian climates",
    blurb: "Same country, different graphs. Compare with numbers, not postcards.",
    goal: "A comparison table of two Australian places: rainfall, a temperature range, and one human or biome consequence.",
    materials: [
      "BOM climate statistics or a textbook graph you cite",
      "Paper",
    ],
    steps: [
      {
        id: "s1",
        title: "Pick two places that are not twins",
        body: "Darwin and Hobart, Broome and Canberra, Cairns and Alice. Write why they are a useful pair (latitude, coast, inland).",
      },
      {
        id: "s2",
        title: "Table three numbers each",
        body: "Mean max of a summer month, mean min of a winter month, and annual rainfall or the wettest month. Cite the table. Do not screenshot a meme.",
      },
      {
        id: "s3",
        title: "Explain one difference with a mechanism",
        body: "Monsoon, latitude, cold current, elevation, continentality. One mechanism, not a list of factors you memorised.",
      },
      {
        id: "s4",
        title: "Consequence",
        body: "Housing, farming, fire, cyclone, or tourism season. Tie it to a number in your table.",
      },
    ],
    checklist: [
      { id: "d1", label: "Two Australian places are named with a reason for the pair" },
      { id: "d2", label: "Three comparable climate figures each are cited" },
      { id: "d3", label: "One difference is explained with a physical mechanism" },
      { id: "d4", label: "A human or biome consequence is tied to a table number" },
    ],
    pathIds: ["g-projection-lie", "g-thematic"],
    difficulty: "medium",
    minutes: 35,
    xp: 120,
  },
  {
    id: "civics-bill-trace",
    subject: "civics",
    title: "Trace a bill or a council decision",
    blurb: "Who moved it, who checks it, where a person like you could still speak.",
    goal: "A one-page trace of a real Australian bill, regulation, or local council item from idea to (possible) law.",
    materials: [
      "Parliament, legislation, or council agenda site",
      "Notes",
    ],
    steps: [
      {
        id: "s1",
        title: "Pick a live or recent item",
        body: "A bill in a state or federal parliament, or a council agenda item (parking, library hours, a DA). Write the official title and the body that owns it.",
      },
      {
        id: "s2",
        title: "Draw the steps",
        body: "Introduction, committee or exhibition, vote, assent or council resolution. Local and federal are not the same cartoon. Use the real names.",
      },
      {
        id: "s3",
        title: "Find the public hook",
        body: "A submission date, a question time, a council public forum. If there is none left, write that the window closed and when.",
      },
      {
        id: "s4",
        title: "Who checks whom",
        body: "Upper house, minister, ombudsman, court, next election. One check that could still stop or shape this item. Power with receipts, not a vibe about politicians.",
      },
    ],
    checklist: [
      { id: "d1", label: "Item title and owning parliament or council are recorded" },
      { id: "d2", label: "The real stages are listed (not a US civics cartoon)" },
      { id: "d3", label: "A public participation hook or its closed date is named" },
      { id: "d4", label: "One checking body or later veto is identified" },
    ],
    pathIds: ["v-parliament", "v-federal", "v-const-au"],
    difficulty: "hard",
    minutes: 45,
    xp: 150,
  },
  {
    id: "civics-rights-map",
    subject: "civics",
    title: "Rights versus rules in one scene",
    blurb: "A school, a train, a protest. What is a right, what is a rule, who enforces it.",
    goal: "A mapped scene with three rules, one right, and a fair-process question.",
    materials: [
      "A real scene you know (school gate, station, workplace, match day)",
      "Notes — look up the actual rule if you claim it",
    ],
    steps: [
      {
        id: "s1",
        title: "Set the scene",
        body: "Where, who has a uniform or a badge, what people are trying to do. No Hollywood riot.",
      },
      {
        id: "s2",
        title: "List three rules",
        body: "Ticket, bag check, uniform, no-smoking. For each: who wrote it (school, operator, parliament) if you can tell.",
      },
      {
        id: "s3",
        title: "Name one right that still sits underneath",
        body: "Safety, non-discrimination, a hearing before a serious punishment. Australian rights are a mix of statute, common law, and implied political communication — do not paste the US Bill of Rights.",
      },
      {
        id: "s4",
        title: "Ask a process question",
        body: "If the rule is applied unfairly, who do you ask next? Teacher, ombudsman, union, court. Write one next step that exists, not “go viral”.",
      },
    ],
    checklist: [
      { id: "d1", label: "Scene is specific (place and what people are doing)" },
      { id: "d2", label: "Three rules are listed with a likely author of each" },
      { id: "d3", label: "One right is named without importing a foreign constitution" },
      { id: "d4", label: "A real next-step for unfair process is written" },
    ],
    pathIds: ["v-rights-limits", "v-fair-process", "v-rule-law"],
    difficulty: "medium",
    minutes: 30,
    xp: 120,
  },
  {
    id: "civics-vote-path",
    subject: "civics",
    title: "How a vote becomes a rule",
    blurb: "From ballot paper to a classroom or a kerb. Follow one chain.",
    goal: "A flowchart from an election or a council vote to one everyday rule you live under.",
    materials: [
      "AEC or state electoral site, or a council minutes page",
      "Paper",
    ],
    steps: [
      {
        id: "s1",
        title: "Start at a ballot",
        body: "Federal, state, or local. Write who was on the ballot that matters for your chain (member, mayor, referendum question).",
      },
      {
        id: "s2",
        title: "Name the winner’s job",
        body: "They do not personally pave your street. Government vs parliament vs public service. One sentence on who actually drafts the thing.",
      },
      {
        id: "s3",
        title: "Land on an everyday rule",
        body: "A speed limit, a recycling bin, a school leaving age, GST. Connect it to a statute or a local law with a name or a URL.",
      },
      {
        id: "s4",
        title: "Show a later check",
        body: "The next election, a court, a minister, a council rescission. If nobody can change it, you probably skipped a step.",
      },
    ],
    checklist: [
      { id: "d1", label: "Ballot level (federal / state / local) is specified" },
      { id: "d2", label: "The flowchart separates politicians from the people who draft rules" },
      { id: "d3", label: "An everyday rule is tied to a named law or council instrument" },
      { id: "d4", label: "A later check or change path is included" },
    ],
    pathIds: ["v-why-rules", "v-parliament", "v-consequences"],
    difficulty: "easy",
    minutes: 35,
    xp: 90,
  },
  {
    id: "languages-intro-30s",
    subject: "languages",
    title: "Thirty-second intro checklist",
    blurb: "Record a greeting that a human could answer. Politeness is a design choice.",
    goal: "A 30-second spoken intro in a language you are learning (or a careful English-for-the-purpose script if you are on the intro hub), plus a checklist of sounds you still miss.",
    materials: [
      "Phone voice memo",
      "A target language you have any contact with (school, family, community)",
      "A native or stronger speaker if you can find one — optional",
    ],
    steps: [
      {
        id: "s1",
        title: "Write the script in both languages",
        body: "Name, where you live (suburb is enough), one like, one polite closer. Mark stress. If your hub language is still ‘how languages work’, pick one real language and say so.",
      },
      {
        id: "s2",
        title: "Record once without stopping",
        body: "Thirty seconds, messy is fine. Listen back. Circle two sounds or tones that broke.",
      },
      {
        id: "s3",
        title: "Fix the politeness, not only the vowels",
        body: "T–V distinction, a family name, whether ‘hi’ is too casual. Write the register you chose and who it would offend.",
      },
      {
        id: "s4",
        title: "Record a second take",
        body: "Same script. Keep both files. The deliverable is the pair plus the two sounds you are still practising — not fluency.",
      },
    ],
    checklist: [
      { id: "d1", label: "A bilingual script exists (target + English gloss)" },
      { id: "d2", label: "Two recordings exist (first take and a second take)" },
      { id: "d3", label: "Register / politeness choice is written down" },
      { id: "d4", label: "Two sounds or patterns still to practise are circled" },
    ],
    pathIds: ["l-register-lang", "l-pragmatics", "l-lang-not-code"],
    difficulty: "easy",
    minutes: 25,
    xp: 90,
  },
  {
    id: "languages-phrasebook",
    subject: "languages",
    title: "Trip phrasebook that could work",
    blurb: "Twenty lines you would actually say: help, food, thanks, no.",
    goal: "A twenty-line phrasebook for one trip scenario, grouped by job, with pronunciation hints you can use.",
    materials: [
      "Paper or a notes file",
      "A dictionary or a class list you cite — not a mystery generator dump",
    ],
    steps: [
      {
        id: "s1",
        title: "Pick the trip",
        body: "Airport, homestay, or a weekend in a suburb where the language is spoken. Write who you are talking to.",
      },
      {
        id: "s2",
        title: "Group by job",
        body: "Greet, ask, refuse, thank, emergency. Twenty lines total. “Where is the bathroom” without “I don’t understand” is a trap.",
      },
      {
        id: "s3",
        title: "Add a hint you can say aloud",
        body: "Stress marks, a respelling, or IPA if you have it. If you cannot say it, it is not in the book.",
      },
      {
        id: "s4",
        title: "Stress-test two lines",
        body: "Say them to a speaker, a teacher, or a recording comparison. Fix the two that fail. Note any cultural no (pointing, first names).",
      },
    ],
    checklist: [
      { id: "d1", label: "Scenario and addressee are specified" },
      { id: "d2", label: "Twenty lines are grouped by communicative job" },
      { id: "d3", label: "Each line has a gloss and a say-aloud hint" },
      { id: "d4", label: "Two lines were spoken and corrected; one cultural caution is noted" },
    ],
    pathIds: ["l-displacement", "l-dialect", "l-arbitrariness"],
    difficulty: "medium",
    minutes: 40,
    xp: 120,
  },
  {
    id: "languages-room-labels",
    subject: "languages",
    title: "Label the room",
    blurb: "Eight objects, two articles or classifiers if the language has them, and a door you walk through.",
    goal: "Physical or digital labels in the target language for one room, with a tiny grammar note.",
    materials: [
      "Sticky notes or a labelled photo",
      "Target language word list you can defend",
    ],
    steps: [
      {
        id: "s1",
        title: "Photograph the room",
        body: "Kitchen or bedroom. Circle eight objects. Write the English names first so you do not skip the ugly ones (tap, charger).",
      },
      {
        id: "s2",
        title: "Label with grammar, not stickers only",
        body: "Gender, article, classifier, or plural if the language cares. A bare noun dumped from a translator is half a label.",
      },
      {
        id: "s3",
        title: "Add two verbs of place",
        body: "Is / are / sits / hangs. One sentence per two objects (“the cups are on the shelf”).",
      },
      {
        id: "s4",
        title: "Walk the door",
        body: "Say the eight nouns aloud as you point. Remove any label you cannot pronounce yet and replace it after a lookup you cite.",
      },
    ],
    checklist: [
      { id: "d1", label: "Eight objects in one real room are labelled" },
      { id: "d2", label: "Articles, classifiers, or number are shown where the language needs them" },
      { id: "d3", label: "Two location sentences use those nouns" },
      { id: "d4", label: "You can say every remaining label aloud" },
    ],
    pathIds: ["l-duality", "l-lang-not-code"],
    difficulty: "easy",
    minutes: 25,
    xp: 90,
  },
];
