export const fr = {
  id: "fr",
  title: "French",
  nativeName: "Français",
  mark: "FR",
  blurb: "Greetings to survival phrases. Tap, match, type, and say it — one prompt at a time.",
  speechLang: "fr-FR",
  accent: "#60a5fa",
  accentDim: "#1e3a8a",
  units: [
    {
      title: "Greetings",
      skill: "Say hello",
      vocab: [
        { n: "Bonjour", e: "Hello", p: "bon-ZHOOR", altsE: ["hi", "good day", "good morning"] },
        { n: "Bonsoir", e: "Good evening", p: "bon-SWAHR" },
        { n: "Salut", e: "Hi", p: "sah-LUU", altsE: ["hey"] },
        { n: "Au revoir", e: "Goodbye", p: "oh ruh-VWAHR", altsE: ["bye"] },
        { n: "Merci", e: "Thank you", p: "mehr-SEE", altsE: ["thanks"] },
        { n: "Merci beaucoup", e: "Thank you very much", p: "mehr-SEE boh-KOO", altsE: ["thanks a lot"] },
        { n: "S'il vous plaît", e: "Please", p: "seel voo PLEH", altsN: ["S'il te plaît"], note: "vous is the polite form." },
        { n: "De rien", e: "You're welcome", p: "duh RYEN", altsE: ["you are welcome"] },
        { n: "Oui", e: "Yes", p: "wee" },
        { n: "Non", e: "No", p: "nohn" },
        { n: "Excusez-moi", e: "Excuse me", p: "ex-kew-zay MWAH", altsE: ["sorry", "pardon me"] },
        { n: "À bientôt", e: "See you soon", p: "ah byan-TOH" },
        { n: "Monsieur", e: "Sir", p: "muh-SYUH", altsE: ["mr", "mister"] },
        { n: "Madame", e: "Madam", p: "mah-DAHM", altsE: ["maam", "mrs"] },
      ],
      phrases: [
        { n: "Comment allez-vous", e: "How are you", p: "ko-mahn tah-lay VOO", tokens: ["Comment", "allez-vous"], altsE: ["how are you doing"], note: "Formal vous." },
        { n: "Ça va", e: "How's it going", p: "sah VAH", tokens: ["Ça", "va"], altsE: ["how is it going", "you okay"] },
        { n: "Ça va bien", e: "I'm well", p: "sah vah BYAN", tokens: ["Ça", "va", "bien"], altsE: ["i am well", "its going well"] },
        { n: "Je m'appelle Marie", e: "My name is Marie", p: "zhuh mah-PELL mah-REE", tokens: ["Je", "m'appelle", "Marie"] },
        { n: "Comment tu t'appelles", e: "What's your name", p: "ko-mahn too tah-PELL", tokens: ["Comment", "tu", "t'appelles"], altsE: ["what is your name"] },
        { n: "Enchanté", e: "Nice to meet you", p: "ahn-shahn-TAY", tokens: ["Enchanté"] },
        { n: "Bonne nuit", e: "Good night", p: "bun NWEE", tokens: ["Bonne", "nuit"] },
        { n: "À demain", e: "See you tomorrow", p: "ah duh-MAN", tokens: ["À", "demain"] },
      ],
    },
    {
      title: "Numbers",
      skill: "Count to twenty",
      vocab: [
        { n: "un", e: "one", p: "uhn" },
        { n: "deux", e: "two", p: "duh" },
        { n: "trois", e: "three", p: "trwah" },
        { n: "quatre", e: "four", p: "KAH-truh" },
        { n: "cinq", e: "five", p: "sank" },
        { n: "six", e: "six", p: "seess" },
        { n: "sept", e: "seven", p: "set" },
        { n: "huit", e: "eight", p: "weet" },
        { n: "neuf", e: "nine", p: "nuhf" },
        { n: "dix", e: "ten", p: "deess" },
        { n: "onze", e: "eleven", p: "ohnz" },
        { n: "douze", e: "twelve", p: "dooz" },
        { n: "vingt", e: "twenty", p: "van" },
        { n: "cent", e: "hundred", p: "sahn", altsE: ["one hundred", "a hundred"] },
      ],
      phrases: [
        { n: "J'ai deux sœurs", e: "I have two sisters", p: "zhay duh SUR", tokens: ["J'ai", "deux", "sœurs"] },
        { n: "Ça coûte dix euros", e: "That costs ten euros", p: "sah koot deess uh-ROH", tokens: ["Ça", "coûte", "dix", "euros"] },
        { n: "Un deux trois", e: "One two three", p: "uhn duh trwah", tokens: ["Un", "deux", "trois"] },
        { n: "J'ai vingt ans", e: "I am twenty years old", p: "zhay van TAHN", tokens: ["J'ai", "vingt", "ans"], note: "French uses avoir for age." },
        { n: "Combien", e: "How much", p: "kohn-BYAN", tokens: ["Combien"], altsE: ["how many"] },
        { n: "Il est une heure", e: "It is one o'clock", p: "eel eh tewn UR", tokens: ["Il", "est", "une", "heure"] },
        { n: "Numéro cinq", e: "Number five", p: "new-may-roh SANK", tokens: ["Numéro", "cinq"] },
        { n: "Cent personnes", e: "A hundred people", p: "sahn pehr-SUN", tokens: ["Cent", "personnes"] },
      ],
    },
    {
      title: "Food",
      skill: "Order a meal",
      vocab: [
        { n: "le pain", e: "bread", p: "luh pan" },
        { n: "l'eau", e: "water", p: "loh", altsN: ["eau"] },
        { n: "le café", e: "coffee", p: "luh kah-FAY", altsN: ["café"] },
        { n: "le thé", e: "tea", p: "luh TAY", altsN: ["thé"] },
        { n: "le fromage", e: "cheese", p: "luh fro-MAHZH" },
        { n: "la pomme", e: "apple", p: "lah PUM" },
        { n: "le vin", e: "wine", p: "luh van" },
        { n: "le restaurant", e: "restaurant", p: "luh res-toh-RAHN" },
        { n: "l'addition", e: "the bill", p: "lah-dee-SYOHN", altsE: ["check", "bill"] },
        { n: "le petit-déjeuner", e: "breakfast", p: "luh puh-tee day-zhuh-NAY" },
        { n: "le déjeuner", e: "lunch", p: "luh day-zhuh-NAY" },
        { n: "le dîner", e: "dinner", p: "luh dee-NAY" },
        { n: "j'ai faim", e: "I am hungry", p: "zhay fan", altsE: ["im hungry"] },
        { n: "j'ai soif", e: "I am thirsty", p: "zhay swahf", altsE: ["im thirsty"] },
      ],
      phrases: [
        { n: "Je voudrais un café", e: "I would like a coffee", p: "zhuh voo-DREH uhn kah-FAY", tokens: ["Je", "voudrais", "un", "café"] },
        { n: "L'addition s'il vous plaît", e: "The bill please", p: "lah-dee-SYOHN seel voo PLEH", tokens: ["L'addition", "s'il", "vous", "plaît"] },
        { n: "C'est délicieux", e: "It's delicious", p: "seh day-lee-SYUH", tokens: ["C'est", "délicieux"], altsE: ["it is delicious"] },
        { n: "Je n'aime pas ça", e: "I don't like that", p: "zhuh nem pah SAH", tokens: ["Je", "n'aime", "pas", "ça"] },
        { n: "De l'eau s'il vous plaît", e: "Some water please", p: "duh LOH seel voo PLEH", tokens: ["De", "l'eau", "s'il", "vous", "plaît"] },
        { n: "Je suis végétarien", e: "I am vegetarian", p: "zhuh swee vay-zhay-tah-RYAN", tokens: ["Je", "suis", "végétarien"] },
        { n: "C'est trop sucré", e: "It's too sweet", p: "seh troh sew-KRAY", tokens: ["C'est", "trop", "sucré"] },
        { n: "Un croissant et un thé", e: "A croissant and a tea", p: "uhn krwah-SAHN ay uhn TAY", tokens: ["Un", "croissant", "et", "un", "thé"] },
      ],
    },
    {
      title: "Travel",
      skill: "Find your way",
      vocab: [
        { n: "le train", e: "train", p: "luh trahn" },
        { n: "l'avion", e: "plane", p: "lah-VYOHN", altsE: ["airplane", "aeroplane"] },
        { n: "l'hôtel", e: "hotel", p: "lo-TEL", altsN: ["hôtel"] },
        { n: "la gare", e: "train station", p: "lah GAR", altsE: ["station"] },
        { n: "l'aéroport", e: "airport", p: "lah-ay-ro-POR" },
        { n: "le billet", e: "ticket", p: "luh bee-YEH" },
        { n: "le passeport", e: "passport", p: "luh pass-POR" },
        { n: "le taxi", e: "taxi", p: "luh tak-SEE" },
        { n: "la rue", e: "street", p: "lah REW" },
        { n: "à gauche", e: "to the left", p: "ah GOHSH", altsE: ["left"] },
        { n: "à droite", e: "to the right", p: "ah DRWAHT", altsE: ["right"] },
        { n: "tout droit", e: "straight ahead", p: "too DRWAH", altsE: ["straight"] },
        { n: "la carte", e: "map", p: "lah KART", altsE: ["menu", "card"] },
        { n: "la plage", e: "beach", p: "lah PLAHZH" },
      ],
      phrases: [
        { n: "Où est la gare", e: "Where is the station", p: "oo eh lah GAR", tokens: ["Où", "est", "la", "gare"] },
        { n: "Je cherche l'hôtel", e: "I am looking for the hotel", p: "zhuh SHAIRSH lo-TEL", tokens: ["Je", "cherche", "l'hôtel"] },
        { n: "Un billet pour Paris", e: "A ticket to Paris", p: "uhn bee-YEH poor pah-REE", tokens: ["Un", "billet", "pour", "Paris"] },
        { n: "C'est loin", e: "It is far", p: "seh LWAN", tokens: ["C'est", "loin"] },
        { n: "C'est près d'ici", e: "It is nearby", p: "seh preh dee-SEE", tokens: ["C'est", "près", "d'ici"], altsE: ["its close"] },
        { n: "Tournez à gauche", e: "Turn left", p: "toor-nay ah GOHSH", tokens: ["Tournez", "à", "gauche"] },
        { n: "Où est l'aéroport", e: "Where is the airport", p: "oo eh lah-ay-ro-POR", tokens: ["Où", "est", "l'aéroport"] },
        { n: "J'ai un passeport", e: "I have a passport", p: "zhay uhn pass-POR", tokens: ["J'ai", "un", "passeport"] },
      ],
    },
    {
      title: "Family",
      skill: "Talk about people",
      vocab: [
        { n: "la mère", e: "mother", p: "lah MEHR", altsE: ["mum", "mom"] },
        { n: "le père", e: "father", p: "luh PEHR", altsE: ["dad"] },
        { n: "le frère", e: "brother", p: "luh FREHR" },
        { n: "la sœur", e: "sister", p: "lah SUR" },
        { n: "l'enfant", e: "child", p: "lahn-FAHN" },
        { n: "le fils", e: "son", p: "luh FEESS" },
        { n: "la fille", e: "daughter", p: "lah FEE", altsE: ["girl"] },
        { n: "les parents", e: "parents", p: "lay pah-RAHN" },
        { n: "la famille", e: "family", p: "lah fah-MEE" },
        { n: "un ami", e: "a friend", p: "uhn ah-MEE", altsE: ["friend"] },
        { n: "mon", e: "my (masculine)", p: "mohn", altsE: ["my"] },
        { n: "ma", e: "my (feminine)", p: "mah", altsE: ["my"] },
        { n: "les enfants", e: "the children", p: "layz ahn-FAHN", altsE: ["children"] },
        { n: "le mari", e: "husband", p: "luh mah-REE" },
      ],
      phrases: [
        { n: "Voici ma mère", e: "This is my mother", p: "vwah-SEE mah MEHR", tokens: ["Voici", "ma", "mère"] },
        { n: "J'ai un frère", e: "I have a brother", p: "zhay uhn FREHR", tokens: ["J'ai", "un", "frère"] },
        { n: "C'est ma sœur", e: "That is my sister", p: "seh mah SUR", tokens: ["C'est", "ma", "sœur"] },
        { n: "Nous sommes une famille", e: "We are a family", p: "noo sum ewn fah-MEE", tokens: ["Nous", "sommes", "une", "famille"] },
        { n: "Mon père s'appelle Paul", e: "My father's name is Paul", p: "mohn pehr sah-PELL POL", tokens: ["Mon", "père", "s'appelle", "Paul"] },
        { n: "Elle a deux enfants", e: "She has two children", p: "el ah duh zahn-FAHN", tokens: ["Elle", "a", "deux", "enfants"] },
        { n: "C'est un ami", e: "He is a friend", p: "seh tuhn ah-MEE", tokens: ["C'est", "un", "ami"], altsE: ["this is a friend"] },
        { n: "Ma fille a dix ans", e: "My daughter is ten", p: "mah fee ah deez AHN", tokens: ["Ma", "fille", "a", "dix", "ans"] },
      ],
    },
    {
      title: "Adjectives",
      skill: "Describe things",
      vocab: [
        { n: "grand", e: "big", p: "grahn", altsE: ["tall", "large"] },
        { n: "petit", e: "small", p: "puh-TEE", altsE: ["little"] },
        { n: "bon", e: "good", p: "bohn" },
        { n: "mauvais", e: "bad", p: "moh-VEH" },
        { n: "chaud", e: "hot", p: "shoh" },
        { n: "froid", e: "cold", p: "frwah" },
        { n: "beau", e: "beautiful", p: "boh", altsE: ["handsome"] },
        { n: "nouveau", e: "new", p: "noo-VOH" },
        { n: "vieux", e: "old", p: "vyuh" },
        { n: "jeune", e: "young", p: "zhun" },
        { n: "facile", e: "easy", p: "fah-SEEL" },
        { n: "difficile", e: "difficult", p: "dee-fee-SEEL", altsE: ["hard"] },
        { n: "cher", e: "expensive", p: "shair" },
        { n: "rapide", e: "fast", p: "rah-PEED", altsE: ["quick"] },
      ],
      phrases: [
        { n: "C'est trop cher", e: "It's too expensive", p: "seh troh SHAIR", tokens: ["C'est", "trop", "cher"] },
        { n: "Il fait chaud", e: "It is hot", p: "eel feh SHOH", tokens: ["Il", "fait", "chaud"], note: "Weather uses il fait." },
        { n: "Il fait froid", e: "It is cold", p: "eel feh FRWAH", tokens: ["Il", "fait", "froid"] },
        { n: "C'est facile", e: "It is easy", p: "seh fah-SEEL", tokens: ["C'est", "facile"] },
        { n: "Le café est bon", e: "The coffee is good", p: "luh kah-FAY eh BOHN", tokens: ["Le", "café", "est", "bon"] },
        { n: "Elle est jeune", e: "She is young", p: "el eh ZHUN", tokens: ["Elle", "est", "jeune"] },
        { n: "Un petit hôtel", e: "A small hotel", p: "uhn puh-TEE o-TEL", tokens: ["Un", "petit", "hôtel"] },
        { n: "C'est très beau", e: "It is very beautiful", p: "seh treh BOH", tokens: ["C'est", "très", "beau"] },
      ],
    },
    {
      title: "Present patterns",
      skill: "Be, have, go",
      vocab: [
        { n: "je suis", e: "I am", p: "zhuh SWEE" },
        { n: "tu es", e: "you are", p: "tew EH", note: "Informal you." },
        { n: "il est", e: "he is", p: "eel EH", altsE: ["it is"] },
        { n: "elle est", e: "she is", p: "el EH" },
        { n: "nous sommes", e: "we are", p: "noo SUM" },
        { n: "j'ai", e: "I have", p: "zhay" },
        { n: "tu as", e: "you have", p: "tew AH" },
        { n: "je vais", e: "I go", p: "zhuh VEH", altsE: ["i am going"] },
        { n: "tu vas", e: "you go", p: "tew VAH" },
        { n: "être", e: "to be", p: "EH-truh" },
        { n: "avoir", e: "to have", p: "ah-VWAHR" },
        { n: "aller", e: "to go", p: "ah-LAY" },
        { n: "vous êtes", e: "you are (formal)", p: "voo ZET" },
        { n: "ils sont", e: "they are", p: "eel SOHN" },
      ],
      phrases: [
        { n: "Je suis étudiant", e: "I am a student", p: "zhuh swee zay-tew-DYAHN", tokens: ["Je", "suis", "étudiant"] },
        { n: "Tu es fatigué", e: "You are tired", p: "tew eh fah-tee-GAY", tokens: ["Tu", "es", "fatigué"] },
        { n: "J'ai un billet", e: "I have a ticket", p: "zhay uhn bee-YEH", tokens: ["J'ai", "un", "billet"] },
        { n: "Je vais à Paris", e: "I am going to Paris", p: "zhuh veh zah pah-REE", tokens: ["Je", "vais", "à", "Paris"] },
        { n: "Nous sommes ici", e: "We are here", p: "noo sum ee-SEE", tokens: ["Nous", "sommes", "ici"] },
        { n: "Elle est à la gare", e: "She is at the station", p: "el eh tah lah GAR", tokens: ["Elle", "est", "à", "la", "gare"] },
        { n: "Vous êtes très gentil", e: "You are very kind", p: "voo zet treh zhan-TEE", tokens: ["Vous", "êtes", "très", "gentil"] },
        { n: "Il est professeur", e: "He is a teacher", p: "eel eh pro-fess-UR", tokens: ["Il", "est", "professeur"] },
      ],
    },
    {
      title: "Common verbs",
      skill: "Do the usual things",
      vocab: [
        { n: "parler", e: "to speak", p: "par-LAY" },
        { n: "manger", e: "to eat", p: "mahn-ZHAY" },
        { n: "boire", e: "to drink", p: "BWAHR" },
        { n: "vouloir", e: "to want", p: "voo-LWAHR" },
        { n: "pouvoir", e: "to be able", p: "poo-VWAHR", altsE: ["can", "to can"] },
        { n: "faire", e: "to do", p: "FEHR", altsE: ["to make"] },
        { n: "venir", e: "to come", p: "vuh-NEER" },
        { n: "prendre", e: "to take", p: "PRAHN-druh" },
        { n: "voir", e: "to see", p: "VWAHR" },
        { n: "je parle", e: "I speak", p: "zhuh PARL" },
        { n: "je mange", e: "I eat", p: "zhuh MAHNZH" },
        { n: "je veux", e: "I want", p: "zhuh VUH" },
        { n: "je peux", e: "I can", p: "zhuh PUH" },
        { n: "je fais", e: "I do", p: "zhuh FEH", altsE: ["i make"] },
      ],
      phrases: [
        { n: "Je parle français", e: "I speak French", p: "zhuh parl frahn-SEH", tokens: ["Je", "parle", "français"] },
        { n: "Je mange du pain", e: "I eat bread", p: "zhuh mahnzh dew pan", tokens: ["Je", "mange", "du", "pain"] },
        { n: "Je veux de l'eau", e: "I want some water", p: "zhuh vuh duh LOH", tokens: ["Je", "veux", "de", "l'eau"] },
        { n: "Je peux t'aider", e: "I can help you", p: "zhuh puh teh-DAY", tokens: ["Je", "peux", "t'aider"] },
        { n: "Nous prenons le train", e: "We take the train", p: "noo pruh-nohn luh trahn", tokens: ["Nous", "prenons", "le", "train"] },
        { n: "Je bois du café", e: "I drink coffee", p: "zhuh bwah dew kah-FAY", tokens: ["Je", "bois", "du", "café"] },
        { n: "Tu viens demain", e: "You come tomorrow", p: "tew vyahn duh-MAN", tokens: ["Tu", "viens", "demain"] },
        { n: "Je ne comprends pas", e: "I do not understand", p: "zhuh nuh kom-prahn PAH", tokens: ["Je", "ne", "comprends", "pas"] },
      ],
    },
    {
      title: "Survival",
      skill: "Get unstuck",
      vocab: [
        { n: "Aidez-moi", e: "Help me", p: "eh-day MWAH", altsE: ["help"] },
        { n: "lentement", e: "slowly", p: "lahnt-MAHN" },
        { n: "les toilettes", e: "the toilets", p: "lay twah-LET", altsE: ["bathroom", "restroom"] },
        { n: "perdu", e: "lost", p: "pehr-DEW" },
        { n: "anglais", e: "English", p: "ahn-GLEH" },
        { n: "un peu", e: "a little", p: "uhn PUH" },
        { n: "allergique", e: "allergic", p: "ah-lehr-ZHEEK" },
        { n: "l'hôpital", e: "hospital", p: "lo-pee-TAHL" },
        { n: "la police", e: "police", p: "lah po-LEESS" },
        { n: "ouvert", e: "open", p: "oo-VEHR" },
        { n: "fermé", e: "closed", p: "fehr-MAY" },
        { n: "aujourd'hui", e: "today", p: "oh-zhoor-DWEE" },
        { n: "maintenant", e: "now", p: "mant-NAHN" },
        { n: "s'il te plaît", e: "please (informal)", p: "seel tuh PLEH" },
      ],
      phrases: [
        { n: "Je ne comprends pas", e: "I don't understand", p: "zhuh nuh kom-prahn PAH", tokens: ["Je", "ne", "comprends", "pas"] },
        { n: "Parlez-vous anglais", e: "Do you speak English", p: "par-lay voo zahn-GLEH", tokens: ["Parlez-vous", "anglais"] },
        { n: "Où sont les toilettes", e: "Where is the bathroom", p: "oo sohn lay twah-LET", tokens: ["Où", "sont", "les", "toilettes"] },
        { n: "Plus lentement s'il vous plaît", e: "More slowly please", p: "plew lahnt-MAHN seel voo PLEH", tokens: ["Plus", "lentement", "s'il", "vous", "plaît"] },
        { n: "Je suis perdu", e: "I am lost", p: "zhuh swee pehr-DEW", tokens: ["Je", "suis", "perdu"] },
        { n: "Je suis allergique", e: "I am allergic", p: "zhuh swee zah-lehr-ZHEEK", tokens: ["Je", "suis", "allergique"] },
        { n: "Combien ça coûte", e: "How much does it cost", p: "kohn-BYAN sah KOOT", tokens: ["Combien", "ça", "coûte"] },
        { n: "Pouvez-vous m'aider", e: "Can you help me", p: "poo-vay voo meh-DAY", tokens: ["Pouvez-vous", "m'aider"] },
      ],
    },
    {
      title: "Daily life",
      skill: "Shop and time",
      vocab: [
        { n: "aujourd'hui", e: "today", p: "oh-zhoor-DWEE" },
        { n: "demain", e: "tomorrow", p: "duh-MAN" },
        { n: "hier", e: "yesterday", p: "YEHR" },
        { n: "lundi", e: "Monday", p: "lun-DEE" },
        { n: "le magasin", e: "the shop", p: "luh mah-gah-ZAN", altsE: ["store", "shop"] },
        { n: "l'argent", e: "money", p: "lar-ZHAHN" },
        { n: "le prix", e: "the price", p: "luh PREE" },
        { n: "le temps", e: "the weather", p: "luh tahn", altsE: ["time"] },
        { n: "la pluie", e: "rain", p: "lah PLWEE" },
        { n: "le soleil", e: "the sun", p: "luh so-LAY" },
        { n: "le matin", e: "morning", p: "luh mah-TAN" },
        { n: "le soir", e: "evening", p: "luh SWAHR" },
        { n: "gratuit", e: "free", p: "grah-TWEE" },
        { n: "la monnaie", e: "change (coins)", p: "lah moh-NEH", altsE: ["change"] },
      ],
      phrases: [
        { n: "Quelle heure est-il", e: "What time is it", p: "kel UR eh-TEEL", tokens: ["Quelle", "heure", "est-il"] },
        { n: "Je voudrais ceci", e: "I would like this", p: "zhuh voo-DREH suh-SEE", tokens: ["Je", "voudrais", "ceci"] },
        { n: "C'est combien", e: "How much is it", p: "seh kohn-BYAN", tokens: ["C'est", "combien"] },
        { n: "Il pleut aujourd'hui", e: "It is raining today", p: "eel pluh oh-zhoor-DWEE", tokens: ["Il", "pleut", "aujourd'hui"] },
        { n: "Le magasin est ouvert", e: "The shop is open", p: "luh mah-gah-ZAN eh too-VEHR", tokens: ["Le", "magasin", "est", "ouvert"] },
        { n: "À demain matin", e: "See you tomorrow morning", p: "ah duh-MAN mah-TAN", tokens: ["À", "demain", "matin"] },
        { n: "Je n'ai pas d'argent", e: "I don't have money", p: "zhuh nay pah dar-ZHAHN", tokens: ["Je", "n'ai", "pas", "d'argent"] },
        { n: "C'est gratuit", e: "It is free", p: "seh grah-TWEE", tokens: ["C'est", "gratuit"] },
      ],
    },
  ],
};
