export const id = {
  id: "id",
  title: "Indonesian",
  nativeName: "Bahasa Indonesia",
  mark: "ID",
  blurb: "Latin script, friendly word order, and phrases you can use in a warung or an airport queue.",
  speechLang: "id-ID",
  accent: "#34d399",
  accentDim: "#064e3b",
  units: [
    {
      title: "Greetings",
      skill: "Say halo",
      vocab: [
        { n: "Halo", e: "Hello", p: "HAH-lo", altsE: ["hi"] },
        { n: "Selamat pagi", e: "Good morning", p: "suh-LAH-mat PAH-gee" },
        { n: "Selamat siang", e: "Good afternoon", p: "suh-LAH-mat see-AHNG", note: "Roughly 11–15." },
        { n: "Selamat sore", e: "Good late afternoon", p: "suh-LAH-mat SO-reh", altsE: ["good evening"] },
        { n: "Selamat malam", e: "Good night", p: "suh-LAH-mat MAH-lahm", altsE: ["good evening"] },
        { n: "Terima kasih", e: "Thank you", p: "tuh-REE-mah KAH-seeh", altsE: ["thanks"] },
        { n: "Terima kasih banyak", e: "Thank you very much", p: "tuh-REE-mah KAH-seeh BAHN-yak" },
        { n: "Sama-sama", e: "You're welcome", p: "SAH-mah SAH-mah", altsE: ["you are welcome"] },
        { n: "Tolong", e: "Please", p: "TOH-long", altsE: ["help"] },
        { n: "Ya", e: "Yes", p: "yah" },
        { n: "Tidak", e: "No", p: "TEE-dak", altsN: ["nggak"] },
        { n: "Permisi", e: "Excuse me", p: "per-MEE-see" },
        { n: "Sampai jumpa", e: "See you", p: "SAHM-pai JOOM-pah", altsE: ["goodbye"] },
        { n: "Selamat tinggal", e: "Goodbye", p: "suh-LAH-mat TEENG-gahl", note: "Said by the person leaving." },
      ],
      phrases: [
        { n: "Apa kabar", e: "How are you", p: "AH-pah KAH-bar", tokens: ["Apa", "kabar"] },
        { n: "Baik-baik saja", e: "I'm fine", p: "BAI-k baik SAH-jah", tokens: ["Baik-baik", "saja"], altsE: ["i am fine"] },
        { n: "Nama saya Budi", e: "My name is Budi", p: "NAH-mah SAH-yah BOO-dee", tokens: ["Nama", "saya", "Budi"] },
        { n: "Siapa nama Anda", e: "What is your name", p: "see-AH-pah NAH-mah AHN-dah", tokens: ["Siapa", "nama", "Anda"] },
        { n: "Senang bertemu dengan Anda", e: "Nice to meet you", p: "suh-NANG ber-tuh-MOO DENG-an AHN-dah", tokens: ["Senang", "bertemu", "dengan", "Anda"] },
        { n: "Selamat datang", e: "Welcome", p: "suh-LAH-mat DAH-tang", tokens: ["Selamat", "datang"] },
        { n: "Maaf", e: "Sorry", p: "MAH-af", tokens: ["Maaf"] },
        { n: "Sampai besok", e: "See you tomorrow", p: "SAHM-pai BEH-sok", tokens: ["Sampai", "besok"] },
      ],
    },
    {
      title: "Numbers",
      skill: "Count to twenty",
      vocab: [
        { n: "satu", e: "one", p: "SAH-too" },
        { n: "dua", e: "two", p: "DOO-ah" },
        { n: "tiga", e: "three", p: "TEE-gah" },
        { n: "empat", e: "four", p: "em-PAT" },
        { n: "lima", e: "five", p: "LEE-mah" },
        { n: "enam", e: "six", p: "uh-NAHM" },
        { n: "tujuh", e: "seven", p: "TOO-jooh" },
        { n: "delapan", e: "eight", p: "duh-LAH-pahn" },
        { n: "sembilan", e: "nine", p: "sem-BEE-lahn" },
        { n: "sepuluh", e: "ten", p: "suh-POO-looh" },
        { n: "sebelas", e: "eleven", p: "suh-buh-LAHS" },
        { n: "dua belas", e: "twelve", p: "DOO-ah buh-LAHS" },
        { n: "dua puluh", e: "twenty", p: "DOO-ah POO-looh" },
        { n: "seratus", e: "one hundred", p: "suh-RAH-toos", altsE: ["hundred", "a hundred"] },
      ],
      phrases: [
        { n: "Saya punya dua kakak", e: "I have two older siblings", p: "SAH-yah POON-yah DOO-ah KAH-kak", tokens: ["Saya", "punya", "dua", "kakak"] },
        { n: "Harganya sepuluh ribu", e: "The price is ten thousand", p: "HAR-gahn-yah suh-POO-looh REE-boo", tokens: ["Harganya", "sepuluh", "ribu"] },
        { n: "Satu dua tiga", e: "One two three", p: "SAH-too DOO-ah TEE-gah", tokens: ["Satu", "dua", "tiga"] },
        { n: "Umur saya dua puluh", e: "I am twenty years old", p: "OO-moor SAH-yah DOO-ah POO-looh", tokens: ["Umur", "saya", "dua", "puluh"] },
        { n: "Berapa", e: "How much", p: "buh-RAH-pah", tokens: ["Berapa"], altsE: ["how many"] },
        { n: "Jam satu", e: "One o'clock", p: "jahm SAH-too", tokens: ["Jam", "satu"] },
        { n: "Nomor lima", e: "Number five", p: "NO-mor LEE-mah", tokens: ["Nomor", "lima"] },
        { n: "Seratus orang", e: "A hundred people", p: "suh-RAH-toos OH-rang", tokens: ["Seratus", "orang"] },
      ],
    },
    {
      title: "Food",
      skill: "Order a meal",
      vocab: [
        { n: "nasi", e: "rice", p: "NAH-see", altsE: ["cooked rice"] },
        { n: "air", e: "water", p: "AH-eer" },
        { n: "kopi", e: "coffee", p: "KOH-pee" },
        { n: "teh", e: "tea", p: "teh" },
        { n: "roti", e: "bread", p: "ROH-tee" },
        { n: "ayam", e: "chicken", p: "AH-yahm" },
        { n: "ikan", e: "fish", p: "EE-kahn" },
        { n: "buah", e: "fruit", p: "BOO-ah" },
        { n: "restoran", e: "restaurant", p: "res-to-RAHN" },
        { n: "enak", e: "tasty", p: "uh-NAHK", altsE: ["delicious"] },
        { n: "pedas", e: "spicy", p: "puh-DAHS" },
        { n: "makan", e: "eat", p: "MAH-kahn" },
        { n: "minum", e: "drink", p: "MEE-noom" },
        { n: "warung", e: "small eatery", p: "WAH-roong", altsE: ["food stall"] },
      ],
      phrases: [
        { n: "Saya lapar", e: "I am hungry", p: "SAH-yah LAH-par", tokens: ["Saya", "lapar"] },
        { n: "Saya haus", e: "I am thirsty", p: "SAH-yah HOWSS", tokens: ["Saya", "haus"] },
        { n: "Saya mau kopi", e: "I want coffee", p: "SAH-yah MAU KOH-pee", tokens: ["Saya", "mau", "kopi"] },
        { n: "Ini enak sekali", e: "This is very tasty", p: "EE-nee uh-NAHK suh-KAH-lee", tokens: ["Ini", "enak", "sekali"] },
        { n: "Tidak pedas", e: "Not spicy", p: "TEE-dak puh-DAHS", tokens: ["Tidak", "pedas"] },
        { n: "Minta air putih", e: "Can I have water", p: "MIN-tah AH-eer POO-teeh", tokens: ["Minta", "air", "putih"], altsE: ["plain water please"] },
        { n: "Saya vegetaris", e: "I am vegetarian", p: "SAH-yah veh-geh-TAH-rees", tokens: ["Saya", "vegetaris"] },
        { n: "Nasi goreng dan teh", e: "Fried rice and tea", p: "NAH-see go-RENG dahn teh", tokens: ["Nasi", "goreng", "dan", "teh"] },
      ],
    },
    {
      title: "Travel",
      skill: "Find your way",
      vocab: [
        { n: "kereta", e: "train", p: "kuh-REH-tah" },
        { n: "pesawat", e: "plane", p: "puh-SAH-wat", altsE: ["airplane"] },
        { n: "hotel", e: "hotel", p: "ho-TEL" },
        { n: "stasiun", e: "station", p: "stah-see-OON" },
        { n: "bandara", e: "airport", p: "bahn-DAH-rah" },
        { n: "tiket", e: "ticket", p: "TEE-ket" },
        { n: "paspor", e: "passport", p: "PAS-por" },
        { n: "taksi", e: "taxi", p: "TAK-see" },
        { n: "jalan", e: "street", p: "JAH-lahn", altsE: ["road"] },
        { n: "kiri", e: "left", p: "KEE-ree" },
        { n: "kanan", e: "right", p: "KAH-nahn" },
        { n: "lurus", e: "straight", p: "LOO-roos" },
        { n: "peta", e: "map", p: "PUH-tah" },
        { n: "pantai", e: "beach", p: "PAHN-tai" },
      ],
      phrases: [
        { n: "Di mana stasiun", e: "Where is the station", p: "dee MAH-nah stah-see-OON", tokens: ["Di", "mana", "stasiun"] },
        { n: "Saya cari hotel", e: "I am looking for a hotel", p: "SAH-yah CHAH-ree ho-TEL", tokens: ["Saya", "cari", "hotel"] },
        { n: "Tiket ke Jakarta", e: "A ticket to Jakarta", p: "TEE-ket kuh jah-KAR-tah", tokens: ["Tiket", "ke", "Jakarta"] },
        { n: "Jauh dari sini", e: "Far from here", p: "JAH-ooh DAH-ree SEE-nee", tokens: ["Jauh", "dari", "sini"] },
        { n: "Dekat dari sini", e: "Near here", p: "duh-KAHT DAH-ree SEE-nee", tokens: ["Dekat", "dari", "sini"] },
        { n: "Belok kiri", e: "Turn left", p: "buh-LOK KEE-ree", tokens: ["Belok", "kiri"] },
        { n: "Di mana bandara", e: "Where is the airport", p: "dee MAH-nah bahn-DAH-rah", tokens: ["Di", "mana", "bandara"] },
        { n: "Saya punya paspor", e: "I have a passport", p: "SAH-yah POON-yah PAS-por", tokens: ["Saya", "punya", "paspor"] },
      ],
    },
    {
      title: "Family",
      skill: "Talk about people",
      vocab: [
        { n: "ibu", e: "mother", p: "EE-boo", altsE: ["mum", "mom"] },
        { n: "ayah", e: "father", p: "AH-yah", altsE: ["dad"] },
        { n: "kakak", e: "older sibling", p: "KAH-kak" },
        { n: "adik", e: "younger sibling", p: "AH-deek" },
        { n: "anak", e: "child", p: "AH-nak" },
        { n: "putra", e: "son", p: "POOT-rah" },
        { n: "putri", e: "daughter", p: "POOT-ree" },
        { n: "orang tua", e: "parents", p: "OH-rang TOO-ah" },
        { n: "keluarga", e: "family", p: "kuh-LOO-ar-gah" },
        { n: "teman", e: "friend", p: "tuh-MAHN" },
        { n: "saya", e: "I", p: "SAH-yah", altsE: ["me", "my"] },
        { n: "Anda", e: "you (polite)", p: "AHN-dah", altsE: ["you"] },
        { n: "suami", e: "husband", p: "SWAH-mee" },
        { n: "istri", e: "wife", p: "EES-tree" },
      ],
      phrases: [
        { n: "Ini ibu saya", e: "This is my mother", p: "EE-nee EE-boo SAH-yah", tokens: ["Ini", "ibu", "saya"] },
        { n: "Saya punya kakak", e: "I have an older sibling", p: "SAH-yah POON-yah KAH-kak", tokens: ["Saya", "punya", "kakak"] },
        { n: "Dia adik saya", e: "She is my younger sibling", p: "DEE-ah AH-deek SAH-yah", tokens: ["Dia", "adik", "saya"], altsE: ["he is my younger sibling"] },
        { n: "Kami satu keluarga", e: "We are one family", p: "KAH-mee SAH-too kuh-LOO-ar-gah", tokens: ["Kami", "satu", "keluarga"] },
        { n: "Nama ayah saya Joko", e: "My father's name is Joko", p: "NAH-mah AH-yah SAH-yah JO-ko", tokens: ["Nama", "ayah", "saya", "Joko"] },
        { n: "Dia punya dua anak", e: "She has two children", p: "DEE-ah POON-yah DOO-ah AH-nak", tokens: ["Dia", "punya", "dua", "anak"] },
        { n: "Ini teman saya", e: "This is my friend", p: "EE-nee tuh-MAHN SAH-yah", tokens: ["Ini", "teman", "saya"] },
        { n: "Putri saya berumur sepuluh", e: "My daughter is ten", p: "POOT-ree SAH-yah buh-ROO-moor suh-POO-looh", tokens: ["Putri", "saya", "berumur", "sepuluh"] },
      ],
    },
    {
      title: "Adjectives",
      skill: "Describe things",
      vocab: [
        { n: "besar", e: "big", p: "buh-SAR", altsE: ["large"] },
        { n: "kecil", e: "small", p: "kuh-CHEEL" },
        { n: "bagus", e: "good", p: "BAH-goos", altsE: ["nice"] },
        { n: "buruk", e: "bad", p: "BOO-rook" },
        { n: "panas", e: "hot", p: "PAH-nahs" },
        { n: "dingin", e: "cold", p: "DEENG-een" },
        { n: "cantik", e: "beautiful", p: "CHAN-teek" },
        { n: "baru", e: "new", p: "BAH-roo" },
        { n: "tua", e: "old", p: "TOO-ah" },
        { n: "muda", e: "young", p: "MOO-dah" },
        { n: "mudah", e: "easy", p: "MOO-dah" },
        { n: "sulit", e: "difficult", p: "SOO-leet", altsE: ["hard"] },
        { n: "mahal", e: "expensive", p: "MAH-hahl" },
        { n: "cepat", e: "fast", p: "chuh-PAT", altsE: ["quick"] },
      ],
      phrases: [
        { n: "Ini terlalu mahal", e: "This is too expensive", p: "EE-nee ter-LAH-loo MAH-hahl", tokens: ["Ini", "terlalu", "mahal"] },
        { n: "Cuacanya panas", e: "The weather is hot", p: "CHWAH-chah-nyah PAH-nahs", tokens: ["Cuacanya", "panas"] },
        { n: "Hari ini dingin", e: "Today is cold", p: "HAH-ree EE-nee DEENG-een", tokens: ["Hari", "ini", "dingin"] },
        { n: "Ini mudah", e: "This is easy", p: "EE-nee MOO-dah", tokens: ["Ini", "mudah"] },
        { n: "Kopinya bagus", e: "The coffee is good", p: "KOH-pee-nyah BAH-goos", tokens: ["Kopinya", "bagus"] },
        { n: "Dia masih muda", e: "She is still young", p: "DEE-ah MAH-seeh MOO-dah", tokens: ["Dia", "masih", "muda"] },
        { n: "Hotel kecil", e: "A small hotel", p: "ho-TEL kuh-CHEEL", tokens: ["Hotel", "kecil"] },
        { n: "Sangat cantik", e: "Very beautiful", p: "SAHNG-at CHAN-teek", tokens: ["Sangat", "cantik"] },
      ],
    },
    {
      title: "Present patterns",
      skill: "Saya + verb",
      vocab: [
        { n: "saya", e: "I", p: "SAH-yah" },
        { n: "kamu", e: "you (informal)", p: "KAH-moo", altsE: ["you"] },
        { n: "dia", e: "he / she", p: "DEE-ah", altsE: ["he", "she"] },
        { n: "kami", e: "we (not you)", p: "KAH-mee", altsE: ["we"] },
        { n: "kita", e: "we (including you)", p: "KEE-tah", altsE: ["we"] },
        { n: "adalah", e: "is / are", p: "ah-DAH-lah", note: "Often dropped in speech." },
        { n: "punya", e: "have", p: "POON-yah" },
        { n: "pergi", e: "go", p: "per-GEE" },
        { n: "sudah", e: "already", p: "SOO-dah" },
        { n: "sedang", e: "currently", p: "suh-DAHNG", altsE: ["in the middle of"] },
        { n: "akan", e: "will", p: "AH-kahn" },
        { n: "ini", e: "this", p: "EE-nee" },
        { n: "itu", e: "that", p: "EE-too" },
        { n: "ada", e: "there is", p: "AH-dah", altsE: ["have", "exist"] },
      ],
      phrases: [
        { n: "Saya mahasiswa", e: "I am a student", p: "SAH-yah mah-hah-SEES-wah", tokens: ["Saya", "mahasiswa"] },
        { n: "Kamu capek", e: "You are tired", p: "KAH-moo CHAH-pek", tokens: ["Kamu", "capek"] },
        { n: "Saya punya tiket", e: "I have a ticket", p: "SAH-yah POON-yah TEE-ket", tokens: ["Saya", "punya", "tiket"] },
        { n: "Saya pergi ke Bali", e: "I am going to Bali", p: "SAH-yah per-GEE kuh BAH-lee", tokens: ["Saya", "pergi", "ke", "Bali"] },
        { n: "Kami di sini", e: "We are here", p: "KAH-mee dee SEE-nee", tokens: ["Kami", "di", "sini"] },
        { n: "Dia di stasiun", e: "She is at the station", p: "DEE-ah dee stah-see-OON", tokens: ["Dia", "di", "stasiun"] },
        { n: "Saya sudah makan", e: "I have already eaten", p: "SAH-yah SOO-dah MAH-kahn", tokens: ["Saya", "sudah", "makan"] },
        { n: "Saya akan datang", e: "I will come", p: "SAH-yah AH-kahn DAH-tang", tokens: ["Saya", "akan", "datang"] },
      ],
    },
    {
      title: "Common verbs",
      skill: "Do the usual things",
      vocab: [
        { n: "berbicara", e: "to speak", p: "ber-bee-CHAH-rah", altsN: ["bicara"] },
        { n: "makan", e: "to eat", p: "MAH-kahn" },
        { n: "minum", e: "to drink", p: "MEE-noom" },
        { n: "ingin", e: "to want", p: "EENG-een", altsN: ["mau"] },
        { n: "bisa", e: "can", p: "BEE-sah", altsE: ["to be able"] },
        { n: "membuat", e: "to make", p: "mem-BOO-at", altsE: ["to do"] },
        { n: "datang", e: "to come", p: "DAH-tang" },
        { n: "mengambil", e: "to take", p: "meng-AHM-beel" },
        { n: "melihat", e: "to see", p: "muh-LEE-hat" },
        { n: "saya bicara", e: "I speak", p: "SAH-yah bee-CHAH-rah" },
        { n: "saya makan", e: "I eat", p: "SAH-yah MAH-kahn" },
        { n: "saya mau", e: "I want", p: "SAH-yah MAU" },
        { n: "saya bisa", e: "I can", p: "SAH-yah BEE-sah" },
        { n: "mengerti", e: "to understand", p: "meng-ER-tee" },
      ],
      phrases: [
        { n: "Saya bicara bahasa Indonesia", e: "I speak Indonesian", p: "SAH-yah bee-CHAH-rah bah-HAH-sah in-do-NEE-see-ah", tokens: ["Saya", "bicara", "bahasa", "Indonesia"] },
        { n: "Saya makan nasi", e: "I eat rice", p: "SAH-yah MAH-kahn NAH-see", tokens: ["Saya", "makan", "nasi"] },
        { n: "Saya mau air", e: "I want water", p: "SAH-yah MAU AH-eer", tokens: ["Saya", "mau", "air"] },
        { n: "Saya bisa membantu", e: "I can help", p: "SAH-yah BEE-sah mem-BAN-too", tokens: ["Saya", "bisa", "membantu"] },
        { n: "Kami naik kereta", e: "We take the train", p: "KAH-mee NA-eek kuh-REH-tah", tokens: ["Kami", "naik", "kereta"] },
        { n: "Saya minum kopi", e: "I drink coffee", p: "SAH-yah MEE-noom KOH-pee", tokens: ["Saya", "minum", "kopi"] },
        { n: "Kamu datang besok", e: "You come tomorrow", p: "KAH-moo DAH-tang BEH-sok", tokens: ["Kamu", "datang", "besok"] },
        { n: "Saya tidak mengerti", e: "I do not understand", p: "SAH-yah TEE-dak meng-ER-tee", tokens: ["Saya", "tidak", "mengerti"] },
      ],
    },
    {
      title: "Survival",
      skill: "Get unstuck",
      vocab: [
        { n: "tolong", e: "help", p: "TOH-long", altsE: ["please"] },
        { n: "pelan-pelan", e: "slowly", p: "puh-LAHN puh-LAHN" },
        { n: "toilet", e: "toilet", p: "toy-LET", altsE: ["bathroom"] },
        { n: "tersesat", e: "lost", p: "ter-suh-SAT" },
        { n: "bahasa Inggris", e: "English", p: "bah-HAH-sah EENG-greess" },
        { n: "sedikit", e: "a little", p: "suh-DEE-keet" },
        { n: "alergi", e: "allergy", p: "ah-LEHR-gee", altsE: ["allergic"] },
        { n: "rumah sakit", e: "hospital", p: "ROO-mah SAH-keet" },
        { n: "polisi", e: "police", p: "po-LEE-see" },
        { n: "buka", e: "open", p: "BOO-kah" },
        { n: "tutup", e: "closed", p: "TOO-toop" },
        { n: "hari ini", e: "today", p: "HAH-ree EE-nee" },
        { n: "sekarang", e: "now", p: "suh-KAH-rang" },
        { n: "minta maaf", e: "apologise", p: "MIN-tah MAH-af", altsE: ["sorry"] },
      ],
      phrases: [
        { n: "Saya tidak mengerti", e: "I don't understand", p: "SAH-yah TEE-dak meng-ER-tee", tokens: ["Saya", "tidak", "mengerti"] },
        { n: "Apakah Anda bisa bahasa Inggris", e: "Do you speak English", p: "ah-PAH-kah AHN-dah BEE-sah bah-HAH-sah EENG-greess", tokens: ["Apakah", "Anda", "bisa", "bahasa", "Inggris"] },
        { n: "Di mana toilet", e: "Where is the toilet", p: "dee MAH-nah toy-LET", tokens: ["Di", "mana", "toilet"] },
        { n: "Pelan-pelan tolong", e: "Slowly please", p: "puh-LAHN puh-LAHN TOH-long", tokens: ["Pelan-pelan", "tolong"] },
        { n: "Saya tersesat", e: "I am lost", p: "SAH-yah ter-suh-SAT", tokens: ["Saya", "tersesat"] },
        { n: "Saya alergi kacang", e: "I am allergic to peanuts", p: "SAH-yah ah-LEHR-gee KAH-chang", tokens: ["Saya", "alergi", "kacang"] },
        { n: "Berapa harganya", e: "How much does it cost", p: "buh-RAH-pah HAR-gahn-yah", tokens: ["Berapa", "harganya"] },
        { n: "Tolong bantu saya", e: "Please help me", p: "TOH-long BAHN-too SAH-yah", tokens: ["Tolong", "bantu", "saya"] },
      ],
    },
    {
      title: "Daily life",
      skill: "Shop and time",
      vocab: [
        { n: "hari ini", e: "today", p: "HAH-ree EE-nee" },
        { n: "besok", e: "tomorrow", p: "BEH-sok" },
        { n: "kemarin", e: "yesterday", p: "kuh-MAH-reen" },
        { n: "Senin", e: "Monday", p: "suh-NEEN" },
        { n: "toko", e: "shop", p: "TOH-ko", altsE: ["store"] },
        { n: "uang", e: "money", p: "WAHNG" },
        { n: "harga", e: "price", p: "HAR-gah" },
        { n: "cuaca", e: "weather", p: "CHWAH-chah" },
        { n: "hujan", e: "rain", p: "HOO-jahn" },
        { n: "matahari", e: "sun", p: "mah-tah-HAH-ree" },
        { n: "pagi", e: "morning", p: "PAH-gee" },
        { n: "malam", e: "night", p: "MAH-lahm" },
        { n: "gratis", e: "free", p: "GRAH-tees" },
        { n: "kembalian", e: "change (money)", p: "kem-BAH-lee-ahn", altsE: ["change"] },
      ],
      phrases: [
        { n: "Jam berapa sekarang", e: "What time is it", p: "jahm buh-RAH-pah suh-KAH-rang", tokens: ["Jam", "berapa", "sekarang"] },
        { n: "Saya mau yang ini", e: "I want this one", p: "SAH-yah MAU yang EE-nee", tokens: ["Saya", "mau", "yang", "ini"] },
        { n: "Berapa harganya", e: "How much is it", p: "buh-RAH-pah HAR-gahn-yah", tokens: ["Berapa", "harganya"] },
        { n: "Hari ini hujan", e: "It is raining today", p: "HAH-ree EE-nee HOO-jahn", tokens: ["Hari", "ini", "hujan"] },
        { n: "Tokonya buka", e: "The shop is open", p: "TOH-ko-nyah BOO-kah", tokens: ["Tokonya", "buka"] },
        { n: "Sampai besok pagi", e: "See you tomorrow morning", p: "SAHM-pai BEH-sok PAH-gee", tokens: ["Sampai", "besok", "pagi"] },
        { n: "Saya tidak punya uang", e: "I don't have money", p: "SAH-yah TEE-dak POON-yah WAHNG", tokens: ["Saya", "tidak", "punya", "uang"] },
        { n: "Ini gratis", e: "This is free", p: "EE-nee GRAH-tees", tokens: ["Ini", "gratis"] },
      ],
    },
  ],
};
