export const is = {
  id: "is",
  title: "Icelandic",
  nativeName: "Íslenska",
  mark: "IS",
  blurb: "Real þ, ð, æ, and ö. Beginner path with phonetic hints when the voice in your browser is shy.",
  speechLang: "is-IS",
  accent: "#67e8f9",
  accentDim: "#164e63",
  units: [
    {
      title: "Greetings",
      skill: "Say halló",
      vocab: [
        { n: "Halló", e: "Hello", p: "HAH-loh", altsE: ["hi"] },
        { n: "Góðan daginn", e: "Good day", p: "GOH-than DAI-yin", altsE: ["hello", "good morning"], note: "ð sounds like th in this." },
        { n: "Gott kvöld", e: "Good evening", p: "gott KVULT" },
        { n: "Góða nótt", e: "Good night", p: "GOH-tha NOHT" },
        { n: "Bless", e: "Bye", p: "bless", altsE: ["goodbye"] },
        { n: "Takk", e: "Thanks", p: "tahk", altsE: ["thank you"] },
        { n: "Takk fyrir", e: "Thank you", p: "tahk FIH-rir", altsE: ["thanks"] },
        { n: "Ekkert mál", e: "You're welcome", p: "EH-kert mowl", altsE: ["no problem"] },
        { n: "Já", e: "Yes", p: "yow" },
        { n: "Nei", e: "No", p: "nay" },
        { n: "Fyrirgefðu", e: "Excuse me", p: "FIH-rir-gev-thu", altsE: ["sorry"] },
        { n: "Ánægja", e: "Pleasure", p: "OW-nai-ya", altsE: ["nice to meet you"] },
        { n: "Ísland", e: "Iceland", p: "EES-lant" },
        { n: "þú", e: "you", p: "thoo", note: "þ is unvoiced th, as in thin." },
      ],
      phrases: [
        { n: "Hvað segirðu", e: "How are you", p: "kvath SAY-ir-thu", tokens: ["Hvað", "segirðu"] },
        { n: "Allt fínt", e: "All good", p: "ahlt FEENT", tokens: ["Allt", "fínt"], altsE: ["im fine"] },
        { n: "Ég heiti Anna", e: "My name is Anna", p: "yeh HAY-tih AH-nah", tokens: ["Ég", "heiti", "Anna"] },
        { n: "Hvað heitir þú", e: "What is your name", p: "kvath HAY-tir thoo", tokens: ["Hvað", "heitir", "þú"] },
        { n: "Ánægja að hitta þig", e: "Nice to meet you", p: "OW-nai-ya ath HIT-tah thig", tokens: ["Ánægja", "að", "hitta", "þig"] },
        { n: "Velkomin", e: "Welcome", p: "VEL-ko-min", tokens: ["Velkomin"] },
        { n: "Góða nótt", e: "Good night", p: "GOH-tha NOHT", tokens: ["Góða", "nótt"] },
        { n: "Sjáumst á morgun", e: "See you tomorrow", p: "SYOW-umst ow MOR-gun", tokens: ["Sjáumst", "á", "morgun"] },
      ],
    },
    {
      title: "Numbers",
      skill: "Count to twenty",
      vocab: [
        { n: "einn", e: "one", p: "aytn", note: "Masculine citation form." },
        { n: "tveir", e: "two", p: "tvayr" },
        { n: "þrír", e: "three", p: "threer" },
        { n: "fjórir", e: "four", p: "FYOH-rir" },
        { n: "fimm", e: "five", p: "fim" },
        { n: "sex", e: "six", p: "sex" },
        { n: "sjö", e: "seven", p: "syuh" },
        { n: "átta", e: "eight", p: "OWT-tah" },
        { n: "níu", e: "nine", p: "NEE-uh" },
        { n: "tíu", e: "ten", p: "TEE-uh" },
        { n: "ellefu", e: "eleven", p: "ET-leh-vuh" },
        { n: "tólf", e: "twelve", p: "tohlv" },
        { n: "tuttugu", e: "twenty", p: "TUT-tuh-guh" },
        { n: "hundrað", e: "hundred", p: "HUN-drath", altsE: ["one hundred"] },
      ],
      phrases: [
        { n: "Ég á tvær systur", e: "I have two sisters", p: "yeh ow tvair SIST-ur", tokens: ["Ég", "á", "tvær", "systur"] },
        { n: "Þetta kostar tíu krónur", e: "This costs ten krónur", p: "THET-tah KOS-tar TEE-uh KROH-nur", tokens: ["Þetta", "kostar", "tíu", "krónur"] },
        { n: "Einn tveir þrír", e: "One two three", p: "aytn tvayr threer", tokens: ["Einn", "tveir", "þrír"] },
        { n: "Ég er tuttugu ára", e: "I am twenty years old", p: "yeh er TUT-tuh-guh OW-rah", tokens: ["Ég", "er", "tuttugu", "ára"] },
        { n: "Hvað kostar", e: "How much does it cost", p: "kvath KOS-tar", tokens: ["Hvað", "kostar"] },
        { n: "Klukkan er eitt", e: "It is one o'clock", p: "KLUH-kahn er ayt", tokens: ["Klukkan", "er", "eitt"] },
        { n: "Númer fimm", e: "Number five", p: "NOO-mer fim", tokens: ["Númer", "fimm"] },
        { n: "Hundrað manns", e: "A hundred people", p: "HUN-drath mahns", tokens: ["Hundrað", "manns"] },
      ],
    },
    {
      title: "Food",
      skill: "Order a meal",
      vocab: [
        { n: "brauð", e: "bread", p: "broyth" },
        { n: "vatn", e: "water", p: "vahtn" },
        { n: "kaffi", e: "coffee", p: "KAH-fih" },
        { n: "te", e: "tea", p: "teh" },
        { n: "ostur", e: "cheese", p: "OS-tur" },
        { n: "epli", e: "apple", p: "EP-lih" },
        { n: "fiskur", e: "fish", p: "FIS-kur" },
        { n: "kjöt", e: "meat", p: "kyuht" },
        { n: "veitingastaður", e: "restaurant", p: "VAY-ting-a-stah-thur" },
        { n: "bragðgott", e: "tasty", p: "BRAGTH-gott", altsE: ["delicious"] },
        { n: "svangur", e: "hungry", p: "SVOWN-gur" },
        { n: "þyrstur", e: "thirsty", p: "THIRST-ur" },
        { n: "mjólk", e: "milk", p: "myolk" },
        { n: "súpa", e: "soup", p: "SOO-pah" },
      ],
      phrases: [
        { n: "Ég er svangur", e: "I am hungry", p: "yeh er SVOWN-gur", tokens: ["Ég", "er", "svangur"], note: "svöng is the feminine form." },
        { n: "Ég er þyrstur", e: "I am thirsty", p: "yeh er THIRST-ur", tokens: ["Ég", "er", "þyrstur"] },
        { n: "Ég ætla að fá kaffi", e: "I would like coffee", p: "yeh IKE-lah ath fow KAH-fih", tokens: ["Ég", "ætla", "að", "fá", "kaffi"] },
        { n: "Þetta er bragðgott", e: "This is tasty", p: "THET-tah er BRAGTH-gott", tokens: ["Þetta", "er", "bragðgott"] },
        { n: "Má ég fá vatn", e: "May I have water", p: "mow yeh fow vahtn", tokens: ["Má", "ég", "fá", "vatn"] },
        { n: "Ég er grænmetisæta", e: "I am vegetarian", p: "yeh er GRAIN-met-is-ai-tah", tokens: ["Ég", "er", "grænmetisæta"] },
        { n: "Reikninginn takk", e: "The bill please", p: "RAIK-ning-inn tahk", tokens: ["Reikninginn", "takk"] },
        { n: "Brauð og te", e: "Bread and tea", p: "broyth og teh", tokens: ["Brauð", "og", "te"] },
      ],
    },
    {
      title: "Travel",
      skill: "Find your way",
      vocab: [
        { n: "lest", e: "train", p: "lest" },
        { n: "flugvél", e: "plane", p: "FLUG-vyehl", altsE: ["airplane"] },
        { n: "hótel", e: "hotel", p: "HOH-tel" },
        { n: "lestarstöð", e: "train station", p: "LES-tar-stueth", altsE: ["station"] },
        { n: "flugvöllur", e: "airport", p: "FLUG-vut-lur" },
        { n: "miði", e: "ticket", p: "MIH-thi" },
        { n: "vegabréf", e: "passport", p: "VEH-ga-bryef" },
        { n: "leigubíll", e: "taxi", p: "LAY-gu-beetl" },
        { n: "gata", e: "street", p: "GAH-tah" },
        { n: "til vinstri", e: "to the left", p: "til VIN-strih", altsE: ["left"] },
        { n: "til hægri", e: "to the right", p: "til HAIG-rih", altsE: ["right"] },
        { n: "beint áfram", e: "straight ahead", p: "baynt OW-fram", altsE: ["straight"] },
        { n: "kort", e: "map", p: "kort" },
        { n: "strönd", e: "beach", p: "struent" },
      ],
      phrases: [
        { n: "Hvar er lestarstöðin", e: "Where is the station", p: "kvar er LES-tar-stueth-in", tokens: ["Hvar", "er", "lestarstöðin"] },
        { n: "Ég leita að hótelinu", e: "I am looking for the hotel", p: "yeh LAY-tah ath HOH-tel-ih-nuh", tokens: ["Ég", "leita", "að", "hótelinu"] },
        { n: "Miði til Reykjavíkur", e: "A ticket to Reykjavík", p: "MIH-thi til RAKE-ya-vee-kur", tokens: ["Miði", "til", "Reykjavíkur"] },
        { n: "Þetta er langt í burtu", e: "It is far away", p: "THET-tah er lahngt ee BUR-tuh", tokens: ["Þetta", "er", "langt", "í", "burtu"] },
        { n: "Þetta er nálægt", e: "It is nearby", p: "THET-tah er NOW-laigt", tokens: ["Þetta", "er", "nálægt"] },
        { n: "Beygðu til vinstri", e: "Turn left", p: "BAYG-thu til VIN-strih", tokens: ["Beygðu", "til", "vinstri"] },
        { n: "Hvar er flugvöllurinn", e: "Where is the airport", p: "kvar er FLUG-vut-lur-inn", tokens: ["Hvar", "er", "flugvöllurinn"] },
        { n: "Ég er með vegabréf", e: "I have a passport", p: "yeh er meth VEH-ga-bryef", tokens: ["Ég", "er", "með", "vegabréf"] },
      ],
    },
    {
      title: "Family",
      skill: "Talk about people",
      vocab: [
        { n: "móðir", e: "mother", p: "MOH-thir", altsE: ["mum", "mom"] },
        { n: "faðir", e: "father", p: "FAH-thir", altsE: ["dad"] },
        { n: "bróðir", e: "brother", p: "BROH-thir" },
        { n: "systir", e: "sister", p: "SIST-ir" },
        { n: "barn", e: "child", p: "bhartn" },
        { n: "sonur", e: "son", p: "SOH-nur" },
        { n: "dóttir", e: "daughter", p: "DOHT-tir" },
        { n: "foreldrar", e: "parents", p: "FOR-el-drar" },
        { n: "fjölskylda", e: "family", p: "FYUL-skil-dah" },
        { n: "vinur", e: "friend", p: "VIH-nur" },
        { n: "ég", e: "I", p: "yeh" },
        { n: "hún", e: "she", p: "hoon" },
        { n: "hann", e: "he", p: "hahn" },
        { n: "maður", e: "husband / man", p: "MAH-thur", altsE: ["man", "husband"] },
      ],
      phrases: [
        { n: "Hér er mamma mín", e: "Here is my mum", p: "hyehr er MAHM-mah meen", tokens: ["Hér", "er", "mamma", "mín"] },
        { n: "Ég á bróður", e: "I have a brother", p: "yeh ow BROH-thur", tokens: ["Ég", "á", "bróður"] },
        { n: "Þetta er systir mín", e: "This is my sister", p: "THET-tah er SIST-ir meen", tokens: ["Þetta", "er", "systir", "mín"] },
        { n: "Við erum fjölskylda", e: "We are a family", p: "vith EH-rum FYUL-skil-dah", tokens: ["Við", "erum", "fjölskylda"] },
        { n: "Pabbi minn heitir Jón", e: "My dad's name is Jón", p: "PAHB-bih min HAY-tir yohn", tokens: ["Pabbi", "minn", "heitir", "Jón"] },
        { n: "Hún á tvö börn", e: "She has two children", p: "hoon ow tvuh burdn", tokens: ["Hún", "á", "tvö", "börn"] },
        { n: "Þetta er vinur minn", e: "This is my friend", p: "THET-tah er VIH-nur min", tokens: ["Þetta", "er", "vinur", "minn"] },
        { n: "Dóttir mín er tíu ára", e: "My daughter is ten", p: "DOHT-tir meen er TEE-uh OW-rah", tokens: ["Dóttir", "mín", "er", "tíu", "ára"] },
      ],
    },
    {
      title: "Adjectives",
      skill: "Describe things",
      vocab: [
        { n: "stór", e: "big", p: "stohr" },
        { n: "lítill", e: "small", p: "LEE-titl" },
        { n: "góður", e: "good", p: "GOH-thur" },
        { n: "slæmur", e: "bad", p: "SLAI-mur" },
        { n: "heitur", e: "hot", p: "HAY-tur" },
        { n: "kaldur", e: "cold", p: "KAL-dur" },
        { n: "fallegur", e: "beautiful", p: "FAHT-leh-gur" },
        { n: "nýr", e: "new", p: "neer" },
        { n: "gamall", e: "old", p: "GAH-mahtl" },
        { n: "ungur", e: "young", p: "OONG-ur" },
        { n: "auðveldur", e: "easy", p: "OYTH-vel-dur" },
        { n: "erfiður", e: "difficult", p: "ER-vih-thur", altsE: ["hard"] },
        { n: "dýr", e: "expensive", p: "deer" },
        { n: "fljótur", e: "fast", p: "FLYOH-tur", altsE: ["quick"] },
      ],
      phrases: [
        { n: "Þetta er of dýrt", e: "This is too expensive", p: "THET-tah er ov deert", tokens: ["Þetta", "er", "of", "dýrt"] },
        { n: "Það er heitt", e: "It is hot", p: "thath er hayt", tokens: ["Það", "er", "heitt"] },
        { n: "Það er kalt", e: "It is cold", p: "thath er kahlt", tokens: ["Það", "er", "kalt"] },
        { n: "Þetta er auðvelt", e: "This is easy", p: "THET-tah er OYTH-velt", tokens: ["Þetta", "er", "auðvelt"] },
        { n: "Kaffið er gott", e: "The coffee is good", p: "KAH-fith er gott", tokens: ["Kaffið", "er", "gott"] },
        { n: "Hún er ung", e: "She is young", p: "hoon er oong", tokens: ["Hún", "er", "ung"] },
        { n: "Lítið hótel", e: "A small hotel", p: "LEE-tith HOH-tel", tokens: ["Lítið", "hótel"] },
        { n: "Mjög fallegt", e: "Very beautiful", p: "myuhg FAHT-lekt", tokens: ["Mjög", "fallegt"] },
      ],
    },
    {
      title: "Present patterns",
      skill: "Ég er, ég hef",
      vocab: [
        { n: "ég er", e: "I am", p: "yeh er" },
        { n: "þú ert", e: "you are", p: "thoo ert" },
        { n: "hann er", e: "he is", p: "hahn er" },
        { n: "hún er", e: "she is", p: "hoon er" },
        { n: "við erum", e: "we are", p: "vith EH-rum" },
        { n: "ég hef", e: "I have", p: "yeh hev" },
        { n: "þú hefur", e: "you have", p: "thoo HEH-vur" },
        { n: "ég fer", e: "I go", p: "yeh fer", altsE: ["i am going"] },
        { n: "vera", e: "to be", p: "VEH-rah" },
        { n: "hafa", e: "to have", p: "HAH-vah" },
        { n: "fara", e: "to go", p: "FAH-rah" },
        { n: "þið eruð", e: "you are (plural)", p: "thith EH-ruth" },
        { n: "þeir eru", e: "they are", p: "thayr EH-ruh" },
        { n: "ég á", e: "I own / I have", p: "yeh ow", altsE: ["i have"] },
      ],
      phrases: [
        { n: "Ég er nemandi", e: "I am a student", p: "yeh er NEH-man-dih", tokens: ["Ég", "er", "nemandi"] },
        { n: "Þú ert þreyttur", e: "You are tired", p: "thoo ert THRAYT-tur", tokens: ["Þú", "ert", "þreyttur"] },
        { n: "Ég er með miða", e: "I have a ticket", p: "yeh er meth MIH-tha", tokens: ["Ég", "er", "með", "miða"] },
        { n: "Ég fer til Reykjavíkur", e: "I am going to Reykjavík", p: "yeh fer til RAKE-ya-vee-kur", tokens: ["Ég", "fer", "til", "Reykjavíkur"] },
        { n: "Við erum hér", e: "We are here", p: "vith EH-rum hyehr", tokens: ["Við", "erum", "hér"] },
        { n: "Hún er á lestarstöðinni", e: "She is at the station", p: "hoon er ow LES-tar-stueth-in-nih", tokens: ["Hún", "er", "á", "lestarstöðinni"] },
        { n: "Þú ert mjög góður", e: "You are very kind", p: "thoo ert myuhg GOH-thur", tokens: ["Þú", "ert", "mjög", "góður"] },
        { n: "Hann er kennari", e: "He is a teacher", p: "hahn er KEN-nah-rih", tokens: ["Hann", "er", "kennari"] },
      ],
    },
    {
      title: "Common verbs",
      skill: "Do the usual things",
      vocab: [
        { n: "tala", e: "to speak", p: "TAH-lah" },
        { n: "borða", e: "to eat", p: "BOR-tha" },
        { n: "drekk", e: "drink", p: "drehk", altsN: ["drekka"], altsE: ["to drink"] },
        { n: "vilja", e: "to want", p: "VIL-yah" },
        { n: "geta", e: "to be able", p: "GEH-tah", altsE: ["can"] },
        { n: "gera", e: "to do", p: "GEH-rah", altsE: ["to make"] },
        { n: "koma", e: "to come", p: "KOH-mah" },
        { n: "taka", e: "to take", p: "TAH-kah" },
        { n: "sjá", e: "to see", p: "syow" },
        { n: "ég tala", e: "I speak", p: "yeh TAH-lah" },
        { n: "ég borða", e: "I eat", p: "yeh BOR-tha" },
        { n: "ég vil", e: "I want", p: "yeh vil" },
        { n: "ég get", e: "I can", p: "yeh get" },
        { n: "skilja", e: "to understand", p: "SKIL-yah" },
      ],
      phrases: [
        { n: "Ég tala íslensku", e: "I speak Icelandic", p: "yeh TAH-lah EES-len-skuh", tokens: ["Ég", "tala", "íslensku"] },
        { n: "Ég borða brauð", e: "I eat bread", p: "yeh BOR-tha broyth", tokens: ["Ég", "borða", "brauð"] },
        { n: "Ég vil vatn", e: "I want water", p: "yeh vil vahtn", tokens: ["Ég", "vil", "vatn"] },
        { n: "Ég get hjálpað þér", e: "I can help you", p: "yeh get HYOWL-path thyehr", tokens: ["Ég", "get", "hjálpað", "þér"] },
        { n: "Við tökum lestina", e: "We take the train", p: "vith TUH-kum LEST-ih-nah", tokens: ["Við", "tökum", "lestina"] },
        { n: "Ég drekk kaffi", e: "I drink coffee", p: "yeh drehk KAH-fih", tokens: ["Ég", "drekk", "kaffi"] },
        { n: "Þú kemur á morgun", e: "You come tomorrow", p: "thoo KEH-mur ow MOR-gun", tokens: ["Þú", "kemur", "á", "morgun"] },
        { n: "Ég skil ekki", e: "I do not understand", p: "yeh skil EH-kih", tokens: ["Ég", "skil", "ekki"] },
      ],
    },
    {
      title: "Survival",
      skill: "Get unstuck",
      vocab: [
        { n: "hjálp", e: "help", p: "hyowlp" },
        { n: "hægar", e: "slower", p: "HIGH-gar", altsE: ["slowly"] },
        { n: "klósett", e: "toilet", p: "KLOH-sett", altsE: ["bathroom"] },
        { n: "villtur", e: "lost", p: "VITL-tur" },
        { n: "enska", e: "English", p: "EN-skah" },
        { n: "svolítið", e: "a little", p: "SVOH-lee-tith" },
        { n: "ofnæmi", e: "allergy", p: "OV-nai-mih", altsE: ["allergic"] },
        { n: "sjúkrahús", e: "hospital", p: "SYOOK-ra-hoos" },
        { n: "lögregla", e: "police", p: "LUH-greg-lah" },
        { n: "opið", e: "open", p: "OH-pith" },
        { n: "lokað", e: "closed", p: "LOH-kath" },
        { n: "í dag", e: "today", p: "ee dahg" },
        { n: "núna", e: "now", p: "NOO-nah" },
        { n: "afsakið", e: "pardon", p: "AF-sah-kith", altsE: ["excuse me"] },
      ],
      phrases: [
        { n: "Ég skil ekki", e: "I don't understand", p: "yeh skil EH-kih", tokens: ["Ég", "skil", "ekki"] },
        { n: "Talarðu ensku", e: "Do you speak English", p: "TAH-lar-thu EN-skuh", tokens: ["Talarðu", "ensku"] },
        { n: "Hvar er klósettið", e: "Where is the toilet", p: "kvar er KLOH-set-tith", tokens: ["Hvar", "er", "klósettið"] },
        { n: "Hægar takk", e: "Slower please", p: "HIGH-gar tahk", tokens: ["Hægar", "takk"] },
        { n: "Ég er villtur", e: "I am lost", p: "yeh er VITL-tur", tokens: ["Ég", "er", "villtur"], note: "villt is the feminine form." },
        { n: "Ég er með ofnæmi", e: "I have an allergy", p: "yeh er meth OV-nai-mih", tokens: ["Ég", "er", "með", "ofnæmi"] },
        { n: "Hvað kostar þetta", e: "How much does this cost", p: "kvath KOS-tar THET-tah", tokens: ["Hvað", "kostar", "þetta"] },
        { n: "Geturðu hjálpað mér", e: "Can you help me", p: "GEH-tur-thu HYOWL-path myehr", tokens: ["Geturðu", "hjálpað", "mér"] },
      ],
    },
    {
      title: "Daily life",
      skill: "Shop and time",
      vocab: [
        { n: "í dag", e: "today", p: "ee dahg" },
        { n: "á morgun", e: "tomorrow", p: "ow MOR-gun" },
        { n: "í gær", e: "yesterday", p: "ee gyair" },
        { n: "mánudagur", e: "Monday", p: "MOW-nu-dah-gur" },
        { n: "búð", e: "shop", p: "booth", altsE: ["store"] },
        { n: "peningar", e: "money", p: "PEH-ning-ar" },
        { n: "verð", e: "price", p: "verth" },
        { n: "veður", e: "weather", p: "VEH-thur" },
        { n: "rigning", e: "rain", p: "RIG-ning" },
        { n: "sól", e: "sun", p: "sohl" },
        { n: "morgunn", e: "morning", p: "MOR-gunn" },
        { n: "kvöld", e: "evening", p: "kvult" },
        { n: "ókeypis", e: "free", p: "OH-kay-pis" },
        { n: "til baka", e: "change (money)", p: "til BAH-kah", altsE: ["change"] },
      ],
      phrases: [
        { n: "Hvað er klukkan", e: "What time is it", p: "kvath er KLUH-kahn", tokens: ["Hvað", "er", "klukkan"] },
        { n: "Ég ætla að fá þetta", e: "I would like this", p: "yeh IKE-lah ath fow THET-tah", tokens: ["Ég", "ætla", "að", "fá", "þetta"] },
        { n: "Hvað kostar þetta", e: "How much is this", p: "kvath KOS-tar THET-tah", tokens: ["Hvað", "kostar", "þetta"] },
        { n: "Það er rigning í dag", e: "It is raining today", p: "thath er RIG-ning ee dahg", tokens: ["Það", "er", "rigning", "í", "dag"] },
        { n: "Búðin er opin", e: "The shop is open", p: "BOO-thin er OH-pin", tokens: ["Búðin", "er", "opin"] },
        { n: "Sjáumst á morgun", e: "See you tomorrow", p: "SYOW-umst ow MOR-gun", tokens: ["Sjáumst", "á", "morgun"] },
        { n: "Ég er ekki með peninga", e: "I don't have money", p: "yeh er EH-kih meth PEH-ning-ah", tokens: ["Ég", "er", "ekki", "með", "peninga"] },
        { n: "Þetta er ókeypis", e: "This is free", p: "THET-tah er OH-kay-pis", tokens: ["Þetta", "er", "ókeypis"] },
      ],
    },
  ],
};
