import { pack } from "../../pack.mjs";

export const ART_MORE = pack("art", [
  ["vy-a-colour-constancy", "Colour", "Colour constancy is the brain naming the banana, not the photons",
    "A yellow banana in blue window light still ‘reads’ yellow. The tube colour that matches the photons may look wrong on the palette until it sits in the picture. Photographers fight this with white balance; painters mix the lie on purpose.",
    "Paint the RGB of the light and the object will look true. Cameras are honest, brains are decoration.",
    "Squint, compare a swatch to a neighbour, then mix for the picture’s world, not for the isolated patch.",
    "A phone auto-WB can flatten a sunset you were trying to keep. Know when the brain or the sensor is the boss."],
  ["vy-a-high-key", "Colour", "High key is a value neighbourhood, not a happy sticker",
    "Most of the picture lives in lights, with a few darker anchors. Impressionist mornings and some fashion photos live here. It is not ‘add yellow for joy’. Low key is the other neighbourhood (a Caravaggio room).",
    "High key means overexpose until it is artistic. Blown whites are a style called high key.",
    "Posterise to three values. If two of them are lights, you are in the neighbourhood. Keep one dark so it does not become fog.",
    "A high-key portrait that loses the drawing in the lights failed the neighbourhood, not the mood board."],
  ["vy-a-analogous-whisper", "Colour", "Analogous hues whisper; a complement is a shout you spend once",
    "Neighbours on the wheel (blue–blue-green–green) sit quietly. Drop one complementary accent and the eye parks there. A scheme of five complements is a food-court fight.",
    "Use every hue so the teacher sees you own a full set of pencils. Harmony is quantity.",
    "Pick a three-neighbour family, mix within it, then one small complement as a spark. Step back.",
    "A landscape that is only analogous greens can still fail on value. Whispering hue does not save a muddy value."],
  ["vy-a-additive-subtract", "Colour", "Lights mix toward white; pigments mix toward dirt",
    "RGB on a screen is additive. Paint and CMYK printers are subtractive (filters that eat light). A neon on a monitor can die on paper. Classroom RYB is a teaching map, not physics of a LED.",
    "Mix red and green paint to get yellow because the screen did. Media are interchangeable.",
    "Name the system before you mix. Soft-proof a print job. Do not match a phone to a gouache as a religion.",
    "A theatre gel is subtractive light. A LED wash is additive. Stage designers live on this split."],
  ["vy-a-colour-script", "Colour", "A colour script is a sequence of keys, not one pretty still",
    "Animation and comics plan mood per scene (cold open, warm crisis). A folio that is five unrelated palettes is five posters. Sequence is a design of feeling over time.",
    "Each page should invent a new wheel so the examiner sees range. Range is chaos with a smile.",
    "Paint three thumbnails of the same scene at dawn, noon, night. Keep one rule (a costume colour) so it is a script, not three films.",
    "A film still grabbed as a ‘palette’ without the shots either side is a moodboard, not a script."],
  ["vy-a-colour-culture", "Colour", "A colour code is cultural, not a universal emoji",
    "White as wedding vs white as mourning in some places. Red as luck, danger, or a party, depending. Using a sacred colour as a texture pack is a context fail. Ask, do not assume the poster-paint poster.",
    "Colours mean the same everywhere because rainbows are physics. Physics is culture.",
    "Research the audience’s code before a campaign or a class poster about a community that is not yours.",
    "A team strip is a colour code with a copyright and a riot history. Designers who ‘rebrand’ it for a meme still step in it."],
  ["vy-a-ground-leak", "Colour", "A coloured ground leaks through whether you booked it or not",
    "Imprimatura, a raw umber wash, a pink gesso. Optical greys happen when the ground peeks. A panic-cover of titanium is a different picture. Watercolour’s ‘ground’ is the paper white — a cousin lesson.",
    "Start on pure white always so colours stay pure. Toned grounds are a cheat from people who cannot mix.",
    "Tone a scrap, paint the same apple on white and on the tone, compare the speed of harmony.",
    "A digital ‘paper texture’ layer with multiply is a ground costume. It still needs the values to work."],
  ["vy-a-chroma-vs-value", "Colour", "Chroma is not the same fader as value; you can have a dark loud and a light dull",
    "A deep ultramarine can be darker than a pastel yellow and still more chromatic. Beginners darken with black and also kill chroma. Mix a dark by neighbour-and-complement, then check value separately.",
    "Darker means more colour. Black is the most colourful tube because it is serious.",
    "Make a chart: one hue, five values, three chromas. Label which fader you moved.",
    "A ‘shadow = black’ digital brush is the same fail. Sample the hue in the darks of a photo you admire."],
  ["vy-a-white-cube", "Context", "A white cube is a politics of looking, not a neutral fridge",
    "The gallery’s blank walls, hush, and plinths train a certain attention. Salon hangs and community halls train another. Pretending the room is invisible is a 20th-century style, not a law of art.",
    "White walls mean the art is pure. Colour on a wall is unprofessional always.",
    "Name the room’s rules (do not touch, a rope, a QR) and how they change the work. Then a hanging that fights the cube on purpose.",
    "A school gym show is a context. Fluoro lights and a bounce echo are materials."],
  ["vy-a-ars-copyright", "Context", "Fair dealing is a rim; a folio still needs a citation",
    "Australian copyright is automatic, has a term, and school exceptions are not ‘I am a student therefore I may reprint a Nike ad as my poster’. Transform, cite, and do not sell the copy as yours.",
    "If it is on Google Images it is public domain. Thumbnails are a licence.",
    "Check still-in-copyright, ask when you can, label studies ‘after’, and keep the commercial brief honest.",
    "A meme format is folk and still sometimes a trademark. The brief’s client cares even if the meme does not."],
  ["vy-a-artist-run", "Context", "An artist-run space is a different economy from a commercial room",
    "Volunteer labour, a short season, a risk of work that will not sit in a lounge. Commercial galleries take a cut and a bet. Neither is automatically more ‘real’. Read who paid the rent.",
    "If it is not in a famous museum it is not art yet. Gatekeepers are physics.",
    "Visit one ARI and one commercial (or their sites). Compare the wall text, the price (or lack), and who is in the room.",
    "A school gallery is an ARI cousin with a timetable. Treat the hang as a public, not a corridor dump."],
  ["vy-a-manifesto-context", "Context", "A manifesto is a context machine, not a caption you skip",
    "Futurists, a feminist tract, a design school’s ‘ten rules’. The work was often a demonstration of the text. Reading only the painting is a half-listen when the artist published a fight.",
    "Artists’ writing is extra. Pictures should not need words, therefore skip the PDF.",
    "Read one page of a manifesto, then list what the work obeys and what it cheats. Cheating can be the point later.",
    "A student statement that only lists materials is not a manifesto. A claim would help."],
  ["vy-a-classification-au", "Context", "Classification and a council permit are Australian context, not a vibe of edgy",
    "MA15+, a public mural DA, a school’s ‘appropriate for a foyer’. Pushing a boundary is a choice with a room. Shock without a thought is a genre, not automatically a critique.",
    "If it is banned it is important. If it is allowed it is decorative. Two cartoons.",
    "Name the audience (primary foyer vs a 18+ space) and design the dose. Then the paperwork if it leaves the classroom.",
    "A performance in a mall is a by-law file. The work includes the security guard."],
  ["vy-a-studio-photo-lie", "Context", "A studio photograph of a sculpture is a second artwork with lighting politics",
    "Hero lighting can make a weak form look expensive. A honest documentation shows scale, a seam, a back. Folios that only exist as glam shots are a context of Instagram, not of the object.",
    "If the photo is good the sculpture is good. Cameras confer quality.",
    "Shoot one glam and one evidence (metre stick, a ugly corner). Put both in the process page.",
    "A render that never existed as a object is a digital work — say so. Passing it off as a pour is a lie."],
  ["vy-a-who-is-we", "Context", "A wall label’s ‘we’ is a who-counts sentence",
    "‘Our landscape tradition’ can erase First Nations painting as the first landscape tradition on this continent. Pronouns in catalogues are context. Rewrite the ‘we’ and the room changes.",
    "Labels are neutral facts. Curators do not have a we. Facts do not have pronouns.",
    "Circle the we/our/the viewer. Ask who is inside. Then write a label that does not kidnap the audience.",
    "A ‘anonymous African artist’ next to a named European is a cataloguing history. Names are a politics."],
  ["vy-a-memorial-brief", "Context", "A memorial is a brief with grief in it, not a statue template",
    "Who is named, who is a number, a empty chair, a counter-memorial (a cut in the ground). Contested statues are this file still running. Tasteful bronze is a style, not a moral.",
    "Memorials should be realistic soldiers so we remember correctly. Abstraction is forgetting.",
    "Write the stakeholders, the site, and one form that is not a man-on-a-horse. Then who maintains it.",
    "A school memorial garden is a living brief. Weeds are part of the context if nobody is paid to care."],
  ["vy-a-notan-two", "Seeing", "Notan is a two-value contract: the light mass vs the dark mass",
    "Japanese design word that art rooms borrowed. If the big dark and the big light do not make a readable lockup, interior rendering will not save it. Logos live here; so do woodcuts.",
    "Notan means add a Japanese vibe. Stamp a wave and you have done it.",
    "Reduce a photo to black and white with no grey. Move the threshold until the subject reads. That map is the picture.",
    "A three-value notan is a later kindness. Start with two so you cannot hide in mid-grey soup."],
  ["vy-a-measure-pencil", "Seeing", "A pencil at arm’s length is a proportional instrument, not a vibe stick",
    "Lock the elbow, close one eye, mark a unit (the head, a bottle). Transfer the unit onto the page. Beginners change the arm length between measurements and then invent a new person.",
    "Measuring is cheating. Real artists just draw. Also: the phone’s grid is the only honest measure.",
    "One unit, three comparisons, then draw. Recheck after you have a map, not after the eyelashes.",
    "A photo you copy already flattened the measure. Life drawing is where the stick earns its rent."],
  ["vy-a-horizon-eye", "Seeing", "The horizon line is your eye height, not a line where the sky got tired",
    "Sit and the horizon drops; stand and it rises. A child’s-eye still life has a high table-edge. Furniture that ignores the shared horizon is a different building in a different world.",
    "Horizon is always the middle of the page because that is balanced. Balance is geography.",
    "Mark eye height on the wall, then the vanishing gear. Draw a chair that shares it.",
    "A drone photo has a horizon that is a map, not a standing person. Say if you stole a flying eye."],
  ["vy-a-texture-value", "Seeing", "Texture is a value pattern, not a sticker of ‘brick’",
    "Bark, hair, a knit: the eye reads light and dark specks as material. Drawing every leaf as a symbol is a map, not a look. Suggest, then a few honest edges.",
    "More tiny lines mean more realism. Count the bricks for marks.",
    "Squint until the texture becomes a value shape. Paint that, then a handful of sharp bits.",
    "A bump-map in 3D is the digital cousin. It still fails if the large form is a sack."],
  ["vy-a-binocular-flatten", "Seeing", "Two eyes give a depth the camera flattens; drawing has to fake one of those contracts",
    "Stereopsis vs a lens. A still life that looks ‘wrong’ in a photo may have been true in the room. Painters invent overlaps and size cues because the page is already flat.",
    "Trace a photo and you have seen as a human. Cameras are eyes.",
    "Close one eye, then open both, on a near cup. Note the jump. Then decide which cue you will draw (overlap, not stereo).",
    "A VR headset is a different seeing. A painting of VR is still a flat joke unless you mean the headset as a still life."],
  ["vy-a-anamorph", "Seeing", "Anamorphosis is a picture that needs a viewpoint as a material",
    "A skull in Holbein, a chalk pavement that only works from a cone. The distortion is the craft. Photographing it from the wrong spot is a different work (sometimes better, often a fail of the brief).",
    "If it looks stretched it is a mistake. Fix it in Photoshop until it is a normal skull.",
    "Set a viewing tape on the floor, draw the distortion to that eye, then test. Do not skip the tape.",
    "A logo on a sports field is anamorphosis for a camera in the roof. Designers already live here."],
  ["vy-a-afterimage-edge", "Seeing", "Stare at a hard edge and the eye leaves a ghost; that is a seeing, not a ghost story",
    "Complementary afterimages, a vibrating complement pair, a retinal fatigue. Op art farms this. If your outline ‘glows’, you may have succeeded or you may have a migraine — know the difference and take a break.",
    "If the paper glows you used cheap ink. Glow is a product defect, never a technique.",
    "Place complement bars, stare, look at white. Then decide if you want that vibration in the work.",
    "A screen at full blue at 1 am is an afterimage machine and a sleep thief. Studio health is seeing too."],
  ["vy-a-scale-cue", "Seeing", "Without a scale cue a form is a toy or a monument — you cannot tell",
    "A door, a hand, a coin, a bird. Product shots use a hand as a tactile ruler. Sculpture photos that crop the room are a magic trick, sometimes a lie for a folio.",
    "Scale is for maps and architects. Art is sizeless and eternal.",
    "Add one known object or a figure. Or crop so mystery of scale is the subject — then say so in the caption.",
    "A maquette photographed against the sky can fake a memorial. Honest process shots keep the cutting mat in frame."],
]);
