import { pack } from "../../pack.mjs";

export const BUSINESS_MORE = pack("business", [
  ["vy-b-abn-not-company", "Tax & records", "An ABN is a number, not a company costume",
    "An Australian Business Number lets you invoice and be looked up. A company is a separate legal person with ASIC. Sole traders can have an ABN and still be the human legally on the hook.",
    "If you have an ABN you are a Pty Ltd and cannot be sued as a person. Numbers are shields.",
    "Say which structure you are (sole trader, partnership, company, trust) then which numbers you actually have (ABN, ACN, TFN).",
    "An ABN lookup that is cancelled is a red flag on an invoice. Check the register before you pay a ‘supplier’."],
  ["vy-b-tfn-withhold", "Tax & records", "A TFN is how PAYG withholding knows where to send the slice",
    "Give it to an employer so they withhold correctly. Quote it to a bank for interest. It is not a student ID to paste on a group chat. Identity theft loves TFNs.",
    "A TFN is a password to the ATO you should share with anyone who pays you in cash to be helpful.",
    "Treat it like a key: employer/payroll, not a screenshot. If it leaks, follow ATO guidance, do not just hope.",
    "No TFN quoted can mean a higher withholding. That is a nudge, not a bonus for the boss."],
  ["vy-b-bas-cycle", "Tax & records", "A BAS cycle is a calendar with GST maths, not a memoir",
    "Business Activity Statements collect GST you owed vs credits, and often PAYG. Late is a penalty machine. A shoebox is not a BAS.",
    "If you issued one invoice you wait until you feel ready, then write a story to the ATO.",
    "Keep invoices that support GST credits, know your reporting cycle, and use software or a registered agent if it is above a shoebox.",
    "GST on a sale you never collected is still a cash-flow event. Terms of trade are a tax timing problem too."],
  ["vy-b-tax-invoice-rules", "Tax & records", "A tax invoice is a GST document with mandatory bits",
    "ABN, GST amount (or a statement it includes GST), who, what, a date, an identity of the invoice. A pretty PDF without an ABN is a poster.",
    "If it says Invoice at the top it is a tax invoice. Typography is law.",
    "Check the ATO’s current must-haves before you claim a credit. Under a threshold the rules are lighter — look up the threshold, do not guess.",
    "A recipient-created tax invoice is a special deal, not a DIY on every cafe receipt."],
  ["vy-b-record-five-years", "Tax & records", "Records have a keep-time; ‘I deleted the app’ is not a defence",
    "ATO expects most records for five years (the detail has rims). Cloud software you stopped paying can vanish. Export is a closing ritual.",
    "If the year is over you may burn the receipts as a ceremony. Fresh starts are spiritual.",
    "Export CSV/PDF yearly to storage you control. Name files so a stranger could audit.",
    "A lost phone with the only copy of receipts is a risk register item, not a personality."],
  ["vy-b-deduct-nexus", "Tax & records", "A deduction needs a nexus to earning the income, not a vibe of hustle",
    "Work tools can be; a new TV ‘for the vibe of the brand’ usually is not. Apportion mixed use. Students: this is not advice for your uncle’s boat.",
    "If it has a logo on the receipt it is deductible. Branding is a spell.",
    "Ask: would I still buy this if I had no income stream? Then keep the receipt and the why.",
    "A car logbook is a method. 100% business on a car that does school pickup is a story the ATO has heard."],
  ["vy-b-payg-instalment", "Tax & records", "PAYG instalments are a prepayment, not a bonus tax",
    "When you earn outside a neat wage, the ATO may want slices during the year so you do not explode at EOFY. A refund was often you lending them money.",
    "Instalments mean you are being fined in advance. Pay extra to be safe always, without reading the activity statement.",
    "Read whether you are in instalments, vary only with a reason, and keep cash for the slice.",
    "A first year of a stall that suddenly profits is how people get a surprise. A buffer is a plan."],
  ["vy-b-super-guarantee", "Tax & records", "Super guarantee is a percent of ordinary time earnings, with a due date",
    "Employers must pay SG by the quarterly deadlines into a fund. It is not a gift; it is a legal slice of remuneration. Unpaid super is a common theft with a recovery path.",
    "If it is not in the weekly envelope it is optional. Super is a vibe for old people.",
    "Check the pay slip % and the fund actually received it. The ATO unpaid super tool exists because of this path.",
    "Ordinary time earnings has a definition. Overtime treatment can surprise. Awards and the ATO page beat a group chat."],
  ["vy-b-depreciation-asset", "Tax & records", "An asset that lasts years is often depreciated, not 100% expensed as a feeling",
    "A $2000 tool might be a decline-in-value story (or an instant asset write-off if a rule says so that year — rules move). Mixing them is how a P&L lies.",
    "If you paid this year it is this year’s entire expense. Cash is accrual.",
    "Separate consumables from assets. Then the current small-business rule, not a 2015 Facebook post.",
    "A laptop for a business can be an asset. A laptop that is also Fortnite at night is apportionment again."],
  ["vy-b-audit-trail", "Tax & records", "An audit trail is who changed the number, not a neat folder only",
    "Dated invoices, sequential numbers, who approved a refund, a void with a reason. Spreadsheets with no history are a fog. POS that allows silent deletes is a risk.",
    "If the total looks right the trail is optional. Auditors like vibes.",
    "Number documents, lock dates in software, and do not edit last month in place without a reversing entry.",
    "A ‘just this once’ off-book cash job is how the trail ends and the story begins."],
  ["vy-b-stocktake", "Tax & records", "A stocktake is a count of reality vs the computer",
    "Shrinkage, a wrong receipt, a stolen box, a unit that was each vs pack. Closing stock changes profit in a periodic system. Skipping the count invents profit.",
    "The barcode system cannot be wrong. Trust the software, skip the clipboard.",
    "Count, compare, investigate the gap, then adjust with a reason code — not a silent edit.",
    "A cafe’s milk is stock too. Perishable inventory is a clock, not only a supermarket story."],
  ["vy-b-reconcile-bank", "Tax & records", "A bank reconciliation is why the books and the bank disagree on purpose",
    "Unpresented cheques (legacy), timing of a Friday EFTPOS batch, a merchant fee. Matching is a control against theft and against you double-counting a sale.",
    "If the bank app total looks like the till, you are reconciled. Screenshots are audits.",
    "Tick off each line. The leftover must have a name (in transit, a fee, a mistake). Then fix the mistake in the books or the bank, not in your head.",
    "A duplicate MYOB import is a classic. Reconciliation is how you find it before GST."],
  ["vy-b-award-coverage", "Work", "Modern awards are a coverage puzzle, not a rumour from a mate",
    "Industry and occupation classifications decide the award. A ‘hospitality vibe’ is not a classification. Misclassifying a worker is how underpayment starts.",
    "If the shop is small, awards do not apply. Small is a legal holiday.",
    "Use Fair Work’s tools to find the award, then the level, then the rate including penalties. Get it in the contract.",
    "A casual loading is not a permission to skip other minima. Loadings and penalties can stack by the document, not by a vibe."],
  ["vy-b-payslip-must", "Work", "A payslip is a legal document with must-have fields",
    "Hours, rate, super, tax, the employer. ‘I’ll Venmo you’ without a slip is a smell. Checking the slip is a work skill, not distrust as a personality.",
    "If the money landed, the slip is optional. Banks are the record.",
    "Read every new job’s first slip against the offer. Query missing super and missing hours in writing.",
    "An app screenshot of a roster is not a payslip. Different documents, both worth keeping."],
  ["vy-b-notice-period", "Work", "Notice is a two-way calendar in the contract and the NES",
    "How long you or they must give. Payment in lieu is a thing. Walking out can cost; so can a constructive dismissal file. Read the hours type (casual vs permanent) first.",
    "Casual means leave today with no words. Permanent means you are stuck forever. Two cartoons.",
    "Check NES + contract + award. Give notice in writing. Keep the email.",
    "A trial period is not a licence to skip the rules you actually signed. Names on the contract matter."],
  ["vy-b-whs-consult", "Work", "WHS consultation is a right, not a poster of a hard hat",
    "Workers must be able to have a say on hazards. A HSRs story exists in bigger workplaces. Young workers still count. A giggle at a near-miss is a culture.",
    "If you are new you do not get to stop a job. Voice is for seniors.",
    "Report the hazard, use the form, tell a supervisor, escalate if the fryer still spits. 000 if it is already an emergency.",
    "A ‘we have always done it this way’ on a unguarded blade is not a risk assessment."],
  ["vy-b-ip-at-work", "Work", "IP you make in the job may already belong to the employer",
    "Contracts often assign copyright in work product. A side hustle on the work laptop is a fog. School is different from employment — still read the assignment spec for who owns a brief.",
    "If I made it with my brain I own it, always, even in paid hours on their software.",
    "Read the IP clause before you invent on company time. Keep side projects on your own kit and time if the contract is spicy.",
    "A customer list in your pocket when you leave is a legal event, not a souvenir."],
  ["vy-b-reference-truth", "Work", "A reference is evidence, not a fiction you write for a mate",
    "Lying as a referee is a reputation and sometimes a legal problem. ‘To whom it may concern’ with inflated titles is how HR stops picking up. Ask before you name someone.",
    "Everyone inflates. It is expected. Honesty is optional in job markets.",
    "Ask a referee who saw the work. Brief them on the role. Do not ghostwrite a lie.",
    "A LinkedIn rec that contradicts the dates on a resume is a gift to a checker."],
  ["vy-b-simple-interest", "Money", "Simple interest is I = Prt; the principal does not join the party",
    "A $1000 at 5% simple for 2 years is $100 interest. Compound would add interest on interest. Personal loans and school examples still mix them on purpose as a trap.",
    "Interest is always compound because banks are fancy. Formulae are for poor people.",
    "Name simple vs compound before you compute. Write P, r as a decimal, t in years (or match the rate’s time).",
    "A 5% per month is not a 5% per year. The time unit on r must match t."],
  ["vy-b-real-vs-nominal", "Money", "A ‘real’ return has inflation taken off, roughly",
    "6% interest in a 4% inflation year is about 2% real in a school model. A high rate that loses to prices is a treadmill. CPI is a basket with arguments.",
    "If the number on the savings ad is bigger than last year you are richer. Nominal is real.",
    "Subtract (or use the slightly better formula if taught) to compare years. Then fees as another silent inflation.",
    "A wage rise of 3% in a 5% CPI year is a real cut. Politics lives here."],
  ["vy-b-diversify-not-ten", "Money", "Diversification is uncorrelated-ish eggs, not ten tech stocks you like",
    "A market, a bond mix, a geography. Ten companies that all sell ads are one egg with ten stickers. Fees in a ‘diversified’ product can still bite.",
    "Diversify by buying more of what went up last year. Winners like company.",
    "Name the risk you are spreading (a stock, a country, a sector). Then a boring index as a default story, not a hot tip.",
    "Your job is already a concentrated bet on one industry. That is why dumping all savings into the same industry is a double."],
  ["vy-b-emergency-fund", "Money", "An emergency fund is a boring cash buffer, not an investment personality",
    "Rent, a dental, a lost shift. High-interest debt usually beats ‘investing the buffer’ as a first move in simple advice. Amount is a circumstance (stable job vs casual).",
    "Emergency money should be in the spiciest shares so it grows in time for the emergency. Timing is a gift.",
    "Park it in a separate, accessible account. Do not count the holiday sinking fund as the same pile.",
    "Insurance is a cousin of the buffer, not a substitute for every small shock."],
  ["vy-b-false-economy", "Money", "A false economy is a cheap that costs more later",
    "A $10 charger that melts, a no-insurance excess, a skip-the-service on a car. Unit price is not total cost of ownership. Tradies know this; students meet it in phones.",
    "The cheapest sticker is always the rational choice. That is what efficient means.",
    "Add expected repairs, time, and risk. Then decide. Sometimes the cheap is still right.",
    "A bulk buy that spoils is a false economy with a smell. Perishables have a clock."],
  ["vy-b-dollar-cost-avg", "Money", "Dollar-cost averaging is a schedule, not a guarantee of profit",
    "Buying a fixed dollar amount regularly buys more units when the price is down. It reduces some timing regret. It does not make a bad asset good. Fees on tiny buys can wreck it.",
    "DCA means you cannot lose. The algorithm is a saint.",
    "If you use it, pick a boring diversified thing and a fee you can see. Do not DCA a meme as a personality.",
    "A lump sum in a rising market can beat DCA in hindsight. Hindsight is not a strategy you had on Monday."],
]);
