import { pack } from "../../pack.mjs";

export const CIVICS_MORE = pack("civics", [
  ["vy-ci-abc-charter", "Media", "The ABC’s charter is a statute with enemies, not a vibe of ‘government TV’",
    "A public broadcaster has a legislated job (inform, independent-ish, a national conversation). A budget cut is a civic lever. It is not a ministry newsletter, and it is not a private start-up. Both criticisms exist; the charter is the text.",
    "If the government funds it, it is state media like a dictatorship. Also: if it criticises the government it is illegitimate. Two cartoons.",
    "Read a paragraph of the charter, then a story, then who is attacking it this week and why.",
    "SBS has a different multicultural brief. Do not mash the two as ‘the ABC’."],
  ["vy-ci-media-ownership", "Media", "Who owns the masthead is a civic map, not gossip about billionaires as sport",
    "Australia’s concentrated press, a TV licence, a digital giant that is not a ‘publisher’ in the old law. Plurality is a public good in theory; the shopping list of owners is the homework.",
    "If there are many websites there is a free market of truth. Tabs are plurality.",
    "Name two owners, two outlets, and a story they would frame differently. Then a independent or a public option.",
    "A local paper bought and stripped is a civic silence. Ownership includes the emptying."],
  ["vy-ci-press-gallery", "Media", "A press gallery is a village with a pack, not the whole country",
    "Canberra proximity, a doorstop, a leak. Useful and also a hall of mirrors. Regional beats die while the gallery still has a coffee. Source-to-journalist is a relationship with a power tilt.",
    "If it is in the gallery it is the nation’s question. The bush is a colour piece.",
    "Compare a gallery lead with a local paper’s lead on the same day. The gap is the lesson.",
    "A press conference without questions is a product launch. Civics starts when a question lands."],
  ["vy-ci-foi-media", "Media", "FOI is a journalist’s spade, and a student’s too",
    "A request, a delay, a black bar, a fee. Cabinet exemptions. A dump at 4pm Friday is a tactic. The story is often in the attachment, not the cover letter.",
    "Democracies email you the secrets. FOI is a vibe for movies.",
    "Write a narrow request as a thought experiment. Then read a real released file and the redactions.",
    "A leak is a different spade, with a source to protect and a law. Do not mix the ethics."],
  ["vy-ci-talkback-frame", "Media", "Talkback is a format that selects for heat",
    "Open lines, a host’s frame, a stack of callers who survived the producer. It can surface a real complaint and also a pile-on. Outrage is a business model, not a census.",
    "If many callers agree it is public opinion. The switchboard is a random sample.",
    "Name the frame in the intro, then who never calls (a shift worker, a shy expert). Then a quieter source.",
    "A talkback campaign can still move a minister. Heat is not the same as a lie, and not the same as a poll."],
  ["vy-ci-media-literacy-ad", "Media", "Native advertising is a shop in an article costume",
    "Sponsored content, a ‘partner’ tag in 8pt, an influencer’s holiday that was a suitcase of product. Disclosure is the civic minimum, not a friendship. The ACCA/ACMA neighbourhood has moods; the skill is spotting the sell.",
    "If the photos are nice it is journalism. Nice is a method.",
    "Find the disclosure, then the claim that would be an ad on TV. Then whether a child could tell.",
    "A school’s ‘free’ educational kit from a company is a cousin. Read who paid for the worksheet."],
  ["vy-ci-whistle-media", "Media", "A whistleblower plus a journalist is a civic technology with a legal fog",
    "Public interest, a NDA, a national security stamp that can be real or a blanket. Australia’s press-freedom fights are this file. You are not the journalist; you still need the shape.",
    "Leaks are always treason, or always heroic. No remainder. Pick a team shirt.",
    "Ask what public harm was being hidden, what was verified, and who pays if it was wrong.",
    "A dump of private medical files is not a whistle. Harm to a person is not automatically a public good."],
  ["vy-ci-algorithm-square", "Media", "A feed is a private square with public effects, ranked for time-on-device",
    "Moderation is a policy, not a court. Virality is not a vote. Parliaments arguing with platforms is a 21st-century civic. eSafety is a Australian office with a controversial rim.",
    "The internet is the 1791 public square. US First Amendment law applies in a Melbourne group chat. Obviously.",
    "Read a community guideline and a statute. Then who is missing from the board that wrote the guideline.",
    "A pile-on is a crowd. A court is a court. A CEO’s Terms are a contract. Do not mix the costumes."],
  ["vy-ci-implied-rights", "Rights", "Implied political communication is a High Court carve, not a imported First Amendment",
    "Australia’s constitution does not list a bill like the US. The Court has implied a freedom of political communication with tests and rims. Schoolyard speech is not the same file as a election pamphlet.",
    "We have the First Amendment. I saw it in a clip. Therefore a teacher cannot stop a slur.",
    "Name the source (implied, statute, common law, a state charter). Then the test in a paragraph, not a meme.",
    "Lange and later cases are a syllabus neighbourhood. The rim moves. That is the point of a court."],
  ["vy-ci-disability-rights", "Rights", "Disability rights are a legal architecture, not a kindness sticker",
    "DDA, reasonable adjustment, a access standard. A ramp is a right in a setting, not a favour. Inspiration porn is a media fail. Nothing about us without us is the civic slogan that still gets skipped.",
    "If they are nice they do not need the law. Niceness is a building code.",
    "Read an adjustment (exam extra time, a caption). Then who pays and who decides ‘reasonable’.",
    "A school excursion that is ‘too hard to include’ is a design of the excursion, not a fact of the student."],
  ["vy-ci-privacy-app", "Rights", "The Privacy Act’s APPs are a costume with teeth that do not bite every small shop the same way",
    "Australian Privacy Principles, a NDB scheme for some, a OAIC. Small business exemptions exist and are a live fight. Your school login is still a data pile. ‘I have nothing to hide’ is not a legal theory that survived the 20th century.",
    "If it is free you are the product, therefore no law. Also: if it is Australian no offshore processor exists.",
    "Ask purpose, retention, who can query. Then a real breach headline and what the notice owed you.",
    "A TFN in a spreadsheet emailed to ‘the team’ is a rights event, not a admin vibe."],
  ["vy-ci-children-rights", "Rights", "The CRC is a global script; Australian kids still meet a patchwork",
    "Best interests, a voice in decisions that affect them, a age of criminal responsibility debate. Schools, a family court, a youth detention. You can have rights and still not have the microphone.",
    "Kids should be seen and not heard, or kids should run the parliament from a phone. Two cartoons, no bus timetable.",
    "List a right you have at 16 vs 18. Then a forum where you were actually heard (or not).",
    "A youth advisory group that cannot change a budget is pedagogy. Say whether the domain was real."],
  ["vy-ci-work-rights-fw", "Rights", "Fair Work is a rights shop for a job, not a vibe of the boss’s mood",
    "NES, awards, a general protections, a unfair dismissal rim (and casuals, and a small business). Cash-in-hand under the floor is not a flex. Young workers are a known target.",
    "If you are new you have no rights. Also: if you are casual the law is a myth.",
    "Keep the contract, the roster, the slip. Use Fair Work’s tools. A union is a technology you can still refuse — know the cost.",
    "A ‘trial’ that is a Saturday of unpaid real work is a smell with a name."],
  ["vy-ci-indigenous-rights", "Rights", "Native title and a Voice debate are different tools; neither is a vibe of 1788 closed",
    "Mabo, a Native Title Act, a ILUA, state treaty processes, a 2023 referendum result that is a civic fact. Closing the Gap is a report card, not a vibe. Sovereignty claims sit beside statute.",
    "It was settled. Civic file closed. Also: one poster of dots is the whole rights story.",
    "Use legal words and community words. Do not flatten 250+ peoples into one logo.",
    "A local Land Council is a civic institution. Find it on a map before a speech."],
  ["vy-ci-charter-state", "Rights", "Some states and territories have human rights charters; the Commonwealth still mostly does not",
    "Victoria, ACT, Queensland as classroom examples. Dialogue models vs a US strike-down myth. A charter can make a public authority consider rights without copying Hollywood civics.",
    "Australia has no rights because there is no bill. Also: we have all the US ones by cultural osmosis.",
    "Name your jurisdiction’s tool (or the gap). Then a case in a paragraph.",
    "A ‘statement of compatibility’ on a bill is a paperwork that can be a habit or a fight. Read one."],
  ["vy-ci-consumer-acl", "Rights", "The ACL is a consumer rights statute, not a Yelp mood",
    "Guarantees, a misleading claim, a unfair contract term neighbourhood, ACCC as a cop with a budget. A subscription trap is a design the law is catching in chunks. Keep the receipt.",
    "Caveat emptor, full stop. Reviews are the only regulator.",
    "Name the guarantee (acceptable quality, a refund path). Then a tribunal vs a tweet.",
    "A fake review is a different file from a angry true one. Speech vs a lie as a commercial weapon."],
  ["vy-ci-icc-politics", "World", "The ICC is a court of last resorts with a politics of who joins",
    "Genocide, war crimes, a complementarity idea (home courts first). Great powers that stay out. Australia’s relationship is a file, not a poster. It is not a world police that arrests a PM on a Tuesday.",
    "The ICC runs the planet, or the ICC is a hoax. Two loud takes, no statute.",
    "Name a jurisdiction, a case (or a refusal), and who did not sign. Then why a victim group might still want it.",
    "A domestic war-crimes inquiry is a different tool. Both can exist. Neither is a movie."],
  ["vy-ci-who-who", "World", "WHO is a technical agency of the UN, not a world health cabinet",
    "Guidelines, a PHEIC, a politics of China/US funding fights, a pandemic treaty argument. Advice is not an Australian statute until Canberra says so. Public health is still mostly states and a CMO.",
    "WHO can lock your suburb. That is why people fear it. Or: ignore it because it is useless. Two cartoons.",
    "Separate a guideline, a treaty, and a state public-health order. Then who you vote for if you hate the order.",
    "A pandemic is a world file with a local hospital. The agency did not build the ICU. The budget did."],
  ["vy-ci-nato-not-us", "World", "NATO is a treaty club Australia is not a member of; AUKUS is a different club",
    "Article 5 is a famous sentence. Australia’s alliances (ANZUS, AUKUS, a quad as a vibe) are a different map. Borrowing NATO memes for the Pacific is a civics fail.",
    "All Western acronyms are the same army. Flags are decoration.",
    "Place ANZUS, AUKUS, NATO, UN peacekeeping on a Venn. Then what a treaty actually obliges.",
    "A visiting US marine in Darwin is a alliance geography. It is not NATO. Names matter."],
  ["vy-ci-sanctions", "World", "Sanctions are a foreign policy tool with a grocery bill",
    "Targeted vs comprehensive, a SWIFT neighbourhood, a humanitarian carve-out that may fail. They can punish a elite or a population. Australia sometimes follows, sometimes leads a smaller list.",
    "Sanctions are war, or sanctions are a polite email. No remainder.",
    "Ask who is targeted, who actually pays (a import, a remittance), and a exit condition.",
    "A secondary sanction can hit a Australian bank that touched a dollar. That is why ‘just don’t trade’ is naive."],
  ["vy-ci-climate-cop", "World", "A COP is a theatre with a text, not a thermostat knob",
    "NDCs, a consensus culture, a walk-out, a fossil-fuel lobby in the pavilion. Paris is a architecture of pledges. Domestic law is where the tonne moves. Youth strikes are a civic, not a substitute statute.",
    "If they flew there the climate file is fake. Also: a pledge is a tonne. Two cartoons.",
    "Read one Australian NDC sentence, then a domestic policy (a safeguard, a rebate). Then the gap.",
    "A loss-and-damage fund is a justice claim with a budget fight. Pacific states are not a backdrop."],
  ["vy-ci-imf-worldbank", "World", "IMF and World Bank are banks with a politics, not a charity tin",
    "Conditionality, a structural adjustment history, a vote share that tracks money. Development is a contested word. A loan can be a lifeline and a leash.",
    "They are a world government of economists, or they are saints of GDP. Pick a conspiracy.",
    "Follow a country case in a paragraph: why the loan, what the conditions, who protested.",
    "A Australian contribution is a budget line. You can argue it without a cartoon of the building."],
  ["vy-ci-diplomatic-bag", "World", "Diplomacy is a quiet machine: immunity, a note, a expulsion",
    "Vienna conventions, a embassy as a legal island-ish, a consular help for a citizen in a mess. Spies sit in the same building in the movies; the civic file is still the convention. A tweet is not a demarche.",
    "Ambassadors are party hosts. Treaties are parties. Also: they run the other country.",
    "Name immunity’s rim (a crime, a persona non grata). Then what a ordinary passport gets you (not much, sometimes a phone number).",
    "A dual citizen in trouble is a nightmare of which embassy. Status is a civic, not a feeling about the flag."],
  ["vy-ci-global-supply-civ", "World", "A supply chain is a civic of other people’s labour law",
    "A shirt, a phone, a modern slavery statement that can be a PDF of fog. Australian firms have reporting duties; enforcement is a mood. Cheap is a geography of a wage.",
    "If I cannot see the factory it is not my civic file. Distance is innocence.",
    "Read a modern slavery statement for a brand you wear. Then a union or a NGO that disagrees.",
    "A boycott is a tool with a aftermath (a worker sacked). Strategy is more than a story."],
]);
