import { pack } from "../../pack.mjs";

export const DIGITAL_MORE = pack("digital", [
  ["vy-d-ratio-human", "Civility extras", "A ratio is still a pile of humans, not a weather of the app",
    "Likes, a quote-tweet pile, a team’s ‘ratio’d’. Each is a person with a bus to catch. Designing for the ratio is how a classroom becomes a colosseum. You will not finish the internet.",
    "If the number is big the people are a statistic. Statistics cannot be cruel. Also: if my team ratio’d them they deserved it.",
    "Wait, ask if you would say it to a face, then whether a pile-on has a off-ramp. Screenshot is a publication.",
    "A school discord ‘L’ spam is a ratio in a hoodie. The target still has a Monday."],
  ["vy-d-quote-context", "Civility extras", "A quote-tweet without the rest of the thread is a court with a crop",
    "The dunk is easy when the setup is missing. Charity is linking the whole, then the because. A 2014 joke in a 2026 costume is a time machine with a pitchfork.",
    "If it looks bad in the quote it is bad. Crops are truth. Also: always quote to dunk, never to understand.",
    "Open the original, read two either side, then decide if you still need a public. A DM can be a first step.",
    "A screenshot of a screenshot is a game of telephone with extra JPEG. Go to the URL."],
  ["vy-d-subtweet-fog", "Civility extras", "A subtweet is a fog of war in a friend group",
    "Plausible deniability plus a audience that knows. It can be a safety tactic and also a coward’s pile-on. If they would not recognise themselves, you may still have painted a third person.",
    "Indirect is always kinder. Kindness is fog. Also: if they know, they deserved the fog.",
    "Say it to them, or drop it. If it is a public interest, name the public interest, not a riddle.",
    "A close-friends story that is a subtweet still leaks. Assume thirty people and a teacher."],
  ["vy-d-tone-text", "Civility extras", "A text has no face; you will invent one and often invent a villain",
    "Punctuation, a leftover-read receipt, a ‘k’. Hanlon’s razor vs a real snub. Voice notes and a walk still exist. Workplace chat is a genre with a different k.",
    "If they used a full stop they are angry. Grammar is emotion. Always. Also: if they used a emoji they are fine, case closed.",
    "Assume a tired writer first. Then ask. Then a call if the stakes are a friendship or a job.",
    "A teacher’s short email is often a time poverty, not a hate. Reply to the ask, not the imagined face."],
  ["vy-d-banter-consent", "Civility extras", "Banter needs a ongoing yes; a group chat is not a comedy club with a door",
    "In-jokes that punch down, a nickname that stuck after a no, a roast of a body. Comedy has a rim. ‘It’s just banter’ is a claim, not a solvent.",
    "If they laughed once they licensed the rest of the year. Laughter is a contract in perpetuity.",
    "Watch the quiet person. Stop at a pause. Do not make a third party the show.",
    "A screenshot of the ‘banter’ in a pastoral care meeting is a predictable sequel. Write as if that meeting exists."],
  ["vy-d-apology-public", "Civility extras", "A public apology is for a public harm; a private harm wants a private first",
    "A performance of sorry that is a brand rehab is a genre. A real one names the act, not the victim’s ‘being offended’. Do not @ the person into a second pile so you can look grown.",
    "A story post with a sad song is an apology. Aesthetics are ethics. Also: never apologise, doubling down is authenticity.",
    "Ask who was hurt, who needs to hear it, and whether a public would re-harm. Then the change, not a synonym of sorry.",
    "A forced apology in assembly can be a ritual without a repair. Repair is the boring bit (a deleted file, a corrected rumour)."],
  ["vy-d-lurk-ok", "Civility extras", "Lurking is allowed; demanding a take is a labour tax",
    "Not every feed needs your essay. A ‘why are you quiet’ in a fight is a recruitment. Rest is a civic of attention. Amplifying is a choice with a receipt.",
    "If you saw it you must speak. Silence is violence always, in every group chat, including a cake poll.",
    "Decide if you have a add, a expertise, or a relationship. If not, scroll. If yes, be specific.",
    "A teacher who wants every student to comment on a traumatic post is a labour. Opting out can be the healthy digital."],
  ["vy-d-mod-queue", "Civility extras", "A slow mod queue is a room with a fire and a volunteer on a bus",
    "Report, do not pile the volunteer. Appeal without a brigade. Making a second channel to ‘keep the bit’ after a ban is a sequel with a name (evasion). Schools have a parallel process.",
    "If mods are slow the community should do street justice. Speed is fairness. Also: mods are the problem, always, if they touched my joke.",
    "Use the report button, keep evidence, escalate to a adult if it is a school space. Do not raid.",
    "A raid from another server is a organised harm. ‘It’s a raid lol’ is a confession, not a defence."],
  ["vy-d-block-tool", "Civility extras", "Block and mute are tools, not a proof you lost the argument",
    "You do not owe a debate to a stranger who is a firehose. Mute is a volume knob; block is a door. A campaign of ‘look they blocked me therefore they are guilty’ is a theatre.",
    "Only cowards block. Real citizens argue until the heat death of the universe. Also: block everyone who disagrees, including a teacher’s feedback.",
    "Use the tool, tell a trusted adult if it is a campaign, and do not scrape a workaround (a fake account) as a hobby.",
    "A block evasion to keep insulting is a harassment, not a free-speech TED talk."],
  ["vy-d-receipts-ethics", "Civility extras", "Receipts are a archive with a ethics; a 2012 chat is not automatically a 2026 trial",
    "Keep evidence of a threat. Do not keep a humiliation as a trading card. Context dies; the JPEG does not. Under-18 sexual images are a bright legal line — never collect, never share.",
    "If I have the screenshot I own the person. Archives are power without a rim. Also: delete everything always, including a threat you should have reported.",
    "Store threats for a adult/police path. Delete the pile-on material you do not need. Do not trade receipts as social capital.",
    "A leaked private photo of a classmate is a incident, not a ratio opportunity. Tell a adult."],
  ["vy-d-url-anatomy", "Info extras", "A URL is a sentence; the host is the who, not the path’s pretty words",
    "https://bank.example/secure looks like a bank if you cannot read. The host is example, not bank. A padlock is encryption to someone, not a identity. Phishing lives in the who.",
    "If it says the bank in the path or the logo it is the bank. Paths are names. Also: a padlock means safe content, not a safe someone.",
    "Read the host right-to-left a little (the registrable domain). Hover before you tap. Type the known address when money is involved.",
    "A lookalike rnicrosoft is a famous cousin. So is a extra hyphen. Slow is a skill."],
  ["vy-d-date-stamp", "Info extras", "A date on a story is a claim; a undated ‘breaking’ is a costume",
    "Old footage, a new caption, a crisis that already had a ending. Reverse image, then a reliable timeline. Recycled disasters are a genre.",
    "If it is in my feed it is today. Algorithms are clocks. Also: if it is old it cannot still be true, so skip history.",
    "Find the original timestamp, then whether the claim was updated. Wikipedia’s history tab is a cousin skill.",
    "A ‘this morning in Sydney’ with a Dallas skyline is a geography fail you can catch with a landmark search."],
  ["vy-d-primary-click", "Info extras", "Click through to the primary; a card is a trailer",
    "A social card, a Google snippet, a AI overview. They drop the ‘not’, the sample size, the later correction. The paper, the Hansard, the judgment is the adult.",
    "If the snippet is punchy the article is punchy and true. Trailers are the film.",
    "Open the thing. Search for the number in the page. If it is not there, the card lied.",
    "A paywall is a access problem, not a proof of quality. A free primary (a ABS table, a bill) still beats a viral graphic."],
  ["vy-d-correlation-share", "Info extras", "A chart that went viral can still be two lines with no mechanism",
    "Correlation, a chopped axis, a per-capita missing. Share the method, not only the coloured line. If you cannot say why they move together, you have a poster.",
    "If two lines move together the first caused the second. Colour is causation. Also: if they did not, the chart is fake, always, even when the method is honest.",
    "Ask n, per-what, a third gear, a axis start. Then whether you should still share.",
    "A ‘my suburb vs crime’ map without a population denominator is a classic. Density of people is not density of evil."],
  ["vy-d-expert-conflict", "Info extras", "An expert with a conflict is still a expert plus a interest; name both",
    "A funded study, a inventor of the drug, a think-tank with a donor. Dismissal because of the funder and worship because of the title are both shortcuts. The methods still sit there.",
    "If they were paid the claim is false. Money is a truth-function. Also: if they have a title the claim is true, money is a smear.",
    "Read the disclosure, then the design (a control, a n). Then a unfunded replication if it exists.",
    "A school assignment that only googles ‘expert says’ is a celebrity. Name the field and the paper."],
  ["vy-d-satire-tag", "Info extras", "Satire that travels without the tag becomes a testimonial",
    "The Onion, a local Facebook clown, a deep-voice ‘news’. People share the bit they wanted. A later ‘it was a joke’ does not un-send the pile-on.",
    "If it is funny it cannot be harmful. Humour is a solvent of civic duty. Also: if it is labelled satire it cannot contain a real smear.",
    "Check the outlet, the about page, a second source for the factual bit. Then share the joke as a joke if you still want.",
    "A satire of a private person is a different ethics from a satire of a minister. Power is the rim."],
  ["vy-d-wiki-talk", "Info extras", "A Wikipedia talk page is a argument you can read; the article is a truce",
    "Citations, a lock, a tag that says [citation needed]. The article is not a source for a serious footnote — the footnote is. A edit war is a weather, not a halo of truth.",
    "If it is on Wikipedia it is settled. Also: Wikipedia is useless, never open it, only a influencer’s carousel.",
    "Read the lead, then a cited source, then the talk if the page is spicy. Use it as a map.",
    "A biography of a living person has a stricter policy. That is why some gossip dies there and lives on a forum."],
  ["vy-d-ai-citation", "Info extras", "A chatbot citation can be a plausible ghost; the paper may not exist",
    "Hallucinated titles, a real author with a fake year, a quote from a book that does not contain it. Use the machine as a index, then open the thing. School assessments that ban a uncited model are a integrity file.",
    "If the bot named a journal it read the journal. Names are libraries. Also: if it is confident it is right. Confidence is a metric of truth.",
    "Search the title in quotes. If zero hits, you were sold a ghost. Then a human source.",
    "A invented case citation in a legal-ish essay is a professional suicide later. This is the cheap lesson."],
  ["vy-d-location-history", "Privacy extras", "A location history is a memoir you did not mean to write",
    "Timeline features, a photo GPS, a subway tap-on as a cousin. A shared album of a house plus a live pin is a map for a stranger. Turn off what you do not use; export then delete if you are leaving a platform.",
    "If I am not famous my map is boring, therefore private. Boring is encryption. Also: live location for a whole weekend is romance, not a file.",
    "Check the history setting, strip EXIF before a house photo, share a pin for a window then stop.",
    "A ‘find my friend’ that never ends is a control. Consent is a timer."],
  ["vy-d-app-permissions", "Privacy extras", "A permission is a door; a torch that wants contacts is a story",
    "Least privilege: location while using, not always; no contacts for a game. A ‘deny’ that breaks the one feature is information. Re-check after a update that re-asks.",
    "If it is in the store the permissions are fine. Stores are ethics. Also: allow all so it works, privacy is a later coat.",
    "Install, deny extras, test the actual job. Then a uninstall if the job was a lie.",
    "A school iPad MDM may take choices off the table. That is a workplace, not a personal phone. Different door."],
  ["vy-d-password-reuse-school", "Privacy extras", "A reused school password is a skeleton key to the rest of a life",
    "If the canteen app and the email and the old forum share a string, one leak is a tour. A manager plus unique plus MFA on the mail is the adult pattern. SMS reset on the same mail is a side door.",
    "Change one letter per site so you can remember. Memory is a algorithm. Also: the school password is already public in a group chat, so reuse is fine.",
    "Unique secrets, a manager the school allows, MFA where it exists. Rotate on a breach mail, not on a folk Friday.",
    "A shared ‘class login’ on the projector is a civic of passwords. Change it after the lesson if it was a real account."],
  ["vy-d-cloud-link", "Privacy extras", "A cloud link with ‘anyone’ is a publication, not a group-chat whisper",
    "Docs, a folder of IDs, a assignment with a other student’s marks in the margin. Link-sharing defaults are a product decision. Search engines sometimes still find the anyone.",
    "If the URL is long it is a secret. Length is a lock. Also: if it is a school tenant it cannot leak, tenants are vaults.",
    "Share to named people, un-anyone the old links, check the preview card that shows the first paragraph.",
    "A ‘view only’ still copies. Do not put a TFN in a doc you ever anyone’d. The anyone had a afternoon."],
  ["vy-d-old-account", "Privacy extras", "A abandoned account is a time capsule with a password from Year 7",
    "Old Tumblr, a game, a forgotten shop. Data brokers and a breach mail will still find it. Delete or export, then a unique password if you keep it. A deadname in a old profile is a extra file for some people.",
    "If you do not use it, it is gone. Servers forget. Also: keep everything forever in case of nostalgia, with the same password, as a museum.",
    "Search your username, log in or reset, delete the pile, then a password manager on what remains.",
    "A ‘download your data’ is a memoir that can include a location history. Read the zip before you post the zip."],
  ["vy-d-public-wifi-session", "Privacy extras", "A cafe Wi-Fi is a shared hallway; a leftover login is a souvenir for the next stranger",
    "Captive portals, a HTTP page, a session cookie on a borrowed laptop. VPN is a shift of trust, not a invisibility cloak. Log out, do not save the password on the library PC.",
    "If it asked for a email to get Wi-Fi it is a private network. Portals are firewalls. Also: HTTPS means the cafe cannot see anything, including the fact you used it.",
    "Prefer your data, use HTTPS sites, log out of the mail, and do not bank on a public PC as a habit.",
    "A charging USB in a bus is a data conversation that can pretend to be a power point. Charge from a brick if you can."],
]);
