import { pack } from "../../pack.mjs";

export const GEOGRAPHY_MORE = pack("geography", [
  ["vy-g-pilot-survey", "Fieldwork", "A pilot survey is a dress rehearsal that should change the script",
    "Ten people, a confusing question, a clipboard that dies in rain. You fix the instrument before the real n. Skipping the pilot is how you collect 80 useless ticks.",
    "A pilot is a small study you publish as the real one if it looks pretty. n is a vibe.",
    "Run a tiny version, rewrite the ambiguous item, then collect. Write what you changed in the eval.",
    "A leading question that survives the pilot is a design choice. Change it or own it as a bias."],
  ["vy-g-stratified-sample", "Fieldwork", "A stratified sample is a deliberate mix, not a vibe of fairness",
    "If the street is 70% shoppers and 30% workers at 4 pm, a random grab at the station at 8 am is a different population. Strata (age, time, land use) keep the mix honest-ish.",
    "Interview whoever makes eye contact. Eye contact is a random number generator.",
    "Name the strata, the quota, and the time window. Then who you still missed (night shift, a language).",
    "A quota that only finds friends in your year level is a convenience sample in a costume."],
  ["vy-g-field-weather-log", "Fieldwork", "The weather on the day is a variable, not a moan in the intro",
    "Wind wrecks a sound-level meter; rain wrecks a foot-count; glare wrecks a photo of a slope. Log it with a time. Otherwise you compare a sunny Saturday to a Tuesday squall and call it land use.",
    "Weather is background. Real geographers ignore it because place is eternal.",
    "Record wind, precipitation, and temperature band. Then say how it bent the data.",
    "A wind-exposed dune vs a leeward carpark is a microclimate. Your hoodie is not the instrument."],
  ["vy-g-consent-clipboard", "Fieldwork", "A clipboard does not cancel consent",
    "School surveys of strangers still need a script, an opt-out, and no photos of faces for a poster without permission. ‘It is for geography’ is not a warrant.",
    "Public street means public data. Faces, names, a kid in the shot — all fine if the assignment is due.",
    "Read the school’s ethics slip. Ask, record a yes, offer a skip. Store paper so it cannot wander.",
    "A QR code on a pole is still a collection. Privacy law does not care that you are in Year 10."],
  ["vy-g-bipolar-scale", "Fieldwork", "A bipolar semantic scale is two poles, not a 1–10 mood",
    "Safe———unsafe, with a middle. People park in the middle when the poles are vague. Define the poles with a place photo if you can.",
    "Ask ‘rate the vibe 1–10’ and average it. Vibe is SI.",
    "Anchor both ends in words the respondents share. Pilot whether five points was actually three because nobody uses 1 or 5.",
    "A mean of 3.2 on a 5-point is not a law. Show the spread. A bimodal ‘love/hate’ street will hide in a mean."],
  ["vy-g-annotation-not-arrow", "Fieldwork", "An annotated photo is a claim per arrow, not a pretty collage",
    "Each label should name a process or a decision (swash, a no-stopping sign, a fetch). A sticker that says ‘nice view’ is a postcard.",
    "More arrows mean more geography. Cover the image.",
    "Three to six labels, each a sentence in miniature. Then a caption with place, date, direction of view.",
    "A drone shot without a scale or a north is a poster. Add one known length if you can."],
  ["vy-g-chi-square-feel", "Fieldwork", "A simple significance test is a caution, not a trophy",
    "If you learned χ² or a similar test, it asks whether your counts are surprising under a boring model. A p-sticker without the method is cargo cult. n=8 is still a story.",
    "If the graph looks different it is significant. Eyes are p-values.",
    "State the null in English, the n, and whether the sample was biased. Then the test as a maybe.",
    "A ‘proves my hypothesis’ sentence from one beach on one Tuesday is the classic overclaim."],
  ["vy-g-site-access", "Fieldwork", "Access is a geography: gates, tides, and a risk form",
    "A site you cannot stand on is not a site. Private land, a sacred place, a cliff, a king tide. The method includes the no.",
    "If it is on Google Street View you may stand in the traffic island. Digital access is physical access.",
    "Check tide, permission, and the risk assessment’s ‘do not’. Pick an alternative transect before the bus leaves.",
    "A ‘we stood on the median strip’ photo is a method and a near-miss. Do not copy it for style."],
  ["vy-g-secondary-date", "Fieldwork", "A census table is fieldwork’s cousin with a date stamp",
    "ABS, a council GIS, a 2016 vs 2021 comparison. Using 1991 data for a 2026 claim is a time machine accident. Secondary still needs a method sentence.",
    "If it is official it is current. Government numbers do not age.",
    "Write the year, the geography (SA2 vs LGA), and what the question actually asked. Then the gap your boots fill.",
    "A Wikipedia infobox is not the ABS. Trace the table to the cell."],
  ["vy-g-eval-bias-self", "Fieldwork", "Evaluation includes your own shoes",
    "You counted bikes because you like bikes. You surveyed at lunch because that was when the bus came. Reflexivity is not a confession; it is a variable.",
    "Bias is what other students have. Your data is clean because you were careful.",
    "Name one selection bias, one measurement bias, and what you would do with another day.",
    "A group member who filled three clipboards in the same cafe is a reliability event. Report it."],
  ["vy-g-contour-index", "Maps", "Index contours are the bold lines; the interval is a legend number",
    "If the interval is 10 m, five spaces between index lines is 50 m. Counting lines without the interval is a ritual. A close packing is a steep, not a high.",
    "More contour lines always means higher above sea level, even if they are loosely spaced on a plateau cartoon.",
    "Read the interval, find a labelled index, then count. Spot-height numbers beat guessing.",
    "A depression contour with hachures is a hole, not a hill. The ticks point down."],
  ["vy-g-chloropleth-class", "Maps", "A choropleth is a classing argument painted on polygons",
    "Equal interval vs quantile vs a natural break will recolour the same data. Darker is not ‘more true’. Small LGAs next to huge outback polygons lie about intensity.",
    "The darkest shade is the worst place. Colour is morality.",
    "State the classification, the per-what (per km², per 1000 people), and the date. Then a cartogram as a rival if area misleads.",
    "Choropleth vs chloropleth: the spelling is choro- (area). Pedants will still love you if the classes are honest."],
  ["vy-g-gnomon-shade", "Maps", "A north arrow is a claim; a grid north may disagree with the arrow on your phone",
    "Map north, magnetic north, true north. A 2024 declination is not your grandparent’s. Bushwalking with a 1980s map and a 2020s phone mix is a bearing error.",
    "The top of the page is always north. Printers know.",
    "Check the north indicator and the declination note. Then whether you are measuring from grid or mag.",
    "An upside-down tourist map of the CBD is a design. It is still a map with a north, even if it hides it."],
  ["vy-g-toponym-politics", "Maps", "A place name on a map is a political layer",
    "Uluru/Ayers Rock, a dual name, a colonial overwrite, a spelling fight. Gazetteers lag. Using only the tourist name can be a choice with a history.",
    "The official name is the first English one. Dual names are optional flavour.",
    "Check a current gazetteer and the local preference. Then say which name you are using and why.",
    "A street named for a squatter is a landscape of memory. Toponymy is geography, not decoration."],
  ["vy-g-isoline-interval", "Maps", "Isolines join equals; the interval is the resolution of the story",
    "Contours, isobars, isohyets. Interpolation between lines is a guess with a rule. A 50 m contour will miss a 40 m cliff that a 10 m interval would show.",
    "If there is no line, the value is zero. Blank paper is data.",
    "Read the interval, then whether the line is labelled. Do not invent a peak from a single ring without a spot height.",
    "Crossing isolines would mean two values at one point. If they cross, someone drew a road."],
  ["vy-g-map-projection-area", "Maps", "Mercator inflates the high latitudes; that is a classroom politics",
    "Greenland vs Africa is the poster. Navigation loved rhumb lines; choropleths of people often should not. Projection is a choice of which lie you can live with.",
    "Mercator is wrong, therefore all maps are propaganda, therefore none can be used. Also: Mercator is true because Google used it.",
    "Name the property you need (area, angle, distance from a point). Then pick a projection that keeps that one.",
    "A classroom Gall–Peters fight is a start. Equal-area is not ‘the moral projection’ for a street directory."],
  ["vy-g-sketch-map-scale", "Maps", "A field sketch map still needs a scale and a north, even if ugly",
    "A mud-map without a scale is a memory. One paced length, a north, and three labels will beat a pretty but lying drawing.",
    "Sketch maps are exempt from map rules because they are sketches. Art class owns them.",
    "Pace a 10 m, mark N, locate two landmarks. Then the land-use colours with a legend.",
    "A north arrow drawn from a phone that has not calibrated is a confident error. Check two methods."],
  ["vy-g-monsoon-top-end", "Australia", "The Top End’s wet is a monsoon system, not ‘it rains in summer everywhere’",
    "Darwin’s build-up, a northwest wet, a dry that is actually dry. The same month in Hobart is a different machine. Latitude plus a seasonal wind reversal.",
    "Australia has one climate: hot. Rain is random because the continent is feral.",
    "Use a climate graph for Darwin vs Alice vs Hobart. Then name the driver (monsoon, subtropical high, a mid-latitude front).",
    "A cyclone is a guest of the wet season, not a synonym for it. Category is wind; flood is rain plus tide plus a catchment."],
  ["vy-g-murray-mouth", "Australia", "The Murray’s mouth is a political geography of water, silt, and a barrage",
    "Upstream extraction, a mouth that can silt shut, Coorong stress, and a basin plan with states as characters. A river is not only a line on a junior map.",
    "Rivers always reach the sea with the same water they had at the source. Conservation of river-ness.",
    "Follow a megalitre claim, a state border, and the mouth’s health as a metric. Then an Indigenous water story as a rights layer.",
    "The Snowy Scheme rewired a catchment for power and irrigation. It is an engineering geography with winners and a drowned town."],
  ["vy-g-urban-heat-au", "Australia", "An Australian heatwave is a suburb of roofs as much as a BOM max",
    "Western Sydney’s baked plain, a lack of canopy, a brick overnight that does not cool. The CBD canyon vs a fibro belt. Heat deaths are a geography of housing and age.",
    "Heat is the same in a park and a carpark because the air is the air. Microclimates are a myth.",
    "Map land surface, canopy, and a night minimum. Then who has air-con and who takes a bus.",
    "A black playground at 2 pm is a planning choice. Shade is infrastructure."],
  ["vy-g-great-barrier-catch", "Australia", "The Reef is a seaward geography with a farm catchment behind it",
    "Coral, a bleaching temperature, and sediment/nutrient from the coastal plain. A ‘save the reef’ sticker that ignores the Burdekin is a half-map.",
    "The Reef is a postcard off Cairns. Land use inland is a different subject (agriculture).",
    "Link a flood plume, a Crown-of-thorns neighbourhood, and a marine park zone. Then tourism as an economy that needs the biology.",
    "Traditional Owner sea Country sits under the postcard. Joint management is a geography of law."],
  ["vy-g-mining-pilbara", "Australia", "The Pilbara is a mineral landscape with a FIFO clock and a Country file",
    "Iron ore, a port, a rail, a camp that is not a town in the old sense. Native title, a rock art province, and a boom-bust housing spike in Karratha.",
    "Mines are holes in empty land. Empty is a surveyor’s word for ‘I did not count people’.",
    "Map the ore, the port, the labour source (Perth–FIFO), and a water/Country constraint.",
    "A royal flying doctor and a 40°C shift are the body geography. WHS is not optional colour."],
  ["vy-g-migration-au-map", "Australia", "Australia’s population map is a coastal clinging with a policy history",
    "A few metro blobs, a sparse interior, a White Australia unwind, a humanitarian intake, and a points test. Where people may live is also a visa and a rent.",
    "People live where they like. The map is a personality test of the nation.",
    "Use a population cartogram vs a land area map. Then a visa class and a suburb of first settlement.",
    "A ‘Big Australia’ debate is a geography of infrastructure lag, not only a fertility number."],
  ["vy-g-bushfire-interface", "Australia", "The urban–bush interface is a planning geography of fire",
    "A ridgeline house with a view is a fuel plus a wind. Black Saturday and later seasons rewrote codes. Stay-or-go is a decision science with a graveyard.",
    "Bushfire is a natural event that cannot be planned. Houses are innocent.",
    "Map vegetation, slope, access roads, and a last-season burn. Then the warning system as a communication geography.",
    "Indigenous fire knowledge is a management file, not a mascot. Cultural burning is not a cartoon of ‘let it all burn’."],
]);
