import { pack } from "../../pack.mjs";

export const HEALTH_MORE = pack("health", [
  ["vy-he-herd-threshold", "Public extras", "Herd immunity is a threshold maths, not a mood of the suburb",
    "If enough people are immune, chains of infection die out. The number depends on how contagious (R). Your personal ‘I never get sick’ is not the threshold.",
    "If my friends are fine, the herd is fine. Friendship is epidemiology.",
    "Use the schedule, catch-up with a GP, and do not treat other people’s medical records as a vibe.",
    "A disease with a higher R needs a higher coverage. Measles is picky that way."],
  ["vy-he-notifiable", "Public extras", "A notifiable disease is a public-health telegram, not a rumour mill",
    "Labs and doctors notify so outbreaks can be seen. Privacy still exists; the point is action (a school letter, a prophylaxis) not a Facebook hunt.",
    "If it is notifiable you should post the name in the year-level chat. Transparency means a pile-on.",
    "Follow official letters, get the recommended check, and leave diagnosis to clinicians.",
    "Food poisoning clusters are a classic notify-and-trace. The cafe is a geography; the lab is the evidence."],
  ["vy-he-wash-hands-soap", "Public extras", "Soap plus time beats a dab of cold water as a public control",
    "20-ish seconds, after toilet, before food, after sport spit. Sanitiser is a backup for clean-looking hands; it fails on some gut bugs and on dirt. Schools are a mixing bowl.",
    "If hands look clean they are clean. Shine is sterility. Also: sanitiser is a personality and replaces sinks.",
    "Wash with soap, dry on something that is not a shared towel from 2004, then eat.",
    "A norovirus season laughs at alcohol gel. Soap and the stay-home-if-you-are-a-fountain rule."],
  ["vy-he-stay-home-rule", "Public extras", "A feverish sports carnival is a public-health own-goal",
    "Stay-home guidance exists because heroes seed the next week’s absences. Coaches who praise ‘playing through’ a flu are running a lab.",
    "If you can stand you can play. The team needs you more than the year-level needs lungs.",
    "Follow the school’s current rule, tell a parent, do not share a water bottle as a bonding ritual.",
    "A mask on a commute when you must travel and are still leaking is a courtesy. It is not a political costume in this path."],
  ["vy-he-fluoride-water", "Public extras", "Water fluoridation is a population dental tool with a dose",
    "A small amount in many supplies reduces decay at scale. It is not toothpaste in the tap. Conspiracy content will still find you; the dental data is boring and large.",
    "Fluoride is a plot. Also: more is always better, so extra tablets on fluoridated water as a flex.",
    "Use fluoridated toothpaste as labelled, spit don’t rinse if that is the current dental advice you were taught, and leave tap chemistry to the water authority.",
    "Bottled water may not have the same fluoride. That is a label, not a purity trophy."],
  ["vy-he-needle-stick", "Public extras", "A found needle is a do-not-touch, then an adult, then a protocol",
    "Parks, a bus, a beach. Do not recap, do not play dares. Blood-borne risk is why there is a procedure and sometimes a clinic window.",
    "Kick it into a bush so kids cannot see it. Helpful. Also: pick it up with fingers to be a legend.",
    "Warn others, tell a teacher/council, follow first-aid if a puncture happened (encourage bleed, wash, 000/GP/hospital as directed by current advice).",
    "This path is not a how-to for using needles. It is a found-object safety."],
  ["vy-he-smoke-secondhand", "Public extras", "Second-hand smoke is other people’s lungs as a shared air",
    "Cars, a courtyard, a concert. There is no safe cute amount as a public-health slogan for kids. Vape aerosol is not water as a brand story either.",
    "If I am not the one smoking it is a smell only. Physics of rooms is optional.",
    "Outdoor air, a distance, indoor bans as a law you can actually use. Do not get in the car with a cloud as a personality test.",
    "A ‘smoking area’ upwind of a playground is a design fail. Geography of air."],
  ["vy-he-sunsmart-uv", "Public extras", "The UV index is the boss, not the temperature app",
    "A 22°C clear day can still burn. Clouds cut some UV, not all. Slip slop slap slide seek is still the liturgy. Melanoma is not only an old farmer’s disease.",
    "If it is cool you cannot burn. UV is heat. Also: a base tan is a shield.",
    "Check UV, cover at peak, SPF on leftover skin, hats that actually shade ears. Recheck after sweat.",
    "A burnt scalp parting is a classic. So is the top of the feet in sandals at a carnival."],
  ["vy-he-food-recall", "Public extras", "A food recall is a supply-chain brake, not a rumour to ignore",
    "FSANZ/state pages, a batch code, a supermarket sign. Keeping the packet is how you know if you are in the batch. Social media is a lagging, messy copy.",
    "If you already ate it and feel fine the recall is theatre. Also: throw every brand in the fridge as a panic.",
    "Match the batch, stop eating it, follow the official what-to-do (return, a GP if symptoms they name).",
    "Allergens mislabelled are a recall class that can be a timer for someone else in the house."],
  ["vy-he-mental-health-first", "Public extras", "Mental health first aid is listen, don’t fix, get the adult",
    "You are not the clinician. Stay, take them seriously, do not swear secrecy if safety is on the line. Kids Helpline 1800 55 1800, school counsellor, 000 if in danger.",
    "A mate’s crisis is a secret you keep to be loyal. Loyalty beats 000.",
    "Listen, ask if they are safe, tell a trusted adult with them if you can. Do not diagnose from a TikTok.",
    "This path does not teach therapy tricks. It teaches you are not alone with someone else’s emergency."],
  ["vy-he-vaccine-record", "Public extras", "An immunisation record is a document, not a family memory",
    "Australian Immunisation Register, a school requirement in some states, a catch-up plan. ‘Mum thinks I had it’ is not a batch number.",
    "If you had a sore arm once you are covered for life against everything. Memory is a register.",
    "Get the statement, see a GP for gaps, keep a copy for enrolments.",
    "Some diseases need boosters. Childhood is not a permanent force field."],
  ["vy-he-mosquito-arbovirus", "Public extras", "A mosquito is a public-health vector, not only a picnic nuisance",
    "Ross River, Japanese encephalitis in some seasons/places, dengue as an imported/local story. Stagnant water is urban design. Repellent and screens are tools.",
    "If you are tough, bites are character. Vector-borne is a tropical myth that cannot happen in Australia.",
    "Tip water, cover up at dusk in risk areas, follow local alerts after floods.",
    "A flood year is a mosquito year. Disaster recovery includes the insects."],
  ["vy-he-fitt-balance", "Movement", "FITT is a recipe: frequency, intensity, time, type — not a hero day",
    "A balanced week mixes aerobic, strength, and skill. Seven identical max sessions is a narrative and a stress fracture application. Progressive means small steps.",
    "FITT means go hard every letter. Intensity can replace rest because maths.",
    "Plan the week, include a rest or an easy, and match type to the goal (not only sweat).",
    "PE’s beep test is one component. It does not measure a back squat or a dance skill. Qualify ‘fit’."],
  ["vy-he-cool-down-point", "Movement", "A cool-down is a landing, not a second training block",
    "Pulse down, easy movement, then stretch if that is the session’s plan. Skipping straight to a cold bus in a sweat is a cramp neighbourhood for some. Evidence on stretch has moods; the landing still matters.",
    "Cool-downs are optional folklore. Champions shower in ice immediately, always.",
    "Five easy minutes, water, clothes that are not wet cotton in a wind. Then the bus.",
    "A static stretch as the entire warm-up then a sprint is still the old costume. Order matters."],
  ["vy-he-cross-training", "Movement", "Cross-training is a second pattern so the first one does not eat you",
    "A runner who only runs meets a shin. A swimmer’s shoulder from only swimming. Variety is load management, not a personality failure of focus.",
    "Specialise at 13 with one sport every day so you are elite. Variety is for amateurs.",
    "Add a complementary session (strength, a different cardio) and keep one rest. A coach who forbids all else is a risk file.",
    "Early specialisation and burnout are a research neighbourhood. Fun is a retention tool."],
  ["vy-he-hygiene-sport", "Movement", "Shared jumpers and a team bottle are a culture plate",
    "Tinea, a staph, a cold. Wash kit, your own drink, do not share a mouthguard. The win does not need a petri dish.",
    "Sweat is sterile. Sharing is caring, biologically.",
    "Personal bottle, wash gear, cover broken skin, sit out if you are a fountain of droplets.",
    "A wrestling mat without a clean is a famous skin-story. Equipment is a public-health object."],
  ["vy-he-periodisation-pe", "Movement", "Periodisation is planned tired, not accidental wrecked",
    "Blocks of load, then recover, then a peak if you have a carnival. Random hero weeks are how you arrive at the final already cooked.",
    "If you feel fine, add 40%. Feeling is a periodisation app.",
    "Write the week’s hard/easy. Sleep is part of the plan. Pain that alters gait is a stop.",
    "A taper is a reduce before the event. It is not laziness. Coaches who taper by yelling are not tapering."],
  ["vy-he-skill-vs-fitness", "Movement", "A skilled mover can still be ‘unfit’ on a beep test, and the reverse",
    "Coordination, timing, a game sense. Fitness components do not transfer 1:1. PE that only ranks beep scores misses the dancer and the goalkeeper.",
    "The fittest person on the test should captain every skill. Numbers are talent.",
    "Train the thing you will be assessed on, and still respect other components. Do not sneer.",
    "A wheelchair athlete’s fitness is real in a different chassis. Modify the test; do not skip the person."],
  ["vy-he-rumination-loop", "Mind", "Rumination is a loop that feels like work and is not a plan",
    "Replaying the fail without a next step. A worry dump on paper, then a scheduled ‘think time’, can help some people. It is not a moral failure to need a stop ritual.",
    "If you think about it harder at 1 am it will resolve. Insomnia is a strategy.",
    "Write the worry, one action for tomorrow, then a wind-down. Tell an adult if the loop owns the week.",
    "This is not CBT certification. A GP/psychologist is the professional loop-cutter."],
  ["vy-he-social-media-social", "Mind", "A like is a thin social; a body next to you is a different nervous system",
    "DMs can help and can also be a pile-on. Isolation plus a feed is a known sour mix. One in-person thing (sport, a club, a walk with a human) is a health tool.",
    "Friends online are the same as lunch. The brain cannot tell. Therefore skip people.",
    "Keep the feed, add a real-world repeat appointment. Mute the tax accounts.",
    "A parasocial bond with a creator is not a substitute GP or a substitute friend in a crisis."],
  ["vy-he-perfection-procrast", "Mind", "Perfectionism and procrastination often share a house",
    "If it cannot be perfect it does not start. A 40% draft is a health intervention for the mind. Marks are not worth a shutdown.",
    "High standards are always healthy. Exhaustion is a trophy of care.",
    "Set a ugly-first version with a timer. Hand in a complete B rather than a missing A.",
    "A teacher would rather a draft they can help than a vanishing student. Email is allowed."],
  ["vy-he-comparison-class", "Mind", "A class rank is a narrow slice of a person, not a worth",
    "Someone else’s ATAR path, body, or family money is not your control panel. Comparison can motivate a bit and then poison. Unfollow the tax; ask for help with the skill.",
    "If they can, you must, on the same timeline, with the same brain and house. Fairness is identical starting blocks.",
    "Name one controllable (a study block, a sleep) and one that is not (their tutor). Talk to a human if the rank owns your mood.",
    "Feeds hide the tutor, the luck, and the edit. That is a media-health overlap."],
  ["vy-he-anger-as-data", "Mind", "Anger is a signal that a boundary or a fairness got hit",
    "It can be true information and still need a non-violent outlet. Punching a locker is a WHS file. Naming it beats leaking it on a teammate who is not the cause.",
    "Anger is always toxic. Swallow it. Also: anger is always authentic so smash. Two cartoons.",
    "Pause, name the hit, pick a legal action (a complaint, a run, a conversation). 000 if it is already violence.",
    "A coach who uses humiliation as fuel is a culture you can still refuse to copy."],
  ["vy-he-grief-not-linear", "Mind", "Grief is not a five-box worksheet you complete for a tick",
    "Loss (a person, a team, a move). Waves, not a staircase. Friends who vanish because they are awkward are common; one who stays is gold. Schoolwork can wobble; tell a teacher.",
    "If you are still sad after a week you are doing it wrong. Stages are a deadline.",
    "A trusted adult, a counsellor, rituals that are yours. There is no correct speed.",
    "Other people’s ‘they would want you to…’ can be kindness or a rush. You can decline the rush."],
]);
