import { pack } from "../../pack.mjs";

export const HISTORY_MORE = pack("history", [
  ["vy-h-1918-flu", "Twentieth century extras", "The 1918 influenza was a wartime pandemic, not a footnote to the guns",
    "It travelled on troopships and trains, killed in waves, and hit young adults hard. Censorship and morale hid numbers at first. Australia’s maritime quarantine is a local chapter.",
    "The Spanish flu was Spanish because it started in Spain. Names are origins.",
    "Tie it to movement of people, a second wave worse than the first in many places, and public-health tools that look familiar (masks, halls).",
    "‘Spanish’ stuck because Spain’s press was less censored. Origin stories are still argued. The nickname is a media fossil."],
  ["vy-h-versailles-1919", "Twentieth century extras", "Versailles was a treaty pile, not a single German bill",
    "Fourteen Points vs a French security hunger vs a British Empire still hungry. War guilt, reparations, and a League with missing teeth sat in one package. Historians still fight how far it ‘caused 1933’.",
    "Versailles was only a huge invoice, and invoices cause dictators automatically. No other 1920s file exists.",
    "Read who was in the room (not Germany as an equal), what was signed, and what was unenforced. Then the 1920s economy as a second actor.",
    "Australia signed as a separate dominion voice. That is a status story, not only a European one."],
  ["vy-h-suffrage-waves", "Twentieth century extras", "Women’s suffrage was a long fight with an unequal prize",
    "New Zealand 1893, some Australian women 1902 (with a racist exclusion of many First Nations people), Britain 1918/1928 in stages. A vote is not the same as equal pay or a seat in the house.",
    "Women got the vote because the war proved they could work, and then history was finished.",
    "Date a jurisdiction, name who was still excluded, then a later rights fight (work, law, body).",
    "Vida Goldstein and a 1903 Senate run are an Australian thread. Suffrage was not only a London story."],
  ["vy-h-great-depression-au", "Twentieth century extras", "Australia’s 1930s were a wool-and-debt crash, not only a Wall Street postcard",
    "Export prices collapsed, unemployment soared, Premiers’ Plan fights, and dole camps. Lang vs Lyons is a political knife. Recovery was uneven and a later war demand helped.",
    "The Depression was an American mood that Australians watched in cinemas. We were fine because we had sheep.",
    "Track a price (wool, wheat), a government choice (deflation vs spend), and a street (evictions, a riot).",
    "The ‘susso’ and a rabbit on the menu are social history. GDP is the other zoom."],
  ["vy-h-nuremberg-law", "Twentieth century extras", "Nuremberg was a legal machine for racial persecution, not a rally only",
    "1935 laws defined who counted as Jewish under the regime and stripped citizenship rights. Bureaucracy plus ideology. The Holocaust has a legal paper trail as well as killing sites.",
    "Nazism was only street thugs. Laws were a later decoration. Also: it was just speeches.",
    "Read a clause, then a consequence for marriage, work, and belonging. Then 1938 as an escalation, not a beginning from nowhere.",
    "A definition on paper is how a state makes a target. Other regimes have used similar tools. Compare with care, do not flatten."],
  ["vy-h-pearl-then-home", "Twentieth century extras", "Pearl Harbor was a US hinge; Australia already had a Pacific war",
    "7 December 1941 pulled the US in. Japan’s war in China was older; Malaya and the north of Australia were already in the blast radius. Curtin’s ‘look to America’ is a speech with a context.",
    "WW2 in the Pacific starts at Pearl Harbor because Hollywood starts there.",
    "Place 1937, 1941, 1942 (Singapore, Darwin) on one line. Then whose ‘start’ you are using.",
    "Darwin’s bombing in February 1942 is an Australian home-front fact that still surprises people raised on a Europe-only map."],
  ["vy-h-un-1945", "Twentieth century extras", "The UN was a 1945 redesign, not a League with a new logo",
    "Security Council vetoes, a General Assembly, and specialised agencies. It was built by winners with a memory of failure. Human rights language sat beside empire that had not yet died.",
    "The UN began as a world government. National governments became ceremonial.",
    "Name an organ, a veto, and a 1945 hypocrisy (colonies, a racial order). Then a later success that was real and small.",
    "Australia was a founding member with Evatt at San Francisco. Middle-power story, not a spectator."],
  ["vy-h-wind-of-change", "Twentieth century extras", "Decolonisation was a wind with a timetable and a body count",
    "Macmillan’s 1960 speech named a trend already running: India 1947, Ghana 1957, a scramble of flags. Settler colonies, wars (Algeria, Kenya, Vietnam as a related imperial unwind), and a Cold War sponsor hunt.",
    "Empires ended because Europeans got nice. Flags lowered themselves.",
    "Pick one transfer of power, who negotiated, who was excluded, and whether it was a war. Then the settler leftover (Australia, South Africa) as a different clock.",
    "The Commonwealth is a sequel with a crown and a club. It is not the empire continuing by law, and it is not nothing."],
  ["vy-h-berlin-wall-1961", "Twentieth century extras", "The Berlin Wall was a border through a city, built to stop a drain",
    "1961: GDR haemorrhaging people west. A wall, then a shoot-to-kill order, then 1989 as a crowd and a misstated press conference. It was never ‘just a symbol’ if you lived beside it.",
    "The Wall was built by the West to keep communists out. Hollywood sometimes implies this.",
    "State who built it, why (labour and legitimacy), and what 1989 undid. Then two Germanys as an economic file too.",
    "Checkpoint Charlie is a tourist fossil. The ordinary street that ended in concrete is the social history."],
  ["vy-h-cuban-1962", "Twentieth century extras", "The missile crisis was a nuclear bargaining week with extra actors",
    "Soviet missiles in Cuba, US missiles in Turkey as a quieter twin, a quarantine/blockade word fight, and luck in a submarine. Kennedy and Khrushchev were not the only names (Castro, advisers, a U-2).",
    "It was a movie about nerves in a room, and the bravest speech won. Missiles are props.",
    "Map the island, the range, the deal that was public vs the deal that was quiet. Then near-misses as a safety lesson.",
    "Australia’s alliance sat in the fallout radius of a US–Soviet fight. ANZUS is a context, not a trigger."],
  ["vy-h-1973-oil", "Twentieth century extras", "The 1973 oil shock was a cartel plus a war plus a way of life",
    "OPEC embargo politics after the October war, prices jumping, queues, and a stagger of Western growth. It also pushed nuclear and coal stories, and a new inflation politics.",
    "Petrol got expensive because stations are greedy. Cartels are a myth.",
    "Connect a Middle East war, a shipping of crude, and a suburban car dependence. Then stagflation as the economic costume.",
    "Australia felt it in prices and in a later resources boom story. Energy security became a civic word."],
  ["vy-h-internet-public", "Twentieth century extras", "A public internet is a 1990s hinge, not a 1969 magic",
    "ARPANET is a ancestor; Tim Berners-Lee’s web is a 1989/91 layer; browsers and commercial ISPs made a public. 1990s Australia got a dial-up soundtrack. This is infrastructure plus a culture, not one inventor myth.",
    "Al Gore invented it, or the US military did in a weekend, and then history was online.",
    "Separate packet networks, the web, and the always-on phone. Date the layer you mean.",
    "A 1995 homepage is a primary source now. Treat it like a pamphlet: dated, partial, precious."],
  ["vy-h-silence-in-source", "Skills extras", "A silence in a source is evidence of a power, not a nothing",
    "Who is not named, not photographed, not allowed to speak on the record. Census categories, a redacted file, a woman’s initial. Absence can be the finding.",
    "If it is not in the archive it did not happen. Archives are the universe.",
    "Ask who could write, who was counted, who was a problem to be managed in the margin. Then a later oral history as a counter-file.",
    "First Nations people listed as a tally and not a name is a silence with a policy. The skill is naming that."],
  ["vy-h-museum-argument", "Skills extras", "A museum caption is an argument with a budget",
    "What is on the plinth, what is in the cupboard, whose voice is first. Repatriation fights are history happening now. A ‘neutral’ label is a style, not a vacuum.",
    "Museums store truth in glass. The object speaks and the caption is furniture.",
    "Read the label, then who funded the show, then what is missing. A contested object is a seminar.",
    "A stolen artwork returned is a civic act. So is a refusal. Both are historical claims."],
  ["vy-h-periodisation", "Skills extras", "A period name is a handle, not a border fence",
    "‘Interwar’, ‘postwar’, ‘the long 19th century’ — they leak. People lived across the handles. A 1946 ration book is still a war story.",
    "If the textbook chapter ends, the era ended at midnight. People reset their personalities.",
    "State the handle, then one continuity that ignores it, then why the handle is still useful for a question.",
    "Decade branding (the Sixties) is a marketing of a minority’s experience sometimes. Ask whose sixties."],
  ["vy-h-quantify-with-care", "Skills extras", "A death toll is a claim with a method",
    "Counts of famine, massacre, and pandemic are fought because records were bad, political, or both. A range can be more honest than a fake precise. Denial also loves a ‘we cannot know’.",
    "If historians disagree on a number, all numbers are fake and the event is optional.",
    "Show the range, the sources (burial, census, a perpetrator’s list), and who benefits from the low vs high.",
    "Holodomor, Holocaust, Nanjing, a frontier massacre in Australia — different files, same skill: method before meme."],
  ["vy-h-film-as-source", "Skills extras", "A feature film is a secondary argument in costume",
    "Gallipoli (1981) is a 1980s Australia talking about 1915. Use it for myth and mood, then a diary for the mud. Anachronism is a tell; so is a missing group.",
    "If the uniforms look right, the history is right. Costume departments are archives with PhDs.",
    "Date the production, name the myth it serves, then a primary source that complicates it.",
    "A documentary is also an argument. Voiceover is a thesis. Credits are a bibliography you should actually read."],
  ["vy-h-compare-then", "Skills extras", "Comparison needs a third thing: the question",
    "Gallipoli and the Western Front; 1789 and 1917 — compare along a axis (violence, legitimacy, who eats). A list of differences is not yet analysis.",
    "Compare means decide which was worse as a moral Olympics. History is a ranking show.",
    "Write the axis first (cause of collapse, role of cities, a gender file). Then evidence on both sides of the axis.",
    "A ‘similarities and differences’ table without a why is a worksheet fossil. Add the because."],
  ["vy-h-eight-hour-day", "Rights & everyday", "The eight-hour day was a slogan with a union timetable",
    "Stonemasons in Melbourne 1856 are a famous Australian claim: 8 hours work, 8 rest, 8 what-you-will. Reality for many workers stayed longer. A slogan can still move a law later.",
    "Everyone always worked nine-to-five until phones ruined it. The eight-hour day is a natural number.",
    "Place the 1856 march, who was excluded (women, Chinese workers, First Nations, farm labour), then a later award system.",
    "Labour Day as a public holiday is a memory technology. A gig roster can still laugh at the slogan."],
  ["vy-h-ration-book", "Rights & everyday", "A ration book is a state in your pantry",
    "WW2 Australia: coupons, a black market, a fairness claim, and a woman doing the queue. It is economic history you can hold. Class still leaked through.",
    "Rationing meant nobody could buy anything. Shops closed for the duration.",
    "Read a coupon’s rules, then a diary of substitution (rabbit, a mended sock), then who cheated.",
    "Clothing coupons made fashion a civic file. A ‘make do and mend’ poster is propaganda and also a skill."],
  ["vy-h-suburb-fibro", "Rights & everyday", "A fibro belt is a postwar social policy you can still drive through",
    "War service homes, a quarter-acre (as a myth and a lot), Holden in the drive, women often pushed back from the wartime job. The suburb is an archive of class and race (who got the loan).",
    "Suburbs just happen when people want trees. No Housing Commission, no bank redline, no policy.",
    "Pick a street type, a loan scheme, and who was not offered the keys. Then a later critique (sprawl, women’s isolation).",
    "A migrant hostel to a brick veneer is a 1950s–70s plot. Not every plot got the veneer."],
  ["vy-h-tv-1956", "Rights & everyday", "Television arrived as a Melbourne Olympic guest and then rearranged the evening",
    "1956 broadcast, a set in the lounge, ads, and a shared schedule. Politics learned a new face (a later Whitlam/Kerr clip culture). It did not kill radio overnight.",
    "When TV arrived, people stopped talking and history became American. Local content was a rumour.",
    "Date the tech, then a program that was a civic event (a royal tour, a game, a disaster), then who could not afford a set yet.",
    "The ABC and later SBS are policy, not only channels. A multicultural broadcast is a 1970s civic invention."],
  ["vy-h-equal-pay-1969", "Rights & everyday", "Equal pay decisions were stages, not a magic 1969 wand",
    "Arbitration cases, a 1969 ‘equal pay for equal work’ that still left women’s jobs classified as lesser, 1972 expanding, and a gap that survived as a structure. Law plus labour market plus care work.",
    "In 1969 every woman instantly earned the same as a man in the next chair. The case closed the file.",
    "Read what the decision actually covered, then award classifications, then unpaid care as the leftover.",
    "First Nations women and migrant women sat in a different labour market again. ‘Women’ is not a single wage series."],
  ["vy-h-green-ban", "Rights & everyday", "A green ban was unions refusing to build on a contested place",
    "Jack Mundey and the BLF in 1970s Sydney: The Rocks, Kelly’s Bush. Heritage and environment as a labour tactic. Developers called it wrecking; residents often called it survival.",
    "Unions only ever fought wages. Trees are a middle-class hobby with no history of work.",
    "Name a site, the union lever (no labour), and who asked for the ban. Then the later heritage law as a sequel.",
    "A green ban is not a general strike. It is a targeted no. That is why it could work and why it made enemies."],
]);
