import { pack } from "../../pack.mjs";

export const LANGUAGES_MORE = pack("languages", [
  ["vy-l-minimal-pair-drill", "Sounds", "A minimal pair is a gym for a contrast your ear was not trained on",
    "ship/sheep, bit/beat, a Japanese r/l neighbourhood for some learners. You are not broken; you are trained. Isolation, then a sentence, then a noisy cafe.",
    "If you cannot hear it, it is not a real difference. Your first language is the human default.",
    "Record both, label, shuffle, test. Then put the pair in a phrase you actually need (a ticket window).",
    "A pair that is not minimal (cat/catch) trains something else. Keep the rest of the word still."],
  ["vy-l-schwa-weak", "Sounds", "Schwa is the unstressed English star; spelling will not warn you",
    "About, support, the second syllable of ‘photograph’ vs ‘photography’ as a stress shift that also moves vowels. Learners who pronounce every vowel as a spelling letter sound ‘over-clear’ and foreign — which can still be fine, and still is not the street.",
    "Every written vowel is a full colour. Schwa is laziness. Also: schwa is optional decoration.",
    "Mark stress, then squint the other vowels toward a mid-central. Listen to a slow then a fast clip.",
    "A spelling pronunciation of a place name (Melbourne, Leicester) is a tourist tell. Locals ate the vowels."],
  ["vy-l-voice-onset", "Sounds", "Aspiration and voicing are different levers; English p in pin is a puff",
    "Voice onset time: p vs b is not only ‘vocal cords on/off’ in every language. Hindi’s four-way stop contrast is a famous map. English learners of French may puff too much; French learners of English may not puff enough.",
    "b is just a soft p. Languages that distinguish them are being fussy. Blow is optional.",
    "Hold a tissue in front of pin vs spin. Then a b. Feel the puff on pin.",
    "A final devoicing (German, some Slavic) makes ‘bad’ sound like ‘bat’ to English ears. It is a rule, not a cold."],
  ["vy-l-nasal-place", "Sounds", "n, m, and ng are the same idea at three places; English ng is not n+g as a plus",
    "sing vs sin vs sim. A learner who releases a g on -ing is spelling with the mouth. Some languages allow ng at the start (Vietnamese); English mostly does not, which is a phonotactic habit, not a law of noses.",
    "ng is n then g because the spelling said so. Always release the g to be clear.",
    "Hum with the mouth closed (m), tongue on the ridge (n), back of the tongue (ng). Then words.",
    "A Sydney vs Melbourne vowel is a different ticket. Do not mix a accent drill with a nasal drill until each is stable."],
  ["vy-l-intonation-tune", "Sounds", "Intonation is a tune that can be the grammar",
    "A rising question vs a falling statement in many English dialects — and a rise that is just ‘not finished’. Some languages use particles instead. Sarcasm is a tune plus a shared file. Texting strips it, hence /s.",
    "Pitch is emotion only. Grammar is words. Tunes are for singers.",
    "Hum a sentence without words. Then add the words. Mark where a yes/no wants a rise in your target dialect.",
    "A ‘polite’ rise on a statement (uptalk) is a social file, not a IQ. Do not mock it as a linguist-in-training."],
  ["vy-l-mora-vs-syllable", "Sounds", "A mora is a beat some languages count; a syllable is a different ruler",
    "Japanese timing, a long vowel as two morae, a ん as a mora. Haiku in Japanese is a mora sport; English haiku as 5-7-5 syllables is a tourist cousin. Do not grade a Japanese learner’s rhythm with an English clap only.",
    "Beats are beats. Clap English and you have clapped Japanese. Rulers are universal.",
    "If you study Japanese (or a similar system), count morae on a word like Tōkyō. Then clap English ‘Tokyo’ and notice the theft.",
    "A geminate (double consonant) can be a mora. Spelling っ is a time, not a decoration."],
  ["vy-l-linking-r", "Sounds", "Linking and intrusive r are dialect machines, not spelling errors in the mouth",
    "law and order getting a r in some non-rhotic Englishes; car alarm keeping one. Rhotic accents (many US, Scotland) do not need the trick. Teaching ‘never say r’ is a dialect prejudice.",
    "If they add a r it is uneducated. RP is physics. Also: always pronounce every r because spelling.",
    "Name the dialect you are aiming at. Then listen for the link. Do not correct a Australian linking r as a fail of literacy.",
    "A rhotic learner of Australian English may sound ‘American’ to locals. That is a target choice, not a moral."],
  ["vy-l-tone-sandhi", "Sounds", "Tone sandhi is a tone that changes because of its neighbour, not a learner fail",
    "Mandarin third-tone sandhi is the classroom celebrity; other Sinitic languages and some African languages have richer maps. Isolating a character’s dictionary tone is a start, not the street.",
    "Tones are stickers that never change. If it changed you said the wrong word and should restart the language.",
    "Learn the citation tone, then the common change in a two-syllable word. Drill the pair, not only the poster.",
    "A romanisation without tone marks is a diet that starves you. Put the marks back."],
  ["vy-l-punct-not-universal", "Scripts", "Punctuation is a technology with a history, not a human instinct",
    "Spaces between words were not always there. Some scripts mark questions with a shape English does not. Fullwidth punctuation in CJK, a inverted ¿ in Spanish. A ‘correct’ English comma rule is a house style, not a law of cognition.",
    "If they do not space like us they cannot think like us. Literacy is one punctuation.",
    "Copy a short text in the target script’s normal punctuation. Do not ‘help’ by converting it to English marks as a default.",
    "A unicode lookalike punctuation is a phishing cousin. Scripts meet security in the worst group chat."],
  ["vy-l-case-optional", "Scripts", "Capital letters are a Latin habit, not a feature of ‘real’ writing",
    "Arabic, Hebrew, Hangul, many others have no upper/lower pair. German capitalises nouns as a different rule. SHOUTING in Latin caps is a register, not a grammar of importance in every script.",
    "If it has no capitals it is informal. Serious languages shout the start of the sentence.",
    "When you learn a script, ask whether case exists. Then stop hunting for it.",
    "A logo that forces Latin caps onto a bicameral-less script is a design fail. Ask a speaker."],
  ["vy-l-romanisation-lossy", "Scripts", "A romanisation is a lossy export, not the language",
    "Pinyin, Hepburn, a library of Korean systems, a ‘how you like’ of a name. Tone and vowel length often die. Tattoos of a romanisation you googled are a famous regret.",
    "If I can type it in English letters I have the word. Export is the same file.",
    "Learn the native script for anything you will keep (a name, a place). Use romanisation as training wheels with the gaps named.",
    "A passport romanisation can be a legal freeze of a lossy choice. That is bureaucracy, not linguistics as a vibe."],
  ["vy-l-font-not-script", "Scripts", "A font is a costume; a script is a system",
    "Comic Sans vs a Naskh vs a Kai typeface. Calling all Chinese ‘kanji font’ is a mash of languages. A ‘Asian-looking’ display face can be a racist costume when it is fake strokes on Latin letters.",
    "Exotic letters are a font you download. Systems are fonts. Also: one font fits Mandarin, Japanese, and Korean.",
    "Name the script, then a appropriate typeface, then whether Latin fake-brush is doing a harm.",
    "A restaurant sign in a ‘chop suey’ Latin font is a history of othering. Designers still ship it. Do not."],
  ["vy-l-orthography-deep", "Scripts", "A deep orthography hides morphology; a shallow one shows sound",
    "English ‘sign/signature’ keeps a g you do not say in sign. Italian is shallower. Neither is smarter. Spelling reform is a political bomb because it picks a dialect to freeze.",
    "Once you know the alphabet you can read any word first try. That was the deal in Year 1.",
    "When you misspell, ask if you stored the morpheme or the sound. Then a dictionary, not a vibe of ‘English is random’ as a full theory.",
    "A spelling bee is a deep-orthography sport. It is not a intelligence test for a Italian kid."],
  ["vy-l-cursive-join", "Scripts", "A joining script has a positional shape; copy-paste print may lie",
    "Arabic letters change by position (initial, medial, final, isolated). A learner who only knows the isolated poster cannot read a word. Latin cursive is a pale cousin.",
    "Print is the real letters; joined is decoration for fancy people. Also: type everything, handwriting is dead, skip the shapes.",
    "Write a three-letter word in all positions. Then a printed font vs a naskh. Both count.",
    "A unjoined Arabic for beginners is a scaffold. Stay on it too long and the street stays closed."],
  ["vy-l-braille-system", "Scripts", "Braille is a script, not a ‘code for English only’",
    "Cells of dots, a grade 2 contractions in English, other languages’ tables. It is literacy, not a pity technology. Digital refreshable displays are a access file.",
    "Braille is Morse for fingers. Anyone can fake it. Also: audio replaced it so skip teaching it.",
    "Feel a cell if you have a model. Then the civic: labels at a lift, a menu. Access is a script in the world.",
    "A ‘braille’ decorative poster that is not actual braille is a costume. Check with a reader."],
  ["vy-l-han-shared", "Scripts", "Han characters are a shared historical technology, not ‘the Asian alphabet’",
    "Chinese, Japanese kanji, a Korean hanja leftover, Vietnamese chữ Nôm as history. Meanings and readings diverge (a Japanese on/kun). Calling it all ‘kanji’ in a Mandarin class is a mash.",
    "One character, one picture, one sound across East Asia. Convenient for tourists.",
    "Name the language, the reading, the simplified/traditional choice. Then a false friend character that drifted.",
    "A tattoo of a ‘kanji’ that is a simplified Chinese with a Japanese aesthetic is a common muddle. Ask a literate human."],
  ["vy-l-prototype-word", "Meaning", "A category has a prototype, not a museum of necessary features",
    "A robin is a ‘birdier’ bird than a penguin for many English speakers. Legal definitions try to fight this with tests. Learners over-narrow (a cup must have a handle) or over-wide.",
    "Every word has a checklist of conditions. If it fails one it is not in the set. Aristotle runs the street.",
    "List three good examples, one odd one, and a borderline. Then a language that splits your category (a cup/mug, a blue/green).",
    "A ‘fruit’ that is a tomato in a court is a prototype war. Botany and lunch are different games."],
  ["vy-l-hyponym-tree", "Meaning", "Hyponyms sit under a hypernym; a dog is a animal is a not a synonym chain",
    "Rose < flower < plant. Translation fails when the tree is cut differently (a rice vs a meal grain). A thesaurus that offers the hypernym as a ‘synonym’ is how essays go vague.",
    "Bigger words are always more precise. Animal is better than dog because it is academic.",
    "Draw a tiny tree for a word you will write. Then pick the level the audience needs.",
    "A ‘vehicle’ when you mean ‘bus’ is a fog. A ‘bus’ when the law said ‘vehicle’ is a different fail."],
  ["vy-l-collocation-l2", "Meaning", "Collocation is why a dictionary line is not a sentence licence",
    "Make a decision, strong tea, commit a crime. A learner’s ‘do a decision’ is grammar-okay and native-no. Chunks are meaning in company.",
    "Any verb plus any noun if the meanings fit. English is Lego. Also: translate word-for-word from home and the company will follow.",
    "When you log a noun, log one verb that owns it. Check a example sentence, not only a equivalent.",
    "A medical collocation you invent can be a harm. Pharmacy is not a creative writing task."],
  ["vy-l-connotation-l2", "Meaning", "A denotation match can still be a connotation bomb",
    "Slim/skinny, a regime/government, a cheap/inexpensive. Learners grab the first dictionary line. Register and smell travel poorly across languages.",
    "If the translation is in the list it is safe in a speech. Lists are ethics.",
    "Check a corpus example, a native, or a learner’s dictionary’s warning triangle. Then the room (a eulogy vs a roast).",
    "A false friend with a extra rude connotation is the advanced trap. Gift/Gift was the cute one; the rude ones hide."],
  ["vy-l-deixis-here", "Meaning", "Deixis is a meaning that needs a pointing finger in the room",
    "I, here, now, this. A recorded announcement that says ‘we will be with you shortly’ is a theatre of deixis. Translation of a comic must redraw the pointing.",
    "Words mean the same in every room. Context is cheating. Also: ‘this’ is a noun you can google.",
    "Circle the deictics in a text message. Then what a stranger would need as a footnote.",
    "A ‘coming now’ that means 40 minutes is a cultural deixis of time. Pragmatics, not a watch fail only."],
  ["vy-l-semantic-role", "Meaning", "Who did what to whom is a role, not only a word order",
    "Agent, patient, experiencer. English hides this in SV-O; other languages mark it on the noun (case). A passive demotes the agent. Translation that keeps the words and loses the role is a muddle.",
    "The first noun is always the doer. Order is a universal of thought.",
    "Label agent and patient in a active and a passive pair. Then a language with case if you have one.",
    "A ergative system (a later curiosity) will wreck the ‘subject = agent’ habit. Stay humble."],
  ["vy-l-presuppose", "Meaning", "A presupposition sneaks a claim in as furniture",
    "‘Have you stopped X?’ assumes you started. ‘The King of France’ as a old puzzle. Political slogans love this. A translator who unpacks it can look rude and be accurate.",
    "If it is in a question it is not a claim. Questions are innocent. Always.",
    "Spot the hidden ‘already true’. Then decide whether to challenge the furniture or answer inside it.",
    "A ‘when did you stop cheating’ in a playground is a trap. Logic hub will want a word; this hub wants the language."],
  ["vy-l-calque-loan", "Meaning", "A calque is a loan of a structure; a loanword is a suitcase of sound",
    "Skyscraper → gratte-ciel is a calque. Tsunami is a suitcase. ‘Chai tea’ stacks a loan. Learners invent calques from home (‘make a photo’) that natives may still understand and still mark as off.",
    "If we translate the bits we have not borrowed. Calques are original local thought. Also: never calque, only borrow, because authenticity.",
    "Trace one of each in your target language. Then a failed calque you should retire.",
    "A ‘handphone’ in some Englishes is a regional collocation, not a error. World Englishes sit here."],
]);
