import { pack } from "../../pack.mjs";

export const LOGIC_MORE = pack("logic", [
  ["vy-o-sample-space", "Probability extras", "A sample space is the list of what can happen, written before the wish",
    "A fair die is {1,2,3,4,5,6}. A ‘random student’ without a list is a vibe. Events are subsets. If you cannot name the space you cannot name the probability except as a mood.",
    "The sample space is the outcomes you like. Leave the rest off so the chance looks bigger.",
    "Write the set, check they are disjoint and cover the experiment, then count or weight.",
    "A continuous space (a spinner) is a different ruler (area). Do not count ticks that have no width as if they were die faces."],
  ["vy-o-equiprobable", "Probability extras", "Equal likelihood is a claim, not a gift of counting the words",
    "Two teams in a final are not 50% if one is a giant. A coin can be bent. ‘There are two options’ is the start of a trap, not the end of a model.",
    "If you can name two results they are always 1/2. Language is a uniform prior.",
    "Ask what symmetry makes them equal. If none, you need data or a better model, not a vibe of fairness.",
    "A ‘either it rains or it does not’ is 50% only in a joke. Tomorrow’s BOM is the model."],
  ["vy-o-complement-one", "Probability extras", "The complement is 1 minus, when the leftover is the event’s not",
    "P(at least one six in n dice) is 1 − P(no sixes). Adding the long way is how you invent a extra six. Exclusive leftover, not a vibe of leftover.",
    "At least one is n times the single chance. Complements are for cowards who cannot add.",
    "Name the ugly event, compute the easy ‘none’, subtract from 1. Check you did not overlap.",
    "A ‘at least’ that is not a complement job (at least 3 sixes) still wants a binomial, not a 1−none unless none is the right leftover."],
  ["vy-o-tree-diagram", "Probability extras", "A tree is a multiply-along, add-the-ends machine",
    "First draw, then second, with the second branch allowed to be conditional. Missing a branch is a silent 0. The ends that match the event get summed.",
    "Trees are for kids. Real probability is a formula you memorise without a picture.",
    "Draw, write probabilities on edges, multiply a path, add the paths you want. The leaves should total 1.",
    "A tree that is not actually sequential (two coins at once) can still be drawn; just do not invent a fake dependence."],
  ["vy-o-with-without", "Probability extras", "With replacement resets; without does not; the words in the question are the experiment",
    "Two cards, no put-back: the second denominator shrank and a ace may already be gone. With replacement is a independent clone. People mix them because the story felt similar.",
    "Without replacement is always 1/2 of with, because you have less. Less is half.",
    "Rewrite the experiment as a sentence, then change the second fraction. A tree is allowed.",
    "A ‘random password of 4 digits’ is with replacement (digits can repeat) unless the brief forbade repeats. Read."],
  ["vy-o-expected-value-bet", "Probability extras", "Expected value is a long-run mean of a numbered bet, not a promise tonight",
    "Sum of value × probability. A raffle can be negative EV and still be a donation in a costume. Insurance can be negative EV and still rational because of ruin.",
    "If the EV is positive you cannot lose this weekend. Long-run lives in a weekend.",
    "List outcomes, multiply, add. Then ask if you can survive the variance.",
    "A ‘free’ spin with a 99% lose is a EV you can compute on a napkin. The venue already did."],
  ["vy-o-variance-spread", "Probability extras", "Two bets can share a mean and not a spread; variance is the weather of the mean",
    "A sure $10 vs a 50/50 of $0 or $20. Same EV, different nights. Ruin cares about the spread. School SD is this costume with a square root.",
    "If the average is fine the ride is fine. Means erase risk. That is why they exist.",
    "Name the mean, then a worst plausible night, then whether you can hold it.",
    "A diversified pile is a variance story. Ten identical lottery tickets are not a spread; they are a thicker same bet."],
  ["vy-o-bayes-clinic", "Probability extras", "A rare disease plus a good test can still be mostly false alarms",
    "Base rate first, then sensitivity/false positive. A 99% accurate test on a 0.1% disease is a famous classroom. The table (or a 10 000 people cartoon) beats a slogan.",
    "If the test is 99% you are 99% likely to have it. Accurate is the posterior. Always.",
    "Write the four boxes of a 10 000 town. Then P(disease | positive) as a fraction of the plus column.",
    "A prosecutor’s DNA match without a how-many-people-could-match is this ticket in a wig."],
  ["vy-o-combinatorics-count", "Probability extras", "If the outcomes are not equally likely, counting them is not a probability yet",
    "Two heads vs a head-and-tail: HT and TH are two outcomes if coins are distinct in time. People count {HH, HT, TT} as three equals and then invent a 1/3 for two-of-a-kind.",
    "Count the words in the question. Each word is a outcome. ‘Two heads or mixed or two tails’ is three, so 1/3.",
    "List the actual micro-outcomes (HT and TH). Then weight. A tree with time-order saves you.",
    "A dice sum of 7 is more micro-ways than 2. Counting faces of the sum as 11 equals is the same crime."],
  ["vy-o-independence-break", "Probability extras", "Independence dies when one result changes the other’s chances",
    "Drawing without replacement; a rumour that updates a test; weather today given a storm line. Multiplying as if independent is a silent extra assumption. Say it or drop it.",
    "If the stories are in different sentences they are independent. Grammar is probability.",
    "Ask: if I knew the first, would I change the second number? If yes, condition. If no, multiply.",
    "A ‘random’ password policy that forbids repeats is a dependence you installed. The space shrank."],
  ["vy-o-law-large", "Probability extras", "The law of large numbers is a long run, not a due in the next five",
    "Frequencies settle toward the mean if the trials are iid-ish. A streak of red does not owe you black. Casinos live on people swapping these sentences.",
    "If it has been red four times, black is due so the large numbers can catch up tonight.",
    "Separate the long-run frequency from the next-spin independence. Both can be true at once.",
    "A small n that ‘looks unfair’ is often just a small n. Simulation of 10 vs 10 000 is a classroom mercy."],
  ["vy-o-simulation-model", "Probability extras", "A simulation is a model you can run, not a proof from Olympus",
    "Random digits, a spreadsheet, a 10 000 loop. Garbage in (a bad independence) is garbage out with more decimal places. Use it to check a tree, not to skip the tree forever.",
    "If the computer said 0.473 it is the true chance to three places. Simulation is the universe.",
    "State the assumptions you coded. Then a analytic check on a simple case. Then the messy case.",
    "A RNG that is not random (a bad seed, a human ‘random’ pick) is a different experiment. Name the generator."],
  ["vy-o-operational-def", "Evidence extras", "A pretty word still needs a measurement recipe you could hand a stranger",
    "‘Aggressive’, ‘liveable’, ‘addicted’. Two labs can disagree because they operationalised differently, not because one is evil. A one-item survey is a thin recipe.",
    "Everyone knows what the word means. Measurement is extra. Also: the more items the more true, always.",
    "Write the recipe (what you count, for how long, who scores). Then a rival recipe and what would flip.",
    "A ‘happiness’ that is GDP is a famous operational dodge. Name the dodge."],
  ["vy-o-selection-bias", "Evidence extras", "Who got into the net is the story, not only who is in the photo of the catch",
    "Hospital patients, a tweet poll, a volunteer sample of ‘concerned parents’. The sea had other fish. Name who could not appear.",
    "If n is big the net does not matter. Size washes bias. That is why big n is a halo.",
    "Draw the population, the sampling frame, the actual n. Then the missing slice.",
    "A survivor-only dataset of startups is a graveyard of missing corpses. Advice from survivors is a selection."],
  ["vy-o-confounder-third", "Evidence extras", "A confounder turns both knobs; ice cream and drowning share a heat",
    "Control, stratify, or randomise if you can. A ‘after we painted the office, sales rose’ is a season, a product, a boss. The third gear is the homework.",
    "If A came before B, A caused B. Time is a sufficient machine. Also: if they correlate, they cause, both ways, for luck.",
    "Name a third gear that could move both. Then what evidence would kill it (a experiment, a negative control).",
    "A Simpson flip when you split groups is a confounder in a trench coat. Look at the split."],
  ["vy-o-p-hacking", "Evidence extras", "A p-value hunted across 20 tests is a trophy you built, not a surprise you found",
    "Optional stopping, a extra covariate, a outlier you dropped after seeing it. Pre-registration is a later patch. One honest p is a different animal from a drawer of 19 fails.",
    "If any p is under 0.05 the phenomenon is real. Multiple tests are a generosity of nature.",
    "Ask how many looks, what was dropped, whether the hypothesis was written before the pile. Then a replication.",
    "A data-dredged ‘sign of your star sign’ will sometimes p. That is the factory."],
  ["vy-o-peer-review-limit", "Evidence extras", "Peer review is a filter with holes, not a sacrament",
    "Reviewers miss fraud, miss a honest error, and also catch a lot. A journal brand is a prior, not a proof. Preprints are a conversation; retractions are a system working, late.",
    "If it is published it is true. If it is retracted the field is fake. Two cartoons.",
    "Read the methods, not only the press release. Then a second lab. Then still a maybe.",
    "A predatory journal will peer-review your wallet. The logo can still look like a university."],
  ["vy-o-anecdote-n1", "Evidence extras", "n = 1 is a existence proof at best, not a rate",
    "It happened to my uncle. Existence of a side effect is not the same as common. A vivid story beats a dull table in a brain; that is why we need the table.",
    "A story is data. Data is a story. Therefore one story is a meta-analysis.",
    "Park the anecdote as a hypothesis. Then a denominator. Then whether you have the denominator.",
    "A miracle diet testimonial is a n=1 with a photographer. The missing n are off-camera."],
  ["vy-o-false-dilemma", "Arguments extras", "A false dilemma sells two doors when the corridor had more",
    "With us or against us; nature or nurture as a only; a exam ‘which of these two causes’. The missing third is often ‘both, in parts’ or ‘neither, a different mechanism’.",
    "If they named two, those are the options. Naming is ontology.",
    "Invent a third that is not a joke. Then ask why it was left off (a rhetoric, a real binary law).",
    "A ballot with two parties is a designed dilemma, not a logic of the universe. Preferential voting is a later civic patch."],
  ["vy-o-straw-man", "Arguments extras", "A straw man is a weaker clone you set on fire for the crowd",
    "They said ‘regulate this ad to kids’; you heard ‘ban all speech’. Steel-man is the opposite sport. Quote, then the because, then your hit.",
    "If I can make their view sound stupid I have refuted it. Comedy is validity.",
    "Write their best sentence in words they would sign. Then disagree with that. If they would not sign, you are still in the field burning hay.",
    "A headline is often already a straw. Go to the paper, not the ratio."],
  ["vy-o-ad-hominem-split", "Arguments extras", "Attacking the person is a miss unless the claim is about the person",
    "‘You would say that, you are a vendor’ can be a bias warning (evidence about the source) or a dodge (the trial data still sits there). Split the jobs. Credentials are a prior, not a theorem.",
    "If they are a bad person the argument is false. Character is truth-functional. Also: if they have a PhD the argument is true.",
    "Ask whether the personal fact changes the likelihood of this claim, then still look at the independent evidence.",
    "A hypocrisy call (‘you fly to a climate talk’) can be a fair ethics hit and still not touch the tonne maths. Two tickets."],
  ["vy-o-slippery-slope", "Arguments extras", "A slope is a causal chain you have to warrant, not a vibe of doom",
    "If we allow A, then Z. Sometimes there is a mechanism (a legal precedent, a incentive). Sometimes it is a ghost story. Demand the steps and a stop that failed.",
    "Every change is a slope to a dystopia. History is a skateboard. Also: slopes never exist, all lines are independent.",
    "Write A→B→C→Z. Put a because on each arrow. If you cannot, you have a fear, not a slope.",
    "A real slippery regulation can exist (a vague crime). That is a drafting lesson, not a ban on all future tense."],
  ["vy-o-burden-shift", "Arguments extras", "The burden sits with the one who moved; ‘prove it is not’ is a cheap teleport",
    "Russell’s teapot as a cartoon. A extraordinary claim wants a extraordinary pile, not a homework for the listener. Absence of evidence is not always evidence of absence — but it is not a proof of presence either.",
    "If you cannot disprove my invisible dragon it is probably in the garage. Gaps are evidence.",
    "Ask who added a entity or a cause. They bring the first data. Then a fair search if the dragon would have left a mess.",
    "A medical ‘we have not proven harm’ is not the same as ‘proven safe’. The burden can sit with a regulator on purpose. Name the rule."],
  ["vy-o-circular", "Arguments extras", "A circle is a premise that already wore the conclusion as a hat",
    "The book is true because it says it is true. A ‘by definition’ that smuggled the fight. Begging the question in the old sense, not ‘this raises the question’ as a TV tic.",
    "If I repeat the claim louder it becomes a premise. Volume is inference.",
    "Write P and C. If P only restates C, you need a new P. Definitions can start a argument; they cannot finish a empirical one.",
    "A legal ‘because I said so’ from a authority can be a valid appeal to a rule, not a empirical circle. Know which game."],
]);
