import { pack } from "../../pack.mjs";

export const MATHS_MORE = pack("maths", [
  ["vy-m-divis-four", "Number sense extras", "Divisible by 4 is a last-two-digits test",
    "A number is divisible by 4 if the number formed by its last two digits is. 1312 ends in 12, and 12 ÷ 4 = 3, so 1312 is.",
    "If it ends in 4 it divides by 4. One digit is enough because 4 is small.",
    "Cover all but the last two digits, test that two-digit number, then keep the original for the actual divide if you need the quotient.",
    "100 is divisible by 4, so any hundreds you ignore were already a multiple. That is why the test works."],
  ["vy-m-divis-eleven", "Number sense extras", "Divisible by 11 is an alternating-sum test",
    "Alternate + and − on the digits: 2 9 3 7 → 2−9+3−7 = −11, and −11 is a multiple of 11, so 2937 is.",
    "If it looks symmetric it divides by 11. Palindromes are the whole rule.",
    "Write + − + − under the digits, add, and check the small result is 0, 11, −11, 22…",
    "10 ≡ −1 (mod 11), so the alternating sum is modular arithmetic in a school costume."],
  ["vy-m-not-commutative-sub", "Number sense extras", "Subtraction does not commute; 7−3 is not 3−7",
    "Addition and multiplication may swap; subtraction and division may not. 7−3=4 and 3−7=−4. Order is the story.",
    "You can always swap to make the bigger number first, because negatives are optional in Year 8.",
    "Write the first number as the start, then walk left for minus. Do not sort the digits for politeness.",
    "a−b = −(b−a). That identity is how you recover when you accidentally swapped."],
  ["vy-m-identity-zero-one", "Number sense extras", "Zero is the add-nothing; one is the multiply-nothing",
    "n+0=n and n×1=n. n×0=0 is a different, famous crush. People mix the identities and then ‘cancel’ a zero.",
    "Adding 1 does nothing, because 1 is the identity. Also multiplying by 0 leaves the number, because 0 is small.",
    "Name which operation you are in, then the identity that belongs to it. Cancel only factors that are 1, not zeros.",
    "Dividing by 1 does nothing; dividing by 0 is illegal. The 1-identity does not license a 0-identity for divide."],
  ["vy-m-compatible-jumps", "Number sense extras", "Compatible numbers are a mental-maths shortcut, not a lie",
    "27+15 as 25+15+2, or 4×98 as 4×100−8. You rewrite, then compensate. The answer still has to match the original question.",
    "Compatible means round both and keep the rounded answer. Compensation is optional decoration.",
    "Change to a friendly pair, compute, then add back what you borrowed or stole.",
    "29×5 is 30×5−5=145. Forgetting the −5 is how estimation pretends to be exact."],
  ["vy-m-frac-number-line", "Fractions extras", "A fraction is a point on a line, not only a pizza",
    "3/4 sits three quarter-jumps from 0 toward 1. 5/4 sits past 1. Pizzas hide improper fractions; the line does not.",
    "Fractions live between 0 and 1. If the top is bigger you must convert or it is not allowed on a line.",
    "Mark 0 and 1, split into equal ticks of the denominator, then count the numerator.",
    "−1/2 is left of 0. The pizza story struggles there; the line does not."],
  ["vy-m-unit-frac-egypt", "Fractions extras", "A unit fraction has 1 on top; Egyptian-style sums are a puzzle, not a law",
    "1/2+1/3+1/6=1. Unit fractions are a costume. 2/5 is already simplest; you do not have to write it as 1/3+1/15 unless the question asked.",
    "Every fraction must be written as unit fractions or it is unfinished. The Egyptians grade the paper.",
    "Use unit fractions when they help (splitting a share). Otherwise keep the single fraction.",
    "1/2+1/3=5/6, not 2/5. Unit-fraction addition still needs a common denominator."],
  ["vy-m-complex-frac-bar", "Fractions extras", "A stacked fraction is divide: the longest bar is the main split",
    "(1/2)/(3/4) is 1/2 × 4/3. The vinculum is a division symbol. Nested bars need brackets or a clear longest line.",
    "Cancel any two numbers you can see, even across different bars, because cancel is a lifestyle.",
    "Rewrite as a÷b with brackets, then multiply by the reciprocal of the bottom.",
    "1/2/4 is ambiguous on a single line. Write (1/2)/4=1/8 or 1/(2/4)=2. The bar length is the referee."],
  ["vy-m-frac-not-ratio-always", "Fractions extras", "A ratio 2:5 is not automatically the fraction 2/5 of the whole",
    "2:5 parts of a mix is 2/7 and 5/7 of the whole if those parts make the whole. 2/5 would be ‘two compared to five’ as a different sentence.",
    "A colon is a slash. 2:5 of 70 is 2/5 of 70.",
    "Ask whether the two numbers partition the whole. If yes, denominator is the sum. If they compare part to part of something else, read again.",
    "Odds of 2:5 against are a different dialect. Sports odds are not a Year 8 pie."],
  ["vy-m-cancel-across-plus", "Fractions extras", "You may cancel factors, not terms across a plus",
    "(2×3)/(2×5)=3/5. (2+3)/(2+5) is 5/7, not 3/5. Cancel is for common factors of a product, not for matching digits in a sum.",
    "If a 2 appears on top and bottom you may always kill it. 2+3 over 2+5 loses the 2s.",
    "Factor first if you want to cancel. If it is a sum, find a common factor of the whole numerator and whole denominator, or do not cancel.",
    "(2x+2)/2 = x+1, not x+2. Factor 2(x+1)/2, then cancel the factor 2."],
  ["vy-m-dec-compare-places", "Decimals", "Compare decimals place by place from the tenths, not by who has more digits",
    "0.8 vs 0.75: tenths 8>7 so 0.8 is larger. Trailing zeros (0.80) do not change that. Extra digits on the right can still lose to a bigger tenth.",
    "The longer decimal is bigger because it took more work to write. 0.75 > 0.8.",
    "Line up the points, pad zeros, compare the first place that differs.",
    "0.09 vs 0.1 is the celebrity trap. Hundredths vs tenths. Money: 9 cents vs 10 cents."],
  ["vy-m-dec-shift-divide", "Decimals", "Slide both numbers in a decimal divide until the divisor is whole",
    "4.8 ÷ 0.12 → 480 ÷ 12. You multiply top and bottom by the same power of 10. The quotient stays.",
    "Only slide the number with the point. The other one can stay, because you already did enough.",
    "Count the slides needed to make the divisor whole, slide the dividend the same count, then divide as wholes.",
    "6 ÷ 0.2 = 30, not 0.3. Sliding both: 60 ÷ 2 = 30. Estimation: five 0.2s fit in 1, so thirty fit in 6."],
  ["vy-m-dec-multiply-estimate", "Decimals", "Estimate a decimal product before you park the point",
    "2.9 × 3.1 is about 3×3=9. If you get 89.9 the point fell in the weeds. Places: one + one = two in the product.",
    "Add the decimals because multiply with points is too spicy. 2.9×3.1=6.0.",
    "Round, multiply, then do the exact with the place-count rule. If they disagree wildly, recount places.",
    "0.2 × 0.3 = 0.06, not 0.6. Two decimal places in the factors want two in the product, including a leading zero in the tenths."],
  ["vy-m-money-two-places", "Decimals", "Money is hundredths; a third decimal is a round, not a new cent",
    "AUD writes two decimal places. 3.456 dollars is not a coin. GST and unit prices may compute extra places, then round to cents by a stated rule.",
    "Keep every calculator digit on a receipt so you look accurate. 3.456 cents is a type of cent.",
    "Compute, then round to two dp for cash/card display unless the context is a unit price per gram.",
    "Three $1.005 items if you round each first can disagree with rounding the total. State when you round."],
  ["vy-m-scientific-neg-slide", "Decimals", "A negative scientific exponent slides the point left",
    "3.2 × 10⁻³ is 0.0032. The minus is direction, not a negative 3.2. 3.2 × 10³ is 3200.",
    "3.2 × 10⁻³ means −3.2 × 10³, because the minus leaked.",
    "Move the point as many places as the exponent, left if negative, filling zeros as chairs.",
    "Calculator 3.2E−3 is the same costume. E is not a digit you multiply by."],
  ["vy-m-percent-points-gap", "Percentages extras", "A rise from 8% to 10% is two percentage points, not a 2% rise",
    "Percentage points subtract the percents. The relative change is 2/8 = 25%. News that mixes them is doing a trick.",
    "If a rate goes from 8% to 10% it rose 2%, because 10−8=2 and both have a %.",
    "Write both: ‘up 2 percentage points, which is a 25% relative increase’. Then pick which the question asked.",
    "Unemployment from 5.0% to 5.5% is 0.5 points, a 10% relative rise. Both sentences can be true."],
  ["vy-m-successive-discount", "Percentages extras", "Two discounts in a row are multipliers, not a sum of the posters",
    "30% off then 10% off is ×0.7×0.9=0.63, so 37% off, not 40%. The second discount is of the already-reduced price.",
    "Add the sale stickers: 30+10=40% off, because both posters are in the window.",
    "Convert each to a multiplier, multiply, then 1 minus that product is the overall off.",
    "A 10% off a 10% off is 19% off, not 20%. The missing 1% is the 10% of the already-missing 10%."],
  ["vy-m-reverse-gst-net", "Percentages extras", "GST-exclusive is inclusive divided by 1.1, not minus 10% of the ticket",
    "A $110 GST-inclusive price has $100 net and $10 GST. Minus 10% of $110 is $99, which is the classic own-goal.",
    "GST is 10%, so knock 10% off the shelf price to find the net. 10% is 10%.",
    "Divide by 1.1 (or ×10/11) for net. Multiply net by 0.1 for the GST dollar.",
    "A $11 sandwich: net $10, GST $1. The 10% lives on the net, not on the inclusive as a second 10%."],
  ["vy-m-percent-of-percent", "Percentages extras", "10% of 10% is 1% of the original, not 20% and not 0%",
    "Take 10% of 10% of 200: 10% of 200 is 20, then 10% of 20 is 2, which is 1% of 200. Nested percents multiply as decimals: 0.1×0.1=0.01.",
    "Of means add when both have a percent sign. 10% of 10% is 20%.",
    "Convert each percent to a decimal, multiply, then interpret against the original base.",
    "A 50% of a 50% off is a quarter of the original remaining if they chain — wait, that is multipliers again: ×0.5×0.5=0.25 remaining, 75% off overall. Different sentence; parse ‘of’ vs ‘off’."],
  ["vy-m-iso-triangle-base", "Geometry extras", "Isosceles means two sides (or two base angles) match, not ‘looks pointy’",
    "Equal sides face equal angles. The base angles are the pair at the equal sides’ far ends. A drawing that looks equal is not a given.",
    "Isosceles means all sides equal. Equilateral is a brand of isosceles, so they are the same word.",
    "Tick the equal sides from the given, then mark the base angles. Only then chase the third.",
    "Equilateral is isosceles with a bonus. Every equilateral has three equal angles of 60°. The converse needs a proof, not a vibe."],
  ["vy-m-cointerior-180", "Geometry extras", "Co-interior angles on a transversal sum to 180° if the lines are parallel",
    "Same-side interior (co-interior) add to a straight-ish 180° when the two lines are parallel. If they do not, the lines are not parallel — that is a test, not a decoration.",
    "Co-interior means they are equal, like corresponding. All parallel-line words mean equal.",
    "Find the pair between the parallels, same side of the transversal. Sum, do not copy.",
    "Corresponding are equal, alternate are equal, co-interior are supplementary. Three costumes, two jobs."],
  ["vy-m-area-composite", "Geometry extras", "A composite area is add the pieces you invent, minus the holes",
    "An L-shape is a rectangle plus a rectangle, or a big rectangle minus a bite. Write the dissection before the arithmetic so you do not double-count a strip.",
    "Walk around the outside and multiply all the lengths you see. Perimeter numbers are area numbers.",
    "Sketch the split, label each length (some are hidden differences), compute each area, then add or subtract.",
    "Missing lengths are often a subtraction of two given sides. Do not invent a 7 because 7 was on another edge."],
  ["vy-m-volume-prism", "Geometry extras", "A prism’s volume is area of the uniform face times the length of the run",
    "V = A_base × h. A triangular prism is (½bh) × length. The ‘height’ of the prism is the extrusion, which may be lying down on the page.",
    "Volume of any 3D thing is length × width × height, even a triangular prism, using the three numbers you can see.",
    "Identify the face that stays the same along the run. Its area, then × the run.",
    "A cylinder is a circular prism in this language: πr²h. A pyramid is not: it takes the extra ⅓."],
]);
