import { pack } from "../../pack.mjs";

export const MUSIC_MORE = pack("music", [
  ["vy-mu-unison-beats", "Ensemble", "A unison is harder than a chord because beats tell on you",
    "Two people on the same pitch make a wah-wah if they disagree by a few cents. Harmony can hide; unison cannot. Choirs and violin sections live here.",
    "Unison is the easy bit because everyone has the same note. Chords are the hard work.",
    "Tune the reference, then the unison, then add the harmony. If it rolls, someone is sharp or dull — not ‘expressing’.",
    "A octave unison still wants the same vowel and the same vowel length. High voices can sound sharp if the vowel is too closed."],
  ["vy-mu-cue-eye", "Ensemble", "An upbeat is a contract you make with your eyes",
    "A conductor’s prep beat tells tempo, style, and when. Looking at the stand through the first bar is how you invent a private tempo. Chamber groups still need a human cue if nobody has a stick.",
    "If you can count you do not need to look up. Counting is a force field.",
    "Breathe with the prep, watch the ictus, then the stand. A late first note is often an eyes problem.",
    "A fermata that dies because nobody agreed who ends it is a civic of ensembles. Assign the ending."],
  ["vy-mu-stand-partner", "Ensemble", "A stand partner is a choreography of page turns and pencil",
    "Inside player turns; outside plays the line — house rules vary, so write yours. A crash in a rest that was meant to be a turn is a craft fail. Sharing a part is a relationship.",
    "Whoever is closer to the audience owns the stand. Rank is geography.",
    "Agree who turns, mark the spot, and do not write a novel in the other person’s cue.",
    "A photocopied extra bar on a fold is legal only if the hire/licence says so. Your teacher owns that fight."],
  ["vy-mu-listen-out", "Ensemble", "Listening out is a part you play with your ears",
    "If you only hear your own bell, you are a soloist in a crowd. Hear the bass, the beat, then you. In-ear monitors can lie; a hall mix is the real exam.",
    "Play loud enough to hear yourself over the band. Self-hearing is blend.",
    "Drop a dynamic until you hear the other section, then sit in it. A recording from the back of the room is the truth serum.",
    "A drummer who only hears the click and never the singer will fill the last word. Space is a note."],
  ["vy-mu-ds-coda", "Ensemble", "A D.S. al Coda is a road map, not a keep-going as a personality",
    "Dal segno, a to-coda, a fine. Choirs that sing through the sign invent a new piece. Pencil the jump bigger than the notes.",
    "If the music is pretty you continue to the last printed bar. Signs are for people who cannot feel form.",
    "Trace the path with a finger in silence, then sing it. Box the coda so a page-turn cannot eat it.",
    "A D.C. al Fine that also has a first ending is a trap city. Write the traffic lights."],
  ["vy-mu-dynamics-room", "Ensemble", "Forte is relative to the room, not a factory setting",
    "A chapel mf can be a gym p. Brass in a dry hall need less than brass in a carpeted drama room. The marking is a relationship, not a decibel tattoo.",
    "f means as loud as the instrument can physically go. Always. That is passion.",
    "Listen from the seats once if you can, then scale the section. A conductor’s ‘too much’ is a room report.",
    "A piano accompanying a choir in a wet church will lag if you play the same attack as a dry studio. Pedal and hall are partners."],
  ["vy-mu-tune-section", "Ensemble", "Section tuning is a hierarchy: reference, then you",
    "Oboe A, or a piano, or a tuner on one person. Then fifths and octaves that beat. A band that tunes to a noisy brass chorale is tuning to soup.",
    "Everyone play a loud A at once and the average will be in tune. Democracy is pitch.",
    "Quiet reference, adjust, then a chord. Warm the instrument first or the A was a lie.",
    "A transposition instrument’s written C is not concert C. Tuning in the wrong key is a theory ticket."],
  ["vy-mu-count-rests", "Ensemble", "Rests are music you play by counting",
    "A 16-bar rest is a job. Subdividing keeps you in the grid when the texture thins. Coming in a bar early is a solo nobody asked for.",
    "If you cannot hear yourself you should not count. The people playing will fetch you.",
    "Pencil the remaining bars, subdivide the empty, watch the cue one bar early.",
    "A D.S. that skips your rest count is a trap. Follow the road map with a finger."],
  ["vy-mu-stage-plot", "Ensemble", "A stage plot is geography for sound, not a selfie arrangement",
    "Brass behind saxes, drums where the kit does not eat the choir, monitors that are not a war. A pretty front row that cannot hear the bass is a mix problem with chairs.",
    "Stand wherever looks good for parents. Acoustics is a studio myth.",
    "Put the timekeepers where they can see, the loud where they will not kill the front, then a quick listen from the hall.",
    "A marching band has a different plot (the field). Do not copy a jazz combo into a chapel without ears."],
  ["vy-mu-vamp-cue", "Ensemble", "A vamp until cue is a loop with a door, not a trance",
    "Theatre pits and some jazz charts sit on a groove until a visual or a lyric lands. Counting 40 bars of vamp without watching is how you miss the door.",
    "Vamp means noodle until you are bored, then the next section will appear telepathically.",
    "Watch the MD/singer, keep the groove boring on purpose, and have a planned last time through.",
    "A safety vamp that the singer never leaves is a rehearsal note, not a concert plan. Ask."],
  ["vy-mu-grid-speak", "Time", "A grid you can speak is how tempo survives a rit",
    "Crotchet = 60 can still hold quavers and triplets. A rit without a spoken grid is a slide off the roof. ‘1-e-and-a’ is literacy, not baby talk.",
    "Feel is the opposite of counting. Real musicians never subdivide. Metronomes are a prison.",
    "Set the metronome on the subdivision you fear, then hide it and keep the spoken grid.",
    "A 6/8 that is felt in 2 still has 6. Conducting pattern vs internal six is a choice you name."],
  ["vy-mu-tempo-mark-range", "Time", "A tempo word is a neighbourhood, not a single BPM tattoo",
    "Andante in one edition is a walk; in another it has a number. Style and the hall steal BPM. A metronome mark is a start, then musicianship.",
    "If it says 120 you must be 120.0. Adjudicators have atomic clocks.",
    "Start at the mark, then ask if the phrase can breathe. A live acoustic may want a notch down.",
    "Allegro that is only fast and not cheerful is a translation fail. Character sits in the word."],
  ["vy-mu-rubato-lend", "Time", "Rubato is borrowed time you actually pay back",
    "Steal from one beat, return it to the phrase. Endless slowing without a return is just dragging. Solo plus accompaniment must agree who is the banker.",
    "Rubato means ignore the barline forever. Romantic equals unmeasured.",
    "Agree the places you will lean, then land together on the structural downbeat.",
    "A pop ballad ‘behind the beat’ is a feel, not a licence to lose the form. The drums may still be honest."],
  ["vy-mu-anacrusis-count", "Time", "An anacrusis is a pickup; the first downbeat is still bar 1",
    "Three pickup quavers do not make the first incomplete bar into bar 1 in every numbering habit — check the edition. Counting in must include the pickup or you enter heavy.",
    "Start counting at the first note you play, always. Incomplete bars are a conspiracy of publishers.",
    "See whether bar 1 is the first full bar. Count the pickup as ‘and-a’ into 1.",
    "A pickup that is also a repeat’s last bar is a road-map trap. Write the traffic."],
  ["vy-mu-syncopation-accent", "Time", "Syncopation is an accent that missed the polite beat",
    "Off-beats, a tie over the barline, a reggae skank. If you accent the downbeat ‘to be safe’ you un-syncopated it. The rest is information.",
    "Syncopation means play everything late. Late is funky. Always.",
    "Clap the grid, then clap only the written off-beats. Then put it on the instrument.",
    "A swung quaver is not automatically a syncopation. Swing is a pair of lengths; syncopation is a placement."],
  ["vy-mu-poly-two-times", "Time", "Two times at once is a ratio you can count, not a vibe of chaos",
    "3 against 2: triplets over duple. Speak ‘1-and-a, 2-and-a’ against ‘1-and 2-and’. Hands separate, then together. Polyrhythm is literacy.",
    "If it sounds messy you are doing polyrhythm correctly. Mess is the aesthetic.",
    "Write both grids on one bar, loop slow, then raise tempo. A teacher’s clapping game is allowed.",
    "A hemiola (3/4 sounding like 2/4 for a moment) is a cousin. Name it when Brahms does it."],
  ["vy-mu-double-time-feel", "Time", "Double-time feel is a subdivision costume; the harmony may not have sped",
    "Drums go twice as busy; the chord chart can still be the old bars. Half-time is the reverse (backbeat on 3 in a 4 that feels like 2). Dancers care.",
    "Double-time means the song is twice as fast, so the singer must panic. Feel is form.",
    "Mark whether the barline speed changed or only the drum language. Count the form in the original bars if the chart did.",
    "A drum-and-bass ‘double time’ over a half-time chorus is a pop arrangement trick. Chart it."],
  ["vy-mu-loop-clean", "Craft", "A clean loop at half speed beats a dirty run at show speed",
    "Hands separate, a tiny cell, a metronome you actually move up. Running the piece at 90% with 40% accuracy grouts the mistakes in.",
    "Always start at performance speed so you learn the feeling. Feeling is accuracy.",
    "Find the bar that fails, make a 2-bar cell, slow until clean, add 4 BPM, stop before it sheds notes.",
    "A mistake practised three times is a practised mistake. The loop must be the correct version."],
  ["vy-mu-mark-the-part", "Craft", "Pencil is an instrument",
    "Breaths, fingerings, a reminder of a sneaky key sig. A clean part at the concert is a risk. Photocopy legalities sit with your teacher; your markings sit with you.",
    "Real musicians memorise and never write. Pencil is for beginners and cowards.",
    "Mark the thing you missed twice. Use a code you can read under lights. Erase when the publisher requires a return.",
    "A borrowed part with someone else’s wrong fingering is a trap. Check."],
  ["vy-mu-long-tone", "Craft", "A long tone is a lab for air, not a boredom exam",
    "Wind and brass: pitch, swell, a tuner, a drone. Strings: a slow bow that does not wobble. You are training the boring excellence that fast notes hide in.",
    "Long tones waste practice. Only run the hard licks. Tone is luck and equipment.",
    "Set a drone, play one note, match, then a fifth. Stop when the sound is a choice not a leak.",
    "A tuner’s green light with a ugly timbre is a half win. Ears after the light."],
  ["vy-mu-record-yourself", "Craft", "A take on your phone is a more honest teacher than your hope",
    "You cannot hear the balance from inside the bell. One recording a week of the hard eight bars. Cringe, then a list of two fixes, not a personality crisis.",
    "Recording is for influencers. Practice is a private myth. Also: only post the perfect take.",
    "Record, listen once with a pencil, fix one thing, rerecord. Do not live in the waveform.",
    "A metronome in the recording tells you if you rushed the easy bars. That is the usual crime."],
  ["vy-mu-full-score-once", "Craft", "Following a full score once is a map of other people’s jobs",
    "Form, cues, a transposition, where the tune goes when you rest. Pianists who only know their stave will smash a chamber entry. Players should visit the conductor’s view.",
    "Your part is the piece. Other staves are decoration for the conductor’s ego.",
    "Follow a recording with the full score once. Pencil a cue from another instrument before your entry.",
    "A transposing part that you ‘hear in C’ wrongly will make your cue a surprise. Know concert pitch of your entry."],
  ["vy-mu-instrument-care", "Craft", "A swab and a case are technique",
    "Cork grease, a loosened bow, a drained trombone, a guitar on a stand that a dog can hit. Repair bills are a pedagogy. Never leave a instrument on a chair at interval as a habit.",
    "If it still makes a sound it does not need care. Maintenance is a shop upsell.",
    "Daily dry, weekly bits your teacher named, a case that actually latches. Name the sticky key before it becomes a concert.",
    "A cheap stick-on mute stored in the bell can wreck a trumpet. Storage is a design."],
  ["vy-mu-practice-plan", "Craft", "A practice plan is minutes with a job, not a mood that you sat near the case",
    "10 min long tones, 10 min the hard cell, 5 min the piece as music. A 90-minute noodle is a hobby. Goals you can tick beat ‘work on it’.",
    "Inspiration will tell you what to practise. If you are not inspired, skip. The muse is WHS.",
    "Write tomorrow’s three jobs tonight. Start with the thing you would otherwise skip.",
    "Distributed practice (little, often) beats a Sunday panic before the lesson. Memory research and music teachers agree for once."],
]);
