import { pack } from "../../pack.mjs";

export const SCIENCE_MORE = pack("science", [
  ["vy-s-heart-two-pumps", "Body systems", "The heart is two pumps in one bag",
    "Right side sends blood to the lungs; left side sends it to the body. Mixing those jobs is a congenital emergency, not a personality. Valves stop backflow.",
    "Blood goes heart → body → lungs → heart as one simple loop, because diagrams are circles.",
    "Trace a red blood cell: body → vena cava → right atrium/ventricle → lungs → left atrium/ventricle → aorta. Colour the oxygen.",
    "The left wall is thicker because the body is a longer, higher-pressure job than the lungs."],
  ["vy-s-artery-vein-cap", "Body systems", "Arteries go away; veins come back; capillaries are the swap shop",
    "Arteries (usually oxygenated, except pulmonary) are high-pressure thick walls. Veins have valves in the limbs. Capillaries are one-cell thin for diffusion.",
    "Arteries are red and veins are blue because the blood changes crayon in the tube.",
    "Ask direction relative to the heart, then oxygen as a second question (pulmonary is the twist).",
    "A bleed that spurts is arterial until proven otherwise in first aid class. Pressure and a professional, not a crayon."],
  ["vy-s-alveoli-surface", "Body systems", "Alveoli are a surface-area trick for gas exchange",
    "Millions of tiny sacs, moist, close to capillaries. Oxygen in, carbon dioxide out, by diffusion — high to low concentration, not by lungs ‘sucking oxygen molecules by name’.",
    "Lungs blow oxygen into blood like a pump inflates a tyre. Pressure is the only story.",
    "Link surface area, thin barrier, and a concentration gradient. Smoking wrecks the surface; that is the health ticket.",
    "Asthma is often airways tightening before the alveoli. Different layer, same organ."],
  ["vy-s-neuron-one-way", "Body systems", "A neuron is a one-way electrochemical gossip",
    "Dendrites collect, axon sends. The synapse is a chemical gap, not a solder joint. Reflexes can skip the thoughtful bits of brain on purpose.",
    "Nerves are tiny rubber tubes with water in them. Cut one and thoughts leak out.",
    "Sketch sensory → inter → motor for a reflex arc. Then say why you still feel it a moment later (brain gets a copy).",
    "Myelin speeds the jump. Demyelinating disease is a later, serious file — not a PE excuse you invent."],
  ["vy-s-kidney-filter", "Body systems", "Kidneys filter, reabsorb, and osmoregulate — they are not only a wee factory",
    "Nephrons filter blood, then take back water and useful solutes. ADH adjusts water recovery. Urine is the leftover story, not the whole job.",
    "Kidneys store urine. The bladder is a rumour.",
    "Follow blood in, filtrate, reabsorption, urine out. Then caffeine/alcohol as ADH gossips if the class is there.",
    "Dialysis is a machine doing a filter job the nephrons lost. That is engineering plus a waitlist."],
  ["vy-s-liver-hub", "Body systems", "The liver is a chemical factory, not a blood bag",
    "It processes nutrients from the gut (portal vein), makes bile, handles some drugs, and stores glycogen. You cannot ‘detox’ it with a tea; it is the detox.",
    "The liver stores urine and also feelings. A cleanse weekend resets it.",
    "Name two jobs (bile, glycogen, protein synthesis) then a harm (alcohol, some paracetamol overdoses) as a respect, not a dare.",
    "Bile is stored in the gallbladder and helps emulsify fats. A liver vs gallbladder mix-up is a common diagram fail."],
  ["vy-s-skin-organ", "Body systems", "Skin is an organ: barrier, sensor, and a temperature radiator",
    "Epidermis vs dermis, melanin as UV context (not a morality), sweat and blood-flow for heat. Broken skin is an infection door.",
    "Skin is dead packaging. Only the organs inside count.",
    "List barrier, vitamin D neighbourhood, and thermoregulation. Then sun safety as the Australian clause.",
    "A burn is a skin-organ injury. Rule of nines is later first aid; cool water is the school move."],
  ["vy-s-hormone-broadcast", "Body systems", "Hormones are a broadcast; nerves are a telegram",
    "Endocrine glands dump messengers into blood. Slow, widespread, long-lasting compared with a reflex. Insulin vs glucagon is a glucose tug of war.",
    "Hormones are feelings. If you are sad, a gland is broken. Always.",
    "Name gland → hormone → target → effect. Then a feedback loop (thyroid, glucose) as a thermostat.",
    "Adrenaline is both a hormone and a neurotransmitter story depending on the release. The word is a neighbourhood, not a single postcode."],
  ["vy-s-particle-model", "Matter extras", "The particle model is a story: spaced, moving, attracting",
    "Solids vibrate in place; liquids slide; gases fly with big gaps. Temperature is average kinetic energy of those particles, not a fluid called ‘heat’ in the thermometer.",
    "Heat is a red liquid that flows from hot to cold. Particles are optional decoration.",
    "Draw the three states with spacing and motion arrows. Then diffusion as particles wandering into gaps.",
    "A compressed gas has the same particles in less volume — more collisions, higher pressure if T is similar. That is the bike pump."],
  ["vy-s-pressure-collisions", "Matter extras", "Gas pressure is collisions with the wall, not a squeeze juice",
    "More particles, faster particles, or a smaller container → more hits per second on the wall. A dented can in the fridge is pressure drop plus atmosphere winning.",
    "Pressure is the weight of the air sitting on you as a stack of bricks you can feel at all times as pain.",
    "Name the three levers (n, T, V) before you recite a formula. Then Boyle as a later costume if you have it.",
    "A sealed bottle on a hot bus can bulge. That is T up, not a new gas species being born."],
  ["vy-s-dissolve-not-melt", "Matter extras", "Dissolving is not melting; the solvent is a character",
    "Sugar in tea disappears into a solution; the tea is still a liquid mix. Melting is a solid becoming liquid of the same substance (ice → water) with no tea required.",
    "If it vanishes it melted. Sugar melts in tea. That is why tea is hot.",
    "Ask: new mixture with a solvent, or same substance changing state? Then recover the solute by evaporating if it was dissolve.",
    "Salt ‘melts’ ice on a path by making a solution with a lower freezing point. That idiom is chemistry, not fusion of NaCl."],
  ["vy-s-exothermic-surroundings", "Matter extras", "Exothermic heats the surroundings; the system’s chemical energy dropped",
    "Combustion, respiration, some acids+metals. Energy conserved: it moved. A bunsen is not ‘making energy’.",
    "Exothermic means the chemicals get hotter forever and also created joules from nothing.",
    "Feel (carefully) the surroundings. Sketch a profile that ends lower than it started. Catalyst still does not change that height difference.",
    "A hand-warmer is a designed exothermic. An instant ice pack is the other sign. Both are energy bookkeeping."],
  ["vy-s-rate-surface", "Matter extras", "Surface area speeds a reaction by offering more doorways",
    "Powdered marble fizzes faster in acid than a lump of the same mass. You did not change the chemical story, only the meeting rate. Temperature and concentration are other levers.",
    "Smash it to make more product in total. Rate and yield are the same word.",
    "Keep mass the same, change lump vs powder, time the fizz. Then say what you did not change (final CO₂ if acid is excess, in the simple story).",
    "A flour-mill explosion is surface area plus a flame. Chemistry class with a hazard poster."],
  ["vy-s-indicator-not-pH-number", "Matter extras", "An indicator is a colour costume, not a pH to two decimals",
    "Litmus is a blunt acid/base hat. Universal indicator is a rainbow map with a chart. A pH meter is a different tool with calibration.",
    "If it turned purple the pH is 7.000. Colours are numbers.",
    "Match the chart in the same lighting, then admit the band. Use a probe when the question needs a number.",
    "Colour-blind students need a probe or a buddy system. The experiment should still be possible."],
  ["vy-s-electrolysis-split", "Matter extras", "Electrolysis uses a current to force a non-spontaneous split",
    "Water can be split into H₂ and O₂ with energy in. The battery is doing work. This is not the same ticket as a metal displacing another in a beaker with no pack.",
    "Electricity is a kind of acid. Any solution will split into hydrogen because electricity is magic.",
    "Name cathode (reduction) and anode (oxidation) if you are at that rung, and the energy source. Do not collect hydrogen near a flame as a party.",
    "Molten salts vs aqueous solutions give different products (water can muscle in). The ion soup matters."],
  ["vy-s-atom-empty", "Matter extras", "An atom is mostly empty space with a dense nucleus",
    "Rutherford’s gold foil: most alpha particles passed, some bounced. Electrons occupy a fuzzy volume; almost all the mass is in the nucleus. Tables are still solid because of electromagnetic push, not because atoms are bricks stuffed with stuff.",
    "If atoms are empty, why does my hand not fall through the desk? Therefore the model is fake and atoms are filled like cake.",
    "Separate ‘empty of mass’ from ‘empty of fields’. The exclusion and charge keep you off the floor.",
    "Nuclear density is a later wow. Do not pack a nucleus-sized marble with the atom’s whole mass in your imagination and then forget the electrons’ job."],
  ["vy-s-solstice-daylength", "Earth & space", "A solstice is an extreme of day length, not ‘the Sun stopping the weather’",
    "June solstice: longest day in the north, shortest in Australia. December is our long-day party. Equinoxes are the roughly equal-day stops.",
    "Solstice means the hottest day. Temperature is a direct read of astronomy.",
    "Tie solstice to tilt and hemisphere, then admit weather lags (oceans). Hottest week is often after the longest day.",
    "Midnight sun is a polar solstice story. Sydney does not get one. Latitude is the gate."],
  ["vy-s-eclipse-geometry", "Earth & space", "An eclipse is a shadow lineup, not a monthly Moon snack",
    "Solar: Moon’s shadow on Earth. Lunar: Earth’s shadow on the Moon. New Moon vs full Moon are the phases that can, and still usually do not, because of a tilt in the Moon’s orbit.",
    "Every full Moon is a lunar eclipse. The Earth’s shadow is why we have phases.",
    "Draw Sun–Moon–Earth in a line, name which body is in the middle, then why it is rare (5° tilt).",
    "A blood Moon is scattered red sunlight in Earth’s shadow. It is still a lunar eclipse, not a new species of Moon."],
  ["vy-s-gravity-orbit", "Earth & space", "An orbit is a continuous fall that keeps missing the ground",
    "Newton’s cannonball: fast enough sideways and the Earth curves away. Gravity is still on. Astronauts ‘float’ because they are falling together, not because gravity switched off at a line in the sky.",
    "There is no gravity in space. That is why planets go in circles, from memory of the Big Bang.",
    "Name gravity as the inward pull and inertia as the sideways habit. Then ISS as a falling lab.",
    "The Moon is falling around Earth. It is also why tides are a later, related ticket — not ‘the Moon is a magnet for water’ as a full theory."],
  ["vy-s-star-life-mass", "Earth & space", "A star’s life story is mostly its mass",
    "Small stars sip hydrogen for a long time; massive stars burn fast and can die as supernovae. Our Sun is a middle story that will not explode as a Type II. The HR diagram is the map when you meet it.",
    "All stars end as black holes. The bigger the poster, the truer.",
    "Rank: brown dwarf neighbourhood, Sun-like, massive. Match death: white dwarf vs neutron star/black hole as a later rung.",
    "A nebula can be a birth cloud or a death leftover. The word is a weather of gas, not one object type."],
  ["vy-s-mineral-vs-rock", "Earth & space", "A mineral is a recipe; a rock is a mix of minerals (usually)",
    "Quartz is a mineral (SiO₂, crystalline). Granite is a rock (quartz + feldspar + mica). Coal is a messy organic rock story. Hardness (Mohs) is a mineral test.",
    "Rocks and minerals are synonyms. Granite is an element.",
    "Ask: definite chemistry and crystal? Mineral. Mixture with a history (igneous/sedimentary/metamorphic)? Rock.",
    "Obsidian is igneous glass — mineraloids sit on the edge. Definitions have a rim."],
  ["vy-s-fossil-sedimentary", "Earth & space", "Fossils prefer sedimentary rock because lava is a kiln",
    "Burial in sediment, then mineral swap, can keep a shape. Magma cooks the evidence. Index fossils help date a layer in a relative way; radiometric is a different clock on some rocks.",
    "Dinosaurs are found in granite because granite is old and strong.",
    "Name the rock type, then why a beach or river could bury, then why a volcano is a bad museum.",
    "A cast vs a trace fossil (footprint) is a behaviour vs a body. Both are evidence."],
  ["vy-s-greenhouse-select", "Earth & space", "Greenhouse gases are picky about which radiation they hug",
    "Visible sunlight in, Earth’s infrared out, some gases absorb that IR (CO₂, CH₄, H₂O). The blanket is selective, not a wool quilt in the sky you could photograph as a layer.",
    "The greenhouse effect is pollution, full stop, and also did not exist before cars. Also: it is a hoax. Pick a cartoon.",
    "Separate the natural greenhouse (habitability) from the enhanced one (extra forcing). Then water vapour as a feedback, CO₂ as a control knob we are turning.",
    "Venus is a greenhouse horror. Mars is a thin-atmosphere freeze. Earth is the middle story we live in."],
  ["vy-s-water-cycle-energy", "Earth & space", "The water cycle is a heat engine with a gravity assist",
    "Evaporation costs energy (from the Sun); condensation pays it back (clouds can heat). Gravity runs the rivers. It is not a mill that makes extra water.",
    "Water is created in clouds and destroyed when it rains. The cycle is a birth-death.",
    "Follow a molecule: ocean → vapour → cloud → rain → catchment → river → ocean. Count the energy at evaporate vs condense.",
    "Groundwater is a slow, hidden limb of the same cycle. A bore is not a magic new ocean."],
]);
