import { pack } from "../../pack.mjs";

export const TECH_MORE = pack("tech", [
  ["vy-t-pcl-postscript", "Printers & peripherals", "PCL and PostScript are languages, not paper sizes",
    "PCL is HP’s page description habit; PostScript is Adobe’s programmable page. A driver speaking the wrong dialect can dump raw code on paper or stall in a queue.",
    "If the printer prints at all, the language does not matter. Paper is paper.",
    "Match the driver to the engine’s advertised PDL, or use a standard job (IPP/AirPrint) that negotiates. Test a PDF, not only Notepad.",
    "A ‘generic / text only’ driver is a last resort for a till docket, not a colour design suite."],
  ["vy-t-fuser-not-toner", "Printers & peripherals", "A fuser melts; toner is just powder until then",
    "Laser toner sits as dust until the fuser’s heat and pressure melt it into the fibre. Smears that rub off are often a tired fuser, not an empty cartridge.",
    "If the print is pale, turn the heat up in Windows. Darkness is a slider, not chemistry.",
    "Print a diagnostics page, check the fuser kit’s page count, and do not ‘fix’ wipe-off toner with a darker driver setting.",
    "A jam in the fuser can bake a sheet into a souvenir. Kill power, wait for cool, then follow the orange handles."],
  ["vy-t-drum-vs-cartridge", "Printers & peripherals", "The drum is a wear part with its own count",
    "Many engines split toner from the photoconductor drum. Streaks that survive a cartridge swap are often the drum or a transfer belt, not ‘Windows colour management’.",
    "Toner and drum are the same bottle. If one is in, the other is immortal.",
    "Read the supplies menu: toner %, drum pages, fuser kit. Replace the part whose life actually ended.",
    "A ‘starter’ cartridge is short on purpose. That is a supply chain, not a broken new printer."],
  ["vy-t-ipp-airprint", "Printers & peripherals", "AirPrint is a protocol hat, not a Windows INF",
    "IPP Everywhere and AirPrint let a phone print without a vendor CD from 2011. The printer must advertise the service on the LAN, and mDNS/Bonjour has to survive the VLAN.",
    "Install the full 400 MB suite so a phone can print. Phones use Win32 drivers.",
    "Confirm the printer is on the same L2/mDNS island, IPP is on, and you are not isolating clients from printers ‘for security’ without a print VLAN plan.",
    "A guest SSID with client isolation will not AirPrint to a LAN printer. That is a fence, not a dying ink sponge."],
  ["vy-t-duplex-path", "Printers & peripherals", "Duplex is a second paper path, not a checkbox miracle",
    "A duplex unit flips the sheet through extra rollers. Jams that only happen on two-sided jobs live in that path, or in paper that is too heavy for the curve.",
    "If duplex is ticked, the printer will always print two sides, even with a straight-through rear door open.",
    "Run a one-sided test, then duplex. Check weight specs and close the rear door if you actually want the flip.",
    "A ‘print on both sides’ PDF that is already imposed can duplex into a scrambled book. Pre-imposition plus hardware duplex is a double flip."],
  ["vy-t-label-thermal", "Printers & peripherals", "Direct thermal fades; transfer is a ribbon",
    "Direct-thermal labels darken with heat and sunlight and then ghost. Thermal-transfer uses a ribbon and lasts on a warehouse shelf. Mixing media is how a ‘new printer’ looks broken.",
    "Any sticky label in a laser is fine. The fuser likes glue as a snack.",
    "Match media to the printhead type. Never send adhesive sheets through a laser fuser unless the stock is rated for it.",
    "A faded shipping label after a week on a sunny dock is chemistry, not a Windows font."],
  ["vy-t-hid-wedge-scan", "Printers & peripherals", "A barcode scanner is a keyboard in a trench coat",
    "HID wedge scanners type digits wherever the cursor sits, then often Enter. A mis-aimed scan into a password box is a login incident, not a ‘broken scan’.",
    "Scanners talk a secret retail protocol. Focus the wrong window and the computer will refuse the barcode as invalid hardware.",
    "Click the field first. Prefix/suffix programming is in the scanner’s cheat-sheet barcodes, not in Word.",
    "A USB COM-port scanner needs a driver and a listener app. HID wedge needs neither, which is why it is also a footgun."],
  ["vy-t-usbc-pd-dock", "Printers & peripherals", "A dock’s wattage is a pie, not a slogan",
    "A 65 W dock that also drives two 4K panels and a bus-powered disk may starve the laptop. PD, DisplayPort Alt Mode, and downstream USB all share a budget.",
    "If it is USB-C it will charge, display, and power a hub at full tilt. The C is a promise.",
    "Add the laptop’s required PD, the displays’ appetite, and bus power. Then read the dock’s passthrough number, not the wall-brick’s.",
    "A charge-only cable in a video dock is a black screen with a full battery. Alt Mode is pins, not optimism."],
  ["vy-t-laps-random", "Security extras", "LAPS exists because shared local admin is a skeleton key",
    "A common local-admin password on every PC is a lateral-movement gift. LAPS (or the cloud cousin) randomises and stores the password in a directory the helpdesk can retrieve.",
    "One easy local-admin password is friendlier for the shop and therefore safer. Attackers hate convenience.",
    "Deploy randomised local admin, restrict who can read the attribute, and stop documenting ‘Password1’ in a shared wiki.",
    "A GPO that also creates a second local admin called Support with a static password undoes the whole play."],
  ["vy-t-motw-macro", "Security extras", "Mark of the Web is why the yellow bar exists",
    "Files from the internet carry a Zone.Identifier. Office’s Protected View and macro blocks are that mark doing a job. Unblocking ‘so the invoice works’ is a policy decision.",
    "If a spreadsheet asks to enable content, the sender is professional. Yellow bars are for amateurs.",
    "Leave MOTW on. Teach people to re-request a clean file from a known person, not to unblock as a reflex.",
    "A zip can hide MOTW depending on how it was saved. Nested archives are a favourite costume."],
  ["vy-t-password-expiry", "Security extras", "Forced expiry is theatre if the next one is Summer2025!",
    "NIST and ACSC-adjacent guidance has cooled on frequent expiry. It trains incrementing and reuse. Length, uniqueness, and breach rotation beat a 30-day carnival.",
    "Change every password every Friday so attackers never catch up. Memory is a security control.",
    "Prefer long unique secrets in a manager, MFA, and rotate on evidence of compromise — not on a folk calendar.",
    "A 90-day policy plus a 8-character maximum is how you get P@ssw0rd3. The policy wrote the password."],
  ["vy-t-admin-share-c", "Security extras", "C$ is a convenience that is also a hallway",
    "Administrative shares (C$, ADMIN$) exist for management. On a flat LAN with local-admin reuse they become a copy-paste worm highway.",
    "Hidden shares with a $ are invisible to hackers because of the dollar. Naming is encryption.",
    "Kill unused admin shares or fence them with firewall + LAPS + no shared local admin. Manage via a jump host if you can.",
    "A ‘we need C$ for the old backup tool’ ticket is how 2008 never left the building."],
  ["vy-t-restore-point", "OS extras", "A restore point is a registry time machine, not a backup",
    "System Restore snapshots some system files and the registry. It will not resurrect Tuesday’s vanished thesis from Documents. Volume Shadow Copy is a cousin, not a 3-2-1 plan.",
    "Restore point means every file on the disk goes back a week. Click and relax.",
    "Use Restore for a bad driver/update. Use real backups for data. Say the difference out loud on the ticket.",
    "Restore points vanish on a disk-full or a policy. They are not a substitute for File History or a proper image."],
  ["vy-t-tz-dualboot", "OS extras", "Dual-boot clocks fight about UTC",
    "Windows traditionally stores local time in the RTC; Linux/macOS often store UTC. Dual-boot then jumps an hour each way, or a whole timezone after daylight saving.",
    "If the clock is wrong, the CMOS battery is dead. Always. Dual-boot is irrelevant.",
    "Pick one convention (Windows registry RealTimeIsUniversal, or Linux local rtc) and set both OSes to match. Then NTP.",
    "Kerberos and TLS get spicy when the clock is 24 h off. A ‘cannot log on’ after a Linux boot can be time, not a password."],
  ["vy-t-roaming-profile", "OS extras", "A roaming profile is a suitcase that can explode",
    "Roaming copies AppData habits across PCs. A bloated profile makes logon a coffee break and can corrupt if the share dies mid-write.",
    "Roaming means the user’s files live in the cloud now, so local disks can be wiped as a greeting.",
    "Folder-redirection for Documents, FSLogix or similar for VDI, and keep classic roaming thin. Do not roam a 12 GB Outlook OST.",
    "A ‘temp profile’ logon is often a share permission or a locked ntuser.dat, not a new PC curse."],
  ["vy-t-win-sandbox", "OS extras", "Windows Sandbox is a disposable room, not an antivirus",
    "Sandbox spins a clean, throwaway Windows. Close the window and the mess dies. It is for opening a dodgy installer, not for replacing Defender on the host.",
    "If Sandbox is on, the host cannot get malware. Virtualisation is a force field.",
    "Use it to inspect a file, then still scan and still not paste secrets into the guest as a habit.",
    "Sandbox needs virtualisation enabled. A BIOS that hid VT-x will just refuse, which is a firmware ticket, not a Windows feature off by mood."],
  ["vy-t-fn-lock-keys", "Mobile extras", "Fn Lock is why the F-keys became volume",
    "Many laptops default function keys to brightness/volume. Fn Lock (or an Esc glyph) flips the layer. A ‘F5 does not refresh’ ticket is often this, not a dying keyboard.",
    "If F5 does not refresh, reinstall Chrome. Function keys are a browser setting.",
    "Toggle Fn Lock, check the BIOS ‘Action keys’ option, and test in Notepad so a web page cannot confuse you.",
    "An external keyboard still sends F5. That split is how you prove the laptop’s layer, not Windows."],
  ["vy-t-usbc-dp-alt", "Mobile extras", "USB-C video is Alt Mode, not any C cable",
    "DisplayPort Alt Mode needs the right pins and often an e-marked cable. Charge-only leads, and some cheap hubs, will power a laptop and still show no desktop.",
    "Any USB-C to HDMI dongle works on any USB-C hole. SuperSpeed logos are jewellery.",
    "Check whether the port is marked DP/Thunderbolt, try a known-good cable, and do not condemn the GPU before the cable.",
    "Thunderbolt docks can need a firmware and a specific port. The left-side C on some ultrabooks is charge-only. Read the silkscreen."],
  ["vy-t-oem-unlock", "Mobile extras", "OEM unlock is a bootloader door with a warranty price",
    "Android OEM unlocking lets you flash a custom image. It wipes the device, can trip Knox/SafetyNet-style flags, and is not ‘a faster phone’ by itself.",
    "Unlocking the bootloader is the same as removing the SIM PIN. Both are phone passwords.",
    "Say the wipe and the warranty/attestation cost out loud before you tick the developer switch. Carrier-locked units may grey it out on purpose.",
    "A ‘fastboot flashing unlock’ on the wrong device is a brick story. Follow that model’s documented path only."],
  ["vy-t-find-my-network", "Mobile extras", "Find My is a crowd of radios, not a GPS implant",
    "Apple’s Find My (and Android’s network cousins) piggyback other people’s Bluetooth to report a sleeping device. No crowd, thick walls, and a dead battery still lose you.",
    "Find My uses a secret satellite in every iPhone. If it is on, the location is exact to the centimetre, underground.",
    "Enable the network feature before the loss, keep a charge habit, and treat a last-seen pin as a clue, not a court exhibit.",
    "Activation Lock after a Find My mark is why a second-hand phone can be a brick. Proof of purchase beats a forum bypass."],
]);
